### ISSUE TITLE
Uncaught RuntimeError: function signature mismatch

### ISSUE THREAD

**Issue by linuxaged** [emscripten-core/emscripten#10082]
emsdk version: 1.39.4
platform: Windows 10

build flags:
```
  FLAGS = -Wno-warn-absolute-paths --js-opts 0 -g4
  LINK_FLAGS = -s WASM=1 -O3 --llvm-lto 1   -s USE_WEBGL2=1 -s TOTAL_MEMORY=64MB -s ASSERTIONS=2 -s ALLOW_MEMORY_GROWTH=1 -s SAFE_HEAP=1 -s ALIASING_FUNCTION_POINTERS=0
```

Call stack:
```
Uncaught RuntimeError: function signature mismatch
    at wasm-function[1463]:0x8b9b6
    at wasm-function[1530]:0x912f3
    at Module.dynCall_ii (http://localhost:8080/SmileStudio.js:1:180058)
    at dynCall (http://localhost:8080/SmileStudio.js:1:7594)
    at drawEvent (http://localhost:8080/SmileStudio.js:1:23228)
```
the `drawEvent()`:
```
var ASM_CONSTS = {
  11821285: function($0) {var name = UTF8ToString($0); return typeof process !== 'undefined' && name in process.env ? allocate(intArrayFromString(process.env[name]), 'i8', ALLOC_NORMAL) : 0;},  
 11824175: function() {var element = Module['keyboardListeningElement'] || document; if(element === document) return 1; if(element === window) return 2; if('id' in element) return allocate(intArrayFromString(element.id), 'i8', ALLOC_NORMAL); return 0;},  
 11824503: function($0, $1) {var drawEvent = function() { var id = window.requestAnimationFrame(drawEvent); if(!dynCall('ii', $0, [$1])) { window.cancelAnimationFrame(id); } }; window.requestAnimationFrame(drawEvent);}
};
```
the `dynCall_ii `
```
var dynCall_ii = Module["dynCall_ii"] = function() {
  assert(runtimeInitialized, 'you need to wait for the runtime to be ready (e.g. wait for main() to be called)');
  assert(!runtimeExited, 'the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)');
  return Module["asm"]["dynCall_ii"].apply(null, arguments)
};
```

i'm not sure it's a emscripten bug or a application error, how to debug the error like this?

**Comment by linuxaged** [comment]
fixed. i used the wrong main function, it should be
```
#define MAGNUM_EMSCRIPTENAPPLICATION_MAIN(className)                        \
    namespace { Corrade::Containers::Pointer<className> emscriptenApplicationInstance ; } \
    int main(int argc, char** argv) {                                       \
        emscriptenApplicationInstance.reset(new className{{argc, argv}});   \
        return emscriptenApplicationInstance->exec();                       \
    }
```
