### ISSUE TITLE
Binaryen version check throws an exception

### ISSUE THREAD

**Issue by Akaricchi** [emscripten-core/emscripten#10239]
I realize I probably have an outdated Binaryen, but this should exit gracefully.

```
 % EMCC_DEBUG=1 /data/webshit/emroot/emcc  -o koishi.js 'koishi@exe/koishi_test.c.o' -g src/libkoishi.a -s ASYNCIFY
shared:DEBUG: EM_CONFIG is located in /data/webshit/emsdk/.emscripten
shared:DEBUG: JAVA not defined in /data/webshit/emsdk/.emscripten, using "java"
cache:DEBUG: PID 28431 acquiring multiprocess file lock to Emscripten cache at /data/webshit/emsdk/.emscripten_cache
cache:DEBUG: done
cache:DEBUG: PID 28431 released multiprocess file lock to Emscripten cache at /data/webshit/emsdk/.emscripten_cache
shared:DEBUG: check tells us to use wasm backend
emcc:WARNING: invocation: /data/git/emscripten/emcc.py -o koishi.js koishi@exe/koishi_test.c.o -g src/libkoishi.a -s ASYNCIFY  (in /data/git/koishi/build/emscripten)
shared:DEBUG: successfully executed /opt/llvm/bin/clang++ --version
root:DEBUG: Checking JS engine ['/data/webshit/emsdk/node/12.9.1_64bit/bin/node']
shared:DEBUG: successfully executed /data/webshit/emsdk/node/12.9.1_64bit/bin/node --version
shared:DEBUG: successfully executed /opt/llvm/bin/llc --version
shared:INFO: (Emscripten: Running sanity checks)
shared:DEBUG: successfully executed java -version
emcc:DEBUG: compiling to bitcode
emcc:DEBUG: emcc step "parse arguments and setup" took 0.12 seconds
cache:DEBUG: PID 28431 acquiring multiprocess file lock to Emscripten cache at /data/webshit/emsdk/.emscripten_cache/wasm-obj
cache:DEBUG: done
emcc:DEBUG: using object file: koishi@exe/koishi_test.c.o
emcc:DEBUG: using static library: src/libkoishi.a
shared:DEBUG: successfully executed /opt/llvm/bin/llvm-nm --print-armap src/libkoishi.a
emcc:DEBUG: emcc step "compile inputs" took 0.00 seconds
emcc:DEBUG: emcc step "process inputs" took 0.00 seconds
shared:DEBUG: executed /opt/llvm/bin/llvm-nm /data/git/koishi/build/emscripten/koishi@exe/koishi_test.c.o
shared:DEBUG: executed /opt/llvm/bin/llvm-nm /data/git/koishi/build/emscripten/src/libkoishi.a
system_libs:DEBUG: including libc (libc.a)
system_libs:DEBUG: including libcompiler_rt (libcompiler_rt.a)
system_libs:DEBUG: including libc-wasm (libc-wasm.a)
system_libs:DEBUG: including libmalloc (libdlmalloc-debug.a)
system_libs:DEBUG: including libpthread (libpthread_stub.a)
system_libs:DEBUG: including libc_rt_wasm (libc_rt_wasm.a)
system_libs:DEBUG: including libsockets (libsockets.a)
emcc:DEBUG: emcc step "calculate system libraries" took 0.06 seconds
emcc:DEBUG: linking: ['koishi@exe/koishi_test.c.o', 'src/libkoishi.a', '-L/data/git/emscripten/system/local/lib', '-L/data/git/emscripten/system/lib', '-L/data/webshit/emsdk/.emscripten_cache/wasm-obj', '/data/webshit/emsdk/.emscripten_cache/wasm-obj/libc.a', '/data/webshit/emsdk/.emscripten_cache/wasm-obj/libcompiler_rt.a', '/data/webshit/emsdk/.emscripten_cache/wasm-obj/libc-wasm.a', '/data/webshit/emsdk/.emscripten_cache/wasm-obj/libdlmalloc-debug.a', '/data/webshit/emsdk/.emscripten_cache/wasm-obj/libpthread_stub.a', '/data/webshit/emsdk/.emscripten_cache/wasm-obj/libc_rt_wasm.a', '/data/webshit/emsdk/.emscripten_cache/wasm-obj/libsockets.a']                                                               
shared:DEBUG: successfully executed /opt/llvm/bin/wasm-ld -o /tmp/emscripten_temp/koishi.wasm --allow-undefined --lto-O0 koishi@exe/koishi_test.c.o src/libkoishi.a -L/data/git/emscripten/system/local/lib -L/data/git/emscripten/system/lib -L/data/webshit/emsdk/.emscripten_cache/wasm-obj /data/webshit/emsdk/.emscripten_cache/wasm-obj/libc.a /data/webshit/emsdk/.emscripten_cache/wasm-obj/libcompiler_rt.a /data/webshit/emsdk/.emscripten_cache/wasm-obj/libc-wasm.a /data/webshit/emsdk/.emscripten_cache/wasm-obj/libdlmalloc-debug.a /data/webshit/emsdk/.emscripten_cache/wasm-obj/libpthread_stub.a /data/webshit/emsdk/.emscripten_cache/wasm-obj/libc_rt_wasm.a /data/webshit/emsdk/.emscripten_cache/wasm-obj/libsockets.a --import-memory --import-table -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --export __wasm_call_ctors --export __data_end --export main --export malloc --export free --export setThrew --export __errno_location --export fflush --export emscripten_builtin_memalign --export memalign --export emscripten_builtin_free -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024            
emcc:DEBUG: emcc step "link" took 0.03 seconds
emcc:DEBUG: LLVM => JS
cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "/data/webshit/emsdk/.emscripten_cache/wasm-obj/generated_struct_info.json" for subsequent builds)
gen_struct_info: Generating C code... /tmp/tmpkSRH2F.c
gen_struct_info: Compiling generated code...
gen_struct_info: ['/usr/bin/python', '/data/git/emscripten/emcc.py', '-D_GNU_SOURCE', '-s', 'BINARYEN=1', '-o', '/tmp/tmphQLigt.js', '/tmp/tmpkSRH2F.c', '-s', 'BOOTSTRAPPING_STRUCT_INFO=1', '-s', 'WARN_ON_UNDEFINED_SYMBOLS=0', '-O0', '--js-opts', '0', '--memory-init-file', '0', '-s', 'SINGLE_FILE=1', '-Wno-format']
shared:DEBUG: EM_CONFIG is located in /data/webshit/emsdk/.emscripten
shared:DEBUG: JAVA not defined in /data/webshit/emsdk/.emscripten, using "java"
shared:DEBUG: check tells us to use wasm backend
emcc:WARNING: invocation: /data/git/emscripten/emcc.py -D_GNU_SOURCE -s BINARYEN=1 -o /tmp/tmphQLigt.js /tmp/tmpkSRH2F.c -s BOOTSTRAPPING_STRUCT_INFO=1 -s WARN_ON_UNDEFINED_SYMBOLS=0 -O0 --js-opts 0 --memory-init-file 0 -s SINGLE_FILE=1 -Wno-format  (in /data/git/koishi/build/emscripten)                                                                                                                                                                                              
shared:DEBUG: successfully executed /opt/llvm/bin/clang++ --version
root:DEBUG: Checking JS engine ['/data/webshit/emsdk/node/12.9.1_64bit/bin/node']
shared:DEBUG: successfully executed /data/webshit/emsdk/node/12.9.1_64bit/bin/node --version
shared:DEBUG: successfully executed /opt/llvm/bin/llc --version
shared:INFO: (Emscripten: Running sanity checks)
shared:DEBUG: successfully executed java -version
emcc:DEBUG: compiling to bitcode
emcc:DEBUG: emcc step "parse arguments and setup" took 0.12 seconds
emcc:DEBUG: compiling source file: /tmp/tmpkSRH2F.c
shared:DEBUG: successfully executed /opt/llvm/bin/clang -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=6 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/data/git/emscripten/system/include/libcxx -Xclang -isystem/data/git/emscripten/system/lib/libcxxabi/include -Xclang -isystem/data/git/emscripten/system/include/compat -Xclang -isystem/data/git/emscripten/system/include -Xclang -isystem/data/git/emscripten/system/include/libc -Xclang -isystem/data/git/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/data/git/emscripten/system/local/include -Xclang -isystem/data/webshit/emsdk/.emscripten_cache/wasm-obj/include -D_GNU_SOURCE -O0 -Wno-format -DEMSCRIPTEN /tmp/tmpkSRH2F.c -Xclang -isystem/data/git/emscripten/system/include/SDL -c -o /tmp/emscripten_temp/tmpkSRH2F_0.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr
emcc:DEBUG: emcc step "compile inputs" took 0.23 seconds
emcc:DEBUG: emcc step "process inputs" took 0.00 seconds
emcc:DEBUG: emcc step "calculate system libraries" took 0.00 seconds
emcc:DEBUG: linking: ['/tmp/emscripten_temp/tmpkSRH2F_0.o', '-L/data/git/emscripten/system/local/lib', '-L/data/git/emscripten/system/lib', '-L/data/webshit/emsdk/.emscripten_cache/wasm-obj']
shared:DEBUG: successfully executed /opt/llvm/bin/wasm-ld -o /tmp/emscripten_temp/tmphQLigt.wasm --allow-undefined --lto-O0 /tmp/emscripten_temp/tmpkSRH2F_0.o -L/data/git/emscripten/system/local/lib -L/data/git/emscripten/system/lib -L/data/webshit/emsdk/.emscripten_cache/wasm-obj --import-memory --import-table -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --strip-debug --export __wasm_call_ctors --export __data_end --export main --export malloc --export free --export setThrew --export __errno_location --export fflush -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024
emcc:DEBUG: emcc step "link" took 0.01 seconds
emcc:DEBUG: LLVM => JS
shared:DEBUG: saving debug copy emcc-0-base.wasm
shared:DEBUG: successfully executed /home/akari/git/binaryen/build/bin/wasm-emscripten-finalize --version
Traceback (most recent call last):
  File "/data/git/emscripten/emcc.py", line 3768, in <module>
    sys.exit(run(sys.argv))
  File "/data/git/emscripten/emcc.py", line 2273, in run
    final = do_emscripten(final, shared.replace_or_append_suffix(target, '.mem'))
  File "/data/git/emscripten/emcc.py", line 464, in do_emscripten
    emscripten.run(infile, outfile, memfile)
  File "/data/git/emscripten/emscripten.py", line 2821, in run
    return temp_files.run_and_clean(lambda: emscripter(
  File "/data/git/emscripten/tools/tempfiles.py", line 105, in run_and_clean
    return func()
  File "/data/git/emscripten/emscripten.py", line 2822, in <lambda>
    infile, outfile_obj, memfile, shared.NODE_JS, temp_files, shared.DEBUG)
  File "/data/git/emscripten/emscripten.py", line 2210, in emscript_wasm_backend
    metadata = finalize_wasm(temp_files, infile, outfile, memfile, DEBUG)
  File "/data/git/emscripten/emscripten.py", line 2372, in finalize_wasm
    stdout=subprocess.PIPE)
  File "/data/git/emscripten/tools/shared.py", line 2968, in run_binaryen_command
    cmd = [os.path.join(Building.get_binaryen_bin(), tool)] + args
  File "/data/git/emscripten/tools/shared.py", line 2962, in get_binaryen_bin
    Building.check_binaryen(rtn)
  File "/data/git/emscripten/tools/shared.py", line 2950, in check_binaryen
    version = output.split()[2]
IndexError: list index out of range
FAIL: Compilation failed!
cache:DEBUG: PID 28431 released multiprocess file lock to Emscripten cache at /data/webshit/emsdk/.emscripten_cache/wasm-obj
```

**Comment by kripken** [comment]
Thanks, I noticed this locally too. Fix in #10244
