### ISSUE TITLE
std::uncaught_exceptions not working in 1.38 / 1.39

### ISSUE THREAD

**Issue by kunitoki** [emscripten-core/emscripten#10356]
Before 1.38 i used to implement a home rolled c++17 `std::uncaught_exceptions` (targeting c++11 codebases) like this:

```
inline int uncaught_exceptions() noexcept
{
    return EM_ASM_INT({
        var uncaught_exceptions = 0;

        for (var ptr in EXCEPTIONS.infos)
        {
            if (EXCEPTIONS.infos[ptr].caught && !EXCEPTIONS.infos[ptr].rethrown)
                continue;

            ++uncaught_exceptions;
        }

        return uncaught_exceptions;
    }, 0);
}
```

and it was working ok.

After switching to 1.38 i noticed `EXCEPTIONS` global is not present anymore, and apparently `__cxa_uncaught_exceptions` seems to be implemented now (that should be called by libcxx `std::uncaught_exceptions`): both using the former and the latter is returning the wrong number of exceptions now, and the code that was relying on uncaught_exceptions and was working before, is now not working at all.

Any ideas on what should i use as a working alternative to rely on `EXCEPTIONS` that also works on c++11 ?

**Comment by kunitoki** [comment]
ah i also found that i can access a global `__ZSt18uncaught_exceptionv` now which is a function, but it only return 0 or 1 as it is basically `std::uncaught_exception`, apparently there is no way to access `___exception_infos` in place of `EXCEPTIONS`

**Comment by kunitoki** [comment]
```
#include <exception>
#include <cassert>

#if defined(__EMSCRIPTEN__)
#include <emscripten.h>
#define EMSCRIPTEN_VERSION ((__EMSCRIPTEN_major__ * 10000) + (__EMSCRIPTEN_minor__ * 100) + __EMSCRIPTEN_tiny__)
#endif

int uncaught_exceptions()
{
#if defined(__EMSCRIPTEN__) && EMSCRIPTEN_VERSION < 13800
    return EM_ASM_INT(
    {
        var uncaught_exceptions = 0;

        try
        {
            for (var ptr in EXCEPTIONS.infos)
            {
                if (EXCEPTIONS.infos[ptr].caught && !EXCEPTIONS.infos[ptr].rethrown)
                    continue;

                ++uncaught_exceptions;
            }
        } catch(e) {
        }

        return uncaught_exceptions;
    }, 0);
#else
    return std::uncaught_exceptions();
#endif
}

struct exception_watcher
{
    exception_watcher(int& exceptions_seen)
        : exceptions_seen_(exceptions_seen)
    {
    }

    ~exception_watcher()
    {
        exceptions_seen_ = uncaught_exceptions();
    }

    int& exceptions_seen_;
};

struct throwing_destructor
{
    throwing_destructor(int& exceptions_seen)
        : exceptions_seen_(exceptions_seen)
    {
    }

    ~throwing_destructor()
    {
        try
        {
            exception_watcher watcher(exceptions_seen_);
            throw 1;
        }
        catch (...)
        {
            assert(uncaught_exceptions() == 1);
        }
    }

    int& exceptions_seen_;
};

int main()
{
    // one exception
    {
        int x = 0;

        try
        {
            exception_watcher watcher(x);
            throw 1;
        }
        catch (...)
        {
            assert(uncaught_exceptions() == 0);
        }

        assert(x == 1);
    }

    // two exceptions
    {
        int x = 0;

        try
        {
            throwing_destructor destructor(x);
            throw 1;
        }
        catch (...)
        {
            assert(uncaught_exceptions() == 0);
        }

        assert(x == 2);
    }

    return 0;
}
```

if i execute this code with `clang++ -std=c++17 main.cpp && ./a.out` i get no assert hits.

if i execute with emscripten 1.37 with `emcc -std=c++11 -s DISABLE_EXCEPTION_CATCHING=0 main.cpp && node a.out.js` i get no assert hits.

if i execute on 1.38 / 1.39 with `emcc -std=c++17 -s DISABLE_EXCEPTION_CATCHING=0 main.cpp && node a.out.js` i hit these:
```
Assertion failed: uncaught_exceptions() == 1, at: main.cpp,67,~throwing_destructor
Assertion failed: uncaught_exceptions() == 1, at: main.cpp,67,~throwing_destructor
exception thrown: abort(Assertion failed: uncaught_exceptions() == 1, at: main.cpp,67,~throwing_destructor) at Error
    at jsStackTrace (/Users/kunitoki/emscripten/a.out.js:1804:17)
    at stackTrace (/Users/kunitoki/emscripten/a.out.js:1821:16)
    at abort (/Users/kunitoki/emscripten/a.out.js:1577:44)
    at ___assert_fail (/Users/kunitoki/emscripten/a.out.js:1827:7)
    at wasm-function[777]:0x241e6
    at Module.dynCall_viiii (/Users/kunitoki/emscripten/a.out.js:5454:41)
    at invoke_viiii (/Users/kunitoki/emscripten/a.out.js:5279:5)
    at wasm-function[50]:0x2033
    at wasm-function[45]:0x1df7
    at Object.Module._main (/Users/kunitoki/emscripten/a.out.js:5340:33)
```

**Comment by kunitoki** [comment]
@sbc100 do you have any suggestion ?

**Comment by VirtualTim** [comment]
Can you try adding the `-fexceptions` compiler flag to the emcc build?

**Comment by kunitoki** [comment]
still not working
