### ISSUE TITLE
Module.locateFile is not working

### ISSUE THREAD

**Issue by chase-moskal** [emscripten-core/emscripten#10434]
hello friends, i'm the author of [webp-hero](https://github.com/chase-moskal/webp-hero), a polyfill that uses google's webp decoder clientside via emscripten

i have taken the emscripten build, and wrapped it into an es module at `/libwebp/dist/webp.js`, exporting the cwrap'd functions i need

however at runtime, emscripten is looking for `webp.wasm` and `webp.js.mem` at *the server root*, which is the wrong location, so requests are going to `/webp.wasm` when it should be to `/libwebp/dist/webp.wasm` -- so i need to instruct emscripten where to look

i thought using [Module.locateFile](https://emscripten.org/docs/api_reference/module.html#Module.locateFile) should be the solution:

```js
window.Module = {
  locateFile: url => {
    // never called :(
    console.log("LOCATE", url)
    debugger
    return `./path/${url}`
  }
}
// ... emscripten build ...
// then exporting what's needed
```

even though i can see the emscripten runtime ingesting this above configuration -- `locateFile` is not being called even one time -- and emscripten is still looking for the wrong paths

i noticed in the minified emscripten code, it's looking for things like `document.currentScript`, which i don't think is available within an es module? is this not working because i've wrapped the emscripten build into an es module? i mean, i've simply wrapped the output and exported the needed cwrap'd function..

is there any other way to influence how emscripten looks for files? or some way to get this working? is there a way to get emscripten to look for the files relative to the module, rather than at the server's root?

i have a webp-hero [commit](https://github.com/chase-moskal/webp-hero/tree/78193921eb94cae82f27c63f001d7899f421eaee) which demonstrates the issue after `sudo ./libwebp/build && npm install && npm start` then browsing to http://localhost:5000/esm?force

thanks,
:wave: chase

**Comment by VirtualTim** [comment]
I'm pretty sure the way you're meant to use locateFile is like:
```
let module_overrides = {
  locateFile: function(path) {  //sample implementation
    const baseURL = window.location.origin + window.location.pathname.substring(0, window.location.pathname.lastIndexOf( "/" ));
    return baseURL + '/a_folder/' + path;
  }
};
//then load the module, passing in module_overrides
Module(module_overrides).then(() => {
  console.log("loaded!");
});
```

**Comment by MarcelKlammer** [comment]
It's a scope issue. Change

```
var Module=typeof Module!=="undefined"?Module:{};
```

to

```
var Module=window.Module
```

in your function Webp() {}

**Comment by chase-moskal** [comment]
@VirtualTim, thanks very much for your help

following your advice, in [commit *"libwebp: add es6 cmake rules"*](https://github.com/chase-moskal/webp-hero/commit/41511db7f9ab191818fe5866e02161d6726fbea1) i've added these flags to CMakeLists.txt:

```
      -s EXPORT_ES6=1 \
      -s USE_ES6_IMPORT_META=1 \
      -s MODULARIZE=1 \
```

however, it doesn't work. strangely enough, not even a single byte is changed in the resulting emscripten output, as if the flags are being ignored. is there something incorrect about the way i'm adding these flags in CMakeLists.txt?

however in [commit *"fail: attempt to override Module.locateFile"*](https://github.com/chase-moskal/webp-hero/commit/da76d43b8816f2b505d60a79b76113cd94777c4d), i tried to put your module overrides advice to work -- however at runtime i got this error:

```
top level error: TypeError: Module is not a function
    at new Webp (webp.js:17)
    at new WebpMachine (webp-machine.ts:27)
    at main (esm?force:25)
    at esm?force:31
```

i'm not familiar with `Module` being a callable function -- i've only known to use the [weird cwrap function to "extract"](https://github.com/chase-moskal/webp-hero/blob/master/libwebp/source/wrapping-end.js.txt#L3) out the functions i need to expose. is there a more standard approach i should be investigating?

**Comment by chase-moskal** [comment]
@MarcelKlammer -- thanks for the advice. it freaks me out a little, because that's emscripten output i'd have to change with a find-and-replace, so my build could break anytime emscripten tweaks its output there -- but desperate times call for desperate measures, i might see if i can hack that in

**Comment by MarcelKlammer** [comment]
Nothing to hack here.

-s MODULARIZE=1

will put a function around that. You can choose the name of that function with

-s "EXPORT_NAME='brfv5Module'"

like WebpModule. Then build your function using that.

**Comment by chase-moskal** [comment]
@VirtualTim, @MarcelKlammer -- i really appreciate your helping me on this issue

following your advice, in [commit *"libwebp: add es6 cmake rules"*](https://github.com/chase-moskal/webp-hero/commit/6fdc55ee0457dcee5835c579ee860977a843fc29), i've added the following flags to my cmakelists:

```
-s MODULARIZE=1 \
-s EXPORT_ES6=1 \
-s EXPORT_NAME='Webp' \
```

however with these added flags, the build is now failing with this error:

```
[ 94%] Linking C executable webp_wasm.js
/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:2780
  throw err                                                                                                                               
  ^                                                                                                                                       

SyntaxError: 'import' and 'export' may only appear at the top level (76:6)                                                                
      import(e.data.urlOrBlob).then(function(Webp) {                                                                                      
      ^                                                                                                                                   

    at Parser.pp$4.raise (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:2778:13)                                 
    at Parser.pp$1.parseStatement (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:831:16)                         
    at Parser.pp$1.parseBlock (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:1145:23)                            
    at Parser.pp$1.parseStatement (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:825:34)
    at Parser.pp$1.parseIfStatement (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:965:26)
    at Parser.pp$1.parseStatement (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:814:31)
    at Parser.pp$1.parseBlock (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:1145:23)
    at Parser.pp$1.parseTryStatement (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:1041:21)
    at Parser.pp$1.parseStatement (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:818:32)
    at Parser.pp$1.parseBlock (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:1145:23) {
  pos: 3239,
  loc: Position { line: 76, column: 6 },
  raisedAt: 3245
}
shared:ERROR: '/work/emsdk/node/12.9.1_64bit/bin/node /work/emsdk/fastcomp/emscripten/tools/acorn-optimizer.js /work/libwebp/webp_js/webp_wasm.worker.js minifyWhitespace' failed (1)
make[2]: *** [CMakeFiles/webp_wasm.dir/build.make:88: webp_wasm.js] Error 1
make[1]: *** [CMakeFiles/Makefile2:226: CMakeFiles/webp_wasm.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
The command '/bin/bash -c cd /work/emsdk   && source ./emsdk_env.sh   && cd /work/libwebp/webp_js   && cmake -DWEBP_BUILD_WEBP_JS=ON     -DEMSCRIPTEN_GENERATE_BITCODE_STATIC_LIBRARIES=1     -DCMAKE_TOOLCHAIN_FILE=$EMSDK/fastcomp/emscripten/cmake/Modules/Platform/Emscripten.cmake     ../   && make' returned a non-zero code: 2
```

anybody have a hunch for what this might be about?

it looks like it's related to es module syntax, perhaps i'm missing another piece of configuration?

**Comment by chase-moskal** [comment]
to clarify the current situation, it looks to me like `Module.locateFile` won't work until i get `EXPORT_ES6` and `MODULARIZE` to work, right?

**Comment by VirtualTim** [comment]
`LocateFile` doesn't depend on `EXPORT_ES6` or `MODULARIZE`, but if if you're trying to make an ES6 module that's what you should be compiling with.

I'm not sure why your build is failing. I'm building an EXPORT_ES6 + MODULARIZE build with Emscripten 1.39.6, and I don't have that problem.

I suspect the problem was introduced by @juj here https://github.com/emscripten-core/emscripten/commit/9c48a508eacac4506e18cc27a27ac8bff405e025. Does 1.39.6 build for you?

[Also if it helps there's a live demo of an ES6 module + Pthreads build here.](https://demo-apollo.hexagongeospatial.com/erdas-iws/samples/ECWPWebAssembly/) (Chrome only unfortunately). I did have to polyfill dynamic module import inside a webworker using a [slightly modified version of shimport](https://github.com/Rich-Harris/shimport/issues/26). You may have to do the same.

**Comment by noahlam** [comment]
> @VirtualTim, @MarcelKlammer -- i really appreciate your helping me on this issue
> 
> following your advice, in [commit _"libwebp: add es6 cmake rules"_](https://github.com/chase-moskal/webp-hero/commit/6fdc55ee0457dcee5835c579ee860977a843fc29), i've added the following flags to my cmakelists:
> 
> ```
> -s MODULARIZE=1 \
> -s EXPORT_ES6=1 \
> -s EXPORT_NAME='Webp' \
> ```
> 
> however with these added flags, the build is now failing with this error:
> 
> ```
> [ 94%] Linking C executable webp_wasm.js
> /work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:2780
>   throw err                                                                                                                               
>   ^                                                                                                                                       
> 
> SyntaxError: 'import' and 'export' may only appear at the top level (76:6)                                                                
>       import(e.data.urlOrBlob).then(function(Webp) {                                                                                      
>       ^                                                                                                                                   
> 
>     at Parser.pp$4.raise (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:2778:13)                                 
>     at Parser.pp$1.parseStatement (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:831:16)                         
>     at Parser.pp$1.parseBlock (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:1145:23)                            
>     at Parser.pp$1.parseStatement (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:825:34)
>     at Parser.pp$1.parseIfStatement (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:965:26)
>     at Parser.pp$1.parseStatement (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:814:31)
>     at Parser.pp$1.parseBlock (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:1145:23)
>     at Parser.pp$1.parseTryStatement (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:1041:21)
>     at Parser.pp$1.parseStatement (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:818:32)
>     at Parser.pp$1.parseBlock (/work/emsdk/fastcomp/emscripten/tools/node_modules/acorn/dist/acorn.js:1145:23) {
>   pos: 3239,
>   loc: Position { line: 76, column: 6 },
>   raisedAt: 3245
> }
> shared:ERROR: '/work/emsdk/node/12.9.1_64bit/bin/node /work/emsdk/fastcomp/emscripten/tools/acorn-optimizer.js /work/libwebp/webp_js/webp_wasm.worker.js minifyWhitespace' failed (1)
> make[2]: *** [CMakeFiles/webp_wasm.dir/build.make:88: webp_wasm.js] Error 1
> make[1]: *** [CMakeFiles/Makefile2:226: CMakeFiles/webp_wasm.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
> The command '/bin/bash -c cd /work/emsdk   && source ./emsdk_env.sh   && cd /work/libwebp/webp_js   && cmake -DWEBP_BUILD_WEBP_JS=ON     -DEMSCRIPTEN_GENERATE_BITCODE_STATIC_LIBRARIES=1     -DCMAKE_TOOLCHAIN_FILE=$EMSDK/fastcomp/emscripten/cmake/Modules/Platform/Emscripten.cmake     ../   && make' returned a non-zero code: 2
> ```
> 
> anybody have a hunch for what this might be about?
> 
> it looks like it's related to es module syntax, perhaps i'm missing another piece of configuration?
> 
> in case it helps: here's my [Dockerfile](https://github.com/chase-moskal/webp-hero/blob/6fdc55ee0457dcee5835c579ee860977a843fc29/libwebp/Dockerfile) that runs the libwebp emscripten build -- and here's the [CMakeLists.txt](https://github.com/chase-moskal/webp-hero/blob/6fdc55ee0457dcee5835c579ee860977a843fc29/libwebp/source/CMakeLists.txt) i've modded to include the es6 flags

How do you solve this problem?  I got the same error.

**Comment by chase-moskal** [comment]
@noahlam — i simply have not solved it — i'm busy elsewhere so this is on my backburner for now

**Comment by chase-moskal** [comment]
i just tried again with emscripten `1.39.16`, and when i use `-s MODULARIZE=1 -s EXPORT_ES6=1` i get that same syntax error:

```
SyntaxError: 'import' and 'export' may only appear at the top level
```

**Comment by christian-valadez** [comment]
I'm getting this error when using ES6 as well.

**Comment by spectras** [comment]
Any news on this topic? The issue still exists.

Fwiw, here is what I analyzed so far.

In my case, Emscripten generates this glue code: [generated-by-emscripten.js](https://github.com/emscripten-core/emscripten/files/6617357/generated-by-emscripten.txt)

Relevant options:
- ENVIRONMENT=web
- EXPORT_ES6=1
- MODULARIZE=1

Pretty-printing and trimming the glue code to the relevant parts:
```js
var Module = (function() {
    var _scriptDir = import.meta.url;

    return (
        function(Module) {
            Module = Module || {};
            var Module = typeof Module !== "undefined" ? Module : {};
            // [...]
            var moduleOverrides = {};
            var key;
            for (key in Module) {
                if (Module.hasOwnProperty(key)) {
                    moduleOverrides[key] = Module[key]
                }
            }

            var scriptDirectory = "";
            function locateFile(path) {
                return scriptDirectory + path
            }

            // [...]
            for (key in moduleOverrides) {
                if (moduleOverrides.hasOwnProperty(key)) {
                    Module[key] = moduleOverrides[key]
                }
            }
            moduleOverrides = null;

            // [...]
            var wasmBinaryFile = "bct-render-service.wasm";
            if (!isDataURI(wasmBinaryFile)) {
                wasmBinaryFile = locateFile(wasmBinaryFile)     // <========= A
            }
            // [...]
            return Module.ready
        }
    );
})();
export default Module;
```
For reference, using as:
```js
import loadService from 'render-service';

const promise = loadService ( { locateFile: file => "/foobar.wasm" });  // actually foobar, trying to make it fail
```

Debugging shows that `locateFile` is properly set on `Module`. The problem is that  is ignored. The marked line above uses the internal implementation and completely disregards any `Module.locateFile` that may have been set.

**Comment by sbc100** [comment]
@RReverser has been working on this code recently.    The internal version of locateFile should defer to the external one:https://github.com/emscripten-core/emscripten/blob/ea6807db453460d2bea3cfad171acbd8e58ea263/src/shell.js#L144-L151

Can you see what your internal locateFile looks like?

**Comment by RReverser** [comment]
The issue is a lot older though, while my change only fixed a temporary breakage I introduced in 2.0.20. I wonder if there are several issues with similar symptoms here.

**Comment by sbc100** [comment]
> ```js
>             function locateFile(path) {
>                 return scriptDirectory + path
>             }
> ```

I'm curious how this could have ended up with the `if (Module['locateFile'])` check.   Are you setting `INCOMING_MODULE_JS_API` perhaps?

**Comment by simzer** [comment]
In case of somebody has difficulty following all the changes they make in their Emscripten options like me:
I had the same problem, that the internal `locateFile()` was generated without the call to the one from the module because I set this in my project previously: `-s INCOMING_MODULE_JS_API=[]`.
