### ISSUE TITLE
SDL2 caching appears broken? llvm-link.exe missing args

### ISSUE THREAD

**Issue by aardappel** [emscripten-core/emscripten#10473]
Just got this on my home machine:

```
C:\w\lobster\dev\emscripten>make -j12
emcc -O3 -DNDEBUG -s ASSERTIONS=0 --llvm-opts 3 --llvm-lto 1 -s WASM_OBJECT_FILES=0 -s DISABLE_EXCEPTION_CATCHING=0 -s USE_SDL=2 -s NO_EXIT_RUNTIME=1 -std=c++17 -Wall -pedantic -Wno-switch -Wno-array-bounds -Wno-gnu-anonymous-struct -Wno-nested-anon-types -I. -I../include -I../src -I../external/freetype/include -I../external/SDLMixer -I../external/imgui   -c -o ../src/audio.o ../src/audio.cpp
system_libs:INFO: retrieving port: sdl2 from https://github.com/emscripten-ports/SDL2/archive/version_18.zip
system_libs:INFO: unpacking port: sdl2
cache:INFO: generating port: libSDL2.bc... (this will be cached in "C:\Users\woute\.emscripten_cache\wasm-bc\libSDL2.bc" for subsequent builds)
llvm-link.exe: Not enough positional command line arguments specified!
Must specify at least 1 positional argument: See: C:/stuff/emsdk/upstream/bin\llvm-link.exe --help
Traceback (most recent call last):
  File "C:\stuff\emsdk\upstream\emscripten\emcc.py", line 3905, in <module>
    sys.exit(run(sys.argv))
  File "C:\stuff\emsdk\upstream\emscripten\emcc.py", line 2091, in run
    compile_source_file(i, input_file)
  File "C:\stuff\emsdk\upstream\emscripten\emcc.py", line 2073, in compile_source_file
    cmd = get_clang_command([input_file]) + ['-c', '-o', output_file]
  File "C:\stuff\emsdk\upstream\emscripten\emcc.py", line 2044, in get_clang_command
    args = system_libs.process_args(args, shared.Settings)
  File "C:\stuff\emsdk\upstream\emscripten\tools\system_libs.py", line 1794, in process_args
    args = port.process_args(Ports, args, settings, shared)
  File "C:\stuff\emsdk\upstream\emscripten\tools\ports\sdl2.py", line 105, in process_args
    get(ports, settings, shared)
  File "C:\stuff\emsdk\upstream\emscripten\tools\ports\sdl2.py", line 91, in get
    return [shared.Cache.get(libname, create, what='port')]
  File "C:\stuff\emsdk\upstream\emscripten\tools\cache.py", line 133, in get
    temp = creator()
  File "C:\stuff\emsdk\upstream\emscripten\tools\ports\sdl2.py", line 88, in create
    ports.create_lib(final, o_s)
  File "C:\stuff\emsdk\upstream\emscripten\tools\system_libs.py", line 1593, in create_lib
    create_lib(libname, inputs)
  File "C:\stuff\emsdk\upstream\emscripten\tools\system_libs.py", line 100, in create_lib
    shared.Building.link_to_object(inputs, libname)
  File "C:\stuff\emsdk\upstream\emscripten\tools\shared.py", line 1760, in link_to_object
    Building.link(linker_inputs, target)
  File "C:\stuff\emsdk\upstream\emscripten\tools\shared.py", line 2017, in link
    Building.link_llvm(actual_files, target)
  File "C:\stuff\emsdk\upstream\emscripten\tools\shared.py", line 1768, in link_llvm
    output = run_process(cmd, stdout=PIPE).stdout
  File "C:\stuff\emsdk\upstream\emscripten\tools\shared.py", line 181, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:/stuff/emsdk/upstream/bin\\llvm-link.exe', '-o', 'C:\\Users\\woute\\.emscripten_cache\\wasm-bc\\ports-builds\\sdl2\\libSDL2.bc']' returned non-zero exit status 1.
make: *** [../src/audio.o] Error 1
```

This is on Windows 10.
Had a super old emsdk, so zapped that dir, and deleted all emscripten related files/dirs in the user dir, then installed a fresh copy. Not sure if that is correct?

**Comment by sbc100** [comment]
If you build SDL2 explictly using embuilder does it also fail?

`$ ./embuilder.py  build --lto  sdl2`

**Comment by aardappel** [comment]
@sbc100 fails in exactly the same way.

I actually ran `python upstream\emscripten\embuilder.py build --lto sdl2` though I am guessing that doesn't matter.

**Comment by sbc100** [comment]
Strange..  Works for me here.

Can you try with EMCC_DEBUG=1.   Sadly it will be quite slow because this also disables parallelism.

On my system the command that builds libsdl2 is so large that it uses a response file:

```
shared:DEBUG: successfully executed /usr/local/google/home/sbc/dev/wasm/llvm-build/bin/llvm-link @/tmp/emscripten_4zo8zpn7.rsp
```

The contents of the response file looks like:

```
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/SDL.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/SDL_assert.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/SDL_dataqueue.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/SDL_error.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/SDL_hints.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/SDL_log.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/atomic/SDL_atomic.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/atomic/SDL_spinlock.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/audio/SDL_audio.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/audio/SDL_audiocvt.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/audio/SDL_audiodev.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/audio/SDL_audiotypecvt.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/audio/SDL_mixer.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/audio/SDL_wave.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/cpuinfo/SDL_cpuinfo.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/dynapi/SDL_dynapi.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/events/SDL_clipboardevents.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/events/SDL_dropevents.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/events/SDL_events.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/events/SDL_gesture.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/events/SDL_keyboard.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/events/SDL_mouse.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/events/SDL_quit.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/events/SDL_touch.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/events/SDL_windowevents.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/file/SDL_rwops.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/haptic/SDL_haptic.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/joystick/SDL_gamecontroller.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/joystick/SDL_joystick.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/libm/e_atan2.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/libm/e_log.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/libm/e_pow.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/libm/e_rem_pio2.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/libm/e_sqrt.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/libm/k_cos.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/libm/k_rem_pio2.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/libm/k_sin.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/libm/k_tan.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/libm/s_atan.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/libm/s_copysign.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/libm/s_cos.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/libm/s_fabs.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/libm/s_floor.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/libm/s_scalbn.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/libm/s_sin.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/libm/s_tan.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/power/SDL_power.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/render/SDL_d3dmath.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/render/SDL_render.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/render/SDL_yuv_sw.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/render/direct3d/SDL_render_d3d.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/render/direct3d11/SDL_render_d3d11.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/render/opengl/SDL_render_gl.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/render/opengl/SDL_shaders_gl.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/render/opengles/SDL_render_gles.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/render/opengles2/SDL_render_gles2.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/render/opengles2/SDL_shaders_gles2.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/render/psp/SDL_render_psp.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/render/software/SDL_blendfillrect.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/render/software/SDL_blendline.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/render/software/SDL_blendpoint.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/render/software/SDL_drawline.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/render/software/SDL_drawpoint.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/render/software/SDL_render_sw.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/render/software/SDL_rotate.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/sensor/SDL_sensor.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/stdlib/SDL_getenv.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/stdlib/SDL_iconv.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/stdlib/SDL_malloc.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/stdlib/SDL_qsort.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/stdlib/SDL_stdlib.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/stdlib/SDL_string.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/thread/SDL_thread.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/timer/SDL_timer.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_RLEaccel.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_blit.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_blit_0.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_blit_1.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_blit_A.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_blit_N.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_blit_auto.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_blit_copy.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_blit_slow.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_bmp.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_clipboard.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_egl.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_fillrect.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_pixels.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_rect.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_shape.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_stretch.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_surface.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_video.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/SDL_yuv.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/emscripten/SDL_emscriptenevents.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/emscripten/SDL_emscriptenframebuffer.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/emscripten/SDL_emscriptenmouse.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/emscripten/SDL_emscriptenopengles.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/emscripten/SDL_emscriptenvideo.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/audio/emscripten/SDL_emscriptenaudio.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/dummy/SDL_nullevents.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/dummy/SDL_nullframebuffer.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/dummy/SDL_nullvideo.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/video/yuv2rgb/yuv_rgb.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/audio/disk/SDL_diskaudio.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/audio/dummy/SDL_dummyaudio.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/loadso/dlopen/SDL_sysloadso.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/power/emscripten/SDL_syspower.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/joystick/emscripten/SDL_sysjoystick.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/filesystem/emscripten/SDL_sysfilesystem.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/timer/unix/SDL_systimer.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/haptic/dummy/SDL_syshaptic.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/main/dummy/SDL_dummy_main.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/thread/generic/SDL_syscond.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/thread/generic/SDL_sysmutex.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/thread/generic/SDL_syssem.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/thread/generic/SDL_systhread.c.o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/src/thread/generic/SDL_systls.c.o
-o
/usr/local/google/home/sbc/.emscripten_cache/wasm-bc/ports-builds/sdl2/libSDL2.bc
```

**Comment by aardappel** [comment]
Note that you're on Linux and I'm on Windows.. not sure how `EMCC_DEBUG=1` would help if running `embuilder.py` separately already fails.. unless that means its run differently?

`EMCC_DEBUG=1` in the Makefile doesn't appear to do much on Windows, it produces the same output.

**Comment by sbc100** [comment]
Set EMCC_DEBUG=1 in the environment before you run embuilder.  It will then log everything it does.

**Comment by sbc100** [comment]
It will produce a whole lot of output that you can then attach to this ticket

**Comment by aardappel** [comment]
Ok, with `EMCC_DEBUG=1` on, it now managed to build.. I have no idea why.

Closing this, maybe someone else will run into it..

**Comment by sbc100** [comment]
You can run that embuilder command with `--force` to force a rebuild.   If you ever see this again or get any more clues please re-open.

**Comment by aardappel** [comment]
`python upstream\emscripten\embuilder.py build --force --lto sdl2` fails in a command prompt that does not have `EMCC_DEBUG=1` debug set, then succeeds in one with it on.

In the succesful case, it notes that it is using a response file, though the file is not there anymore after the build. Given that it succeeds, I guess it has similar contents to yours. I link all my code against SDL2, so clearly it was built correctly.

Given that in the failing case the command line is `['C:/stuff/emsdk/upstream/bin\\llvm-link.exe', '-o', 'C:\\Users\\woute\\.emscripten_cache\\wasm-bc\\ports-builds\\sdl2\\libSDL2.bc']` it appears to fail to supply the input files. Given that it is supplying the `-o`, maybe it is trying to pass these without a response file and failing?

**Comment by sbc100** [comment]
I guess its related to building in parallel somehow,  and its trying to link the library before the object file are built.. strange that we don't see it elsewhere.  Investigating.

**Comment by sbc100** [comment]
Does this happen with any other libraries?

Can you run `./embuilder build ALL`?

**Comment by sbc100** [comment]
If you feel like debugging you could take a look at `tools/ports/sdl2.py:88`.  I'd be curious to see what th evalue of `o_s` is in the failing build.   It should be a list of all the object files.

**Comment by aardappel** [comment]
`embuilder build ALL` builds a bunch of libc variants correctly, before I interrupted it.

`o_s`  contains `['C:\\Users\\woute\\.emscripten_cache\\wasm-bc\\ports-builds\\sdl2\\src\\SDL.c.o', ...many more here...]`

**Comment by aardappel** [comment]
Actually, apparently it has to do with LTO. Just noticed this message from @jgravelle-google from last week: `I did have to disable LTO because SDL2.bc was giving me llvm-link errors, but that seems like an emscripten bug (it does that standalone with embuilder build sdl2 --lto` (and I presume he was also on Windows at the time).

And indeed, removing `--lto` makes it build here locally too.

**Comment by apples** [comment]
Just ran into this exact issue when enabling LTO.

I get the same exact error as OP, though a few line numbers are different.

Either setting `EMCC_DEBUG=1` or disabling LTO allows SDL2 to be built.

The `EMCC_DEBUG=1` flag is only needed while building SDL2. My own sources build just fine with LTO enabled and without `EMCC_DEBUG` set.

**Comment by sbc100** [comment]
@apples are you on windows too?

**Comment by jgravelle-google** [comment]
Right I was going to file this but forgot

Also was on windows. The issue was building with `--lto`, which would invoke llvm-link, which wouldn't have any arguments passed to it. I assume it's something about how windows handles response files

**Comment by kripken** [comment]
Side issue maybe, but is using llvm-link expected here? Should we be using lld for stuff like this?

**Comment by sbc100** [comment]
lld is only used when you want the output to be native.   In LTO mode libSDL either needs to be a single giant bitcode file (.bc, produced by llvm-link) or an archive or bitcode files (.a produced by llvm-ar).

**Comment by sbc100** [comment]
Having said that .. with the wasm backend we should always prefer .a archives.    I thought I'd converted them all with #10485 recently but I guess I only changed the default.

**Comment by apples** [comment]
@sbc100 Yes I am on Windows.
