### ISSUE TITLE
Enabling SIMD results in "invalid local type" error at runtime

### ISSUE THREAD

**Issue by nemequ** [emscripten-core/emscripten#10541]
I'm trying to enable SIMD support (`-msimd128 -s SIMD=1`) in the tests for [SIMDe](https://github.com/nemequ/simde), but when I do I end up with [an error](https://travis-ci.org/nemequ/simde/jobs/653760153#L620) at runtime when trying to use node to run emscripten's output.

I'm using emscripten tot (due to #10425), emcc --version says "emcc (Emscripten gcc/clang-like replacement) 1.39.8 (commit 1458145cf4f3db0fb548343e6acab267eef8e4ef)".

```
failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Compiling function #38:"main" failed: invalid local type @+4749
CompileError: WebAssembly.instantiate(): Compiling function #38:"main" failed: invalid local type @+4749
CompileError: WebAssembly.instantiate(): Compiling function #38:"main" failed: invalid local type @+4749
RuntimeError: abort(CompileError: WebAssembly.instantiate(): Compiling function #38:"main" failed: invalid local type @+4749). Build with -s ASSERTIONS=1 for more info.
RuntimeError: abort(CompileError: WebAssembly.instantiate(): Compiling function #38:"main" failed: invalid local type @+4749). Build with -s ASSERTIONS=1 for more info.
/home/nemequ/local/src/simde/test/build/run-tests.js:119
      throw ex;
      ^

RuntimeError: abort(RuntimeError: abort(CompileError: WebAssembly.instantiate(): Compiling function #38:"main" failed: invalid local type @+4749). Build with -s ASSERTIONS=1 for more info.). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/home/nemequ/local/src/simde/test/build/run-tests.js:1463:9)
    at process.emit (events.js:209:13)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:86:32)
```

I've attached the [generated JavaScript and WASM](https://github.com/emscripten-core/emscripten/files/4239067/simde-wasm.zip).

If I enable assertions when compiling I get

```
failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Compiling function #39:"main" failed: invalid local type @+4817
CompileError: WebAssembly.instantiate(): Compiling function #39:"main" failed: invalid local type @+4817
CompileError: WebAssembly.instantiate(): Compiling function #39:"main" failed: invalid local type @+4817
RuntimeError: abort(CompileError: WebAssembly.instantiate(): Compiling function #39:"main" failed: invalid local type @+4817) at Error
    at jsStackTrace (/home/nemequ/local/src/simde/test/build/run-tests.js:1804:17)
    at stackTrace (/home/nemequ/local/src/simde/test/build/run-tests.js:1821:16)
    at abort (/home/nemequ/local/src/simde/test/build/run-tests.js:1602:44)
    at /home/nemequ/local/src/simde/test/build/run-tests.js:1723:7
RuntimeError: abort(CompileError: WebAssembly.instantiate(): Compiling function #39:"main" failed: invalid local type @+4817) at Error
    at jsStackTrace (/home/nemequ/local/src/simde/test/build/run-tests.js:1804:17)
    at stackTrace (/home/nemequ/local/src/simde/test/build/run-tests.js:1821:16)
    at abort (/home/nemequ/local/src/simde/test/build/run-tests.js:1602:44)
    at /home/nemequ/local/src/simde/test/build/run-tests.js:1723:7
/home/nemequ/local/src/simde/test/build/run-tests.js:122
      throw ex;
      ^

RuntimeError: abort(RuntimeError: abort(CompileError: WebAssembly.instantiate(): Compiling function #39:"main" failed: invalid local type @+4817) at Error
    at jsStackTrace (/home/nemequ/local/src/simde/test/build/run-tests.js:1804:17)
    at stackTrace (/home/nemequ/local/src/simde/test/build/run-tests.js:1821:16)
    at abort (/home/nemequ/local/src/simde/test/build/run-tests.js:1602:44)
    at /home/nemequ/local/src/simde/test/build/run-tests.js:1723:7) at Error
    at jsStackTrace (/home/nemequ/local/src/simde/test/build/run-tests.js:1804:17)
    at stackTrace (/home/nemequ/local/src/simde/test/build/run-tests.js:1821:16)
    at process.abort (/home/nemequ/local/src/simde/test/build/run-tests.js:1602:44)
    at process.emit (events.js:209:13)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:86:32)
    at process.abort (/home/nemequ/local/src/simde/test/build/run-tests.js:1608:9)
    at process.emit (events.js:209:13)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:86:32)
```

If I switch from `-O3` to `-O2` or below I get a compile time error which may or may not be related:

```
Stack dump:
0.	Program arguments: /opt/emscripten/upstream/bin/clang -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=8 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/opt/emscripten/upstream/emscripten/system/include/libcxx -Xclang -isystem/opt/emscripten/upstream/emscripten/system/lib/libcxxabi/include -Xclang -isystem/opt/emscripten/upstream/emscripten/system/include/compat -Xclang -isystem/opt/emscripten/upstream/emscripten/system/include -Xclang -isystem/opt/emscripten/upstream/emscripten/system/include/libc -Xclang -isystem/opt/emscripten/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/opt/emscripten/upstream/emscripten/system/local/include -Xclang -isystem/home/nemequ/.emscripten_cache/wasm/include -DSIMDE_BUILD_CPP_TESTS -DSIMDE_NO_NATIVE -I/home/nemequ/local/src/simde/test/.. -msimd128 -O2 -DSIMDE_ENABLE_OPENMP -fopenmp-simd -gline-tables-only -std=gnu99 -c -DEMSCRIPTEN -msimd128 /home/nemequ/local/src/simde/test/x86/mmx.c -Xclang -isystem/opt/emscripten/upstream/emscripten/system/include/SDL -c -o CMakeFiles/simde-test-emul.dir/x86/mmx.c.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr 
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '/home/nemequ/local/src/simde/test/x86/mmx.c'.
4.	Running pass 'WebAssembly Instruction Selection' on function '@test_simde_mm_adds_pi8'
 #0 0x00007fd2bcefee44 PrintStackTraceSignalHandler(void*) (/opt/emscripten/upstream/bin/../lib/libLLVM-11git.so+0x744e44)
 #1 0x00007fd2bcefc9be llvm::sys::RunSignalHandlers() (/opt/emscripten/upstream/bin/../lib/libLLVM-11git.so+0x7429be)
 #2 0x00007fd2bcefdfb4 llvm::sys::CleanupOnSignal(unsigned long) (/opt/emscripten/upstream/bin/../lib/libLLVM-11git.so+0x743fb4)
 #3 0x00007fd2bce37093 (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) (/opt/emscripten/upstream/bin/../lib/libLLVM-11git.so+0x67d093)
 #4 0x00007fd2bce371cc CrashRecoverySignalHandler(int) (/opt/emscripten/upstream/bin/../lib/libLLVM-11git.so+0x67d1cc)
 #5 0x00007fd2bc784b20 __restore_rt (/lib64/libpthread.so.0+0x14b20)
 #6 0x00007fd2beabb996 llvm::WebAssemblyTargetLowering::LowerSIGN_EXTEND_INREG(llvm::SDValue, llvm::SelectionDAG&) const (/opt/emscripten/upstream/bin/../lib/libLLVM-11git.so+0x2301996)
 #7 0x00007fd2beab9bf9 llvm::WebAssemblyTargetLowering::LowerOperation(llvm::SDValue, llvm::SelectionDAG&) const (/opt/emscripten/upstream/bin/../lib/libLLVM-11git.so+0x22ffbf9)
 #8 0x00007fd2bd56a2e1 (anonymous namespace)::SelectionDAGLegalize::LegalizeOp(llvm::SDNode*) (/opt/emscripten/upstream/bin/../lib/libLLVM-11git.so+0xdb02e1)
 #9 0x00007fd2bd5698ca llvm::SelectionDAG::Legalize() (/opt/emscripten/upstream/bin/../lib/libLLVM-11git.so+0xdaf8ca)
#10 0x00007fd2bd6de983 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/opt/emscripten/upstream/bin/../lib/libLLVM-11git.so+0xf24983)
#11 0x00007fd2bd6dc9ef llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/opt/emscripten/upstream/bin/../lib/libLLVM-11git.so+0xf229ef)
#12 0x00007fd2bd6d90a4 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/opt/emscripten/upstream/bin/../lib/libLLVM-11git.so+0xf1f0a4)
#13 0x00007fd2bd27c6de llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/opt/emscripten/upstream/bin/../lib/libLLVM-11git.so+0xac26de)
#14 0x00007fd2bd05b551 llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/emscripten/upstream/bin/../lib/libLLVM-11git.so+0x8a1551)
#15 0x00007fd2bd05b858 llvm::FPPassManager::runOnModule(llvm::Module&) (/opt/emscripten/upstream/bin/../lib/libLLVM-11git.so+0x8a1858)
#16 0x00007fd2bd05bf90 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/emscripten/upstream/bin/../lib/libLLVM-11git.so+0x8a1f90)
#17 0x00007fd2ba8cd122 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/opt/emscripten/upstream/bin/../lib/libclang-cpp.so.11git+0x16cc122)
#18 0x00007fd2babc4f4c clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/opt/emscripten/upstream/bin/../lib/libclang-cpp.so.11git+0x19c3f4c)
#19 0x00007fd2b99d6e43 clang::ParseAST(clang::Sema&, bool, bool) (/opt/emscripten/upstream/bin/../lib/libclang-cpp.so.11git+0x7d5e43)
#20 0x00007fd2bb411500 clang::FrontendAction::Execute() (/opt/emscripten/upstream/bin/../lib/libclang-cpp.so.11git+0x2210500)
#21 0x00007fd2bb3ac8c3 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/emscripten/upstream/bin/../lib/libclang-cpp.so.11git+0x21ab8c3)
#22 0x00007fd2bb485430 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/emscripten/upstream/bin/../lib/libclang-cpp.so.11git+0x2284430)
#23 0x0000000000410a26 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/emscripten/upstream/bin/clang+0x410a26)
#24 0x000000000040ef7c ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) (/opt/emscripten/upstream/bin/clang+0x40ef7c)
#25 0x00007fd2bb0538c2 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::$_1>(long) (/opt/emscripten/upstream/bin/../lib/libclang-cpp.so.11git+0x1e528c2)
#26 0x00007fd2bce36fb1 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/emscripten/upstream/bin/../lib/libLLVM-11git.so+0x67cfb1)
#27 0x00007fd2bb052e8e clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/opt/emscripten/upstream/bin/../lib/libclang-cpp.so.11git+0x1e51e8e)
#28 0x00007fd2bb020b4b clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/opt/emscripten/upstream/bin/../lib/libclang-cpp.so.11git+0x1e1fb4b)
#29 0x00007fd2bb020f6a clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/opt/emscripten/upstream/bin/../lib/libclang-cpp.so.11git+0x1e1ff6a)
#30 0x00007fd2bb039f38 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/opt/emscripten/upstream/bin/../lib/libclang-cpp.so.11git+0x1e38f38)
#31 0x000000000040e739 main (/opt/emscripten/upstream/bin/clang+0x40e739)
#32 0x00007fd2b8d031a3 __libc_start_main (/lib64/libc.so.6+0x271a3)
#33 0x000000000040bc69 _start (/opt/emscripten/upstream/bin/clang+0x40bc69)
clang-11: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 11.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 45f008704df2680660ee82a7c3543d3ac9499a99)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /opt/emscripten/upstream/bin
clang-11: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-11: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-11: note: diagnostic msg: /tmp/mmx-ef2486.c
clang-11: note: diagnostic msg: /tmp/mmx-ef2486.sh
clang-11: note: diagnostic msg: 

********************
shared:ERROR: '/opt/emscripten/upstream/bin/clang -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=8 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/opt/emscripten/upstream/emscripten/system/include/libcxx -Xclang -isystem/opt/emscripten/upstream/emscripten/system/lib/libcxxabi/include -Xclang -isystem/opt/emscripten/upstream/emscripten/system/include/compat -Xclang -isystem/opt/emscripten/upstream/emscripten/system/include -Xclang -isystem/opt/emscripten/upstream/emscripten/system/include/libc -Xclang -isystem/opt/emscripten/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/opt/emscripten/upstream/emscripten/system/local/include -Xclang -isystem/home/nemequ/.emscripten_cache/wasm/include -DSIMDE_BUILD_CPP_TESTS -DSIMDE_NO_NATIVE -I/home/nemequ/local/src/simde/test/.. -msimd128 -O2 -DSIMDE_ENABLE_OPENMP -fopenmp-simd -gline-tables-only -std=gnu99 -c -DEMSCRIPTEN -msimd128 /home/nemequ/local/src/simde/test/x86/mmx.c -Xclang -isystem/opt/emscripten/upstream/emscripten/system/include/SDL -c -o CMakeFiles/simde-test-emul.dir/x86/mmx.c.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (254)
```

In case it's useful, I've attached the [preprocessed source and script](https://github.com/emscripten-core/emscripten/files/4239056/mmx-ef2486.zip).

The code works without SIMD enabled.

If there is any more information I can provide that would be useful please let me know.  If you'd rather just check out a copy of SIMDe, to build just pass `-DCMAKE_C_FLAGS='-msimd128 -s SIMD=1 -O3' -DCMAKE_CXX_FLAGS='-msimd128 -s SIMD=1 -O3'` to cmake in the test/ directory, then `node run-tests.js`.

**Comment by ngzhian** [comment]
I think a flag needs to be passed to node. For `d8`, the flag is `--experimental-wasm-simd`, but i'm not sure how to pass a d8 flag to node.

**Comment by nemequ** [comment]
Thanks, that helps.

According to https://nodejs.org/api/cli.html#cli_synopsis I should be able to just pass the option to `node`.  `node --v8-options` lists `--experimental-wasm-simd` as an option, and when I pass it to node I do get a slightly different error (this time it's complaining about something in `munit_suite_main_custom` instead of `main`:

```
failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Compiling function #45:"munit_suite_main_custom" failed: invalid simd opcode @+7588
CompileError: WebAssembly.instantiate(): Compiling function #45:"munit_suite_main_custom" failed: invalid simd opcode @+7588
CompileError: WebAssembly.instantiate(): Compiling function #45:"munit_suite_main_custom" failed: invalid simd opcode @+7588
RuntimeError: abort(CompileError: WebAssembly.instantiate(): Compiling function #45:"munit_suite_main_custom" failed: invalid simd opcode @+7588) at Error
    at jsStackTrace (/home/nemequ/local/src/simde/test/build/run-tests.js:1804:17)
    at stackTrace (/home/nemequ/local/src/simde/test/build/run-tests.js:1821:16)
    at abort (/home/nemequ/local/src/simde/test/build/run-tests.js:1602:44)
    at /home/nemequ/local/src/simde/test/build/run-tests.js:1723:7
RuntimeError: abort(CompileError: WebAssembly.instantiate(): Compiling function #45:"munit_suite_main_custom" failed: invalid simd opcode @+7588) at Error
    at jsStackTrace (/home/nemequ/local/src/simde/test/build/run-tests.js:1804:17)
    at stackTrace (/home/nemequ/local/src/simde/test/build/run-tests.js:1821:16)
    at abort (/home/nemequ/local/src/simde/test/build/run-tests.js:1602:44)
    at /home/nemequ/local/src/simde/test/build/run-tests.js:1723:7
/home/nemequ/local/src/simde/test/build/run-tests.js:122
      throw ex;
      ^

RuntimeError: abort(RuntimeError: abort(CompileError: WebAssembly.instantiate(): Compiling function #45:"munit_suite_main_custom" failed: invalid simd opcode @+7588) at Error
    at jsStackTrace (/home/nemequ/local/src/simde/test/build/run-tests.js:1804:17)
    at stackTrace (/home/nemequ/local/src/simde/test/build/run-tests.js:1821:16)
    at abort (/home/nemequ/local/src/simde/test/build/run-tests.js:1602:44)
    at /home/nemequ/local/src/simde/test/build/run-tests.js:1723:7) at Error
    at jsStackTrace (/home/nemequ/local/src/simde/test/build/run-tests.js:1804:17)
    at stackTrace (/home/nemequ/local/src/simde/test/build/run-tests.js:1821:16)
    at process.abort (/home/nemequ/local/src/simde/test/build/run-tests.js:1602:44)
    at process.emit (events.js:209:13)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:86:32)
    at process.abort (/home/nemequ/local/src/simde/test/build/run-tests.js:1608:9)
    at process.emit (events.js:209:13)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:86:32)
```

That's with `-msimd128 -O3 -s SIMD=1 -s ASSERTIONS=1`.

FWIW, it may be worth mentioning --experimental-wasm-simd on <https://emscripten.org/docs/porting/simd.html> if it is required.  Or is there another way to run the result that I should be using instead of node?

**Comment by nemequ** [comment]
Here is a reduced test case:

```c
typedef int vec __attribute__((__vector_size__(8)));

int foo(vec v, int idx) {
  return v[idx & 1];
}

int main(int argc, char** argv) {
  vec a = { 1, 2 };
  return foo(a, argc);
}
```

It works if the vector_size is 16 or 32, but not 8.

**Comment by ngzhian** [comment]
This looks similar to a opcode mismatch that we have seen before and fixed. From what I can tell, node 13.9.10 has [V8 7.9](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V13.md#notable-changes-7), and I've been doing most of my testing on V8 TOT, which probably already the fix.

I tried this on V8 8.0.426.25 (https://v8.dev/blog/v8-release-80) and this works fine. Not sure how your CI is set up, maybe you can consider using latest v8 release instead of node?

**Comment by nemequ** [comment]
That would be feasible if there is somewhere we can download binaries from, but I don't see any.  Maybe I'm missing something?

Our CI just [installs emscripten](https://github.com/nemequ/simde/blob/e99f22696e65da1792101009931bb56950dd507e/.travis.yml#L228) each run.  It would be easy to do something similar for v8.  Compiling v8, OTOH, would probably be prohibitively slow.

**Comment by kripken** [comment]
You can get V8 binaries using jsvu: https://github.com/GoogleChromeLabs/jsvu

cc @tlively for the SIMD issue

**Comment by nemequ** [comment]
That worked, thanks @ngzhian and @kripken!

I'm closing this, but I do still think it might be a good idea to the SIMD page with a note about --experimental-wasm-simd.
