### ISSUE TITLE
MEMORY_GROWTH_GEOMETRIC_STEP value requires KB, MB, GB or TB

### ISSUE THREAD

**Issue by ghost** [emscripten-core/emscripten#10649]
I tried using -s MEMORY_GROWTH_GEOMETRIC_STEP=1.0 compile time option to change the growth step and got this error:
```
Traceback (most recent call last):
  File "D:\src\360\lmv\emsdk\upstream\emscripten\emcc.py", line 3841, in <module>
    sys.exit(run(sys.argv))
  File "D:\src\360\lmv\emsdk\upstream\emscripten\emcc.py", line 1095, in run
    apply_settings(settings_changes)
  File "D:\src\360\lmv\emsdk\upstream\emscripten\emcc.py", line 429, in apply_settings
    value = str(shared.expand_byte_size_suffixes(value))
  File "D:\src\360\lmv\emsdk\upstream\emscripten\tools\shared.py", line 1147, in expand_byte_size_suffixes
    raise Exception("Invalid byte size, valid suffixes: KB, MB, GB, TB")
Exception: Invalid byte size, valid suffixes: KB, MB, GB, TB```
```
I installed `latest-upstream` and `emcc --version` report:
```
emcc (Emscripten gcc/clang-like replacement) 1.39.7 (commit 801bef7d44b9a255ff5f1dc0c21bae3a6bfdd110)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
I looked at the shared.py Python file and MEMORY_GROWTH_GEOMETRY_STEP was in the list of values to be interpreted as a memory size. Requiring a memory size doesn't match the comments in settings.js or the default value.

**Comment by kripken** [comment]
This does look like a bug, thanks @clevea !
