### ISSUE TITLE
Option clash of -gseparate_dwarf and SINGLE_FILE 

### ISSUE THREAD

**Issue by pfaffe** [emscripten-core/emscripten#10758]
When both -gseparate_dwarf and SINGLE_FILE are set, this is what happens:

```
Traceback (most recent call last):                                              
  File "[...]/Software/emsdk/upstream/emscripten/em++.py", line 14, in <module>
    sys.exit(emcc.run(sys.argv))                                                   
  File "[...]/Software/emsdk/upstream/emscripten/emcc.py", line 2674, in run 
    optimizer)                                                                     
  File "[...]/Software/emsdk/upstream/emscripten/emcc.py", line 3337, in do_binaryen
    shared.Building.emit_debug_on_side(wasm_binary_target)                         
  File "[...]/Software/emsdk/upstream/emscripten/tools/shared.py", line 2787, in emit_debug_on_side
    shutil.move(wasm_file, wasm_file_with_dwarf)                                   
  File "/usr/lib/python3.7/shutil.py", line 580, in move                           
    copy_function(src, real_dst)                                                   
  File "/usr/lib/python3.7/shutil.py", line 266, in copy2                          
    copyfile(src, dst, follow_symlinks=follow_symlinks)                            
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile                       
    with open(src, 'rb') as fsrc:                                                  
FileNotFoundError: [Errno 2] No such file or directory: '../../bin/opencv_js.wasm
```

**Comment by kripken** [comment]
Thanks @pfaffe , fix in #10760.
