### ISSUE TITLE
Segfault when closing files with PHYSFS

### ISSUE THREAD

**Issue by zippoxer** [emscripten-core/emscripten#11036]
Hi everyone,

I'm getting a segfault when calling `PHYSFS_close`. It only happens with `-s SAFE_HEAP=1`, which I'm enabling to fix other memory access issues.

Here's the stack trace:

```
Uncaught RuntimeError: abort(segmentation fault) at Error
    at jsStackTrace (http://172.17.2.214:8090/otclient.js:2048:17)
    at stackTrace (http://172.17.2.214:8090/otclient.js:2065:16)
    at abort (http://172.17.2.214:8090/otclient.js:1815:44)
    at segfault (http://172.17.2.214:8090/otclient.js:785:3)
    at SAFE_HEAP_LOAD_i32_4_4 (wasm-function[61847]:0x4e8150)
    at fcntl (wasm-function[59358]:0x498b1b)
    at __PHYSFS_platformFlush (wasm-function[57060]:0x3b5354)
    at nativeIo_flush (wasm-function[57013]:0x3b3d9f)
    at closeHandleInOpenList (wasm-function[56990]:0x3b34d3)
    at PHYSFS_close (wasm-function[56989]:0x3b341e)
```

We can see that `PHYSFS_close` calls `__PHYSFS_platformFlush` and eventually segfaults at `fnctl`.

Here's the entire flow of the file handling that causes this issue in C++:

```cpp
PHYSFS_init(argv[0]); // I tried NULL and also "/"

// ...

PHYSFS_file* file = PHYSFS_openWrite(fileName.c_str());
if(!file) {
    g_logger.error(PHYSFS_getErrorByCode(PHYSFS_getLastErrorCode()));
    return false;
}

PHYSFS_writeBytes(file, (void*)data, size);
PHYSFS_close(file);
```

If it's relevant, I am calling `FS.syncfs(true, ...` at startup of the program. Also, I've compiled PHYSFS for Emscripten using [their own build script](https://github.com/criptych/physfs/blob/master/extras/buildbot-emscripten.sh).

Can anyone help me with how do I go around debugging this?

**Comment by kripken** [comment]
First thing I'd try is ASan, https://emscripten.org/docs/debugging/Sanitizers.html#address-sanitizer

After that, I'd look at that pointer's value. ASan might already print it out for you, if not, instrumenting the wasm. (Might be easier to instrument with `-s WASM=0`, as then you can just edit the JS to add a console.log inside `function fcntl`.)

Then hopefully the value of the pointer, and where it came from, help figure this out.
