### ISSUE TITLE
Not all tests pass with that latest node version (14.1.0)

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#11062]
I didn't look into why or exactly how many fail but one failing test was: `wasm2.test_postrun_exception` (only fails at O2):

```
Traceback (most recent call last):
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/test_core.py", line 8473, in test_postrun_exception
    self.assertNotContained('failed to asynchronously prepare wasm', output)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/runner.py", line 870, in assertNotContained
    limit_size(''.join([a.rstrip() + '\n' for a in difflib.unified_diff(value.split('\n'), string.split('\n'), fromfile='expected', tofile='actual')]))
AssertionError: Expected to NOT find 'failed to asynchronously prepare wasm' in 'hello, world!
ReferenceError: ThisFunctionDoesNotExist is not defined
ReferenceError: ThisFunctionDoesNotExist is not defined
/tmp/emscripten_test_wasm2_0zydv1er/src.c.o.js:1
....
```

**Comment by sbc100** [comment]
I think its because the whole module lives on line 1 so any crash will cause the backtrace to contain all the strings in the program including `failed to asynchronously prepare wasm`
