### ISSUE TITLE
Can't call JS function added by addFunction from secondary thread

### ISSUE THREAD

**Issue by theosib** [emscripten-core/emscripten#11317]
I have a pipelined compute process I'm implementing in WASM using pthreads. Tasks are started from the main thread, but they're executed on a secondary thread in the background. When a task is done, it needs to make a callback into the JS to inform the control logic to retrieve its data. I have used addFunction to turn a JS function (the "callback") into a function pointer, which I can pass to the WASM code. If I call this callback through the main thread, it works fine. But if I call it from the secondary thread, I get a bunch of errors as follows:

```
worker.js onmessage() captured an uncaught exception: RuntimeError: invalid index into function table
threadPrintErr @ decoder.worker.js:24
onmessage @ decoder.worker.js:170
decoder.worker.js:24 RuntimeError: invalid index into function table
    at call_callback (<anonymous>:wasm-function[43]:0x1870)
    at <anonymous>:wasm-function[62]:0x246c
    at dynCall_ii (<anonymous>:wasm-function[1805]:0x32bdd)
    at Object.dynCall_ii (http://localhost:8080/threaded_decoder/decoder.js:2026:22)
    at onmessage (http://localhost:8080/threaded_decoder/decoder.worker.js:130:42)
threadPrintErr @ decoder.worker.js:24
onmessage @ decoder.worker.js:171
decoder.js:2471 pthread sent an error! http://localhost:8080/threaded_decoder/decoder.worker.js:172: Uncaught RuntimeError: invalid index into function table
worker.onerror @ decoder.js:2471
error (async)
loadWasmModuleToWorker @ decoder.js:2470
getNewWorker @ decoder.js:2512
spawnThread @ decoder.js:5842
_pthread_create @ decoder.js:6046
launch_thread @ decoder.wasm:1
(anonymous) @ decoder.js:2026
startup @ test.js:62
(anonymous) @ test.js:73
Promise.then (async)
TestModule @ test.js:68
(anonymous) @ test.js:78
decoder.worker.js:172 Uncaught RuntimeError: invalid index into function table
    at call_callback (<anonymous>:wasm-function[43]:0x1870)
    at <anonymous>:wasm-function[62]:0x246c
    at dynCall_ii (<anonymous>:wasm-function[1805]:0x32bdd)
    at Object.dynCall_ii (http://localhost:8080/threaded_decoder/decoder.js:2026:22)
    at onmessage (http://localhost:8080/threaded_decoder/decoder.worker.js:130:42)
call_callback @ 000eb812:1
(anonymous) @ 000eb812:1
dynCall_ii @ 000eb812:1
(anonymous) @ decoder.js:2026
onmessage @ decoder.worker.js:130
```

I have attached a minimal working example that demonstrates the problem.

[module-pthread.zip](https://github.com/emscripten-core/emscripten/files/4719003/module-pthread.zip)

**Comment by sbc100** [comment]
Since tables are not shared between threads these function don't work as expected in the presence of threads.

We should at least warn, and possible just error out if they are used in threaded programs.
