### ISSUE TITLE
Can't call JS function looked up by emscripten::val::global from alternate thread

### ISSUE THREAD

**Issue by theosib** [emscripten-core/emscripten#11330]
I have a pipelined compute process I'm implementing in WASM using pthreads. Tasks are started from the main thread, but they're executed on a secondary thread in the background. When a task is done, it needs to make a callback into the JS to inform the control logic to retrieve its data. 

I have added a function to the global JS namespace (apparently you have to add it to the window object), and I'm looking that up using `emscripten::val::global()`. If I call this callback through the main thread, it works fine. But if I call it from the secondary thread, I get a bunch of errors as follows:

```
test.worker.js:24 worker.js onmessage() captured an uncaught exception: TypeError: Cannot read property 'apply' of undefined
threadPrintErr @ test.worker.js:24
onmessage @ test.worker.js:170
test.worker.js:24 TypeError: Cannot read property 'apply' of undefined
    at __emval_call (http://localhost:8080/module-pthread/test.js:5672:23)
    at emscripten::val emscripten::val::internalCall<emscripten::internal::_EM_VAL* (*)(emscripten::internal::_EM_VAL*, unsigned int, void const* const*, void const*)>(emscripten::internal::_EM_VAL* (*)(emscripten::internal::_EM_VAL*, unsigned int, void const* const*, void const*)) const (<anonymous>:wasm-function[57]:0x1d92)
    at emscripten::val emscripten::val::operator()<>() const (<anonymous>:wasm-function[52]:0x1995)
    at call_callback (<anonymous>:wasm-function[49]:0x1841)
    at thread_func(void*) (<anonymous>:wasm-function[58]:0x1e01)
    at dynCall_ii (<anonymous>:wasm-function[1734]:0x29803)
    at Object.dynCall_ii (http://localhost:8080/module-pthread/test.js:2021:22)
    at onmessage (http://localhost:8080/module-pthread/test.worker.js:130:42)
threadPrintErr @ test.worker.js:24
onmessage @ test.worker.js:171
test.js:2466 pthread sent an error! http://localhost:8080/module-pthread/test.worker.js:172: Uncaught TypeError: Cannot read property 'apply' of undefined
worker.onerror @ test.js:2466
error (async)
loadWasmModuleToWorker @ test.js:2465
getNewWorker @ test.js:2507
spawnThread @ test.js:6460
_pthread_create @ test.js:6664
launch_thread @ test.wasm:1
(anonymous) @ test.js:2021
moduleTest @ test.html:15
(anonymous) @ test.html:21
Promise.then (async)
(anonymous) @ test.html:19
test.worker.js:172 Uncaught TypeError: Cannot read property 'apply' of undefined
    at __emval_call (http://localhost:8080/module-pthread/test.js:5672:23)
    at emscripten::val emscripten::val::internalCall<emscripten::internal::_EM_VAL* (*)(emscripten::internal::_EM_VAL*, unsigned int, void const* const*, void const*)>(emscripten::internal::_EM_VAL* (*)(emscripten::internal::_EM_VAL*, unsigned int, void const* const*, void const*)) const (<anonymous>:wasm-function[57]:0x1d92)
    at emscripten::val emscripten::val::operator()<>() const (<anonymous>:wasm-function[52]:0x1995)
    at call_callback (<anonymous>:wasm-function[49]:0x1841)
    at thread_func(void*) (<anonymous>:wasm-function[58]:0x1e01)
    at dynCall_ii (<anonymous>:wasm-function[1734]:0x29803)
    at Object.dynCall_ii (http://localhost:8080/module-pthread/test.js:2021:22)
    at onmessage (http://localhost:8080/module-pthread/test.worker.js:130:42)
```

I have attached a minimal working example that demonstrates the problem.

[module-pthread.zip](https://github.com/emscripten-core/emscripten/files/4724458/module-pthread.zip)

**Comment by kripken** [comment]
JavaScript is not shared between threads. Each pthread has a Web Worker, which is a new JS environment. If the data you need is on the main thread, you need to do the call to JS from there.

**Comment by theosib** [comment]
There's got to be SOME way for a secondary thread in WASM to communicate back to the main JS thread. I thought about using emscripten::val::global to see if I could find postMessage and call that, but the emscripten JS wrapper is in control of all the workers and owns onmessage. There should be some standard hooks for a secondary thread to send messages, which are then received by the main thread.

**Comment by kripken** [comment]
Emscripten has a bunch of C/C++ ways to help you do that.

* `MAIN_THREAD_EM_ASM`: https://emscripten.org/docs/api_reference/emscripten.h.html#c.MAIN_THREAD_EM_ASM (runs some JS on the main thread)
* The C API: https://github.com/emscripten-core/emscripten/blob/master/system/include/emscripten/threading.h#L303 (runs some C on the main thread)
* JS library calls can be proxied: https://emscripten.org/docs/porting/pthreads.html#proxying
