### ISSUE TITLE
Runtime errors using pthreads

### ISSUE THREAD

**Issue by AlexVestin** [emscripten-core/emscripten#11351]
Hello,
(Doing this using version `releases-upstream-ae5001fac3849895a873e422a2a80afc90f3b798-64bit`, and chromium 83.0.4103.61 (Official Build) Arch Linux (64-bit) )

I've come across an issue I'm having a hard time debugging. 
I've compiled ffmpeg with x264 to use pthreads, and replaced the check for how many processors there are with a constant number.

Using up to three processors works fine, however if I specify 4 it crashes with
`worker.js onmessage() captured an uncaught exception: RuntimeError: function signature mismatch`
and 
```
WasmEncoder1t.worker.js:24 RuntimeError: function signature mismatch
    at <anonymous>:wasm-function[360]:0x52997
    at dynCall_ii (<anonymous>:wasm-function[1662]:0x10bb13)
    at Object.Module.dynCall_ii (http://localhost:3000/WasmEncoder1t.js:7215:38)
    at onmessage (http://localhost:3000/WasmEncoder1t.worker.js:130:42)
```

always on the 16th iteration. x264 logging indicates that 8 threads are being used if 4 processors are specified, and 4 otherwise. Logging `_pthread_create` it creates 9 threads, so I don't think it should be hitting a max worker limit.  

I'm compiling with the options:
`
-o WasmEncoder1t.js\
-s EXPORTED_FUNCTIONS=$(ENCODE_FUNCTIONS) \
-s TOTAL_MEMORY=1024MB \
-s MODULARIZE=1 \
-s EXPORT_NAME="WasmEncoder" \
-s USE_PTHREADS=1 \
-s ALLOW_BLOCKING_ON_MAIN_THREAD=1 \
-s PTHREAD_POOL_SIZE=16
`
And tried with varying total memory and pool size (also without defining the pool size).

Any pointer to what is going wrong?

**Comment by AlexVestin** [comment]
Actually it seems it was a path that was only reached when more than one lookahead thread was used, and there was a pointer cast that was the problem, so not really related to pthreads.
