### ISSUE TITLE
cannot use the stack before compiled code is ready to run, and has provided stack access

### ISSUE THREAD

**Issue by matt-42** [emscripten-core/emscripten#11428]
This  code seems to trigger a stack allocation before the code is ready to run:

```c++
#include <iostream>
auto& x = std::cout; // x is a global ref pointing to std::cout
```

Here is the stack with 1.39.16:
```js
cppLib.js:1808 Uncaught (in promise) RuntimeError: abort(cannot use the stack before compiled code is ready to run, and has provided stack access) at Error
    at jsStackTrace (http://localhost:3000/292d556….worker.js:70621:17)
    at stackTrace (http://localhost:3000/292d556….worker.js:70638:16)
    at abort (http://localhost:3000/292d556….worker.js:70397:44)
    at stackAlloc (http://localhost:3000/292d556….worker.js:68988:3)
    at invoke_ii (http://localhost:3000/292d556….worker.js:74812:12)
    at std::__2::ios_base::Init::Init() (http://localhost:3000/2b61077….wasm:wasm-function[373]:0x4b3f)
    at __cxx_global_var_init.1 (http://localhost:3000/2b61077….wasm:wasm-function[372]:0x4b0c)
    at _GLOBAL__I_000101 (http://localhost:3000/2b61077….wasm:wasm-function[447]:0x6185)
    at __wasm_call_ctors (http://localhost:3000/2b61077….wasm:wasm-function[57]:0x1691)
    at ./src/cppLib.js.Module.___wasm_call_ctors (http://localhost:3000/292d556….worker.js:74516:45)
    at abort (http://localhost:3000/292d556….worker.js:70403:9)
    at stackAlloc (http://localhost:3000/292d556….worker.js:68988:3)
    at invoke_ii (http://localhost:3000/292d556….worker.js:74812:12)
    at std::__2::ios_base::Init::Init() (http://localhost:3000/2b61077….wasm:wasm-function[373]:0x4b3f)
    at __cxx_global_var_init.1 (http://localhost:3000/2b61077….wasm:wasm-function[372]:0x4b0c)
    at _GLOBAL__I_000101 (http://localhost:3000/2b61077….wasm:wasm-function[447]:0x6185)
    at __wasm_call_ctors (http://localhost:3000/2b61077….wasm:wasm-function[57]:0x1691)
    at ./src/cppLib.js.Module.___wasm_call_ctors (http://localhost:3000/292d556….worker.js:74516:45)
    at func (http://localhost:3000/292d556….worker.js:70596:65)
    at callRuntimeCallbacks (http://localhost:3000/292d556….worker.js:70152:7)
```

With 1.39.18:
```js
cppLib.js:6012 Uncaught (in promise) ReferenceError: stackSave is not defined
    at invoke_ii (cppLib.js:6012)
    at std::__2::ios_base::Init::Init() (c72d9db……unction[393]:0x5774)
    at __cxx_global_var_init.1 (c72d9db……unction[392]:0x5741)
    at _GLOBAL__I_000101 (c72d9db……unction[455]:0x6d4c)
    at __wasm_call_ctors (c72d9db……function[57]:0x1689)
    at cppLib.js:1793
    at func (cppLib.js:1942)
    at callRuntimeCallbacks (cppLib.js:1495)
    at initRuntime (cppLib.js:1528)
    at doRun (cppLib.js:6502)
```

**Comment by matt-42** [comment]
Update: the problem is solved when using emsdk instead of the archlinux emscripten package.

**Comment by kripken** [comment]
Sounds like we can close this, if it works in latest emsdk?

**Comment by matt-42** [comment]
yes it's ok
