### ISSUE TITLE
stacktrace shows wasm-function[XXXX]:0xXXXXX instead of real filenames and line numbers

### ISSUE THREAD

**Issue by matt-42** [emscripten-core/emscripten#11425]
Is it possible to get real file names and lines number  instead of wasm-function[XXXX]:0xXXXXX ? 

Note: I'm using the -g4 flag and jest to run the code.

**Comment by sbc100** [comment]
Are you linking with `-g4` too?  It should be enough to linking with `-g` (or `-g4`) to get function names.

You will need to use this flag when linking though, its not enough to just use it when compiling.

**Comment by sbc100** [comment]
Also what engine are you running under where you see those message (browser?, node?)

**Comment by sbc100** [comment]
We also have the explicit `--profiling-funcs` flag that just includes function names, but `-g4` should be a superset of that functionality.

**Comment by matt-42** [comment]
Yes I used -g4 for compiling and linking. I have the problem in browser (with --source-map-base / and putting the map at the root of the webserver but with webpack changing the filenames I'm not sure this can work..) and in node (because I run the tests with jest) aswell.

**Comment by sbc100** [comment]
Seeing function names in backtraces should not depend on sourcemaps.  

Can you verify that it works for a simple hello world program (just put an abort in main to test):

```
$ cat hello.c
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>

int main(int argc, char* argv[]) {
  printf("Hello, world! %s\n", NULL);
  abort();
  return 0;
}
```

```
$ emcc -g -c hello.c && ./emcc hello.o  -g && node ./a.out.js
exception thrown: RuntimeError: abort(undefined) at Error
    at jsStackTrace (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:1907:17)
    at stackTrace (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:1924:16)
    at abort (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:1650:44)
    at _abort (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:1934:7)
    at main (wasm-function[8]:85)       <----- shows main
    at /usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:1727:22
    at callMain (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:2339:15)
    at doRun (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:2401:23)
```

Without -g:

```
$ emcc -c hello.c && ./emcc hello.o && node ./a.out.js
exception thrown: RuntimeError: abort(undefined) at Error
    at jsStackTrace (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:1907:17)
    at stackTrace (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:1924:16)
    at abort (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:1650:44)
    at _abort (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:1934:7)
    at wasm-function[8]:85
    at /usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:1727:22
    at callMain (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:2339:15)
    at doRun (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:2401:23)
 ```

**Comment by sbc100** [comment]
I don't think sourcemaps or dwarf are supported at all in node.. so that best you get is function names in backtraces.

For sourcemaps, does it work for simple examples without webpack?

**Comment by matt-42** [comment]
I did a test this morning without webpack:

```
#include <cassert>

void fun_with_assert() {  assert(0); }
void fun() {  fun_with_assert(); }
int main() { fun(); }
```

I compiled it with
```
emcc --source-map-base / -s DISABLE_EXCEPTION_CATCHING=0 -s ASSERTIONS=1 -g4 -o test.html ./test.cc;
```
served the current directory it with a static file server
```
serve .
```

When I open test.html in a browser, I see the emscripten shell.
in the console I see this:
```
Assertion failed: 0, at: ./test.cc,3,fun_with_assert
test:1246 Assertion failed: 0, at: ./test.cc,3,fun_with_assert
test:1246 exception thrown: RuntimeError: abort(Assertion failed: 0, at: ./test.cc,3,fun_with_assert) at Error
    at jsStackTrace (http://localhost:5000/test.js:1905:17)
    at stackTrace (http://localhost:5000/test.js:1922:16)
    at abort (http://localhost:5000/test.js:1650:44)
    at ___assert_fail (http://localhost:5000/test.js:1928:7)
    at fun_with_assert() (http://localhost:5000/test.wasm:wasm-function[5]:0x1aa)
    at fun() (http://localhost:5000/test.wasm:wasm-function[6]:0x1b0)
    at __original_main (http://localhost:5000/test.wasm:wasm-function[7]:0x1bc)
    at main (http://localhost:5000/test.wasm:wasm-function[8]:0x1c6)
    at http://localhost:5000/test.js:1727:22
    at callMain (http://localhost:5000/test.js:2203:15),RuntimeError: abort(Assertion failed: 0, at: ./test.cc,3,fun_with_assert) at Error
    at jsStackTrace (http://localhost:5000/test.js:1905:17)
    at stackTrace (http://localhost:5000/test.js:1922:16)
    at abort (http://localhost:5000/test.js:1650:44)
    at ___assert_fail (http://localhost:5000/test.js:1928:7)
    at fun_with_assert() (http://localhost:5000/test.wasm:wasm-function[5]:0x1aa)
    at fun() (http://localhost:5000/test.wasm:wasm-function[6]:0x1b0)
    at __original_main (http://localhost:5000/test.wasm:wasm-function[7]:0x1bc)
    at main (http://localhost:5000/test.wasm:wasm-function[8]:0x1c6)
    at http://localhost:5000/test.js:1727:22
    at callMain (http://localhost:5000/test.js:2203:15)
    at abort (http://localhost:5000/test.js:1656:9)
    at ___assert_fail (http://localhost:5000/test.js:1928:7)
    at fun_with_assert() (http://localhost:5000/test.wasm:wasm-function[5]:0x1aa)
    at fun() (http://localhost:5000/test.wasm:wasm-function[6]:0x1b0)
    at __original_main (http://localhost:5000/test.wasm:wasm-function[7]:0x1bc)
    at main (http://localhost:5000/test.wasm:wasm-function[8]:0x1c6)
    at http://localhost:5000/test.js:1727:22
    at callMain (http://localhost:5000/test.js:2203:15)
    at doRun (http://localhost:5000/test.js:2265:23)
    at http://localhost:5000/test.js:2276:7
test.js:1656 Uncaught RuntimeError: abort(Assertion failed: 0, at: ./test.cc,3,fun_with_assert) at Error
    at jsStackTrace (http://localhost:5000/test.js:1905:17)
    at stackTrace (http://localhost:5000/test.js:1922:16)
    at abort (http://localhost:5000/test.js:1650:44)
    at ___assert_fail (http://localhost:5000/test.js:1928:7)
    at fun_with_assert() (http://localhost:5000/test.wasm:wasm-function[5]:0x1aa)
    at fun() (http://localhost:5000/test.wasm:wasm-function[6]:0x1b0)
    at __original_main (http://localhost:5000/test.wasm:wasm-function[7]:0x1bc)
    at main (http://localhost:5000/test.wasm:wasm-function[8]:0x1c6)
    at http://localhost:5000/test.js:1727:22
    at callMain (http://localhost:5000/test.js:2203:15)
    at abort (http://localhost:5000/test.js:1656:9)
    at ___assert_fail (http://localhost:5000/test.js:1928:7)
    at fun_with_assert() (http://localhost:5000/test.wasm:wasm-function[5]:0x1aa)
    at fun() (http://localhost:5000/test.wasm:wasm-function[6]:0x1b0)
    at __original_main (http://localhost:5000/test.wasm:wasm-function[7]:0x1bc)
    at main (http://localhost:5000/test.wasm:wasm-function[8]:0x1c6)
    at http://localhost:5000/test.js:1727:22
    at callMain (http://localhost:5000/test.js:2203:15)
    at doRun (http://localhost:5000/test.js:2265:23)
    at http://localhost:5000/test.js:2276:7
```
But when I click on the links (in chromium) http://localhost:5000/test.wasm:wasm-function[6]:0x1b0 I got redirected to the first line wasm (which freeze the browser for a few seconds):
![image](https://user-images.githubusercontent.com/846584/84983578-56754680-b139-11ea-9e35-0aa20291801c.png)

I would expect that I get redirect to the cc files. At least I thought that this was the purpose of the .map files.

**Comment by sbc100** [comment]
Can you see the source map being fetching the network log?  If not then its not correctly being embedded in the wasm file.

**Comment by matt-42** [comment]
No I did not see it. Only test.js and test.wasm are in the network panel.

**Comment by kripken** [comment]
I think the network panel shows user network operations. Fetching the .map file by the devtools is a browser internal operation.

Your .cpp file works for me, when I build with `./emcc -s DISABLE_EXCEPTION_CATCHING=0 -g4 -o a.html a.cpp`, and then in the devtools I click on "sources" and then I see "a.cpp" there, and can click on it to see the original source code, set breakpoints, etc. That's on Chrome 83.

**Comment by matt-42** [comment]
I actually never tried to set breackpoints. This works well yes :) So I'm closing this issue.

On the other hand do you know if it would be possible or hard to replace `test.wasm:wasm-function[5]:0x1aa` with test.c:4 in the exception stacktrace ?

 fun_with_assert() (http://localhost:5000/test.wasm:wasm-function[5]:0x1aa)

**Comment by kripken** [comment]
I don't think browsers do anything with stack traces exception use function names, if the Names section is present. So `--profiling` would give you `test.wasm:real-name()`, but not the source file and line number.

**Comment by matt-42** [comment]
I tried --profiling and --profiling-funcs with the -g4 flag and the names section is always empty: 
`
{"version":3,"sources":["test.cc"],"names":[],"mappings":"4YAEA...
`

**Comment by kripken** [comment]
That's a source map file. That's not used for stack traces in an exception by the VM.

All you need for proper names (again, just names, not filenames or line numbers) in a stack trace of an exception is `--profiling`, without `-g4` or anything else.
