### ISSUE TITLE
"Fatal: Module::addExport: stackSave already exists" failure in tests

### ISSUE THREAD

**Issue by Shachlan** [emscripten-core/emscripten#11455]
I get the error below when trying to run any test. I tried loading emsdk before the tests, or installing binaryen from homebrew, neither option helped. 

I'm using MacOS 10.15.4, this error happens on current `master` tip.

```
Test suites:
['test_browser']
Running test_browser: (1 tests)
(checking sanity from test runner)
shared:INFO: (Emscripten: Running sanity checks)
[Browser harness server on process 9843]
/Users/shachar/repositories/emscripten/tests/runner.py:INFO: Using default system browser

Running the browser tests. Make sure the browser allows popups from localhost.

test_TextDecoder (test_browser.browser) ... cache:INFO: generating system library: libc.a... (this will be cached in "/Users/shachar/repositories/emscripten/cache/wasm/libc.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libcompiler_rt.a... (this will be cached in "/Users/shachar/repositories/emscripten/cache/wasm/libcompiler_rt.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc-wasm.a... (this will be cached in "/Users/shachar/repositories/emscripten/cache/wasm/libc-wasm.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc++-noexcept.a... (this will be cached in "/Users/shachar/repositories/emscripten/cache/wasm/libc++-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc++abi-noexcept.a... (this will be cached in "/Users/shachar/repositories/emscripten/cache/wasm/libc++abi-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libdlmalloc.a... (this will be cached in "/Users/shachar/repositories/emscripten/cache/wasm/libdlmalloc.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libpthread_stub.a... (this will be cached in "/Users/shachar/repositories/emscripten/cache/wasm/libpthread_stub.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc_rt_wasm.a... (this will be cached in "/Users/shachar/repositories/emscripten/cache/wasm/libc_rt_wasm.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libsockets.a... (this will be cached in "/Users/shachar/repositories/emscripten/cache/wasm/libsockets.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "/Users/shachar/repositories/emscripten/cache/wasm/generated_struct_info.json" for subsequent builds)
Fatal: Module::addExport: stackSave already exists
emcc: error: '/Users/shachar/repositories/exception-example/emsdk/upstream/bin/wasm-emscripten-finalize --detect-features --global-base=1024 --check-stack-overflow /var/folders/6r/4ynwf0ld5_lb39f7qxvvv07w0000gn/T/emscripten_temp_o5nafrr_/tmp1iqz43gu.wasm -o /var/folders/6r/4ynwf0ld5_lb39f7qxvvv07w0000gn/T/emscripten_temp_o5nafrr_/tmp1iqz43gu.wasm.o.wasm' failed (1)
FAIL: Compilation failed!: ['/Users/shachar/repositories/emscripten/emcc', '-D_GNU_SOURCE', '-o', '/var/folders/6r/4ynwf0ld5_lb39f7qxvvv07w0000gn/T/tmp1iqz43gu.js', '/var/folders/6r/4ynwf0ld5_lb39f7qxvvv07w0000gn/T/tmpfea2nyc2.c', '-O0', '--js-opts', '0', '--memory-init-file', '0', '-Werror', '-Wno-format', '-s', 'BOOTSTRAPPING_STRUCT_INFO=1', '-s', 'WARN_ON_UNDEFINED_SYMBOLS=0', '-s', 'STRICT=1', '-s', 'SINGLE_FILE=1']
ERROR
[Browser harness server terminated]

======================================================================
ERROR: test_TextDecoder (test_browser.browser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/shachar/repositories/emscripten/tests/test_browser.py", line 4185, in test_TextDecoder
    self.btest('browser_test_hello_world.c', '0', args=['-s', 'TEXTDECODER=0'])
  File "/Users/shachar/repositories/emscripten/tests/runner.py", line 1739, in btest
    self.compile_btest(all_args)
  File "/Users/shachar/repositories/emscripten/tests/runner.py", line 1699, in compile_btest
    run_process([EMCC] + args + ['--pre-js', path_from_root('tests', 'browser_reporting.js')])
  File "/Users/shachar/repositories/emscripten/tools/shared.py", line 192, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/Users/shachar/repositories/emscripten/emcc', '-s', 'IN_TEST_HARNESS=1', '/Users/shachar/repositories/emscripten/tests/browser_test_hello_world.c', '-o', 'test.html', '-s', 'TEXTDECODER=0', '-DEMTEST_PORT_NUMBER=8888', '-include', '/Users/shachar/repositories/emscripten/tests/report_result.h', '/Users/shachar/repositories/emscripten/tests/report_result.cpp', '--pre-js', '/Users/shachar/repositories/emscripten/tests/browser_reporting.js']' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 1 test in 42.499s

FAILED (errors=1)
```

**Comment by sbc100** [comment]
Looks like maybe you need an even more recent version of emsdk.

To get this you can install the `tot` version (run `./emsdk update-tags && ./emsdk install tot && ./emsdk activate tot`.   Then make sure emsdk is active in your current shell: `source ./emsdk_env.sh`.

**Comment by Shachlan** [comment]
thanks, that works!
