### ISSUE TITLE
Emscripten failing to build SDL2_Mixer.

### ISSUE THREAD

**Issue by thedarkb** [emscripten-core/emscripten#11499]
```emcc nutricia.c -O3 -s MODULARIZE=1 -s ALLOW_MEMORY_GROWTH=1 -s USE_SDL=2 -s USE_SDL_MIXER=2 -s USE_OGG=1 -s USE_VORBIS=1 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='["png"]' -s USE_SDL_TTF=2 --embed-file assets -o web/nutricia.js
wasm-ld: warning: function signature mismatch: SDL_SetError
>>> defined as (i32, i32) -> void in /home/beno/.emscripten_cache/wasm-obj/libSDL2_mixer.a(music_ogg_c7e927a2.c.o)
>>> defined as (i32, i32) -> i32 in /home/beno/.emscripten_cache/wasm-obj/libSDL2.a(SDL_error_67c42f5e.c.o)

wasm-ld: warning: function signature mismatch: SDL_Error
>>> defined as (i32) -> void in /home/beno/.emscripten_cache/wasm-obj/libSDL2_mixer.a(music_ogg_c7e927a2.c.o)
>>> defined as (i32) -> i32 in /home/beno/.emscripten_cache/wasm-obj/libSDL2.a(SDL_error_67c42f5e.c.o)
emcc:INFO: Enabling --no-heap-copy because -s ALLOW_MEMORY_GROWTH=1 is being used with file_packager.py (pass --no-heap-copy to suppress this notification)
```

The resultant binary won't run, and exits with the error:
```
Uncaught (in promise) RuntimeError: function signature mismatch
    at wasm-function[1112]:0x6de1a
    at wasm-function[436]:0x11a04
    at wasm-function[1850]:0xbad51
    at wasm-function[1757]:0xb101c
    at Module._main (http://localhost/da/web/nutricia.js:9:1326371)
    at callMain (http://localhost/da/web/nutricia.js:9:1334521)
    at doRun (http://localhost/da/web/nutricia.js:9:1335099)
    at run (http://localhost/da/web/nutricia.js:9:1335271)
    at runCaller (http://localhost/da/web/nutricia.js:9:1334376)
    at removeRunDependency (http://localhost/da/web/nutricia.js:9:1147458)
```

**Comment by sbc100** [comment]
Can you build with `--profiling-functions` to see the names of the functions in the backtrace?

**Comment by thedarkb** [comment]
`clang-10: error: unsupported option '--profiling-functions`

**Comment by kripken** [comment]
What's the build command here? Is this using the emscripten port of SDL2_mixer, or a custom one?

**Comment by kripken** [comment]
Oh, but that this is using `clang-10` may mean it's a bug in older LLVM that has been fixed. Please try in the latest release (which will use `clang-11`).

**Comment by thedarkb** [comment]
I'll give it a try.

**Comment by thedarkb** [comment]
I ran `emsdk install latest` and attempted another compilation only to run into the same issue again.

**Comment by sbc100** [comment]
Can you post the the full failing command and the full output? 

Can you also include the output of `emcc -v`?

**Comment by thedarkb** [comment]
The command is: `emcc nutricia.c -v -O3 -s MODULARIZE=1 -s ALLOW_MEMORY_GROWTH=1 -s USE_SDL=2 -s USE_SDL_MIXER=2 -s USE_OGG=0 -s USE_VORBIS=0 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='["png"]' -s USE_SDL_TTF=2 --embed-file assets -o web/nutricia.js`

And the output is:
```
shared:INFO: (Emscripten: Running sanity checks)
 "/home/beno/emsdk/upstream/bin/clang" -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=5 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/home/beno/emsdk/upstream/emscripten/system/include/libcxx -Xclang -isystem/home/beno/emsdk/upstream/emscripten/system/lib/libcxxabi/include -Xclang -isystem/home/beno/emsdk/upstream/emscripten/system/include/compat -Xclang -isystem/home/beno/emsdk/upstream/emscripten/system/include -Xclang -isystem/home/beno/emsdk/upstream/emscripten/system/include/libc -Xclang -isystem/home/beno/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/home/beno/emsdk/upstream/emscripten/system/local/include -Xclang -isystem/home/beno/.emscripten_cache/wasm-obj/include -v -O3 -DEMSCRIPTEN nutricia.c -Xclang -isystem/home/beno/.emscripten_cache/wasm-obj/include/SDL2 -I/home/beno/.emscripten_cache/wasm-obj/include/freetype2/freetype -c -o /tmp/emscripten_temp_qykpCF/nutricia_0.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr
clang version 10.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project be2b7ea89ab43d6827634fbdbbd2661e1f242527)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/beno/emsdk/upstream/bin
 "/home/beno/emsdk/upstream/bin/clang-10" -cc1 -triple wasm32-unknown-emscripten -emit-obj -disable-free -main-file-name nutricia.c -mrelocation-model static -mthread-model posix -mframe-pointer=none -fno-rounding-math -masm-verbose -mconstructor-aliases -target-cpu generic -fvisibility hidden -dwarf-column-info -debugger-tuning=gdb -v -resource-dir /home/beno/emsdk/upstream/lib/clang/10.0.0 -D __EMSCRIPTEN_major__=1 -D __EMSCRIPTEN_minor__=39 -D __EMSCRIPTEN_tiny__=5 -D _LIBCPP_ABI_VERSION=2 -D unix -D __unix -D __unix__ -D EMSCRIPTEN -I /home/beno/.emscripten_cache/wasm-obj/include/freetype2/freetype -internal-isystem /home/beno/emsdk/upstream/lib/clang/10.0.0/include -internal-isystem /include/wasm32-emscripten -internal-isystem /include -O3 -Werror=implicit-function-declaration -fdebug-compilation-dir /home/beno/Documents/work/mycode -ferror-limit 19 -fmessage-length 0 -fgnuc-version=4.2.1 -fobjc-runtime=gnustep -fno-common -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -nostdsysteminc -isystem/home/beno/emsdk/upstream/emscripten/system/include/libcxx -isystem/home/beno/emsdk/upstream/emscripten/system/lib/libcxxabi/include -isystem/home/beno/emsdk/upstream/emscripten/system/include/compat -isystem/home/beno/emsdk/upstream/emscripten/system/include -isystem/home/beno/emsdk/upstream/emscripten/system/include/libc -isystem/home/beno/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -isystem/home/beno/emsdk/upstream/emscripten/system/local/include -isystem/home/beno/.emscripten_cache/wasm-obj/include -isystem/home/beno/.emscripten_cache/wasm-obj/include/SDL2 -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /tmp/emscripten_temp_qykpCF/nutricia_0.o -x c nutricia.c
clang -cc1 version 10.0.0 based upon LLVM 10.0.0git default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/include/wasm32-emscripten"
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /home/beno/.emscripten_cache/wasm-obj/include/freetype2/freetype
 /home/beno/emsdk/upstream/emscripten/system/include/libcxx
 /home/beno/emsdk/upstream/emscripten/system/lib/libcxxabi/include
 /home/beno/emsdk/upstream/emscripten/system/include/compat
 /home/beno/emsdk/upstream/emscripten/system/include
 /home/beno/emsdk/upstream/emscripten/system/include/libc
 /home/beno/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten
 /home/beno/emsdk/upstream/emscripten/system/local/include
 /home/beno/.emscripten_cache/wasm-obj/include
 /home/beno/.emscripten_cache/wasm-obj/include/SDL2
 /home/beno/emsdk/upstream/lib/clang/10.0.0/include
End of search list.
 "/home/beno/emsdk/upstream/bin/wasm-ld" -o /tmp/emscripten_temp_qykpCF/nutricia.wasm --allow-undefined --lto-O0 /tmp/emscripten_temp_qykpCF/nutricia_0.o -L/home/beno/emsdk/upstream/emscripten/system/local/lib -L/home/beno/emsdk/upstream/emscripten/system/lib -L/home/beno/.emscripten_cache/wasm-obj /home/beno/.emscripten_cache/wasm-obj/libSDL2_ttf.a /home/beno/.emscripten_cache/wasm-obj/libfreetype.a /home/beno/.emscripten_cache/wasm-obj/libSDL2_mixer.a /home/beno/.emscripten_cache/wasm-obj/libvorbis.a /home/beno/.emscripten_cache/wasm-obj/libogg.a /home/beno/.emscripten_cache/wasm-obj/libSDL2_image_png.a /home/beno/.emscripten_cache/wasm-obj/libSDL2.a /home/beno/.emscripten_cache/wasm-obj/libpng.a /home/beno/.emscripten_cache/wasm-obj/libz.a /home/beno/.emscripten_cache/wasm-obj/libc.a /home/beno/.emscripten_cache/wasm-obj/libcompiler_rt.a /home/beno/.emscripten_cache/wasm-obj/libc-wasm.a /home/beno/.emscripten_cache/wasm-obj/libgl.a /home/beno/.emscripten_cache/wasm-obj/libdlmalloc.a /home/beno/.emscripten_cache/wasm-obj/libpthread_stub.a /home/beno/.emscripten_cache/wasm-obj/libc_rt_wasm.a /home/beno/.emscripten_cache/wasm-obj/libsockets.a --import-memory --import-table -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --strip-debug --export __wasm_call_ctors --export __data_end --export main --export malloc --export free --export setThrew --export __errno_location --export realloc --export _get_environ --export fileno --export emscripten_GetProcAddress --export strstr -z stack-size=5242880 --initial-memory=16777216 --no-entry --global-base=1024
wasm-ld: warning: function signature mismatch: SDL_SetError
>>> defined as (i32, i32) -> void in /home/beno/.emscripten_cache/wasm-obj/libSDL2_mixer.a(music_ogg_c7e927a2.c.o)
>>> defined as (i32, i32) -> i32 in /home/beno/.emscripten_cache/wasm-obj/libSDL2.a(SDL_error_67c42f5e.c.o)

wasm-ld: warning: function signature mismatch: SDL_Error
>>> defined as (i32) -> void in /home/beno/.emscripten_cache/wasm-obj/libSDL2_mixer.a(music_ogg_c7e927a2.c.o)
>>> defined as (i32) -> i32 in /home/beno/.emscripten_cache/wasm-obj/libSDL2.a(SDL_error_67c42f5e.c.o)
 "/home/beno/emsdk/upstream/bin/wasm-emscripten-finalize" --detect-features --global-base=1024 /tmp/emscripten_temp_qykpCF/nutricia.wasm -o /tmp/emscripten_temp_qykpCF/nutricia.wasm.o.wasm
emcc:INFO: Enabling --no-heap-copy because -s ALLOW_MEMORY_GROWTH=1 is being used with file_packager.py (pass --no-heap-copy to suppress this notification)
 "/home/beno/emsdk/upstream/bin/wasm-opt" --post-emscripten --inline-main --no-exit-runtime -O3 --low-memory-unused --strip-debug --strip-producers --pass-arg=emscripten-sbrk-ptr@240256 web/nutricia.wasm -o web/nutricia.wasm --mvp-features
 "/home/beno/emsdk/upstream/bin/wasm-metadce" --graph-file=/tmp/tmpOwc3Ir.txt web/nutricia.wasm -o web/nutricia.wasm --mvp-features
 "/home/beno/emsdk/upstream/bin/wasm-opt" --minify-imports-and-exports web/nutricia.wasm -o web/nutricia.wasm --mvp-features
```

**Comment by sbc100** [comment]
Can you try with the latest version of emscripten (`emsdk install latest`).   I can't tell what version you are using but it can't be the latest version since it includes llvm 10 and not llvm 11.

And if the runtime issue persists after the update please try adding `--profiling-functions` once again to see the names of the functions in the backtrace.
