### ISSUE TITLE
emconfigure is failing

### ISSUE THREAD

**Issue by vbora** [emscripten-core/emscripten#11601]
Hi,
I am trying to build OpenSSL using emscripten using [this documentation.](https://emscripten.org/docs/compiling/Building-Projects.html) 
I setup the emscripten environment for 1.39.17 and downloaded [openssl-1.0.2m](https://www.openssl.org/source/old/1.0.2/openssl-1.0.2m.tar.gz).

when I run emconfigure ./Configure
I get the following error

```
configure: ./Configure
Traceback (most recent call last):
  File "/home/vabora/emsdk/upstream/emscripten/emconfigure.py", line 52, in <module>
    sys.exit(run())
  File "/home/vabora/emsdk/upstream/emscripten/emconfigure.py", line 45, in run
    building.configure(sys.argv[1:])
  File "/home/vabora/emsdk/upstream/emscripten/tools/building.py", line 357, in configure
    run_process(args, stdout=stdout, stderr=stderr, env=env, **kwargs)
  File "/home/vabora/emsdk/upstream/emscripten/tools/shared.py", line 191, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: './Configure'

```

Google told me to add a shebang on top, but it did not help.

Any ideas on what I can try to get this to work will be very appreciated!

**Comment by sbc100** [comment]
Does openssl's configure script really start with a capital letter like that?

What does `file Configure` say? 

Can you run `./Configure` without emscripten preceding it?    (It should configure for the host platform in this case)

**Comment by sbc100** [comment]
Oh string.. that version of openssl has a Configure script written in perl.

The simplest path forward is to run `emconfigure /usr/bin/perl ./Configure`

**Comment by vbora** [comment]
@sbc100 Thanks a lot! That worked.
