### ISSUE TITLE
error: failure to process js library "library.js"

### ISSUE THREAD

**Issue by lailton** [emscripten-core/emscripten#11663]
Hello everyone,

I have updated my git repository today and after I try to compile I got this error.

error: failure to process js library "library.js": TypeError: Cannot read property 'utimbuf' of undefined,
error: use -s VERBOSE to see more details
Internal compiler error in src/compiler.js!
Please create a bug report at https://github.com/emscripten-core/emscripten/issues/
with a log of the build and the input files used to run. Exception message: "TypeError: Cannot read property 'utimbuf' of undefined" | TypeError: Cannot read property 'utimbuf' of undefined
    at eval (eval at <anonymous> (eval at globalEval (/hbc0d3/3rd/emsdk/upstream/emscripten/src/compiler.js:45:8)), <anonymous>:1:12)
    at eval (eval at globalEval (/hbc0d3/3rd/emsdk/upstream/emscripten/src/compiler.js:45:8), <anonymous>:16:15)
    at String.replace (<anonymous>)
    at processMacros (eval at globalEval (/hbc0d3/3rd/emsdk/upstream/emscripten/src/compiler.js:45:8), <anonymous>:14:15)
    at Object.load (eval at globalEval (/hbc0d3/3rd/emsdk/upstream/emscripten/src/compiler.js:45:8), <anonymous>:189:21)
    at JSify (eval at globalEval (/hbc0d3/3rd/emsdk/upstream/emscripten/src/compiler.js:45:8), <anonymous>:79:20)
    at Object.<anonymous> (/hbc0d3/3rd/emsdk/upstream/emscripten/src/compiler.js:136:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
emcc: error: '/hbc0d3/3rd/emsdk/node/12.18.1_64bit/bin/node /hbc0d3/3rd/emsdk/upstream/emscripten/src/compiler.js /var/folders/t4/lnryfz455bv8z9prf5ckyvdc0000gn/T/tmp45sv3y3s.txt' failed (1)
make[3]: *** [hbpp.js] Error 1
rm hbpp.o
make[2]: *** [descend] Error 2
make[1]: *** [pp] Error 2
make: *** [src] Error 2

Any suggestion?

**Comment by kripken** [comment]
This probably means the emscripten install is broken somehow, or has a bad local change. Doing `emcc --clear-cache` to force a rebuild may help. If not, the simplest thing might be to reinstall from scratch (or otherwise make sure there are no local changes).

**Comment by lailton** [comment]
Okay, I will try it. 
Thank you.

**Comment by lailton** [comment]
@kripken 
Yeah, I have recompiled everything from scratch then it works, thank you!
