### ISSUE TITLE
/usr/lib/emscripten/system/lib/compiler-rt/lib/builtins/gcc_personality_v0.c:11:10: fatal error: 'unwind.h' file not found

### ISSUE THREAD

**Issue by svenstaro** [emscripten-core/emscripten#11711]
After building release 1.39.20, I try to compile a trivial test file which fails. I deleted all `~/.emscripten*` files prior to running the tests.

emscripten 1.39.18 works fine.

This is for the official Arch Linux emscripten package. Package sources are [here](https://github.com/archlinux/svntogit-community/tree/packages/emscripten/trunk).
```
$ cat lol.c 
int main(int argc, char *argv[])
{
    
    return 0;
}
```

```
$ emcc -v lol.c
shared:INFO: EM_IGNORE_SANITY set, ignoring sanity checks
shared:INFO: EM_IGNORE_SANITY set, ignoring sanity checks
 "/usr/lib/emscripten-llvm/clang" -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=20 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/usr/lib/emscripten/system/include/compat -Xclang -isystem/usr/lib/emscripten/system/include -Xclang -isystem/usr/lib/emscripten/system/include/libc -Xclang -isystem/usr/lib/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/usr/lib/emscripten/system/local/include -Xclang -isystem/usr/lib/emscripten/system/include/SSE -Xclang -isystem/usr/lib/emscripten/system/lib/compiler-rt/include -Xclang -isystem/home/svenstaro/.emscripten_cache/wasm/include -DEMSCRIPTEN -fignore-exceptions -v lol.c -Xclang -isystem/usr/lib/emscripten/system/include/SDL -c -o /tmp/emscripten_temp_6w0sr3da/lol_0.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr
clang version 12.0.0 (/startdir/llvm-project 55fa315b0352b63454206600d6803fafacb42d5e)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/lib/emscripten-llvm
 (in-process)
 "/usr/lib/emscripten-llvm/clang-12" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name lol.c -mrelocation-model static -mframe-pointer=none -fno-rounding-math -mconstructor-aliases -target-cpu generic -fvisibility hidden -debugger-tuning=gdb -v -resource-dir /usr/lib/lib/clang/12.0.0 -D __EMSCRIPTEN_major__=1 -D __EMSCRIPTEN_minor__=39 -D __EMSCRIPTEN_tiny__=20 -D _LIBCPP_ABI_VERSION=2 -D unix -D __unix -D __unix__ -D EMSCRIPTEN -internal-isystem /usr/lib/lib/clang/12.0.0/include -internal-isystem /include/wasm32-emscripten -internal-isystem /include -Werror=implicit-function-declaration -fdebug-compilation-dir /tmp -ferror-limit 19 -fgnuc-version=4.2.1 -fignore-exceptions -fcolor-diagnostics -nostdsysteminc -isystem/usr/lib/emscripten/system/include/compat -isystem/usr/lib/emscripten/system/include -isystem/usr/lib/emscripten/system/include/libc -isystem/usr/lib/emscripten/system/lib/libc/musl/arch/emscripten -isystem/usr/lib/emscripten/system/local/include -isystem/usr/lib/emscripten/system/include/SSE -isystem/usr/lib/emscripten/system/lib/compiler-rt/include -isystem/home/svenstaro/.emscripten_cache/wasm/include -isystem/usr/lib/emscripten/system/include/SDL -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /tmp/emscripten_temp_6w0sr3da/lol_0.o -x c lol.c
clang -cc1 version 12.0.0 based upon LLVM 12.0.0git default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/home/svenstaro/.emscripten_cache/wasm/include"
ignoring nonexistent directory "/usr/lib/lib/clang/12.0.0/include"
ignoring nonexistent directory "/include/wasm32-emscripten"
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/emscripten/system/include/compat
 /usr/lib/emscripten/system/include
 /usr/lib/emscripten/system/include/libc
 /usr/lib/emscripten/system/lib/libc/musl/arch/emscripten
 /usr/lib/emscripten/system/local/include
 /usr/lib/emscripten/system/include/SSE
 /usr/lib/emscripten/system/lib/compiler-rt/include
 /usr/lib/emscripten/system/include/SDL
End of search list.
cache:INFO: generating system library: libcompiler_rt.a... (this will be cached in "/home/svenstaro/.emscripten_cache/wasm/libcompiler_rt.a" for subsequent builds)
/usr/lib/emscripten/system/lib/compiler-rt/lib/builtins/gcc_personality_v0.c:11:10: fatal error: 'unwind.h' file not found
#include <unwind.h>
         ^~~~~~~~~~
1 error generated.
emcc: error: '/usr/lib/emscripten-llvm/clang -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=20 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/usr/lib/emscripten/system/include/compat -Xclang -isystem/usr/lib/emscripten/system/include -Xclang -isystem/usr/lib/emscripten/system/include/libc -Xclang -isystem/usr/lib/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/usr/lib/emscripten/system/local/include -Xclang -isystem/usr/lib/emscripten/system/include/SSE -Xclang -isystem/usr/lib/emscripten/system/lib/compiler-rt/include -Xclang -isystem/home/svenstaro/.emscripten_cache/wasm/include -DEMSCRIPTEN -fignore-exceptions -Werror -O2 -fno-builtin -c /usr/lib/emscripten/system/lib/compiler-rt/lib/builtins/gcc_personality_v0.c -Xclang -isystem/usr/lib/emscripten/system/include/SDL -c -o /tmp/emscripten_temp_6w0sr3da/gcc_personality_v0.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/lib/emscripten/tools/system_libs.py", line 81, in run_one_command
    shared.run_process(cmd, stdout=stdout, stderr=stderr, env=safe_env)
  File "/usr/lib/emscripten/tools/shared.py", line 206, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/lib/emscripten/emcc', '-Werror', '-O2', '-fno-builtin', '-c', '/usr/lib/emscripten/system/lib/compiler-rt/lib/builtins/gcc_personality_v0.c', '-o', '/tmp/emscripten_temp_6w0sr3da/gcc_personality_v0.o', '-Wno-fastcomp']' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/emscripten/emcc.py", line 3964, in <module>
    sys.exit(run(sys.argv))
  File "/usr/lib/emscripten/emcc.py", line 2363, in run
    extra_files_to_link += system_libs.calculate([f for _, f in sorted(temp_files)] + extra_files_to_link, in_temp, link_as_cxx, forced=forced_stdlibs)
  File "/usr/lib/emscripten/tools/system_libs.py", line 1635, in calculate
    add_library(system_libs_map['libcompiler_rt'])
  File "/usr/lib/emscripten/tools/system_libs.py", line 1577, in add_library
    libs_to_link.append((lib.get_path(), need_whole_archive))
  File "/usr/lib/emscripten/tools/system_libs.py", line 342, in get_path
    return shared.Cache.get(self.get_filename(), self.build)
  File "/usr/lib/emscripten/tools/cache.py", line 130, in get
    temp = creator()
  File "/usr/lib/emscripten/tools/system_libs.py", line 389, in build
    create_lib(out_filename, self.build_objects())
  File "/usr/lib/emscripten/tools/system_libs.py", line 383, in build_objects
    run_build_commands(commands)
  File "/usr/lib/emscripten/tools/system_libs.py", line 95, in run_build_commands
    pool.map_async(run_one_command, commands, chunksize=1).get(999999)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
subprocess.CalledProcessError: Command '['/usr/lib/emscripten/emcc', '-Werror', '-O2', '-fno-builtin', '-c', '/usr/lib/emscripten/system/lib/compiler-rt/lib/builtins/gcc_personality_v0.c', '-o', '/tmp/emscripten_temp_6w0sr3da/gcc_personality_v0.o', '-Wno-fastcomp']' returned non-zero exit status 1.
```

**Comment by sbc100** [comment]
I think there are a couple of different things going on here perhaps.

I'm not quite sure how this could have worked for you in 1.39.18.   Can you try compiling (not linking) a simply C (not C++) file that includes unwind.h with 1.39.18 to confirm?   My only guess is that maybe compiler-rt changed to start requiring this header between 18 and 20..  Will confirm.

Historically we could expect to find unwind.h in clangs builtin header directory.  In this case on your system it would be `/usr/lib/lib/clang/12.0.0/include`.   Do you know why that header might be missing from that location?   IIUC clang installs `unwind.h` there.

e.g on ubuntu we have:  

```
$ dpkg -S /usr/lib/llvm-9/lib/clang/9.0.1/include/unwind.h
libclang-common-9-dev: /usr/lib/llvm-9/lib/clang/9.0.1/include/unwind.h
```

And in the emsdk bundled version of llvm we have this file too.  

Secondly, it looks like you are not the only one to have experienced this: https://github.com/emscripten-core/emscripten/pull/10497

This change fixed the problem when compiling C++ but not when compiling C code.   We should update that patch to add that include directory to c_include_paths instead.

But I'm still curious why your llvm doesn't include this file?

**Comment by sbc100** [comment]
Indeed, compiler-rt started depending on unwind.h in #11634
