### ISSUE TITLE
Add support for unsigned long long

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#11726]
I can't pass values like 149688835276 to C++ side using embind val's <as> and I believe it's great if someone can add support for this

**Comment by ClaudiaLapalme** [comment]
How about converting all integer types bigger than a `long` to `BigInt` in JavaScript?

**Comment by kripken** [comment]
The `WASM_BIGINT` flag provides general support for that. I don't know enough of embind internals to guess about if that means this already works with `emcc -s WASM_BIGINT`, but that's worth checking. If it doesn't work, then hopefully adding embind integration with that flag is not hard.

**Comment by cuberoot** [comment]
I have played with this a bit today. The answer is that embind does not automatically support 64-bit ints with `-s WASM_BIGINT`.

I am able to pass `int64_t` values through to JS code from C++ if I add this code on the C++ side:

```c++
namespace emscripten {
namespace internal {


EMSCRIPTEN_DEFINE_NATIVE_BINDING_TYPE(int64_t);

template <typename T>
struct TypeID<T,
              typename std::enable_if_t<
                  std::is_same<typename Canonicalized<T>::type, int64_t>::value>> {
    static constexpr TYPEID get() { return LightTypeID<int>::get(); }

}; // namespace internal

}
}
```

However, it is a hack because I used `LightTypeID<int>`. If I use `LightTypeID<int64_t>` I get an exception on the JS side:

```
UnboundTypeError {name: "UnboundTypeError", message: "Cannot call TestVal2 due to unbound types: x", stack: "UnboundTypeError: Cannot call TestVal2 due to unbo…host:8000/test.js:3182:11)↵    at <anonymous>:1:8"}message: "Cannot call TestVal2 due to unbound types: x"name: "UnboundTypeError"stack: "UnboundTypeError: Cannot call TestVal2 due to unbound types: x\n    at UnboundTypeError.<anonymous> (http://localhost:8000/test.js:1923:24)\n    at new UnboundTypeError (eval at createNamedFunction (http://localhost:8000/test.js:1910:14), <anonymous>:4:34)\n    at throwUnboundTypeError (http://localhost:8000/test.js:2703:13)\n    at Object.TestVal2 (http://localhost:8000/test.js:3182:11)\n    at <anonymous>:1:8"__proto__: Error
```

So, I think something has to be done on the JS side of embind to allow registration of the new type? I'm pretty new to embind, so I am just guessing here.

**Comment by kripken** [comment]
I believe this was fixed by #13889
