### ISSUE TITLE
Error using install under windows

### ISSUE THREAD

**Issue by yzg-github** [emscripten-core/emscripten#11741]
When I use .\emsdk install 1.39.20 under windows, the following error occurs. I am using python3.7.5. What is the reason?

Traceback (most recent call last):
  File "D:\Gitcode\emsdk/emsdk.py", line 3077, in <module>
    sys.exit(main())
  File "D:\Gitcode\emsdk/emsdk.py", line 3057, in main
    success = tool.install()
  File "D:\Gitcode\emsdk/emsdk.py", line 1813, in install
    return self.install_sdk()
  File "D:\Gitcode\emsdk/emsdk.py", line 1830, in install_sdk
    success = emscripten_npm_install(self, os.path.join(emsdk_path(), install_path, 'emscripten'))
  File "D:\Gitcode\emsdk/emsdk.py", line 1246, in emscripten_npm_install
    universal_newlines=True)
  File "C:\ProgramFiles\Python37\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\ProgramFiles\Python37\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramFiles\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramFiles\Python37\lib\subprocess.py", line 1208, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2]  The system can not find the file specified.

**Comment by sbc100** [comment]
Looks like its having trouble finding `npm` .. or `npm.cmd`.    Can you print the `npm` variable within `emscripten_npm_install`.

What shell are you using?

**Comment by yzg-github** [comment]
@sbc100
i can't find such filename like “emscripten_npm_install”，but i can find the directory containing the "nmp" file,in file folder:D:\Gitcode\emsdk\node\12.18.1_64bit\node_modules\npm.
i use windowspowershell V:5.1.14393.2189

**Comment by sbc100** [comment]
Does `emsdk install 1.39.20` work in the normal window shell (cmd.exe)?

**Comment by yzg-github** [comment]
@ sbc100
not yet.
there is the same error.

**Comment by sbc100** [comment]
Take a look at `emsdk.py`.. in that file you will see a function called `emscripten_npm_install`.   The code here is looking for a file called `npm.cmd` which should be installed in `node/12.18.1_64bit/bin`.

Can you check the the `npm.cmd` file exists for you?

Can you try printing the value of the `npm` variable within that function?

Can you trying completely removing the `node` directory and running the ` install 1.39.20` again?

**Comment by ricardoboss** [comment]
Experiencing the exact same issue in PowerShell 7 using `.\emsdk install latest`.

**Comment by sbc100** [comment]
Would you mind debugging to see what going on there exactly?     For example is the npm command really missing?   What can't python seem to execute it?

**Comment by ricardoboss** [comment]
So the npm executable was detected to be at `S:/repos/emscripten-core/emsdk/node/12.18.1_64bit\bin\npm.cmd`.

This file does not exist, but there is a file without `.cmd`. But this binary is 0KB in size, which seems strange to me: 
![image](https://user-images.githubusercontent.com/6266356/105907518-56212000-6025-11eb-8ef9-bce45de8d6a8.png)

Why don't you use the environments `npm`? Why ship your own one, which is clearly causing trouble?

**Comment by sbc100** [comment]
A couple of reasons we don't use the system npm:

1.  emsdk is designed to be self contained.  We explicitly want to avoid having user need to install other tools.   This is why we ship out own versions of both node and python.
2.  Depending on the system version node makes this kind of problem even more likely since we don't know how a given user installed node or what version they are using.  Shipping our own version of node is supposed to make this kinds of issue *less* frequent since we always know exactly what we dealing (because we installed it ourselves).   I believe this is true, and we would have lot more compatibility issues if we changed this policy.

**Comment by ricardoboss** [comment]
Okay, I understand what you are trying to achieve and I agree it would make things easier in terms of support. But on the other hand, there seems to be a problem with the stability of your tools installers:

1. They do not recognize a broken installation
2. They don't fix broken installations
3. The errors caused by broken installations aren't handled very user friendly (causing issues such as this to be opened, where you need to ask users to debug it themselves)

After manually deleting the "node" folder in the emsdk directory, node got installed properly. But then the next step failed (`npm ci`), outputting a few thousand "warn tar invalid entry" lines (so much for known stability when using your own version). Any idea what could be causing this?

**Comment by sbc100** [comment]
The linux and mac versions of node both ship the `node` binary alongside `npm` and `npx` which are symbol links to it so they would be of zero size.    So it kind of looks to me like you have the mac or linux version of node somehow?   

Can you try removing the node directory completely and then running `emsdk.bat install node-12.18.1-64bit`?  Does it download `https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v12.18.1-win-x64.zip`?

**Comment by sbc100** [comment]
There must be something unusual going on with you setup since we don't see this issue coming from most of our windows users.

Is it just a normal windows machine?  What shell are you using?  Is it some kind of virtual environment?   I believe we can address and fix all the issues you bring up here.

**Comment by ricardoboss** [comment]
I guess your last comment is outdated, since removing the "node" directory fixed it for me.

On behalf of the other issue I mentioned, this is the output from npm when I manually try to install it:
```
PS S:\repos\emscripten-core\emsdk\upstream\emscripten> npm ci --production --no-optional
npm WARN tarball cached data for google-closure-compiler-java@20200920.0.0 (sha512-q8m/+QLBWrzjg5VZ2b4B628zDvbi0Gyenj9bvZQlPY7mqj68HXhe5aOfKzZO7vXgHDXMvsvI3v/1g5mPAku/5w==) seems to be corrupted. Refreshing cache.
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
...
```

I am using PowerShell 7.1.1 (as I already stated) on Windows 10 Pro.

**Comment by sbc100** [comment]
This error now looks like a general issue with `npm`.. it doesn't seem realed to emscripten or emsdk (not that we shouldn't get the bottom of it).   Can you run `npm install google-closure-compiler` outside of emscripten (and without our version npm PATH?). 

I'm also still curious how you could and ended up with what looks like the mac (or linux) version of node in place of the windows one, but I'm glad its fixed now.

**Comment by sbc100** [comment]
When you ran `npm ci --production --no-optional` above was that with the emsdk version of node in your PATH or some other version?

**Comment by ricardoboss** [comment]
Installing `google-closure-compiler` worked in a temporary directory:

```
PS S:\repos\tmp> npm install google-closure-compiler
npm WARN saveError ENOENT: no such file or directory, open 'S:\repos\tmp\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: google-closure-compiler-linux@^20210106.0.0 (node_modules\google-closure-compiler\node_modules\google-closure-compiler-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for google-closure-compiler-linux@20210106.0.0: wanted {"os":"linux","arch":"x64,x86"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: google-closure-compiler-osx@^20210106.0.0 (node_modules\google-closure-compiler\node_modules\google-closure-compiler-osx):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for google-closure-compiler-osx@20210106.0.0: wanted {"os":"darwin","arch":"x64,x86"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'S:\repos\tmp\package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

+ google-closure-compiler@20210106.0.0
added 28 packages from 73 contributors and audited 30 packages in 24.331s
found 0 vulnerabilities
```

This (and the `npm ci` from before) was using my local `npm`, version 6.14.10 w/ node v14.15.4 (LTS).

**Comment by ricardoboss** [comment]
I cleared some local caches and executed the `npm ci` command using your npm binary and it seems to work.
After executing `.\emsdk install latest` from the root again, it worked aswell.
Seems like there where some broken caches on my end and yes, you are correct that this has nothing to do with emscripten. Thanks for your help so far!

**Comment by sbc100** [comment]
Awesome!  Thanks for your patience
