### ISSUE TITLE
Exception while running emscripten_wget_data method with ASYNCIFY under nodejs

### ISSUE THREAD

**Issue by nikhilso** [emscripten-core/emscripten#11894]
I have compiled WASM binary using Emscripten (UpStream) 1.39.13 SDK. I use ASYNCIFY option with emscripten_wget_data method. My WASM is running under nodejs. But when i run the script it gives me following error.
ASYNCIFY: start unwind 5877656
 ASYNCIFY:        try asyncify_start_unwind
 ASYNCIFY:        finally asyncify_start_unwind
 ASYNCIFY:      finally dynCall_iii
 ASYNCIFY:    finally main
 ASYNCIFY: stop unwind
 ASYNCIFY:    try asyncify_stop_unwind
 ASYNCIFY:    finally asyncify_stop_unwind
 exception thrown: import emscripten_asm_const_iii was not in ASYNCIFY_IMPORTS, but changed the state
Any help in debugging the problem
Where does import emscripten_asm_const_iii comes from?

**Comment by kripken** [comment]
`emscripten_asm_const_iii` is how EM_ASM calls are implemented. I think that means it's an EM_ASM returning an i32 and receiving two i32s as parameters. Adding that function to the asyncify imports should fix things I hope.

**Comment by nikhilso** [comment]
Thanks Kripken, but i am using emscripten_wget_data standard function with -s ASYNCIFY=1 as compiler option. Is there anything which i need to fix on the settings?

**Comment by kripken** [comment]
Sorry if I wasn't clear - does my suggestion to add that function to the asyncify imports not help? That is, build with `-s ASYNCIFY_IMPORTS=[emscripten_asm_const_iii]`?

**Comment by nikhilso** [comment]
Let me try it while i compile it, but is the syntax -s ASYNCIFY_IMPORTS=[emscripten_asm_const_iii] correct. I thought its -s ASYNCIFY_IMPORTS=['emscripten_asm_const_iii'].

**Comment by kripken** [comment]
I think the commandline parser is smart enough to not need quotes in cases like that. But it may depend on the shell environment you are in. Maybe try quotes if it doesn't work without them.

**Comment by nikhilso** [comment]
Hello Kripken,

The error related to imports gone after i added the entry for emscripten_asm_const_iii. But now i get another error.
I am trying to dowload http URL using emscripten_wget_data. 
Here are my project settings.
-O0 --bind --memory-init-file 0 -s MAX_WEBGL_VERSION=2 -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=268435456 -s GL_PREINITIALIZED_CONTEXT=1 -s NODERAWFS=1 --emit-symbol-map -s ENVIRONMENT=node -s ASYNCIFY=1 -s ASYNCIFY_IMPORTS=[emscripten_asm_const_iii,emscripten_wget_data] -s ASYNCIFY_IGNORE_INDIRECT=1 -s ASYNCIFY_DEBUG=2 -s ASSERTIONS=1 -g --source-map-base http://127.0.0.1:8080 

Below is the error i am getting.
         ASYNCIFY:      finally malloc
         ASYNCIFY:      try dynCall_iii
         ASYNCIFY: handleSleep 0
         ASYNCIFY:        try malloc
         ASYNCIFY:        finally malloc
         ASYNCIFY: setDataRewindFunc(6039120), bottomOfCallStack is main Error
    at Object.setDataRewindFunc (*.wasm.js:10577:94)
    at Object.allocateData (*.wasm.js:10570:18)
    at Object.handleSleep (*.wasm.js:10646:42)
    at _emscripten_wget_data (*.wasm.js:8770:16)
	
----------------------------------------------------------------------------
         ASYNCIFY: start: function() {
                Asyncify.exportCallStack.push(x);
                err('ASYNCIFY: ' + '  '.repeat(Asyncify.exportCallStack.length) + ' try', x);
                try {
                  return original.apply(null, arguments);
                } finally {
                  if (ABORT) return;
                  var y = Asyncify.exportCallStack.pop(x);
                  assert(y === x);
                  err('ASYNCIFY: ' + '  '.repeat(Asyncify.exportCallStack.length + 1) + ' finally', x);
                  if (Asyncify.currData &&
                      Asyncify.state === Asyncify.State.Unwinding &&
                      Asyncify.exportCallStack.length === 0) {
                    // We just finished unwinding.
                    err('ASYNCIFY: stop unwind');
                    Asyncify.state = Asyncify.State.Normal;
                    runAndAbortIfError(Module['_asyncify_stop_unwind']);
                    if (typeof Fibers !== 'undefined') {
                      Fibers.trampoline();
                    }
                    if (Asyncify.afterUnwind) {
                      Asyncify.afterUnwind();
                      Asyncify.afterUnwind = null;
                    }
                  }
                }
              }
         ASYNCIFY:    try main
         ASYNCIFY:    finally main
         RuntimeError: unreachable
         RuntimeError: unreachable
*file.wasm.js:150
      throw ex;
      ^

RuntimeError: abort(RuntimeError: unreachable) at Error
    at jsStackTrace (*.wasm.js:1916:17)
    at stackTrace (*.wasm.js:1933:16)
    at process.abort (*.wasm.js:1660:44)
    at process.emit (events.js:198:13)
    at process.EventEmitter.emit (domain.js:448:20)
    at emitPromiseRejectionWarnings (internal/process/promises.js:119:20)
    at process._tickCallback (internal/process/next_tick.js:69:34)
    at process.abort (*.wasm.js:1666:9)
    at process.emit (events.js:198:13)
    at process.EventEmitter.emit (domain.js:448:20)
    at emitPromiseRejectionWarnings (internal/process/promises.js:119:20)
    at process._tickCallback (internal/process/next_tick.js:69:34)	

Can you help in analyzing this problem?
