### ISSUE TITLE
How to debug emscripten::val BindingError (has unknown type)

### ISSUE THREAD

**Issue by BKAUTO** [emscripten-core/emscripten#12022]
Hello,

I ran into a emscripten::val Binding Error when running the .wasm in browser.

The C++ code is:

```
void Logger::log(int level, const char* fileName, const char* functionName, int lineNumber,
	std::string msg) {
	long long timestamp = std::chrono::system_clock::now().time_since_epoch().count();
	emscripten::val entry = emscripten::val::object();
	entry.set("file", fileName);
	entry.set("timestamp", (double)(timestamp / 1000));
	entry.set("level", level);
	entry.set("functionName", functionName);
	entry.set("lineNumber", lineNumber);
	entry.set("msg", msg);
	logsArray.call<void>("push", entry);
};
```

And the browser console output:

```
"BindingError: _emval_take_value has unknown type d
    at BindingError.<anonymous> (https://static.mastergo.com/static/resources/b943ed5d/masterkit.js:4608:15)
    at new BindingError (eval at createNamedFunction (https://static.mastergo.com/static/resources/b943ed5d/masterkit.js:4601:9), <anonymous>:4:34)
    at throwBindingError (https://static.mastergo.com/static/resources/b943ed5d/masterkit.js:4628:8)
    at requireRegisteredType (https://static.mastergo.com/static/resources/b943ed5d/masterkit.js:5334:3)
    at __emval_take_value (https://static.mastergo.com/static/resources/b943ed5d/masterkit.js:5498:9)
    at emscripten::val::val<double const&>(double const&) (https://static.mastergo.com/static/resources/b943ed5d/masterkit.wasm:wasm-function[1663]:0x2bd9c)
    at void emscripten::val::set<char [10], double>(char const (&) [10], double const&) (https://static.mastergo.com/static/resources/b943ed5d/masterkit.wasm:wasm-function[1659]:0x2bc83)
    at Logger::log(int, char const*, char const*, int, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >) (https://static.mastergo.com/static/resources/b943ed5d/masterkit.wasm:wasm-function[1656]:0x2bb8b)
    at EmscriptenBindingInitializer_MasterKit::EmscriptenBindingInitializer_MasterKit() (https://static.mastergo.com/static/resources/b943ed5d/masterkit.wasm:wasm-function[1405]:0x249f4)
    at __wasm_call_ctors (https://static.mastergo.com/static/resources/b943ed5d/masterkit.wasm:wasm-function[487]:0x10b9b)"
```
It seems like the val::set() function is not working correctly. If I annotate all such set() functions, it goes like:
```
"BindingError: parameter 0 has unknown type v
    at BindingError.<anonymous> (https://static.mastergo.com/static/resources/dc37a915/masterkit.js:4608:15)
    at new BindingError (eval at createNamedFunction (https://static.mastergo.com/static/resources/dc37a915/masterkit.js:4601:9), <anonymous>:4:34)
    at throwBindingError (https://static.mastergo.com/static/resources/dc37a915/masterkit.js:4628:8)
    at requireRegisteredType (https://static.mastergo.com/static/resources/dc37a915/masterkit.js:5334:3)
    at __emval_lookupTypes (https://static.mastergo.com/static/resources/dc37a915/masterkit.js:5414:10)
    at __emval_get_method_caller (https://static.mastergo.com/static/resources/dc37a915/masterkit.js:5420:14)
    at emscripten::internal::Signature<void, emscripten::val&>::init_method_caller() (https://static.mastergo.com/static/resources/dc37a915/masterkit.wasm:wasm-function[1664]:0x2b8e3)
    at emscripten::internal::Signature<void, emscripten::val&>::get_method_caller() (https://static.mastergo.com/static/resources/dc37a915/masterkit.wasm:wasm-function[1662]:0x2b865)
    at emscripten::internal::MethodCaller<void, emscripten::val&>::call(emscripten::internal::_EM_VAL*, char const*, emscripten::val&) (https://static.mastergo.com/static/resources/dc37a915/masterkit.wasm:wasm-function[1659]:0x2b71a)
    at void emscripten::val::call<void, emscripten::val&>(char const*, emscripten::val&) const (https://static.mastergo.com/static/resources/dc37a915/masterkit.wasm:wasm-function[1658]:0x2b6fc)"
```
The val::call() function may emit an error. For the error description is not so clear, how can I quickly locate the bug in my code?

**Comment by m-peko** [comment]
@BKAUTO have you found a way to debug this?
