### ISSUE TITLE
Support for BigInt in pthreads proxy code

### ISSUE THREAD

**Issue by kleisauke** [emscripten-core/emscripten#12079]
A call to `fseek` within a thread compiled with support for JS BigInt to Wasm i64 integration (`-s WASM_BIGINT=1`) seems to fail. Here is a simplified test case:

```python
  def test_noderawfs_pthread_bigint(self):
    fopen_write = open(path_from_root('tests', 'asmfs', 'fopen_write.cpp')).read()
    create_test_file('main.cpp', fopen_write)
    self.run_process([EMCC, 'main.cpp', '-s', 'EXIT_RUNTIME=1', '-s', 'NODERAWFS=1', '-s', 'USE_PTHREADS=1', '-s', 'PROXY_TO_PTHREAD', '-s', 'WASM_BIGINT=1'])
    out = self.run_js('a.out.js', engine=NODE_JS + ['--experimental-wasm-threads', '--experimental-wasm-bigint'])
    self.assertContained("read 11 bytes. Result: Hello data!", out)

    # NODERAWFS should directly write on OS file system
    self.assertEqual("Hello data!", open('hello_file.txt').read())
```

```javascript
a.worker.js:1 TypeError: Cannot convert a BigInt value to a number
    at _emscripten_proxy_to_main_thread_js (a.out.js:9)
    at _fd_seek (a.out.js:9)
```

<details>
  <summary>Output</summary>
  
```
$ python tests/runner.py other.test_noderawfs_pthread_bigint
shared:INFO: (Emscripten: Running sanity checks)
test_noderawfs_pthread_bigint (test_other.other) ... FAIL

======================================================================
FAIL: test_noderawfs_pthread_bigint (test_other.other)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kleisauke/emscripten/tests/test_other.py", line 7643, in test_noderawfs_pthread_bigint
    self.assertContained("read 11 bytes. Result: Hello data!", out)
  File "/home/kleisauke/emscripten/tests/runner.py", line 740, in assertContained
    self.fail("Expected to find '%s' in '%s', diff:\n\n%s\n%s" % (
AssertionError: Expected to find 'read 11 bytes. Result: Hello data!' in 'worker.js onmessage() captured an uncaught exception: TypeError: Cannot convert a BigInt value to a number
pthread sent an error! undefined:undefined: Cannot convert a BigInt value to a number
', diff:

--- expected
+++ actual
@@ -1 +1,3 @@
-read 11 bytes. Result: Hello data!
+worker.js onmessage() captured an uncaught exception: TypeError: Cannot convert a BigInt value to a number
+pthread sent an error! undefined:undefined: Cannot convert a BigInt value to a number
+



----------------------------------------------------------------------
Ran 1 test in 0.510s

FAILED (failures=1)
Test suites:
['test_other']
Running test_other: (1 tests)
(checking sanity from test runner)
```
</details>

Removing the `-s WASM_BIGINT=1` compiler flag in the above test case will make it pass.

**Comment by kripken** [comment]
Looking into this, the issue is that the proxying code assumes all JS values are Numbers,
```javascript
    function _emscripten_receive_on_main_thread_js(index, numCallArgs, args) {
      _emscripten_receive_on_main_thread_js_callArgs.length = numCallArgs;
      var b = args >> 3;
      for (var i = 0; i < numCallArgs; i++) {
        _emscripten_receive_on_main_thread_js_callArgs[i] = HEAPF64[b + i];
      }
```
(and we proxy a call to fd_seek which has an i64). HEAPF64 there works ok for int32s and float64s, but not for a BigInt representing an i64. We would need to use a [BigInt64Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array) there, and also I think we would need to send the signature so we know the type of each argument - right now, we just store float64s for them all.
