### ISSUE TITLE
Install fail on Win10 by emsdk

### ISSUE THREAD

**Issue by zjxpcyc** [emscripten-core/emscripten#12235]
I installed python3.8 . And set env PYTHON="xxx"

Then I followed [https://emscripten.org/docs/getting_started/downloads.html](https://emscripten.org/docs/getting_started/downloads.html)

Then I got an error:

```bat
>emsdk activate latest
Traceback (most recent call last):
  File "D:\Application\emsdk\\emsdk.py", line 13, in <module>
    import multiprocessing
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 16, in <module>
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\context.py", line 6, in <module>
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\reduction.py", line 16, in <module>
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\socket.py", line 49, in <module>
ImportError: Module use of python38.dll conflicts with this version of Python.
```

And I cann't find the path `D:\obj\windows-release\`

In emsdk install floder, I found a python installed, and the versio is 3.7.4

**Comment by sbc100** [comment]
Can you check if you have PYTHONHOME set in your environment?  And if so can you remove it?  

This looks like it could be related to https://github.com/emscripten-core/emsdk/pull/600

You should not need to set any envrionment variables when you install python.  Just having the python directory in your PATH should be enough.

**Comment by zjxpcyc** [comment]
Not found `PYTHONHOME`, but got `PYTHONPAHT`.

I removed it , and installed successful

Thx
