### ISSUE TITLE
AsyncCompile error when trying to launch the hello world gRPC example  

### ISSUE THREAD

**Issue by itamarsher** [emscripten-core/emscripten#12257]
I've built the helloworld example from the gRPC github repo (it took some work), however, when I try to launch the greeter_server using node I'm getting the following error: RuntimeError: abort(CompileError: AsyncCompile: Wasm decoding failed: unexpected section: Code @+37085)

I've opened an issue on the gRPC repo as well in case it's not an Emscripten issue.
https://github.com/grpc/grpc/issues/24166

I can provide the compiled example files if needed

Tools versions:
Emsdk: 1.39.20
Node: 12.8.1

**Comment by kripken** [comment]
Possibly it's something like bulk memory (for pthreads) in a VM that does not support it. Please try a newer node, and build with `-s ASSERTIONS` which may show more information.

If that's not it, please provide that wasm file. Looking at `Code @+37085` would show what section is not recognized there.

**Comment by itamarsher** [comment]
Is bulk memory a feature that needs manual activation? I tried running it node V12.18.4 and got the same error.
This is the command line is use to execute greeter_server.js:
```node --experimental-wasm-threads --experimental-worker  greeter_server.js```
I'm attaching the .js .worker.js and .wasm files
[greeter_server.zip](https://github.com/emscripten-core/emscripten/files/5250174/greeter_server.zip)

**Comment by kleisauke** [comment]
Could you try passing the `--experimental-wasm-bulk-memory` flag to Node?

**Comment by itamarsher** [comment]
Okay! that actually moved things forward a bit, though now I'm not sure it's an Emscripten issue anymore. Care to explain what made you suspicious that this was the root cause? I'd love to understand it better (because the error code wasn't very indicative). 

```
node --experimental-wasm-threads --experimental-worker --experimental-wasm-bulk-memory greeter_server.js
E0919 20:05:53.487000000  632752 cpu_posix.cc:41]                      Cannot determine number of CPUs: assuming 1
E0919 20:05:53.504000000  632752 socket_utils_common_posix.cc:223]     check for SO_REUSEPORT: {"created":"@1600535153.504000000","description":"Protocol not available","errno":50,"file":"~/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":198,"os_error":"Protocol not available","syscall":"setsockopt(SO_REUSEPORT)"}
E0919 20:05:53.506000000  632752 server_chttp2.cc:40]                  {"created":"@1600535153.505000000","description":"No address added out of total 1 resolved","file":"~/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":307,"referenced_errors":[{"created":"@1600535153.505000000","description":"Failed to add any wildcard listeners","file":"~/grpc/src/core/lib/iomgr/tcp_server_posix.cc","file_line":341,"referenced_errors":[{"created":"@1600535153.505000000","description":"Unable to configure socket","fd":3,"file":"~/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":215,"referenced_errors":[{"created":"@1600535153.505000000","description":"Protocol not available","errno":50,"file":"~/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":239,"os_error":"Protocol not available","syscall":"setsockopt(TCP_NODELAY)"}]},{"created":"@1600535153.505000000","description":"Unable to configure socket","fd":3,"file":"~/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":215,"referenced_errors":[{"created":"@1600535153.505000000","description":"Protocol not available","errno":50,"file":"~/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":239,"os_error":"Protocol not available","syscall":"setsockopt(TCP_NODELAY)"}]}]}]}
Server listening on 0.0.0.0:50051
exception thrown: RuntimeError: memory access out of bounds,RuntimeError: memory access out of bounds
    at <anonymous>:wasm-function[61]:0x9d26
    at main (<anonymous>:wasm-function[63]:0x9e6f)
    at ~/grpc/examples/cpp/helloworld/cmake/build/greeter_server.js:1:26530
    at callMain (~/grpc/examples/cpp/helloworld/cmake/build/greeter_server.js:1:211052)
    at doRun (~/grpc/examples/cpp/helloworld/cmake/build/greeter_server.js:1:211649)
    at run (~/grpc/examples/cpp/helloworld/cmake/build/greeter_server.js:1:211821)
    at runCaller (~/grpc/examples/cpp/helloworld/cmake/build/greeter_server.js:1:210458)
    at removeRunDependency (~/grpc/examples/cpp/helloworld/cmake/build/greeter_server.js:1:25341)
    at receiveInstance (~/grpc/examples/cpp/helloworld/cmake/build/greeter_server.js:1:27553)
    at receiveInstantiatedSource (~/grpc/examples/cpp/helloworld/cmake/build/greeter_server.js:1:27883)

```

**Comment by kleisauke** [comment]
Are you sure that you used Node v12.18.4? Enabling this flag is only needed on older Node.js versions (see https://github.com/v8/v8/commit/af1988f1e43d663167ea1566983aa3a7ff625701). For example, this is what I see on Node v12.18.3:
```bash
$ node -v
v12.18.3
$ node --v8-options | grep bulk-memory -A 1
  --experimental-wasm-bulk-memory (enable prototype bulk memory opcodes for wasm)
        type: bool  default: true
```

fwiw, here's the output when I run your JS file:
<details><summary>Details</summary>

```bash
$ node --experimental-wasm-threads greeter_server.js
E0919 19:22:41.812000000  632752 cpu_posix.cc:41]                      Cannot determine number of CPUs: assuming 1
E0919 19:22:41.874000000  632752 socket_utils_common_posix.cc:223]     check for SO_REUSEPORT: {"created":"@1600536161.874000000","description":"Protocol not available","errno":50,"file":"/home/t85-itamars/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":198,"os_error":"Protocol not available","syscall":"setsockopt(SO_REUSEPORT)"}
E0919 19:22:41.877000000  632752 server_chttp2.cc:40]                  {"created":"@1600536161.876000000","description":"No address added out of total 1 resolved","file":"/home/t85-itamars/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":307,"referenced_errors":[{"created":"@1600536161.876000000","description":"Failed to add any wildcard listeners","file":"/home/t85-itamars/grpc/src/core/lib/iomgr/tcp_server_posix.cc","file_line":341,"referenced_errors":[{"created":"@1600536161.876000000","description":"Unable to configure socket","fd":3,"file":"/home/t85-itamars/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":215,"referenced_errors":[{"created":"@1600536161.876000000","description":"Protocol not available","errno":50,"file":"/home/t85-itamars/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":239,"os_error":"Protocol not available","syscall":"setsockopt(TCP_NODELAY)"}]},{"created":"@1600536161.876000000","description":"Unable to configure socket","fd":3,"file":"/home/t85-itamars/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":215,"referenced_errors":[{"created":"@1600536161.876000000","description":"Protocol not available","errno":50,"file":"/home/t85-itamars/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":239,"os_error":"Protocol not available","syscall":"setsockopt(TCP_NODELAY)"}]}]}]}
Server listening on 0.0.0.0:50051
exception thrown: RuntimeError: memory access out of bounds,RuntimeError: memory access out of bounds
    at wasm-function[61]:0x9d26
    at wasm-function[63]:0x9e6f
    at /home/kleisauke/greeter_server.js:1:26530
    at callMain (/home/kleisauke/greeter_server.js:1:211052)
    at doRun (/home/kleisauke/greeter_server.js:1:211649)
    at run (/home/kleisauke/greeter_server.js:1:211821)
    at runCaller (/home/kleisauke/greeter_server.js:1:210458)
    at removeRunDependency (/home/kleisauke/greeter_server.js:1:25341)
    at receiveInstance (/home/kleisauke/greeter_server.js:1:27553)
    at receiveInstantiatedSource (/home/kleisauke/greeter_server.js:1:27883)
```
</details>

**Comment by itamarsher** [comment]
@kleisauke I ran it later on version V14.11.0. I get the same output that you had. It's interesting to note that when I'm debugging with the developer tools I get SIGSEGV while this exception is thrown
