### ISSUE TITLE
Question: Module variables are not defined in `Module.onRuntimeInitialized` even after variables are imported

### ISSUE THREAD

**Issue by UnHumbleBen** [emscripten-core/emscripten#12286]
Not sure if this is the right place to ask question, but I'm trying to follow the steps from [this OpenCV tutorial](https://docs.opencv.org/3.4/dc/de6/tutorial_js_nodejs.html#minimal-example):
The minimal example is what I am having trouble running:
> __example1.js__:
```javascript
// Define a global variable 'Module' with a method 'onRuntimeInitialized':
Module = {
  onRuntimeInitialized() {
    // this is our application:
    console.log(cv.getBuildInformation())
  }
}
// Load 'opencv.js' assigning the value to the global variable 'cv'
cv = require('./opencv.js')
```
Execute with:
```
node example1.js
```

I get this error message:
```
/tmp/opencv-tutorial/using-opencv-in-node-js/opencv.js:21
var Module;if(!Module)Module=(typeof cv!=="undefined"?cv:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMEN

ReferenceError: cv is not defined
    at Object.onRuntimeInitialized (/tmp/opencv-tutorial/using-opencv-in-node-js/example1.js:5:17)
    at doRun (/tmp/opencv-tutorial/using-opencv-in-node-js/opencv.js:56:18338)
    at run (/tmp/opencv-tutorial/using-opencv-in-node-js/opencv.js:56:18560)
    at cv (/tmp/opencv-tutorial/using-opencv-in-node-js/opencv.js:56:19694)
    at /tmp/opencv-tutorial/using-opencv-in-node-js/opencv.js:70:10
    at /tmp/opencv-tutorial/using-opencv-in-node-js/opencv.js:11:22
    at Object.<anonymous> (/tmp/opencv-tutorial/using-opencv-in-node-js/opencv.js:16:2)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
```

When I run the debugger, and debug the `onRuntimeInitialized` function, I do not see`cv` declared anywhere, even though `onRuntimeInitialized` is called *after* the cv import

# Additional Info:
I am using [opencv.js version 3.4.0](https://docs.opencv.org/3.4.0/opencv.js).

I don't think there is anything wrong with the opencv file because a normal `require` works just fine:

```javascript
cv = require('./opencv.js')
console.log(cv.getBuildInformation())
```

**Comment by UnHumbleBen** [comment]
Strangely enough, adding `setTimeout`, even for 0 time makes the example work:

```javascript
// Define a global variable 'Module' with a method 'onRuntimeInitialized':
Module = {
  onRuntimeInitialized() {
    setTimeout(() => {
      // this is our application:
      console.log(cv.getBuildInformation())
    }, 0);
  }
}
// Load 'opencv.js' assigning the value to the global variable 'cv'
cv = require('./opencv.js')
```
