### ISSUE TITLE
building.py uses bogus python path on Windows

### ISSUE THREAD

**Issue by mmcparlane** [emscripten-core/emscripten#12376]
When running emconfigure it seems a bogus python path is referenced by the emconfigure script.
Error message:

```
configure: ./configure
Traceback (most recent call last):
  File "c:\emsdk\upstream\emscripten\\emconfigure.py", line 52, in <module>
    sys.exit(run())
  File "c:\emsdk\upstream\emscripten\\emconfigure.py", line 45, in run
    building.configure(sys.argv[1:])
  File "c:\emsdk\upstream\emscripten\tools\building.py", line 339, in configure
    run_process(args, stdout=stdout, stderr=stderr, env=env, **kwargs)
  File "c:\emsdk\upstream\emscripten\tools\shared.py", line 205, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 472, in run
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 775, in __init__
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 1178, in _execute_child
OSError: [WinError 193] %1 is not a valid Win32 application
```

My environment uses emsdk 2.0.5 with the following in .emscripten:

```
import os
emsdk_path = os.path.dirname(os.environ.get('EM_CONFIG')).replace('\\', '/')
NODE_JS = emsdk_path + '/node/12.18.1_64bit/bin/node.exe'
PYTHON = emsdk_path + '/python/3.7.4-pywin32_64bit/python.exe'
JAVA = emsdk_path + '/java/8.152_64bit/bin/java.exe'
LLVM_ROOT = emsdk_path + '/upstream/bin'
BINARYEN_ROOT = emsdk_path + '/upstream'
EMSCRIPTEN_ROOT = emsdk_path + '/upstream/emscripten'
TEMP_DIR = emsdk_path + '/tmp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]
```

**Comment by sbc100** [comment]
Do you have PYTHONHOME set in your environment by any chance?    Can you try unsetting it?  

I made a change recently to have emsdk_env unset this: https://github.com/emscripten-core/emsdk/pull/600

However this will only effect the current command prompt I believe.

**Comment by sbc100** [comment]
Oh, can can you tell me what the value of PYTHONHOME is on your system?  Any any idea what set it there in your envrionment?

**Comment by sbc100** [comment]
Also even once you have fixed that it looks like you will also need to somehow tell emconfigure how to run your configure script.   On windows presumably you can't just run a configure script since its a text file.  You will need to run it under a bash shell.   So something like `emconfigure /path/to/bash configure`?   

Are you aware the running autoconf-generated shell scripts on windows is unlikely to work?    At least not without some kind mingw/msys thing installed.

**Comment by mmcparlane** [comment]
@sbc100 Thanks for the prompt reply.

I was able to get configure to work using my msys2 install. I checked with the emsdk-installed mingw64 and it doesn't have the sh.exe (or other common utilities like sed.exe, etc.) installed by default. If possible it might be nice to have those included with the emsdk mingw download too 😉

I am running into another issue though once emmake is run that seems to have stripped some path separators:

```
emmake make
make: make
make  all-am
make[1]: Entering directory '/c/Users/mtmcp/Documents/grafX2/3rdparty/archives/jpeg-9d'
  CC       cjpeg.o
./depcomp: line 772: exec: c:emsdkupstreamemscriptenemcc.bat: not found
make[1]: *** [Makefile:769: cjpeg.o] Error 127
make[1]: Leaving directory '/c/Users/mtmcp/Documents/grafX2/3rdparty/archives/jpeg-9d'
make: *** [Makefile:526: all] Error 2

```

**Comment by mmcparlane** [comment]
I did a string replace in the autoconf-generated files: `libtool` and `Makefile` to use `/c/emsdk/*` instead of `C:\emsdk` and the libjpeg build succeeded.

So, it seems like there's some sort of bug still with paths on Windows. Should the EMSDK system replace `c:\` with `c:/` or does emconfigure need to be invoked expecting to use an msys2 or mingw environment, and hence replace `c:\` with `/c/` (or d:, etc)?

My `.emscripten` file seems to have normalized paths in it so I'm not quite sure where the mishap is occurring.

```
import os
emsdk_path = os.path.dirname(os.environ.get('EM_CONFIG')).replace('\\', '/')
NODE_JS = emsdk_path + '/node/12.18.1_64bit/bin/node.exe'
PYTHON = emsdk_path + '/python/3.7.4-pywin32_64bit/python.exe'
JAVA = emsdk_path + '/java/8.152_64bit/bin/java.exe'
LLVM_ROOT = emsdk_path + '/upstream/bin'
BINARYEN_ROOT = emsdk_path + '/upstream'
EMSCRIPTEN_ROOT = emsdk_path + '/upstream/emscripten'
TEMP_DIR = emsdk_path + '/tmp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

```

**Comment by mmcparlane** [comment]
Strange... I just noticed also that when calling `emsdk_env.bat` I get a subtle note on a missing drive as well: `The system cannot find the drive specified.`.

```
c:\emsdk>emsdk_env.bat
The system cannot find the drive specified.
Adding directories to PATH:
PATH += c:\emsdk
PATH += c:\emsdk\upstream\emscripten
PATH += c:\emsdk\node\12.18.1_64bit\bin
PATH += c:\emsdk\java\8.152_64bit\bin

Setting environment variables:
EMSDK = c:/emsdk
EM_CONFIG = c:\emsdk\.emscripten
EM_CACHE = c:/emsdk/upstream/emscripten\cache
EMSDK_NODE = c:\emsdk\node\12.18.1_64bit\bin\node.exe
EMSDK_PYTHON = c:\emsdk\python\3.7.4-pywin32_64bit\python.exe
JAVA_HOME = c:\emsdk\java\8.152_64bit

```

**Comment by mmcparlane** [comment]
I have just confirmed this also builds when changing the paths from `c:\` to `c:/` and replacing all `\` with `/` in Makefile and libtool files generated by autoconf (as opposed to /c/). This implies that normalizing path separators in `emconfigure` _should_ fix this problem and in general make things play nicer with msys2.

**Comment by sbc100** [comment]
I think one problem will be that emconfigure doesn't know its running on msys2 since I imagine you are using the windows version python to run emconfigure.   It thinks "hey I'm on windows so that right thing to do is use windows paths".     Ideas/patches welcome.  There are other buts open related to msys2 and windows that you might want to coordinate with.   e.g. https://github.com/emscripten-core/emsdk/issues/385

It could be argued that emsdk should have set unix-style envrionment variables when running on msys2 .. which would make this bug a emsdk bug rather than an emscripten bug.

I'm not clear how environment variables are supposed to work in this mixed context.  I mean we want EMSDK_NODE environment variable to work in both windows contests and msys2 contexts right?     Doesn't msys2 not have an existing way to deal with such things?

**Comment by mmcparlane** [comment]
I can see two primary scenarios for Windows with detection at emsdk-activation time:

1. Within Cmd running  `emsdk activate` ensures that the current environment _is not_ supposed to be run with configure/make style builds (due to the dependence on Unix utilities not present by default on Windows). It may use other build systems like CMake though. This will set paths using the system "\\" delimiter.

2. Within a MinTTY run `emsdk activate` followed by configure/make style builds (or others like CMake as supported by Unix systems). This sets paths using the Posix "/" delimiter and replaces "c:\\" with "/c/" or "c:/".

However, it seems the problems need to be fixed in the emscripten repo (maybe in `tools/shared.py` script), so changes could be introduced to detect the "msys" versus "win32" platforms (see below) and adjust the paths accordingly. As it stands, the problem lies not in the main paths like `EMSDK_NODE` but in the ones generated from those like `EMCC = bat_suffix(path_from_root('emcc'))`.

This will give the user flexibility to specify which set up they want by opening a particular shell instead of keeping it fixed based on which one executes the emsdk commands.

MinTTY:
```
$ python
Python 3.8.5 (default, Sep  4 2020, 09:00:02)
[GCC 9.3.0] on msys
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.platform
'msys'
```

Cmd:
```
c:\emsdk\python\3.7.4-pywin32_64bit\python.exe
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.platform
'win32'
```

**Comment by sbc100** [comment]
But is using windows python from MinTTY really the "wrong python".    For example I often use msys2 shell that somes with git for windows and run emscripten and emsdk within it using windows python.   Are we saying that if you want to run a python tool in the git shell it should be considered wrong to use windows python?

**Comment by sbc100** [comment]
Sorry I just read your note which clarifies this.

**Comment by sbc100** [comment]
Also when running in msys mode is it impossible to run `.bat` files directly with `subprocess`?   i.e. what is wrong with calling the `.bat` files in this mode?

**Comment by mmcparlane** [comment]
Looks like the bat files can be executed but it does not end up setting any environment variables. Also, as it stands, when I execute the bat file it seems to be confused about the platform and prints the "setting environment variables" message expected by Windows systems _and_ Unix systems. In addition, when sourcing the `emsdk_env.sh` file there is an error message printed complaining about a duplicate SDK (see below).

I think the expected usage to populate the MinTTY environment vars would be the Unix way—as it seems the bat file won't do that—despite them being callable. In essence, it is setting env. variables for the particular invocation but not in the calling process.

Given this, I think changes to the Emsdk will be necessary to permit MSYS/MinGW environments as first-class Unix citizens (by reading the `MSYSTEM` env. and checking for `mingw32|mingw64|msys`). And per our discussion above, also changes to the emscripten scripts to distinguish MSYS/MinGW from Windows—adjusting path-separators to the Unix flavour.

Invoking emsdk_env.bat:
```
MSYS ~
$ /c/emsdk/emsdk_env.bat
The system cannot find the drive specified.
Adding directories to PATH:
PATH += /c/emsdk
PATH += /c/emsdk/upstream/emscripten
PATH += /c/emsdk/node/12.18.1_64bit/bin
PATH += /c/emsdk/python/3.7.4-pywin32_64bit
PATH += /c/emsdk/java/8.152_64bit/bin

Setting environment variables:
EMSDK = C:/emsdk
EM_CONFIG = C:\emsdk\.emscripten
EM_CACHE = C:/emsdk/upstream/emscripten\cache
EMSDK_NODE = C:/emsdk/node/12.18.1_64bit/bin/node.exe
EMSDK_PYTHON = C:/emsdk/python/3.7.4-pywin32_64bit/python.exe
JAVA_HOME = C:/emsdk/java/8.152_64bit
export PATH="/c/emsdk:/c/emsdk/upstream/emscripten:/c/emsdk/node/12.18.1_64bit/bin:/c/emsdk/python/3.7.4-pywin32_64bit:/c/emsdk/java/8.152_64bit/bin:/c/msys64/usr/local/bin:/c/msys64/usr/bin:/c/msys64/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/c/msys64/usr/bin/site_perl:/c/msys64/usr/bin/vendor_perl:/c/msys64/usr/bin/core_perl";
export EMSDK="C:/emsdk";
export EM_CONFIG="C:\emsdk\.emscripten";
export EM_CACHE="C:/emsdk/upstream/emscripten\cache";
export EMSDK_NODE="C:/emsdk/node/12.18.1_64bit/bin/node.exe";
export EMSDK_PYTHON="C:/emsdk/python/3.7.4-pywin32_64bit/python.exe";
export JAVA_HOME="C:/emsdk/java/8.152_64bit";
```

Sourcing emsdk_env.sh:
```
MSYS ~
$ source /c/emsdk/emsdk_env.sh
Traceback (most recent call last):
  File "/c/emsdk/emsdk.py", line 3055, in <module>
    sys.exit(main())
  File "/c/emsdk/emsdk.py", line 2799, in main
    load_sdk_manifest()
  File "/c/emsdk/emsdk.py", line 2338, in load_sdk_manifest
    add_sdk(sdk)
  File "/c/emsdk/emsdk.py", line 1972, in add_sdk
    raise Exception('Duplicate sdk ' + str(sdk) + '! Existing:\n{' + ', '.join("%s: %s" % item for item in vars(find_sdk(str(sdk))).items()) + '}, New:\n{' + ', '.join("%s: %s" % item for item in vars(sdk).items()) + '}')
Exception: Duplicate sdk sdk-upstream-master-64bit! Existing:
{version: upstream-master, bitness: 64, uses: ['llvm-git-master-64bit', 'node-12.18.1-64bit', 'python-3.7.4-pywin32-64bit', 'emscripten-master-64bit', 'binaryen-master-64bit'], os: win, id: sdk, name: sdk-upstream-master-64bit, is_old: False, is_sdk: True}, New:
{version: upstream-master, bitness: 64, uses: ['llvm-git-master-64bit', 'node-12.18.1-64bit', 'emscripten-master-64bit', 'binaryen-master-64bit'], os: linux, id: sdk, name: sdk-upstream-master-64bit, is_old: False, is_sdk: True}
```

**Comment by sbc100** [comment]
I believe that crash only happens if you have msys2 python in your PATH before windows python right?  If you have windows python first it works, right?

**Comment by sbc100** [comment]
I think it would be great to get some minimal testing on the emsdk CI with msys python if you feel like adding any.

Right now we do some testing in the msys shell (I believe its the one that comes with git for windows) but that environment doesn't contains python AFAICT.

**Comment by mmcparlane** [comment]
> I believe that crash only happens if you have msys2 python in your PATH before windows python right? If you have windows python first it works, right?

It seems to be an issue with the `emsdk.py` script where it detects environments. Because msys2 is a hybrid environment, both the `WINDOWS` _and_ `MSYS` (or `MINGW` ) need to evaluate to `True`. And as it stands, on MinTTY python, `os.name == 'posix'` will return `True` and so in the following block the system gets confused to be Linux.

Difference in os.name based on python flavour:
```
mtmcp@JollyBox MINGW64 ~
$ /usr/bin/python -c "import os; print(os.name)"
posix

MINGW64 ~
$ /c/emsdk/python/3.7.4-pywin32_64bit/python.exe -c "import os; print(os.name)"
nt

```

From emsdk.py (where the msys gets confused to be Linux):
```
LINUX = False
if not MACOS and (platform.system() == 'Linux' or os.name == 'posix'):
  LINUX = True
```


> I think it would be great to get some minimal testing on the emsdk CI with msys python if you feel like adding any.

Not a problem—I can also start on a fix for the emsdk.py as well.

**Comment by mmcparlane** [comment]
After removing the the `or os.name == 'posix'` it fixed the issue with sourcing the `emsdk_env.sh`. The build is now failing due to paths per our discussion. So, I will turn to that fix over next couple days and see where it ends up.

```
 MSYS /c/users/mtmcp/Documents/grafX2/3rdparty/archives/jpeg-9d
$ emconfigure sh.exe ./configure --prefix=/c/emsdk/upstream/emscripten/cache/custom
configure: loading site script C:/msys64/etc/config.site
checking build system type... x86_64-pc-msys
checking host system type... x86_64-pc-msys
checking target system type... x86_64-pc-msys
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... C:\emsdk\upstream\emscripten\emcc.bat
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether C:\emsdk\upstream\emscripten\emcc.bat accepts -g... yes
checking for C:\emsdk\upstream\emscripten\emcc.bat option to accept ISO C89... none needed
checking whether C:\emsdk\upstream\emscripten\emcc.bat understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of C:\emsdk\upstream\emscripten\emcc.bat... none
checking for C:\emsdk\upstream\emscripten\emcc.bat option to accept ISO C99... none needed
checking for C:\emsdk\upstream\emscripten\emcc.bat option to accept ISO Standard C... (cached) none needed
checking how to run the C preprocessor... C:\emsdk\upstream\emscripten\emcc.bat -E
checking whether make sets $(MAKE)... (cached) yes
checking whether ln -s works... no, using cp -pR
checking the archiver (C:\emsdk\upstream\emscripten\emar.bat) interface... ar
checking if LD -Wl,--version-script works... yes
checking for function prototypes... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdlib.h... (cached) yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for string.h... (cached) yes
checking for size_t... yes
checking for type unsigned char... yes
checking for type unsigned short... yes
checking for type void... yes
checking for an ANSI C-conforming const... yes
checking for inline... __inline__
checking for broken incomplete types... ok
checking for short external names... ok
checking to see if char is signed... yes
checking to see if right shift is signed... yes
checking to see if fopen accepts b spec... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by C:\emsdk\upstream\emscripten\emcc.bat... C:\emsdk\upstream\emscripten\emcc.bat
checking if the linker (C:\emsdk\upstream\emscripten\emcc.bat) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... C:/emsdk/upstream/bin\llvm-nm.exe
checking the name lister (C:/emsdk/upstream/bin\llvm-nm.exe) interface... BSD nm
checking the maximum length of command line arguments... 24000
checking how to convert x86_64-pc-msys file names to x86_64-pc-msys format... func_convert_file_noop
checking how to convert x86_64-pc-msys file names to toolchain format... func_convert_file_noop
checking for C:\emsdk\upstream\emscripten\emcc.bat option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... unknown
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... C:\emsdk\upstream\emscripten\emranlib.bat
checking command to parse C:/emsdk/upstream/bin\llvm-nm.exe output from C:\emsdk\upstream\emscripten\emcc.bat object... failed
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if C:\emsdk\upstream\emscripten\emcc.bat supports -fno-rtti -fno-exceptions... yes
checking for C:\emsdk\upstream\emscripten\emcc.bat option to produce PIC... -fPIC -DPIC
checking if C:\emsdk\upstream\emscripten\emcc.bat PIC flag -fPIC -DPIC works... yes
checking if C:\emsdk\upstream\emscripten\emcc.bat static flag -static works... yes
checking if C:\emsdk\upstream\emscripten\emcc.bat supports -c -o file.o... yes
checking if C:\emsdk\upstream\emscripten\emcc.bat supports -c -o file.o... (cached) yes
checking whether the C:\emsdk\upstream\emscripten\emcc.bat linker (C:\emsdk\upstream\emscripten\emcc.bat) supports shared libraries... clang version 12.0.0 (Cswircachegitchromium.googlesource.com-external-github.com-llvm-llvm--project 5dbf80cad9556e222c4383960007fc0b27ea9541)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:/emsdk/upstream/bin
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.5
shared:INFO: (Emscripten: Running sanity checks)
yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... no
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... no
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking libjpeg version number... 9.4.0
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libjpeg.pc
config.status: creating jconfig.h
config.status: executing depfiles commands
config.status: executing libtool commands
configure: sh.exe ./configure --prefix=C:/emsdk/upstream/emscripten/cache/custom

mtmcp@JollyBox MSYS /c/users/mtmcp/Documents/grafX2/3rdparty/archives/jpeg-9d
$ emmake make install
  CC       cjpeg.o
./depcomp: line 772: exec: C:emsdkupstreamemscriptenemcc.bat: not found
make: *** [Makefile:769: cjpeg.o] Error 127
make: make install

```

**Comment by sbc100** [comment]
Would you consider making a patch to emsdk to fix the first issue?

**Comment by mmcparlane** [comment]
> Would you consider making a patch to emsdk to fix the first issue?
Yep! On it now.

**Comment by mmcparlane** [comment]
Regarding the msys2 python—based on the docs CircleCI already uses msys2 so my hope is that simply requires running `pacman -S python` to install python into the MSYS2 environment.

https://circleci.com/docs/2.0/hello-world-windows/#software-pre-installed-in-the-windows-image

**Comment by sbc100** [comment]
I hope that works!   I imagine they simply piggy back on the fact the it comes with git.. but we will see.. maybe pacman also comes with git?

**Comment by mmcparlane** [comment]
I figured out how to get the environment set up. It's a little roundabout: use chocolatey to install msys2 and then use msys2 to install python via pacman. Then the `source emsdk_env.sh` can happen (similar to how python gets invoked in the example) and output checked, or whatever.

Below is a link to an example yaml file (but I ran out of credits so can't do any more tests on Windows at the moment—probably from holding an SSH session open too long). The system-provided bash.exe is provided as part of a custom cygwin install and hence somewhat fixed. Thankfully they provided [Chocolatey](https://chocolatey.org/)!

Example yaml file:
https://github.com/mmcparlane/test-circleci-win/blob/master/.circleci/config.yml

**Comment by mmcparlane** [comment]
Please see associated PR for added msys2 tests in emsdk. Once those are vetted/merged a similar set of changes could be added in the emscripten repo.
https://github.com/emscripten-core/emsdk/pull/631

**Comment by mmcparlane** [comment]
Found another potential issue with msys2 builds. On my system at the moment I have an EMSDK installed in `C:\Emsdk` which I used to download precompiled LLVM, Node, JRE, etc. I also cloned a separate emscripten branch (which I'm using to make changes) into `C:\Users\mtmcp\Documents\emscripten`. In order to avoid recompiling those dependencies, I added them to a custom `.emscripten` file (note: configured python is msys2 python as required above).

```python
MSYS /c/Users/mtmcp/Documents/emscripten
$ cat .emscripten
import os
emsdk_path = '/c/emsdk'
NODE_JS = emsdk_path + '/node/12.18.1_64bit/bin/node.exe'
PYTHON = '/usr/bin/python.exe'
JAVA = emsdk_path + '/java/8.152_64bit/bin/java.exe'
LLVM_ROOT = emsdk_path + '/upstream/bin'
BINARYEN_ROOT = emsdk_path + '/upstream'
EMSCRIPTEN_ROOT = emsdk_path + '/upstream/emscripten'
TEMP_DIR = emsdk_path + '/tmp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]
```

And then went to build a custom `test.c` file (just a basic main function returning an int), yielding a _failure to precompile libc._ Some of this may be related to the paths, but I'm curious about the line stating `clang -cc1 version 12.0.0 based upon LLVM 12.0.0git default target x86_64-pc-windows-msvc`, which is followed by the failure to find paths which include the libc headers. There may need to be some more switches passed to clang to ensure the directories are understood.

```bash
 MSYS /c/Users/mtmcp/Documents/emscripten
$ ./emcc -v test.c -o test.exe
shared:INFO: (Emscripten: Running sanity checks)
 "/c/emsdk/upstream/bin/clang" -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=6 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/include/compat -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/include -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/include/libc -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/local/include -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/include/SSE -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/include/neon -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/lib/compiler-rt/include -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/lib/libunwind/include -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/cache/wasm/include -DEMSCRIPTEN -fignore-exceptions -v -o test.exe test.c -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/include/SDL -c -o /tmp/emscripten_temp_jnlw7h41/test_0.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr
clang version 12.0.0 (Cswircachegitchromium.googlesource.com-external-github.com-llvm-llvm--project a81b938b6dee0e1ed4dd44e7d59325d0aa4774cc)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: C:\emsdk\upstream\bin
 (in-process)
 "C:\\emsdk\\upstream\\bin\\clang.exe" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all --mrelax-relocations -disable-free -main-file-name test.c -mrelocation-model static -mframe-pointer=none -fno-rounding-math -mconstructor-aliases -target-cpu generic -fvisibility hidden -debugger-tuning=gdb -v -resource-dir "C:\\emsdk\\upstream\\lib\\clang\\12.0.0" -D __EMSCRIPTEN_major__=2 -D __EMSCRIPTEN_minor__=0 -D __EMSCRIPTEN_tiny__=6 -D _LIBCPP_ABI_VERSION=2 -D unix -D __unix -D __unix__ -D EMSCRIPTEN -internal-isystem "C:\\emsdk\\upstream\\lib\\clang\\12.0.0\\include" -internal-isystem /include/wasm32-emscripten -internal-isystem /include -Werror=implicit-function-declaration -fdebug-compilation-dir "C:\\Users\\mtmcp\\Documents\\emscripten" -ferror-limit 19 -fgnuc-version=4.2.1 -fignore-exceptions -nostdsysteminc -isystem/c/Users/mtmcp/Documents/emscripten/system/include/compat -isystem/c/Users/mtmcp/Documents/emscripten/system/include -isystem/c/Users/mtmcp/Documents/emscripten/system/include/libc -isystem/c/Users/mtmcp/Documents/emscripten/system/lib/libc/musl/arch/emscripten -isystem/c/Users/mtmcp/Documents/emscripten/system/local/include -isystem/c/Users/mtmcp/Documents/emscripten/system/include/SSE -isystem/c/Users/mtmcp/Documents/emscripten/system/include/neon -isystem/c/Users/mtmcp/Documents/emscripten/system/lib/compiler-rt/include -isystem/c/Users/mtmcp/Documents/emscripten/system/lib/libunwind/include -isystem/c/Users/mtmcp/Documents/emscripten/cache/wasm/include -isystem/c/Users/mtmcp/Documents/emscripten/system/include/SDL -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o C:/msys64/tmp/emscripten_temp_jnlw7h41/test_0.o -x c test.c
clang -cc1 version 12.0.0 based upon LLVM 12.0.0git default target x86_64-pc-windows-msvc
ignoring nonexistent directory "/c/Users/mtmcp/Documents/emscripten/system/include/compat"
ignoring nonexistent directory "/c/Users/mtmcp/Documents/emscripten/system/include"
ignoring nonexistent directory "/c/Users/mtmcp/Documents/emscripten/system/include/libc"
ignoring nonexistent directory "/c/Users/mtmcp/Documents/emscripten/system/lib/libc/musl/arch/emscripten"
ignoring nonexistent directory "/c/Users/mtmcp/Documents/emscripten/system/local/include"
ignoring nonexistent directory "/c/Users/mtmcp/Documents/emscripten/system/include/SSE"
ignoring nonexistent directory "/c/Users/mtmcp/Documents/emscripten/system/include/neon"
ignoring nonexistent directory "/c/Users/mtmcp/Documents/emscripten/system/lib/compiler-rt/include"
ignoring nonexistent directory "/c/Users/mtmcp/Documents/emscripten/system/lib/libunwind/include"
ignoring nonexistent directory "/c/Users/mtmcp/Documents/emscripten/cache/wasm/include"
ignoring nonexistent directory "/c/Users/mtmcp/Documents/emscripten/system/include/SDL"
ignoring nonexistent directory "/include/wasm32-emscripten"
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 C:\emsdk\upstream\lib\clang\12.0.0\include
End of search list.
cache:INFO: generating system library: libc.a... (this will be cached in "/c/Users/mtmcp/Documents/emscripten/cache/wasm/libc.a" for subsequent builds)
C:/Users/mtmcp/Documents/emscripten/system/lib/libc/musl/src/compat-emscripten/strlwr.c:1:10: fatal error: 'ctype.h' file not found
#include <ctype.h>
         ^~~~~~~~~
1 error generated.
emcc: error: '/c/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=6 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/include/compat -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/include -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/include/libc -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/local/include -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/include/SSE -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/include/neon -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/lib/compiler-rt/include -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/lib/libunwind/include -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/cache/wasm/include -DEMSCRIPTEN -fignore-exceptions -fno-inline-functions -Werror -D_XOPEN_SOURCE=700 -Wno-unused-result -Os -fno-builtin -Wno-ignored-attributes -Wno-dangling-else -Wno-unknown-pragmas -Wno-shift-op-parentheses -Wno-string-plus-int -Wno-pointer-sign -I/c/Users/mtmcp/Documents/emscripten/system/lib/libc/musl/src/internal -c -o /tmp/emscripten_temp_jnlw7h41/strlwr.o /c/Users/mtmcp/Documents/emscripten/system/lib/libc/musl/src/compat-emscripten/strlwr.c -Xclang -isystem/c/Users/mtmcp/Documents/emscripten/system/include/SDL -c -o /tmp/emscripten_temp_jnlw7h41/strlwr.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
In file included from C:/Users/mtmcp/Documents/emscripten/system/lib/libc/musl/src/complex/cabsf.c:1:
C:/Users/mtmcp/Documents/emscripten/system/lib/libc/musl/src/internal\libm.h:18:10: fatal error: 'math.h' file not found
#include <math.h>
         ^~~~~~~~
1 error generated.

```

**Comment by boboben1** [comment]
Issue is fixed by adding a call to `normalize_path` in emsdk/upstream/emscripten/tools/utils.py in path_from_root on line 25

`def path_from_root(*pathelems):
  return normalize_path(str(Path(__rootpath__, *pathelems)))`

**Comment by sbc100** [comment]
@boboben1 you how/why this fix works?   Can you perhaps send the `clang.exe` command line before and after the change so we can see the difference and try to figure out why one works and one doesn't?

**Comment by boboben1** [comment]
It's not an issue with clang. The change affects how `configure` outputs the path to emcc.bat or em++.bat. When running make, if it uses windows endings, the slashes get removed and it results in make error 127 (file not found) You can see the issue in @ghost's reply (https://github.com/emscripten-core/emscripten/issues/12376#issuecomment-702257955)

```
mtmcp@JollyBox MSYS /c/users/mtmcp/Documents/grafX2/3rdparty/archives/jpeg-9d
$ emmake make install
  CC       cjpeg.o
./depcomp: line 772: exec: C:emsdkupstreamemscriptenemcc.bat: not found
make: *** [Makefile:769: cjpeg.o] Error 127
make: make install```
