### ISSUE TITLE
Acorn optimizer - Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by georeith** [emscripten-core/emscripten#12543]
My build is failing with the following error:

```
building:DEBUG: running cleanup on shell code: JSDCE minifyWhitespace
/usr/local/emsdk/upstream/emscripten/tools/acorn-optimizer.js:91
    if (!(node.type in cs)) {
               ^

TypeError: Cannot read property 'type' of undefined
    at c (/usr/local/emsdk/upstream/emscripten/tools/acorn-optimizer.js:91:16)
    at /usr/local/emsdk/upstream/emscripten/tools/acorn-optimizer.js:395:11
    at Array.forEach (<anonymous>)
    at ObjectExpression (/usr/local/emsdk/upstream/emscripten/tools/acorn-optimizer.js:394:25)
    at c (/usr/local/emsdk/upstream/emscripten/tools/acorn-optimizer.js:96:20)
    at Object.VariableDeclarator (/usr/local/emsdk/upstream/emscripten/tools/acorn-optimizer.js:390:24)
    at c (/usr/local/emsdk/upstream/emscripten/tools/acorn-optimizer.js:96:20)
    at recursiveWalk (/usr/local/emsdk/upstream/emscripten/tools/acorn-optimizer.js:98:5)
    at /usr/local/emsdk/upstream/emscripten/tools/acorn-optimizer.js:93:9
    at maybeChild (/usr/local/emsdk/upstream/emscripten/tools/acorn-optimizer.js:51:7)
em++: error: '/usr/local/emsdk/node/12.18.1_64bit/bin/node /usr/local/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/emscripten_temp/dwr.wasm.js.pp.js JSDCE minifyWhitespace --closureFriendly' failed (1)
cache:DEBUG: PID 110 released multiprocess file lock to Emscripten cache at /usr/local/emsdk/upstream/emscripten/cache/wasm
```

Here's the command I'm running:

```
/usr/local/emsdk/upstream/emscripten/em++.py -Oz --closure 1 -DSK_RELEASE -DGR_GL_CHECK_ALLOC_WITH_GET_ERROR=0 -I third_party/skia -I third_party/skia/third_party/icu -I third_party/skia/third_party/externals/icu/source/common/ -I include -DSK_DISABLE_AAA -DSK_FORCE_8_BYTE_ALIGNMENT -lGL -DSK_SUPPORT_GPU=1 -DSK_GL -DSK_DISABLE_LEGACY_SHADERCONTEXT -s USE_WEBGL2=1 -std=c++17 --bind --pre-js src/js/pre.js --pre-js src/js/interface.js src/Canvas.cpp src/Rectangle.cpp src/RenderList.cpp src/RenderObject.cpp src/RenderObjectContainer.cpp src/Shape.cpp src/Text.cpp src/main.cpp /root/design-wasm-renderer/third_party/skia/out/lib/libskparagraph.a /root/design-wasm-renderer/third_party/skia/out/lib/libskshaper.a /root/design-wasm-renderer/third_party/skia/out/lib/libharfbuzz.a /root/design-wasm-renderer/third_party/skia/out/lib/libicu.a /root/design-wasm-renderer/third_party/skia/out/lib/libskia.a /root/design-wasm-renderer/third_party/skia/modules/canvaskit/fonts/NotoMono-Regular.ttf.cpp -s EXPORT_NAME='Module' -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=128MB -s NO_EXIT_RUNTIME=1 -s STRICT=1 -s WASM=1 -s USE_BOOST_HEADERS=1 -s LLD_REPORT_UNDEFINED -s ASSERTIONS=1 -s SAFE_HEAP=1 -Wl,-error-limit=0 -o out/dwr.js
```

version: 2.0.7

**Comment by kripken** [comment]
This doesn't sound like a known issue, but we'd need a testcase to debug it @georeith 

Or you can debug it on your side by seeing if it's something specific in your user-provided JS (check if removing a `--pre-js` for example makes a difference).

**Comment by georeith** [comment]
@kripken thanks for the pointer on where to start. I narrowed it down to this function in my pre-js:

```js
  DWR.Text.prototype.generateFontCache = function () {
    const fontCache = {};
    const _fontCache = this._generateFontCache();
    const _fontNames = _fontCache.keys();
    for (let i = 0; i < _fontCache.size(); i++) {
      const fontName = _fontNames.get(i);
      const _fontData = _fontCache.get(fontName);
      const glyphCache = {};
      const fontData = {
        ..._fontData,
        glyphs: glyphCache,
      };
      fontCache[fontName] = fontData;
      const _glyphCache = _fontData.glyphs;
      const _glyphIds = _glyphCache.keys();
      for (let j = 0; j < _glyphCache.size(); j++) {
        const glyphId = _glyphIds.get(j);
        glyphCache[glyphId] = _glyphCache.get(glyphId);
      }
    }

    return fontCache;
  };
```

Specifically the spread operation here:

```js
const fontData = {
    ..._fontData,
    glyphs: glyphCache,
};
```

Replacing it with this removes the issue:

```js
const fontData = Object.assign({}, _fontData, {
  glyphs: glyphCache,
});
```

**Comment by kripken** [comment]
Interesting, thanks for the update @georeith 

It would be good to check if this is an issue in upstream acorn (if so we should update). We do already pass `ecmaVersion: 2020` so we should be using everything acorn supports.

**Comment by sbc100** [comment]
We did only recently switch to 2020 though... what version of emscripten are you using?   (if you are using a git checkout, have you run `npm install` recently?)

**Comment by sbc100** [comment]
> We did only recently switch to 2020 though... what version of emscripten are you using? (if you are using a git checkout, have you run `npm install` recently?)

Ignore this I see you are using 2.0.7 and the emsdk.

**Comment by sbc100** [comment]
@kripken looks like maybe a bug in our `acorn-optimizer.js` code which uses acorn, rather than an issue with acorn itself?

**Comment by kripken** [comment]
@sbc100 Worth investigating, yes. But the stack trace is on
```
    if (!(node.type in cs)) {
```
which suggests the node is undefined. That seems less likely to be a bug in our code.

**Comment by Ghabry** [comment]
I just had this issue in code starting with this line: ``Module = { ...Module,``.

Applied the mentioned Object.assign workaround to make it compile

**Comment by pavelsavara** [comment]
The node looks like this
```
{
            "type": "SpreadElement",
            "start": 185894,
            "end": 185899,
            "argument": {
                "type": "Identifier",
                "start": 185897,
                "end": 185899,
                "name": "Va"
            }
        }
```

It fails in 
```
ObjectExpression(node, c) {
        // ignore the property identifiers
        node.properties.forEach(function (node) {
          c(node.value);
        });
      },
```
because the node doesn't have `value`

It probably should be handled by `hasSideEffects()`.
