### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '.'

### ISSUE THREAD

**Issue by justablob** [emscripten-core/emscripten#12555]
Hey there, I'm currently facing an issue with Emscripten 2.0.7, specifically emcmake, where immediately after running it, it gives me a PermissionError. I'm running this on Ubuntu 20.04 in WSL1 on Windows 10 Pro (Build 19041.572). Here's the exact command and error:
```
chef@LAPTOP-KQVDDPOS:/mnt/c/Users/Chef/Syncronized Folders/Syncronized Library/Projekt/liboqs-working/liboqs-wasm$ emcmake . -DOQS_PORTABLE_BUILD=ON -DOQS_USE_OPENSSL=OFF -DOQS_USE_CPU_EXTENSIONS=OFF -GNinja
configure: . -DOQS_PORTABLE_BUILD=ON -DOQS_USE_OPENSSL=OFF -DOQS_USE_CPU_EXTENSIONS=OFF -GNinja
Traceback (most recent call last):
  File "/home/chef/emsdk/upstream/emscripten/emcmake.py", line 34, in <module>
    sys.exit(run())
  File "/home/chef/emsdk/upstream/emscripten/emcmake.py", line 27, in run
    building.configure(sys.argv[1:])
  File "/home/chef/emsdk/upstream/emscripten/tools/building.py", line 339, in configure
    run_process(args, stdout=stdout, stderr=stderr, env=env, **kwargs)
  File "/home/chef/emsdk/upstream/emscripten/tools/shared.py", line 205, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '.'
```
As you might be able to tell, I'm trying to compile liboqs, a post-quantum cryptography library, to Emscripten. I can provide more information if it's necessary.

**Comment by sbc100** [comment]
You need to pass `cmake` as the first argument to `emcmake`

**Comment by justablob** [comment]
Wow... Now I feel stupid. Thanks @sbc100 :)
