### ISSUE TITLE
Problem with EM_FUNC_SIG_PARAM_I64 when posting to main thread

### ISSUE THREAD

**Issue by emaxx-google** [emscripten-core/emscripten#12748]
Hello, I'm trying to use `emscripten_async_run_in_main_runtime_thread()` (as suggested in #8212). I'm getting the `"Invalid Emscripten pthread _do_call opcode!"` exception when trying to use it with an `int64_t` argument.

Sample code:
```cpp
void TrampolineMethod(int64_t arg) {}

// ...
  emscripten_async_run_in_main_runtime_thread(
      (EM_FUNC_SIG_RETURN_VALUE_V | EM_FUNC_SIG_WITH_N_PARAMETERS(1) |
       EM_FUNC_SIG_SET_PARAM(0, EM_FUNC_SIG_PARAM_I64)),
      &TrampolineMethod, static_cast<int64_t>(123));
```

DevTools show this exception:
```
Uncaught RuntimeError: abort(Assertion failed: 0 && "Invalid Emscripten pthread _do_call opcode!", at: /b/s/w/ir/k/install/emscripten/system/lib/pthread/library_pthread.c,347,_do_call) at Error
    at jsStackTrace (chrome-extension://kkfjhpobikanfaakacenbjnmhebacpje/executable.js:2322:19)
    at stackTrace (chrome-extension://kkfjhpobikanfaakacenbjnmhebacpje/executable.js:2339:16)
    at abort (chrome-extension://kkfjhpobikanfaakacenbjnmhebacpje/executable.js:1683:44)
    at ___assert_fail (chrome-extension://kkfjhpobikanfaakacenbjnmhebacpje/executable.js:2345:7)
    at _do_call (chrome-extension://kkfjhpobikanfaakacenbjnmhebacpje/executable.wasm:wasm-function[6629]:0xe0f3d)
    at emscripten_current_thread_process_queued_calls (chrome-extension://kkfjhpobikanfaakacenbjnmhebacpje/executable.wasm:wasm-function[6628]:0xe0670)
    at emscripten_main_thread_process_queued_calls (chrome-extension://kkfjhpobikanfaakacenbjnmhebacpje/executable.wasm:wasm-function[6646]:0xe173e)
    at chrome-extension://kkfjhpobikanfaakacenbjnmhebacpje/executable.js:1745:22
    at Worker.worker.onmessage (chrome-extension://kkfjhpobikanfaakacenbjnmhebacpje/executable.js:2211:13)
    at abort (chrome-extension://kkfjhpobikanfaakacenbjnmhebacpje/executable.js:1689:11)
    at ___assert_fail (chrome-extension://kkfjhpobikanfaakacenbjnmhebacpje/executable.js:2345:7)
    at _do_call (chrome-extension://kkfjhpobikanfaakacenbjnmhebacpje/executable.wasm:wasm-function[6629]:0xe0f3d)
    at emscripten_current_thread_process_queued_calls (chrome-extension://kkfjhpobikanfaakacenbjnmhebacpje/executable.wasm:wasm-function[6628]:0xe0670)
    at emscripten_main_thread_process_queued_calls (chrome-extension://kkfjhpobikanfaakacenbjnmhebacpje/executable.wasm:wasm-function[6646]:0xe173e)
    at chrome-extension://kkfjhpobikanfaakacenbjnmhebacpje/executable.js:1745:22
    at Worker.worker.onmessage (chrome-extension://kkfjhpobikanfaakacenbjnmhebacpje/executable.js:2211:13)
```

Browser version: Chrome 86.0.4240.193. Emsdk: 2.0.6.

**Comment by msabwat** [comment]
This is very late, but I think the issue was that the parameter did not belong there.
I call it like that :
```
    em_queued_call q = { EM_FUNC_SIG_VI, handler };

    q.args[0].i64 = 42;                                                                                                                   
    emscripten_sync_run_in_main_thread(&q);
```

and then handler would be 
```
void handler(int64_t num) {
 // with num = 42
}
```

**Comment by emaxx-google** [comment]
@msabwat , your reply uses sync call however. I don't see an asynchronous equivalent that'd receive `em_queued_call` (there's `emscripten_async_run_in_main_thread()`, but it's not exposed in the public headers).

**Comment by msabwat** [comment]
this is the one I meant to use, it has the same prototype as the sync one. I don't know however why it's not exposed
