### ISSUE TITLE
Emscripten Install broken by doing a pthreads build.

### ISSUE THREAD

**Issue by cshenton** [emscripten-core/emscripten#12753]
Version 2.0.6, Windows 10, MinGW shell environment.

I tried building a project with pthreads and now my entire emscripten install is not working at all. I usually get errors like this:

```
em++ -Isrc/ -Wall -Wformat -Os -s USE_SDL=2 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s DISABLE_EXCEPTION_CATCHING=1 -s NO_EXIT_RUNTIME=0 -s ASSERTIONS=1  -c -o build/src/main.cpp.o src/main.cpp
cache:INFO: generating port: libSDL2.a... (this will be cached in "C:\<MY_USER>\emsdk\upstream\emscripten\cache\wasm\libSDL2.a" for subsequent builds)
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 121, in worker
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 44, in mapstar
  File "C:\<MY_USER>\emsdk\upstream\emscripten\tools\system_libs.py", line 80, in run_one_command
    shared.run_process(cmd, stdout=stdout, stderr=stderr, env=safe_env)
  File "C:\<MY_USER>\emsdk\upstream\emscripten\tools\shared.py", line 205, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 472, in run
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 775, in __init__
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 1178, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\<MY_USER>\emsdk\upstream\emscripten\\em++.py", line 14, in <module>
    sys.exit(emcc.run(sys.argv))
  File "C:\<MY_USER>\emsdk\upstream\emscripten\emcc.py", line 2006, in run
    compile_source_file(i, input_file)
  File "C:\<MY_USER>\emsdk\upstream\emscripten\emcc.py", line 1985, in compile_source_file
    cmd = get_clang_command(input_file)
  File "C:\<MY_USER>\emsdk\upstream\emscripten\emcc.py", line 1930, in get_clang_command
    return system_libs.process_args(cmd, shared.Settings)
  File "C:\<MY_USER>\emsdk\upstream\emscripten\tools\system_libs.py", line 1968, in process_args
    port.get(Ports, settings, shared)
  File "C:\<MY_USER>\emsdk\upstream\emscripten\tools\ports\sdl2.py", line 85, in get
    return [shared.Cache.get(libname, create, what='port')]
  File "C:\<MY_USER>\emsdk\upstream\emscripten\tools\cache.py", line 126, in get
    temp = creator()
  File "C:\<MY_USER>\emsdk\upstream\emscripten\tools\ports\sdl2.py", line 80, in create
    ports.run_commands(commands)
  File "C:\<MY_USER>\emsdk\upstream\emscripten\tools\system_libs.py", line 1710, in run_commands
    run_build_commands([add_args(c) for c in commands])
  File "C:\<MY_USER>\emsdk\upstream\emscripten\tools\system_libs.py", line 94, in run_build_commands
    pool.map_async(run_one_command, commands, chunksize=1).get(999999)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 657, in get
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

I have tried `emcc --clear-cache`, but don't know what to do next. This error tells me nothing.

**Comment by cshenton** [comment]
Okay, this is resolved by a fresh install and moving from msys2 shell to powershell. Still weird that it just broke like that.

**Comment by cshenton** [comment]
Okay, the same error is now occurring with the fresh install on powershell.

**Comment by sbc100** [comment]
Do you have PYTHONPATH or PYTHONHOME set in your environment?     Can you try removing them?

**Comment by sbc100** [comment]
Using msys2 can certain cause issues,  I would try using the normal windows cmd shell first, then once you are sure your setup is working try other shells.
