### ISSUE TITLE
How to stack allocate structs on the javascript side.

### ISSUE THREAD

**Issue by jkbbwr** [emscripten-core/emscripten#12758]
I am wrapping a pure C codebase and wanted to see if I could avoid using embind for this as I didn't like the complexity it was adding.

I have managed to compile my C library into the `.wasm` and `.js` binding files and it is callable and usable.

Something the C library does very often is this pattern

```c
thing_t t;
do_thing(&t);
```

I understand that we have `Module._malloc` and other methods, and I can just allocate `thing_t` but my issue is, it seems all information about structs is just lost when the js bindings are emitted so I don't know how much I need to allocate for any given structure (there are quite a few different ones in the codebase so manually coding the sizes by hand would be fragile and bad)

I spent a long time looking around for answers online and didn't find much.

I tried playing with the `gen_struct_info.py` tool but it kept crashing (partly due to our use of `__attribute__` in our C code)

If you have any suggestions or advice I would greatly apprecate them

**Comment by sbc100** [comment]
gen_struct_info.py is the only way we have right now to extract structure sizes and offset.  Its also not really designed for use outside the emscripten core library.

BYW, if you want to allocate on the stack you can use `stackAlloc(size);` to get your memory.  Just remember to call `stackSave` before  and `stackRestore` after.

On option is to write a native function that return structure sizes.  So you could write:

`var ptr = stackAlloc(_get_thing_size())`

**Comment by jkbbwr** [comment]
I can probably skip the stack allocation of the structures, so long as I get the sizes correct for the heap allocation.

So choices are;

Either dig into `gen_struct_info.py` and make it generic for external projects. I know python, it might be doable.

Or write some shim C code that exposes the compile time sizes of the structs I plan to allocate. This would be faster but it leaves others in a similar situation in the future.

I shall think on this more.

**Comment by sbc100** [comment]
Actually it looks like gen_struct_info.py can already be used for your purposes ..  you can pass it your own headers and it will output JSON.    You should then be able to read that in at runtime (or possibly compile time if you use library js).

**Comment by sbc100** [comment]
Having said that we don't currently consider `gen_struct_info.py` to be part of the public API so it could change (although it hasn't changed in many years now).

**Comment by jkbbwr** [comment]
Currently it gets chewed up on attributes like `__attribute__(unused)` and `must_check`

**Comment by jkbbwr** [comment]
So, many different issues. 

```
gen_struct_info: Parsing header "test.h"...
Traceback (most recent call last):
  File "/usr/lib/emscripten/tools/gen_struct_info.py", line 562, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/emscripten/tools/gen_struct_info.py", line 553, in main
    defines.extend(data['defines'])
AttributeError: 'dict' object has no attribute 'extend'
```

Fixing tihs is simple as changing `extend` to `update`
This leaves a second problem, 

```
h
gen_struct_info: Parsing header "test.h"...
gen_struct_info: Generating C code... /tmp/tmp6sletzao.c
gen_struct_info: Compiling generated code...
gen_struct_info: ['/home/jakob/tmp/emscripten/emcc', '-D_GNU_SOURCE', '-I.', '-o', '/tmp/tmpfnwocjpq.js', '/tmp/tmp6sletzao.c', '-O0', '--memory-init-file', '0', '-Werror', '-Wno-format', '-s', 'BOOTSTRAPPING_STRUCT_INFO=1', '-s', 'WARN_ON_UNDEFINED_SYMBOLS=0', '-s', 'STRICT=1', '-s', 'SINGLE_FILE=1', '-Wno-error=version-check', '-Wno-deprecated']
emcc: warning: LLVM version appears incorrect (seeing "11.0", expected "12.0") [-Wversion-check]
shared:INFO: EM_IGNORE_SANITY set, ignoring sanity checks
cache:INFO: generating system library: libcompiler_rt.a... (this will be cached in "/home/jakob/tmp/emscripten/cache/wasm/libcompiler_rt.a" for subsequent builds)
clang -cc1as: fatal error: error in backend: don't yet support defined globals
em++: error: '/usr/lib/emsdk/upstream/bin/clang++ -DEMSCRIPTEN -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Xclang -isystem/home/jakob/tmp/emscripten/system/include/SDL -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=8 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/home/jakob/tmp/emscripten/system/include/libcxx -Xclang -isystem/home/jakob/tmp/emscripten/system/lib/libcxxabi/include -Xclang -isystem/home/jakob/tmp/emscripten/system/include/compat -Xclang -isystem/home/jakob/tmp/emscripten/system/include -Xclang -isystem/home/jakob/tmp/emscripten/system/include/libc -Xclang -isystem/home/jakob/tmp/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/home/jakob/tmp/emscripten/system/local/include -Xclang -isystem/home/jakob/tmp/emscripten/system/include/SSE -Xclang -isystem/home/jakob/tmp/emscripten/system/include/neon -Xclang -isystem/home/jakob/tmp/emscripten/system/lib/compiler-rt/include -Xclang -isystem/home/jakob/tmp/emscripten/system/lib/libunwind/include -Xclang -isystem/home/jakob/tmp/emscripten/cache/wasm/include -Werror -O2 -fno-builtin -c -o /tmp/emscripten_temp_blqk7fts/stack_limits.o /home/jakob/tmp/emscripten/system/lib/compiler-rt/stack_limits.S -c -o /tmp/emscripten_temp_blqk7fts/stack_limits.o' failed (1)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/jakob/tmp/emscripten/tools/system_libs.py", line 79, in run_one_command
    shared.run_process(cmd, stdout=stdout, stderr=stderr, env=safe_env)
  File "/home/jakob/tmp/emscripten/tools/shared.py", line 94, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/jakob/tmp/emscripten/em++', '-Werror', '-O2', '-fno-builtin', '-c', '/home/jakob/tmp/emscripten/system/lib/compiler-rt/stack_limits.S', '-o', '/tmp/emscripten_temp_blqk7fts/stack_limits.o', '-Wno-deprecated']' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jakob/tmp/emscripten/emcc.py", line 3298, in <module>
    sys.exit(main(sys.argv))
  File "/home/jakob/tmp/emscripten/emcc.py", line 3291, in main
    ret = run(args)
  File "/home/jakob/tmp/emscripten/emcc.py", line 2125, in run
    extra_files_to_link += system_libs.calculate([f for _, f in sorted(temp_files)] + extra_files_to_link, link_as_cxx, forced=forced_stdlibs)
  File "/home/jakob/tmp/emscripten/tools/system_libs.py", line 1518, in calculate
    add_library(system_libs_map[forced])
  File "/home/jakob/tmp/emscripten/tools/system_libs.py", line 1509, in add_library
    libs_to_link.append((lib.get_path(), need_whole_archive))
  File "/home/jakob/tmp/emscripten/tools/system_libs.py", line 335, in get_path
    return shared.Cache.get(self.get_filename(), self.build)
  File "/home/jakob/tmp/emscripten/tools/cache.py", line 125, in get
    temp = creator()
  File "/home/jakob/tmp/emscripten/tools/system_libs.py", line 382, in build
    create_lib(out_filename, self.build_objects())
  File "/home/jakob/tmp/emscripten/tools/system_libs.py", line 376, in build_objects
    run_build_commands(commands)
  File "/home/jakob/tmp/emscripten/tools/system_libs.py", line 93, in run_build_commands
    pool.map_async(run_one_command, commands, chunksize=1).get(999999)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
subprocess.CalledProcessError: Command '['/home/jakob/tmp/emscripten/em++', '-Werror', '-O2', '-fno-builtin', '-c', '/home/jakob/tmp/emscripten/system/lib/compiler-rt/stack_limits.S', '-o', '/tmp/emscripten_temp_blqk7fts/stack_limits.o', '-Wno-deprecated']' returned non-zero exit status 1.
FAIL: Compilation failed!: ['/home/jakob/tmp/emscripten/emcc', '-D_GNU_SOURCE', '-I.', '-o', '/tmp/tmpfnwocjpq.js', '/tmp/tmp6sletzao.c', '-O0', '--memory-init-file', '0', '-Werror', '-Wno-format', '-s', 'BOOTSTRAPPING_STRUCT_INFO=1', '-s', 'WARN_ON_UNDEFINED_SYMBOLS=0', '-s', 'STRICT=1', '-s', 'SINGLE_FILE=1', '-Wno-error=version-check', '-Wno-deprecated']
```

**Comment by jkbbwr** [comment]
If I knew more about what its trying to do I could offer to help by working on it

**Comment by sbc100** [comment]
I think you will be better off leaving the `src/struct_info.json` alone and creating a new file for your structs then then running `tools/gen_struct_info.py` on your file.   e.g. `tools/gen_struct_info.py myfie.json > output.json`.

**Comment by jkbbwr** [comment]
For some reason it still goes of and tries to cache `libcompiler_rt.a` 

This is my header
```c
jakob@devtank~/tmp> cat test.h
typedef struct thing {
    int a;
    int b;
} thing_t;
```

This is my json
```json
jakob@devtank~/tmp> cat my.json 
[
    {
        "defines": [],
        "file": "test.h",
        "structs": {
            "thing": [
                "a",
                "b"
            ]
        }
    }
]
```

This is my invocation
```
jakob@devtank~/tmp> ./emscripten/tools/gen_struct_info.py -I . my.json
gen_struct_info: Generating C code... /tmp/tmpab07hsxt.c
gen_struct_info: Compiling generated code...
gen_struct_info: ['/home/jakob/tmp/emscripten/emcc', '-D_GNU_SOURCE', '-I.', '-o', '/tmp/tmpmg6e_2p0.js', '/tmp/tmpab07hsxt.c', '-O0', '--memory-init-file', '0', '-Werror', '-Wno-format', '-s', 'BOOTSTRAPPING_STRUCT_INFO=1', '-s', 'WARN_ON_UNDEFINED_SYMBOLS=0', '-s', 'STRICT=1', '-s', 'SINGLE_FILE=1', '-Wno-error=version-check', '-Wno-deprecated']
emcc: warning: LLVM version appears incorrect (seeing "11.0", expected "12.0") [-Wversion-check]
shared:INFO: EM_IGNORE_SANITY set, ignoring sanity checks
cache:INFO: generating system library: libcompiler_rt.a... (this will be cached in "/home/jakob/tmp/emscripten/cache/wasm/libcompiler_rt.a" for subsequent builds)
clang -cc1as: fatal error: error in backend: don't yet support defined globals
em++: error: '/usr/lib/emsdk/upstream/bin/clang++ -DEMSCRIPTEN -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Xclang -isystem/home/jakob/tmp/emscripten/system/include/SDL -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=8 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/home/jakob/tmp/emscripten/system/include/libcxx -Xclang -isystem/home/jakob/tmp/emscripten/system/lib/libcxxabi/include -Xclang -isystem/home/jakob/tmp/emscripten/system/include/compat -Xclang -isystem/home/jakob/tmp/emscripten/system/include -Xclang -isystem/home/jakob/tmp/emscripten/system/include/libc -Xclang -isystem/home/jakob/tmp/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/home/jakob/tmp/emscripten/system/local/include -Xclang -isystem/home/jakob/tmp/emscripten/system/include/SSE -Xclang -isystem/home/jakob/tmp/emscripten/system/include/neon -Xclang -isystem/home/jakob/tmp/emscripten/system/lib/compiler-rt/include -Xclang -isystem/home/jakob/tmp/emscripten/system/lib/libunwind/include -Xclang -isystem/home/jakob/tmp/emscripten/cache/wasm/include -Werror -O2 -fno-builtin -c -o /tmp/emscripten_temp_l6z2tcq9/stack_limits.o /home/jakob/tmp/emscripten/system/lib/compiler-rt/stack_limits.S -c -o /tmp/emscripten_temp_l6z2tcq9/stack_limits.o' failed (1)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/jakob/tmp/emscripten/tools/system_libs.py", line 79, in run_one_command
    shared.run_process(cmd, stdout=stdout, stderr=stderr, env=safe_env)
  File "/home/jakob/tmp/emscripten/tools/shared.py", line 94, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/jakob/tmp/emscripten/em++', '-Werror', '-O2', '-fno-builtin', '-c', '/home/jakob/tmp/emscripten/system/lib/compiler-rt/stack_limits.S', '-o', '/tmp/emscripten_temp_l6z2tcq9/stack_limits.o', '-Wno-deprecated']' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jakob/tmp/emscripten/emcc.py", line 3298, in <module>
    sys.exit(main(sys.argv))
  File "/home/jakob/tmp/emscripten/emcc.py", line 3291, in main
    ret = run(args)
  File "/home/jakob/tmp/emscripten/emcc.py", line 2125, in run
    extra_files_to_link += system_libs.calculate([f for _, f in sorted(temp_files)] + extra_files_to_link, link_as_cxx, forced=forced_stdlibs)
  File "/home/jakob/tmp/emscripten/tools/system_libs.py", line 1518, in calculate
    add_library(system_libs_map[forced])
  File "/home/jakob/tmp/emscripten/tools/system_libs.py", line 1509, in add_library
    libs_to_link.append((lib.get_path(), need_whole_archive))
  File "/home/jakob/tmp/emscripten/tools/system_libs.py", line 335, in get_path
    return shared.Cache.get(self.get_filename(), self.build)
  File "/home/jakob/tmp/emscripten/tools/cache.py", line 125, in get
    temp = creator()
  File "/home/jakob/tmp/emscripten/tools/system_libs.py", line 382, in build
    create_lib(out_filename, self.build_objects())
  File "/home/jakob/tmp/emscripten/tools/system_libs.py", line 376, in build_objects
    run_build_commands(commands)
  File "/home/jakob/tmp/emscripten/tools/system_libs.py", line 93, in run_build_commands
    pool.map_async(run_one_command, commands, chunksize=1).get(999999)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
subprocess.CalledProcessError: Command '['/home/jakob/tmp/emscripten/em++', '-Werror', '-O2', '-fno-builtin', '-c', '/home/jakob/tmp/emscripten/system/lib/compiler-rt/stack_limits.S', '-o', '/tmp/emscripten_temp_l6z2tcq9/stack_limits.o', '-Wno-deprecated']' returned non-zero exit status 1.
FAIL: Compilation failed!: ['/home/jakob/tmp/emscripten/emcc', '-D_GNU_SOURCE', '-I.', '-o', '/tmp/tmpmg6e_2p0.js', '/tmp/tmpab07hsxt.c', '-O0', '--memory-init-file', '0', '-Werror', '-Wno-format', '-s', 'BOOTSTRAPPING_STRUCT_INFO=1', '-s', 'WARN_ON_UNDEFINED_SYMBOLS=0', '-s', 'STRICT=1', '-s', 'SINGLE_FILE=1', '-Wno-error=version-check', '-Wno-deprecated']
```

**Comment by sbc100** [comment]
Is you emsdk out-of-date?  Try updating from git and `emsdk install latest`

**Comment by jkbbwr** [comment]
Yay! Everything is progressing!

Getting to latest allows me to parse some simple structs and get out size info, this is great.

The downside is, it fails as soon as anything tries to include `stdlib.h` as the system stdlib includes.

```
jakob@devtank~/tmp> cat test.h
#include <stdlib.h>

typedef struct thing {
    int a;
    int b;
} thing_t;
```

It crashes out on attributes used in `stdlib.h`

```
jakob@devtank~/tmp> /usr/lib/emsdk/upstream/emscripten/tools/gen_struct_info.py -I . test.h
gen_struct_info: Parsing header "test.h"...
Traceback (most recent call last):
  File "/usr/lib/emsdk/upstream/emscripten/tools/gen_struct_info.py", line 565, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/emsdk/upstream/emscripten/tools/gen_struct_info.py", line 554, in main
    data = parse_header(header, cpp_opts)
  File "/usr/lib/emsdk/upstream/emscripten/tools/gen_struct_info.py", line 235, in parse_header
    ast = pycparser.parse_file(path, True, cpp_path=shared.CLANG_CC, cpp_args=['-E'] + cpp_opts)
  File "/usr/lib/python3.8/site-packages/pycparser/__init__.py", line 90, in parse_file
    return parser.parse(text, filename)
  File "/usr/lib/python3.8/site-packages/pycparser/c_parser.py", line 149, in parse
    return self.cparser.parse(
  File "/usr/lib/python3.8/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.8/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3.8/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/lib/python3.8/site-packages/pycparser/c_parser.py", line 1845, in p_error
    self._parse_error(
  File "/usr/lib/python3.8/site-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /usr/include/stdlib.h:97:45: before: __attribute__
```

**Comment by sbc100** [comment]
If you switch the compiler to `shared.CLANG_CXX` in `gen_struct_info.py` does it work?

**Comment by sbc100** [comment]
Oh it also looks like if you give it a json file as input it won't try to parse the headers directly:

```
  for header in args.headers:                                                                        
    if header[-5:] == '.json':                                                                       
      # This is a JSON file, parse it.                                                               
      parse_json(header, header_files, structs, defines)                                             
    else:                                                                                            
      # If the passed file isn't a JSON file, assume it's a header.                                  
      header_files.append(header)                                                                    
      data = parse_header(header, cpp_opts)                                                          
      structs.update(data['structs'])                                                                
      defines.extend(data['defines'])    
```

**Comment by sbc100** [comment]
Since we don't use the `parse_header` feature internally perhaps we should remove that feature (it gets no testing)
