### ISSUE TITLE
compiled successfully, but when running the js in chrome, it reports an error.

### ISSUE THREAD

**Issue by qingweiqm** [emscripten-core/emscripten#12842]

**Comment by qingweiqm** [comment]
here is the error message from the chrome console:

------------------------------------------------------------------------
Uncaught (in promise) RuntimeError: abort(RuntimeError: abort(bad ioctl syscall 35090) at Error
    at jsStackTrace (http://172.16.144.195/mac.js:1680:19)
    at stackTrace (http://172.16.144.195/mac.js:1697:16)
    at abort (http://172.16.144.195/mac.js:1410:44)
    at ___sys_ioctl (http://172.16.144.195/mac.js:4196:18)
    at <anonymous>:wasm-function[7]:0x4a1
    at <anonymous>:wasm-function[4]:0x23e
    at main (<anonymous>:wasm-function[5]:0x454)
    at http://172.16.144.195/mac.js:1467:22
    at callMain (http://172.16.144.195/mac.js:5598:15)
    at doRun (http://172.16.144.195/mac.js:5657:23)) at Error
    at jsStackTrace (http://172.16.144.195/mac.js:1680:19)
    at stackTrace (http://172.16.144.195/mac.js:1697:16)
    at abort (http://172.16.144.195/mac.js:1410:44)
    at ___sys_ioctl (http://172.16.144.195/mac.js:4199:69)
    at <anonymous>:wasm-function[7]:0x4a1
    at <anonymous>:wasm-function[4]:0x23e
    at main (<anonymous>:wasm-function[5]:0x454)
    at http://172.16.144.195/mac.js:1467:22
    at callMain (http://172.16.144.195/mac.js:5598:15)
    at doRun (http://172.16.144.195/mac.js:5657:23)
    at abort (http://172.16.144.195/mac.js:1416:11)
    at ___sys_ioctl (http://172.16.144.195/mac.js:4199:69)
    at <anonymous>:wasm-function[7]:0x4a1
    at <anonymous>:wasm-function[4]:0x23e
    at main (<anonymous>:wasm-function[5]:0x454)
    at http://172.16.144.195/mac.js:1467:22
    at callMain (http://172.16.144.195/mac.js:5598:15)
    at doRun (http://172.16.144.195/mac.js:5657:23)
    at run (http://172.16.144.195/mac.js:5672:5)
    at runCaller (http://172.16.144.195/mac.js:5576:19)
-------------------------------------------------------------------------


Any ideas, any input will be appriciated!

**Comment by qingweiqm** [comment]
the original file is a simple C file to get the mac address.

**Comment by sbc100** [comment]
Emscripten doesn't support that ioctl.    Its not surprising I suppose as the there is no way address you mac address on the web.

If you want to fake it out you could modify the ioctl implementation in src/library_syscall.js

**Comment by qingweiqm** [comment]
Got it.  I'm new guy to webassembly, Thanks!
