### ISSUE TITLE
Abort when using static std::map with string as key

### ISSUE THREAD

**Issue by Daft-Freak** [emscripten-core/emscripten#1289]
This code:

```
#include <string>
#include <map>
#include <iostream>

using namespace std;

void test()
{
    static const map<string, int> stringAsKey = {
        {"string", 1},
        {"another string", 2}
    };

}

int main()
{
    cout << "start" << endl;

    test();
    cout << "1" << endl;
    test();
    cout << "2" << endl;

    cout << "done" << endl;

    return 0;
}
```

When compiled with `emcc -std=c++11` causes an abort in `_free` when calling the function for the second time (Works as expected with gcc and clang). Removing the static prevents the crash.

Output:

```
start
1

/home/daftfreak/emtest/a.out.js:130330
      throw e;
            ^
abort() at Error
    at _abort (/home/daftfreak/emtest/a.out.js:2118:30)
    at _free (/home/daftfreak/emtest/a.out.js:122253:7)
    at __ZdlPv (/home/daftfreak/emtest/a.out.js:127342:7)
    at __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED2Ev (/home/daftfreak/emtest/a.out.js:15431:7)
    at __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED1Ev (/home/daftfreak/emtest/a.out.js:15328:3)
    at __ZNSt3__14pairIKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEiED2Ev (/home/daftfreak/emtest/a.out.js:9674:3)
    at __ZNSt3__14pairIKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEiED1Ev (/home/daftfreak/emtest/a.out.js:4060:3)
    at __Z4testv (/home/daftfreak/emtest/a.out.js:4003:7)
    at Object._main (/home/daftfreak/emtest/a.out.js:4096:3)
    at Object.callMain (/home/daftfreak/emtest/a.out.js:130322:26)
```

**Comment by Daft-Freak** [comment]
This was fixed by that workaround and seems to now work without the workaround. (If `-fno-threadsafe-statics` is still useful.)

**Comment by kripken** [comment]
Great, sounds like we can close this then.
