### ISSUE TITLE
Errors in fresh emscripten install

### ISSUE THREAD

**Issue by softsprocket** [emscripten-core/emscripten#12900]
I followed the istall instructions for linux found here: https://emscripten.org/docs/getting_started/downloads.html#sdk-download-and-install

$ emcc -v
Traceback (most recent call last):
  File "/home/greg/Development/web/emsdk/upstream/emscripten/emcc.py", line 40, in <module>
    import emscripten
  File "/home/greg/Development/web/emsdk/upstream/emscripten/emscripten.py", line 463
    args.append(f'--separate-data-segments={memfile}')
                                                    ^
SyntaxError: invalid syntax

**Comment by softsprocket** [comment]
I see that f string formatting is added in python3 3.6 and linux mint is at 3.5 but I thought emsrcipten used its own installed version of python3?

**Comment by softsprocket** [comment]
Ah, I see on linux it doesn't install python3 so the local install must be >3.6 to work - not available from the package manager. It will have to be finagled by pathing. I'm closing this.
