### ISSUE TITLE
Function signature mismatch

### ISSUE THREAD

**Issue by pavlukivan** [emscripten-core/emscripten#12950]
I'm attempting to run Google Dawn code using OpenGL and Emscripten, but ran into a runtime error with signature mismatch. The function is declared as `GLenum glClientWaitSync(GLsync p0, GLbitfield p1, GLuint64 p2)`, the code I use calls it as `(func (param i32 i32 i64) (result i32)))`, but Emscripten defines it as `(func (param i32 i32 i32 i32) (result i32)))`. Are there any flags I'm missing, or is it a bug in Emscripten or the SDK?

**Comment by pavlukivan** [comment]
I tried adding `-s RELOCATABLE=1`, but now it says `undefined symbol 'glfwGetProcAddress'`

**Comment by kripken** [comment]
Looks like the difference between the two signatures is legalization. The i64 is turned into two i32s.

What is the stack trace leading to the error? Probably something there needs to be fixed.

Note that building with `-s WASM_BIGINT` would use BigInts to avoid the need for legalization, and so might work around this.

**Comment by pavlukivan** [comment]
bigint probably won't help, https://github.com/emscripten-core/emscripten/blob/13eddf9aad21c5649ca7a7c1973bdea5c3ce1257/src/library_webgl2.js#L695 has the function signature hardcoded as 2x i32 (I can try tomorrow, but it's unlikely to help). The problem is clearly the fact the dynamically loaded function call doesn't get legalized, the function gets loaded without problems but the signature mismatches as I checked using wasm2wat.

**Comment by kripken** [comment]
Those will need to be fixed, good find. We should emit different code for WASM_BIGINT in those cases. But as you said, that's a separate issue.

The puzzle here is why this fails specifically, and not other i64-using functions (we don't have any open issues on those AFAIK) That's why I hope the stack trace may help - it matters if it's coming from JS or from wasm, in particular. It may be a place in the JS code that needs fixing.

Legalizing every single function, even internal ones and even in the table, would add overhead, so we avoid it (and our tools don't have an option for it, even, I believe).

**Comment by pavlukivan** [comment]
however when there's a dynamic pointer to an arbitrary function that accepts i64 that can be either a js binding or an internal function, isn't there no choice but to legalize every function? Otherwise, js bindings should use its own calling convention to differentiate the function pointers

**Comment by pavlukivan** [comment]
Here's a minimal example that you should honestly add to test cases:

```cpp
#include <stdio.h>
#include <emscripten.h>
#include <GLES3/gl3.h>
#include <GLFW/glfw3.h>

GLenum test_func(GLsync, GLbitfield, GLuint64) {
	return 0;
}

int main() {
	printf("Starting\n");
	PFNGLCLIENTWAITSYNCPROC func = &test_func;
	printf("Calling test_func\n");
	func(0, 0, 0);
	func = (PFNGLCLIENTWAITSYNCPROC)glfwGetProcAddress("glClientWaitSync");
	if(!func) {
		printf("Error: glClientWaitSync not found\n");
		return 0;
	}
	printf("Calling glClientWaitSync\n");
	func(0, 0, 0);
	printf("Done\n");
}
```

As far as I can tell, only `glClientWaitSync` accepts an i64 like that (also printf-like funcs, but its okay because of varargs), which explains why nobody found it yet. And I'm not sure users can even provide custom JS functions that take i64 as an argument.

**Comment by sbc100** [comment]
I think I that case it would not be possible to implement glClientWaitSync directly JS.   You would need to have glfwGetProcAddress return the address of a wasm function and then that wasm function can then call out of JS if needed, but that actual implementation of glClientWaitSync would need to be in native wasm (unless WASM_BIGINT is enabled in which case this whole problem goes away).

**Comment by sbc100** [comment]
If a JS implementation really wanted to provide truly dynamic symbols it could also use a small WebAssembly shim to wrap JS functions into WebAssembly function.  You can imagine a small module whos only purpose is to import a JS function and export a wasm function with the signature converted to use i64.

We do something just like that already when users try to add JavaScript functions to the wasm table at runtime:
https://github.com/emscripten-core/emscripten/blob/28b1af76755d0950cab70f3e33432d9c10916236/src/runtime_functions.js#L8

**Comment by pavlukivan** [comment]
There's another mismatch when calling `glSampleMaski` but I can't find the definition in emscripten so I can't find out why the mismatch happens, perhaps in this case it just means the function isn't defined?

**Comment by sbc100** [comment]
I guess the fix in this case is to move the glClientWaitSync symbol into native code than have *it* call the emscripten_glClientWaitSync JS function.     That way, glfwGetProcAddress will return a point to the native i64 taking function.

**Comment by briancullinan** [comment]
Is there a simple way to tell *which* function it is trying to call?  I only get this ambiguous output:
```
exception thrown: RuntimeError: function signature mismatch,RuntimeError: function signature mismatch
    at http://localhost:8080/quake3e.wasm:wasm-function[1989]:0x84a15
    at http://localhost:8080/quake3e.wasm:wasm-function[2405]:0xa34ca
    at dynCall_vi (http://localhost:8080/quake3e.wasm:wasm-function[2515]:0xa6edd)
    at Module.dynCall_vi (http://localhost:8080/quake3e.js:1:480724)
    at invoke_vi (http://localhost:8080/quake3e.js:1:499706)
    at http://localhost:8080/quake3e.wasm:wasm-function[2179]:0x933e5
    at http://localhost:8080/quake3e.wasm:wasm-function[2935]:0xfbb9f
    at dynCall_v (http://localhost:8080/quake3e.wasm:wasm-function[2516]:0xa6ee5)
    at Object.Module.dynCall_v (http://localhost:8080/quake3e.js:1:480403)
    at browserIterationFunc (http://localhost:8080/quake3e.js:1:74942)
```

I don't see how :wasm-function[2516]:0xa6ee5 makes any sense to anyone. What am I missing?

**Comment by sbc100** [comment]
If you build with `--profiling` (or just `--profiling-funcs`, or full `-g`) you should see real function names rather than `wasm-function[N]`

**Comment by briancullinan** [comment]
Strange I see function names but with -O1 some of the functions are purged
from the call tree and moved to the parent function. Then I see a warning
"this is a large function you should consider using -Oz"

I'll continue using printf since nothing about this stack and the docs
isn't obfuscated.

**Comment by sbc100** [comment]
Do you know what tools is generating "this is a large function you should consider using -Oz"?  I can't find that warning in any of our tools.

**Comment by kripken** [comment]
I think the warning about large functions was present in older versions of emscripten. It made sense for asm.js. So I'd recommend upgrading to latest emscripten, that might also fix this issue if it's been resolved meanwhile.

**Comment by atsushieno** [comment]
I am experiencing similar issue on my experimental audio app port, stack trace can be seen at https://github.com/juce-framework/JUCE/commit/67cd7ec

I binary searched which release had triggered, and it was 1.39.20. There seems couple of suspicious changes between 1.39.19 and 1.39.20 (llvm upgrade to 12, stack allocation changes, varargs reading...), but I have no further idea.

**Comment by hannorein** [comment]
I believe I have the same issue when calling `glVertexAttribDivisor`.

**Comment by hannorein** [comment]
If anyone else stumbling upon this, a cross-platform workaround that works for me is the following (using the idea of @sbc100):

```c
#ifdef __EMSCRIPTEN__
void emscripten_glVertexAttribDivisor (GLuint index, GLuint divisor);
#define reb_glVertexAttribDivisor emscripten_glVertexAttribDivisor
#else
#define reb_glVertexAttribDivisor glVertexAttribDivisor
#endif
```
