### ISSUE TITLE
Flaky "Internal error!" and other exceptions when using threads

### ISSUE THREAD

**Issue by emaxx-google** [emscripten-core/emscripten#12970]
Reproducible using this simple program, although with a big number of iterations:

```
#include <thread>
int main() {
  for (int i = 0; i < 1000000; ++i)
    std::thread([](){}).join();
}
```

Compilation flags (using Emscripten 2.0.6):
```
emcc main.cc -s INITIAL_MEMORY=67108864 -pthread -s PROXY_TO_PTHREAD=1 -s EXIT_RUNTIME=1
```

This program typically crashes with an exception after some number of iterations (sometimes 100, sometimes as big as 30000), e.g.:

```
Internal error!
Thrown at:
    at a.out.js:151:7
    at emit (events.js:315:20)
    at internal/process/execution.js:165:25
```

or (when running in Chrome, the stack trace is fuller for whatever reason);

```
spawnThread	@	a.out.js:3125
_pthread_create	@	a.out.js:3349
(anonymous)	@	a.out.wasm:0x87b0
emscripten_current_thread_process_queued_calls	@	a.out.wasm:0x83e0
emscripten_main_thread_process_queued_calls	@	a.out.wasm:0x941b
(anonymous)	@	a.out.wasm:0x7f2b
(anonymous)	@	a.out.wasm:0x7ff8
(anonymous)	@	a.out.wasm:0x7527
(anonymous)	@	a.out.wasm:0x73f3
free	@	a.out.wasm:0x63fd
(anonymous)	@	a.out.js:1615
freeThreadData	@	a.out.js:2039
returnWorkerToPool	@	a.out.js:2047
worker.onmessage	@	a.out.js:2101
```

or

```
Pthread aborting at Error
    at abort (eval at globalEval (a.out.worker.js:200:10), <anonymous>:1630:70)
    at _abort (eval at globalEval (a.out.worker.js:200:10), <anonymous>:2410:7)
    at dlfree (wasm-function[264]:0x76b0)
    at operator delete(void*) (wasm-function[99]:0x208b)
    at std::__2::default_delete<std::__2::tuple<std::__2::unique_ptr<std::__2::__thread_struct, std::__2::default_delete<std::__2::__thread_struct> >, main::$_0> >::operator()(std::__2::tuple<std::__2::unique_ptr<std::__2::__thread_struct, std::__2::default_delete<std::__2::__thread_struct> >, main::$_0>*) const (wasm-function[91]:0x1ed5)
    at std::__2::unique_ptr<std::__2::tuple<std::__2::unique_ptr<std::__2::__thread_struct, std::__2::default_delete<std::__2::__thread_struct> >, main::$_0>, std::__2::default_delete<std::__2::tuple<std::__2::unique_ptr<std::__2::__thread_struct, std::__2::default_delete<std::__2::__thread_struct> >, main::$_0> > >::reset(std::__2::tuple<std::__2::unique_ptr<std::__2::__thread_struct, std::__2::default_delete<std::__2::__thread_struct> >, main::$_0>*) (wasm-function[59]:0x1633)
    at std::__2::unique_ptr<std::__2::tuple<std::__2::unique_ptr<std::__2::__thread_struct, std::__2::default_delete<std::__2::__thread_struct> >, main::$_0>, std::__2::default_delete<std::__2::tuple<std::__2::unique_ptr<std::__2::__thread_struct, std::__2::default_delete<std::__2::__thread_struct> >, main::$_0> > >::~unique_ptr() (wasm-function[46]:0x117c)
    at void* std::__2::__thread_proxy<std::__2::tuple<std::__2::unique_ptr<std::__2::__thread_struct, std::__2::default_delete<std::__2::__thread_struct> >, main::$_0> >(void*) (wasm-function[36]:0xe42)
    at Object.dynCall (eval at globalEval (a.out.worker.js:200:10), <anonymous>:1945:33)
    at onmessage (a.out.worker.js:124:39)
```

The exceptions are seen regardless of how it's executed: Node (12.18.1) or Chrome (87.0.4280.66).

I believe I also see the same errors in a non-synthetic real-world program (with much smaller number of threads but a big amount of other functionality).

**Comment by kripken** [comment]
Looks like the error here happens on

https://github.com/emscripten-core/emscripten/blob/96b14d38f547092d9875b601aa60298a506ba550/src/library_pthread.js#L497

To debug it, we'd need to trace each worker object I suppose, and see what is assigned to `pthread` there. In particular as it gets put back in `unusedWorkers` and re-used.

**Comment by emaxx-google** [comment]
Hello, is there anything else I can do to help fixing this bug?

I realize that the program from the initial post may look too synthetic, however it's just the smallest repro that I could find for an issue that I'm observing in real-world programs as well. Also this issue makes it harder to investigate/reproduce Emscripten's other pthreads issues.

**Comment by sbc100** [comment]
Looks like the fix is to call `freeThreadData` right at the top of `returnWorkerToPool` before adding it to `unusedWorkers`?

**Comment by kripken** [comment]
I'm not sure why you think that would help @sbc100 ? What is `freeThreadData` doing that ends up being an issue?

(Does calling `free` somehow end up calling into worker management code? I hope it doesn't, but maybe it does...?)

**Comment by kripken** [comment]
Oh, yes, I saw the other email now. Makes sense. So what happens is `free` ends up taking a lock, which ends up running the proxied main thread message queue. And if there is a `pthread_create` that is proxied, that will indeed make changes on the worker management code.

**Comment by sbc100** [comment]
freeThreadData calls free which then needs to get the dlmalloc mutex.   If that mutex is busy, because we are the main thread we will busy wait while running `emscripten_main_thread_process_queued_calls`.     One of the queued calls could be thread creation, which can then see that the worker we are in the process of cleaning is :unused".    This looks like it can lead to the worker to be recycled before we doing freeing its data.   Or am I missing something?

Solution: don't mark it as unused until we are 100% done with it.

**Comment by sbc100** [comment]
Should I make a PR for this?  Sadly write a good test will be hard (impossible?).

**Comment by kripken** [comment]
Yes, I think that's right. But I'm not sure what the solution is. The current code already seems to do what I would hope would work, which is to clean up everything and then do the free. Doing the free earlier doesn't seem safe.

Setting `worker.pthread` to null at the beginning might be better. But I'm not sure that's right either.

It seems like we want to have a critical section, where the event queue is not run. But that may be significant work.

(Yes, a doubt we can test this, it's a race.)

**Comment by sbc100** [comment]
Why not just to the free before putting the worker back in the unused list?

**Comment by kripken** [comment]
If you do the free as the very first operation, then if there is a `pthread_create` there it will not have an available pthread. And if there is no other one available, it can error.

Doing it at the very end seems more promising to me, that is, after `worker.pthread = undefined;`. But when I test that, it fails for a reason I don't see yet.

**Comment by kripken** [comment]
Another issue with doing the freefirst is that after free one of the structures something, if we run an event for that same thread, the thread is in an inconsistent state.
