### ISSUE TITLE
Embind + Dynamic Libraries: RuntimeError function signature mismatch

### ISSUE THREAD

**Issue by donalffons** [emscripten-core/emscripten#13073]
Hi!

Similar to my previous issues, here is another fairly simplified test case, which results in the following error during WASM instantiation:
```
Uncaught (in promise) RuntimeError: function signature mismatch
    at _ZN8Standard8AllocateEm (<anonymous>:wasm-function[23]:0x1379)
    at obj.<computed> (https://embind-dynamic-libs-03-git-master.donalffons.vercel.app/emscripten/build/main.js:2037:31)
    at _ZN18Standard_TransientnwEm (<anonymous>:wasm-function[4]:0x200)
    at <anonymous>:wasm-function[3]:0x1c8
    at <anonymous>:wasm-function[5]:0x219
    at __post_instantiate (<anonymous>:wasm-function[1]:0x1b6)
    at callRuntimeCallbacks (https://embind-dynamic-libs-03-git-master.donalffons.vercel.app/emscripten/build/main.js:1747:11)
    at initRuntime (https://embind-dynamic-libs-03-git-master.donalffons.vercel.app/emscripten/build/main.js:1361:3)
    at doRun (https://embind-dynamic-libs-03-git-master.donalffons.vercel.app/emscripten/build/main.js:52650:5)
    at run (https://embind-dynamic-libs-03-git-master.donalffons.vercel.app/emscripten/build/main.js:52672:5)
```
Repo: https://github.com/donalffons/embind-dynamicLibs-03
Live Example: https://embind-dynamic-libs-03-git-master.donalffons.vercel.app/javascript

- As before, the code is stripped down from a fairly large code base
- As before, there seems to be a race condition: Sometimes, WASM instantiation works as expected, sometimes it raises the error. For me, the web-hosted live examples runs without issues most of the time. On localhost, I see the error almost always.
- There is one MAIN_MODULE and 2 SIDE_MODULEs (named library1 and library2). Again, there is no Embind code.
- All what library2 does, is [`auto a = Standard::Allocate();`](https://github.com/donalffons/embind-dynamicLibs-03/blob/master/emscripten/library2.cxx#L3). This method is [implemented in library1](https://github.com/donalffons/embind-dynamicLibs-03/blob/master/emscripten/library1.cxx#L12):
```cpp
class Standard_MMgrRaw
{
public:
  virtual void* Allocate() {
    return new int;
  }
};

void* Standard::Allocate()
{
  std::cout << "1" << std::endl;
  auto a = new Standard_MMgrRaw ();
  std::cout << "2" << std::endl;
  auto b = a->Allocate(); // RuntimeError: Function signature mismatch
  std::cout << "3" << std::endl;
  return b;
}
```

Full disclosure: This is most probably the same issue as #13026, but I was hoping to get your attention towards this test case with a new issue.

I would greatly appreciate help with this, as this is a major blocking point for my project.

**Comment by sbc100** [comment]
Thanks for the report.

To be clear, you say there is no embed here, but you include embind in the bug title (was that a mistake?)

In this example it looks like the error occurs in a static constructor (__post_instantiate)... i wonder if that is pertanent?

**Comment by donalffons** [comment]
> To be clear, you say there is no embed here, but you include embind in the bug title (was that a mistake?)

You're right! This has nothing to do with Embind. I just pushed a new commit to `master`in which I removed all the Embind flags + file. Will change the title in a second.

> In this example it looks like the error occurs in a static constructor (__post_instantiate)

To simplify things a bit more, I changed the static method `Standard::Allocate()` into a simple function named `Standard_Allocate()` and it leads to the same error. I pushed that change to the `master` branch.

**Comment by donalffons** [comment]
I made another branch ([`call-virtual-method-directly`](https://github.com/donalffons/embind-dynamicLibs-03/tree/call-virtual-method-directly)) in which I tested calling the `virtual` method "directly" like this:
```cpp
// library2.cxx

// New version (no error):
void* a = (new Standard_MMgrRaw())->Allocate();

// Previous Version (throws the function signature mismatch error):
// void* a = Standard_Allocate();
```
With this version, the error goes away. Here is a [live example of the branch `call-virtual-method-directly`](https://embind-dynamic-libs-03-git-call-virtual-method-directly.donalffons.vercel.app/javascript).

**Comment by donalffons** [comment]
I think I found a workaround. I pushed it to the `manually-loading-libraries` branch.

- [`maunally-loading-libraries`](https://github.com/donalffons/embind-dynamicLibs-03/tree/manually-loading-libraries)-branch in repo
- [Live Example](https://embind-dynamic-libs-03-git-manually-loading-libraries.donalffons.vercel.app/javascript)

In the `master` branch, I was using the `dynamicLibraries` array of Emscripten's `Module` object to load the libraries like this:
```javascript
dynamicLibraries: [
  "/emscripten/build/library1.wasm",
  "/emscripten/build/library2.wasm",
]
```

Instead of doing this, with this new example, I'm manually loading the libraries like this:

1. I create my own worker thread
2. I fetch both wasm libraries and write them to Emscripten's file system
```javascript
const library1 = new Int8Array(await (await fetch("/emscripten/build/library1.wasm")).arrayBuffer());
o.FS.writeFile("/library1.wasm", library1);
const library2 = new Int8Array(await (await fetch("/emscripten/build/library2.wasm")).arrayBuffer());
o.FS.writeFile("/library2.wasm", library2);
o.ccall("loadLib1");
o.ccall("loadLib2");
o.callMain();
```
3. Those `ccall` functions simply load the libraries using `dlopen`.
```cpp
extern "C" {
  void loadLib1() {
    std::cout << "==> Start loading lib 1" << std::endl;
    dlopen("/library1.wasm", RTLD_NOW | RTLD_GLOBAL);
    std::cout << "<== Finished loading lib 1" << std::endl;
  }
  void loadLib2() {
    std::cout << "==> Start loading lib 2" << std::endl;
    dlopen("/library2.wasm", RTLD_NOW | RTLD_GLOBAL);
    std::cout << "<== Finished loading lib 2" << std::endl;
  }
}
```

With this setup, the `Standard_Allocate` function is correctly executed when `library2` is loaded. After letting this run for 10 minutes (to make sure there are no race conditions), I am pretty sure there are no issues.

@sbc100, it seems like the issue is related to how the `dynamicLibraries` array is used (or to how I am using it :wink:).
