### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by wurc** [emscripten-core/emscripten#13077]
recently upgrade the emsdk to the newest version, below error pop up

wrc@wrc-PNVKB0A0-Samsung-DeskTop:~/wasm_study$ emcc -v
Traceback (most recent call last):
  File "/home/wrc/emsdk/upstream/emscripten/emcc.py", line 40, in <module>
    import emscripten
  File "/home/wrc/emsdk/upstream/emscripten/emscripten.py", line 463
    args.append(f'--separate-data-segments={memfile}')
                                                    ^
SyntaxError: invalid syntax
wrc@wrc-PNVKB0A0-Samsung-DeskTop:~/wasm_study$

wrc@wrc-PNVKB0A0-Samsung-DeskTop:~/wasm_study$ python
Python 3.6.9 (default, Oct  8 2020, 12:12:24)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by wurc** [comment]
wrc@wrc-PNVKB0A0-Samsung-DeskTop:~/wasm_study$ em++ -v
Traceback (most recent call last):
  File "/home/wrc/emsdk/upstream/emscripten/em++.py", line 8, in <module>
    import emcc
  File "/home/wrc/emsdk/upstream/emscripten/emcc.py", line 40, in <module>
    import emscripten
  File "/home/wrc/emsdk/upstream/emscripten/emscripten.py", line 463
    args.append(f'--separate-data-segments={memfile}')

**Comment by sbc100** [comment]
Can you try running with `sh -x` so that you can see exactly which version of python is being chosen?  i.e.
 `sh -x em++ -v`

**Comment by sbc100** [comment]
The problem here is that the version of python being selected does not support python's f-strings.   

As long as the python version being used is 3.6 or above it should be fine.

**Comment by wurc** [comment]
my python version is Python3.6.9
as below command shows:
wrc@wrc-PNVKB0A0-Samsung-DeskTop:~/wasm_study$ python
Python 3.6.9 (default, Oct 8 2020, 12:12:24)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

**Comment by sbc100** [comment]
Can you try running `sh -x em++ -v` ?

**Comment by sbc100** [comment]
em++ has some logic for finding the version of python to use and its clearly finding a different python.
