### ISSUE TITLE
RuntimeError: function signature mismatch with dynamic library and EMULATE_FUNCTION_POINTER_CASTS

### ISSUE THREAD

**Issue by dalcde** [emscripten-core/emscripten#13076]
Sample code:
```c
// main.c
#include <dlfcn.h>
int main() {
  void *handle = dlopen("library.wasm", RTLD_NOW);
  typedef void (*fp)();
  fp g = (fp) dlsym(handle, "foo");
  g();
  return 0;
}
```
```c
// library.c
void foo() {}
```
Build script:
```shell
$ emcc library.c -o library.wasm -s SIDE_MODULE=1 -s EXPORT_ALL=1 -s EMULATE_FUNCTION_POINTER_CASTS=1
$ emcc main.c -s MAIN_MODULE=1 -s EXPORT_ALL=1 --embed-file library.wasm -s EMULATE_FUNCTION_POINTER_CASTS=1
$ node a.out.js
```
Error message:
```
exception thrown: RuntimeError: function signature mismatch,RuntimeError: function signature mismatch
    at __original_main (<anonymous>:wasm-function[145]:0x6dc93)
    at main (<anonymous>:wasm-function[146]:0x6dcae)
    at /tmp/dyncall/a.out.js:1506:22
    at callMain (/tmp/dyncall/a.out.js:49544:15)
    at doRun (/tmp/dyncall/a.out.js:49608:23)
    at run (/tmp/dyncall/a.out.js:49623:5)
    at runCaller (/tmp/dyncall/a.out.js:49518:19)
    at removeRunDependency (/tmp/dyncall/a.out.js:1427:7)
    at receiveInstance (/tmp/dyncall/a.out.js:1573:5)
    at receiveInstantiatedSource (/tmp/dyncall/a.out.js:1589:5)
```
emcc version: 2.0.10

**Comment by dalcde** [comment]
Here it appears that `library.wasm` exports the original function `foo`, but `main.c` imports the function pointer `foo` and calls it as if it were emulated.

I can confirm that the code works with `1.38.45-fastcomp`, after patching a typo `dlsym` (see https://github.com/iodide-project/pyodide/blob/master/emsdk/patches/emulate_pointer.patch ). I haven't looked much into the generated output, but `library.wasm` contains emulated functions and exports `fp$_foo` which `dlsym` uses.

As far as I can tell, the combination `dlsym` + `EMULATE_FUNCTION_POINTER_CASTS` has been broken since 1.38.34, but the mechanism in which it breaks has changed.

**Comment by sbc100** [comment]
Perhaps this is a fastcomp vs llvm backend thing?   Can you try with the last ever fastcomp release which was 1.40.1?  

If you take a release where this works under fastcomp and you switch to the llvm backend does this cause it to fail (I imagine the answer will be yes which means this probably never worked with the llvm backend).

**Comment by dalcde** [comment]
With `1.40.1-fastcomp` I can't run anything with `-s MAIN_MODULE=1 -s EMULATE_FUNCTION_POINTER_CASTS=1` at all:
```c
// main.c
int main() { return 0; }
```
```shell
$ emcc main.c -s MAIN_MODULE=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s EXPORT_ALL=1
$ node a.out.js
```
Error:
```
RuntimeError: function signature mismatch
/tmp/broken/a.out.js:123
      throw ex;
      ^

RuntimeError: abort(RuntimeError: function signature mismatch) at Error
    at jsStackTrace (/tmp/broken/a.out.js:2473:17)
    at stackTrace (/tmp/broken/a.out.js:2496:16)
    at process.abort (/tmp/broken/a.out.js:2158:44)
    at process.emit (node:events:376:20)
    at emit (node:internal/process/promises:202:22)
    at processPromiseRejections (node:internal/process/promises:223:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:32)
    at process.abort (/tmp/broken/a.out.js:2164:11)
    at process.emit (node:events:376:20)
    at emit (node:internal/process/promises:202:22)
    at processPromiseRejections (node:internal/process/promises:223:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:32)
```
`1.40.1-upstream` has the same error as `2.0.10`

**Comment by sbc100** [comment]
So did this code ever with with the llvm backend?   From what I can't tell the answer is no?

And what is that last version where it work with fastcomp where this code works without an extra patch?  1.38.33?

**Comment by sbc100** [comment]
I did a little investigation.   I was able to get your example to work with fastcomp (plus your patch).  I can even get it to work right up to the last fastcomp release (1.40.1) if I use MAIN_MODULE=2 instead of MAIN_MODULE=1.

However, I can't see that this *ever* worked with the llvm backend so its a feature we still need to add (dynamic linking + EMULATE_FUNCTION_POINTER_CASTS).  

I believe that in order to implement this we will need to dynamically generate a thunk module for each function address shared between the dynamic libraries.   This is because we use a model were only function themselves are exported, no function addresses.   Function addresses are generated by adding functions to the wasm table at runtime.  @kripken what do you think?

So for now, until we can find a fix for this, I think we should error out on this combination of build flags.

**Comment by dalcde** [comment]
It appears that @joerromano has working patches here: https://github.com/joemarshall/pyodide/commit/e5604882471c284e03829d9149768fb6acb05f51
