### ISSUE TITLE
SDL 2 and SDL image 2 dependencies

### ISSUE THREAD

**Issue by Laguna1989** [emscripten-core/emscripten#13174]
The `CMakeLists.txt` contains the following lines

```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -s USE_SDL=2")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='[\"bmp\",\"png\"]'")
```

When I compile a project with no ports available in `emsdk\upstream\emscripten\cache` this leads to the following error:

```
File "/mnt/c/Users/Laguna_HP/webassembly/emsdk/upstream/emscripten/tools/ports/sdl2_image.py", line 18, in get
    assert os.path.exists(sdl_build), 'You must use SDL2 to use SDL2_image'
AssertionError: You must use SDL2 to use SDL2_image
```
Apparently `emsdk\upstream\emscripten\cache\wasm\ports-builds\sdl2` has not been created at the point when SDL2_image is looking for that folder.

This seems like a dependency issue between the SDL2 and the SDL2 library ports. The same happens for sdl2 and sdl mixer 2.

If the second line in the `CMakeLists.txt` file (containing SDL2_image) is commented out a build of the sdl2 port is created. Of course the application build itself fails, because I am using functionality from SDL_image. 
After that I can uncomment the second line and SDL_image correctly detects the sdl2 build.

**Comment by sbc100** [comment]
Can you give the full failing command line?    (If you use `ninja` then it should be reported automatically, if you use `make` you may need to add `VERBOSE=1` to see the failing command line)

**Comment by Laguna1989** [comment]
Thank you for the reply. Please find the verbose log attached here: 

```
make: make VERBOSE=1
/usr/bin/cmake -S/mnt/c/projects/JamTemplateCpp -B/mnt/c/projects/JamTemplateCpp/build_web --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /mnt/c/projects/JamTemplateCpp/build_web/CMakeFiles /mnt/c/projects/JamTemplateCpp/build_web/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/mnt/c/projects/JamTemplateCpp/build_web'
make -f CMakeFiles/Box2D.dir/build.make CMakeFiles/Box2D.dir/depend
make[2]: Entering directory '/mnt/c/projects/JamTemplateCpp/build_web'
cd /mnt/c/projects/JamTemplateCpp/build_web && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /mnt/c/projects/JamTemplateCpp /mnt/c/projects/JamTemplateCpp /mnt/c/projects/JamTemplateCpp/build_web /mnt/c/projects/JamTemplateCpp/build_web /mnt/c/projects/JamTemplateCpp/build_web/CMakeFiles/Box2D.dir/DependInfo.cmake --color=
Dependee "/mnt/c/projects/JamTemplateCpp/build_web/CMakeFiles/Box2D.dir/DependInfo.cmake" is newer than depender "/mnt/c/projects/JamTemplateCpp/build_web/CMakeFiles/Box2D.dir/depend.internal".
Dependee "/mnt/c/projects/JamTemplateCpp/build_web/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/mnt/c/projects/JamTemplateCpp/build_web/CMakeFiles/Box2D.dir/depend.internal".
Scanning dependencies of target Box2D
make[2]: Leaving directory '/mnt/c/projects/JamTemplateCpp/build_web'
make -f CMakeFiles/Box2D.dir/build.make CMakeFiles/Box2D.dir/build
make[2]: Entering directory '/mnt/c/projects/JamTemplateCpp/build_web'
make[2]: Warning: File 'CMakeFiles/Box2D.dir/depend.make' has modification time 0.43 s in the future
[  1%] Building CXX object CMakeFiles/Box2D.dir/ext/box2d/Box2D/Collision/Shapes/b2ChainShape.cpp.o
/mnt/c/Users/Laguna_HP/webassembly/emsdk/upstream/emscripten/em++  -DDISABLE_CPP17_FILESYSTEM -DENABLE_WEB -DMUSIC_OGG @CMakeFiles/Box2D.dir/includes_CXX.rsp -Wall -Wextra -O2 --std=c++17 -fpermissive  --use-preload-plugins --preload-file assets -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='["bmp","png"]' -s USE_SDL_MIXER=2 -s USE_VORBIS=1 -s USE_OGG=1   -std=gnu++17 -o CMakeFiles/Box2D.dir/ext/box2d/Box2D/Collision/Shapes/b2ChainShape.cpp.o -c /mnt/c/projects/JamTemplateCpp/ext/box2d/Box2D/Collision/Shapes/b2ChainShape.cpp
system_libs:INFO: retrieving port: sdl2 from https://github.com/emscripten-ports/SDL2/archive/version_22.zip
system_libs:INFO: unpacking port: sdl2
cache:INFO: generating port: libSDL2.a... (this will be cached in "/mnt/c/Users/Laguna_HP/webassembly/emsdk/upstream/emscripten/cache/wasm/libSDL2.a" for subsequent builds)
cache:INFO:  - ok
system_libs:INFO: retrieving port: ogg from https://github.com/emscripten-ports/ogg/archive/version_1.zip
system_libs:INFO: unpacking port: ogg
cache:INFO: generating system library: libogg.a... (this will be cached in "/mnt/c/Users/Laguna_HP/webassembly/emsdk/upstream/emscripten/cache/wasm/libogg.a" for subsequent builds)
root:INFO: building port: ogg
cache:INFO:  - ok
system_libs:INFO: retrieving port: vorbis from https://github.com/emscripten-ports/vorbis/archive/version_1.zip
system_libs:INFO: unpacking port: vorbis
cache:INFO: generating system library: libvorbis.a... (this will be cached in "/mnt/c/Users/Laguna_HP/webassembly/emsdk/upstream/emscripten/cache/wasm/libvorbis.a" for subsequent builds)
root:INFO: building port: vorbis
cache:INFO:  - ok
root:INFO: ports.get_build_dir() /mnt/c/Users/Laguna_HP/webassembly/emsdk/upstream/emscripten/cache/wasm/ports-builds
root:INFO: check /mnt/c/Users/Laguna_HP/webassembly/emsdk/upstream/emscripten/cache/wasm/ports-builds/sdl2
system_libs:INFO: retrieving port: sdl2_mixer from https://github.com/emscripten-ports/SDL2_mixer/archive/release-2.0.2.zip
system_libs:INFO: unpacking port: sdl2_mixer
cache:INFO: generating port: libSDL2_mixer_ogg.a... (this will be cached in "/mnt/c/Users/Laguna_HP/webassembly/emsdk/upstream/emscripten/cache/wasm/libSDL2_mixer_ogg.a" for subsequent builds)
root:INFO: building port: sdl2_mixer
cache:INFO:  - ok
system_libs:INFO: retrieving port: zlib from https://github.com/emscripten-ports/zlib/archive/version_1.zip
system_libs:INFO: unpacking port: zlib
cache:INFO: generating port: libz.a... (this will be cached in "/mnt/c/Users/Laguna_HP/webassembly/emsdk/upstream/emscripten/cache/wasm/libz.a" for subsequent builds)
cache:INFO:  - ok
system_libs:INFO: retrieving port: libpng from https://github.com/emscripten-ports/libpng/archive/version_1.zip
system_libs:INFO: unpacking port: libpng
cache:INFO: generating port: libpng.a... (this will be cached in "/mnt/c/Users/Laguna_HP/webassembly/emsdk/upstream/emscripten/cache/wasm/libpng.a" for subsequent builds)
root:INFO: building port: libpng
cache:INFO:  - ok
Traceback (most recent call last):
  File "/mnt/c/Users/Laguna_HP/webassembly/emsdk/upstream/emscripten/em++.py", line 14, in <module>
    sys.exit(emcc.run(sys.argv))
  File "/mnt/c/Users/Laguna_HP/webassembly/emsdk/upstream/emscripten/emcc.py", line 1963, in run
    system_libs.add_ports_cflags(cflags, shared.Settings)
  File "/mnt/c/Users/Laguna_HP/webassembly/emsdk/upstream/emscripten/tools/system_libs.py", line 1969, in add_ports_cflags
    port.get(Ports, settings, shared)
  File "/mnt/c/Users/Laguna_HP/webassembly/emsdk/upstream/emscripten/tools/ports/sdl2_image.py", line 18, in get
    assert os.path.exists(sdl_build), 'You must use SDL2 to use SDL2_image'
AssertionError: You must use SDL2 to use SDL2_image
make[2]: *** [CMakeFiles/Box2D.dir/build.make:64: CMakeFiles/Box2D.dir/ext/box2d/Box2D/Collision/Shapes/b2ChainShape.cpp.o] Error 1
make[2]: Leaving directory '/mnt/c/projects/JamTemplateCpp/build_web'
make[1]: *** [CMakeFiles/Makefile2:135: CMakeFiles/Box2D.dir/all] Error 2
make[1]: Leaving directory '/mnt/c/projects/JamTemplateCpp/build_web'
make: *** [Makefile:84: all] Error 2
```
