### ISSUE TITLE
compile wasm binary without javascript imports.env (for deno support)

### ISSUE THREAD

**Issue by andykais** [emscripten-core/emscripten#13190]
Hi, just looking for a general guide on how to compile wasm programs ready for deno. The only issue I found related to deno support is this one: https://github.com/emscripten-core/emscripten/issues/12203 does emscripten not support deno currently?

 I am currently trying my luck at compiling opencv to deno using their wasm compilation guide: https://docs.opencv.org/master/d4/da1/tutorial_js_setup.html. 

I cannot use the resulting js with deno out of the box though.
```
 ✘ andrew  ~/Code/scratchwork/opencv  deno run build_js/bin/opencv.js
error: Uncaught ReferenceError: Module is not defined
    Module = {};
           ^
    at file:///Users/andrew/Code/scratchwork/opencv/build_js/bin/opencv.js:46:12
    at file:///Users/andrew/Code/scratchwork/opencv/build_js/bin/opencv.js:14:15
    at file:///Users/andrew/Code/scratchwork/opencv/build_js/bin/opencv.js:22:2
```

I have attempted running just the extracted wasm binary from the opencv.js emscripten output. I can run that with the following deno code:
```ts
import Context from 'https://deno.land/std@0.83.0/wasi/snapshot_preview1.ts'

const context = new Context({
    args: Deno.args,
    env: Deno.env.toObject()
})
const wasmCode = await Deno.readFile('./opencv.wasm')
const module = await WebAssembly.compile(wasmCode)
const memory = new WebAssembly.Memory({ initial: 256, maximum: 256 })

const instance = await WebAssembly.instantiate(module, {
    wasi_snapshot_preview1: context.exports
})
```
this still expects some emscripten javascsript code:
```
$ deno run --allow-read --v8-flags="--experimental-wasm-threads" --allow-env deno-wasm.ts
Check file:///Users/andrew/Code/scratchwork/opencv/deno-wasm.ts
error: Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #0 module="env" error: module is not an object or function
const instance = await WebAssembly.instantiate(module, {
                                   ^
    at deno-wasm.ts:11:36
```
I have seen a few issues specifying how to pass an env to Webassembly.instantiate that look like the following:
```ts
const instance = await WebAssembly.instantiate(module, {
    env: {
      abortStackOverflow: () => { throw new Error('overflow'); },
      table: new WebAssembly.Table({ initial: 0, maximum: 0, element: 'anyfunc' }),
      __table_base: 0,
      memory: memory,
      __memory_base: 1024,
      STACKTOP: 0,
      STACK_MAX: memory.buffer.byteLength,
    },
    wasi_snapshot_preview1: context.exports
})
```
however wasm appears to be expecting some emscripten specific functions
```
error: Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #0 module="env" function="_emval_new_array" error: function import requires a callable
```
Is there a way to either shove those allocation functions into the wasm binary, or import those functions independent of the compiled emscripten js output? I have tried the following flags: `-s STANDALONE`, `-s WASM=1`, `-s SINGLE_FILE=1`, `--no-entry` but none of them avoid the wasm binary relying on those functions.

**Comment by sbc100** [comment]
In general emscripten does not support deno, at least not directly.   Using `STANDALONE_WASM` will enable you to build some modules that will likely work since deno supports WASI.   But almost all complex programs will most likely end up using emscripten features that require emscripten JS support code.  

Case in point, _emval_new_array is coming from embind, which is a library for binding C++ to JS.  It requires that JS library support code from emscripten so won't be usable in deno without a fair amount of work.  

Do you know where the embind code is used in your application?  Perhaps you can remove it?

**Comment by andykais** [comment]
the program is opencv so I dont have much control over what embind functions it requires. I think if there were an option to export a js file from emscripten that was an es5 module, that would work with deno out of the box. That is assuming that there are no Browser specific or nodejs specific features in the exported file. I believe what is currently exported attempts to be both web compliant and nodejs compliant. I think that is where deno is running into trouble

**Comment by sbc100** [comment]
Yes, it sounds like there would be fair amount of work involved in making emscripten output deno compatible.

**Comment by Ciantic** [comment]
Emscripten works with Deno, when using these flags:

```bash
emcc src/ft.cpp \
    // other flags omitted
    -s EXPORT_ES6=1 \
    -s MODULARIZE=1 \
    -s EXPORT_NAME=YourExport \
    -s SINGLE_FILE=1 \
    -o youroutput.js
```

Single file is required because Deno does not support XMLHttpRequest, modularization and ES6 is also good thing to have with Deno.

I have compiled [Freetype with emscripten](https://github.com/Ciantic/freetype-wasm), and it works with Deno.

**Comment by KnorpelSenf** [comment]
Are there any plans to support Deno in the future? I have not contributed to emscripten before, so I have no idea what it'd take.

If yes: could anyone outline what's necessary to achieve Deno support? I can imagine helping out, assuming that we are able to build up some momentum to get this started.

**Comment by sbc100** [comment]
From the last comment is sounds like works already, given the right set of options?

**Comment by KnorpelSenf** [comment]
Yes, I could make it work on sample projects, too. It seems like the output only serves as a module that can be imported, but it does not offer a way to directly run it as a script. This is very simple to fix by adding a small wrapper script, so I don't mind.

I am particularly interested in using an equivalent for NODEFS on Deno so that we get native file system performance from Deno. Does this work, too? I'd be glad about some pointers in the right direction.

**Comment by sbc100** [comment]
That could be cool idea.  If `NODEFS` and/of `NODERAWFS` doesn't work today under deno I agree it could be useful to add.

**Comment by kripken** [comment]
> Are there any plans to support Deno in the future? I have not contributed to emscripten before, so I have no idea what it'd take.

I think the best plan is in https://github.com/emscripten-core/emscripten/issues/12203 that is linked at the very top. That shouldn't be too much work to do, and would make adding Deno and Bun and other support very practical I think.

**Comment by kripken** [comment]
(I'm not aware of anyone working on it - contributions would be welcome!)
