### ISSUE TITLE
syntax error in emscripten.py

### ISSUE THREAD

**Issue by hydrocanine** [emscripten-core/emscripten#13200]
No matter what I try to do, I get the same syntax error from emscripten.py when I when I run emcc, e.g.,

emcc --clear-cache
Traceback (most recent call last):
  File "/home/alans/emsdk/upstream/emscripten/emcc.py", line 40, in <module>
    import emscripten
  File "/home/alans/emsdk/upstream/emscripten/emscripten.py", line 463
    args.append(f'--separate-data-segments={memfile}')

I'm not really a python person, so any suggestions would be appreciated...;^)

**Comment by sbc100** [comment]
You need to have python3 installed.  I think `apt-get install python3` should do it.

**Comment by hydrocanine** [comment]
unfortunately...

python3 is already the newest version (3.5.1-3).

**Comment by sbc100** [comment]
Ah I see.  emscripten requires python 3.6.  You will either need to update your distro to 18.04 or 20.04 (or basically anything newer that 16.04), or you download and install python 3.6 some other way, i.e. from python.org: https://www.python.org/downloads/. 
 Simply having a recent enough version of python3 in your PATH should be enough.

**Comment by sbc100** [comment]
We did consider packaging python3 binaries as part of the emsdk like we do for mac and windows, and we could still do that if there is enough demand, but so far most linux users seem to be able install pyhthon 3.6 without issue.

**Comment by hydrocanine** [comment]
Thanks. I'll give that a shot. Update to 18.04 breaks things I need at the 
moment...;^)

**Comment by hydrocanine** [comment]
Update: installed python 3.6.12 and seems to work. At least creating a 
hello.html gets me a page that says 'Powered by Emscripten' and a spin
wait widget that says 'Downloading' forever...;^) Thanks!

**Comment by sbc100** [comment]
To load WebAssembly you need to load you page via a server, not via `file://`.   See https://emscripten.org/docs/getting_started/FAQ.html#faq-local-webserver

**Comment by hydrocanine** [comment]
That works. The doc says 'python -m http.server' for python 3, but I needed to use 'python3' in the command. Thanks!
