### ISSUE TITLE
Function signature mismatch with Embind + Function Pointers + dynamic libraries + Optimizations (with minimal test case)

### ISSUE THREAD

**Issue by donalffons** [emscripten-core/emscripten#13241]
Test case: https://github.com/donalffons/embind-dynamicLibs-04
Preview Link: https://embind-dynamic-libs-04-git-master.donalffons.vercel.app/javascript

This test case is distilled down from a large project with several thousand of source files. Here's the gist:

- I'm using Embind and dynamic libraries. There is one MAIN_MODULE and one SIDE_MODULE (if I don't use modules, the error goes away)
- The MAIN_MODULE is empty (contains an empty bindings file as input)
- The SIDE_MODULE contains bindings for the class `STEPCAFControl_Reader` and the following code
```cpp
/* NCollection_Vector.h */
class NCollection_Vector
{
  typedef void (*initMemBlocks_t) ();
  initMemBlocks_t  myInitBlocks;

public:
  NCollection_Vector() : myInitBlocks(initMemBlocks) {}
  void expandV();
  static void initMemBlocks() {}
};

/* NCollection_Vector.cxx */
void NCollection_Vector::expandV()
{
  myInitBlocks(); // ERROR: Uncaught (in promise) RuntimeError: function signature mismatch
}
```

```cpp
/* STEPCAFControl_Reader.hxx */
class STEPCAFControl_Reader 
{
public:
  STEPCAFControl_Reader(){}
  void ReadFile();
};

/* STEPCAFControl_Reader.cxx */
void STEPCAFControl_Reader::ReadFile()
{
  std::cout << "1" << std::endl;
  NCollection_Vector testVec;
  std::cout << "2" << std::endl;
  testVec.expandV();
  std::cout << "3" << std::endl;
}
```
- I'm am using a two-staged build system, which first compiles all source files into `.o`-files using `emcc -c`. Those `.o`-files are then used as input files to the `emcc --bind` command of the SIDE_MODULE. If I use the `.cxx` files directly (instead of the `.o`-files, the error goes away). If I put the method definition of the problematic `expandV` method directly into the header files, the error also goes away.
- I'm building the SIDE_MODULE with `-O3` optimizations. If I'm building it [with `-O1` or `O0` optimizations](https://github.com/donalffons/embind-dynamicLibs-04/blob/master/emscripten/build.sh#L22), the error goes away.
- If I remove the bindings for [`NCollection_Vector`](https://github.com/donalffons/embind-dynamicLibs-04/blob/master/emscripten/embind-library.cpp#L8), the error goes away.
- I read the documentation on potential issues with [function pointers](https://emscripten.org/docs/porting/guidelines/function_pointer_issues.html), but if I understand correctly, the pitfalls mentioned there, do not apply to this case.

I would greatly appreciate it if someone could take a look at this issue. Based on my investigations, I see several potential workarounds. However, I do think that this test case *should* work as it is.

**Comment by donalffons** [comment]
Hi @sbc100 and @kripken  (hope you don't mind addressing you directly) - just wanted to make sure that you at least took note of this issue. If you think there is something I could do to this test case to help with finding the root cause of the issue, feel free to let me know :slightly_smiling_face:. Cheers.

**Comment by sbc100** [comment]
I've not had time to look at this yet I'm afraid.     I am curious to know if this is a regression or not though.  Did this used to work in the past?  I'm not sure we do much testing of embind with dynamic linking but I would need to check.

**Comment by sbc100** [comment]
Anything you could to to make the test case as small as possible would always be much appreciated (although as I say I've not looked at the code yet so maybe you already did as much as you could).

**Comment by donalffons** [comment]
> Did this used to work in the past? 

I just made a few tests. It is not working with the following Emscripten versions, producing the same error message as in my original post:

- 2.0.12
- 2.0.0
- 1.40.0
- 1.39.0

1.39.0 seems to be the last version which ships with a Docker image. So, I don't think this ever worked.

**Comment by donalffons** [comment]
> Anything you could to to make the test case as small as possible would always be much appreciated

I just had another look at the code and didn't find any more opportunities to reduce the number of lines of code. Any further simplification I try to make seems to just "fix" the error. Here are some more findings (code snippets are from the `NCollection_Vector.cxx` file):

- Calling the problematic `initMemBlocks` function of class `NCollection_Vector` directly, instead of using the function pointer to that function, resolves the issue:
```cpp
void NCollection_Vector::expandV()
{
  // myInitBlocks(); // ERROR: Uncaught (in promise) RuntimeError: function signature mismatch
  NCollection_Vector::initMemBlocks(); // No Error
}
```

- Defining the function pointer immediately before calling the function (instead of defining it in the constructor) also resolves the issue:
```cpp
void NCollection_Vector::expandV()
{
  // myInitBlocks(); // ERROR: Uncaught (in promise) RuntimeError: function signature mismatch
  void (*functionPointer) () = NCollection_Vector::initMemBlocks;
  functionPointer(); // No Error
}
```

- Defining the constructor (which initializes the problematic `myInitBlocks` function pointer) inside the `.cxx` file instead of the `.h` file also resolves the issue.
```cpp
NCollection_Vector::NCollection_Vector() :
 myInitBlocks(NCollection_Vector::initMemBlocks) {}

void NCollection_Vector::expandV()
{
  myInitBlocks(); // No Error
}
```

- Defining the `initMemBlocks` function inside the `.cxx` file instead of the `.h` file also resolves the issue
```cpp
void NCollection_Vector::initMemBlocks() {}

void NCollection_Vector::expandV()
{
  myInitBlocks(); // No Error
}
```

**Comment by jamiebird-arm** [comment]
> Anything you could to to make the test case as small as possible would always be much appreciated (although as I say I've not looked at the code yet so maybe you already did as much as you could).

@sbc100 this looks like the same issue as #13049 which has a simple reproducer.

**Comment by sbc100** [comment]
#13049 looks realted to ASYNCIFY though.. whereas this looks like its related to EMBIND.    What makes you think they are the same?

**Comment by jamiebird-arm** [comment]
Appologies I got mixed up with another one of @donalffons issues, #13026, where there was a suugestion it was simlar to #13049. I see this issue doesn't include ASYNCIFY.

**Comment by donalffons** [comment]
@sbc100 as mentioned in #14311, due to this issue I am unable to use pre-compiled libraries as an input to `emcc --bind`. I just updated the Dockerfile to Emscripten `2.0.23` and the error message is still (mostly) identical:

```
Uncaught (in promise) RuntimeError: function signature mismatch
    at NCollection_Vector::expandV() (<anonymous>:wasm-function[31]:0x212c)
    at STEPCAFControl_Reader::ReadFile() (<anonymous>:wasm-function[32]:0x217a)
    at emscripten::internal::MethodInvoker<void (STEPCAFControl_Reader::*)(), void, STEPCAFControl_Reader*>::invoke(void (STEPCAFControl_Reader::* const&)(), STEPCAFControl_Reader*) (<anonymous>:wasm-function[28]:0x20fc)
    at STEPCAFControl_Reader$ReadFile [as ReadFile] (eval at new_ (https://embind-dynamic-libs-04-git-master-donalffons.vercel.app/emscripten/build/main.js:30653:27), <anonymous>:8:1)
    at https://embind-dynamic-libs-04-git-master-donalffons.vercel.app/javascript/myWorker.js:12:10
```

**Comment by sbc100** [comment]
That really doesn't make much sense at all... the differences between those scenarios are very minimall.  are you using `--Wl,--whole-archive` around your libraries? (if you do that the differences should be zero).

**Comment by sbc100** [comment]
Apologies for not investigate #14311 more.. (yet).

**Comment by donalffons** [comment]
This is what I get when I pass `--whole-archive`.
![image](https://user-images.githubusercontent.com/33040347/119898455-29810480-bf42-11eb-944e-3e1a654ea99e.png)

**Comment by sbc100** [comment]
You need a comma betwee `-Wl` and the `--whole-achive`.    `-Wl` means "the arguments after the comma are for the linker"

**Comment by sbc100** [comment]
Yes `-Wl,--whole-archive` should go before you librarys and `-Wl,--no-whole-archive` should go after.

For example `-Wl,--whole-archive -lfoo libbar.a -Wl,--no-whole-archive`.    This means that libfoo.a and libbar.a will be includes as if each of the object files within them were specified individually on the command line.

**Comment by donalffons** [comment]
With the following build script, the error message is still identical (I'm passing `.o` files already)
```bash
mkdir -p build

emcc \
  --bind embind-main.cpp \
  -s MAIN_MODULE=1 \
  -s EXPORT_ES6=1 \
  -s USE_ES6_IMPORT_META=0 \
  -g3 \
  -O3 \
  -o ./build/main.js

emcc \
  ./NCollection_Vector.cxx \
  -fPIC \
  -c -o ./build/NCollection_Vector.o

emcc \
  ./STEPCAFControl_Reader.cxx \
  -fPIC \
  -c -o ./build/STEPCAFControl_Reader.o

# HINT: If this is set to O1, the error goes away 
emcc \
  --bind embind-library.cpp \
  -Wl,--whole-archive ./build/NCollection_Vector.o -Wl,--no-whole-archive \ # CHANGED
  -Wl,--whole-archive ./build/STEPCAFControl_Reader.o -Wl,--no-whole-archive \ # CHANGED
  -s SIDE_MODULE=1 \
  -g3 \
  -O3 \
  -o ./build/library.wasm
```

However, I also just realized that this is not 100% applicable to building the "full" version of opencascade.js (as discussed in #14311), since that full version doesn't need MAIN_MODULEs and SIDE_MODULEs.

I will set up a proper build in a separate branch in the opencascade.js project and open a new issue in case I have problems.

> Apologies for not investigate this issue more

I realize that you're all very busy. I appreciate your help with this!

**Comment by sbc100** [comment]
You don't need the whole archive stuff if you pass `.o` files directly.  It only effects `.a` files.

What do you do differently in the non-failing case?   Is it just passing the .cxx files directly the `MAIN_MODULE` and `SIDE_MODULE` commands?

**Comment by sbc100** [comment]
Also, you can compile `embind-library.cpp` and `embind-main.cpp` separately too.

The `--bind` argument is link-time-only thing so should not effect compilation and you don't need `--bind` when compiling embind code.

**Comment by donalffons** [comment]
> What do you do differently in the non-failing case? Is it just passing the .cxx files directly the MAIN_MODULE and SIDE_MODULE commands?

There are a couple of ways to "resolve" this (i.e. there will be no error during execution).

1. Removing Optimizations from the SIDE_MODULE build (keeping everything else as it is)

`./emscripten/build.sh`
```diff
 mkdir -p build

 emcc \
   --bind embind-main.cpp \
   -s MAIN_MODULE=1 \
   -s EXPORT_ES6=1 \
   -s USE_ES6_IMPORT_META=0 \
   -g3 \
   -O3 \
   -o ./build/main.js

-# HINT: If this is set to O1, the error goes away
+# HINT: If this is set to O0, the error goes away 
 emcc \
   ./NCollection_Vector.cxx \
   -fPIC \
   -c -o ./build/NCollection_Vector.o

 emcc \
   ./STEPCAFControl_Reader.cxx \
   -fPIC \
   -c -o ./build/STEPCAFControl_Reader.o

 emcc \
   --bind embind-library.cpp \
   ./build/NCollection_Vector.o \
   ./build/STEPCAFControl_Reader.o \
   -s SIDE_MODULE=1 \
   -g3 \
+  -O0 \
-  -O3 \
   -o ./build/library.wasm
```

2. Removing the (unused) bindings for NCollection_Vector (also keeping everything else)

`./emscripten/embind-library.cpp`
```diff
 #include "NCollection_Vector.hxx"
 #include "STEPCAFControl_Reader.hxx"

 #include <emscripten/bind.h>
 using namespace emscripten;

 EMSCRIPTEN_BINDINGS(library) {
-  class_<NCollection_Vector>("NCollection_Vector") // HINT: If this is removed, the error goes away
-    .constructor<>()
-  ;
   class_<STEPCAFControl_Reader>("STEPCAFControl_Reader")
     .constructor<>()
     .function("ReadFile", &STEPCAFControl_Reader::ReadFile)
   ;
 }
```

3. Passing the `.cxx` source files instead of the pre-build `.o` files to `emcc --bind`

`./emscripten/build.sh`
```diff
 mkdir -p build

 emcc \
   --bind embind-main.cpp \
   -s MAIN_MODULE=1 \
   -s EXPORT_ES6=1 \
   -s USE_ES6_IMPORT_META=0 \
   -g3 \
   -O3 \
   -o ./build/main.js

-emcc \
-  ./NCollection_Vector.cxx \
-  -fPIC \
-  -c -o ./build/NCollection_Vector.o

-emcc \
-  ./STEPCAFControl_Reader.cxx \
-  -fPIC \
-  -c -o ./build/STEPCAFControl_Reader.o

# HINT: If this is set to O0, the error goes away 
 emcc \
   --bind embind-library.cpp \
-  ./build/NCollection_Vector.o \
+  ./NCollection_Vector.cxx \
-  ./build/STEPCAFControl_Reader.o \
+  ./STEPCAFControl_Reader.cxx \
   -s SIDE_MODULE=1 \
   -g3 \
   -O3 \
   -o ./build/library.wasm
```

> Also, you can compile embind-library.cpp and embind-main.cpp separately too.

Interesting! That also resolves the issue:

`./emscripten/build.sh`
```bash
mkdir -p build

emcc \
  ./NCollection_Vector.cxx \
  -fPIC \
  -c -o ./build/NCollection_Vector.o

emcc \
  ./STEPCAFControl_Reader.cxx \
  -fPIC \
  -c -o ./build/STEPCAFControl_Reader.o

emcc \
  ./embind-library.cpp \
  -fPIC \
  -c -o ./build/embind-library.o

emcc \
  ./embind-main.cpp \
  -fPIC \
  -c -o ./build/embind-main.o

emcc \
  --bind ./build/embind-main.o \
  -s MAIN_MODULE=1 \
  -s EXPORT_ES6=1 \
  -s USE_ES6_IMPORT_META=0 \
  -g3 \
  -O3 \
  -o ./build/main.js

# HINT: If this is set to O0, the error goes away 
emcc \
  --bind ./build/embind-library.o \
  ./build/NCollection_Vector.o \
  ./build/STEPCAFControl_Reader.o \
  -s SIDE_MODULE=1 \
  -g3 \
  -O3 \
  -o ./build/library.wasm
```
