### ISSUE TITLE
UBSan blows stack on == of type_infos.

### ISSUE THREAD

**Issue by tlively** [emscripten-core/emscripten#13330]
I intend to continue investigating this after doing some other work, but I thought I would document a minimal reproducer for the issue. We have had a few reports of users running into this bug because it is triggered by googletest.

```
// main.cpp
#include <typeinfo>
int main(int, char**) {
    return typeid(int) == typeid(int);
}
```
```
em++ -O2 -g -fsanitize=undefined main.cpp -o main.js && node main.js
```
```
exception thrown: RangeError: Maximum call stack size exceeded,RangeError: Maximum call stack size exceeded
    at Object.value (internal/console/constructor.js:273:13)
    at Object.log (internal/console/constructor.js:341:26)
    at dump (/usr/local/google/home/tlively/code/emscripten/ubsan-loop/main.js:1609:29)
    at __ubsan::checkDynamicType(void*, void*, unsigned long) (<anonymous>:wasm-function[111]:0x738d)
    at HandleDynamicTypeCacheMiss(__ubsan::DynamicTypeCacheMissData*, unsigned long, unsigned long, __ubsan::ReportOptions) (<anonymous>:wasm-function[110]:0x6c6a)
    at __ubsan_handle_dynamic_type_cache_miss (<anonymous>:wasm-function[109]:0x6c35)
    at std::type_info::operator==(std::type_info const&) const (<anonymous>:wasm-function[27]:0x71f)
    at is_equal(std::type_info const*, std::type_info const*, bool) (<anonymous>:wasm-function[38]:0x7d6)
    at __dynamic_cast (<anonymous>:wasm-function[41]:0x906)
    at __ubsan::checkDynamicType(void*, void*, unsigned long) (<anonymous>:wasm-function[111]:0x74fd)
```

**Comment by tlively** [comment]
Building libc++abi with -O3 instead of -Oz "fixes" this bug by somehow optimizing `__dynamic_cast` so that it no longer recurses into `type_info::operator==`. I still have to figure out why exactly that is.
