### ISSUE TITLE
Custom EM_CACHE error

### ISSUE THREAD

**Issue by thomasballinger** [emscripten-core/emscripten#13339]
With latest emsdk on a mac, running `rm -rf emcache/; EM_CACHE=emcache emcc -o hello.html main.cpp` fails the first time, then is fine the second time it runs (unless the cache is again rm'd).

contents of main.cpp:
```
#include <iostream>
using namespace std;
int main(int argc, char *argv[])
{
	cout << "Running program." << endl;
}
```

```
tomb (min-repro) minimal-repro$ rm -rf emcache/; EM_CACHE=emcache emcc -o hello.html main.cpp
shared:INFO: (Emscripten: Running sanity checks)
cache:INFO: generating system library: wasm/libc.a... (this will be cached in "/Users/tomb/minimal-repro/emcache/wasm/libc.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: wasm/libcompiler_rt.a... (this will be cached in "/Users/tomb/minimal-repro/emcache/wasm/libcompiler_rt.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: wasm/libc++-noexcept.a... (this will be cached in "/Users/tomb/minimal-repro/emcache/wasm/libc++-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: wasm/libc++abi-noexcept.a... (this will be cached in "/Users/tomb/minimal-repro/emcache/wasm/libc++abi-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: wasm/libdlmalloc.a... (this will be cached in "/Users/tomb/minimal-repro/emcache/wasm/libdlmalloc.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: wasm/libc_rt_wasm.a... (this will be cached in "/Users/tomb/minimal-repro/emcache/wasm/libc_rt_wasm.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: wasm/libsockets.a... (this will be cached in "/Users/tomb/minimal-repro/emcache/wasm/libsockets.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "/Users/tomb/minimal-repro/emcache/generated_struct_info.json" for subsequent builds)
Traceback (most recent call last):
  File "/Users/tomb/emsdk/upstream/emscripten/emcc.py", line 3315, in <module>
    sys.exit(main(sys.argv))
  File "/Users/tomb/emsdk/upstream/emscripten/emcc.py", line 3308, in main
    ret = run(args)
  File "/Users/tomb/emsdk/upstream/emscripten/emcc.py", line 2156, in run
    post_link(options, wasm_target, wasm_target, target)
  File "/Users/tomb/emsdk/upstream/emscripten/emcc.py", line 2185, in post_link
    emscripten.run(in_wasm, wasm_target, final_js, memfile)
  File "/Users/tomb/emsdk/upstream/emscripten/emscripten.py", line 874, in run
    generate_struct_info()
  File "/Users/tomb/emsdk/upstream/emscripten/emscripten.py", line 868, in generate_struct_info
    shared.Settings.STRUCT_INFO = shared.Cache.get(generated_struct_info_name, generate_struct_info)
  File "/Users/tomb/emsdk/upstream/emscripten/tools/cache.py", line 145, in get
    shutil.copyfile(temp, cachename)
  File "/Users/tomb/emsdk/python/3.7.4-2_64bit/lib/python3.7/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: 'emcache/generated_struct_info.json' and '/Users/tomb/minimal-repro/emcache/generated_struct_info.json' are the same file
```

**Comment by thomasballinger** [comment]
Closing because can no longer reproduce
