### ISSUE TITLE
Cannot find module 'acorn' compilation error

### ISSUE THREAD

**Issue by cggallant** [emscripten-core/emscripten#13368]
I'm trying to compile the `calculate_primes.cpp` file found here but, as of Emscripten 2.0.12, I'm getting a compilation error: https://github.com/cggallant/WebAssembly-in-Action/tree/master/updated-code/Chapter%209/9.4%20pthreads/source

The command line I'm using is: `emcc calculate_primes.cpp -O1 -std=c++11 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=4 -o pthreads.html`

The compilation error is:
```
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'acorn'
Require stack:
- D:\emsdk-master\emsdk-master\upstream\emscripten\tools\acorn-optimizer.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:842:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1026:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (D:\emsdk-master\emsdk-master\upstream\emscripten\tools\acorn-optimizer.js:1:13)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1138:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:986:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'D:\\emsdk-master\\emsdk-master\\upstream\\emscripten\\tools\\acorn-optimizer.js'←[39m
  ]
}
emcc: error: 'D:/emsdk-master/emsdk-master/node/12.18.1_64bit/bin/node.exe D:\emsdk-master\emsdk-master\upstream\emscripten\tools\acorn-optimizer.js "D:\Gs Stuff\Blog Posts\WebAssembly-in-Action\updated-code\Chapter 9\9.4 pthreads\source\pthreads.worker.js" minifyWhitespace' failed (1)
```

Any help would be greatly appreciated.

**Comment by kripken** [comment]
Does `npm install` help?

**Comment by cggallant** [comment]
Very interesting! I navigated to my Emscripten folder (`D:\emsdk-master\emsdk-master\upstream\emscripten`) and ran `npm install` as you suggested.

*That fixed it!*

Should the npm install step be part of the `emsdk install`?

**Comment by kripken** [comment]
It should be automatic, yes, @sbc100 set that up. Maybe it requires `emsdk install` and also `emsdk activate`?
