### ISSUE TITLE
Assertion failed: the Module object should not be replaced during async compilation - perhaps the order of HTML elements is wrong?

### ISSUE THREAD

**Issue by dhirajnitk** [emscripten-core/emscripten#13392]
I am getting this bug on first load of html. I recently moved .data files to indexdb caching with option `--use-preload-cache`

Reloading is fine but my wasm is crashing on first load everytime(opening the tab)  for chrome and edge. In edge, the error appears during reloads as well

Enabled full stack trace with 
`-s DEMANGLE_SUPPORT=1`

```
Uncaught (in promise) RuntimeError: abort(Assertion failed: the Module object should not be replaced during async compilation - perhaps the order of HTML elements is wrong?) at Error
    at jsStackTrace (http://localhost:8000/xxx/xxxx.js:1:39377)
    at stackTrace (http://localhost:8000/xxx/xxxx.js:1:39545)
    at abort (http://localhost:8000/xxx/xxxx.js:1:35762)
    at assert (http://localhost:8000/xxx/xxxx.js:1:22557)
    at receiveInstantiatedSource (http://localhost:8000/xxx/xxxx.js:1:37259)
    at abort (http://localhost:8000/xxx/xxxx.js:1:35793)
    at assert (http://localhost:8000/xxx/xxxx.js:1:22557)
    at receiveInstantiatedSource (http://localhost:8000/xxx/xxx.js:1:37259)
```
Firefox works fine but every reload is causing the memory to explode.[The c++ code doesnt have any memory leaks]

**Comment by dhirajnitk** [comment]
Different ordering of js files fixed this bug
