### ISSUE TITLE
Memory corruption when compiling dylink + pthreads + exceptions

### ISSUE THREAD

**Issue by jprendes** [emscripten-core/emscripten#13398]
The following example seems to constantly result in a memory corruption.
This happens regardless of whether I am actually spinning a new thread or not (as in the example).

main.cpp
```c++
#include <stdio.h>
int get_value(char c); // from side module
int main(void) {
    printf("%d\n", get_value('x'));
    return 0;
}
```

side.cpp
```c++
#include <string>
int get_value(char x) {
    std::string value = "123";
    value.push_back(x);
    return value.length();
}
```

I am compiling with
```
em++ -s ASSERTIONS=1 -g -pthread -Wno-experimental -s DISABLE_EXCEPTION_CATCHING=0 -s SIDE_MODULE=1 -o side.wasm side.cpp
em++ -s ASSERTIONS=1 -g -pthread -Wno-experimental -s DISABLE_EXCEPTION_CATCHING=0 -s MAIN_MODULE=1 -s EXIT_RUNTIME=1 -s RUNTIME_LINKED_LIBS=['side.wasm'] -o main.html main.cpp
```

The example correctly prints `4`, but then it is followed by
```
Uncaught RuntimeError: abort(Runtime error: The application has corrupted its heap memory area (address zero)!) at Error
    at jsStackTrace (http://127.0.0.1:8080/main.js:2201:19)
    at stackTrace (http://127.0.0.1:8080/main.js:2751:16)
    at abort (http://127.0.0.1:8080/main.js:1567:44)
    at checkStackCookie (http://127.0.0.1:8080/main.js:1339:46)
    at exitRuntime (http://127.0.0.1:8080/main.js:1405:3)
    at exit (http://127.0.0.1:8080/main.js:54481:5)
    at callMain (http://127.0.0.1:8080/main.js:54338:7)
    ...
```

**Comment by jprendes** [comment]
It looks like the compiler is generating code that required thread local storage, but doesn't actually allocate any when the thread starts.

This seems to happen when a `noexcept` function calls a function that "could" throw. This seems to be the case with musl's `allocator`s, used by `std::string` in my previous example.

Here's an example:

main.cpp
```c++
#include <stdio.h>
int get_value();
int main(void) {
    printf("%d\n", get_value());
    return 0;
}
```

side.cpp
```c++
#include <stdlib.h>
int some_function() noexcept {
    return atoi("42");
}
int get_value() {
    return some_function();
}
```

And here's another example that doesn't require any library:

main.cpp
```c++
int random() {
    return 42;
}
int get_value();
int main(void) {
    return get_value();
}
```

side.cpp
```c++
int random();
int some_function() noexcept {
    return random();
}
int get_value() {
    return some_function();
}
```

In both cases removing the `noexcept` everything works as expected.
Both examples are compiled with the same commands from the previous post.

**Comment by jprendes** [comment]
Ok, it turns out that exceptions + pthread shares TLS data addresses with JS, which is mentioned as a missing feature in @sbc100 's initial commit for dylink + pthread.

Adding TLS support and making sure that side modules are linked against emscripten's exceptions builtin code should fix this issue.
