### ISSUE TITLE
Latest emsdk fails with Python 3.7.8 on Windows 10

### ISSUE THREAD

**Issue by pjmlp** [emscripten-core/emscripten#13433]
Python isn't my daily driver and I am stuck trying to make `emscripten_npm_install()` be happy on Windows 10, while fighting for encoding problems.

```
PS D:\WebAssembly\emsdk> .\emsdk install latest
Installing SDK 'sdk-releases-upstream-ce0e4a4d1cab395ee5082a60ebb4f3891a94b256-64bit'..
Skipped installing node-12.18.1-64bit, already installed.
Skipped installing python-3.7.4-pywin32-64bit, already installed.
Skipped installing java-8.152-64bit, already installed.
Skipped installing releases-upstream-ce0e4a4d1cab395ee5082a60ebb4f3891a94b256-64bit, already installed.
Running post-install step: npm ci ...
Running post-install step: npm install google-closure-compiler-windows
Traceback (most recent call last):
  File "D:\WebAssembly\emsdk/emsdk.py", line 3082, in <module>
    sys.exit(main())
  File "D:\WebAssembly\emsdk/emsdk.py", line 3062, in main
    success = tool.install()
  File "D:\WebAssembly\emsdk/emsdk.py", line 1840, in install
    return self.install_sdk()
  File "D:\WebAssembly\emsdk/emsdk.py", line 1857, in install_sdk
    success = emscripten_npm_install(self, os.path.join(emsdk_path(), install_path, 'emscripten'))
  File "D:\WebAssembly\emsdk/emsdk.py", line 1286, in emscripten_npm_install
    universal_newlines=True)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 395, in check_output
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 474, in run
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 926, in communicate
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 625: character maps to <undefined>
```

**Comment by pjmlp** [comment]
I managed to fix my problem by adding `encoding='latin1'` to the `subprocess.check_output()` call.

If this is an acceptable solution for upstream, I can do a pull request.

**Comment by sbc100** [comment]
Is this related to the python version?    Can you verify which version of python is being run by emsdk.bat?    Does the problem also occur if you use the version of python that emsdk installs?

Do you have any idea what might cause this issue on windows?   The subprocess in question is node and I imagine that both python and node should have the same locale set.. but I don't know enough about how windows handles this stuff I'm afraid.

**Comment by pjmlp** [comment]
It uses the version I installed as part of the Visual Studio 2019 setup.

Not sure about the root cause, it might be related to my Windows being localized in German, and default Python encoding is not able to deal with German characters, äÄöÖüÜß°áàéè.

**Comment by mkdotcom** [comment]
I had a smilar issue with emcc.exe, calling this solved it:

` set PYTHONUTF8=1`
