### ISSUE TITLE
error: logv('Searching for processes by full path name "' + exe_full_path + '".. found ' + str(len(pids)) + ' entries')

### ISSUE THREAD

**Issue by seveirbian** [emscripten-core/emscripten#13544]
When run "emrun --no_browser --port 8080 ." and use browser to open "localhost:8080" to test webassembly code which is built from a hello world C code, this error occurs: 
```
root@bc86023e22b8:~/hello# emrun --no_browser --port 8080 .
Web server root directory: /root/hello
Now listening at http://0.0.0.0:8080/
----------------------------------------
Exception happened during processing of request from ('172.17.0.1', 61768)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/lib/python3.8/http/server.py", line 651, in do_GET
    f = self.send_head()
  File "/root/emsdk/upstream/emscripten/emrun.py", line 591, in send_head
    detect_browser_processes()
  File "/root/emsdk/upstream/emscripten/emrun.py", line 429, in detect_browser_processes
    running_browser_processes = list_processes_by_name(browser_exe)
  File "/root/emsdk/upstream/emscripten/emrun.py", line 1420, in list_processes_by_name
    logv('Searching for processes by full path name "' + exe_full_path + '".. found ' + str(len(pids)) + ' entries')
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by seveirbian** [comment]
After modifying this line of code ``` logv('Searching for processes by full path name "' + exe_full_path + '".. found ' + str(len(pids)) + ' entries')``` to ``` logv('Searching for processes by full path name "' + str(exe_full_path) + '".. found ' + str(len(pids)) + ' entries')```, my hello world webassembly code runs correctly.
