### ISSUE TITLE
Abort output is not great

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#13647]
When application aborts (whether via explicit `abort`, or via `assert`, or via C++ system error), our output is not great.

E.g. take this example:

```c
#include <stdlib.h>

int main() {
    abort();
    return 0;
}
```

When compiled and executed, the output looks like this:

```
$ node temp
undefined
exception thrown: RuntimeError: abort(undefined) at Error
    at jsStackTrace (/usr/local/google/home/rreverser/emscripten/temp.js:1751:19)
    at stackTrace (/usr/local/google/home/rreverser/emscripten/temp.js:1768:16)
    at abort (/usr/local/google/home/rreverser/emscripten/temp.js:1464:44)
    at _abort (/usr/local/google/home/rreverser/emscripten/temp.js:1774:7)
    at wasm-function[2]:0x197
    at wasm-function[3]:0x19f
    at /usr/local/google/home/rreverser/emscripten/temp.js:1541:22
    at callMain (/usr/local/google/home/rreverser/emscripten/temp.js:2106:15)
    at doRun (/usr/local/google/home/rreverser/emscripten/temp.js:2177:23)
    at run (/usr/local/google/home/rreverser/emscripten/temp.js:2192:5),RuntimeError: abort(undefined) at Error
    at jsStackTrace (/usr/local/google/home/rreverser/emscripten/temp.js:1751:19)
    at stackTrace (/usr/local/google/home/rreverser/emscripten/temp.js:1768:16)
    at abort (/usr/local/google/home/rreverser/emscripten/temp.js:1464:44)
    at _abort (/usr/local/google/home/rreverser/emscripten/temp.js:1774:7)
    at wasm-function[2]:0x197
    at wasm-function[3]:0x19f
    at /usr/local/google/home/rreverser/emscripten/temp.js:1541:22
    at callMain (/usr/local/google/home/rreverser/emscripten/temp.js:2106:15)
    at doRun (/usr/local/google/home/rreverser/emscripten/temp.js:2177:23)
    at run (/usr/local/google/home/rreverser/emscripten/temp.js:2192:5)
    at abort (/usr/local/google/home/rreverser/emscripten/temp.js:1470:11)
    at _abort (/usr/local/google/home/rreverser/emscripten/temp.js:1774:7)
    at wasm-function[2]:0x197
    at wasm-function[3]:0x19f
    at /usr/local/google/home/rreverser/emscripten/temp.js:1541:22
    at callMain (/usr/local/google/home/rreverser/emscripten/temp.js:2106:15)
    at doRun (/usr/local/google/home/rreverser/emscripten/temp.js:2177:23)
    at run (/usr/local/google/home/rreverser/emscripten/temp.js:2192:5)
    at runCaller (/usr/local/google/home/rreverser/emscripten/temp.js:2084:19)
    at removeRunDependency (/usr/local/google/home/rreverser/emscripten/temp.js:1444:7)
```

There are two issues here:

1. We print `undefined` and then `abort(undefined)` which is more of a noise than a helpful message, and could be removed instead.
2. The stacktrace is printed twice, with second part not even separated from the first one so it appears to be one huge stacktrace.

This is one of those papercuts that were around for a while, but always felt bad, so I figured I'd raise an issue as I'm sure we can improve UX for those errors.

**Comment by RReverser** [comment]
Probably cc @sbc100 since you looked into `abort` handling very recently.

**Comment by sbc100** [comment]
Yeah.. I hate this..  I've been trying land a fix for that for while now.   I need to resurrect it.

**Comment by RReverser** [comment]
Ran into this / remembered about it again while trying out Wasm EH.

Simple program:

```cpp
#include <stdexcept>

int main() {
  throw std::runtime_error("hello");
}
```

DevTools output:

![image](https://user-images.githubusercontent.com/557590/133098017-a52346b2-893c-4f7c-a49c-f50aa1fd8b55.png)

This is unhelpfully verbose...
