### ISSUE TITLE
CMake error when updating emscripten 2.0.1 to 2.0.15

### ISSUE THREAD

**Issue by PowerNow** [emscripten-core/emscripten#13648]
Hi,
I just update my project on Win10 from Emscripten 2.0.1 to 2.0.15 and get during compilation the following error:

```
shared:INFO: (Emscripten: Running sanity checks)
cache:INFO: generating system headers: sysroot_install.stamp... (this will be cached in "E:\PROGRAMS\emsdk-master\upstream\emscripten\cache\sysroot_install.stamp" for subsequent builds)
cache:INFO:  - ok
system_libs:INFO: retrieving port: freetype from https://github.com/emscripten-ports/FreeType/archive/version_1.zip
system_libs:INFO: unpacking port: freetype
cache:INFO: generating port: sysroot\lib\wasm32-emscripten\libfreetype.a... (this will be cached in "E:\PROGRAMS\emsdk-master\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\libfreetype.a" for subsequent builds)
cache:INFO:  - ok
system_libs:INFO: retrieving port: sdl2 from https://github.com/emscripten-ports/SDL2/archive/version_22.zip
system_libs:INFO: unpacking port: sdl2
cache:INFO: generating port: sysroot\lib\wasm32-emscripten\libSDL2.a... (this will be cached in "E:\PROGRAMS\emsdk-master\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\libSDL2.a" for subsequent builds)
cache:INFO:  - ok
system_libs:INFO: retrieving port: harfbuzz from https://github.com/harfbuzz/harfbuzz/releases/download/1.7.5/harfbuzz-1.7.5.tar.bz2
system_libs:INFO: unpacking port: harfbuzz
cache:INFO: generating port: sysroot\lib\wasm32-emscripten\libharfbuzz.a... (this will be cached in "E:\PROGRAMS\emsdk-master\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\libharfbuzz.a" for subsequent builds)
root:INFO: building port: harfbuzz
configure: cmake -G "Unix Makefiles" -BE:\PROGRAMS\emsdk-master\upstream\emscripten\cache\ports-builds\harfbuzz -HE:/PROGRAMS/emsdk-master/upstream/emscripten\cache\ports\harfbuzz\harfbuzz-1.7.5 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=E:\PROGRAMS\emsdk-master\upstream\emscripten\cache\ports-builds\harfbuzz -DFREETYPE_INCLUDE_DIRS=E:\PROGRAMS\emsdk-master\upstream\emscripten\cache\sysroot\include\freetype2\freetype;E:\PROGRAMS\emsdk-master\upstream\emscripten\cache\sysroot\include\freetype2\freetype\config -DFREETYPE_LIBRARY=E:\PROGRAMS\emsdk-master\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\libfreetype.a -DHB_HAVE_FREETYPE=ON -DCMAKE_TOOLCHAIN_FILE=E:\PROGRAMS\emsdk-master\upstream\emscripten\cmake\Modules\Platform\Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR="E:/PROGRAMS/emsdk-master/node/14.15.5_64bit/bin/node.exe"
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "E:/PROGRAMS/emsdk-master/upstream/emscripten/cache/ports-builds/harfbuzz/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "E:\PROGRAMS\emsdk-master\upstream\emscripten\\emcc.py", line 3304, in <module>
    sys.exit(main(sys.argv))
  File "E:\PROGRAMS\emsdk-master\upstream\emscripten\\emcc.py", line 3297, in main
    ret = run(args)
  File "E:\PROGRAMS\emsdk-master\upstream\emscripten\\emcc.py", line 1949, in run
    system_libs.add_ports_cflags(cflags, shared.Settings)
  File "E:\PROGRAMS\emsdk-master\upstream\emscripten\tools\system_libs.py", line 1848, in add_ports_cflags
    port.get(Ports, settings, shared)
  File "E:\PROGRAMS\emsdk-master\upstream\emscripten\tools\ports\harfbuzz.py", line 71, in get
    return [shared.Cache.get_lib(get_lib_name(settings), create, what='port')]
  File "E:\PROGRAMS\emsdk-master\upstream\emscripten\tools\cache.py", line 130, in get_lib
    return self.get(name, *args, **kwargs)
  File "E:\PROGRAMS\emsdk-master\upstream\emscripten\tools\cache.py", line 158, in get
    creator(cachename)
  File "E:\PROGRAMS\emsdk-master\upstream\emscripten\tools\ports\harfbuzz.py", line 64, in create
    building.configure(configure_args)
  File "E:\PROGRAMS\emsdk-master\upstream\emscripten\tools\building.py", line 327, in configure
    run_process(args, stdout=stdout, stderr=stderr, env=env, **kwargs)
  File "E:\PROGRAMS\emsdk-master\upstream\emscripten\tools\shared.py", line 95, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['cmake', '-G', 'Unix Makefiles', '-BE:\\PROGRAMS\\emsdk-master\\upstream\\emscripten\\cache\\ports-builds\\harfbuzz', '-HE:/PROGRAMS/emsdk-master/upstream/emscripten\\cache\\ports\\harfbuzz\\harfbuzz-1.7.5', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=E:\\PROGRAMS\\emsdk-master\\upstream\\emscripten\\cache\\ports-builds\\harfbuzz', '-DFREETYPE_INCLUDE_DIRS=E:\\PROGRAMS\\emsdk-master\\upstream\\emscripten\\cache\\sysroot\\include\\freetype2\\freetype;E:\\PROGRAMS\\emsdk-master\\upstream\\emscripten\\cache\\sysroot\\include\\freetype2\\freetype\\config', '-DFREETYPE_LIBRARY=E:\\PROGRAMS\\emsdk-master\\upstream\\emscripten\\cache\\sysroot\\lib\\wasm32-emscripten\\libfreetype.a', '-DHB_HAVE_FREETYPE=ON', '-DCMAKE_TOOLCHAIN_FILE=E:\\PROGRAMS\\emsdk-master\\upstream\\emscripten\\cmake\\Modules\\Platform\\Emscripten.cmake', '-DCMAKE_CROSSCOMPILING_EMULATOR="E:/PROGRAMS/emsdk-master/node/14.15.5_64bit/bin/node.exe"']' returned non-zero exit status 1.
```

**CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.**

Do I have to update CMake?

Can someone help me what's going wrong here?

**Comment by PowerNow** [comment]
I updated now to Emscripten 2.0.10 and got no error but a warning. Until now everthing seems working fine.

`warning: metadce: missing declaration for emcc$export$dynCall_vi`

**Comment by sbc100** [comment]
Does you project use the `harfbuzz` library?    That library has required "Unix Makefile" support to be installed at least since 1.39.17 (See #11352).    You can fix the issue by install `make`.

However I'm not sure how this could have worked for you on 2.0.1 ..  My only guess is that somehow you project doesn't depend on harfbuzz but 2.0.15 is deciding to build it for some reason.

What is the command you are running that is triggering he hardbuzz build?

I imagine that `./emsbuilder build harfbuzz --force` will fail on your machine regardless of SDK version?

**Comment by PowerNow** [comment]
Hi sbc100,
I haven't heard anything about harfbuzz and I don't use it.

Here is my build command:

`emcc -s main.cpp -o emsc.js -I E:\PROGRAMS\glm-0.9.9.8\glm -lidbfs.js -s INITIAL_MEMORY=128MB -s ALLOW_MEMORY_GROWTH=1 -s USE_SDL=2 -s USE_SDL_TTF=2 -s USE_ZLIB=1 -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s FETCH=1 -s EXPORTED_FUNCTIONS="['_main']" -s NO_EXIT_RUNTIME=1 -s EXTRA_EXPORTED_RUNTIME_METHODS="['cwrap']" -O3`

An do you maybe know what this `warning: metadce: missing declaration for emcc$export$dynCall_vi` means?

**Comment by sbc100** [comment]
Ah, it looks like the harfbuzz issue is caused by #12868.  This change added harfbuzz as a dependency of  sdl2_ttf, and harfbuzz the harfbuzz port currently requires `make` to me installed to compile.

I'm not familiar with that metadce warning, hopefully it won't be there anymore once you upgrade to 2.0.15.

**Comment by sbc100** [comment]
Hopefully https://github.com/emscripten-core/emscripten/pull/13655 will fix the issue.

**Comment by PowerNow** [comment]
Ok thanks, so the best will be if I wait for Emscripten 2.0.16.

**Comment by sbc100** [comment]
You have a few options:

1. wait for 2.0.16
2. modify tools/ports/harfbuzz.py locally with the patch from #13655 
3. Install make on your windows machine.

**Comment by Beuc** [comment]
Hi,

With and without #13655 I get a harfbuzz error under GNU/Linux:
```
root:INFO: building port: harfbuzz
configure: cmake -B.../emsdk/upstream/emscripten/cache/ports-builds/harfbuzz -H.../emsdk/upstream/emscripten/cache/ports/harfbuzz/harfbuzz-1.7.5 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=.../emsdk/upstream/emscripten/cache/ports-builds/harfbuzz -DFREETYPE_INCLUDE_DIRS=.../emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype;.../emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype/config -DFREETYPE_LIBRARY=.../emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libfreetype.a -DHB_HAVE_FREETYPE=ON -DCMAKE_TOOLCHAIN_FILE=.../emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=".../emsdk/node/14.15.5_64bit/bin/node"
-- Looking for atexit
-- Looking for atexit - not found
-- Looking for mprotect
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error at /usr/share/cmake-3.13/Modules/CheckFunctionExists.cmake:72 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  CMakeLists.txt:99 (check_function_exists)
  CMakeLists.txt:105 (check_funcs)


-- Configuring incomplete, errors occurred!
See also ".../emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File ".../emsdk/upstream/emscripten/emcc.py", line 3304, in <module>
    sys.exit(main(sys.argv))
  File ".../emsdk/upstream/emscripten/emcc.py", line 3297, in main
    ret = run(args)
  File ".../emsdk/upstream/emscripten/emcc.py", line 1949, in run
    system_libs.add_ports_cflags(cflags, shared.Settings)
  File ".../emsdk/upstream/emscripten/tools/system_libs.py", line 1849, in add_ports_cflags
    port.get(Ports, settings, shared)
  File ".../emsdk/upstream/emscripten/tools/ports/harfbuzz.py", line 70, in get
    return [shared.Cache.get_lib(get_lib_name(settings), create, what='port')]
  File ".../emsdk/upstream/emscripten/tools/cache.py", line 130, in get_lib
    return self.get(name, *args, **kwargs)
  File ".../emsdk/upstream/emscripten/tools/cache.py", line 158, in get
    creator(cachename)
  File ".../emsdk/upstream/emscripten/tools/ports/harfbuzz.py", line 63, in create
    building.configure(configure_args)
  File ".../emsdk/upstream/emscripten/tools/building.py", line 327, in configure
    run_process(args, stdout=stdout, stderr=stderr, env=env, **kwargs)
  File ".../emsdk/upstream/emscripten/tools/shared.py", line 95, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cmake', '-B.../emsdk/upstream/emscripten/cache/ports-builds/harfbuzz', '-H.../emsdk/upstream/emscripten/cache/ports/harfbuzz/harfbuzz-1.7.5', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=.../emsdk/upstream/emscripten/cache/ports-builds/harfbuzz', '-DFREETYPE_INCLUDE_DIRS=.../emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype;.../emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype/config', '-DFREETYPE_LIBRARY=.../emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libfreetype.a', '-DHB_HAVE_FREETYPE=ON', '-DCMAKE_TOOLCHAIN_FILE=.../emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake', '-DCMAKE_CROSSCOMPILING_EMULATOR=".../emsdk/node/14.15.5_64bit/bin/node"']' returned non-zero exit status 1.
error: command 'emcc' failed with exit status 1
make: *** [Makefile:518: .../build/pygame_sdl2-static.built] Error 1
```

Apparently the harfbuzz port doesn't properly clean its environment and gets confused by my outer build system's CFLAGS:
```
  CC=emcc \
    CFLAGS="-s USE_SDL=2 -s USE_SDL_MIXER=2 -s USE_SDL_TTF=2 ..." \
      python setup.py ...
```

To minimally reproduce:
```
emcc --clear-ports
CFLAGS='-s USE_SDL_TTF=2' emcc -s USE_SDL_TTF=2 hello.c
```

**Comment by sbc100** [comment]
Does it help if you build harfbuzz ahead of time using `./embuilder build harfbuzz`

**Comment by Beuc** [comment]
That's my current work-around yes
