### ISSUE TITLE
Emscripten Windows Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by ShuangLiu1992** [emscripten-core/emscripten#13656]
during autoconf with command: configure:9120: /c/Users/liush/.conan/data/emsdk/2.0.11/Zappar/SLAMVis/package/1b9cae620f52583dcb25f37430b509cc22615199/emsdk/upstream/emscripten/emcc -O3 -fPIC -DNDEBUG  conftest.c  >&5

Exception message: "Error: ENOENT: no such file or directory, open '/c/Users/liush/.conan/data/emsdk/2.0.11/Zappar/SLAMVis/package/1b9cae620f52583dcb25f37430b509cc22615199/emsdk/upstream/emscripten/src/library_pthread_stub.js'" | Error: ENOENT: no such file or directory, open '/c/Users/liush/.conan/data/emsdk/2.0.11/Zappar/SLAMVis/package/1b9cae620f52583dcb25f37430b509cc22615199/emsdk/upstream/emscripten/src/library_pthread_stub.js'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at read (C:\Users\liush\.conan\data\emsdk\2.0.11\Zappar\SLAMVis\package\1b9cae620f52583dcb25f37430b509cc22615199\emsdk\upstream\emscripten\src\compiler.js:34:17)
    at Object.load (eval at load (C:\Users\liush\.conan\data\emsdk\2.0.11\Zappar\SLAMVis\package\1b9cae620f52583dcb25f37430b509cc22615199\emsdk\upstream\emscripten\src\compiler.js:38:8), <anonymous>:186:17)
    at JSify (eval at load (C:\Users\liush\.conan\data\emsdk\2.0.11\Zappar\SLAMVis\package\1b9cae620f52583dcb25f37430b509cc22615199\emsdk\upstream\emscripten\src\compiler.js:38:8), <anonymous>:75:20)
    at Object.<anonymous> (C:\Users\liush\.conan\data\emsdk\2.0.11\Zappar\SLAMVis\package\1b9cae620f52583dcb25f37430b509cc22615199\emsdk\upstream\emscripten\src\compiler.js:98:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
emcc: error: 'C:/Users/liush/.conan/data/emsdk/2.0.11/Zappar/SLAMVis/package/1b9cae620f52583dcb25f37430b509cc22615199/emsdk/node/14.15.5_64bit/bin/node.exe /c/Users/liush/.conan/data/emsdk/2.0.11/Zappar/SLAMVis/package/1b9cae620f52583dcb25f37430b509cc22615199/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpmwfsqmol.txt' failed (1)

**Comment by sbc100** [comment]
It looks like emscripten or emsdk is somehow not fully installed.

Is the `library_pthread_stub.js` not present under `emscripten/src` directory?     How about other libraries such as `src/library.js`?

**Comment by ShuangLiu1992** [comment]
its a problem specific to WSL, closing now
