### ISSUE TITLE
ReferenceError: ___cxa_find_matching_catch_2 is not defined

### ISSUE THREAD

**Issue by sps-gold** [emscripten-core/emscripten#13794]
Including flag INCLUDE_FULL_LIBRARY fails the build with:

ReferenceError: ___cxa_find_matching_catch_2 is not defined
at Object. (/tmp/emscripten_test_other_enjwcv6n/test_split_module_ex.js:1:203814)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
at Module.load (internal/modules/cjs/loader.js:928:32)
at Function.Module._load (internal/modules/cjs/loader.js:769:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
at internal/main/run_main_module.js:17:47
-- end program output --
FAIL

**Update**: With the latest I find that INCLUDE_FULL_LIBRARY passes if used together with MAIN_MODULE flag
**Update2**: small test case to reproduce the same https://github.com/emscripten-core/emscripten/pull/14855

emscripten-core/emscripten#13696
test case: test_split_module_ex

**Comment by sps-gold** [comment]
@sbc100 thanks for looking into it. Unfortunately I am still seeing the same error, [here](https://app.circleci.com/pipelines/github/emscripten-core/emscripten/12418/workflows/9de18b5c-244e-44ef-874e-02524a37223d/jobs/413616) after [change](https://github.com/emscripten-core/emscripten/pull/13696/commits/20940744082cf39cf7a0231df45590f58665e8fa).

```
ReferenceError: ___cxa_find_matching_catch_2 is not defined
    at Object.<anonymous> (/tmp/tmpj2bsg2hy/emscripten_test_other_n3kp9l_5/test_split_module_ex.js:1:203446)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

Please have a look, let me know if you think anything is wrong with the test itself.

**Comment by sbc100** [comment]
Was this fixed by a recent change?

**Comment by sps-gold** [comment]
unfortunately not, the issue is still reproducible. 
I was visiting open issues by me, and I felt due to unclear steps its becoming stale. So I have created a better small test case to reproduce the same. 
https://github.com/emscripten-core/emscripten/pull/14855
You may have a look and feel free to decide if its still worth fixing (uses DISABLE_EXCEPTION_CATCHING)

**Comment by sbc100** [comment]
I certainly think its worth fixing.

**Comment by sbc100** [comment]
Thanks so much for the tiny test case.. it really helped me to find the issue: https://github.com/emscripten-core/emscripten/pull/14862
