### ISSUE TITLE
USE_FREETYPE error In Emscripten V2.0.16 

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#13980]
1、Generate VideoRender.a and SuperRender.a  by the Makefile file(emcc and amar)
2、Use VideoRender.a and SuperRender.a generate the SuperRender.js , the compile command is as follows :
`emcc SuperRenderMT.aSuperRender.a -o SuperRender.js  --bind -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'getValue','writeArrayToMemory']"  -s USE_PTHREADS=1 -s TOTAL_MEMORY=1GB -s ALLOW_MEMORY_GROWTH=0 -s MAX_WEBGL_VERSION=2 -s FULL_ES2=1 -s OFFSCREENCANVAS_SUPPORT=1 -s OFFSCREEN_FRAMEBUFFER=1 -s USE_FREETYPE=1 `

and there are two errors:
1、Uncaught TypeError: Module._InputData is not a function , I must use -s EXPORTED_FUNCTIONS="['_InputData','_Stop','_InitMain']" to export the function , the EMSCRIPTEN_KEEPALIVE doesn't work in SuperRender.cpp ?
2、In Emscripten V2.0.16 ，generate the js file make a error. And in Emscripten V1.39 ,it work well(same compile command ) .

**the error In Emscripten V2.0.16:**
`system_libs:INFO: retrieving port: freetype from https://github.com/emscripten-ports/FreeType/archive/version_1.zip
Traceback (most recent call last):
  File "/home/hyde/emsdk/upstream/emscripten/tools/system_libs.py", line 1740, in retrieve
    import requests
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyde/emsdk/upstream/emscripten/emcc.py", line 3475, in <module>
    sys.exit(main(sys.argv))
  File "/home/hyde/emsdk/upstream/emscripten/emcc.py", line 3468, in main
    ret = run(args)
  File "/home/hyde/emsdk/upstream/emscripten/emcc.py", line 2240, in run
    extra_files_to_link += system_libs.get_ports_libs(shared.Settings)
  File "/home/hyde/emsdk/upstream/emscripten/tools/system_libs.py", line 1868, in get_ports_libs
    ret += [f for f in port.get(Ports, settings, shared) if not f.endswith('.txt')]
  File "/home/hyde/emsdk/upstream/emscripten/tools/ports/freetype.py", line 18, in get
    ports.fetch_project('freetype', 'https://github.com/emscripten-ports/FreeType/archive/' + TAG + '.zip', 'FreeType-' + TAG, sha512hash=HASH)
  File "/home/hyde/emsdk/upstream/emscripten/tools/system_libs.py", line 1789, in fetch_project
    retrieve()
  File "/home/hyde/emsdk/upstream/emscripten/tools/system_libs.py", line 1745, in retrieve
    f = urlopen(url)
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 549, in _open
    'unknown_open', req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1388, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
`
can you tell me why ?

**Comment by sbc100** [comment]
`EMSCRIPTEN_KEEPALIVE` will work as long as the object file gets includes.  By default object files in `.a` archive are not included unless there is some dependency on that object file.   You can either use `-Wl,-u,_InputData` or add `-Wl,-whole-archive` (along with `-Wl,no-whole-archive` after) before the `.a` on the command line when linker.. or of course you can use `EXPORTED_FUNCTIONS` as you have found.]

Regarding you second error, that is indeed strange?  Presumably that happens with any port that you try to download and build.    Can try running `./emcc --clear-cache` followed by `./embuilder build zlib` and see if that fails in the same way?  Assuming it does we need to look at why the urllib that is part of the linux distro doesn't seem to working correctly.    Do you know where your  `/usr/local/lib/python3.6/` installation is coming from?  It seems that the urllib there isn't recognizing https URLs..

**Comment by sbc100** [comment]
For `-s USE_FREETYPE=1` work in older versions of emscripten?  For example does it work if you install 2.0.15?

**Comment by yangfangfang1204** [comment]
i solve the problem ,when i update the python version
