### ISSUE TITLE
`emscripten_sleep` causes error when used in `atexit` callback

### ISSUE THREAD

**Issue by navzam** [emscripten-core/emscripten#13993]
## Description

I recently jumped from v1.40.1 to v2.0.18 and am having issues when `emscripten_sleep()` is called during shutdown, such as in an `atexit` callback. I'm compiling with `-s ASYNCIFY -s EXIT_RUNTIME=1` and using `emscripten_force_exit()`. When the `atexit()` callback runs and `emscripten_sleep(0)` is called, I get this error:

```
import emscripten_force_exit was not in ASYNCIFY_IMPORTS, but changed the state
```

If I include `emscripten_force_exit` in `ASYNCIFY_IMPORTS`, I get this error:

```
TypeError: FUNCTION_TABLE[($10_1 | 0)] is not a function
    at $50 (/home/nazam/Simulator/emscripten_testing/out.js:8396:42)
    at $49 (/home/nazam/Simulator/emscripten_testing/out.js:8190:19)
    at ret.<computed> (/home/nazam/Simulator/emscripten_testing/out.js:12013:35)
    at /home/nazam/Simulator/emscripten_testing/out.js:10775:22
    at flush_NO_FILESYSTEM (/home/nazam/Simulator/emscripten_testing/out.js:11849:43)
    at callRuntimeCallbacks (/home/nazam/Simulator/emscripten_testing/out.js:10948:11)
    at exitRuntime (/home/nazam/Simulator/emscripten_testing/out.js:10520:3)
    at exit (/home/nazam/Simulator/emscripten_testing/out.js:12660:5)
    at _emscripten_force_exit (/home/nazam/Simulator/emscripten_testing/out.js:11821:7)
    at imports.<computed> (/home/nazam/Simulator/emscripten_testing/out.js:11989:35)
```

## Version

I'm using v2.0.18, but this is happening back on v2.0.3 too. I don't get these errors on v2.0.2 (though I realized that while `emscripten_sleep()` isn't giving errors, it isn't actually sleeping).

#12295 possible seems related? I'm not sure. That issue was also between v2.0.2 and v2.0.3.

## Example

Here's a small example, taken from the [Asyncify doc](https://emscripten.org/docs/porting/asyncify.html#sleeping-yielding-to-the-event-loop) and added an `emscripten_force_exit()` and `atexit()`:

```cpp
#include <stdlib.h>
#include <emscripten.h>
#include <stdio.h>

// start_timer(): call JS to set an async timer for 500ms
EM_JS(void, start_timer, (), {
  Module.timer = false;
  setTimeout(function() {
    Module.timer = true;
  }, 500);
});

// check_timer(): check if that timer occurred
EM_JS(bool, check_timer, (), {
  return Module.timer;
});

void exitFunc () {
  printf("Starting exit func\n");
  emscripten_sleep(1000);
  printf("Finished exit func\n");
}

int main() {
  atexit(exitFunc);
  
  start_timer();
  // Continuously loop while synchronously polling for the timer.
  while (1) {
    if (check_timer()) {
      printf("timer happened!\n");
      emscripten_force_exit(0);
      return 0;
    }
    printf("sleeping...\n");
    emscripten_sleep(100);
  }
}
```

which I'm compiling with:

```
emcc emscriptenTest.cpp -o out.js -s WASM=0 -s ASYNCIFY -s EXIT_RUNTIME=1
```

and then running `node ./out.js`

**Comment by sbc100** [comment]
Does the issue occur also with WebAssembly (i.e. if you drop the `s WASM=0`) ?

**Comment by navzam** [comment]
Yep, still occurs with WebAssembly on v2.0.3, though with a somewhat different error. Without `ASYNCIFY_IMPORTS`, the error is the same. With `ASYNCIFY_IMPORTS=["emscripten_force_exit"]`, the error is:

```
RuntimeError: function signature mismatch
    at <anonymous>:wasm-function[59]:0xe8b3
    at fflush (<anonymous>:wasm-function[58]:0xe4f1)
    at ret.<computed> (/home/nazam/Simulator/emscripten_testing/a.out.js:2874:35)
    at /home/nazam/Simulator/emscripten_testing/a.out.js:1640:22
    at flush_NO_FILESYSTEM (/home/nazam/Simulator/emscripten_testing/a.out.js:2710:43)
    at callRuntimeCallbacks (/home/nazam/Simulator/emscripten_testing/a.out.js:1809:11)
    at exitRuntime (/home/nazam/Simulator/emscripten_testing/a.out.js:1385:3)
    at exit (/home/nazam/Simulator/emscripten_testing/a.out.js:3440:5)
    at _emscripten_force_exit (/home/nazam/Simulator/emscripten_testing/a.out.js:2682:7)
    at imports.<computed> (/home/nazam/Simulator/emscripten_testing/a.out.js:2850:35)
```

**Comment by sbc100** [comment]
Can't reproduce this on tip of tree.   Can you try with the latest emscripten version (2.0.18)?

**Comment by sbc100** [comment]
> Can't reproduce this on tip of tree. Can you try with the latest emscripten version (2.0.18)?

Sorry, I mispoke, I can reproduce it.

**Comment by sbc100** [comment]
Looks like its related to the use of an async function in atexit.  I can repro with this simpler version:

```
#include <stdlib.h>
#include <emscripten.h>
#include <stdio.h>

void exitFunc () {
  printf("Starting exit func\n");
  emscripten_sleep(1000);
  printf("Finished exit func\n");
}

int main() {
  atexit(exitFunc);
  printf("calling emscripten_force_exit!\n");
  emscripten_force_exit(0);
  return 0;
}
```

**Comment by sbc100** [comment]
Minimal command line to repro: `./emcc test.cc -g -s ASYNCIFY -s EXIT_RUNTIME -s ASYNCIFY_IMPORTS=emscripten_force_exit,fflush  && node a.out.js`

I don't know a lot of about asyncify,  perhaps @kripken will know why it doesn't seem to work from within an atexit function

**Comment by kripken** [comment]
I think can't work currently. The code that calls `atexit`s is in JS, and that JS is synchronous. So the compiled code pauses but the JS that calls it keeps running synchronously, tearing down the runtime, and then things break when the code tries to resume.

To solve this that JS code would need to be async, or for the code calling `atexit`s to be in compiled code (where asyncify would rewrite it). The latter may be worth looking into? We've moved to do more startup in compiled code, and I think the same could work for shutdown.

**Comment by navzam** [comment]
Thanks @sbc100 and @kripken for the help. Is there any way to detect when emscripten is trying to shutdown?

For context, we have functions like:

```c
void Foo::bar()
{
  ...
  emscripten_sleep(0);
  ...
}
```

`bar()` is called from a lot of places, including destructors which currently break. If we could detect that emscripten is shutting down, then we could wrap the `emscripten_sleep` call in a condition. I know we can pass an extra parameter to `bar()` that is set to `true` when called from destructors, but I'm wondering if we can avoid this.

Alternatively we can revert to v2.0.2, but I'm also trying to avoid that.

**Comment by sbc100** [comment]
It sounds like removing your reliance on `atexit` somehow might be way forward.

**Comment by kripken** [comment]
@sbc100 's advice is best I think.

Another option might be for you to add an `atexit` solely for the purpose of detecting when atexits are being called, in order to detect shutdown. (I forget the order of atexits, but if you put it all the way at the front or the end, it can be guaranteed to run before anything else.)

**Comment by navzam** [comment]
Makes sense. I used `atexit` to reproduce the issue, but really our problem is in destructors. Not sure if there's any ordering trick we can do with destructors but I'll look into it.

**Comment by sbc100** [comment]
Presumably you are referring to static destructors which run using atexit?     Are you dependent on `EXIT_RUNTIME=1`?     Most programs work fine without this, and relying on program exits is not a good idea, especially on the web.   

Perhaps in debug mode we could assert if `emscripten_sleep` us called during the exit process?

**Comment by kripken** [comment]
@sbc100 that's a good idea, I'll add an assert + test for that.

**Comment by navzam** [comment]
Yep, static destructors. I didn't realize they're run using `atexit` but makes sense ☺

In our current C library, it's important for those static destructors to run when the user's program (compiled against our library) terminates cleanly. So currently we're dependent on `EXIT_RUNTIME=1`. We may be able to do some reworking so that those static destructors aren't necessary, or at least do something different when using it with emscripten (the library is most often used as a normal C library, not with emscripten).

**Comment by sbc100** [comment]
I think this can be closed now?
