### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by Ducanger** [emscripten-core/emscripten#14027]
I have same error in #13648 but my curent version is 2.0.18.
I don't know why? I certainly error from SDL2_TFF because I build this command sucessfully:
`emcc hello_world.c -I include -O2 -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s USE_SDL_MIXER=2 -o index.html`
If I add `-s USE_SDL_TTF=2`, it is wrong.
Please help me! 
Thanks.

**Comment by sbc100** [comment]
Does building harfbuzz on its own fail for you:  `./embuilder build harfbuzz`?

Can you post the full output of the failure?

**Comment by Ducanger** [comment]
It's full output of the failure
```
cache:INFO: generating port: sysroot\lib\wasm32-emscripten\libharfbuzz.a... (this will be cached in "D:\Flying Shiba\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\libharfbuzz.a" for subsequent builds)
root:INFO: building port: harfbuzz
configure: cmake "-BD:\Flying Shiba\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz" "-HD:\Flying Shiba\emsdk\upstream\emscripten\cache\ports\harfbuzz\harfbuzz-1.7.5" -DCMAKE_BUILD_TYPE=Release "-DCMAKE_INSTALL_PREFIX=D:\Flying Shiba\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz" "-DFREETYPE_INCLUDE_DIRS=D:\Flying Shiba\emsdk\upstream\emscripten\cache\sysroot\include\freetype2\freetype;D:\Flying Shiba\emsdk\upstream\emscripten\cache\sysroot\include\freetype2\freetype\config" "-DFREETYPE_LIBRARY=D:\Flying Shiba\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\libfreetype.a" -DHB_HAVE_FREETYPE=ON "-DCMAKE_TOOLCHAIN_FILE=D:\Flying Shiba\emsdk\upstream\emscripten\cmake\Modules\Platform\Emscripten.cmake" "-DCMAKE_CROSSCOMPILING_EMULATOR=\"D:/Flying Shiba/emsdk/node/14.15.5_64bit/bin/node.exe\"" -G "MinGW Makefiles"
emcmake: error: 'cmake "-BD:\Flying Shiba\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz" "-HD:\Flying Shiba\emsdk\upstream\emscripten\cache\ports\harfbuzz\harfbuzz-1.7.5" -DCMAKE_BUILD_TYPE=Release "-DCMAKE_INSTALL_PREFIX=D:\Flying Shiba\emsdk\upstream\emscripten\cache\ports-builds\harfbuzz" "-DFREETYPE_INCLUDE_DIRS=D:\Flying Shiba\emsdk\upstream\emscripten\cache\sysroot\include\freetype2\freetype;D:\Flying Shiba\emsdk\upstream\emscripten\cache\sysroot\include\freetype2\freetype\config" "-DFREETYPE_LIBRARY=D:\Flying Shiba\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\libfreetype.a" -DHB_HAVE_FREETYPE=ON "-DCMAKE_TOOLCHAIN_FILE=D:\Flying Shiba\emsdk\upstream\emscripten\cmake\Modules\Platform\Emscripten.cmake" "-DCMAKE_CROSSCOMPILING_EMULATOR=\"D:/Flying Shiba/emsdk/node/14.15.5_64bit/bin/node.exe\"" -G "MinGW Makefiles"' failed: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "D:\Flying Shiba\emsdk\upstream\emscripten\emcc.py", line 3535, in <module>
    sys.exit(main(sys.argv))
  File "D:\Flying Shiba\emsdk\upstream\emscripten\emcc.py", line 3528, in main
    ret = run(args)
  File "D:\Flying Shiba\emsdk\upstream\emscripten\emcc.py", line 2225, in run
    compile_source_file(i, input_file)
  File "D:\Flying Shiba\emsdk\upstream\emscripten\emcc.py", line 2213, in compile_source_file
    cmd = get_clang_command(input_file)
  File "D:\Flying Shiba\emsdk\upstream\emscripten\emcc.py", line 2162, in get_clang_command
    return get_compiler(use_cxx(src_file)) + get_cflags(options, args) + compile_args + [src_file]
  File "D:\Flying Shiba\emsdk\upstream\emscripten\emcc.py", line 844, in get_cflags
    system_libs.add_ports_cflags(cflags, settings)
  File "D:\Flying Shiba\emsdk\upstream\emscripten\tools\system_libs.py", line 1909, in add_ports_cflags
    port.get(Ports, settings, shared)
  File "D:\Flying Shiba\emsdk\upstream\emscripten\tools\ports\harfbuzz.py", line 70, in get
    return [shared.Cache.get_lib(get_lib_name(settings), create, what='port')]
  File "D:\Flying Shiba\emsdk\upstream\emscripten\tools\cache.py", line 131, in get_lib
    return self.get(name, *args, **kwargs)
  File "D:\Flying Shiba\emsdk\upstream\emscripten\tools\cache.py", line 159, in get
    creator(cachename)
  File "D:\Flying Shiba\emsdk\upstream\emscripten\tools\ports\harfbuzz.py", line 63, in create
    shared.run_process(cmake_cmd)
  File "D:\Flying Shiba\emsdk\upstream\emscripten\tools\shared.py", line 97, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['D:\\Flying Shiba\\emsdk\\upstream\\emscripten\\emcmake.bat', 'cmake', '-BD:\\Flying Shiba\\emsdk\\upstream\\emscripten\\cache\\ports-builds\\harfbuzz', '-HD:\\Flying Shiba\\emsdk\\upstream\\emscripten\\cache\\ports\\harfbuzz\\harfbuzz-1.7.5', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=D:\\Flying Shiba\\emsdk\\upstream\\emscripten\\cache\\ports-builds\\harfbuzz', '-DFREETYPE_INCLUDE_DIRS=D:\\Flying Shiba\\emsdk\\upstream\\emscripten\\cache\\sysroot\\include\\freetype2\\freetype;D:\\Flying Shiba\\emsdk\\upstream\\emscripten\\cache\\sysroot\\include\\freetype2\\freetype\\config', '-DFREETYPE_LIBRARY=D:\\Flying Shiba\\emsdk\\upstream\\emscripten\\cache\\sysroot\\lib\\wasm32-emscripten\\libfreetype.a', '-DHB_HAVE_FREETYPE=ON']' returned non-zero exit status 1.
```

**Comment by sbc100** [comment]
Yes, so the problem is that the harfbuzz port depends on MinGW make being installed on windows, and freetype recently started to depend on harfbuzz.   This is unfortunate, but for now I think you need to install mingw make to make hardbuzz work on windows.

Alternatively you could comment out the harfbuzz dependency in `tools/ports/sdl2_ttf.py` (remove `'-DTTF_USE_HARFBUZZ=1'` and `settings.USE_HARFBUZZ = 1`)

**Comment by Ducanger** [comment]
I had install MinGW in my pc.
```
C:\Users\ADMIN>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/9.2.0/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-9.2.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --target=mingw32 --disable-win32-registry --with-arch=i586 --with-tune=generic --enable-static --enable-shared --enable-threads --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --enable-libgomp --disable-libvtv --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --disable-build-format-warnings --prefix=/mingw --with-gmp=/mingw --with-mpfr=/mingw --with-mpc=/mingw --with-isl=/mingw --enable-nls --with-pkgversion='MinGW.org GCC Build-2'
Thread model: win32
gcc version 9.2.0 (MinGW.org GCC Build-2)
```
 And I follow you to comment out the harfbuzz dependency in tools/ports/sdl2_ttf.py but no change.
```
def process_dependencies(settings):
  settings.USE_SDL = 2
  settings.USE_FREETYPE = 1
#  settings.USE_HARFBUZZ = 1
def process_args(ports):
  return [] #'-DTTF_USE_HARFBUZZ=1'
def show():
  return 'SDL2_ttf (USE_SDL_TTF=2; zlib license)'
```

**Comment by ericoporto** [comment]
> freetype recently started to depend on harfbuzz

This is false. FreeType CAN use harfbuzz but doesn't depend on it. https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/CMakeLists.txt#L82

**Comment by sbc100** [comment]
> > freetype recently started to depend on harfbuzz
> 
> This is false. FreeType CAN use harfbuzz but doesn't depend on it. https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/CMakeLists.txt#L82
> 
> FreeType from the ports is super old but the latest FreeType from their GITLAB repository builds fine with Emscripten using their own `CMakeLists.txt`.
> 
> Updating the port though requires simultaneously updating the port source AND the emsdk since for some reason the ports use the weird python builder instead of something normal.

Sorry, I should been more clear:   The sdl2_ttf port in emscripten was recently updated to depend on hardbuzz.  See #12868.  Prior to that change harfbuzz was not needed/used by the sdl2_ttf port.

I don't think updating the version of freetype is going to fix this issue.  Its the building of harfbuzz that is the issue.

**Comment by sbc100** [comment]
The workaround is to either install `ninja` or `mingw-make`.  I've created #14323 to clearly indicate this.

@Ducanger .. it looks like maybe you don't have `cmake` either, which is also a pre-requisite for building harfbuzz.  

It looks like you will also need to remove `harfbuzz` from  `deps = ['freetype', 'sdl2', 'harfbuzz']` in sdl2_ttf.py if you want to avoid this dependency completely.
