### ISSUE TITLE
Some wasm EH tests fail with ASan

### ISSUE THREAD

**Issue by aheejin** [emscripten-core/emscripten#14035]
Some wasm EH tests fail with asan, including `test_exceptions_uncaught_count_wasm_eh`:

```
$ ./tests/runner.py asan.test_exceptions_uncaught_count_wasm_eh 
runner:WARNING: use EMTEST_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
Test suites:
['test_core']
Running test_core: (1 tests)
(checking sanity from test runner)
shared:INFO: (Emscripten: Running sanity checks)
test_exceptions_uncaught_count_wasm_eh (test_core.asan) ... -- begin program output --
in inner catch: 0
exception thrown: RuntimeError: unreachable,RuntimeError: unreachable
    at main (<anonymous>:wasm-function[33]:0xdc7)
    at Module._main (test_exceptions_uncaught_count.js:1:83212)
    at callMain (test_exceptions_uncaught_count.js:1:89234)
    at doRun (test_exceptions_uncaught_count.js:1:89794)
    at run (test_exceptions_uncaught_count.js:1:89966)
    at runCaller (test_exceptions_uncaught_count.js:1:89089)
    at removeRunDependency (test_exceptions_uncaught_count.js:1:13048)
    at receiveInstance (test_exceptions_uncaught_count.js:1:16918)
    at receiveInstantiationResult (test_exceptions_uncaught_count.js:1:17076)
-- end program output --
FAIL

======================================================================
FAIL: test_exceptions_uncaught_count_wasm_eh (test_core.asan)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/aheejin/emscripten/tests/runner.py", line 345, in resulting_test
    return func(self, *args)
  File "/usr/local/google/home/aheejin/emscripten/tests/test_core.py", line 105, in metafunc
    f(self)
  File "/usr/local/google/home/aheejin/emscripten/tests/test_core.py", line 1432, in test_exceptions_uncaught_count
    self.do_core_test('test_exceptions_uncaught_count.cpp')
  File "/usr/local/google/home/aheejin/emscripten/tests/test_core.py", line 288, in do_core_test
    self.do_run_in_out_file_test('core', testname, **kwargs)
  File "/usr/local/google/home/aheejin/emscripten/tests/runner.py", line 1036, in do_run_in_out_file_test
    self._build_and_run(srcfile, expected, **kwargs)
  File "/usr/local/google/home/aheejin/emscripten/tests/runner.py", line 1077, in _build_and_run
    js_output = self.run_js(js_file, engine, args, output_nicerizer=output_nicerizer, assert_returncode=assert_returncode)
  File "/usr/local/google/home/aheejin/emscripten/tests/runner.py", line 695, in run_js
    self.fail('JS subprocess failed (%s): %s.  Output:\n%s' % (error.cmd, error.returncode, ret))
AssertionError: JS subprocess failed (/usr/local/google/home/aheejin/waterfall/src/work/wasm-install/bin/d8 --experimental-wasm-eh test_exceptions_uncaught_count.js --no-wasm-async-compilation --): 1.  Output:
in inner catch: 0
exception thrown: RuntimeError: unreachable,RuntimeError: unreachable
    at main (<anonymous>:wasm-function[33]:0xdc7)
    at Module._main (test_exceptions_uncaught_count.js:1:83212)
    at callMain (test_exceptions_uncaught_count.js:1:89234)
    at doRun (test_exceptions_uncaught_count.js:1:89794)
    at run (test_exceptions_uncaught_count.js:1:89966)
    at runCaller (test_exceptions_uncaught_count.js:1:89089)
    at removeRunDependency (test_exceptions_uncaught_count.js:1:13048)
    at receiveInstance (test_exceptions_uncaught_count.js:1:16918)
    at receiveInstantiationResult (test_exceptions_uncaught_count.js:1:17076)


----------------------------------------------------------------------
Ran 1 test in 7.462s

FAILED (failures=1)
```

The list of failing tests is:
```
test_exceptions_typed_wasm_eh
test_exceptions_convert_wasm_eh
test_exceptions_multi_wasm_eh
test_exceptions_rethrow_wasm_eh
test_exceptions_uncaught_count_wasm_eh
test_exceptions_resume_wasm_eh
test_exceptions_multiple_inherit_wasm_eh
test_exceptions_multiple_inherit_rethrow_wasm_eh
```

**Comment by sbc100** [comment]
We should probably look into this ..

**Comment by aheejin** [comment]
Not sure what the cause was and what fixed it, but all asan tests here, except the ones affected by #21124 (and will be fixed by #23552), are working now. Closing.
