### ISSUE TITLE
WebIDL, callback, function pointer

### ISSUE THREAD

**Issue by lsarrazi** [emscripten-core/emscripten#14070]
How can we define a function that took a callback from Javascript using WebIDL ?

**Comment by mmarczell-graphisoft** [comment]
WebIDL supports callback types:

```
callback SomeCallback = void (long a, long b, boolean c);

interface SomeModule {
	void SomeMethod(SomeCallback callback);
};
```

But Emscripten's WebIDL Binder does not.

```
$EMSDK/upstream/emscripten/tools/webidl_binder my_classes.idl glue
```
prints an error:
```
Traceback (most recent call last):
  File "/Volumes/SSD/git/emsdk/upstream/emscripten/tools/webidl_binder.py", line 59, in <module>
    data = p.finish()
  File "/Volumes/SSD/git/emsdk/upstream/emscripten/third_party/WebIDL.py", line 4984, in finish
    if p not in seen:
TypeError: unhashable type: 'IDLCallbackType'
```

I could work on fixing this but I'd appreciate some pointers on where to start.

**Version of emscripten/emsdk:**

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.0.0 (3fd52e107187b8a169bb04a02b9f982c8a075205)
clang version 14.0.0 (https://github.com/llvm/llvm-project 4348cd42c385e71b63e5da7e492172cff6a79d7b)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Volumes/SSD/git/emsdk/upstream/bin

**Comment by kripken** [comment]
`third_party/WebIDL.py` is the generic WebIDL parser. It is used by `tools/webidl_binder.py` which operates on the IR that the parser emits, basically. For this, maybe changes in both would be needed.

But I'm not sure how callbacks could be integrated in the WebIDL glue code, though. The WebIDL glue is fairly simple. As a first step maybe I would suggest reading the WebIDL output and seeing how callbacks can work there.

**Comment by mmarczell-graphisoft** [comment]
Thanks for the advice. In the meantime we seem to have settled on Embind instead, as it's much more flexible and complete. That makes it less likely for me to work on WebIDL improvements.
