### ISSUE TITLE
asan.test_pthread_thread_local_storage failure on emscripten-releases waterfall

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#14111]
We started seeing this failure on the emscripten-releases waterfall after #14047 landed.

```
======================================================================
FAIL: test_pthread_thread_local_storage (test_core.asan)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/b/s/w/ir/cipd_bin_packages/cpython3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/b/s/w/ir/cipd_bin_packages/cpython3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/b/s/w/ir/cipd_bin_packages/cpython3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/b/s/w/ir/k/install/emscripten/tests/runner.py", line 202, in decorated
    f(self)
  File "/b/s/w/ir/k/install/emscripten/tests/test_core.py", line 2423, in test_pthread_thread_local_storage
    self.do_run_in_out_file_test('pthread', 'test_pthread_thread_local_storage.cpp')
  File "/b/s/w/ir/k/install/emscripten/tests/runner.py", line 1029, in do_run_in_out_file_test
    self._build_and_run(srcfile, expected, **kwargs)
  File "/b/s/w/ir/k/install/emscripten/tests/runner.py", line 1070, in _build_and_run
    js_output = self.run_js(js_file, engine, args, output_nicerizer=output_nicerizer, assert_returncode=assert_returncode)
  File "/b/s/w/ir/k/install/emscripten/tests/runner.py", line 697, in run_js
    self.fail('JS subprocess failed (%s): %s.  Output:\n%s' % (error.cmd, error.returncode, ret))
  File "/b/s/w/ir/cipd_bin_packages/cpython3/lib/python3.8/unittest/case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: JS subprocess failed (/b/s/w/ir/cache/builder/emscripten-releases/node-v12.18.1-linux-x64/bin/node --experimental-wasm-threads --experimental-wasm-bulk-memory test_pthread_thread_local_storage.js): 1.  Output:
==42==AddressSanitizer CHECK failed: /b/s/w/ir/k/install/emscripten/system/lib/compiler-rt/lib/sanitizer_common/sanitizer_allocator_secondary.h:101 "((IsAligned(map_beg, page_size_))) != (0)" (0x0, 0x0)
    #0 0x18a53 in wasm-function[230]+0x18a53 (/b/s/w/ir/tmp/t/tmplxzpt76l/emscripten_test_asan_3kt721ei/test_pthread_thread_local_storage.wasm+0x18a53)
    #1 0x2126c in wasm-function[286]+0x2126c (/b/s/w/ir/tmp/t/tmplxzpt76l/emscripten_test_asan_3kt721ei/test_pthread_thread_local_storage.wasm+0x2126c)
    #2 0x11e42 in wasm-function[175]+0x11e42 (/b/s/w/ir/tmp/t/tmplxzpt76l/emscripten_test_asan_3kt721ei/test_pthread_thread_local_storage.wasm+0x11e42)
    #3 0x1155b in wasm-function[173]+0x1155b (/b/s/w/ir/tmp/t/tmplxzpt76l/emscripten_test_asan_3kt721ei/test_pthread_thread_local_storage.wasm+0x1155b)
    #4 0x1a9a9 in wasm-function[244]+0x1a9a9 (/b/s/w/ir/tmp/t/tmplxzpt76l/emscripten_test_asan_3kt721ei/test_pthread_thread_local_storage.wasm+0x1a9a9)
    #5 0x80000001 in _emscripten_builtin_pthread_create /b/s/w/ir/tmp/t/tmplxzpt76l/emscripten_test_asan_3kt721ei/test_pthread_thread_local_storage.js:1:93972
    #6 0x80000001 in _emscripten_builtin_pthread_create /b/s/w/ir/tmp/t/tmplxzpt76l/emscripten_test_asan_3kt721ei/test_pthread_thread_local_storage.js:1:93972
    #7 0x1abee in wasm-function[246]+0x1abee (/b/s/w/ir/tmp/t/tmplxzpt76l/emscripten_test_asan_3kt721ei/test_pthread_thread_local_storage.wasm+0x1abee)
```

The strange thing is that this does *not* occur with the current version of node that we use in emsdk (v14.15.5).   I can only reproduce this locally if I use v12.18.1 which is installed on the emscripten-releases builders.

I'm tempted to just update the waterfall scripts to use the current / correct / expected version of node... but at the same time I'm rather curious what could be going on here.    

@kripken any ideas?

**Comment by kripken** [comment]
Hmm, very odd...

It seems like this has to be a node or v8 bug. One that has been fixed - as you said, v14 works, which I verified locally, and also newer versions still work, as well as chrome. So not sure it's worth looking into more, +1 for updating the node on CI.
