### ISSUE TITLE
emrun exception thrown: NetworkError: Failed to execute 'send' on XMLHttpRequest stdio.html

### ISSUE THREAD

**Issue by nipuna** [emscripten-core/emscripten#14128]
I have a simple c file, 
#include <stdio.h>

int main() {
	printf("Hello Word");
	return 0;
}
Compiled the file successfully to wasm.
D:\Practice\emscripten>emcc -O3 --emrun -s WASM=1 -o Hello.html hello.c

But I get an error using emrun. emrun is making an AJAX request to stdio.html. Anybody can help on how to fix this issue?

D:\Practice\emscripten>emrun Hello.html
exception thrown: NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:6931/stdio.html'.,Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:6931/stdio.html'.
    at postExit (http://localhost:6931/Hello.js:1:14076)
    at http://localhost:6931/Hello.js:1:14629
    at callRuntimeCallbacks (http://localhost:6931/Hello.js:1:10404)
    at exitRuntime (http://localhost:6931/Hello.js:1:6251)
    at exit (http://localhost:6931/Hello.js:1:13422)
    at callMain (http://localhost:6931/Hello.js:1:12558)
    at doRun (http://localhost:6931/Hello.js:1:13093)
    at http://localhost:6931/Hello.js:1:13248

**Comment by pscamodio** [comment]
I'm able to reproduce the issue on my side.
Emscripten Version: 2.0.27
Browser: Firefox 91.0.1

**Comment by 3d4m-vladimir** [comment]
Same here. I got this on 2.0.27+

**Comment by 3d4m-vladimir** [comment]
> Same here. I got this on 2.0.27+

Ops. In my case I had `emscripten_async_call`

**Comment by mere-human** [comment]
Is there some sort of a workaround for this? 
I see this exception in the browser when using `emrun`. 
How the `stdio.html` should be created?

**Comment by sbc100** [comment]
I tracked this down to #12523.   Not sure what the best solution is here.
