### ISSUE TITLE
New failure with exception catching

### ISSUE THREAD

**Issue by abellgithub** [emscripten-core/emscripten#14163]
Our CI loop caught this. We fetch a new emsdk each run. The previous 

```
cd /home/runner/work/laz-perf/laz-perf/lazperf/build/cpp/examples && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/readlaz.dir/link.txt --verbose=1
/home/runner/work/laz-perf/laz-perf/emsdk/upstream/emscripten/em++ -s DISABLE_EXCEPTION_CATCHING=2  -O3 -DNDEBUG @CMakeFiles/readlaz.dir/objects1.rsp -o readlaz.js @CMakeFiles/readlaz.dir/linklibs.rsp
/home/runner/work/laz-perf/laz-perf/emsdk/upstream/emscripten/em++ -s DISABLE_EXCEPTION_CATCHING=2  -O3 -DNDEBUG @CMakeFiles/readlaz.dir/objects1.rsp -o readlaz.js @CMakeFiles/readlaz.dir/linklibs.rsp
error: DISABLE_EXCEPTION_CATCHING was set, which means no C++ exception catching support code is linked in, but such support is required by symbol `__cxa_begin_catch`. Either link with DISABLE_EXCEPTION_CATCHING=0 (if you do want exception catching) or compile all source files with DISABLE_EXCEPTION_CATCHING=1 (the default) (so that no exception catching support code is required).
error: DISABLE_EXCEPTION_CATCHING was set, which means no C++ exception catching support code is linked in, but such support is required by symbol `__cxa_end_catch`. Either link with DISABLE_EXCEPTION_CATCHING=0 (if you do want exception catching) or compile all source files with DISABLE_EXCEPTION_CATCHING=1 (the default) (so that no exception catching support code is required).
Internal compiler error in src/compiler.js!
Please create a bug report at https://github.com/emscripten-core/emscripten/issues/
with a log of the build and the input files used to run. Exception message: "ReferenceError: addCxaCatch is not defined" | ReferenceError: addCxaCatch is not defined
    at functionStubHandler (eval at load (/home/runner/work/laz-perf/laz-perf/emsdk/upstream/emscripten/src/compiler.js:38:8), <anonymous>:128:7)
    at Array.forEach (<anonymous>)
    at JSify (eval at load (/home/runner/work/laz-perf/laz-perf/emsdk/upstream/emscripten/src/compiler.js:38:8), <anonymous>:440:19)
    at Object.<anonymous> (/home/runner/work/laz-perf/laz-perf/emsdk/upstream/emscripten/src/compiler.js:98:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
em++: error: '/home/runner/work/laz-perf/laz-perf/emsdk/node/14.15.5_64bit/bin/node 
```

**Comment by kripken** [comment]
Is the error message there not clear enough? Or is the problem that following those steps is either hard, or does not work?

I mean the first error shown,
```
error: DISABLE_EXCEPTION_CATCHING was set, which means no C++ exception catching support code is linked in, but such support is required by symbol `__cxa_begin_catch`.

Either link with DISABLE_EXCEPTION_CATCHING=0 (if you do want exception catching) or compile all source files with DISABLE_EXCEPTION_CATCHING=1 (the default) (so that no exception catching support code is required).
```

**Comment by kripken** [comment]
(That is, it seems like you have built some object files with exceptions, but are linking without exceptions, so the compiler is not sure what you actually want.)

**Comment by abellgithub** [comment]
Thanks for the feedback, but no, I don't understand WRT emsdk. I'm never setting any exception handling options and my project hasn't changed since it last ran successfully, so something external has. It may not be emsdk, but perhaps cmake or the compiler.  All this is hidden by emmake so I'm a bit at a loss.  The process that I'm running is:


```
git clone https://github.com/emscripten-core/emsdk.git
cd emsdk
git pull
./emsdk activate latest
. emsdk/emsdk_env.sh
```      

followed by:

```
cmake .. \
    -DCMAKE_TOOLCHAIN_FILE="$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake" \
    -DCMAKE_BUILD_TYPE=Release -DWASM=1
$EMSDK/upstream/emscripten/emmake make VERBOSE=1
```

**Comment by abellgithub** [comment]
It seems like this might have been introduced by this change:

https://github.com/emscripten-core/emscripten/pull/13862

Does the cmake support file(upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake) perhaps need to get updated as well to pass the proper options to the linker?
