### ISSUE TITLE
test_emsize fails on windows on github CI but not on emscripten-releases CI

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#14183]
We don't normally run this test on windows in github CI so it went unnoticed.

I have no idea why it would fail, only on windows and only on github CI.

```
FAIL: test_emsize (test_other.other)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "unittest\case.py", line 59, in testPartExecutor
  File "unittest\case.py", line 593, in run
  File "unittest\case.py", line 550, in _callTestMethod
  File "C:\Users\circleci\project\tests\test_other.py", line 544, in test_emsize
    self.assertContained(expected, output)
  File "C:\Users\circleci\project\tests\runner.py", line 765, in assertContained
    self.fail("Expected to find '%s' in '%s', diff:\n\n%s\n%s" % (
  File "unittest\case.py", line 670, in fail
AssertionError: Expected to find 'section      size   addr
TYPE           51      0
IMPORT         31      0
FUNCTION       14      0
GLOBAL          9      0
EXPORT          9      0
ELEM            9      0
CODE         1556      0
DATA           77      0
JS		6756	0
Total		8512
' in 'C:\Users\circleci\project\tests\other\test_emsize.wasm  :
section      size   addr
TYPE           51      0
IMPORT         31      0
FUNCTION       14      0
GLOBAL          9      0
EXPORT          9      0
ELEM            9      0
CODE         1556      0
DATA           77      0
JS		6773	0
Total		8529
', diff:

--- expected
+++ actual
@@ -1,3 +1,4 @@
+C:\Users\circleci\project\tests\other\test_emsize.wasm  :
 section      size   addr
 TYPE           51      0
 IMPORT         31      0
@@ -7,6 +8,6 @@
 ELEM            9      0
 CODE         1556      0
 DATA           77      0
-JS		6756	0
-Total		8512
+JS		6773	0
+Total		8529
```

**Comment by sbc100** [comment]
https://app.circleci.com/pipelines/github/emscripten-core/emscripten/13301/workflows/0cd375ae-51da-4353-aa85-c5609f4ad010/jobs/425540

@dschuff @kripken any ideas?  I guess its not super urgent but its a little wierd.

**Comment by kripken** [comment]
Kind of odd, yeah. The small extra size seems like it might be extra `\r`s - is there some way to disable windows emitting those, like maybe we are on windows but in WSL or such, on chromium CI?

**Comment by dschuff** [comment]
or could it be an encoding thing? UTF8 vs CP1252?

**Comment by sbc100** [comment]
I think I tested with my PR that added PYTHONUTF8 and it still failed.
