### ISSUE TITLE
using a relative path for --cache fails in a confusing way

### ISSUE THREAD

**Issue by thomasballinger** [emscripten-core/emscripten#14184]
Only absolute paths work with --cache/EM_CACHE. Would adding an error message or warning to emcc.py (assuming [EM_CACHE is going away](https://github.com/emscripten-core/emscripten/pull/13954#issuecomment-827491591)) make sense?

---

If relative paths should be allowed, I'm seeing using a relative path for EM_CACHE like `emcc -o hello.html --cache foo main.cpp` fail because `copytree_exists_ok()`

https://github.com/emscripten-core/emscripten/blob/301b84283435df6fee9500329816440e9a83afd9/tools/system_libs.py#L1919-L1925

recurses forever when run with `toolscopytree_exists_ok("/Users/tomb/emsdk/upstream/emscripten/system/include", "foo/sysroot/inc")`:

```
cache:INFO: generating system headers: sysroot_install.stamp... (this will be cached in "/Users/tomb/tmp/emcache/sysroot_install.stamp" for subsequent builds)
Traceback (most recent call last):
  File "/Users/tomb/emsdk/upstream/emscripten/emcc.py", line 3632, in <module>
    sys.exit(main(sys.argv))
  File "/Users/tomb/emsdk/upstream/emscripten/emcc.py", line 3625, in main
    ret = run(args)
  File "/Users/tomb/emsdk/upstream/emscripten/emcc.py", line 1047, in run
    phase_compile_inputs(options, state, newargs, input_files, linker_inputs)
  File "/Users/tomb/emsdk/python/3.9.2-1_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/tomb/emsdk/upstream/emscripten/emcc.py", line 2259, in phase_compile_inputs
    system_libs.ensure_sysroot()
  File "/Users/tomb/emsdk/python/3.9.2-1_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/tomb/emsdk/upstream/emscripten/tools/system_libs.py", line 1974, in ensure_sysroot
    shared.Cache.get('sysroot_install.stamp', install_system_headers, what='system headers')
  File "/Users/tomb/emsdk/upstream/emscripten/tools/cache.py", line 162, in get
    creator(cachename)
  File "/Users/tomb/emsdk/upstream/emscripten/tools/system_libs.py", line 1953, in install_system_headers
    copytree_exist_ok(src, dest)
  File "/Users/tomb/emsdk/upstream/emscripten/tools/system_libs.py", line 1931, in copytree_exist_ok
    shared.safe_copy(os.path.join(src, dirname, f), os.path.join(destdir, f))
  File "/Users/tomb/emsdk/upstream/emscripten/tools/shared.py", line 739, in safe_copy
    shutil.copy(src, dst)
  File "/Users/tomb/emsdk/python/3.9.2-1_64bit/lib/python3.9/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/tomb/emsdk/python/3.9.2-1_64bit/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 63] File name too long: '/Users/tomb/emsdk/upstream/emscripten/system/include/emcache/sysroot/include/emcachea/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emcache/sysroot/include/emscripten.h'
tomb tmp$
```

**Comment by thomasballinger** [comment]
Fixed by https://github.com/emscripten-core/emscripten/pull/14209, now this works. See notes at https://github.com/emscripten-core/emscripten/pull/14185 for why you probably don't want to use --cache in the first place.
