### ISSUE TITLE
emscripten_current_thread_process_queued_calls error

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#14334]
First, the c code as :
`int main() {
    //线程一
    printf("Creating thread1.\n");
    pthread_create(&thread1, NULL, DecodeThread, NULL);
    pthread_detach(thread1);
    //线程二
    pthread_attr_t attr;
    pthread_attr_init(&attr);
    emscripten_pthread_attr_settransferredcanvases(&attr, g_pHwd);
    printf("Creating thread2.\n");
    pthread_create(&thread2, &attr, displayThread, NULL);
    pthread_detach(thread2);
    EM_ASM(noExitRuntime=true);
    return 1;
}`
Second, the compile file as 
'-s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'getValue','writeArrayToMemory']" -s TOTAL_MEMORY=2000MB -s ALLOW_MEMORY_GROWTH=0 --js-library renderer.js -s MAX_WEBGL_VERSION=2  -s OFFSCREENCANVAS_SUPPORT=1 -s USE_FREETYPE=1 -lopenal -s GL_PREINITIALIZED_CONTEXT=1 -pthread -s EXPORT_NAME='JSPlayerModule' -s MODULARIZE=1'

Then: one of the thread exit, and there is a error: 
`Pthread aborting at Error
    at abort (http://localhost:9090/Decoder.js:1554:70)
    at ___assert_fail (http://localhost:9090/Decoder.js:2273:7)
    at http://localhost:9090/Decoder.wasm:wasm-function[366]:0x7cae
    at emscripten_current_thread_process_queued_calls (http://localhost:9090/Decoder.wasm:wasm-function[365]:0x7bcd)
    at http://localhost:9090/Decoder.wasm:wasm-function[364]:0x7b32
    at http://localhost:9090/Decoder.wasm:wasm-function[452]:0xc953
    at http://localhost:9090/Decoder.wasm:wasm-function[453]:0xc991
    at http://localhost:9090/Decoder.wasm:wasm-function[4407]:0x1e23fb
    at http://localhost:9090/Decoder.wasm:wasm-function[4406]:0x1e19d3
    at http://localhost:9090/Decoder.js:9498:26`

in EmscriptenV2.0.16 , Could you tell me why?

**Comment by yangfangfang1204** [comment]
How to use emscripten_request_animation_frame_loop in subThread()?

**Comment by yangfangfang1204** [comment]
emscripten_request_animation_frame_loop(callbackFun,pUser);
After callbackFun() , the subThread exit() ？why？

**Comment by yangfangfang1204** [comment]
why noExitRuntime is false , and the thread exit？
