### ISSUE TITLE
OpenSSL dlopen abort error

### ISSUE THREAD

**Issue by StillWaters77** [emscripten-core/emscripten#14492]
Disclaimer: I already read the issue here with an similar name, but the solution there (adding the no-engine and no-dso parameters) did not work for me.

My plan was to have a ssl connection running on top of a emscripten websocket bridge so i can do end to end encryption like i did in my native project. I have a simple openssl server running (port 7777) and also the websocket_to_posix_proxy (port 8088).

I successfuly compiled openssl with emscripten using the following script:

```
#!/bin/sh

OPENSSL="openssl-1.1.1d"

if [ -d ${OPENSSL} ]; then
  rm -rf ${OPENSSL}
fi

if [ ! -f ${OPENSSL}.tar.gz ]; then
  curl -O https://www.openssl.org/source/${OPENSSL}.tar.gz
fi

tar xf ${OPENSSL}.tar.gz
cd ${OPENSSL} || exit 1

emconfigure ./Configure \
  linux-generic64 \
  no-asm \
  no-engine \
  no-hw \
  no-weak-ssl-ciphers \
  no-dtls \
  no-shared \
  no-dso \
  --prefix=$EMSCRIPTEN/system

sed -i 's|^CROSS_COMPILE.*$|CROSS_COMPILE=|g' Makefile
sed -i '/^CFLAGS/ s/$/ -D__STDC_NO_ATOMICS__=1/' Makefile
sed -i '/^CXXFLAGS/ s/$/ -D__STDC_NO_ATOMICS__=1/' Makefile

emmake make -j 1 build_generated libssl.a libcrypto.a

cd ..
```

Then i tried linking it statically so i can use the openssl api on top of posix socket.

```
em++ -std=c++17 \
-s ALLOW_MEMORY_GROWTH=1 \
main.cpp \
lib/libssl.a \
lib/libcrypto.a \
-I E:\DATA\Libs\openssl-1.1.1d\include \
-o test.html 
--shell-file html_template/shell_minimal.html \
-s EXPORTED_FUNCTIONS="['_main']" \
-s ASSERTIONS=1 \
-lwebsocket.js \
-s PROXY_POSIX_SOCKETS=1 \
-s USE_PTHREADS=1 \
-s PROXY_TO_PTHREAD=1 \
-static
```

My c++ code is just like in the sample "tests/websocket/tcp_echo_client.cpp".
But instead of sending data i try to open an tls connection:

```
    #ifdef __EMSCRIPTEN__
        bridgeSocket = emscripten_init_websocket_to_posix_socket_bridge("ws://localhost:8088");
        // Synchronously wait until connection has been established.
        uint16_t readyState = 0;
        do {
            emscripten_websocket_get_ready_state(bridgeSocket, &readyState);
            emscripten_thread_sleep(100);
        } while (readyState == 0);
    #endif

    //lookup_host("google.com");

    // Create socket
    int sock = socket(AF_INET, SOCK_STREAM, 0);
    if (sock == -1)
    {
        printf("Could not create socket");
        exit(1);
    }
    printf("Socket created: %d\n", sock);

    struct sockaddr_in server;
    server.sin_addr.s_addr = inet_addr("127.0.0.1");
    server.sin_family = AF_INET;
    server.sin_port = htons(7777);

    if (connect(sock, (struct sockaddr*)&server, sizeof(server)) < 0)
    {
        perror("connect failed. Error");
        return 1;
    }

    SSL_CTX* ctx = InitSSL_CTX();
    SSL* ssl = SSL_new(ctx);
    if (ssl == nullptr)
    {
        fprintf(stderr, "SSL_new() failed\n");
        exit(EXIT_FAILURE);
    }

    SSL_set_fd(ssl, sock);

    const int status = SSL_connect(ssl);
    if (status != 1)
    {
        SSL_get_error(ssl, status);
        ERR_print_errors_fp(stderr); //High probability this doesn't do anything
        fprintf(stderr, "SSL_connect failed with SSL_get_error code %d\n", status);
        exit(EXIT_FAILURE);
    }
```

I think the error im getting occurs at the `SSL_CTX* ctx = InitSSL_CTX();`.
The error is:
```
Pthread aborting at Error
    at abort (http://localhost/test/test.js:1:24436)
    at _dlopen (http://localhost/test/test.js:1:103187)
    at http://localhost/test/test.wasm:wasm-function[1046]:0x55753
    ...
```

and also:
```
Uncaught RuntimeError: abort(To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking) at Error
    at jsStackTrace (test.js:1)
    at stackTrace (test.js:1)
    at abort (test.js:1)
    at _dlopen (test.js:1)
    ...
```

Also, i removed the -no-threads option from the openssl build script because i got a thread error. I dont know if that was the right way to do it and maybe this also has something to do with the problem im facing right now.

**Comment by sbc100** [comment]
I would recommend trying to remove all the use of `dlopen` and threading if you possibly can.

To find out where the dlopen call is coming from you can link with `--profiling-funcs` which will give you function names in your backtraces (as would `-g` or `--profiling` but `--profiling-funcs` is the most light weight way to enable that).

**Comment by StillWaters77** [comment]
Thanks for the quick reply.
Im not doing anything with dlopen and i tried to compile openssl so that it does not use dlopen, atleast thats what i thought.
I tried compiling openssl for and only for static linking.
I also cannot really compile it without multithreading because if i specify the `no-threads` flag in the openssl compilation, i cant compile my emscripten project anymore. The error is:
`wasm-ld: error: --shared-memory is disallowed by ssl_cert.o because it was not compiled with 'atomics' or 'bulk-memory' features.`
As in the documentation of emscripten stated i compile my project with the following options so i can use websockets and posix sockets:
`-s PROXY_POSIX_SOCKETS=1 -s USE_PTHREADS=1 -s PROXY_TO_PTHREAD=1`
It seems like it is necessary to compile with pthreads and i think thats why i also need to compile openssl with multithreading enabled (no `no-threads` flag).

Using the `--profiling-funcs` i get the following stacktrace:
```
test.worker.js:1 Uncaught RuntimeError: abort(To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking) at Error
    at jsStackTrace (test.js:1)
    at stackTrace (test.js:1)
    at abort (test.js:1)
    at _dlopen (test.js:1)
    at dlfcn_globallookup (test.wasm:0x5585a)
    at rand_drbg_get_entropy (test.wasm:0xb1dd4)
    at RAND_DRBG_instantiate (test.wasm:0xb0e67)
    at do_rand_drbg_init_ossl_ (test.wasm:0xb1850)
    at __pthread_once (test.wasm:0xea891)
    at CRYPTO_THREAD_run_once (test.wasm:0xca966)
    at abort (test.js:1)
    at _dlopen (test.js:1)
    at dlfcn_globallookup (test.wasm:0x5585a)
    at rand_drbg_get_entropy (test.wasm:0xb1dd4)
    at RAND_DRBG_instantiate (test.wasm:0xb0e67)
    at do_rand_drbg_init_ossl_ (test.wasm:0xb1850)
    at __pthread_once (test.wasm:0xea891)
    at CRYPTO_THREAD_run_once (test.wasm:0xca966)
    at drbg_bytes (test.wasm:0xb19c8)
    at RAND_bytes (test.wasm:0xb297e)
```

Maybe that means that im somehow trying to link openssl dynamically and that it is trying to load it at runtime?
If so, how can i compile my project in a way that no dynamic linking happens

**Comment by sbc100** [comment]
From the stack trace you can see that `rand_drbg_get_entropy` is trying to call `dlopen`... you need to see if you can find a way to configure it not to do that.
