### ISSUE TITLE
Terser "cannot read property print of undefined"

### ISSUE THREAD

**Issue by hoodmane** [emscripten-core/emscripten#14525]
I've been getting the following error during linking very recently. It occurs both with emsdk version 20.0.16 and 20.0.24.
```
/src/emsdk/emsdk/upstream/emscripten/third_party/terser/terser.js:6956
        self.right.print(output);
                   ^

TypeError: Cannot read property 'print' of undefined
    at /src/emsdk/emsdk/upstream/emscripten/third_party/terser/terser.js:6956:20
    at doit (/src/emsdk/emsdk/upstream/emscripten/third_party/terser/terser.js:5999:13)
    at AST_Binary.<anonymous> (/src/emsdk/emsdk/upstream/emscripten/third_party/terser/terser.js:6006:13)
    at /src/emsdk/emsdk/upstream/emscripten/third_party/terser/terser.js:6857:22
    at Array.forEach (<anonymous>)
    at /src/emsdk/emsdk/upstream/emscripten/third_party/terser/terser.js:6855:23
    at Object.with_parens (/src/emsdk/emsdk/upstream/emscripten/third_party/terser/terser.js:5765:19)
    at /src/emsdk/emsdk/upstream/emscripten/third_party/terser/terser.js:6854:16
    at doit (/src/emsdk/emsdk/upstream/emscripten/third_party/terser/terser.js:5999:13)
    at AST_Call.<anonymous> (/src/emsdk/emsdk/upstream/emscripten/third_party/terser/terser.js:6006:13)
em++: error: '/src/emsdk/emsdk/node/14.15.5_64bit/bin/node /src/emsdk/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/emscripten_temp_sfcafjzx/pyodide.asm.js
```

I can make it go away by commenting out the following lines in the definition of `phase_binaryen` in `emcc.py`:
```
      final_js = building.minify_wasm_js(js_file=final_js,
                                          wasm_file=wasm_target,
                                          expensive_optimizations=will_metadce(),
                                          minify_whitespace=minify_whitespace() and not options.use_closure_compiler,
                                          debug_info=intermediate_debug_info)
```

**Comment by kripken** [comment]
Perhaps you are hitting a bug in terser. If this isn't a regression from an earlier version, can you provide a testcase?

**Comment by kleisauke** [comment]
Noticed the same when testing https://github.com/emscripten-core/emscripten/issues/11066#issuecomment-866901127. Here's a reduced test case:
```c
#include <emscripten.h>

EM_JS(int, test, (), {
  var bigint = 1 & 0xffffffffn;
  //var bigint = 1 & BigInt(0xffffffff);
  return bigint;
});

int main() {
    test();
    return 0;
}
```

```bash
emcc -O2 test.c
```

Looks like it's failing on that BigInt's `n`-suffix.

**Comment by hoodmane** [comment]
Thanks @kleisauke! I hadn't realized it was the BigInt suffix causing the trouble. For now I can just avoid that syntax.

**Comment by kleisauke** [comment]
This looks like a duplicate of issue https://github.com/emscripten-core/emscripten/issues/13297.
