### ISSUE TITLE
Assertion failed:native function 'Start' called before runtime initialization

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#14581]
i compile the c file to decoder.js and load it in test.html

```
function getScirpt (url) {
        return new Promise ((resolve, reject) => {
            const el = document.createElement('script')
            el.type = 'text/javascript'
            el.onload = () => {
            window.Module['onRuntimeInitialized'] = () => {
               this._decoderLoaded = true;
               console.log("decoder.js load end");
               };
            resolve()
            }
            el.src = url
            document.body.append(el)
        })
    }
function start() {		 
        Promise.all([getScirpt(`Decoder.js`)]).then(() => {
		    Module._Start();		
		})		
}
```
then  On some computers, you'll get an error:
```
Decoder.js:1556 Assertion failed: native function `Start` called before runtime initialization
abort @ Decoder.js:1556
Decoder.js:1572 Uncaught RuntimeError: abort(Assertion failed: native function `Start` called before runtime initialization) at Error
    at jsStackTrace (http://localhost:9090/Decoder.js:2201:19)
    at stackTrace (http://localhost:9090/Decoder.js:2224:16)
    at abort (http://localhost:9090/Decoder.js:1561:44)
    at assert (http://localhost:9090/Decoder.js:743:5)
    at Object._Start (http://localhost:9090/Decoder.js:1613:5)
    at abort (http://localhost:9090/Decoder.js:1567:11)
    at assert (http://localhost:9090/Decoder.js:743:5)
    at Object._Start (http://localhost:9090/Decoder.js:1613:5)
    at start (http://localhost:9090/test_Timer.html:303:19)
```

**Comment by sbc100** [comment]
You need to put your `resolve()` call inside the `onRuntimeInitialized` function so that the promise is not resolved until the module is ready to be used.

**Comment by sbc100** [comment]
@RReverser / @kripken  what is the pattern we should recommend here?   If a user wants a promise should we recommend `MODULARLIZE` in that case or is there an easy way to get a promise from `onRuntimeInitialized` out of the box?

**Comment by kripken** [comment]
In general, yes, using the promise from Modularize may be simplest. Modularize in general is a good idea, and perhaps should have been the default, but isn't for historical reasons (JS VMs used to run it slowly).
