### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#14593]
`system_libs:INFO: retrieving port: freetype from https://github.com/emscripten-ports/FreeType/archive/version_1.zip
Traceback (most recent call last):
  File "/home/hyde/emsdk/upstream/emscripten/tools/system_libs.py", line 1808, in retrieve
    import requests
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyde/emsdk/upstream/emscripten/emcc.py", line 3738, in <module>
    sys.exit(main(sys.argv))
  File "/home/hyde/emsdk/upstream/emscripten/emcc.py", line 3731, in main
    ret = run(args)
  File "/home/hyde/emsdk/upstream/emscripten/emcc.py", line 1090, in run
    phase_calculate_system_libraries(state, linker_arguments, linker_inputs, newargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/hyde/emsdk/upstream/emscripten/emcc.py", line 2425, in phase_calculate_system_libraries
    extra_files_to_link += system_libs.get_ports_libs(settings)
  File "/home/hyde/emsdk/upstream/emscripten/tools/system_libs.py", line 1937, in get_ports_libs
    ret += [f for f in port.get(Ports, settings, shared) if not f.endswith('.txt')]
  File "/home/hyde/emsdk/upstream/emscripten/tools/ports/freetype.py", line 19, in get
    ports.fetch_project('freetype', 'https://github.com/emscripten-ports/FreeType/archive/' + TAG + '.zip', 'FreeType-' + TAG, sha512hash=HASH)
  File "/home/hyde/emsdk/upstream/emscripten/tools/system_libs.py", line 1857, in fetch_project
    retrieve()
  File "/home/hyde/emsdk/upstream/emscripten/tools/system_libs.py", line 1813, in retrieve
    f = urlopen(url)
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>
Makefile:29: recipe for target 'SuperRender.js' failed
make: *** [SuperRender.js] Error 1
`

when update the EmscriptenV2.0.21，there is error ?

**Comment by sbc100** [comment]
If you run `source emsdk_env.sh`, it should configure emscripten to use the python version shipped with emsdk which should not have the certificate issue that you are seeing with the version of python in `/usr/local/lib/python3.6`. 

If emsdk is correctly configured when `/usr/local/lib/python3.6` should not appear anywhere in the error message.

**Comment by yangfangfang1204** [comment]
yes ,update the python version.
