### ISSUE TITLE
ReferenceError: ___sys_statfs64 is not defined

### ISSUE THREAD

**Issue by adamsitnik** [emscripten-core/emscripten#14602]
Hi!

Disclaimer: I am very new to WASM, so I might be doing something wrong.

When trying to run following code:

```c
int64_t SystemNative_GetFileSystemType(int32_t fd)
{
    int statfsRes;
    struct statfs statfsArgs;
    while ((statfsRes = fstatfs(fd, &statfsArgs)) == -1 && errno == EINTR) ;
    return statfsRes == -1 ? (int64_t)-1 : (int64_t)statfsArgs.f_type;
}
```

I get the following error:

```log
[09:00:19] info: ABORT: ReferenceError: ___sys_statfs64 is not defined
[09:00:19] info: Stacktrace:
[09:00:19] info: 
[09:00:19] info: Error
[09:00:19] info:     at Object.onAbort (runtime.js:219:13)
[09:00:19] info:     at abort (dotnet.js:1:13505)
[09:00:19] info:     at ___sys_fstatfs64 (dotnet.js:1:91616)
[09:00:19] info:     at <anonymous>:wasm-function[8613]:0x1aa7c5
[09:00:19] info:     at <anonymous>:wasm-function[5822]:0x13df12
[09:00:19] info:     at <anonymous>:wasm-function[2271]:0x6734c
[09:00:19] info:     at <anonymous>:wasm-function[6836]:0x168617
[09:00:19] info:     at <anonymous>:wasm-function[6652]:0x15f88d
[09:00:19] info:     at <anonymous>:wasm-function[3454]:0xacd2b
[09:00:19] info:     at <anonymous>:wasm-function[472]:0x10f91
[09:00:19] info:     at <anonymous>:wasm-function[6288]:0x14f9af
[09:00:19] info:     at <anonymous>:wasm-function[2546]:0x7e81a
[09:00:19] info:     at <anonymous>:wasm-function[2271]:0x66bfb
[09:00:19] info:     at <anonymous>:wasm-function[6836]:0x168617
[09:00:19] info:     at <anonymous>:wasm-function[6652]:0x15f88d
[09:00:19] info:     at <anonymous>:wasm-function[3454]:0xacd2b
[09:00:19] info:     at <anonymous>:wasm-function[665]:0x1592e
[09:00:19] info:     at eb (<anonymous>:wasm-function[6549]:0x15c2f0)
[09:00:19] info:     at Object.Module._mono_wasm_invoke_method [as invoke_method] (dotnet.js:1:211906)
[09:00:19] info:     at Object._call_method_with_converted_args (dotnet.js:1:178354)
[09:00:19] info:     at Object.call_method (dotnet.js:1:176827)
[09:00:19] info:     at dotnet.js:1:184566
[09:00:19] info:     at Object.call_assembly_entry_point (dotnet.js:1:184799)
[09:00:19] info:     at Object.init (runtime.js:356:24)
[09:00:19] info:     at Object.Module.config.loaded_cb (runtime.js:243:8)
[09:00:19] info:     at Object._finalize_startup (dotnet.js:1:136118)
[09:00:19] info:     at onPendingRequestComplete (dotnet.js:1:137317)
[09:00:19] info:     at processFetchResponseBuffer (dotnet.js:1:137637)
[09:00:19] info: Process v8 exited with 1
```

**Comment by vadimkantorov** [comment]
I also started to have this problem in recent Emscripten SDK's while compiling TexLive: https://github.com/emscripten-core/emscripten/issues/14777

**Comment by sbc100** [comment]
> I also started to have this problem in recent Emscripten SDK's while compiling TexLive: #14777

Do you have any idea why this might have started happening for your only recently?  As far as I can tell the dependency has always been missing.   I tried the simple test case and the issue still exists back in 2.0.21 at least.
