### ISSUE TITLE
firefox hangs when using fetch api

### ISSUE THREAD

**Issue by PowerNow** [emscripten-core/emscripten#14925]
Hi, I just saw that Mozilla Firefox hangs by using emscripten's fetch api. On Chrome, Edge and Opera everything works correctly.

When using 

```
string filepath = m_pCtrl->m_dir + Lib::filesFileName(tile.lat, tile.lon, Files::Zlip);
emscripten_fetch_attr_t attr;
emscripten_fetch_attr_init(&attr);
strcpy(attr.requestMethod, "GET");
attr.attributes = EMSCRIPTEN_FETCH_LOAD_TO_MEMORY;
attr.onsuccess = &Files::dwldFinished;
attr.onerror = &Files::dwldFailed;
emscripten_fetch(&attr, filepath.c_str());
```
the functions dwldFinished() or dwldFailed() never called altough the status of the GET request is 200 OK.

I found this report https://github.com/emscripten-core/emscripten/issues/12805. 

Does someone know the reason or is there already a fallback solution out there?

Thanks...

**Comment by sbc100** [comment]
We have several tests the use `emscripten_fetch` and they seem to work fine under firefox when we run them during our CI. 

Can you try running `./tests/runner browser.test_fetch_to_memory --browser=firefox` to see if it works for you.

The code for this test lives in `tests/fetch/to_memory.cpp`.

Can you include a full example of a program that fails under firefox so we can try to reproduce it?

**Comment by PowerNow** [comment]
Hi Sam, unfortunately this testcase doesn't work. I don't know why...

C:\Programs\emscripten-main\tests>runner browser.test_fetch_to_memory
--browser=firefox
runner:WARNING: use EMTEST_ALL_ENGINES=1 in the env to run against all JS
engines, which is slower but provides more coverage
posixtestsuite not found (run git submodule update --init?)
WARNING: no 'numpy' module, HyBi protocol will be slower
WARNING: no 'resource' module, daemonizing is disabled
Test suites:
['test_browser']
Running test_browser: (1 tests)
(checking sanity from test runner)
shared:INFO: (Emscripten: Running sanity checks)
[Browser harness server on process 17224]
common:INFO: Using Emscripten browser: ['firefox']
ERROR

======================================================================
ERROR: setUpClass (test_browser.browser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Programs\emscripten-main\tests\test_browser.py", line 161, in
setUpClass
    super().setUpClass()
  File "C:\Programs\emscripten-main\tests\common.py", line 1312, in
setUpClass
    cls.browser_open('http://localhost:%s/run_harness' % cls.port)
  File "C:\Programs\emscripten-main\tests\common.py", line 1297, in
browser_open
    subprocess.Popen(browser_args + [url])
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht
finden

----------------------------------------------------------------------
Ran 0 tests in 0.129s

FAILED (errors=1)
Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "C:\Programs\emscripten-main\tests\common.py", line 1248, in
harness_server_func
    httpd.serve_forever() # test runner will kill us
  File "socketserver.py", line 232, in serve_forever
  File "selectors.py", line 324, in select
  File "selectors.py", line 315, in _select
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "multiprocessing\util.py", line 357, in _exit_function
  File "multiprocessing\process.py", line 149, in join
  File "multiprocessing\popen_spawn_win32.py", line 108, in wait
KeyboardInterrupt
Batchvorgang abbrechen (J/N)?

What exactly step by step I have to do to run this testcase?

https://discovar.top
This is the project with the problem on mozilla desktop/mobile browser.
Click on the START button and the webassembly plugin is loaded and started.
Try it with Chrome, Edge, Opera and Mozilla.

Since it's a large project it's not so trivial to extract only the relevant
code. I will think about it.
Before I do this I want to run your testcase with to_memory.cpp file. So I
will wait for your instructions.

Best regards,
Armin



Am Mo., 23. Aug. 2021 um 21:10 Uhr schrieb Sam Clegg <
***@***.***>:

**Comment by sbc100** [comment]
try `runner browser.test_fetch_to_memory --browser=$(which firefox)`.. (or specify the full path your browser)

**Comment by PowerNow** [comment]
This --browser attribute does not work, no matter what i use
--browser=$(which firefox)
--browser=$(91.0.1 (64-Bit))
--browser=$(C:\Program Files\Mozilla Firefox)
--browser=$("C:\Program Files\Mozilla Firefox")

But if I set the firefox to my system default browser i can use only
runner browser.test_fetch_to_memory

Here is the result

C:\Programs\emscripten-main\tests>runner browser.test_fetch_to_memory
runner:WARNING: use EMTEST_ALL_ENGINES=1 in the env to run against all JS
engines, which is slower but provides more coverage
posixtestsuite not found (run git submodule update --init?)
WARNING: no 'numpy' module, HyBi protocol will be slower
WARNING: no 'resource' module, daemonizing is disabled
Test suites:
['test_browser']
Running test_browser: (1 tests)
(checking sanity from test runner)
shared:INFO: (Emscripten: Running sanity checks)
[Browser harness server on process 3784]
common:INFO: Using default system browser

Running the browser tests. Make sure the browser allows popups from
localhost.

test_fetch_to_memory (test_browser.browser) ... 127.0.0.1 - - [25/Aug/2021
09:14:11] code 404, message File not found
127.0.0.1 - - [25/Aug/2021 09:14:11] code 404, message File not found
WASM=0
127.0.0.1 - - [25/Aug/2021 09:14:12] code 404, message File not found
WASM=0
WASM=0
ok
[Browser harness server terminated]

----------------------------------------------------------------------
Ran 1 test in 9.996s

OK

Which message file is not found?


Am Di., 24. Aug. 2021 um 20:02 Uhr schrieb Sam Clegg <
***@***.***>:

**Comment by PowerNow** [comment]
I enclosed the problem now to the following code.

void downloadSucceeded(emscripten_fetch_t *fetch)
{    printf("downloadSucceeded\n");
     emscripten_fetch_close(fetch);
}

void downloadFailed(emscripten_fetch_t *fetch) {
  printf("Downloading %s failed, HTTP failure status code: %d.\n", fetch->
url, fetch->status);
  emscripten_fetch_close(fetch);
}

int main() {
    printf("main\n");

    EM_ASM(
        FS.mkdir("/geo");

        FS.mount(IDBFS, {}, "/geo");
        // sync indexedDB with emscripten filesystem
        FS.syncfs(true, function (err) { assert(!err); });
    );

    emscripten_fetch_attr_t attr;
    emscripten_fetch_attr_init(&attr);
    strcpy(attr.requestMethod, "GET");
    attr.attributes = EMSCRIPTEN_FETCH_LOAD_TO_MEMORY;
    attr.onsuccess = downloadSucceeded;
    attr.onerror = downloadFailed;
    emscripten_fetch(&attr, "http://192.168.0.200/filename.zlip");
}

I built with

emcc -s INITIAL_MEMORY=640000KB code.cpp -o index.html --shell-file
shell.html -lidbfs.js -s ASSERTIONS=
1 -s FORCE_FILESYSTEM=1 -s FULL_ES2=1 -s USE_SDL=2 -s FETCH=1
 -s NO_EXIT_RUNTIME=1 -s EXPORTED_FUNCTIONS="['_main']"
 -s EXPORTED_RUNTIME_METHODS="['cwrap']" -O3

This works with Chrome, Edge, and Opera, not with Firefox. If one deletes
the EM_ASM() block then the fetch also works in Firefox.

It seems so that the FS. blocks somehow the emscripten's fetch module in
firefox

Do you have an idea?


Am Di., 24. Aug. 2021 um 20:02 Uhr schrieb Sam Clegg <
***@***.***>:

**Comment by sbc100** [comment]
> This --browser attribute does not work, no matter what i use --browser=$(which firefox) --browser=$(91.0.1 (64-Bit)) --browser=$(C:\Program Files\Mozilla Firefox) --browser=$("C:\Program Files\Mozilla Firefox") 

Sorry, it you are on windows then the `$()` syntax won't work.  That is bash syntax for running a subprocess.  You would want something more like `--browser="C:\Program Files\Mozilla Firefox"`.  However it sounds like you found  way to make it work by setting the system browser.
