### ISSUE TITLE
Segmentation fault when using SDL >= 1 with assertions on

### ISSUE THREAD

**Issue by VictorQueiroz** [emscripten-core/emscripten#15062]
I wonder why this is happening. Not sure if this is a problem with SDL implementation or an EMScripten bug. The stack is below:

```
app.html:1246 exception thrown: Error: abort(segmentation fault) at Error
    at jsStackTrace (http://localhost:8080/app.js:153883:14)
    at stackTrace (http://localhost:8080/app.js:153898:11)
    at abort (http://localhost:8080/app.js:152597:43)
    at segfault (http://localhost:8080/app.js:151995:2)
    at SAFE_HEAP_LOAD_i32_1_U_1 (http://localhost:8080/app.js:148818:3)
    at __memcpy (http://localhost:8080/app.js:144643:35)
    at __sigaction (http://localhost:8080/app.js:146614:2)
    at SDL_QuitInit (http://localhost:8080/app.js:135147:3)
    at SDL_EventsInit (http://localhost:8080/app.js:150584:2)
    at SDL_InitSubSystem (http://localhost:8080/app.js:102450:10),Error: abort(segmentation fault) at Error
    at jsStackTrace (http://localhost:8080/app.js:153883:14)
    at stackTrace (http://localhost:8080/app.js:153898:11)
    at abort (http://localhost:8080/app.js:152597:43)
    at segfault (http://localhost:8080/app.js:151995:2)
    at SAFE_HEAP_LOAD_i32_1_U_1 (http://localhost:8080/app.js:148818:3)
    at __memcpy (http://localhost:8080/app.js:144643:35)
    at __sigaction (http://localhost:8080/app.js:146614:2)
    at SDL_QuitInit (http://localhost:8080/app.js:135147:3)
    at SDL_EventsInit (http://localhost:8080/app.js:150584:2)
    at SDL_InitSubSystem (http://localhost:8080/app.js:102450:10)
    at abort (http://localhost:8080/app.js:152599:10)
    at segfault (http://localhost:8080/app.js:151995:2)
    at SAFE_HEAP_LOAD_i32_1_U_1 (http://localhost:8080/app.js:148818:3)
    at __memcpy (http://localhost:8080/app.js:144643:35)
    at __sigaction (http://localhost:8080/app.js:146614:2)
    at SDL_QuitInit (http://localhost:8080/app.js:135147:3)
    at SDL_EventsInit (http://localhost:8080/app.js:150584:2)
    at SDL_InitSubSystem (http://localhost:8080/app.js:102450:10)
    at SDL_Init (http://localhost:8080/app.js:151506:9)
    at Window__init_28Window__29 (http://localhost:8080/app.js:42240:35)
```

I'm using the following flags:

```
-s TRACE_WEBGL_CALLS=1 -s GL_ASSERTIONS=1
-s GL_DEBUG=1 -s GL_TESTING=1 -s ASSERTIONS=2
-s SAFE_HEAP=1
```

**Comment by sbc100** [comment]
I you create simple example that displays this issue?

Or at least can you share the full link settings?  From the stacktrace is it looks like you are building with `WASM=0` since all the function look like they are in JS.   This this reproduce in wasm too?

**Comment by sbc100** [comment]
I have a local repro case now.
