### ISSUE TITLE
Null pointer dereference in sigaction means SDL_Init fails with address sanitizer or SAFE_MEMORY

### ISSUE THREAD

**Issue by fflexo** [emscripten-core/emscripten#15175]
Given the simple test program below:

```
#include <emscripten.h>
#include <SDL2/SDL.h>

int main(void) {
	SDL_Init(SDL_INIT_VIDEO|SDL_INIT_JOYSTICK);	
}
```
Built with this command:

```
docker run --rm -v $(pwd):/src -u $(id -u):$(id -g) emscripten/emsdk emcc  --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.30 (f782b50a7f8dded7cd0e2c7ee4fed41ab743f5c0)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

docker run --rm -v $(pwd):/src -u $(id -u):$(id -g) emscripten/emsdk emcc  -s ALLOW_MEMORY_GROWTH=1 -s ASYNCIFY=1 -s SDL2_IMAGE_FORMATS=[png] -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s USE_SDL_TTF=2  -Wall -Wextra --emrun -s DEMANGLE_SUPPORT=1 -s ASSERTIONS=2  -fsanitize=address,undefined -g -Wall -Wextra test.c -o test.html
```

We explode in ASAN (but also SAFE_HEAP reports an error too, it's just that ASAN is much clearer):

```
Heap resize call from 308871168 to 370671616 took 0 msecs. Success: true test.html:1237:21
================================================================= test.html:1246:19
==42==ERROR: AddressSanitizer: null-pointer-dereference on address 0x00000001 at pc 0x002e836c bp 0x10978950 sp 0x10978950 test.html:1246:19
READ of size 140 at 0x00000001 thread T0 test.html:1246:19
    #0 0x2e836c in __sanitizer::StackTrace::GetCurrentPc()+0x2e836c (http://localhost:6931/test.wasm+0x2e836c) test.html:1246:19
    #1 0x2816b9 in __asan_memcpy+0x2816b9 (http://localhost:6931/test.wasm+0x2816b9) test.html:1246:19
    #2 0x244c80 in __sigaction+0x244c80 (http://localhost:6931/test.wasm+0x244c80) test.html:1246:19
    #3 0x20852 in SDL_QuitInit+0x20852 (http://localhost:6931/test.wasm+0x20852) test.html:1246:19
    #4 0x1b529 in SDL_EventsInit+0x1b529 (http://localhost:6931/test.wasm+0x1b529) test.html:1246:19
    #5 0x4f1a in SDL_InitSubSystem+0x4f1a (http://localhost:6931/test.wasm+0x4f1a) test.html:1246:19
    #6 0x5567 in SDL_Init+0x5567 (http://localhost:6931/test.wasm+0x5567) test.html:1246:19
    #7 0x4b1e in __original_main+0x4b1e (http://localhost:6931/test.wasm+0x4b1e) test.html:1246:19
    #8 0x4c9c in main+0x4c9c (http://localhost:6931/test.wasm+0x4c9c) test.html:1246:19
    #9 0x800022de in instrumentWasmExports/</ret[x] http://localhost:6931/test.js:8926:24 test.html:1246:19
    #10 0x800004ed in createExportWrapper/< http://localhost:6931/test.js:1261:20 test.html:1246:19
    #11 0x800029ce in callMain http://localhost:6931/test.js:10702:26 test.html:1246:19
    #12 0x800029ef in doRun http://localhost:6931/test.js:10735:29 test.html:1246:19
    #13 0x800029f8 in run/< http://localhost:6931/test.js:10744:4 test.html:1246:19
<empty string> test.html:1246:19
Address 0x00000001 is located in the shadow gap area. test.html:1246:19
SUMMARY: AddressSanitizer: null-pointer-dereference (http://localhost:6931/test.wasm+0x2e836b) in __sanitizer::StackTrace::GetCurrentPc()+0x2e836b test.html:1246:19
==42==ABORTING test.html:1246:19
```

Investigating some more we can see that SDL_QuitInit will eventually call this function:

```
static void
SDL_EventSignal_Init(const int sig)
{
#ifdef HAVE_SIGACTION
    struct sigaction action;

    sigaction(sig, NULL, &action);
```

Which in turn calls sigaction with the 2nd parameter NULL. The manpage strongly implies that NULL is an acceptable value for the 2nd parameter, however the implementation of sigaction in libc seems to look like this:

```
    12	int __sigaction(int sig, const struct sigaction *restrict sa, struct sigaction *restrict old) {
    13	  if (sig < 0 || sig >= _NSIG) {
    14	    errno = EINVAL;
    15	    return -1;
    16	  }
       
    17	  if (old) {
    18	    *old = __sig_actions[sig];
    19	  }
       
    20	  __sig_actions[sig] = *sa;
    21	  return 0;
    22	}
```

Which will correctly test if old is non-NULL, but unconditionally dereference the 2nd parameter, sa even if it is NULL, causing our error.

We can work around it with:

```
SDL_SetHint(SDL_HINT_NO_SIGNAL_HANDLERS, "1");
```

but it would be nice to get a proper fix here...

**Comment by fflexo** [comment]
Whoops just found #15062
