### ISSUE TITLE
Nested emscripten_async_call() calls accumulate stack frames on log

### ISSUE THREAD

**Issue by msorvig** [emscripten-core/emscripten#15344]
The following code logs the stack using EM_LOG_C_STACK, and then makes a (nested) call to emscripten_async_call().

Expected behavior is that the stack log contains one instance of "foo()", even after repeated calls.
Actual behavior is that the stack log contains multiple instances of "foo()" after repeated calls.

As far as I can see the stack frames are actually freed, so it's just the stack trace which is incorrect.

```
void foo(void *)
{
    void *stack = alloca(10);
    emscripten_log(EM_LOG_C_STACK, "stack %p %p\n", stack, &stack);
    emscripten_async_call(foo, nullptr, 500);
}

int main(int argc, char **)
{
    emscripten_async_call(foo, nullptr, 500);
    return 0;
}

```

```
stack 0x500e40 0x500e58
    at foo(void*) (https://10.0.20.6:8000/tmp/log_stack/main.wasm:wasm-function[25]:0x8fc:0)
    at wrapper (https://10.0.20.6:8000/tmp/log_stack/main.js:2732:26)
    at callUserCallback (https://10.0.20.6:8000/tmp/log_stack/main.js:2045:3)
    at safeSetTimeout/< (https://10.0.20.6:8000/tmp/log_stack/main.js:2065:19)
    at setTimeout handler*safeSetTimeout (https://10.0.20.6:8000/tmp/log_stack/main.js:2063:9)
    at _emscripten_async_call (https://10.0.20.6:8000/tmp/log_stack/main.js:2735:17)
    at foo(void*) (https://10.0.20.6:8000/tmp/log_stack/main.wasm:wasm-function[25]:0x911:0)
    at wrapper (https://10.0.20.6:8000/tmp/log_stack/main.js:2732:26)
    at callUserCallback (https://10.0.20.6:8000/tmp/log_stack/main.js:2045:3)
    at safeSetTimeout/< (https://10.0.20.6:8000/tmp/log_stack/main.js:2065:19)
    at setTimeout handler*safeSetTimeout (https://10.0.20.6:8000/tmp/log_stack/main.js:2063:9)
    at _emscripten_async_call (https://10.0.20.6:8000/tmp/log_stack/main.js:2735:17)
    at foo(void*) (https://10.0.20.6:8000/tmp/log_stack/main.wasm:wasm-function[25]:0x911:0)
    at wrapper (https://10.0.20.6:8000/tmp/log_stack/main.js:2732:26)
    at callUserCallback (https://10.0.20.6:8000/tmp/log_stack/main.js:2045:3)
    at safeSetTimeout/< (https://10.0.20.6:8000/tmp/log_stack/main.js:2065:19)
    at setTimeout handler*safeSetTimeout (https://10.0.20.6:8000/tmp/log_stack/main.js:2063:9)
    at _emscripten_async_call (https://10.0.20.6:8000/tmp/log_stack/main.js:2735:17)
    at foo(void*) (https://10.0.20.6:8000/tmp/log_stack/main.wasm:wasm-function[25]:0x911:0)
    at wrapper (https://10.0.20.6:8000/tmp/log_stack/main.js:2732:26)
    at callUserCallback (https://10.0.20.6:8000/tmp/log_stack/main.js:2045:3)
    at safeSetTimeout/< (https://10.0.20.6:8000/tmp/log_stack/main.js:2065:19)
    at setTimeout handler*safeSetTimeout (https://10.0.20.6:8000/tmp/log_stack/main.js:2063:9)
    at _emscripten_async_call (https://10.0.20.6:8000/tmp/log_stack/main.js:2735:17)
    at foo(void*) (https://10.0.20.6:8000/tmp/log_stack/main.wasm:wasm-function[25]:0x911:0)
    at wrapper (https://10.0.20.6:8000/tmp/log_stack/main.js:2732:26)
    at callUserCallback (https://10.0.20.6:8000/tmp/log_stack/main.js:2045:3)
    at safeSetTimeout/< (https://10.0.20.6:8000/tmp/log_stack/main.js:2065:19)
    at setTimeout handler*safeSetTimeout (https://10.0.20.6:8000/tmp/log_stack/main.js:2063:9)
    at _emscripten_async_call (https://10.0.20.6:8000/tmp/log_stack/main.js:2735:17)
    at foo(void*) (https://10.0.20.6:8000/tmp/log_stack/main.wasm:wasm-function[25]:0x911:0)
    at wrapper (https://10.0.20.6:8000/tmp/log_stack/main.js:2732:26)
    at callUserCallback (https://10.0.20.6:8000/tmp/log_stack/main.js:2045:3)
    at safeSetTimeout/< (https://10.0.20.6:8000/tmp/log_stack/main.js:2065:19)
    at setTimeout handler*safeSetTimeout (https://10.0.20.6:8000/tmp/log_stack/main.js:2063:9)
    at _emscripten_async_call (https://10.0.20.6:8000/tmp/log_stack/main.js:2735:17)
    at foo(void*) (https://10.0.20.6:8000/tmp/log_stack/main.wasm:wasm-function[25]:0x911:0)
    at wrapper (https://10.0.20.6:8000/tmp/log_stack/main.js:2732:26)
    at callUserCallback (https://10.0.20.6:8000/tmp/log_stack/main.js:2045:3)
    at safeSetTimeout/< (https://10.0.20.6:8000/tmp/log_stack/main.js:2065:19)
    at setTimeout handler*safeSetTimeout (https://10.0.20.6:8000/tmp/log_stack/main.js:2063:9)
    at _emscripten_async_call (https://10.0.20.6:8000/tmp/log_stack/main.js:2735:17)
    at foo(void*) (https://10.0.20.6:8000/tmp/log_stack/main.wasm:wasm-function[25]:0x911:0)
    at wrapper (https://10.0.20.6:8000/tmp/log_stack/main.js:2732:26)
    at callUserCallback (https://10.0.20.6:8000/tmp/log_stack/main.js:2045:3)
    at safeSetTimeout/< (https://10.0.20.6:8000/tmp/log_stack/main.js:2065:19)
```

**Comment by msorvig** [comment]
This was probably caused by by Chromes "Asynchronous stack traces" feature. Sorry for the noise!
