### ISSUE TITLE
How save upload file  to workerfs and reading his ?

### ISSUE THREAD

**Issue by zababurinsv** [emscripten-core/emscripten#15343]
Sorry if the question is not very correct.
But I didn’t find information on how to do it.

* I create worker
`index.html`
```
<input type="file" id="upload" multiple/>

            <script>
            
            let worker = new Worker(new URL('./WORKERFS.mjs', import.meta.url), { type: "module" });
                 
            let input = document.querySelector('#upload')
            input.addEventListener('change', (e) => {
                 worker.postMessage(e.target.files)
            })
            
            </script>
```

* Init workerefs

```
            let Module = await init({ wasmBinary: bytecode })
            object.fs.worker = await Module.FS
            object.fs.api = await api.WORKERFS(object.fs.worker)
            object.fs.api.mkdir(mount);
            object.fs.api.mount(Module.FS.filesystems.WORKERFS, mount)
```

* Mount dir is 

```
let mount = await fs.mount(type, { files: [], blobs: [] }, dir)
```

Now i get file from html in worker

`worker.mjs`
```
(async ()=>{
        self.onmessage = async (events) => {
        let myFiles = null
        myFiles = events.data;
        myFiles.name = "file.txt";
        console.log('file----',myFiles)

        if(await workerfs.is.dir("/bigData")) {
                 // How can i write this file - ?
        }
    }
})()
```

How can i create methods for write add files in folder  ?

In documentation i see methods writeFile and writeFileData.
And if i try this method
```
            await workerfs.writeFile(`/bigData/${myFiles.name}`, myFiles) - ???
            console.log('folder:', await workerfs.readdir("/bigData")) - ???
```

I get error

```
code: "EPERM"
errno: 63
message: "Not super-user"
node: undefined
setErrno: ƒ (errno1)
stack: "Error\n    at new ErrnoError (http://localhost:4536/WORKERFS.4fa7ce34.js:5071:36)\n    at Object.mknod (http://localhost:4536/WORKERFS.4fa7ce34.js:3833:27)\n
```

**Comment by nkbai** [comment]
@zababurinsv did you resolved this problem?  I want visit a very large uploaded file from web assembly.
