### ISSUE TITLE
test_realpath_nodefs is failing (on windows only)

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#15468]
```
FAIL: test_realpath_nodefs (test_other.other)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\Lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\Lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\Lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "C:\b\s\w\ir\k\install\emscripten\tests\test_other.py", line 6270, in test_realpath_nodefs
    self.assertContained('Resolved: /working/TEST_NODEFS.txt', self.run_js('a.out.js'))
  File "C:\b\s\w\ir\k\install\emscripten\tests\common.py", line 698, in run_js
    self.fail('JS subprocess failed (%s): %s.  Output:\n%s' % (error.cmd, error.returncode, ret))
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\Lib\unittest\case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: JS subprocess failed (C:\b\s\w\ir\cache\builder\emscripten-releases\node-v14.15.5-win-x64\node.exe --stack-trace-limit=50 --unhandled-rejections=throw --trace-uncaught C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js): 7.  Output:
Aborted(Assertion failed: undefined)
Aborted(RuntimeError: Aborted(Assertion failed: undefined))
C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:141
      throw ex;
      ^

RuntimeError: Aborted(RuntimeError: Aborted(Assertion failed: undefined))
    at abort (C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:1515:11)
    at ___syscall_readlink (C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:4471:69)
    at <anonymous>:wasm-function[41]:0xf7a
    at <anonymous>:wasm-function[12]:0x774
    at main (<anonymous>:wasm-function[10]:0x3d7)
    at C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:1559:22
    at callMain (C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:5099:15)
    at doRun (C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:5156:23)
    at run (C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:5171:5)
    at runCaller (C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:5077:19)
    at removeRunDependency (C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:1488:7)
    at receiveInstance (C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:1648:5)
    at receiveInstantiationResult (C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:1665:5)
Thrown at:
    at abort (C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:1515:11)
    at ___syscall_readlink (C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:4471:69)
    at :1:3963
    at :1:1909
    at main (:1:984)
    at C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:1559:22
    at callMain (C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:5099:15)
    at doRun (C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:5156:23)
    at run (C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:5171:5)
    at runCaller (C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:5077:19)

```

**Comment by kripken** [comment]
This started with the musl upgrade it seems #13006

**Comment by sbc100** [comment]
So far I've discovered that due so a simplification in musl's `realpath.c` this test went from SYSCALLS_REQUIRE_FILESYSTEM=1 before to SYSCALLS_REQUIRE_FILESYSTEM=0 after the upgrade.    So it makes sense we would see failures when the filesystem was used.. but I'm trying to figure out why this would be windows only.

**Comment by sbc100** [comment]
Ooops, ignore that last comment.   It looks like we have `SYSCALLS_REQUIRE_FILESYSTEM=1` both before and after the upgrade.

**Comment by sbc100** [comment]
Found the root cause.  It seems that node under windows sometimes returns 'UNKNOWN' as the error code:

```
RuntimeError: Aborted(Assertion failed: unexpected node error code: UNKNOWN(Error: UNKNOWN: unknown error, readlink '.'))
    at abort (C:\Users\circleci\AppData\Local\Temp\tmps1u7wt4y\emscripten_test_other_bo0d_o_6\a.out.js:1515:11)
    at assert (C:\Users\circleci\AppData\Local\Temp\tmps1u7wt4y\emscripten_test_other_bo0d_o_6\a.out.js:700:5)
    at Object.convertNodeCode (C:\Users\circleci\AppData\Local\Temp\tmps1u7wt4y\emscripten_test_other_bo0d_o_6\a.out.js:2481:9)
    at Object.readlink (C:\Users\circleci\AppData\Local\Temp\tmps1u7wt4y\emscripten_test_other_bo0d_o_6\a.out.js:2655:44)
    at Object.readlink (C:\Users\circleci\AppData\Local\Temp\tmps1u7wt4y\emscripten_test_other_bo0d_o_6\a.out.js:3352:71)
    at Object.doReadlink (C:\Users\circleci\AppData\Local\Temp\tmps1u7wt4y\emscripten_test_other_bo0d_o_6\a.out.js:4381:22)
    at ___syscall_readlink (C:\Users\circleci\AppData\Local\Temp\tmps1u7wt4y\emscripten_test_other_bo0d_o_6\a.out.js:4469:23)
    at <anonymous>:wasm-function[41]:0xf7a
    at <anonymous>:wasm-function[12]:0x774
    at main (<anonymous>:wasm-function[10]:0x3d7)
```
