### ISSUE TITLE
Enable function names by default in all test suites?

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#15470]
Its pretty unhelpful to see reports from builders that look like this one: https://github.com/emscripten-core/emscripten/issues/15468

```
RuntimeError: Aborted(RuntimeError: Aborted(Assertion failed: undefined))
    at abort (C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:1515:11)
    at ___syscall_readlink (C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:4471:69)
    at <anonymous>:wasm-function[41]:0xf7a
    at <anonymous>:wasm-function[12]:0x774
    at main (<anonymous>:wasm-function[10]:0x3d7)
    at C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:1559:22
    at callMain (C:\b\s\w\ir\tmp\t\tmp3j_wc7cp\emscripten_test_other_86z_eylk\a.out.js:5099:15)
```

Having the names of the intervening functions would make diagnostics much faster.  

I believe the cheapest way to do this is to run all tests with `--profiling-functions` by default.  (some tests may want to opt out of course).

**Comment by kripken** [comment]
That's a possibility, but the downside is that it means we test using different flags than users run. Maybe the risk isn't large, but it's still a little worrying to me.

How about adding an easy way to make a test run with that flag? Not quite as useful, but could still help.

**Comment by sbc100** [comment]
How about making `--profiling-funcs` (i.e. keep name section) the default for `-O0` builds?

**Comment by kripken** [comment]
Interesting idea for `-O0`, yeah, that seems reasonable since it can help our debugging and it isn't a build that users ship. +1

**Comment by sbc100** [comment]
Here is a more useful backtrace from the same test failure running after #15472 :

```
untimeError: Aborted(Assertion failed: undefined)
    at abort (C:\Users\circleci\AppData\Local\Temp\tmp807h304a\emscripten_test_other_a92yb1pg\a.out.js:1515:11)
    at assert (C:\Users\circleci\AppData\Local\Temp\tmp807h304a\emscripten_test_other_a92yb1pg\a.out.js:700:5)
    at Object.convertNodeCode (C:\Users\circleci\AppData\Local\Temp\tmp807h304a\emscripten_test_other_a92yb1pg\a.out.js:2481:9)
    at Object.readlink (C:\Users\circleci\AppData\Local\Temp\tmp807h304a\emscripten_test_other_a92yb1pg\a.out.js:2655:44)
    at Object.readlink (C:\Users\circleci\AppData\Local\Temp\tmp807h304a\emscripten_test_other_a92yb1pg\a.out.js:3352:71)
    at Object.doReadlink (C:\Users\circleci\AppData\Local\Temp\tmp807h304a\emscripten_test_other_a92yb1pg\a.out.js:4381:22)
    at ___syscall_readlink (C:\Users\circleci\AppData\Local\Temp\tmp807h304a\emscripten_test_other_a92yb1pg\a.out.js:4469:23)
    at <anonymous>:wasm-function[41]:0xf7a
    at <anonymous>:wasm-function[12]:0x774
    at main (<anonymous>:wasm-function[10]:0x3d7)
 ```
