### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '--max_old_space_size=8192'

### ISSUE THREAD

**Issue by lovasoa** [emscripten-core/emscripten#15545]
Hello, I'm trying to compile the latest version of https://github.com/ERGO-Code/HiGHS with the latest emscripten from debian stable. I ran into the following error, which looks like a bug : 

```
Traceback (most recent call last):
  File "/usr/share/emscripten/emcc.py", line 3292, in <module>
    sys.exit(main(sys.argv))
  File "/usr/share/emscripten/emcc.py", line 3285, in main
    ret = run(args)
  File "/usr/share/emscripten/emcc.py", line 2156, in run
    post_link(options, wasm_target, wasm_target, target)
  File "/usr/share/emscripten/emcc.py", line 2253, in post_link
    do_binaryen(target, options, wasm_target)
  File "/usr/share/emscripten/emcc.py", line 2774, in do_binaryen
    run_closure_compiler()
  File "/usr/share/emscripten/emcc.py", line 2769, in run_closure_compiler
    final_js = building.closure_compiler(final_js, pretty=not minify_whitespace(),
  File "/usr/share/emscripten/tools/building.py", line 1027, in closure_compiler
    proc = run_process(cmd, stderr=PIPE, check=False, env=env)
  File "/usr/share/emscripten/tools/shared.py", line 94, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--max_old_space_size=8192'
```

The following line seems to be inserting `--max_old_space_size=8192` as the closure command program name instead of an argument : 

https://github.com/emscripten-core/emscripten/blob/main/tools/building.py#L673

**Comment by lovasoa** [comment]
Fixing the argument position makes emscripten fail with : 

```
building:ERROR: Closure compiler run failed:

building:ERROR: "--max_old_space_size" is not a valid option
 --accept_const_keyword                 : Allows usage of const keyword.
                                          (default: false)
 --angular_pass                         : Generate $inject properties for
                                          AngularJS for functions annotated
                                          with @ngInject (default: false)
 --charset VAL                          : Input and output charset for all
                                          files. By default, we accept UTF-8 as
                                          input and output US_ASCII (default: )
 --closure_entry_point VAL              : Entry points to the program. Must be
                                          goog.provide'd symbols. Any
                                          goog.provide'd symbols that are not a
                                          transitive dependency of the entry
                                          points will be removed. Files without
                                          goog.provides, and their
                                          dependencies, will always be left in.
                                          If any entry points are specified,
                                          then the manage_closure_dependencies
                                          option will be set to true and all
                                          files will be sorted in dependency
                                          order.
 --common_js_entry_module VAL           : Root of your common JS dependency
                                          hierarchy. Your main script.
 --common_js_module_path_prefix VAL     : Path prefix to be removed from
                                          CommonJS module names. (default: ./)
 --compilation_level [WHITESPACE_ONLY   : Specifies the compilation level to
 | SIMPLE_OPTIMIZATIONS |                 use. Options: WHITESPACE_ONLY,
 ADVANCED_OPTIMIZATIONS]                  SIMPLE_OPTIMIZATIONS, ADVANCED_OPTIMIZ
                                          ATIONS (default: SIMPLE_OPTIMIZATIONS)
 --create_name_map_files                : If true, variable renaming and
                                          property renaming map files will be
                                          produced as {binary name}_vars_map.out
                                          and {binary name}_props_map.out. Note
                                          that this flag cannot be used in
                                          conjunction with either
                                          variable_map_output_file or
                                          property_map_output_file (default:
                                          false)
 --create_source_map VAL                : If specified, a source map file
                                          mapping the generated source files
                                          back to the original source file will
                                          be output to the specified path. The
                                          %outname% placeholder will expand to
                                          the name of the output file that the
                                          source map corresponds to. (default: )
 --debug                                : Enable debugging options (default:
                                          false)
 --define (--D, -D) VAL                 : Override the value of a variable
                                          annotated @define. The format is
                                          <name>[=<val>], where <name> is the
                                          name of a @define variable and <val>
                                          is a boolean, number, or a
                                          single-quoted string that contains no
                                          single quotes. If [=<val>] is
                                          omitted, the variable is marked true
 --externs VAL                          : The file containing JavaScript
                                          externs. You may specify multiple
 --extra_annotation_name VAL            : A whitelist of tag names in JSDoc.
                                          You may specify multiple
 --flagfile VAL                         : A file containing additional
                                          command-line options. (default: )
 --formatting [PRETTY_PRINT |           : Specifies which formatting options,
 PRINT_INPUT_DELIMITER | SINGLE_QUOTES]   if any, should be applied to the
                                          output JS. Options: PRETTY_PRINT,
                                          PRINT_INPUT_DELIMITER, SINGLE_QUOTES
 --generate_exports                     : Generates export code for those
                                          marked with @export (default: false)
 --help                                 : Displays this message (default: false)
 --js VAL                               : The JavaScript filename. You may
                                          specify multiple
 --js_output_file VAL                   : Primary output filename. If not
                                          specified, output is written to
                                          stdout (default: )
 --jscomp_error VAL                     : Make the named class of warnings an
                                          error. Options:accessControls,
                                          ambiguousFunctionDecl, checkRegExp,
                                          checkTypes, checkVars, const,
                                          constantProperty, deprecated,
                                          duplicateMessage, es5Strict,
                                          externsValidation, fileoverviewTags,
                                          globalThis, internetExplorerChecks,
                                          invalidCasts, misplacedTypeAnnotation,
                                          missingProperties, nonStandardJsDocs,
                                          suspiciousCode, strictModuleDepCheck,
                                          typeInvalidation, undefinedNames,
                                          undefinedVars, unknownDefines,
                                          uselessCode, visibility
 --jscomp_off VAL                       : Turn off the named class of warnings.
                                          Options:accessControls,
                                          ambiguousFunctionDecl, checkRegExp,
                                          checkTypes, checkVars, const,
                                          constantProperty, deprecated,
                                          duplicateMessage, es5Strict,
                                          externsValidation, fileoverviewTags,
                                          globalThis, internetExplorerChecks,
                                          invalidCasts, misplacedTypeAnnotation,
                                          missingProperties, nonStandardJsDocs,
                                          suspiciousCode, strictModuleDepCheck,
                                          typeInvalidation, undefinedNames,
                                          undefinedVars, unknownDefines,
                                          uselessCode, visibility
 --jscomp_warning VAL                   : Make the named class of warnings a
                                          normal warning. Options:accessControls
                                          , ambiguousFunctionDecl, checkRegExp,
                                          checkTypes, checkVars, const,
                                          constantProperty, deprecated,
                                          duplicateMessage, es5Strict,
                                          externsValidation, fileoverviewTags,
                                          globalThis, internetExplorerChecks,
                                          invalidCasts, misplacedTypeAnnotation,
                                          missingProperties, nonStandardJsDocs,
                                          suspiciousCode, strictModuleDepCheck,
                                          typeInvalidation, undefinedNames,
                                          undefinedVars, unknownDefines,
                                          uselessCode, visibility
 --language_in VAL                      : Sets what language spec that input
                                          sources conform. Options: ECMASCRIPT3
                                          (default), ECMASCRIPT5,
                                          ECMASCRIPT5_STRICT (default:
                                          ECMASCRIPT3)
 --logging_level VAL                    : The logging level (standard
                                          java.util.logging.Level values) for
                                          Compiler progress. Does not control
                                          errors or warnings for the JavaScript
                                          code under compilation (default:
                                          WARNING)
 --manage_closure_dependencies          : Automatically sort dependencies so
                                          that a file that goog.provides symbol
                                          X will always come before a file that
                                          goog.requires symbol X. If an input
                                          provides symbols, and those symbols
                                          are never required, then that input
                                          will not be included in the
                                          compilation. (default: false)
 --module VAL                           : A JavaScript module specification.
                                          The format is <name>:<num-js-files>[:[
                                          <dep>,...][:]]]. Module names must be
                                          unique. Each dep is the name of a
                                          module that this module depends on.
                                          Modules must be listed in dependency
                                          order, and JS source files must be
                                          listed in the corresponding order.
                                          Where --module flags occur in
                                          relation to --js flags is
                                          unimportant. Provide the value 'auto'
                                          to trigger module creation from
                                          CommonJSmodules.
 --module_output_path_prefix VAL        : Prefix for filenames of compiled JS
                                          modules. <module-name>.js will be
                                          appended to this prefix. Directories
                                          will be created as needed. Use with
                                          --module (default: ./)
 --module_wrapper VAL                   : An output wrapper for a JavaScript
                                          module (optional). The format is
                                          <name>:<wrapper>. The module name
                                          must correspond with a module
                                          specified using --module. The wrapper
                                          must contain %s as the code
                                          placeholder. The %basename%
                                          placeholder can also be used to
                                          substitute the base name of the
                                          module output file.
 --only_closure_dependencies            : Only include files in the transitive
                                          dependency of the entry points
                                          (specified by closure_entry_point).
                                          Files that do not provide
                                          dependencies will be removed. This
                                          supersedesmanage_closure_dependencies
                                          (default: false)
 --output_manifest VAL                  : Prints out a list of all the files in
                                          the compilation. If --manage_closure_d
                                          ependencies is on, this will not
                                          include files that got dropped
                                          because they were not required. The
                                          %outname% placeholder expands to the
                                          JS output file. If you're using
                                          modularization, using %outname% will
                                          create a manifest for each module.
                                          (default: )
 --output_module_dependencies VAL       : Prints out a JSON file of
                                          dependencies between modules.
                                          (default: )
 --output_wrapper VAL                   : Interpolate output into this string
                                          at the place denoted by the marker
                                          token %output%. Use marker token
                                          %output|jsstring% to do js string
                                          escaping on the output. (default: )
 --print_ast                            : Prints a dot file describing the
                                          internal abstract syntax tree and
                                          exits (default: false)
 --print_pass_graph                     : Prints a dot file describing the
                                          passes that will get run and exits
                                          (default: false)
 --print_tree                           : Prints out the parse tree and exits
                                          (default: false)
 --process_closure_primitives           : Processes built-ins from the Closure
                                          library, such as goog.require(),
                                          goog.provide(), and goog.exportSymbol(
                                          ) (default: true)
 --process_common_js_modules            : Process CommonJS modules to a
                                          concatenable form. (default: false)
 --process_jquery_primitives            : Processes built-ins from the Jquery
                                          library, such as jQuery.fn and
                                          jQuery.extend() (default: false)
 --property_map_input_file VAL          : File containing the serialized
                                          version of the property renaming map
                                          produced by a previous compilation
                                          (default: )
 --property_map_output_file VAL         : File where the serialized version of
                                          the property renaming map produced
                                          should be saved (default: )
 --source_map_format [V1 | DEFAULT |    : The source map format to produce.
 V2 | V3]                                 Options: V1, V2, V3, DEFAULT. DEFAULT
                                          produces V2. (default: DEFAULT)
 --summary_detail_level N               : Controls how detailed the compilation
                                          summary is. Values: 0 (never print
                                          summary), 1 (print summary only if
                                          there are errors or warnings), 2
                                          (print summary if the 'checkTypes'
                                          diagnostic  group is enabled, see
                                          --jscomp_warning), 3 (always print
                                          summary). The default level is 1
                                          (default: 1)
 --third_party                          : Check source validity but do not
                                          enforce Closure style rules and
                                          conventions (default: false)
 --transform_amd_modules                : Transform AMD to CommonJS modules.
                                          (default: false)
 --translations_file VAL                : Source of translated messages.
                                          Currently only supports XTB.
                                          (default: )
 --translations_project VAL             : Scopes all translations to the
                                          specified project.When specified, we
                                          will use different message ids so
                                          that messages in different projects
                                          can have different translations.
 --use_only_custom_externs              : Specifies whether the default externs
                                          should be excluded (default: false)
 --use_types_for_optimization           : Experimental: perform additional
                                          optimizations based on available
                                          information.  Inaccurate type
                                          annotations may result in incorrect
                                          results. (default: false)
 --variable_map_input_file VAL          : File containing the serialized
                                          version of the variable renaming map
                                          produced by a previous compilation
                                          (default: )
 --variable_map_output_file VAL         : File where the serialized version of
                                          the variable renaming map produced
                                          should be saved (default: )
 --version                              : Prints the compiler version to
                                          stderr. (default: false)
 --warning_level [QUIET | DEFAULT |     : Specifies the warning level to use.
 VERBOSE]                                 Options: QUIET, DEFAULT, VERBOSE
                                          (default: DEFAULT)
 --warnings_whitelist_file VAL          : A file containing warnings to
                                          suppress. Each line should be of the
                                          form
                                          <file-name>:<line-number>? 
                                          <warning-description> (default: )
```

**Comment by sbc100** [comment]
Can you modify `get_closure_compiler` in `tools/building.py` to find out what is going on here?

I would start doing `print(cmd)` before and after the `--max_old_space_size=8192` argument is added. 

You should see something like this:

```
['/usr/local/google/home/sbc/dev/wasm/emsdk/node/14.15.5_64bit/bin/node', '/usr/local/google/home/sbc/dev/wasm/emscripten/node_modules/.bin/google-closure-compiler']
['/usr/local/google/home/sbc/dev/wasm/emsdk/node/14.15.5_64bit/bin/node', '--max_old_space_size=8192', '/usr/local/google/home/sbc/dev/wasm/emscripten/node_modules/.bin/google-closure-compiler']
```

The idea here is the argument is inject between the node executable and the google-closure-compiler js file, but I guess something else is happening for you?

**Comment by lovasoa** [comment]
There is no node, just the closure compiler executable : 

```
['closure-compiler']
['--max_old_space_size=8192', 'closure-compiler']
```

**Comment by lovasoa** [comment]
Hmm, looking a little bit deeper into it, it looks like it's a bug in debian's packaging. 
Debian includes the following patch to emscripten's source : 

```patch
Description: use system-shared closure-compiler
 Avoid fetching closure-compiler with npm.
 Simply expect it to be available in PATH.
 .
 Also, skip checking option --version
 which hangs with old Debian release.
Author: Jonas Smedegaard <dr@jones.dk>
Last-Update: 2020-11-02
---
This patch header follows DEP-3: http://dep.debian.net/deps/dep3/
--- a/tools/building.py
+++ b/tools/building.py
@@ -901,8 +901,8 @@
   if config.CLOSURE_COMPILER:
     return shared.CLOSURE_COMPILER
 
-  # Otherwise use the one installed vai npm
-  cmd = shared.get_npm_cmd('google-closure-compiler')
+  # Otherwise use the system-shared one
+  cmd = ['closure-compiler']
   if not WINDOWS:
     # Work around an issue that Closure compiler can take up a lot of memory and crash in an error
     # "FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap
@@ -951,11 +951,12 @@
 
     closure_cmd = get_closure_compiler()
 
-    native_closure_compiler_works = check_closure_compiler(closure_cmd, user_args, env, allowed_to_fail=True)
-    if not native_closure_compiler_works and not any(a.startswith('--platform') for a in user_args):
-      # Run with Java Closure compiler as a fallback if the native version does not work
-      user_args.append('--platform=java')
-      check_closure_compiler(closure_cmd, user_args, env, allowed_to_fail=False)
+    # skip checking option --version which hangs with old Debian release.
+    #native_closure_compiler_works = check_closure_compiler(closure_cmd, user_args, env, allowed_to_fail=True)
+    #if not native_closure_compiler_works and not any(a.startswith('--platform') for a in user_args):
+    #  # Run with Java Closure compiler as a fallback if the native version does not work
+    #  user_args.append('--platform=java')
+    #  check_closure_compiler(closure_cmd, user_args, env, allowed_to_fail=False)
 
     # Closure externs file contains known symbols to be extern to the minification, Closure
     # should not minify these symbol names.
```


https://packages.debian.org/source/testing/emscripten

**Comment by lovasoa** [comment]
I already reported multiple problems to debian's package, I'll add this one: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=999803

**Comment by jonassmedegaard** [comment]
Debian package maintainer here.

I don't think it is helpful for the Emscripten project that you report issues with the Debian package at their issue tracker: They clearly state that that they support only their latest release, tied to specific releases of related tools - notably binaryen, closure, and LLVM.

What I think is helpful is that you report issues with Debian-packaged Emscripten at the Debian issue tracker - or if you prefer to use the upstream Emscriptem that you then follow their guidelines in how to install it.

Of course, if the Emscripten developers appreciate issue reports about Debian packaged code, and discussing the deviations applied in Debian, then I am happy to contribute my knowledge about it here has well.  I just prefer to be respectful to the Emscripten developers.

**Comment by lovasoa** [comment]
I'm sorry for the misreport, I didn't realize initially that the bug was in debian's patches to emscripten. I'm reporting it separately to the debian bugtracker, with a link to this discussion.

**Comment by jonassmedegaard** [comment]
Thanks.

I recognize the dilemma of where to report issues.

You are obviously free to do as you like, but as a rule of thumb, report to your closest upstream, and let that upstream figure out what is sensible to pass further upstream.

Concretely, since you use a Debian-redistributed package of Emscripten, that means report it to Debian.  And concretely the Debian package maintainer (me in this case) then figure out if relevant to pass the issue further upstream.

**Comment by sbc100** [comment]
Thanks @jonassmedegaard, that makes sense to me.    No worries if is few bugs get misfiled like this,  we can figure it out and re-direct as needed.    I'll close this one for now I guess.
