### ISSUE TITLE
test_openjpeg fails under LTO with undefined sybmols `setjmp`

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#15679]
```
./tests/runner lto2.test_openjpeg
...
error: undefined symbol: setjmp (referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _setjmp may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
emcc: error: '/usr/local/google/home/sbc/dev/wasm/emsdk/node/14.15.5_64bit/bin/node /usr/local/google/home/sbc/dev/wasm/emscripten/src/compiler.js /tmp/tmpsbvld52_.txt' failed (returned 1)
None
None
FAIL

======================================================================
FAIL: test_openjpeg (test_core.lto2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/common.py", line 863, in run_process
    return shared.run_process(cmd, check=check, **args)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tools/shared.py", line 105, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/google/home/sbc/dev/wasm/emscripten/emcc', '-sNO_DEFAULT_TO_CXX', '/usr/local/google/home/sbc/dev/wasm/emscripten/tests/third_party/openjpeg/codec/j2k_to_image.c', '-o', 'j2k_to_image.js', '-sEXIT_RUNTIME=0', '-Werror', '-flto', '-O2', '--minify=0', '--pre-js', 'pre.js', '-sUSE_LIBPNG', '/tmp/emscripten_test_lto2_94dv56wu/building/third_party/openjpeg/codec/CMakeFiles/j2k_to_image.dir/index.c.o', '/tmp/emscripten_test_lto2_94dv56wu/building/third_party/openjpeg/codec/CMakeFiles/j2k_to_image.dir/convert.c.o', '/tmp/emscripten_test_lto2_94dv56wu/building/third_party/openjpeg/codec/CMakeFiles/j2k_to_image.dir/__/common/color.c.o', '/tmp/emscripten_test_lto2_94dv56wu/building/third_party/openjpeg/bin/libopenjpeg.a', '-I.', '-I/usr/local/google/home/sbc/dev/wasm/emscripten/tests/third_party/openjpeg/libopenjpeg', '-I/usr/local/google/home/sbc/dev/wasm/emscripten/tests/third_party/openjpeg/codec', '-I/usr/local/google/home/sbc/dev/wasm/emscripten/tests/third_party/openjpeg/common', '-I/tmp/emscripten_test_lto2_94dv56wu/building/third_party/openjpeg']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/common.py", line 134, in decorated
    return func(self, *args, **kwargs)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/test_core.py", line 6397, in test_openjpeg
    do_test_openjpeg()
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/test_core.py", line 6382, in do_test_openjpeg
    do_test()
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/test_core.py", line 6371, in do_test
    self.do_runf(test_file('third_party/openjpeg/codec/j2k_to_image.c'),
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/common.py", line 1040, in do_runf
    return self._build_and_run(filename, expected_output, **kwargs)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/common.py", line 1067, in _build_and_run
    js_file = self.build(filename, libraries=libraries, includes=includes,
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/common.py", line 588, in build
    self.run_process(cmd, stderr=self.stderr_redirect if not DEBUG else None)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/common.py", line 868, in run_process
    self.fail(f'subprocess exited with non-zero return code({e.returncode}): `{shared.shlex_join(cmd)}`')
AssertionError: subprocess exited with non-zero return code(1): `/usr/local/google/home/sbc/dev/wasm/emscripten/emcc -sNO_DEFAULT_TO_CXX /usr/local/google/home/sbc/dev/wasm/emscripten/tests/third_party/openjpeg/codec/j2k_to_image.c -o j2k_to_image.js -sEXIT_RUNTIME=0 -Werror -flto -O2 --minify=0 --pre-js pre.js -sUSE_LIBPNG /tmp/emscripten_test_lto2_94dv56wu/building/third_party/openjpeg/codec/CMakeFiles/j2k_to_image.dir/index.c.o /tmp/emscripten_test_lto2_94dv56wu/building/third_party/openjpeg/codec/CMakeFiles/j2k_to_image.dir/convert.c.o /tmp/emscripten_test_lto2_94dv56wu/building/third_party/openjpeg/codec/CMakeFiles/j2k_to_image.dir/__/common/color.c.o /tmp/emscripten_test_lto2_94dv56wu/building/third_party/openjpeg/bin/libopenjpeg.a -I. -I/usr/local/google/home/sbc/dev/wasm/emscripten/tests/third_party/openjpeg/libopenjpeg -I/usr/local/google/home/sbc/dev/wasm/emscripten/tests/third_party/openjpeg/codec -I/usr/local/google/home/sbc/dev/wasm/emscripten/tests/third_party/openjpeg/common -I/tmp/emscripten_test_lto2_94dv56wu/building/third_party/openjpeg`

----------------------------------------------------------------------
Ran 1 test in 54.634s

FAILED (failures=1)
```

**Comment by sbc100** [comment]
cc @aheejin
