### ISSUE TITLE
ASan error inside pthread_create and malloc

### ISSUE THREAD

**Issue by tlively** [emscripten-core/emscripten#15762]
Using `tot` installed just now:
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.0.1-git (ad05649111fa61c653b11adf86fe418782ecbf06)
clang version 14.0.0 (https://github.com/llvm/llvm-project 9cbab13282fe59885b6f9c2411eddbdd452c36e7)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/local/google/home/tlively/code/emsdk/upstream/bin
```

Reproducer:
```C
// test.c
#include <pthread.h>

pthread_t other_thread;

static void* thread_main(void* arg) {
  return NULL;
}

int main(int argc, char* argv[]) {
  pthread_create(&other_thread, NULL, thread_main, NULL);
}
```
Compile and run:
```
 ~/code/emsdk/upstream/emscripten/emcc test.c -o test.js -pthread -fsanitize=address -sPTHREAD_POOL_SIZE=2 --profiling-funcs && node --experimental-wasm-threads test.js
```
Output:
```
exiting due to exception: RuntimeError: memory access out of bounds,RuntimeError: memory access out of bounds
    at __sanitizer::StackDepotBase<__sanitizer::StackDepotNode, 1, 20>::Put(__sanitizer::StackTrace, bool*) (<anonymous>:wasm-function[861]:0x2805d)
    at __sanitizer::StackDepotPut(__sanitizer::StackTrace) (<anonymous>:wasm-function[860]:0x27f7d)
    at __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) (<anonymous>:wasm-function[389]:0x13383)
    at __asan::asan_malloc(unsigned long, __sanitizer::BufferedStackTrace*) (<anonymous>:wasm-function[388]:0x13059)
    at malloc (<anonymous>:wasm-function[477]:0x18fe6)
    at __pthread_create (<anonymous>:wasm-function[83]:0x58c6)
    at pthread_create (<anonymous>:wasm-function[348]:0x11815)
    at main (<anonymous>:wasm-function[51]:0x130e)
    at /usr/local/google/home/tlively/code/emscripten/test.js:1378:20
    at callMain (/usr/local/google/home/tlively/code/emscripten/test.js:6950:13)
```

Notes: Adding `-g` makes the problem go away.

**Comment by tlively** [comment]
I can also reproduce using `latest`.

**Comment by pmatos** [comment]
> I can also reproduce using `latest`.

FWIW, I quickly gave this a go but couldn't reproduce it with `latest`.

Log:
```
➜  emsdk git:(main) ./emsdk install latest
Resolving SDK alias 'latest' to '3.0.0'
Resolving SDK version '3.0.0' to 'sdk-releases-upstream-7fbe748230f2ce99abbf975d9ad997699efb3153-64bit'
Installing SDK 'sdk-releases-upstream-7fbe748230f2ce99abbf975d9ad997699efb3153-64bit'..
Installing tool 'node-14.15.5-64bit'..
Downloading: /home/pmatos/dev/emsdk/zips/node-v14.15.5-linux-x64.tar.xz from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v14.15.5-linux-x64.tar.xz, 21391232 Bytes
Unpacking '/home/pmatos/dev/emsdk/zips/node-v14.15.5-linux-x64.tar.xz' to '/home/pmatos/dev/emsdk/node/14.15.5_64bit'
Done installing tool 'node-14.15.5-64bit'.
Installing tool 'releases-upstream-7fbe748230f2ce99abbf975d9ad997699efb3153-64bit'..
Downloading: /home/pmatos/dev/emsdk/zips/7fbe748230f2ce99abbf975d9ad997699efb3153-wasm-binaries.tbz2 from https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/7fbe748230f2ce99abbf975d9ad997699efb3153/wasm-binaries.tbz2, 258872974 Bytes
Unpacking '/home/pmatos/dev/emsdk/zips/7fbe748230f2ce99abbf975d9ad997699efb3153-wasm-binaries.tbz2' to '/home/pmatos/dev/emsdk/upstream'
Done installing tool 'releases-upstream-7fbe748230f2ce99abbf975d9ad997699efb3153-64bit'.
Done installing SDK 'sdk-releases-upstream-7fbe748230f2ce99abbf975d9ad997699efb3153-64bit'.
➜  emsdk git:(main) ./emsdk activate latest
Resolving SDK alias 'latest' to '3.0.0'
Resolving SDK version '3.0.0' to 'sdk-releases-upstream-7fbe748230f2ce99abbf975d9ad997699efb3153-64bit'
Setting the following tools as active:
   node-14.15.5-64bit
   releases-upstream-7fbe748230f2ce99abbf975d9ad997699efb3153-64bit

Next steps:
- To conveniently access emsdk tools from the command line,
  consider adding the following directories to your PATH:
    /home/pmatos/dev/emsdk
    /home/pmatos/dev/emsdk/node/14.15.5_64bit/bin
    /home/pmatos/dev/emsdk/upstream/emscripten
- This can be done for the current shell by running:
    source "/home/pmatos/dev/emsdk/emsdk_env.sh"
- Configure emsdk in your shell startup scripts by running:
    echo 'source "/home/pmatos/dev/emsdk/emsdk_env.sh"' >> $HOME/.zprofile
➜  emsdk git:(main) source ./emsdk_env.sh
Adding directories to PATH:
PATH += /home/pmatos/dev/emsdk
PATH += /home/pmatos/dev/emsdk/upstream/emscripten
PATH += /home/pmatos/dev/emsdk/node/14.15.5_64bit/bin

Setting environment variables:
PATH = /home/pmatos/dev/emsdk:/home/pmatos/dev/emsdk/upstream/emscripten:/home/pmatos/dev/emsdk/node/14.15.5_64bit/bin:/home/pmatos/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
EMSDK = /home/pmatos/dev/emsdk
EM_CONFIG = /home/pmatos/dev/emsdk/.emscripten
EMSDK_NODE = /home/pmatos/dev/emsdk/node/14.15.5_64bit/bin/node
➜  emsdk git:(main) cd ~/tmp
➜  tmp emcc test.c -o test.js -pthread -fsanitize=address -sPTHREAD_POOL_SIZE=2 --profiling-funcs && node --experimental-wasm-threads test.js
shared:INFO: (Emscripten: Running sanity checks)
``` 

The last command exits successfully.

**Comment by pmatos** [comment]
Interesting - but I can reproduce it with `tot`:

```
➜  emsdk git:(main) ./emsdk install tot    
Cloning from https://chromium.googlesource.com/emscripten-releases...
Cloning into '/home/pmatos/dev/emsdk/releases'...
remote: Finding sources: 100% (42/42)
remote: Total 29579 (delta 19110), reused 29577 (delta 19110)
Receiving objects: 100% (29579/29579), 12.54 MiB | 12.34 MiB/s, done.
Resolving deltas: 100% (19110/19110), done.
Fetching latest changes to the branch/tag 'main' for '/home/pmatos/dev/emsdk/releases'...
refs/heads/main
Already up to date.
Successfully updated and checked out branch/tag 'main' on repository '/home/pmatos/dev/emsdk/releases'
Current repository version: "Mon, 13 Dec 2021 14:35:24 +0000 27ffa83e21f825a277dd7d0c92a17cb23961a800"
Installing SDK 'sdk-releases-upstream-27ffa83e21f825a277dd7d0c92a17cb23961a800-64bit'..
Skipped installing node-14.15.5-64bit, already installed.
Installing tool 'releases-upstream-27ffa83e21f825a277dd7d0c92a17cb23961a800-64bit'..
Downloading: /home/pmatos/dev/emsdk/zips/27ffa83e21f825a277dd7d0c92a17cb23961a800-wasm-binaries.tbz2 from https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/27ffa83e21f825a277dd7d0c92a17cb23961a800/wasm-binaries.tbz2, 186131076 Bytes
Unpacking '/home/pmatos/dev/emsdk/zips/27ffa83e21f825a277dd7d0c92a17cb23961a800-wasm-binaries.tbz2' to '/home/pmatos/dev/emsdk/upstream'
Done installing tool 'releases-upstream-27ffa83e21f825a277dd7d0c92a17cb23961a800-64bit'.
Done installing SDK 'sdk-releases-upstream-27ffa83e21f825a277dd7d0c92a17cb23961a800-64bit'.
➜  emsdk git:(main) ./emsdk activate tot   Setting the following tools as active:
   node-14.15.5-64bit
   releases-upstream-27ffa83e21f825a277dd7d0c92a17cb23961a800-64bit

Next steps:
- To conveniently access emsdk tools from the command line,
  consider adding the following directories to your PATH:
    /home/pmatos/dev/emsdk
    /home/pmatos/dev/emsdk/node/14.15.5_64bit/bin
    /home/pmatos/dev/emsdk/upstream/emscripten
- This can be done for the current shell by running:
    source "/home/pmatos/dev/emsdk/emsdk_env.sh"
- Configure emsdk in your shell startup scripts by running:
    echo 'source "/home/pmatos/dev/emsdk/emsdk_env.sh"' >> $HOME/.zprofile
➜  emsdk git:(main) emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.0.1-git (ad05649111fa61c653b11adf86fe418782ecbf06)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

➜  emsdk git:(main) cd ~/tmp 
➜  tmp emcc test.c -o test.js -pthread -fsanitize=address -sPTHREAD_POOL_SIZE=2 --profiling-funcs && node --experimental-wasm-threads test.js
shared:INFO: (Emscripten: Running sanity checks)
exiting due to exception: RuntimeError: memory access out of bounds,RuntimeError: memory access out of bounds
    at __sanitizer::StackDepotBase<__sanitizer::StackDepotNode, 1, 20>::Put(__sanitizer::StackTrace, bool*) (<anonymous>:wasm-function[861]:0x2805d)
    at __sanitizer::StackDepotPut(__sanitizer::StackTrace) (<anonymous>:wasm-function[860]:0x27f7d)
    at __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) (<anonymous>:wasm-function[389]:0x13383)
    at __asan::asan_malloc(unsigned long, __sanitizer::BufferedStackTrace*) (<anonymous>:wasm-function[388]:0x13059)
    at malloc (<anonymous>:wasm-function[477]:0x18fe6)
    at __pthread_create (<anonymous>:wasm-function[83]:0x58c6)
    at pthread_create (<anonymous>:wasm-function[348]:0x11815)
    at main (<anonymous>:wasm-function[51]:0x130e)
    at /home/pmatos/tmp/test.js:1378:20
    at callMain (/home/pmatos/tmp/test.js:6950:13)
```

This sounds like a job for bisection.

**Comment by pmatos** [comment]
And I also confirm that `-g` makes the problem go away.

**Comment by tlively** [comment]
Thanks for confirming!

**Comment by sbc100** [comment]
The stack trace looks wrong to me because IIRC, pthread_create is supposed to be intercepted by asan do user code should be called the wrapper which will then call `emscripten_builtin_pthread_create` internally.

Here is looks like pthread_create is be called directly from user code.

**Comment by sbc100** [comment]
Does `--profiling` also hide the bug?   That might explain why the bots don't see the issue (since we always do asan builds with `--profiling` .. since the output of asan is not very useful without function names).

**Comment by tlively** [comment]
No, `--profiling` does not hide the bug.

**Comment by sbc100** [comment]
Well that is odd. why aren't all the `asan.test_*thead*` tests failing I wonder.

**Comment by kleisauke** [comment]
Here's a reproducer on the test suite: https://github.com/kleisauke/emscripten/commit/d4ae43dd712148b0fe823e3496001fd401c5adbf.

It seems that linking with `-sALLOW_MEMORY_GROWTH` makes this issue disappear, which is the default for the `asan.test_*thread*` tests.
https://github.com/emscripten-core/emscripten/blob/ad282f9824f37f3efdf0646ef0d514e1f568e749/tests/test_core.py#L8912
(I had to explicitly clear that setting with `self.clear_setting('ALLOW_MEMORY_GROWTH')` in order to reproduce)

**Comment by kleisauke** [comment]
Somehow running `emcc --clear-cache` before testing also makes this issue disappear on the latest tip-of-tree build. Although, it can still be reliably reproduced on the test suite.
<details>
  <summary>Details</summary>

```bash
$ emcc test.c -o test.js -pthread -fsanitize=address -sPTHREAD_POOL_SIZE=2 --profiling-funcs && node --experimental-wasm-threads test.js
shared:INFO: (Emscripten: Running sanity checks)
exiting due to exception: RuntimeError: memory access out of bounds,RuntimeError: memory access out of bounds
    at __sanitizer::StackDepotBase<__sanitizer::StackDepotNode, 1, 20>::Put(__sanitizer::StackTrace, bool*) (<anonymous>:wasm-function[861]:0x2805d)
    at __sanitizer::StackDepotPut(__sanitizer::StackTrace) (<anonymous>:wasm-function[860]:0x27f7d)
    at __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) (<anonymous>:wasm-function[389]:0x13383)
    at __asan::asan_malloc(unsigned long, __sanitizer::BufferedStackTrace*) (<anonymous>:wasm-function[388]:0x13059)
    at malloc (<anonymous>:wasm-function[477]:0x18fe6)
    at __pthread_create (<anonymous>:wasm-function[83]:0x58c6)
    at pthread_create (<anonymous>:wasm-function[348]:0x11815)
    at main (<anonymous>:wasm-function[51]:0x130e)
    at /home/kleisauke/test.js:1378:20
    at callMain (/home/kleisauke/test.js:6950:13)
$ echo $?
1
$ emcc --clear-cache
emcc:INFO: clearing cache as requested by --clear-cache: `/home/kleisauke/emsdk/upstream/emscripten/cache`
shared:INFO: (Emscripten: Running sanity checks)
$ emcc test.c -o test.js -pthread -fsanitize=address -sPTHREAD_POOL_SIZE=2 --profiling-funcs && node --experimental-wasm-threads test.js
<snip />
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/libc-mt-asan-debug.a... (this will be cached in "/home/kleisauke/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc-mt-asan-debug.a" for subsequent builds)
cache:INFO:  - ok
<snip />
$ echo $?
0
$ cd emscripten/
$ ./emcc --clear-cache
shared:INFO: (Emscripten: Running sanity checks)
emcc:INFO: clearing cache as requested by --clear-cache: `/home/kleisauke/emscripten/cache`
shared:INFO: (Emscripten: Running sanity checks)
$ ./tests/runner asan.test_pthread_create_2
<snip />
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/libc-mt-asan-debug.a... (this will be cached in "/home/kleisauke/emscripten/cache/sysroot/lib/wasm32-emscripten/libc-mt-asan-debug.a" for subsequent builds)
cache:INFO:  - ok
<snip />
======================================================================
FAIL: test_pthread_create_2 (test_core.asan)
----------------------------------------------------------------------
<snip />
----------------------------------------------------------------------
Ran 1 test in 38.821s

FAILED (failures=1)
$ echo $?
1
```
</details>

FWIW, the `-sALLOW_MEMORY_GROWTH` option has been turned on since the beginning of ASan tests (commit https://github.com/emscripten-core/emscripten/pull/8884/commits/a2a514335a14bc2991a297ddfe75563259e1d908), but that didn't support pthreads at that time (commit https://github.com/emscripten-core/emscripten/pull/8884/commits/731e2e06320e72e2d66fd0a8fdc44f7263e9e173). After commit https://github.com/emscripten-core/emscripten/commit/fdd60695ba3b4098a6a88fc8a8df4d50cc1b033b the ASan+pthreads combo fully worked.

**Comment by sbc100** [comment]
So I think #15780 will fix the `--clear-cache` seeming non-determinism.

The actual issue seems like is actually just OOM since increasing TOTAL_MEMORY or making it growable make the issue go away.   It seems that my hacky/fragile attempt to estimate potential memory requirements of asan is not always good enough: 

https://github.com/emscripten-core/emscripten/blob/0fd050ace6e6e5fda43e4751f8e49c3317c8b1f4/emcc.py#L2228-L2241

**Comment by sbc100** [comment]
We should at least try to make these OOM situations obvious.. that backtrace is very unhelpful.

**Comment by sbc100** [comment]
This bug seems extremely hard to pin down.   Changing almost any build flag will make it go away... as will increasing the total memory from the default of 16Mb to 18Mb.. or allowing grow-able memory.

I do have a repro case that works on tip of tree.  But its started reproducing at very-much unrelated PR: #15767.   The crash is so sensitive that removing a single empty line from the JS output (or collapsing two into a single one) will make it go away.   This led Thomas to point me in the direction of the offset coverter since it must be sensitive to the over JS line numbers.   However I still have no idea why changing JS line number can cause asan to crash in `__sanitizer::StackDepotPut`.

I do think its likely this bug has just always be latent in low memory situations when asan is enabled.. because I don't think anything has change recently in the relevant code.

I don't think this bug has anything fundamentally to do with threading because the crash happens before the thread is started will the main thread is trying to allocating the data for the thread.

**Comment by sbc100** [comment]
I manages to get a repro that works against the `main` branch at least at revision fb960fb75.   The raname that just landed on top of that causes the repro to stop working again.

Steps to repro:

$ git checkout fb960fb75
$ cat test.c 
// test.c
#include <pthread.h>
#include <stdlib.h>
#include <stdio.h>

pthread_t other_thread;

static void* thread_main(void* arg) {
  return NULL;
}

int main(int argc, char* argv[]) {
  printf("xxx\n");
  pthread_create(&other_thread, NULL, thread_main, NULL);
}
$ ./emcc test.c -o test.js -pthread -fsanitize=address -sPTHREAD_POOL_SIZE=1 --profiling-funcs
$ node --experimental-wasm-threads test.js  
xxx
exiting due to exception: RuntimeError: memory access out of bounds,RuntimeError: memory access out of bounds
    at __sanitizer::StackDepotBase<__sanitizer::StackDepotNode, 1, 20>::Put(__sanitizer::StackTrace, bool*) (<anonymous>:wasm-function[858]:0x2a80e)
    at __sanitizer::StackDepotPut(__sanitizer::StackTrace) (<anonymous>:wasm-function[857]:0x2a72e)
    at __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) (<anonymous>:wasm-function[329]:0x12932)
    at __asan::asan_malloc(unsigned long, __sanitizer::BufferedStackTrace*) (<anonymous>:wasm-function[328]:0x12608)
    at malloc (<anonymous>:wasm-function[446]:0x1bd85)
    at __pthread_create (<anonymous>:wasm-function[120]:0x5ca3)
    at pthread_create (<anonymous>:wasm-function[386]:0x162a1)
    at main (<anonymous>:wasm-function[50]:0x1361)
    at /usr/local/google/home/sbc/dev/wasm/emscripten/test.js:1378:20
    at callMain (/usr/local/google/home/sbc/dev/wasm/emscripten/test.js:6923:13)
```

Note that this is very sensitive:

- Removing the `printf` call or just moving it to the end of `main` will make the issue go away.   
- Syncing to c04a30b21 (an NFC rename/refactor) will make the issue go away.
- Adding a black line to test.js at 4711 will make the issue go away!

**Comment by sbc100** [comment]
This issue is certainly about lack of memory.    When `TOTAL_MEMORY` is not large enough I see hash table entries in `StackDepotBase` being overridden with `0xfafafafa` which is `kAsanHeapLeftRedzoneMagic`.  I confirmed this by changing `kAsanHeapLeftRedzoneMagic` and it changed the corruption.

I will keep debugging, but I'm also writing a test to confirm that this corruption has always been there or not.

**Comment by sbc100** [comment]
One reason this is so hard to pin down is that it depends on the hash of the line addresses in the back traces (i.e. the hash of JS line numbers).   If the hash don't land on corrupted slots you don't see the crash.

**Comment by sbc100** [comment]
As I suspected this issue is unrelated to threads, and unrelated to any recent commit.  I create patch to detect the corruption, even when the program being run does not otherwise crash:

```
 --- a/system/lib/compiler-rt/lib/sanitizer_common/sanitizer_stackdepotbase.h
+++ b/system/lib/compiler-rt/lib/sanitizer_common/sanitizer_stackdepotbase.h
@@ -14,6 +14,7 @@
 #define SANITIZER_STACKDEPOTBASE_H
 
 #include <stdio.h>
+#include <stdlib.h>
 
 #include "sanitizer_atomic.h"
 #include "sanitizer_internal_defs.h"
@@ -104,6 +105,23 @@ StackDepotBase<Node, kReservedBits, kTabSizeLog>::Put(args_type args,
   uptr h = Node::hash(args);
   atomic_uintptr_t *p = &tab[h % kTabSize];
   uptr v = atomic_load(p, memory_order_consume);
+  int oops_count = 0;
+#if 1
+  printf("put: hash=%p table=%p slot=%p\n", h, tab, v);
+  for (int i = 0; i < kTabSize; i++) {
+    atomic_uintptr_t *y = &tab[i];
+    uptr x = atomic_load(y, memory_order_consume);
+    if (x == 0xfafafafa) {
+      if (!oops_count)
+        printf("oops at %i (of %d)\n", i, kTabSize);
+      oops_count++;
+    }
+  }
+  if (oops_count) {
+    printf("bad entries: %i\n", oops_count);
+    abort();
+  }
+#endif
   Node *s = (Node *)(v & ~1);
   // First, try to find the existing stack.
   Node *node = find(s, args, h);
```

Using this patch I can detect corruption in a much simple program:

```
$ cat test.c 
// test.c
#include <pthread.h>
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char* argv[]) {
  void* ptr = malloc(100);
  printf("ptr = %p\n", ptr);
  free(ptr);
  return 0;
}
```

```
$ ./emcc test.c -s TOTAL_MEMORY=34Mb  -o test.js -fsanitize=address --profiling-funcs && node --experimental-wasm-threads test.js  
emcc: warning: unexpected binaryen version: 103 (expected 101) [-Wversion-check]
put: hash=0x72111cb2 table=0x479954 slot=0
put: hash=0xb4c9ddbd table=0x479954 slot=0
put: hash=0x458f3cfe table=0x479954 slot=0
put: hash=0xa9998fff table=0x479954 slot=0
put: hash=0x6b54833b table=0x479954 slot=0
put: hash=0xb2f08776 table=0x479954 slot=0
put: hash=0xd59fcace table=0x479954 slot=0
put: hash=0xa5a0462f table=0x479954 slot=0
put: hash=0x89e7873c table=0x479954 slot=0
put: hash=0x14885142 table=0x479954 slot=0
put: hash=0x4eff8084 table=0x479954 slot=0
put: hash=0x7622c6c8 table=0x479954 slot=0
put: hash=0x8a3f2ce4 table=0x479954 slot=0
put: hash=0x27cb60d9 table=0x479954 slot=0
put: hash=0xc8d20a8b table=0x479954 slot=0
oops at 137643 (of 1048576)
bad entries: 65536
Aborted(native code called abort())
exiting due to exception: RuntimeError: Aborted(native code called abort()),RuntimeError: Aborted(native code called abort())
    at abort (/usr/local/google/home/sbc/dev/wasm/emscripten/test.js:1229:10)
    at _abort (/usr/local/google/home/sbc/dev/wasm/emscripten/test.js:4194:2)
    at __sanitizer::StackDepotBase<__sanitizer::StackDepotNode, 1, 20>::Put(__sanitizer::StackTrace, bool*) (<anonymous>:wasm-function[579]:0x1d5b7)
    at __sanitizer::StackDepotPut(__sanitizer::StackTrace) (<anonymous>:wasm-function[578]:0x1d0ee)
    at __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) (<anonymous>:wasm-function[410]:0x154c6)
    at __asan::asan_malloc(unsigned long, __sanitizer::BufferedStackTrace*) (<anonymous>:wasm-function[409]:0x151a3)
    at malloc (<anonymous>:wasm-function[346]:0x11616)
    at main (<anonymous>:wasm-function[31]:0xcd8)
    at /usr/local/google/home/sbc/dev/wasm/emscripten/test.js:1255:20
    at callMain (/usr/local/google/home/sbc/dev/wasm/emscripten/test.js:5878:13)
```

The corruption is delectable in almost any program and exists until I raise the `TOTAL_MEMORY` to around 50Mb.

The corruption is delectable in 2.0.34, and 3.0.0 and HEAD.

**Comment by sbc100** [comment]
And ... of course I tracked it down to one of my own changes: #14621 ... the bug here is that we set the shadow area based on the memory size and then we bump the memory size.. doh
