### ISSUE TITLE
UnicodeDecodeError when running tests

### ISSUE THREAD

**Issue by miladfarca** [emscripten-core/emscripten#15774]
I have built llvm and binaryen from source (main branch).
I'm using the main branch of emscripten to run tests.
I am also using Node.js `v16.13.1`.
My python version is `3.6`.

I am getting `UnicodeDecodeError` when running a single test case:
```
tests/runner test_zero_struct_varargs
```

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.0.1-git (ad282f9824f37f3efdf0646ef0d514e1f568e749)
clang version 14.0.0 (https://github.com/llvm/llvm-project.git 3f066ac64893979adb79079991686325242ae7e9)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: ./emc/llvm-project/build/bin

**Failing command line in full:**
tests/runner test_zero_struct_varargs

**Full link command and output with `-v` appended:**
root:DEBUG: Checking JS engine ['./emc/node-v16.13.1-linux-x64/bin/node']
Running: './emc/node-v16.13.1-linux-x64/bin/node ./emc/emscripten/tests/hello_world.js'
shared:DEBUG: successfully executed ./emc/binaryen/bin/wasm-opt --version
Test suites:
['test_core']
Running test_core: (1 tests)
(checking sanity from test runner)
shared:DEBUG: successfully executed ./emc/llvm-project/build/bin/clang --version
cache:DEBUG: PID 57508 acquiring multiprocess file lock to Emscripten cache at ./emc/emscripten/cache
tools.filelock:DEBUG: Attempting to acquire lock 139770436716472 on ./emc/emscripten/cache/cache.lock
tools.filelock:DEBUG: Lock 139770436716472 acquired on ./emc/emscripten/cache/cache.lock
cache:DEBUG: done
shared:DEBUG: sanity file up-to-date but check forced: ./emc/emscripten/cache/sanity.txt
shared:DEBUG: successfully executed ./emc/node-v16.13.1-linux-x64/bin/node --version
shared:DEBUG: successfully executed ./emc/llvm-project/build/bin/llc --version
shared:INFO: (Emscripten: Running sanity checks)
shared:DEBUG: successfully executed ./emc/node-v16.13.1-linux-x64/bin/node -e console.log("hello")
profiler:DEBUG: block "sanity compiler_engine" took 0.05 seconds
profiler:DEBUG: block "sanity LLVM" took 0.00 seconds
tools.filelock:DEBUG: Attempting to release lock 139770436716472 on ./emc/emscripten/cache/cache.lock
tools.filelock:DEBUG: Lock 139770436716472 released on ./emc/emscripten/cache/cache.lock
cache:DEBUG: PID 57508 released multiprocess file lock to Emscripten cache at ./emc/emscripten/cache
profiler:DEBUG: block "sanity" took 0.08 seconds
test_zero_struct_varargs (test_core.wasm0) ... common:DEBUG: _build_and_run: ./emc/emscripten/tests/core/test_zero_struct_varargs.c
shared:DEBUG: successfully executed ./emc/emscripten/emcc -sNO_DEFAULT_TO_CXX ./emc/emscripten/tests/core/test_zero_struct_varargs.c -o test_zero_struct_varargs.js -Werror -O0 -I.
ERROR

ERROR: test_zero_struct_varargs (test_core.wasm0)

Traceback (most recent call last):
  File "./emc/emscripten/tests/test_core.py", line 495, in test_zero_struct_varargs
    self.do_core_test('test_zero_struct_varargs.c')
  File "./emc/emscripten/tests/test_core.py", line 360, in do_core_test
    self.do_run_in_out_file_test(Path('core', testname), **kwargs)
  File "./emc/emscripten/tests/common.py", line 1054, in do_run_in_out_file_test
    self._build_and_run(srcfile, expected, **kwargs)
  File "./emc/emscripten/tests/common.py", line 1072, in _build_and_run
    output_basename=output_basename)
  File "./emc/emscripten/tests/common.py", line 591, in build
    self.verify_es5(output)
  File "./emc/emscripten/tests/common.py", line 558, in verify_es5
    shared.run_process(es_check + ['es5', os.path.abspath(filename)], stdout=PIPE, stderr=STDOUT, env=es_check_env)
  File "./emc/emscripten/tools/shared.py", line 105, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/lib/python3.6/subprocess.py", line 425, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 850, in communicate
    stdout = self.stdout.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 59: ordinal not in range(128)

**Comment by miladfarca** [comment]
Seems to be a locale issue in Docker. `export LANG=C.UTF-8` fixed the problem. More info on this: https://stackoverflow.com/a/51027262
