### ISSUE TITLE
Possible leak in _gmtime_r()

### ISSUE THREAD

**Issue by iboukris** [emscripten-core/emscripten#15861]
Trying to add `-fsanitize=address` in my project (at https://github.com/iboukris/webgss), I get this leak error:

**Version of emscripten/emsdk:**
```
emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.0 (8e1e305519e1027726a48861a1fec5662f7e18a2)
clang version 14.0.0 (https://github.com/llvm/llvm-project 1a929525e86a20d0b3455a400d0dbed40b325a13)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/admin/git/emsdk/upstream/bin
```
Leak error:

```
==42==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x2eb817 in malloc+0x2eb817 (/home/admin/git/webgss/lib/k5lib_node.wasm+0x2eb817)
    #1 0x80000530  (JavaScript+0x530)
    #2 0x80000402 in allocateUTF8 /home/admin/git/webgss/lib/k5lib_node.js:1026:12
    #3 0x80001dcd in _gmtime_r /home/admin/git/webgss/lib/k5lib_node.js:7629:50
    #4 0xd7630 in k5_asn1_encode_generaltime+0xd7630 (/home/admin/git/webgss/lib/k5lib_node.wasm+0xd7630)
    #5 0xe4955 in encode_kerberos_time+0xe4955 (/home/admin/git/webgss/lib/k5lib_node.wasm+0xe4955)
    #6 0xd8fe4 in encode_atype+0xd8fe4 (/home/admin/git/webgss/lib/k5lib_node.wasm+0xd8fe4)
    #7 0xd92b9 in encode_atype+0xd92b9 (/home/admin/git/webgss/lib/k5lib_node.wasm+0xd92b9)

SUMMARY: AddressSanitizer: 4 byte(s) leaked in 1 allocation(s).
```

If I change the line in the generated k5lib_node.js:7629 as bellow, the error goes away:
```diff
- if (!_gmtime_r.GMTString) _gmtime_r.GMTString = allocateUTF8("GMT");
+ if (!_gmtime_r.GMTString) _gmtime_r.GMTString = "GMT";
```

**Comment by iboukris** [comment]
Thanks for the prompt xmas fix :)
