### ISSUE TITLE
test_atexit_threads_stub fails under lsan (but not asan)

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#15988]
I spent the best part of a day investigating and its a very odd failure.
Looks like an internal issue where LSan metadata get corrupted or confuses.

**Comment by sbc100** [comment]
```
exiting due to exception: RuntimeError: invalid index into function table,RuntimeError: invalid index into function table
    at __cxxabiv1::(anonymous namespace)::run_dtors(void*) (<anonymous>:wasm-function[98]:0x5c5e)
    at __cxxabiv1::(anonymous namespace)::DtorsManager::~DtorsManager() (<anonymous>:wasm-function[100]:0x5c84)
    at __cxx_global_array_dtor (<anonymous>:wasm-function[96]:0x5c28)
    at __funcs_on_exit (<anonymous>:wasm-function[32]:0x9e7)
    at /tmp/emscripten_test_lsan_b6ieqsyz/test_atexit_threads.js:1006:22
    at exitRuntime (/tmp/emscripten_test_lsan_b6ieqsyz/test_atexit_threads.js:792:3)
    at exitJS (/tmp/emscripten_test_lsan_b6ieqsyz/test_atexit_threads.js:4263:9)
    at callMain (/tmp/emscripten_test_lsan_b6ieqsyz/test_atexit_threads.js:5434:5)
    at doRun (/tmp/emscripten_test_lsan_b6ieqsyz/test_atexit_threads.js:5483:23)
    at run (/tmp/emscripten_test_lsan_b6ieqsyz/test_atexit_threads.js:5498:5)
    at runCaller (/tmp/emscripten_test_lsan_b6ieqsyz/test_atexit_threads.js:5406:19)
    at removeRunDependency (/tmp/emscripten_test_lsan_b6ieqsyz/test_atexit_threads.js:926:7)
    at receiveInstance (/tmp/emscripten_test_lsan_b6ieqsyz/test_atexit_threads.js:1264:5)
    at receiveInstantiationResult (/tmp/emscripten_test_lsan_b6ieqsyz/test_atexit_threads.js:1282:5)
```
