### ISSUE TITLE
[libc] System library build error (Emscripten 3.1.1)

### ISSUE THREAD

**Issue by Razakhel** [emscripten-core/emscripten#16055]
Hello the Emscripten team :wave: 

I happen to have an issue with the 3.1.1, which seems to fail to build a libc header. This has never happened before with any Emscripten version. I had another problem prior to that (with a macro `weak` which was expanded insided an `__attribute__((weak))`); a full clean of the build files fixed it, but not the current one.

If relevant:
- I am on Windows 8.1;
- The project uses CMake, generating makefiles and using MinGW's make (4.3) to build;
- CMake's Emscripten-related arguments are:
```
-DCMAKE_TOOLCHAIN_FILE="D:/Emscripten/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake"
-DCMAKE_CROSSCOMPILING_EMULATOR="D:/Emscripten/node/14.18.2_64bit/bin/node.exe"
```
- Other build & link flags [are specified here](https://github.com/Razakhel/RaZ/blob/master/cmake/CompilerFlags.cmake#L236-L297).

Don't hesitate to ask for any missing information.

Thanks in advance!

---

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.1 (1934a98e709b57d3592b8272d3f1264a72c089e4)
clang version 14.0.0 (https://github.com/llvm/llvm-project f142c45f1e494f8dbdcc1bcf14122d128ac8f3fe)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: D:\Emscripten\upstream\bin
```

**Failing command line in full:**
Output with verbose make:
```cpp
D:/MinGW64/bin/mingw32-make.exe  -f examples\CMakeFiles\RaZ_MinDemo.dir\build.make examples/CMakeFiles/RaZ_MinDemo.dir/build
mingw32-make[3]: Entering directory 'D:/Dropbox/GitHub/RaZ/build-emscripten/Release'
[ 97%] Linking CXX executable RaZ_MinDemo.html
cd /d D:\Dropbox\GitHub\RaZ\build-emscripten\Release\examples && "D:\Program Files (x86)\JetBrains\Toolbox\apps\CLion\ch-0\213.6461.75\bin\cmake\win\bin\cmake.exe" -E cmake_link_script CMakeFiles\RaZ_MinDemo.dir\link.txt --verbose=1
D:\Emscripten\upstream\emscripten\em++.bat -O3 -DNDEBUG --preload-file D:/Dropbox/GitHub/RaZ/assets/meshes/ball.obj@assets/meshes/ball.obj --preload-file D:/Dropbox/GitHub/RaZ/assets/materials/test.mtl@assets/materials/test.mtl --preload-file D:/Dropbox/GitHub/RaZ/assets/textures/rustediron_albedo.png@assets/textures/rustediron_albedo.png --preload-file D:/Dropbox/GitHub/RaZ/assets/textures/rustediron_normal.png@assets/textures/rustediron_normal.png --preload-file D:/Dropbox/GitHub/RaZ/assets/textures/rustediron_metallic.png@assets/textures/rustediron_metallic.png --preload-file D:/Dropbox/GitHub/RaZ/assets/textures/rustediron_roughness.png@assets/textures/rustediron_roughness.png --preload-file D:/Dropbox/GitHub/RaZ/shaders/opengles3@shaders -s ALLOW_MEMORY_GROWTH=1 -s USE_WEBGL2=1 -s OFFSCREEN_FRAMEBUFFER=1 -s OFFSCREENCANVAS_SUPPORT=1 -s DISABLE_EXCEPTION_CATCHING=0 -s USE_GLFW=3 -s USE_LIBPNG=1 @CMakeFiles\RaZ_MinDemo.dir\objects1.rsp -o RaZ_MinDemo.html @CMakeFiles\RaZ_MinDemo.dir\linklibs.rsp
cache:INFO: generating system library: sysroot\lib\wasm32-emscripten\libc.a... (this will be cached in "D:\Emscripten\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\libc.a" for subsequent builds)
D:\Emscripten\upstream\emscripten\system\lib\libc\musl\src\misc\emscripten_pthread.c:7:26: error: too many arguments provided to function-like macro invocation
pthread_t __pthread_self(void) {
                         ^
D:\Emscripten\upstream\emscripten\system\lib\libc\musl\src\internal\pthread_impl.h:141:9: note: macro '__pthread_self' defined here
#define __pthread_self() ((pthread_t)__get_tp())
        ^
D:\Emscripten\upstream\emscripten\system\lib\libc\musl\src\misc\emscripten_pthread.c:7:25: error: expected ';' after top level declarator
pthread_t __pthread_self(void) {
                        ^
                        ;
2 errors generated.
emcc: error: 'D:/Emscripten/upstream/bin\clang.exe -target wasm32-unknown-emscripten -DEMSCRIPTEN -fignore-exceptions -fno-inline-functions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=1 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=D:\Emscripten\upstream\emscripten\cache\sysroot -Xclang -iwithsysroot/include\compat -O2 -Werror -fno-unroll-loops -std=c99 -D_XOPEN_SOURCE=700 -Wno-unused-result -Os -fno-builtin -Wno-ignored-attributes -Wno-macro-redefined -Wno-shift-op-parentheses -Wno-string-plus-int -Wno-pointer-sign -g -ID:\Emscripten\upstream\emscripten\system\lib\libc\musl\src\internal -ID:\Emscripten\upstream\emscripten\system\lib\libc\musl\src\include -ID:\Emscripten\upstream\emscripten\system\lib\pthread -DNDEBUG -c D:\Emscripten\upstream\emscripten\system\lib\libc\musl\src\misc\emscripten_pthread.c -o D:\Emscripten\upstream\emscripten\cache\build\libc\emscripten_pthread.o' failed (returned 1)
Traceback (most recent call last):
  File "D:\Emscripten\upstream\emscripten\\em++.py", line 14, in <module>
    sys.exit(emcc.run(sys.argv))
  File "D:\Emscripten\upstream\emscripten\emcc.py", line 1138, in run
    phase_calculate_system_libraries(state, linker_arguments, linker_inputs, newargs)
  File "D:\Python\Python37\lib\contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "D:\Emscripten\upstream\emscripten\emcc.py", line 2630, in phase_calculate_system_libraries
    extra_files_to_link += system_libs.calculate([f for _, f in sorted(linker_inputs)] + extra_files_to_link, forced=state.forced_stdlibs)
  File "D:\Emscripten\upstream\emscripten\tools\system_libs.py", line 1739, in calculate
    add_library('libc')
  File "D:\Emscripten\upstream\emscripten\tools\system_libs.py", line 1696, in add_library
    libs_to_link.append((lib.get_link_flag(), need_whole_archive))
  File "D:\Emscripten\upstream\emscripten\tools\system_libs.py", line 321, in get_link_flag
    fullpath = self.get_path()
  File "D:\Emscripten\upstream\emscripten\tools\system_libs.py", line 313, in get_path
    return shared.Cache.get_lib(self.get_filename(), self.build)
  File "D:\Emscripten\upstream\emscripten\tools\cache.py", line 139, in get_lib
    return self.get(name, *args, **kwargs)
  File "D:\Emscripten\upstream\emscripten\tools\cache.py", line 167, in get
    creator(cachename)
  File "D:\Emscripten\upstream\emscripten\tools\system_libs.py", line 393, in build
    create_lib(out_filename, self.build_objects(build_dir))
  File "D:\Emscripten\upstream\emscripten\tools\system_libs.py", line 386, in build_objects
    run_build_commands(commands)
  File "D:\Emscripten\upstream\emscripten\tools\system_libs.py", line 72, in run_build_commands
    shared.run_multiple_processes(commands, env=clean_env())
  File "D:\Emscripten\upstream\emscripten\tools\shared.py", line 208, in run_multiple_processes
    raise Exception('Subprocess %d/%d failed (%s)! (cmdline: %s)' % (idx + 1, len(commands), returncode_to_str(finished_process.returncode), shlex_join(commands[idx])))
Exception: Subprocess 405/945 failed (returned 1)! (cmdline: D:\Emscripten\upstream\emscripten\emcc.bat -O2 -Werror -fno-unroll-loops -std=c99 -D_XOPEN_SOURCE=700 -Wno-unused-result -Os -fno-builtin -Wno-ignored-attributes -Wno-macro-redefined -Wno-shift-op-parentheses -Wno-string-plus-int -Wno-pointer-sign -g -ID:\Emscripten\upstream\emscripten\system\lib\libc\musl\src\internal -ID:\Emscripten\upstream\emscripten\system\lib\libc\musl\src\include -ID:\Emscripten\upstream\emscripten\system\lib\pthread -DNDEBUG -c D:\Emscripten\upstream\emscripten\system\lib\libc\musl\src\misc\emscripten_pthread.c -o D:\Emscripten\upstream\emscripten\cache\build\libc\emscripten_pthread.o)
mingw32-make[3]: *** [examples\CMakeFiles\RaZ_MinDemo.dir\build.make:103: examples/RaZ_MinDemo.html] Error 1
mingw32-make[2]: *** [CMakeFiles\Makefile2:358: examples/CMakeFiles/RaZ_MinDemo.dir/all] Error 2
mingw32-make[1]: *** [CMakeFiles\Makefile2:365: examples/CMakeFiles/RaZ_MinDemo.dir/rule] Error 2
mingw32-make: *** [Makefile:262: RaZ_MinDemo] Error 2
```

**Full link command and output with `-v` appended:**
Adding `-v` to the link options changes nothing to the output above.

**Comment by kripken** [comment]
I don't have a guess what could cause this weird error. As it is a regression, I think if you bisect it that would be the fastest way to find the underlying issue,

https://emscripten.org/docs/contributing/developers_guide.html#bisecting

**Comment by sbc100** [comment]
The problem seems to be the file `system\lib\libc\musl\src\misc\emscripten_pthread.c`... 

That file was removed from emscripten about a year ago in #13268.   Any idea how it might have some to exist in `upstream/emscripten`?    Are you doing anything to the `upstream/emscripten` directory?  Is it coming from emsdk?

You could try completely removing the upstream directory and re-installing.. although that won't solve the mystery as to why you seem to have an ancient file there.

**Comment by Razakhel** [comment]
`emscripten_pthread.c` was indeed marked as last modified in 2020... Deleting it did fix this issue, but another arose:
```
cache:INFO: generating system library: sysroot\lib\wasm32-emscripten\libc-debug.a... (this will be cached in "D:\Emscripten\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\libc-debug.a" for subsequent builds)
In file included from D:\Emscripten\upstream\emscripten\system\lib\libc\musl\src\misc\forkpty.c:1:
In file included from D:\Emscripten\upstream\emscripten\cache\sysroot/include\pty.h:9:
In file included from D:\Emscripten\upstream\emscripten\cache\sysroot/include\sys/ioctl.h:10:
D:\Emscripten\upstream\emscripten\cache\sysroot/include\bits/ioctl.h:90:8: error: redefinition of 'winsize'
struct winsize {
       ^
D:\Emscripten\upstream\emscripten\cache\sysroot/include\bits/alltypes.h:428:8: note: previous definition is here
struct winsize { unsigned short ws_row, ws_col, ws_xpixel, ws_ypixel; };
       ^
1 error generated.
```
All related files are this time marked as modified in 2022, so that probably is not the same problem again.

---

I've had Emscripten installed since about 2 years; as per what is explained on the [download & install page](https://emscripten.org/docs/getting_started/downloads.html), I update it with:
```
git pull
emsdk install latest
emsdk activate latest
```
All of this does come from emsdk, and as far as I recall I have never modified anything in the upstream folder.

I will probably try to make a fresh reinstall then, thank you for your time!
