### ISSUE TITLE
Missing _lzma.cpython-39-darwin.so on emsdk 3.1.1 with Python 3.9.2-1_64bit

### ISSUE THREAD

**Issue by sbehnke** [emscripten-core/emscripten#16073]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.1 (1934a98e709b57d3592b8272d3f1264a72c089e4)
clang version 14.0.0 (https://github.com/llvm/llvm-project f142c45f1e494f8dbdcc1bcf14122d128ac8f3fe)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/sbehnke/Development/mobile/tools/emsdk/upstream/bin
```

**Failing command line in full:**
```
em++ -s USE_SDL_TTF=2 hello_world.cpp
cache:INFO: generating system headers: sysroot_install.stamp... (this will be cached in "/Users/sbehnke/Development/mobile/tools/emsdk/upstream/emscripten/cache/sysroot_install.stamp" for subsequent builds)
cache:INFO:  - ok
ports:INFO: retrieving port: freetype from https://github.com/emscripten-ports/FreeType/archive/version_1.zip
ports:INFO: unpacking port: freetype
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libfreetype.a... (this will be cached in "/Users/sbehnke/Development/mobile/tools/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libfreetype.a" for subsequent builds)
cache:INFO:  - ok
ports:INFO: retrieving port: sdl2 from https://github.com/libsdl-org/SDL/archive/release-2.0.18.zip
ports:INFO: unpacking port: sdl2
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libSDL2.a... (this will be cached in "/Users/sbehnke/Development/mobile/tools/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libSDL2.a" for subsequent builds)
cache:INFO:  - ok
ports:INFO: retrieving port: harfbuzz from https://github.com/harfbuzz/harfbuzz/releases/download/2.8.1/harfbuzz-2.8.1.tar.xz
ports:INFO: unpacking port: harfbuzz
Traceback (most recent call last):
  File "/Users/sbehnke/Development/mobile/tools/emsdk/upstream/emscripten/em++.py", line 14, in <module>
    sys.exit(emcc.run(sys.argv))
  File "/Users/sbehnke/Development/mobile/tools/emsdk/upstream/emscripten/emcc.py", line 1110, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/Users/sbehnke/Development/mobile/tools/emsdk/python/3.9.2-1_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/sbehnke/Development/mobile/tools/emsdk/upstream/emscripten/emcc.py", line 2602, in phase_compile_inputs
    compile_source_file(i, input_file)
  File "/Users/sbehnke/Development/mobile/tools/emsdk/upstream/emscripten/emcc.py", line 2582, in compile_source_file
    cmd = get_clang_command(input_file)
  File "/Users/sbehnke/Development/mobile/tools/emsdk/upstream/emscripten/emcc.py", line 2523, in get_clang_command
    return get_compiler(src_file) + get_cflags(state.orig_args) + compile_args + [src_file]
  File "/Users/sbehnke/Development/mobile/tools/emsdk/upstream/emscripten/emcc.py", line 898, in get_cflags
    ports.add_cflags(cflags, settings)
  File "/Users/sbehnke/Development/mobile/tools/emsdk/upstream/emscripten/tools/ports/__init__.py", line 364, in add_cflags
    port.get(Ports, settings, shared)
  File "/Users/sbehnke/Development/mobile/tools/emsdk/upstream/emscripten/tools/ports/harfbuzz.py", line 82, in get
    ports.fetch_project('harfbuzz', 'https://github.com/harfbuzz/harfbuzz/releases/download/' +
  File "/Users/sbehnke/Development/mobile/tools/emsdk/upstream/emscripten/tools/ports/__init__.py", line 259, in fetch_project
    unpack()
  File "/Users/sbehnke/Development/mobile/tools/emsdk/upstream/emscripten/tools/ports/__init__.py", line 232, in unpack
    shutil.unpack_archive(filename=fullpath, extract_dir=fullname)
  File "/Users/sbehnke/Development/mobile/tools/emsdk/python/3.9.2-1_64bit/lib/python3.9/shutil.py", line 1241, in unpack_archive
    raise ReadError("Unknown archive format '{0}'".format(filename))
shutil.ReadError: Unknown archive format '/Users/sbehnke/Development/mobile/tools/emsdk/upstream/emscripten/cache/ports/harfbuzz.8.1.tar.xz'
```

`_lzma.cpython-39-darwin.so` is missing from the provided python environment.

```
Python 3.9.2 (tags/v3.9.2:1a79785e3e, Mar 10 2021, 16:55:30) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lzma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sbehnke/Development/mobile/tools/emsdk/python/3.9.2-1_64bit/lib/python3.9/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
```

**Comment by sbehnke** [comment]
I am running on macOS 12.1 arm64. I was able to copy the `_lzma.cpython-39-darwin.so` from the Python 3.9.2 download and place it into the appropriate location, clear the python cache and then successfully extract the harfbuzz file.

**Comment by MrColour** [comment]
If you are getting an error like:

ports:INFO: retrieving port: harfbuzz from https://github.com/harfbuzz/harfbuzz/releases/download/2.8.1/harfbuzz-2.8.1.tar.xz
      ports:INFO: unpacking port: harfbuzz
      Traceback (most recent call last):
        File "/projectdir/emsdk/upstream/emscripten/emcc.py", line 3943, in <module>
          sys.exit(main(sys.argv))
When trying to build on a M1 mac (my macOS version: Ventura 13.3.1 (a)) when running an emcc line that includes USE_SDL_TTF=2 you can try setting the following shell or environment variable EMSDK_PYTHON=/path/to/system/python (https://www.purdue.edu/hla/sites/varalalab/wp-content/uploads/sites/20/2018/02/Lecture_5.pdf, basically run EMSDK_PYTHON=/path/to/system/python in the shell, you can also try EMSDK_PYTHON=/path/to/system/python3).

You will also want to ensure that your mac runs python, you can check this with the command which python or which python3 and you should get something like: /opt/homebrew/bin/python3.

When the command emcc compiles your program it will get the hint that to use the python path that was declared in the environment/shell EMSDK_PYTHON which should allow it to successfully compile harfbuzz-2.8.1 that is required when using SDL_ttf.
