### ISSUE TITLE
Error installing harfbuzz

### ISSUE THREAD

**Issue by Tam** [emscripten-core/emscripten#16097]
harfbuzz fails to install when using SDL_TTF due to archive extension `tar.xz`. Everything builds and runs correctly when not using SDL_TTF.

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.2 (a77b559a8b40b7e89fc8c17e41034128df9543e4)
clang version 14.0.0 (https://github.com/llvm/llvm-project 782c0dd1a1c235afb09a34e7da4a1267ead14765)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/tam/Developer/emsdk/upstream/bin

**Failing command line in full:**
```sh
emcc src/main.cpp \
	-s WASM=1 \
	-s USE_SDL=2 \
	-s USE_SDL_TTF=2 \
	-o build/index.html \
	--shell-file ./shell.html
```

```
ports:INFO: retrieving port: harfbuzz from https://github.com/harfbuzz/harfbuzz/releases/download/2.8.1/harfbuzz-2.8.1.tar.xz
ports:INFO: unpacking port: harfbuzz
Traceback (most recent call last):
  File "/Users/tam/Developer/emsdk/upstream/emscripten/emcc.py", line 3943, in <module>
    sys.exit(main(sys.argv))
  File "/Users/tam/Developer/emsdk/python/3.9.2-1_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/tam/Developer/emsdk/upstream/emscripten/emcc.py", line 3936, in main
    ret = run(args)
  File "/Users/tam/Developer/emsdk/upstream/emscripten/emcc.py", line 1110, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/Users/tam/Developer/emsdk/python/3.9.2-1_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/tam/Developer/emsdk/upstream/emscripten/emcc.py", line 2616, in phase_compile_inputs
    compile_source_file(i, input_file)
  File "/Users/tam/Developer/emsdk/upstream/emscripten/emcc.py", line 2596, in compile_source_file
    cmd = get_clang_command(input_file)
  File "/Users/tam/Developer/emsdk/upstream/emscripten/emcc.py", line 2537, in get_clang_command
    return get_compiler(src_file) + get_cflags(state.orig_args) + compile_args + [src_file]
  File "/Users/tam/Developer/emsdk/upstream/emscripten/emcc.py", line 898, in get_cflags
    ports.add_cflags(cflags, settings)
  File "/Users/tam/Developer/emsdk/upstream/emscripten/tools/ports/__init__.py", line 364, in add_cflags
    port.get(Ports, settings, shared)
  File "/Users/tam/Developer/emsdk/upstream/emscripten/tools/ports/harfbuzz.py", line 82, in get
    ports.fetch_project('harfbuzz', 'https://github.com/harfbuzz/harfbuzz/releases/download/' +
  File "/Users/tam/Developer/emsdk/upstream/emscripten/tools/ports/__init__.py", line 259, in fetch_project
    unpack()
  File "/Users/tam/Developer/emsdk/upstream/emscripten/tools/ports/__init__.py", line 232, in unpack
    shutil.unpack_archive(filename=fullpath, extract_dir=fullname)
  File "/Users/tam/Developer/emsdk/python/3.9.2-1_64bit/lib/python3.9/shutil.py", line 1241, in unpack_archive
    raise ReadError("Unknown archive format '{0}'".format(filename))
shutil.ReadError: Unknown archive format '/Users/tam/Developer/emsdk/upstream/emscripten/cache/ports/harfbuzz.8.1.tar.xz'
```

**Comment by sbc100** [comment]
I believe this is a duplicate of #16073.   If you agree we can close this one.

**Comment by Tam** [comment]
Closed in favour of #16073.

**Comment by MrColour** [comment]
Potential fix on M1 macs using SDL_ttf2 due to harfbuzz failure:

https://github.com/emscripten-core/emscripten/issues/16073#issuecomment-1546493030
