### ISSUE TITLE
pthread: side module calling thread using std::function, RuntimeError: null function or function signature mismatch

### ISSUE THREAD

**Issue by sps-gold** [emscripten-core/emscripten#16133]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.2 (a77b559a8b40b7e89fc8c17e41034128df9543e4)
clang version 14.0.0 (https://github.com/llvm/llvm-project 782c0dd1a1c235afb09a34e7da4a1267ead14765)
Target: wasm32-unknown-emscripten
Thread model: posix

```
**Failing command line in full:**
Runtime failure
```
em++ side.cpp -o side.wasm -sSIDE_MODULE=2 -pthread -sPTHREAD_POOL_SIZE=1
em++ main.cpp -sMAIN_MODULE=2 side.wasm -sEXIT_RUNTIME -pthread -sPTHREAD_POOL_SIZE=1
```

**Full link command and output with `-v` appended:**
```
 "/home/sps/Source/github/sps-gold/emsdk/upstream/bin/clang++" -target wasm32-unknown-emscripten -DEMSCRIPTEN -fignore-exceptions -fPIC -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=2 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/home/sps/Source/github/sps-gold/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -pthread -v main.cpp -c -o /tmp/emscripten_temp_d1xbnfxw/main_0.o
clang version 14.0.0 (https://github.com/llvm/llvm-project 782c0dd1a1c235afb09a34e7da4a1267ead14765)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/sps/Source/github/sps-gold/emsdk/upstream/bin
 (in-process)
 "/home/sps/Source/github/sps-gold/emsdk/upstream/bin/clang-14" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name main.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-feature +atomics -target-feature +bulk-memory -target-feature +mutable-globals -target-feature +sign-ext -target-feature +mutable-globals -target-cpu generic -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/sps/Learn/proj3 -resource-dir /home/sps/Source/github/sps-gold/emsdk/upstream/lib/clang/14.0.0 -D EMSCRIPTEN -D __EMSCRIPTEN_major__=3 -D __EMSCRIPTEN_minor__=1 -D __EMSCRIPTEN_tiny__=2 -D _LIBCPP_ABI_VERSION=2 -isysroot /home/sps/Source/github/sps-gold/emsdk/upstream/emscripten/cache/sysroot -internal-isystem /home/sps/Source/github/sps-gold/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1 -internal-isystem /home/sps/Source/github/sps-gold/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1 -internal-isystem /home/sps/Source/github/sps-gold/emsdk/upstream/lib/clang/14.0.0/include -internal-isystem /home/sps/Source/github/sps-gold/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten -internal-isystem /home/sps/Source/github/sps-gold/emsdk/upstream/emscripten/cache/sysroot/include -Werror=implicit-function-declaration -fdeprecated-macro -fdebug-compilation-dir=/home/sps/Learn/proj3 -ferror-limit 19 -fvisibility default -pthread -fgnuc-version=4.2.1 -fcxx-exceptions -fignore-exceptions -fexceptions -fcolor-diagnostics -iwithsysroot/include/SDL -iwithsysroot/include/compat -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /tmp/emscripten_temp_d1xbnfxw/main_0.o -x c++ main.cpp
clang -cc1 version 14.0.0 based upon LLVM 14.0.0git default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/home/sps/Source/github/sps-gold/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1"
ignoring nonexistent directory "/home/sps/Source/github/sps-gold/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 /home/sps/Source/github/sps-gold/emsdk/upstream/emscripten/cache/sysroot/include/SDL
 /home/sps/Source/github/sps-gold/emsdk/upstream/emscripten/cache/sysroot/include/compat
 /home/sps/Source/github/sps-gold/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1
 /home/sps/Source/github/sps-gold/emsdk/upstream/lib/clang/14.0.0/include
 /home/sps/Source/github/sps-gold/emsdk/upstream/emscripten/cache/sysroot/include
End of search list.
em++: warning: -s MAIN_MODULE + pthreads is experimental [-Wexperimental]
 "/home/sps/Source/github/sps-gold/emsdk/upstream/bin/wasm-ld" @/tmp/emscripten_jd8drzqr.rsp.utf-8
 "/home/sps/Source/github/sps-gold/emsdk/upstream/bin/wasm-emscripten-finalize" --minimize-wasm-changes --dyncalls-i64 --pass-arg=legalize-js-interface-export-originals a.out.wasm -o a.out.wasm --detect-features
 "/home/sps/Source/github/sps-gold/emsdk/node/14.18.2_64bit/bin/node" /home/sps/Source/github/sps-gold/emsdk/upstream/emscripten/src/compiler.js /tmp/tmp3lje41cn.json
 "/home/sps/Source/github/sps-gold/emsdk/upstream/bin/llvm-objcopy" a.out.wasm a.out.wasm --remove-section=.debug* --remove-section=producers
 "/home/sps/Source/github/sps-gold/emsdk/node/14.18.2_64bit/bin/node" /home/sps/Source/github/sps-gold/emsdk/upstream/emscripten/tools/preprocessor.js /tmp/emscripten_temp_d1xbnfxw/settings.js worker.js --expandMacros
```

node --version
v17.4.0
node a.out.js --experimental-wasm-threads

```
exiting due to exception: RuntimeError: null function or function signature mismatch,RuntimeError: null function or function signature mismatch
    at std::__2::__function::__value_func<void (std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >)>::__value_func(std::__2::__function::__value_func<void (std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >)> const&).1 (wasm://wasm/0011808e:wasm-function[474]:0x14e80)
    at stubs.<computed> (/home/sps/Learn/proj3/a.out.js:2622:33)
    at std::__2::function<void (std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >)>::function(std::__2::function<void (std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >)> const&).1 (wasm://wasm/0011808e:wasm-function[458]:0x14857)
    at stubs.<computed> (/home/sps/Learn/proj3/a.out.js:2622:33)
    at std::__2::decay<std::__2::function<void (std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >)>&>::type std::__2::__decay_copy<std::__2::function<void (std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >)>&>(std::__2::function<void (std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >)>&).1 (wasm://wasm/0011808e:wasm-function[294]:0x1100d)
    at stubs.<computed> (/home/sps/Learn/proj3/a.out.js:2622:33)
    at std::__2::thread::thread<std::__2::function<void (std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >)>&, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >, void>(std::__2::function<void (std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >)>&, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >&&).1 (wasm://wasm/0011808e:wasm-function[285]:0x10c84)
    at callme() (wasm://wasm/0011808e:wasm-function[282]:0x10ab3)
    at sidey (wasm://wasm/0011808e:wasm-function[306]:0x11496)
    at __original_main (wasm://wasm/00186b22:wasm-function[34]:0x7729)
```

**source**
[proj3.zip](https://github.com/emscripten-core/emscripten/files/7956691/proj3.zip)

**Comment by sps-gold** [comment]
this works if thread is created in main module
ps: I see a similar output reported [here](https://github.com/emscripten-core/emscripten/issues/15953) on webgl

**Comment by sps-gold** [comment]
update: this appears fixed and can be closed.
As tested with
```
emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.15 (8b4443a87f5eab5dbb9adb690f9ebed0a9da4bd9)

\proj3>node --version
v18.1.0

\proj3>node a.out.js --experimental-wasm-threads
hello
```
