### ISSUE TITLE
how can I debug function signature mismatch ?

### ISSUE THREAD

**Issue by vertexpotato** [emscripten-core/emscripten#16305]
I have an application that uses pthreads, and when I build with ```-s PROXY_TO_PTHREAD```

I get the following runtime error :
```Runtime.wasm:0xa738cb Uncaught RuntimeError: null function or function signature mismatch
    at _do_call (Runtime.wasm:0xa738cb)
    at emscripten_current_thread_process_queued_calls (Runtime.wasm:0xa724bd)
    at emscripten_main_thread_process_queued_calls (Runtime.wasm:0xa74c49)
    at ret.<computed> (Runtime.js:18705:24)
    at Runtime.js:1649:20
    at Worker.worker.onmessage (Runtime.js:2064:5)```

I don't even know where it fails. anyone has any idea on how I can debug it ?

program is linked with the following link options : 
```
"-O3", "-s SAFE_HEAP", "-s ASSERTIONS=1","-s ALLOW_MEMORY_GROWTH=1", "-s PTHREAD_POOL_SIZE=3", "-s ASYNCIFY", "-pthread", "-s ASYNCIFY_IMPORTS=['doLoadLibrary']","-s ALLOW_TABLE_GROWTH", "-s USE_PTHREADS=1", "-s PROXY_TO_PTHREAD", "-s EXPORTED_RUNTIME_METHODS=['FS']", "-s DYNCALLS=1","-s MAIN_MODULE=1", "-s USE_WEBGL2=1", "-s FULL_ES3=1", "-s OFFSCREEN_FRAMEBUFFER=1","-s FORCE_FILESYSTEM=1", "--profiling", "--pre-js="
```

**Comment by hoodmane** [comment]
My usual approach to this: 

1. Add your startup:
```js
  EM_ASM({ Module.wasmTable = wasmTable; });
```
preferably right at the top to expose the function pointer table.

2. Open your application in chrome and trigger the error

3. In the traceback as formatted above, click on `Runtime.wasm:0xa738cb`. Hopefully it will take you to the location in the webassembly where the error occurred. This should be a `call_indirect` instruction. If your wasm is really long, you might get the "long source is truncated" message which is bad.

4. set a breakpoint in the debugger on the call_indirect instruction

5. Refresh the page and trigger the bug again, it should break at the `call_indirect` instruction. Confirm with step once that the code will crash on this pass, refresh again and trigger again

6. Look at the call stack:

![Screenshot from 2022-02-16 13-26-37-mod](https://user-images.githubusercontent.com/8739626/154332484-4f923581-0e7d-4643-b8ad-1fac7f467d57.png)
The stack will have in position 0 the first argument of the function, in position 1 the second argument of the function, etc. Probably the last argument in the argument stack will be the function pointer, you can check by counting the number of arguments. In the screenshot the function is `call_indirect (param i32 i32)(result i32)` so there are two arguments and the third thing on the stack is the function pointer. So in this case the function pointer is `152`.


7. Run `Module.wasmTable.get(function_ptr)`.
![Screenshot from 2022-02-16 13-37-27-mod](https://user-images.githubusercontent.com/8739626/154333332-3ef7d8b5-5578-4bfd-84ad-7b6274e11054.png)
Then you see `$function_name` so that tells you what the function is called. You can click on `function_name` and it will take you to the source. In this case I see `func $PyType_GenericAlloc (;2233;) (export "PyType_GenericAlloc") (param $var0 i32) (param $var1 i32) (result i32)`, so the function is indeed of type `(param i32 i32)(result i32)`. So there won't be an indirect call mismatch error. In an actual example, the call signature you see will be different than the call signature that `call_indirect` declares.

**Comment by kleisauke** [comment]
For C code, you can detect such issues at compile-time by enabling the `-Wbad-function-cast -Wcast-function-type` warnings. See: https://github.com/emscripten-core/emscripten/issues/16126#issuecomment-1023067658.

**Comment by oelmekki** [comment]
Sorry if what I'm going to say is not really related to the initial issue, nor even really to EMscripten itself, but this page is actually the most useful information I found on debugging WASM, so I figure this may be useful to other people reaching this page for it:

if you can't easily change sources to expose WebAssembly's table like mentioned in step 1 from the post of Hoodmane, you can find it in the inspector in the same panel than the stack, in `Module > table`:

![table](https://github.com/user-attachments/assets/a0df40f5-98f7-418e-a3f4-a58c97796a99)

The `[[FunctionLocation]]` reference is clickable as well.

I'm debugging Pyodide on top of EMscripten, so it's still possible they're the ones setting this up, though - hopefully the table is exposed like this for everybody.
