### ISSUE TITLE
Something wrong when embind a structure has long long type items, shown error "UnboundTypeError, ... due to unbound types: x"

### ISSUE THREAD

**Issue by juliuming** [emscripten-core/emscripten#16457]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.6

**Failing command line in full:**
UnboundTypeError {name: 'UnboundTypeError', message: 'Cannot construct IntPoint due to unbound types: x', stack: 'UnboundTypeError: Cannot construct IntPoint due to…864:14), <anonymous>:4:34)\n    at <anonymous>:1:8'}
message: "Cannot construct IntPoint due to unbound types: x"
name: "UnboundTypeError"
stack: "UnboundTypeError: Cannot construct IntPoint due to unbound types: x\n    at UnboundTypeError.<anonymous> (http://127.0.0.1:5500/build/hello.js:1877:24)\n    at new UnboundTypeError (eval at createNamedFunction (http://127.0.0.1:5500/build/hello.js:1864:14), <anonymous>:4:

** The demo is like:
```
#include <iostream>
typedef signed long long cInt;
class IntPoint {
   public:
    cInt X;
    cInt Y;
    IntPoint(cInt x = 0,cInt y = 0)
        {X=x; Y=y;};
};
```

bindings:
```
class_<IntPoint>("IntPoint")
      .constructor<cInt, cInt>()
      .property("X", &IntPoint::X)
      .property("Y", &IntPoint::Y);
```

**Comment by juliuming** [comment]
I think i have got the solution. Just add `WASM_BIGINT` option to solve it.
The command like
`emcc --bind -s WASM_BIGINT xx.o -o xx.js`
