### ISSUE TITLE
--closure 1 breaks threads when WASM is set to 0 and PROXY_TO_PTHREAD is set to 1

### ISSUE THREAD

**Issue by Username404-59** [emscripten-core/emscripten#16706]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.8 (3ff7eff373d31d8c0179895165462019221f192e)
clang version 15.0.0 (https://github.com/llvm/llvm-project 80ec0ebfdc5692a58e0832125f2c6a991df9d63f)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Output with `-v` appended:**
```
 "/home/doggo/Apps/emsdk/upstream/bin/wasm-ld" -o test.wasm CMakeFiles/test.dir/src/main.cpp.o CMakeFiles/test.dir/src/etc/filefuncs.cpp.o CMakeFiles/test.dir/src/etc/lexer.cpp.o -L/home/doggo/Apps/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/thinlto /home/doggo/Apps/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/thinlto/crtbegin.o -lGL-mt -lal -lhtml5 -lstubs -lc-mt -ldlmalloc-mt -lcompiler_rt-mt -lc++-mt -lc++abi-mt -lsockets-mt -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --import-memory --shared-memory --strip-debug --export-if-defined=main --export-if-defined=_emscripten_thread_init --export-if-defined=_emscripten_thread_exit --export-if-defined=_emscripten_thread_crashed --export-if-defined=emscripten_tls_init --export-if-defined=pthread_self --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__stdio_exit --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export=emscripten_dispatch_to_thread_ --export=_emscripten_thread_free_data --export=_emscripten_allow_main_runtime_queued_calls --export=emscripten_main_browser_thread_id --export=emscripten_main_thread_process_queued_calls --export=emscripten_run_in_main_runtime_thread_js --export=emscripten_stack_set_limits --export=emscripten_builtin_memalign --export=emscripten_proxy_main --export=__funcs_on_exit --export=malloc --export=free --export=__cxa_is_pointer_type --export=__cxa_can_catch --export=setThrew --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024
 "/home/doggo/Apps/emsdk/upstream/bin/wasm-emscripten-finalize" --dyncalls-i64 test.wasm -o test.wasm --detect-features
 "/usr/bin/node" /home/doggo/Apps/emsdk/upstream/emscripten/src/compiler.js /tmp/tmp90x0hgsu.json
 "/home/doggo/Apps/emsdk/upstream/bin/wasm-opt" --strip-dwarf --post-emscripten -Os --low-memory-unused --zero-filled-memory --strip-debug --strip-producers test.wasm -o test.wasm --mvp-features --enable-threads --enable-mutable-globals --enable-bulk-memory --enable-sign-ext
 "/usr/bin/node" /home/doggo/Apps/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/emscripten_temp_l5dvllbs/test.js AJSDCE --closureFriendly
 "/usr/bin/node" /home/doggo/Apps/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/tmpb1t7tmtr.js emitDCEGraph noPrint --closureFriendly
 "/home/doggo/Apps/emsdk/upstream/bin/wasm-metadce" --graph-file=/tmp/tmp7i75_bkv.txt test.wasm -o test.wasm --mvp-features --enable-threads --enable-mutable-globals --enable-bulk-memory --enable-sign-ext
 "/usr/bin/node" /home/doggo/Apps/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/tmps49jhiay.js applyDCEGraphRemovals --closureFriendly
 "/usr/bin/node" /home/doggo/Apps/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/emscripten_temp_l5dvllbs/test.js.jso.js.jso.js AJSDCE --closureFriendly
 "/home/doggo/Apps/emsdk/upstream/bin/wasm-opt" --strip-dwarf --minify-imports-and-exports-and-modules test.wasm -o test.wasm --mvp-features --enable-threads --enable-mutable-globals --enable-bulk-memory --enable-sign-ext
 "/usr/bin/node" /home/doggo/Apps/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/tmpa22sjlkk.js applyImportAndExportNameChanges --closureFriendly
 "/usr/bin/node" --max_old_space_size=8192 /home/doggo/Apps/emsdk/upstream/emscripten/node_modules/.bin/google-closure-compiler --compilation_level ADVANCED_OPTIMIZATIONS --language_in ECMASCRIPT_2020 --language_out NO_TRANSPILE --emit_use_strict=false --externs /home/doggo/Apps/emsdk/upstream/emscripten/src/closure-externs/closure-externs.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/src/closure-externs/node-externs.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/domain.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/readline.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/util.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/http.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/events.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/cluster.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/repl.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/vm.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/path.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/zlib.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/tty.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/url.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/dns.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/fs.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/net.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/https.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/buffer.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/string_decoder.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/os.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/punycode.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/tls.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/dgram.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/child_process.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/querystring.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/core.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/process.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/assert.js --externs /home/doggo/Apps/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/stream.js --js /tmp/emscripten_temp_l5dvllbs/test.js.jso.js.jso.js.jso.js.jso.js --js_output_file tmpgvgxeglp.cc.js
 "/home/doggo/Apps/emsdk/upstream/bin/wasm2js" --emscripten -O test.wasm --mvp-features --enable-threads --enable-mutable-globals --enable-bulk-memory --enable-sign-ext
 "/usr/bin/node" /home/doggo/Apps/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/tmpf23h1nbb.jsfunc_0.js minifyWhitespace last
 "/usr/bin/node" /home/doggo/Apps/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/tmporihdtmp.jsfunc_1.js minifyWhitespace last
 "/usr/bin/node" /home/doggo/Apps/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/tmplqiofec4.jsfunc_2.js minifyWhitespace last
 "/usr/bin/node" /home/doggo/Apps/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/tmpi1lvip67.jsfunc_3.js minifyWhitespace last
 "/usr/bin/node" /home/doggo/Apps/emsdk/upstream/emscripten/tools/preprocessor.js /tmp/emscripten_temp_l5dvllbs/settings.js worker.js --expandMacros
 "/usr/bin/node" /home/doggo/Apps/emsdk/upstream/emscripten/tools/acorn-optimizer.js /home/doggo/CLionProjects/Test/cmake-build-release-emscripten/test.worker.js minifyWhitespace --closureFriendly
```

With the following linker flags: `--closure 1 -sWASM=0 -sEXIT_RUNTIME=1 -sPROXY_TO_PTHREAD`, the program fails with the following error:
```
Module.instantiateWasm callback failed with error: TypeError: WebAssembly.Instance is not a constructor
worker.js onmessage() captured an uncaught exception: TypeError: Cannot read properties of undefined (reading 'ua')
TypeError: Cannot read properties of undefined (reading 'ua')
    at Object.f.__emscripten_thread_init (eval at importScripts (/home/doggo/CLionProjects/Test/cmake-build-release-emscripten/test.worker.js:1:510), <anonymous>:365:89)
    at self.onmessage (/home/doggo/CLionProjects/Test/cmake-build-release-emscripten/test.worker.js:1:1742)
    at MessagePort.<anonymous> (/home/doggo/CLionProjects/Test/cmake-build-release-emscripten/test.worker.js:1:307)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
worker sent an error! undefined:undefined: Cannot read properties of undefined (reading 'va')
```
However, if `--closure 1` is removed, the program works fine.

**Comment by kripken** [comment]
This works at least on hello world,
```
./emcc tests/hello_world.c --closure 1 -sWASM=0 -sEXIT_RUNTIME=1 -sPROXY_TO_PTHREAD -pthread
```
So we probably need a full testcase here.

**Comment by Username404-59** [comment]
I doubt hello world actually uses threads, so yeah.

**Comment by Username404-59** [comment]
> This works at least on hello world,
> 
> ```
> ./emcc tests/hello_world.c --closure 1 -sWASM=0 -sEXIT_RUNTIME=1 -sPROXY_TO_PTHREAD -pthread
> ```
> 
> So we probably need a full testcase here.

I compiled and ran the following example:
```
#include <iostream>

using namespace std;

int main(int argc, char* argv[]) {
    cout << "Hello, World!\n";
}
```
and the program failed with (nearly) the same error:
```
Module.instantiateWasm callback failed with error: TypeError: WebAssembly.Instance is not a constructor
worker.js onmessage() captured an uncaught exception: TypeError: Cannot read properties of undefined (reading 'emscripten_stack_init')
TypeError: Cannot read properties of undefined (reading 'emscripten_stack_init')
    at e._emscripten_stack_init (eval at importScripts (/home/doggo/HelloWorldTest/test/a.out.worker.js:39:16), <anonymous>:52306:49)
    at cd (eval at importScripts (/home/doggo/HelloWorldTest/test/a.out.worker.js:39:16), <anonymous>:52606:9)
    at eval (eval at importScripts (/home/doggo/HelloWorldTest/test/a.out.worker.js:39:16), <anonymous>:52659:1)
    at eval (<anonymous>)
    at importScripts (/home/doggo/HelloWorldTest/test/a.out.worker.js:39:16)
    at self.onmessage (/home/doggo/HelloWorldTest/test/a.out.worker.js:105:9)
    at MessagePort.<anonymous> (/home/doggo/HelloWorldTest/test/a.out.worker.js:25:5)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
Aborted(Assertion failed: native function `_emscripten_thread_crashed` called before runtime initialization)
Pthread 0x00505c10 sent an error! undefined:undefined: Aborted(Assertion failed: native function `_emscripten_thread_crashed` called before runtime initialization)

/home/doggo/HelloWorldTest/test/a.out.js:62
      throw b;
      ^
Error: Aborted(Assertion failed: native function `_emscripten_thread_crashed` called before runtime initialization)
    at A (eval at importScripts (/home/doggo/HelloWorldTest/test/a.out.worker.js:39:16), <anonymous>:50775:9)
    at assert (eval at importScripts (/home/doggo/HelloWorldTest/test/a.out.worker.js:39:16), <anonymous>:50562:8)
    at Object.eval [as __emscripten_thread_crashed] (eval at importScripts (/home/doggo/HelloWorldTest/test/a.out.worker.js:39:16), <anonymous>:50781:5)
    at self.onmessage (/home/doggo/HelloWorldTest/test/a.out.worker.js:192:44)
    at MessagePort.<anonymous> (/home/doggo/HelloWorldTest/test/a.out.worker.js:25:5)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
```

**Comment by kripken** [comment]
Oh, right, it does fail on hello world - for some reason I misread this as a compile-time closure error. But it indeed fails at runtime.

I think the problem is that in WASM=0 mode the polyfill for the WebAssembly object is defined in `*.js`, and `*.worker.js` is a separate file. If the first is optimized by closure, the second can't use it properly. 

This is the beginning of a patch, but it fails on a bunch of other closure issues, and I don't have the time to work through those atm. It would be great if someone has the time to fix those and submit a PR!

```diff
diff --git a/src/wasm2js.js b/src/wasm2js.js
index c944e4322..f3800fed6 100644
--- a/src/wasm2js.js
+++ b/src/wasm2js.js
@@ -61,8 +61,12 @@ WebAssembly = {
     // the main JS
   },
 
+  // Note that Instance must not be minified by closure as it will be used by
+  // workers in the case of pthreads: workers get the Module and will create an
+  // Instance of it, so WebAssembly.Instance is the one API they must be able to
+  // call.
   /** @constructor */
-  Instance: function(module, info) {
+  'Instance': function(module, info) {
     // TODO: use the module and info somehow - right now the wasm2js output is embedded in
     // the main JS
     // This will be replaced by the actual wasm2js code.
@@ -77,7 +81,7 @@ WebAssembly = {
 #if SHARED_MEMORY
           'module': module,
 #endif
-          'instance': new WebAssembly.Instance(module)
+          'instance': new WebAssembly['Instance'](module)
         });
 #if ASSERTIONS || WASM == 2 // see postamble_minimal.js which uses .catch
         // Emulate a simple WebAssembly.instantiate(..).then(()=>{}).catch(()=>{}) syntax.
diff --git a/tests/test_core.py b/tests/test_core.py
index 86e8d3bbd..2528e8c42 100644
--- a/tests/test_core.py
+++ b/tests/test_core.py
@@ -2576,6 +2576,11 @@ The current type of b is: 9
   def test_pthread_proxying(self):
     self.set_setting('EXIT_RUNTIME')
     self.set_setting('PROXY_TO_PTHREAD')
+    if self.is_wasm2js():
+      # Add one test of wasm2js + closure in the default test suites that run on
+      # the bots (they only run wasm2js1 atm, and by default we don't run
+      # closure on -O1 builds).
+      self.emcc_args += ['--closure=1']
     self.set_setting('INITIAL_MEMORY=32mb')
     args = [f'-I{path_from_root("system/lib/pthread")}']
     self.do_run_in_out_file_test('pthread/test_pthread_proxying.c',
```

**Comment by sbc100** [comment]
Adding the jules label to this old bug to see how it handles it..
