### ISSUE TITLE
memory leak in `test_exceptions_longjmp3_wasm`

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#17004]
```
$ ./tests/runner lsan.test_exceptions_longjmp3_wasm --save-dir
..
Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x9490 in malloc+0x9490 (test_exceptions_longjmp3.wasm+0x9490)
    #1 0x914 in test()+0x914 (test_exceptions_longjmp3.wasm+0x914)
    #2 0xa97 in __original_main+0xa97 (test_exceptions_longjmp3.wasm+0xa97)
    #3 0xb6f in main+0xb6f (test_exceptions_longjmp3.wasm+0xb6f)
    #4 0x8000054d  (JavaScript+0x54d)
    #5 0x800013ee in callMain /tmp/emscripten_test/test_exceptions_longjmp3.js:5102:15
    #6 0x80001427 in doRun /tmp/emscripten_test/test_exceptions_longjmp3.js:5159:23
```

Seems like there must be an internal allocation at setjmp that is not fee'd

Sadly we don't run this particular test on the releases waterfal because we don't have d8/v8 available there (which this test requires).

**Comment by aheejin** [comment]
Not sure what the cause was and what fixed it, but this was already working. #23552 re-enabled this test. Closing.
