### ISSUE TITLE
SSL error when building SDL2 project.

### ISSUE THREAD

**Issue by GGIEnrike** [emscripten-core/emscripten#17154]
I've been attempting to compile a blank SDL2 project to test Emscripten toolchain, but I keep getting SSL errors which I can't resolve, nothing I find on google helps. I am running Mac OSX.

Version of Emscripten:
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.13 (531257621816c200bc7c3be53129494afd029aec)
clang version 15.0.0 (https://github.com/llvm/llvm-project 5c6ed60c517c47b25b6b25d8ac3666d0e746b0c3)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/macbookair1/Development/emsdk/upstream/bin
```

The errors I get:
```
emcc -o "bin/web/index.html" src/*.cpp -Wall -g -lm -s USE_SDL=2
ports:INFO: retrieving port: sdl2 from https://github.com/libsdl-org/SDL/archive/4b8d69a41687e5f6f4b05f7fd9804dd9fcac0347.zip
Traceback (most recent call last):
  File "/Users/macbookair1/Development/emsdk/python/3.9.2_64bit/lib/python3.9/site-packages/urllib3/connectionpool.py", line 692, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/Users/macbookair1/Development/emsdk/python/3.9.2_64bit/lib/python3.9/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
    return conn or self._new_conn()
  File "/Users/macbookair1/Development/emsdk/python/3.9.2_64bit/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1009, in _new_conn
    raise SSLError(
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macbookair1/Development/emsdk/python/3.9.2_64bit/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/macbookair1/Development/emsdk/python/3.9.2_64bit/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/macbookair1/Development/emsdk/python/3.9.2_64bit/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /libsdl-org/SDL/archive/4b8d69a41687e5f6f4b05f7fd9804dd9fcac0347.zip (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macbookair1/Development/emsdk/upstream/emscripten/emcc.py", line 4054, in <module>
    sys.exit(main(sys.argv))
  File "/Users/macbookair1/Development/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/macbookair1/Development/emsdk/upstream/emscripten/emcc.py", line 4047, in main
    ret = run(args)
  File "/Users/macbookair1/Development/emsdk/upstream/emscripten/emcc.py", line 1136, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/Users/macbookair1/Development/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/macbookair1/Development/emsdk/upstream/emscripten/emcc.py", line 2739, in phase_compile_inputs
    compile_source_file(i, input_file)
  File "/Users/macbookair1/Development/emsdk/upstream/emscripten/emcc.py", line 2719, in compile_source_file
    cmd = get_clang_command(input_file)
  File "/Users/macbookair1/Development/emsdk/upstream/emscripten/emcc.py", line 2660, in get_clang_command
    return get_compiler(src_file) + get_cflags(state.orig_args) + compile_args + [src_file]
  File "/Users/macbookair1/Development/emsdk/upstream/emscripten/emcc.py", line 888, in get_cflags
    ports.add_cflags(cflags, settings)
  File "/Users/macbookair1/Development/emsdk/upstream/emscripten/tools/ports/__init__.py", line 364, in add_cflags
    port.get(Ports, settings, shared)
  File "/Users/macbookair1/Development/emsdk/upstream/emscripten/tools/ports/sdl2.py", line 23, in get
    ports.fetch_project('sdl2', 'https://github.com/libsdl-org/SDL/archive/' + TAG + '.zip', SUBDIR, sha512hash=HASH)
  File "/Users/macbookair1/Development/emsdk/upstream/emscripten/tools/ports/__init__.py", line 258, in fetch_project
    retrieve()
  File "/Users/macbookair1/Development/emsdk/upstream/emscripten/tools/ports/__init__.py", line 213, in retrieve
    response = requests.get(url)
  File "/Users/macbookair1/Development/emsdk/python/3.9.2_64bit/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/macbookair1/Development/emsdk/python/3.9.2_64bit/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/macbookair1/Development/emsdk/python/3.9.2_64bit/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/macbookair1/Development/emsdk/python/3.9.2_64bit/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/macbookair1/Development/emsdk/python/3.9.2_64bit/lib/python3.9/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /libsdl-org/SDL/archive/4b8d69a41687e5f6f4b05f7fd9804dd9fcac0347.zip (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
make: *** [build_web] Error 1
```

**Comment by sbc100** [comment]
I don't think we've seen that exact problem before.   It seems that the `_ssl` module is loadable from python for some reason.

That module should be installed within the emsdk version of python:

```
$ find . -iname _ssl*
./python/3.9.2_64bit/lib/python3.9/lib-dynload/_ssl.cpython-39-darwin.so
```

Can you try running `$EMSDK_PYTHON -c "import ssl"` and see what is reported?
