### ISSUE TITLE
Native wasm exceptions failing under recent d8

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#17278]
With the latest v8 from jsvu all the wasm exception tests a failing like this:

```
$ ./tests/runner wasm2.test_exceptions_3_wasm
warning: test suites in test_core.py have been renamed from `wasm` to `core`. Please use the new names
Test suites:
['test_core']
Running test_core: (1 tests)
(checking sanity from test runner)
shared:INFO: (Emscripten: Running sanity checks)
test_exceptions_3_wasm (test_core.core2) ... 0
-- begin program output --
Caught C string: a c string
exiting due to exception: RuntimeError: memory access out of bounds
-- end program output --
FAIL

======================================================================
FAIL: test_exceptions_3_wasm (test_core.core2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/common.py", line 354, in resulting_test
    return func(self, *args)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/test_core.py", line 112, in metafunc
    f(self)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/test_core.py", line 1383, in test_exceptions_3
    self.do_run(src, 'Caught C string: a c string\nDone.', args=['0'])
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/common.py", line 1136, in do_run
    return self._build_and_run(filename, expected_output, **kwargs)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/common.py", line 1194, in _build_and_run
    js_output = self.run_js(js_file, engine, args,
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tests/common.py", line 791, in run_js
    self.fail('JS subprocess failed (%s): %s.  Output:\n%s' % (error.cmd, error.returncode, ret))
AssertionError: JS subprocess failed (/usr/local/google/home/sbc/.jsvu/v8 --experimental-wasm-eh /tmp/emscripten_test_core2_3qgpzfo4/src.js --no-wasm-async-compilation -- 0): 1.  Output:
Caught C string: a c string
exiting due to exception: RuntimeError: memory access out of bounds


----------------------------------------------------------------------
Ran 1 test in 2.545s

FAILED (failures=1)
```

**Comment by aheejin** [comment]
Filed a bug in v8: https://bugs.chromium.org/p/v8/issues/detail?id=12983
