### ISSUE TITLE
Abort when using dlopen() in pthreads build; from _emscripten_thread_sync_code (dynlink.c)

### ISSUE THREAD

**Issue by msorvig** [emscripten-core/emscripten#17349]
Version: emsdk 3.1.12

Adding a call to dlopen() makes the included pthreads testing code crash. Note that actually calling dlopen() is not required; it is sufficient to make sure its implementation is included in the genrated JS runtime.

The sample code aborts with "To use dlopen, you need enable dynamic linking" from

>   at abort (main.js:1172:10)
>     at __dlopen_js (main.js:1872:2)
>     at _emscripten_thread_sync_code (dynlink.c:246)
>     at _emscripten_yield (emscripten_yield.c:45)
>     at emscripten_futex_wait (emscripten_futex_wait.c:116)
>     at __timedwait_cp (__timedwait.c:93)
>     at __timedwait (__timedwait.c:116)
>     at __pthread_mutex_timedlock (pthread_mutex_timedlock.c:89)
>     at __pthread_mutex_lock (pthread_mutex_lock.c:9)
>     at dlmalloc (dlmalloc.c:4638)

However, as noted above the sample code never calls dlopen(). Enabling SAFE_HEAP prints additional alignfault and segfault errors.

To reproduce, build the attached main.cpp with

> em++ main.cpp -o main.html -g -std=c++20 -pthread -sALLOW_MEMORY_GROWTH

[main.cpp.zip](https://github.com/emscripten-core/emscripten/files/9019612/main.cpp.zip)

**Comment by msorvig** [comment]
It's perhaps not an important distinction, but I'll try to clarify "included" vs "actually calling":

CrashEnabler would call dlopen() if its destructor ran. But it doesn't, because the example leaks the CrashEnabler object. So the code to call dlopen() included in the wasm file, but it never runs at runtime.

**Comment by msorvig** [comment]
I'm unfortunately quite unfamiliar with node - what's the easiest way to run it there?

**Comment by msorvig** [comment]
Yes, I can reproduce by running

`node  --experimental-wasm-threads  main.js`

This is when building and running on macOS/ARM . I was able to reproduce running on x86/Windows earlier as well, I can try that again with node.

**Comment by sbc100** [comment]
Does that exact code you posted fail?  Or does it need to be modified in someway?
