### ISSUE TITLE
`pthread_create` throws when building with `-s WASM_ASYNC_COMPILATION=0`

### ISSUE THREAD

**Issue by merceyz** [emscripten-core/emscripten#17361]
Calling `pthread_create` when building with `-s WASM_ASYNC_COMPILATION=0` throws

```
TypeError [Error]: createModule(...).then is not a function
    at self.onmessage (/repro/build.worker.js:116:28)
    at MessagePort.<anonymous> (/repro/build.worker.js:25:5)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
```

**Reproduction:**

Build the following C code with the provided build command

```c
// thread.c
#include <pthread.h>

void *doWork(void *args)
{
  return NULL;
}

void createThread()
{
  pthread_t t;
  pthread_create(&t, NULL, &doWork, NULL);
}

```

and run the following Node.js script.

```js
const createModule = require(`./build`);

const mod = createModule();
mod.cwrap(`createThread`, `void`, [])();
```

**Version of emscripten/emsdk:**

```console
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.14 (4343cbec72b7db283ea3bda1adc6cb1811ae9a73)
clang version 15.0.0 (https://github.com/llvm/llvm-project 7effcbda49ba32991b8955821b8fdbd4f8f303e2)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /emsdk/upstream/bin
```

**Full link command and output with `-v` appended:**

```console
$ docker run --rm -it -v "$(pwd):/src" emscripten/emsdk:3.1.14 emcc \
  -o ./build.js \
  -s WASM=1 \
  -s EXPORTED_FUNCTIONS="[\"_createThread\"]" \
  -s EXPORTED_RUNTIME_METHODS='["cwrap"]' \
  -s ENVIRONMENT=node \
  -s MODULARIZE=1 \
  -s NODERAWFS=1 \
  -s EXPORT_NAME="createModule" \
  -s WASM_ASYNC_COMPILATION=0 \
  -pthread \
  -v \
  ./thread.c
 "/emsdk/upstream/bin/clang" -target wasm32-unknown-emscripten -D__EMSCRIPTEN_SHARED_MEMORY__=1 -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=14 -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -pthread -v -matomics -mbulk-memory ./thread.c -c -o /tmp/emscripten_temp_fnam9e1z/thread_0.o
clang version 15.0.0 (https://github.com/llvm/llvm-project 7effcbda49ba32991b8955821b8fdbd4f8f303e2)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /emsdk/upstream/bin
 (in-process)
 "/emsdk/upstream/bin/clang-15" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name thread.c -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-feature +atomics -target-feature +bulk-memory -target-feature +mutable-globals -target-feature +sign-ext -target-cpu generic -target-feature +atomics -target-feature +bulk-memory -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=/src -resource-dir /emsdk/upstream/lib/clang/15.0.0 -D __EMSCRIPTEN_SHARED_MEMORY__=1 -D EMSCRIPTEN -D __EMSCRIPTEN_major__=3 -D __EMSCRIPTEN_minor__=1 -D __EMSCRIPTEN_tiny__=14 -isysroot /emsdk/upstream/emscripten/cache/sysroot -internal-isystem /emsdk/upstream/lib/clang/15.0.0/include -internal-isystem /emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten -internal-isystem /emsdk/upstream/emscripten/cache/sysroot/include -Werror=implicit-function-declaration -fdebug-compilation-dir=/src -ferror-limit 19 -fvisibility default -pthread -fgnuc-version=4.2.1 -fignore-exceptions -fcolor-diagnostics -iwithsysroot/include/SDL -iwithsysroot/include/compat -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /tmp/emscripten_temp_fnam9e1z/thread_0.o -x c ./thread.c
clang -cc1 version 15.0.0 based upon LLVM 15.0.0git default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 /emsdk/upstream/emscripten/cache/sysroot/include/SDL
 /emsdk/upstream/emscripten/cache/sysroot/include/compat
 /emsdk/upstream/lib/clang/15.0.0/include
 /emsdk/upstream/emscripten/cache/sysroot/include
End of search list.
 "/emsdk/upstream/bin/wasm-ld" -o ./build.wasm /tmp/emscripten_temp_fnam9e1z/thread_0.o -L/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten /emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/crtbegin.o -lGL-mt -lal -lhtml5 -lstubs-debug -lnoexit -lc-mt-debug -ldlmalloc-mt -lcompiler_rt-mt -lc++-mt-noexcept -lc++abi-mt-noexcept -lsockets-mt -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --import-memory --shared-memory --strip-debug --export-if-defined=createThread --export-if-defined=_emscripten_thread_init --export-if-defined=_emscripten_thread_exit --export-if-defined=_emscripten_thread_crashed --export-if-defined=_emscripten_tls_init --export-if-defined=pthread_self --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export=emscripten_dispatch_to_thread_ --export=_emscripten_thread_free_data --export=emscripten_main_browser_thread_id --export=emscripten_main_thread_process_queued_calls --export=emscripten_run_in_main_runtime_thread_js --export=emscripten_stack_set_limits --export=malloc --export=free --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024
 "/emsdk/upstream/bin/wasm-emscripten-finalize" --dyncalls-i64 ./build.wasm -o ./build.wasm --detect-features
 "/emsdk/node/14.18.2_64bit/bin/node" /emsdk/upstream/emscripten/src/compiler.js /tmp/tmp9h19sw8g.json
 "/emsdk/upstream/bin/llvm-objcopy" ./build.wasm ./build.wasm --remove-section=.debug* --remove-section=producers
 "/emsdk/node/14.18.2_64bit/bin/node" /emsdk/upstream/emscripten/tools/preprocessor.js /tmp/emscripten_temp_fnam9e1z/settings.js worker.js --expandMacros
```

**Comment by RReverser** [comment]
> RuntimeError: Aborted(Assertion failed: native function `createThread` called before runtime initialization)

The problem is, just because you use `WASM_ASYNC_COMPILATION`, it doesn't mean entire runtime is initialized synchronously. In your case PThread pool is still initialized asynchronously, and there's no good way around waiting - even with `PTHREAD_POOL_DELAY_LOAD=0` + #18281 you'd still have to do `.then(...)` somewhere before calling into the module.

However, if you're building only for Node.js, #18305 will help you as it allows to spawn threads fully synchronously on that target.

**Comment by merceyz** [comment]
I was going to close this either way since the original issue I had was fixed by https://github.com/emscripten-core/emscripten/pull/18313, was just unsure if the new error I got was expected, thanks for the fix and for confirming that it's expected behaviour.
