### ISSUE TITLE
fetch & MEMORY64 app build fails

### ISSUE THREAD

**Issue by lpotter** [emscripten-core/emscripten#17414]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
Please include the output `emcc -v` here

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.15 (8b4443a87f5eab5dbb9adb690f9ebed0a9da4bd9)
clang version 15.0.0 (https://github.com/llvm/llvm-project 27abff670bc7ad9702c4f9fc8b82aae6b530bf0f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/lpotter/emsdk/upstream/bin

**Failing command line in full:**
If this is compile or link-time failure please include the full failing command
along with its entire output.

em++ --bind main.cpp -o wasm-fetch.html -std=c++11 -s MEMORY64 -s FETCH=1

When I try to build a simple test all with the code from the fetch docs, and using -s MEMORY64, I get this error:

/Users/lpotter/emsdk/upstream/emscripten/system/lib/fetch/emscripten_fetch.c:263:77: error: cast to smaller integer type 'int32_t' (aka 'int') from 'char *' [-Werror,-Wpointer-to-int-cast]
  return (size_t)_emscripten_fetch_get_response_headers((int32_t)fetch->id, (int32_t)dst, (int32_t)dstSizeBytes);
                                                                            ^~~~~~~~~~~~
1 error generated.
emcc: error: '/Users/lpotter/emsdk/upstream/bin/clang -target wasm64-unknown-emscripten -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=15 -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -disable-lsr -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/Users/lpotter/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -O2 -Werror -fno-unroll-loops -g3 -c /Users/lpotter/emsdk/upstream/emscripten/system/lib/fetch/emscripten_fetch.c -o /Users/lpotter/emsdk/upstream/emscripten/cache/build/libfetch/emscripten_fetch.o' failed (returned 1)
Traceback (most recent call last):
  File "/Users/lpotter/emsdk/upstream/emscripten/em++.py", line 14, in <module>
    sys.exit(emcc.run(sys.argv))
  File "/Users/lpotter/emsdk/upstream/emscripten/emcc.py", line 1194, in run
    phase_calculate_system_libraries(state, linker_arguments, linker_inputs, newargs)
  File "/Users/lpotter/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/lpotter/emsdk/upstream/emscripten/emcc.py", line 2803, in phase_calculate_system_libraries
    extra_files_to_link += system_libs.calculate(all_linker_inputs, newargs, forced=state.forced_stdlibs)
  File "/Users/lpotter/emsdk/upstream/emscripten/tools/system_libs.py", line 1956, in calculate
    libs_to_link = get_libs_to_link(args, forced, only_forced)
  File "/Users/lpotter/emsdk/upstream/emscripten/tools/system_libs.py", line 1862, in get_libs_to_link
    add_library(forced)
  File "/Users/lpotter/emsdk/upstream/emscripten/tools/system_libs.py", line 1841, in add_library
    libs_to_link.append((lib.get_link_flag(), need_whole_archive))
  File "/Users/lpotter/emsdk/upstream/emscripten/tools/system_libs.py", line 258, in get_link_flag
    fullpath = self.get_path()
  File "/Users/lpotter/emsdk/upstream/emscripten/tools/system_libs.py", line 250, in get_path
    return shared.Cache.get_lib(self.get_filename(), self.build)
  File "/Users/lpotter/emsdk/upstream/emscripten/tools/cache.py", line 140, in get_lib
    return self.get(name, *args, **kwargs)
  File "/Users/lpotter/emsdk/upstream/emscripten/tools/cache.py", line 167, in get
    creator(str(cachename))
  File "/Users/lpotter/emsdk/upstream/emscripten/tools/system_libs.py", line 335, in build
    create_lib(out_filename, self.build_objects(build_dir))
  File "/Users/lpotter/emsdk/upstream/emscripten/tools/system_libs.py", line 322, in build_objects
    run_build_commands(commands)
  File "/Users/lpotter/emsdk/upstream/emscripten/tools/system_libs.py", line 77, in run_build_commands
    shared.run_multiple_processes(commands, env=clean_env())
  File "/Users/lpotter/emsdk/upstream/emscripten/tools/shared.py", line 218, in run_multiple_processes
    raise Exception('Subprocess %d/%d failed (%s)! (cmdline: %s)' % (idx + 1, len(commands), returncode_to_str(finished_process.returncode), shlex_join(commands[idx])))
Exception: Subprocess 1/1 failed (returned 1)! (cmdline: /Users/lpotter/emsdk/upstream/emscripten/emcc -O2 -Werror -fno-unroll-loops -g -sMEMORY64=1 -c /Users/lpotter/emsdk/upstream/emscripten/system/lib/fetch/emscripten_fetch.c -o /Users/lpotter/emsdk/upstream/emscripten/cache/build/libfetch/emscripten_fetch.o)
make: *** [all] Error 1

**Comment by kripken** [comment]
Probably Fetch is one of the last remaining libraries to be ported to wasm64 - @sbc100 ?
