### ISSUE TITLE
[asyncify]: asyncify_stop_unwind throws a RuntimeError: unreachable

### ISSUE THREAD

**Issue by msabwat** [emscripten-core/emscripten#17567]
Hi, 

I am hitting an abort() when maybeStopUnwind is called after I refactored a pthread_create wrapper that [sets and cancels the mainloop](https://code.videolan.org/b1ue/vlc/-/commit/08c0fe66b51b2a54b143b079e72674c8f0d5e792) (to allow correctly joining the thread as a workaround to #17552).

Replacing the abort in [runAndAbortIfError](https://github.com/emscripten-core/emscripten/blob/77da62969eb0b5efe4ce4a0c9ce67c45b9e32638/src/library_async.js#L216) with a console.error to get the exception I get this trace :

```
RuntimeError: unreachable
    at asyncify_stop_unwind (experimental.wasm:0x35470b3)
    at ret.<computed> (experimental.js:7561:35)
    at experimental.js:1152:22
    at runAndAbortIfError (experimental.js:7449:16)
    at Object.maybeStopUnwind (experimental.js:7584:11)
    at ret.<computed> (experimental.js:7566:30)
    at Object.doRewind (experimental.js:7628:16)
    at experimental.js:7661:47

runAndAbortIfError	@	experimental.js:7451
maybeStopUnwind	@	experimental.js:7584
ret.<computed>	@	experimental.js:7566
doRewind	@	experimental.js:7628
(anonymous)	@	experimental.js:7661
Promise.then (async)		
(anonymous)	@	experimental.js:7721
handleSleep	@	experimental.js:7639
handleAsync	@	experimental.js:7719
__asyncjs__init_js_file	@	experimental.js:1360
imports.<computed>	@	experimental.js:7527
$EmFileOpen	@	experimental.wasm:0x45dd42
$generic_start	@	experimental.wasm:0x31c049c
$vlc_module_load	@	experimental.wasm:0x31bfcfa
$module_need	@	experimental.wasm:0x31c0194
$access_New	@	experimental.wasm:0x3279fa4
...
```
Sorry for not being able to provide a short sample, I tried fiddling with the one in #17552 but could not reproduce.

asyncify_stop_unwind is called regularly, and when it is called after [this function](https://code.videolan.org/b1ue/vlc/-/commit/49f585a2a5fbbc04d85fbccbf63881d2a659cc54#2a7dea5d33617957668666b0ac9a19b12f8b718c_0_138) or [this function](https://code.videolan.org/b1ue/vlc/-/blob/394a123418b39a827467598bf19aef7d9e0a3c3c/modules/codec/webcodec.cpp#L131), I am having [this](https://github.com/emscripten-core/emscripten/blob/77da62969eb0b5efe4ce4a0c9ce67c45b9e32638/src/library_async.js#L18) abort().

**Version of emscripten/emsdk:**
```
$ emcc -v 
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.17 (fbc532773d84d2bd7da876275671970e792ad1cd)
clang version 15.0.0 (https://github.com/llvm/llvm-project 17e4c217b66305e60657a48f10fe3c428c2fe4d2)
Target: wasm32-unknown-emscripten
```

**Comment by allsey87** [comment]
When I get an error like this, it is usually because I forgot to include the function in [`ASYNCIFY_IMPORTS`](https://emscripten.org/docs/porting/asyncify.html?highlight=asyncify#more-on-asyncify-imports) so that might be worthwhile double checking.

**Comment by msabwat** [comment]
Hi @allsey87, thanks for the help,

The functions were in ASYNCIFY_IMPORTS, I tested without the imports to let emscripten decide what to instrument and I have the same result.

In both cases, I can see :

```
function __asyncjs__init_js_file(p_access,id) { return Asyncify.handleAsync(async () => { let p = new Promise((resolve\
, reject) => { function handleFileResult(e) { const msg = e['data']; if (msg.type === 'FileResult') { self.removeEvent\
Listener('message', handleFileResult); if (msg.file !== undefined) { Module.vlcAccess[p_access].worker_js_file = msg.f\
ile; Module.vlcAccess[p_access].reader = new FileReaderSync(); resolve(); } else { reject("error: sent an undefined Fi\
le object from the main thread"); } } else if (msg.type === 'ErrorVLCAccessFileUndefined') { reject("error: vlc_access\
_file object is not defined"); } else if (msg.type === 'ErrorRequestFileMessageWithoutId') { reject("error: request fi\
le message send without an id"); } else if (msg.type === 'ErrorMissingFile') { reject("error: missing file, bad id or \
vlc_access_file[id] is not defined"); } } self.addEventListener('message', handleFileResult); }); let timer = undefine\
d; let timeout = new Promise(function (resolve, reject) { timer = setTimeout(resolve, 1000, 'timeout') }); let promise\
s = [p, timeout]; self.postMessage({ cmd: "customCmd", type: "requestFile", id: id}); let return_value = 0; try { let \
value = await Promise.race(promises); if (value === 'timeout') { console.error("vlc_access timeout: could not get file\
!"); return_value = 1; } } catch(error) { console.error("vlc_access error in init_js_file(): ", error); return_value =\
 1; } clearTimeout(timer); return return_value; }); }
```

and 

```
function __asyncjs__probeConfig(cfg) { return Asyncify.handleAsync(async () => { var decoderCfg = Emval.toValue(cfg); \
var res = await VideoDecoder.isConfigSupported(decoderCfg).catch((err) => { console.log(err); return {'supported': fal\
se}; }); return res['supported']; }); }
```

in the runtime.

Interesting to note I am not having the issue when I add -O3 in the build script.

**Comment by quolpr** [comment]
I have the same issue 🤔 And with -O3 it works correctly too

**Comment by quolpr** [comment]
I found the reason! You need to increase asyncify stack size — `-s ASYNCIFY_STACK_SIZE=24576`

**Comment by msabwat** [comment]
> I found the reason! You need to increase asyncify stack size — `-s ASYNCIFY_STACK_SIZE=24576`

Thanks ! will test and report back, but it seems coherent!

**Comment by curiousdannii** [comment]
I ran into my first "unreachable" error, and increasing ASYNCIFY_STACK_SIZE also fixed it for me.

```
Aborted(RuntimeError: unreachable)
Unhandled Rejection: RuntimeError: Aborted(RuntimeError: unreachable). Build with -sASSERTIONS for more info.
    at abort (file:///home/dannii/parchment/src/upstream/emglken/build/tads-core.js:337:10)
    at runAndAbortIfError (file:///home/dannii/parchment/src/upstream/emglken/build/tads-core.js:3650:3)
    at Object.maybeStopUnwind (file:///home/dannii/parchment/src/upstream/emglken/build/tads-core.js:3751:4)
    at ret.<computed> (file:///home/dannii/parchment/src/upstream/emglken/build/tads-core.js:3736:18)
    at Object.doRewind (file:///home/dannii/parchment/src/upstream/emglken/build/tads-core.js:3789:10)
    at file:///home/dannii/parchment/src/upstream/emglken/build/tads-core.js:3810:38
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

But there's no more useful error when run with -sASSERTIONS!

@kripken I wonder if it would be possible to detect this error and add an extra message suggesting trying increasing ASYNCIFY_STACK_SIZE? If "unreachable" errors can happen for other reasons, then would it need some kind of test to see if it's happening during ASYNCIFY restoring?

**Comment by kripken** [comment]
@curiousdannii Yeah, we should definitely try to hint at the issue. I opened https://github.com/emscripten-core/emscripten/pull/18085 now for that.

With more work the error could be fully precise, if we made the Asyncify pass call out to a special import. That would take some more thinking, though, as the Asyncify pass is not specific to Emscripten, so we wouldn't want a hardcoded assumption about the Emscripten error function.
