### ISSUE TITLE
SyntaxError: Unexpected token  after upgrading to 3.1.23

### ISSUE THREAD

**Issue by rickg-hcl** [emscripten-core/emscripten#17994]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.23 (6be8aa86b61cc5227e0e2ccd10bbb862f54490d1)
clang version 16.0.0 (https://github.com/llvm/llvm-project 8b587113b746f31b63fd6473083df78cef30a72e)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/richardgillaspy/GitHub_nfs/emsdk/upstream/bin
```

**Failing command line in full:**
```
emcc -s USE_PTHREADS=1 -s PROXY_TO_PTHREAD=1 -s PTHREAD_POOL_SIZE=8 -s FETCH=1 -s FETCH_SUPPORT_INDEXEDDB=0 -s FULL_ES2=1 -s USE_FREETYPE=1 -s USE_LIBPNG=1 -s DISABLE_EXCEPTION_CATCHING=0 -s INITIAL_MEMORY=268435456 -s ALLOW_MEMORY_GROWTH=1 -s FORCE_FILESYSTEM=1 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s OFFSCREEN_FRAMEBUFFER=1 -s DEMANGLE_SUPPORT=1 -s ABORT_ON_WASM_EXCEPTIONS=1 test/hello_world.c
```
If this is compile or link-time failure please include the full failing command
along with its entire output.

**Full link command and output with `-v` appended:**
```
 "/Users/richardgillaspy/GitHub_nfs/emsdk/upstream/bin/clang" --version
 "/Users/richardgillaspy/GitHub_nfs/emsdk/upstream/bin/clang" -target wasm32-unknown-emscripten -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_SHARED_MEMORY__=1 -DEMSCRIPTEN -Werror=implicit-function-declaration -I/Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot/include/SDL -I/Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot/include/freetype2 --sysroot=/Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -v -pthread test/hello_world.c -c -o /var/folders/z5/pls2z2_s5wj3gjf517krrmth0000gn/T/emscripten_temp_qp3wka4i/hello_world_0.o
clang version 16.0.0 (https://github.com/llvm/llvm-project 8b587113b746f31b63fd6473083df78cef30a72e)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/richardgillaspy/GitHub_nfs/emsdk/upstream/bin
 (in-process)
 "/Users/richardgillaspy/GitHub_nfs/emsdk/upstream/bin/clang-16" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name hello_world.c -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-feature +atomics -target-feature +bulk-memory -target-feature +mutable-globals -target-feature +sign-ext -target-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=/Users/richardgillaspy/GitHub_nfs/emsdk/upstream/emscripten -resource-dir /Users/richardgillaspy/GitHub_nfs/emsdk/upstream/lib/clang/16.0.0 -D __EMSCRIPTEN_SHARED_MEMORY__=1 -D EMSCRIPTEN -I /Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot/include/SDL -I /Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot/include/freetype2 -isysroot /Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot -internal-isystem /Users/richardgillaspy/GitHub_nfs/emsdk/upstream/lib/clang/16.0.0/include -internal-isystem /Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot/include/wasm32-emscripten -internal-isystem /Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot/include -Werror=implicit-function-declaration -fdebug-compilation-dir=/Users/richardgillaspy/GitHub_nfs/emsdk/upstream/emscripten -ferror-limit 19 -fvisibility=default -pthread -fgnuc-version=4.2.1 -fcolor-diagnostics -iwithsysroot/include/compat -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /var/folders/z5/pls2z2_s5wj3gjf517krrmth0000gn/T/emscripten_temp_qp3wka4i/hello_world_0.o -x c test/hello_world.c
clang -cc1 version 16.0.0 based upon LLVM 16.0.0git default target x86_64-apple-darwin20.6.0
ignoring nonexistent directory "/Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 /Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot/include/SDL
 /Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot/include/freetype2
 /Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot/include/compat
 /Users/richardgillaspy/GitHub_nfs/emsdk/upstream/lib/clang/16.0.0/include
 /Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot/include
End of search list.
emcc: warning: USE_PTHREADS + ALLOW_MEMORY_GROWTH may run non-wasm code slowly, see https://github.com/WebAssembly/design/issues/1271 [-Wpthreads-mem-growth]
 "/Users/richardgillaspy/GitHub_nfs/emsdk/upstream/bin/wasm-ld" -o a.out.wasm /var/folders/z5/pls2z2_s5wj3gjf517krrmth0000gn/T/emscripten_temp_qp3wka4i/hello_world_0.o -L/Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot/lib/wasm32-emscripten /Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot/lib/wasm32-emscripten/libpng-mt.a /Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot/lib/wasm32-emscripten/libz.a /Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot/lib/wasm32-emscripten/libfreetype.a /Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot/lib/wasm32-emscripten/crtbegin.o /Users/richardgillaspy/GitHub_nfs/emscripten/cache/sysroot/lib/wasm32-emscripten/crt1_proxy_main.o --whole-archive -lfetch-mt --no-whole-archive -lGL-mt-ofb -lal -lhtml5 -lstubs-debug -lnoexit -lc-mt-debug -ldlmalloc-mt -lcompiler_rt-mt -lc++-mt -lc++abi-mt -lsockets-mt -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --import-memory --shared-memory --strip-debug --export-if-defined=main --export-if-defined=_emscripten_thread_init --export-if-defined=_emscripten_thread_exit --export-if-defined=_emscripten_thread_crashed --export-if-defined=_emscripten_tls_init --export-if-defined=pthread_self --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_init --export=__cxa_demangle --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export=emscripten_dispatch_to_thread_ --export=_emscripten_thread_free_data --export=emscripten_main_browser_thread_id --export=emscripten_main_thread_process_queued_calls --export=emscripten_run_in_main_runtime_thread_js --export=emscripten_stack_set_limits --export=getTempRet0 --export=setTempRet0 --export=__get_temp_ret --export=__set_temp_ret --export=malloc --export=free --export=__cxa_is_pointer_type --export=__cxa_can_catch --export=setThrew --export=saveSetjmp --export-table -z stack-size=5242880 --initial-memory=268435456 --entry=_emscripten_proxy_main --max-memory=2147483648 --global-base=1024
 "/Users/richardgillaspy/GitHub_nfs/emsdk/upstream/bin/wasm-emscripten-finalize" --dyncalls-i64 --pass-arg=legalize-js-interface-exported-helpers a.out.wasm -o a.out.wasm --detect-features
 "/Users/richardgillaspy/GitHub_nfs/emsdk/node/14.18.2_64bit/bin/node" /Users/richardgillaspy/GitHub_nfs/emscripten/src/compiler.js /var/folders/z5/pls2z2_s5wj3gjf517krrmth0000gn/T/tmpp08pdn9t.json
 "/Users/richardgillaspy/GitHub_nfs/emsdk/upstream/bin/llvm-objcopy" a.out.wasm a.out.wasm --remove-section=.debug* --remove-section=producers
 "/Users/richardgillaspy/GitHub_nfs/emsdk/node/14.18.2_64bit/bin/node" /Users/richardgillaspy/GitHub_nfs/emscripten/tools/acorn-optimizer.js /var/folders/z5/pls2z2_s5wj3gjf517krrmth0000gn/T/emscripten_temp_qp3wka4i/a.out.js growableHeap
/Users/richardgillaspy/GitHub_nfs/emscripten/tools/acorn-optimizer.js:1852
  throw err;
  ^

SyntaxError: Unexpected token (5727:2)
  finally {
  ^

    at Parser.pp$4.raise (/Users/richardgillaspy/GitHub_nfs/emscripten/node_modules/acorn/dist/acorn.js:3462:15)
    at Parser.pp$9.unexpected (/Users/richardgillaspy/GitHub_nfs/emscripten/node_modules/acorn/dist/acorn.js:756:10)
    at Parser.pp$5.parseExprAtom (/Users/richardgillaspy/GitHub_nfs/emscripten/node_modules/acorn/dist/acorn.js:2837:12)
    at Parser.pp$5.parseExprSubscripts (/Users/richardgillaspy/GitHub_nfs/emscripten/node_modules/acorn/dist/acorn.js:2629:21)
    at Parser.pp$5.parseMaybeUnary (/Users/richardgillaspy/GitHub_nfs/emscripten/node_modules/acorn/dist/acorn.js:2595:19)
    at Parser.pp$5.parseExprOps (/Users/richardgillaspy/GitHub_nfs/emscripten/node_modules/acorn/dist/acorn.js:2522:21)
    at Parser.pp$5.parseMaybeConditional (/Users/richardgillaspy/GitHub_nfs/emscripten/node_modules/acorn/dist/acorn.js:2505:21)
    at Parser.pp$5.parseMaybeAssign (/Users/richardgillaspy/GitHub_nfs/emscripten/node_modules/acorn/dist/acorn.js:2472:21)
    at Parser.pp$5.parseExpression (/Users/richardgillaspy/GitHub_nfs/emscripten/node_modules/acorn/dist/acorn.js:2435:21)
    at Parser.pp$8.parseStatement (/Users/richardgillaspy/GitHub_nfs/emscripten/node_modules/acorn/dist/acorn.js:946:47) {
  pos: 215372,
  loc: Position { line: 5727, column: 2 },
  raisedAt: 215379
}
emcc: error: '/Users/richardgillaspy/GitHub_nfs/emsdk/node/14.18.2_64bit/bin/node /Users/richardgillaspy/GitHub_nfs/emscripten/tools/acorn-optimizer.js /var/folders/z5/pls2z2_s5wj3gjf517krrmth0000gn/T/emscripten_temp_qp3wka4i/a.out.js growableHeap' failed (returned 1)
```
Even for runtime issues it helps a lot if you can include the full link command.
Adding `-v` to the link command will show all of the sub-commands run which
can help us diagnose your issue.

**Comment by rickg-hcl** [comment]
I think this is due to :
https://github.com/emscripten-core/emscripten/pull/17486

**Comment by rickg-hcl** [comment]
command line with minimal options:
emcc -s USE_PTHREADS=1 -s PROXY_TO_PTHREAD=1  -s ALLOW_MEMORY_GROWTH=1  -s ABORT_ON_WASM_EXCEPTIONS=1 test/hello_world.c

**Comment by sbc100** [comment]
Oh crap. I guess we don't have testing of `ABORT_ON_WASM_EXCEPTIONS`.   Do you rely on the the behaviour that that setting implies?

**Comment by sbc100** [comment]
Actually it looks like its just the combination of `ABORT_ON_WASM_EXCEPTIONS` and `PROXY_TO_PTHREAD` that was not fully tested.

**Comment by rickg-hcl** [comment]
I just tried running without ABORT_ON_WASM_EXCEPTIONS and it did not go well.  
I guess we do rely on the behavior after all.
