### ISSUE TITLE
For loop runs forever when conditional should be evaluated to false

### ISSUE THREAD

**Issue by andeplane** [emscripten-core/emscripten#18024]
**Version of emscripten/emsdk:**
```
emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.23 (5ae63ce7dd955df449cb419bfe5afc51d1bd57f2)
clang version 16.0.0 (https://github.com/llvm/llvm-project 8b587113b746f31b63fd6473083df78cef30a72e)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/anderhaf/repos/emsdk/upstream/bin
```

In short: I have a reasonably big simulator code [LAMMPS](https://github.com/lammps/lammps) written in c++ that I run with real time visualization using three.js. The link between LAMMPS and the frontend is done using a class (defined in `lammpsweb.cpp`). This has worked nicely, but when I added a small thing the other day, I end up finding something I can't understand is something else than a bug with the compiler.  I have a for loop that should run for `i` in range [0,25), but it runs forever with steady increasing `i`:
```
long LAMMPSWeb::getBondListData() {
  int numAtoms = 25;
  std::cout << "Looping over numAtoms = " << numAtoms << " atoms" << std::endl;
  for(int idx=0; idx<numAtoms; idx++) {
    std::cout << "Condition " << idx << " < " << numAtoms << ": " << (idx<numAtoms) << std::endl;
  }
}
```

this loop runs forever. It prints large value for `idx`, but still evaluates the conditional `idx<numAtoms` to `1`. The `getBondListData` function is called from JS.

**One error in my code is that I don't return anything from the function. If I do return something, the loop runs as expected.**

I haven't been able to create a small reproduceable example, but it can be reproduced with [this repo](https://github.com/andeplane/atomify/tree/anders/emscripten_bug).
```
git clone https://github.com/andeplane/atomify --branch anders/emscripten_bug
cd cpp
python3 build.py
cd ..
npm install
npm run start
```
Then open http://localhost:3000/atomify/ and click the play button on the one example in the list.

By modifying `cpp/lammpsweb.cpp`, you can recompile by again running `python3 build.py` in the `cpp`-folder.

**Comment by andeplane** [comment]
It happens with -O1 and -O2 at least, have not tried -O0. Will try to reduce the thing as much as possible. Will check your suggestions too.

**Comment by andeplane** [comment]
Managed to reproduce quite easily. In the attached zip file, run it with

```
./compile.sh
node run.js
```


The bug happens at `-O1` through `-O3`, but not at `-O0`. With `-O0`, it stops with
```
Looping to 25
Condition 0 < 25: 1
...
Condition 24 < 25: 1
/Users/anderhaf/projects/emscripten_bug/MyClass.js:168
      throw ex;
      ^

RuntimeError: unreachable
    at <anonymous>:wasm-function[57]:0x1f2d
    at <anonymous>:wasm-function[92]:0x5bdd
    at dynCall_iii (<anonymous>:wasm-function[1709]:0xc1d7b)
    at ret.<computed> (/Users/anderhaf/projects/emscripten_bug/MyClass.js:2710:35)
    at /Users/anderhaf/projects/emscripten_bug/MyClass.js:1001:22
    at dynCallLegacy (/Users/anderhaf/projects/emscripten_bug/MyClass.js:2401:38)
    at dynCall (/Users/anderhaf/projects/emscripten_bug/MyClass.js:2416:14)
    at /Users/anderhaf/projects/emscripten_bug/MyClass.js:2423:16
    at MyClass$test [as test] (eval at new_ (/Users/anderhaf/projects/emscripten_bug/MyClass.js:2608:27), <anonymous>:8:10)
    at /Users/anderhaf/projects/emscripten_bug/run.js:5:11
``` 
[infinite_loop_bug.zip](https://github.com/emscripten-core/emscripten/files/9748198/infinite_loop_bug.zip)

**Comment by andeplane** [comment]
I read more about this. In the C++ standard, this is actually undefined behaviour, so it is not a compiler bug. See [this thread](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=43943) for details.
