### ISSUE TITLE
Clean after linking: file is being used by another process

### ISSUE THREAD

**Issue by caxapexac** [emscripten-core/emscripten#18150]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
3.1.24

**Failing command line in full:**
Everything worked in at least 3.1.16
Everything works in 'debug' build:
```
set(COMMON_DEBUG_CXX
        -O0
        )
set(COMMON_DEBUG_LNK
        -O0
        -sASSERTIONS=1
        -sDEMANGLE_SUPPORT
        -sRUNTIME_LOGGING
        -sINITIAL_MEMORY=512MB
        -sMAXIMUM_MEMORY=4096MB
        )
set(DEBUG_CXX ${COMMON_DEBUG_CXX}
        -g2
        -fsanitize=undefined
        )
set(DEBUG_LNK ${COMMON_DEBUG_LNK}
        -g2
        -fsanitize=undefined
        )
(also works):
set(DEBUGDWARF_CXX ${COMMON_DEBUG_CXX}
        -g3
        )
set(DEBUGDWARF_LNK ${COMMON_DEBUG_LNK}
        -g3
        )
```

This crash happens in 'release' build:
```
set(COMMON_RELEASE_CXX
        -Oz
        -g0
        -fno-exceptions
        -flto
        -DNDEBUG
        )
set(COMMON_RELEASE_LNK
        -Oz
        -g0
        -fno-exceptions
        -flto
        -sINLINING_LIMIT=1
        -sELIMINATE_DUPLICATE_FUNCTIONS=1
        -sNO_ASSERTIONS
        -sNO_DEMANGLE_SUPPORT
        -sDISABLE_EXCEPTION_CATCHING
        -sDISABLE_EXCEPTION_THROWING
        )
set(RELEASE_CXX ${COMMON_RELEASE_CXX})
set(RELEASE_LNK ${COMMON_RELEASE_LNK}
        -sINITIAL_MEMORY=128MB
        -sMAXIMUM_MEMORY=1024MB
        )
```

**Full link command and output with `-v` appended:**
```
profiler:INFO: block "calculate system libraries" took 6.011 seconds
profiler:INFO: start block "link"
profiler:INFO: block "link" took 50.427 seconds
profiler:INFO: start block "post_link"
profiler:INFO:   start block "emscript"
profiler:INFO:     start block "get_metadata"
profiler:INFO:     block "get_metadata" took 1.031 seconds
profiler:INFO:     start block "check_node"
profiler:INFO:     block "check_node" took 0.092 seconds
profiler:INFO:   block "emscript" took 1.486 seconds
profiler:INFO:   start block "source transforms"
profiler:INFO:   block "source transforms" took 0.000 seconds
profiler:INFO:   start block "binaryen"
profiler:INFO:   block "binaryen" took 16.823 seconds
profiler:INFO:   start block "final emitting"
profiler:INFO:   block "final emitting" took 0.049 seconds
profiler:INFO: block "post_link" took 18.361 seconds
Traceback (most recent call last):
  File "F:\Apps\W4Trial\emsdk\upstream\emscripten\tools\tempfiles.py", line 58, in clean
    utils.delete_file(filename)
  File "F:\Apps\W4Trial\emsdk\upstream\emscripten\tools\utils.py", line 103, in delete_file
    os.remove(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\caxap\\AppData\\Local\\Temp\\emcc_acorn_info_zaxpu9cg.js'
```

The problem happens on every try. The problem happens on different projects. 

Tell me if it is needed to do a binary search of the compilation flags and emscripten version where does the issue firstly exist if it isn't clear whats the root of the problem right now

**Comment by caxapexac** [comment]
With -v:
```
[1/2] Building CXX object CMakeFiles/_playground.dir/samples/_playground/sources/main.cpp.o
profiler:INFO: start block "parse arguments"
profiler:INFO: block "parse arguments" took 0.015 seconds
profiler:INFO: start block "check_sanity"
profiler:INFO: block "check_sanity" took 0.021 seconds
profiler:INFO: start block "setup"
profiler:INFO: block "setup" took 0.001 seconds
profiler:INFO: start block "compile inputs"
profiler:INFO:   start block "ensure_sysroot"
profiler:INFO:   block "ensure_sysroot" took 0.000 seconds
profiler:INFO: block "compile inputs" took 8.345 seconds
[2/2] Linking CXX executable .generated\_playground\_playground.js
[Res] ...ok
profiler:INFO: start block "parse arguments"
profiler:INFO: block "parse arguments" took 0.016 seconds
profiler:INFO: start block "check_sanity"
 "F:/Apps/W4Trial/emsdk/upstream/bin\clang.exe" --version
profiler:INFO: block "check_sanity" took 0.021 seconds
profiler:INFO: start block "setup"
profiler:INFO: block "setup" took 0.001 seconds
profiler:INFO: start block "compile inputs"
profiler:INFO:   start block "ensure_sysroot"
profiler:INFO:   block "ensure_sysroot" took 0.001 seconds
profiler:INFO: block "compile inputs" took 0.001 seconds
profiler:INFO: start block "linker_setup"
profiler:INFO: block "linker_setup" took 0.002 seconds
profiler:INFO: start block "calculate linker inputs"
profiler:INFO: block "calculate linker inputs" took 0.019 seconds
profiler:INFO: start block "calculate system libraries"
profiler:INFO:   start block "llvm_nm_multiple"
profiler:INFO:   block "llvm_nm_multiple" took 2.866 seconds
profiler:INFO: block "calculate system libraries" took 2.873 seconds
profiler:INFO: start block "link"
 "F:/Apps/W4Trial/emsdk/upstream/bin\wasm-ld.exe" -o .generated\_playground\_playground.wasm CMakeFiles/_playground.dir/samples/_playground/sources/main.cpp.o libw4-Release.a -LF:\Apps\W4Trial\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\lto -lGL -lal -lhtml5 -lc_optz -lstubs -lnoexit -lc -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --strip-debug --export-if-defined=malloc --export-if-defined=free --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=malloc --export-table -z stack-size=5242880 --initial-memory=134217728 --no-entry --max-memory=1073741824 --global-base=1024
profiler:INFO: block "link" took 10.981 seconds
profiler:INFO: start block "post_link"
profiler:INFO:   start block "emscript"
profiler:INFO:     start block "get_metadata"
 "F:/Apps/W4Trial/emsdk/upstream\bin\wasm-emscripten-finalize" --dyncalls-i64 --pass-arg=legalize-js-interface-exported-helpers .generated\_playground\_playground.wasm -o .generated\_playground\_playground.wasm --detect-features
profiler:INFO:     block "get_metadata" took 0.237 seconds
profiler:INFO:     start block "check_node"
profiler:INFO:     block "check_node" took 0.095 seconds
 "F:/Apps/W4Trial/emsdk/node/14.18.2_64bit/bin/node.exe" F:\Apps\W4Trial\emsdk\upstream\emscripten\src\compiler.js C:\Users\caxap\AppData\Local\Temp\tmp_rgivj0a.json
profiler:INFO:   block "emscript" took 0.701 seconds
profiler:INFO:   start block "source transforms"
profiler:INFO:   block "source transforms" took 0.000 seconds
profiler:INFO:   start block "binaryen"
 "F:/Apps/W4Trial/emsdk/upstream\bin\wasm-opt" --strip-dwarf --post-emscripten -Oz --low-memory-unused --zero-filled-memory --pass-arg=directize-initial-contents-immutable --strip-debug --strip-producers .generated\_playground\_playground.wasm -o .generated\_playground\_playground.wasm --mvp-features --enable-mutable-globals
 "F:/Apps/W4Trial/emsdk/node/14.18.2_64bit/bin/node.exe" F:\Apps\W4Trial\emsdk\upstream\emscripten\tools\acorn-optimizer.js C:\Users\caxap\AppData\Local\Temp\emscripten_temp_hs95f0_v\_playground.js AJSDCE minifyWhitespace -o C:\Users\caxap\AppData\Local\Temp\emscripten_temp_hs95f0_v\_playground.jso1.js
 "F:/Apps/W4Trial/emsdk/node/14.18.2_64bit/bin/node.exe" F:\Apps\W4Trial\emsdk\upstream\emscripten\tools\acorn-optimizer.js C:\Users\caxap\AppData\Local\Temp\emcc_acorn_info_yxdjghz8.js emitDCEGraph noPrint
 "F:/Apps/W4Trial/emsdk/upstream\bin\wasm-metadce" --graph-file=C:\Users\caxap\AppData\Local\Temp\emcc_dce_graph_hijtsks0.json .generated\_playground\_playground.wasm -o .generated\_playground\_playground.wasm --mvp-features --enable-mutable-globals
 "F:/Apps/W4Trial/emsdk/node/14.18.2_64bit/bin/node.exe" F:\Apps\W4Trial\emsdk\upstream\emscripten\tools\acorn-optimizer.js C:\Users\caxap\AppData\Local\Temp\emcc_acorn_info_q9b5h40f.js applyDCEGraphRemovals minifyWhitespace -o C:\Users\caxap\AppData\Local\Temp\emscripten_temp_hs95f0_v\_playground.jso2.js
 "F:/Apps/W4Trial/emsdk/node/14.18.2_64bit/bin/node.exe" F:\Apps\W4Trial\emsdk\upstream\emscripten\tools\acorn-optimizer.js C:\Users\caxap\AppData\Local\Temp\emscripten_temp_hs95f0_v\_playground.jso2.js AJSDCE minifyWhitespace -o C:\Users\caxap\AppData\Local\Temp\emscripten_temp_hs95f0_v\_playground.jso3.js
 "F:/Apps/W4Trial/emsdk/upstream\bin\wasm-opt" --strip-dwarf --minify-imports-and-exports-and-modules .generated\_playground\_playground.wasm -o .generated\_playground\_playground.wasm --mvp-features --enable-mutable-globals
 "F:/Apps/W4Trial/emsdk/node/14.18.2_64bit/bin/node.exe" F:\Apps\W4Trial\emsdk\upstream\emscripten\tools\acorn-optimizer.js C:\Users\caxap\AppData\Local\Temp\emcc_acorn_info_did3ix90.js applyImportAndExportNameChanges minifyWhitespace -o C:\Users\caxap\AppData\Local\Temp\emscripten_temp_hs95f0_v\_playground.jso4.js
profiler:INFO:   block "binaryen" took 5.113 seconds
profiler:INFO:   start block "final emitting"
profiler:INFO:   block "final emitting" took 0.070 seconds
profiler:INFO: block "post_link" took 5.886 seconds
Traceback (most recent call last):
  File "F:\Apps\W4Trial\emsdk\upstream\emscripten\tools\tempfiles.py", line 58, in clean
    utils.delete_file(filename)
  File "F:\Apps\W4Trial\emsdk\upstream\emscripten\tools\utils.py", line 103, in delete_file
    os.remove(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\caxap\\AppData\\Local\\Temp\\emcc_acorn_info_yxdjghz8.js'
```

**Comment by sbc100** [comment]
That is strange.  We don't see that on any of our windows test infrastructure so something odd must be going on here.

Could you try bisecting to see which change caused this regression: https://emscripten.org/docs/contributing/developers_guide.html#bisecting
