### ISSUE TITLE
Run all ASYNCIFY tests in JSPI mode

### ISSUE THREAD

**Issue by brendandahl** [emscripten-core/emscripten#18180]
Not all of these will make sense to enable, but we can track progress here.

Core

- [ ] test_dlfcn_asyncify
- [ ] test_cubescript
- [ ] test_async_ccall_bad
- [ ] test_async_ccall_good
- [ ] test_async_ccall_promise
- [ ] test_fibers_asyncify
- [ ] test_asyncify_unused
- [ ] test_asyncify_lists
- [ ] test_asyncify_indirect_lists
- [ ] test_asyncify_side_module
- [ ] test_emscripten_scan_registers
- [ ] test_asyncify_assertions
- [ ] test_asyncify_during_exit
- [ ] test_asyncify_main_module
- [ ] test_embind_lib_with_asyncify

Other

- [ ] test_embind_asyncify
- [ ] test_dlopen_blocking
- [ ] test_asyncify_escaping
- [ ] test_asyncify_response_file
- [ ] test_asyncify_advise
- [ ] test_asyncify_stack_overflow
- [ ] test_pthread_asyncify
- [ ] test_webgpu_compiletest
- [ ] test_closure_safe
- [ ] test_stack_switching_size

**Comment by brendandahl** [comment]
@sbc100 Do you have any thoughts on how to compose two `@parameterized` decorators. e.g. I'd like to run `test_cubescript` with `@with_asyncify_and_stack_switching`, but it already has an `@parameterized`. It seems we'd want to do something with named arguments instead of position arguments, but my python-fu is weak.

**Comment by sbc100** [comment]
> @sbc100 Do you have any thoughts on how to compose two `@parameterized` decorators. e.g. I'd like to run `test_cubescript` with `@with_asyncify_and_stack_switching`, but it already has an `@parameterized`. It seems we'd want to do something with named arguments instead of position arguments, but my python-fu is weak.

IIRC i wasn't never able to make it work..  @tlively might have more info.   My fallback has been to just stick to single @parameterized block and use the old method of writing a loop inside the test body for the second parameter set.

**Comment by tlively** [comment]
Honestly I never understood the metaclass magic that makes `parameterized` work, but I guess it's not composable with itself because it just sets a field `_parameterized` on the original method, so it loses any previous information. Making it composable would require having it push onto a list of parameterizations instead. Then the metaclass magic that synthesizes the new test methods would have to take the cartesian product of all the parameterizations.

**Comment by fs-eire** [comment]
I have this "RuntimeError: invalid suspender object for suspend" runtime error when I try to use "-s ASYNCIFY=2" instead of "-s ASYNCIFY=1". Is this because the feature still in development?

**Comment by brendandahl** [comment]
It's still in development, but most things should work. Also, there are some differences in how 1 vs 2 works. If possible can you open a new issue with a small reproducer?

**Comment by fs-eire** [comment]
It may be a little difficult to prepare a small reproducer.. This is the change I am trying: (just switching ASYNCIFY=1 to ASYNCIFY=2)
https://github.com/microsoft/onnxruntime/compare/fs-eire/use-jspi-based-asyncify

emsdk version is 3.1.37. I will update to use latest version to see if the error is resolved.

**Comment by fs-eire** [comment]
tried latest 3.1.42. got this error:

```
Aborted(Assertion failed: Missing __sig for invoke_di)
```

I found this issue #19672 and tried the workaround mentioned inside. error changed to this:

```
      RuntimeError: invalid suspender object for suspend
          at jsepDownload (test/ort-wasm-simd.jsep.wasm:wasm-function[269684]:0x423cf27)
          at onnxruntime::js::DataTransfer::CopyTensor(onnxruntime::Tensor const&, onnxruntime::Tensor&) const (test/ort-wasm-simd.jsep.wasm:wasm-function[247313]:0x3a855dd)
          at onnxruntime::IDataTransfer::CopyTensors(std::__2::vector<onnxruntime::IDataTransfer::SrcDstPair, std::__2::allocator<onnxruntime::IDataTransfer::SrcDstPair>> const&) const (test/ort-wasm-simd.jsep.wasm:wasm-function[83566]:0x1500519)
          at onnxruntime::DataTransferManager::CopyTensors(std::__2::vector<onnxruntime::IDataTransfer::SrcDstPair, std::__2::allocator<onnxruntime::IDataTransfer::SrcDstPair>> const&) const (test/ort-wasm-simd.jsep.wasm:wasm-function[25695]:0x6e30de)
          at invoke_viii (test/ort.dev.js:88135:27)
          at onnxruntime::utils::CopyOutputsAcrossDevices(onnxruntime::SessionState const&, gsl::span<OrtValue const, 4294967295ul>, std::__2::vector<OrtValue, std::__2::allocator<OrtValue>>&, gsl::span<onnxruntime::MLValueCopyInfo const, 4294967295ul>, gsl::span<onnxruntime::Stream* const, 4294967295ul>) (test/ort-wasm-simd.jsep.wasm:wasm-function[42019]:0xa75239)
          at invoke_viiiiii (test/ort.dev.js:88267:27)
          at onnxruntime::utils::ExecuteGraphImpl(onnxruntime::SessionState const&, onnxruntime::FeedsFetchesManager const&, gsl::span<OrtValue const, 4294967295ul>, std::__2::vector<OrtValue, std::__2::allocator<OrtValue>>&, std::__2::unordered_map<unsigned long, std::__2::function<onnxruntime::common::Status (onnxruntime::TensorShape const&, OrtDevice const&, OrtValue&, bool&)>, std::__2::hash<unsigned long>, std::__2::equal_to<unsigned long>, std::__2::allocator<std::__2::pair<unsigned long const, std::__2::function<onnxruntime::common::Status (onnxruntime::TensorShape const&, OrtDevice const&, OrtValue&, bool&)>>>> const&, ExecutionMode, bool const&, onnxruntime::logging::Logger const&, onnxruntime::DeviceStreamCollection*, bool, onnxruntime::Stream*) (test/ort-wasm-simd.jsep.wasm:wasm-function[41978]:0xa718ea)
          at invoke_viiiiiiiiiiii (test/ort.dev.js:88421:27)
          at onnxruntime::utils::ExecuteGraph(onnxruntime::SessionState const&, onnxruntime::FeedsFetchesManager&, gsl::span<OrtValue const, 4294967295ul>, std::__2::vector<OrtValue, std::__2::allocator<OrtValue>>&, ExecutionMode, bool const&, onnxruntime::logging::Logger const&, bool, bool, onnxruntime::Stream*) (test/ort-wasm-simd.jsep.wasm:wasm-function[41975]:0xa6e7a5)
```

jsepDownload is defined as this:
```
EM_ASYNC_JS(void, jsepDownload, (const void* src_data, void* dst_data, size_t bytes), {
  await Module.jsepCopyAsync(src_data, dst_data, bytes);
});
```

still not working

**Comment by dakenf** [comment]
@fs-eire the problem here is that any exported webassembly method which calls JS code internally, needs to be asyncifyed (so browser will create and set suspender object ineternally) 
By default none of the them are wrapped in ASYNCIFY=2, so you need to do these things:
1. add `"SHELL:-s ASYNCIFY_EXPORTS=['OrtRun']"` to `target_link_options(onnxruntime_webassembly PRIVATE` in onnxruntime_webassembly.cmake
2. replace `-s DISABLE_EXCEPTION_CATCHING=0` with `-fwasm-exceptions` in onnxruntime_webassembly.cmake and adjust_global_compile_flags.cmake

It runs fine and faster than ASYNCIFY=1 (3+ minutes for 1 stable diffusion step went down to less than 2.5)
I've also made emscripten working with 64 bit memory, so once those changes get into release, you can expect another pull request from me to support 64bit with ability to use up to 16gb mem in the browser
