### ISSUE TITLE
ASSERTIONS mode should tell the user when trying to use pthreads w/o -pthread

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#18240]
I just tried building [simple C++ example](https://web.dev/webassembly-threads/#c-2) that uses threads and trying to run, getting an anonymous abort somewhere in Emscripten internals:

```js
> node temp
Before the thread
Aborted(native code called abort())
/home/rreverser/temp.js:147
      throw ex;
      ^

RuntimeError: Aborted(native code called abort())
    at abort (/home/rreverser/temp.js:990:11)
    at _abort (/home/rreverser/temp.js:1304:7)
    at std::__2::__throw_system_error(int, char const*) (<anonymous>:wasm-function[1689]:0x24cef)
    at std::__2::thread::thread<main::$_0, void>(main::$_0&&) (<anonymous>:wasm-function[15]:0x1167)
    at __original_main (<anonymous>:wasm-function[14]:0xfff)
    at main (<anonymous>:wasm-function[135]:0x3e75)
    at /home/rreverser/temp.js:1034:22
    at callMain (/home/rreverser/temp.js:4806:15)
    at doRun (/home/rreverser/temp.js:4860:23)
    at run (/home/rreverser/temp.js:4875:5)
```

After a few minutes of cleaning up `emcc` cache & rebuilding (in case it was my local pthread-related experiments that broke something), I finally realised that I just forgot to add `-pthread` flag when building 🤦‍♂️ 

So Emscripten linked it with the `library_pthread_stub.js` instead, which has most operations stubbed out.

I think in the default `ASSERTIONS` mode it would be worth to either print a warning or even throw an early error when `pthread_create` or other unsupported operations are invoked.

Also, generally, `__throw_system_error` probably shouldn't ignore the message parameter in non-exceptions mode and instead pass it to be printed by JS here: https://github.com/emscripten-core/emscripten/blob/2e02d0eba92c9c7489bed38eff9bd1ee61e93229/system/lib/libcxx/src/system_error.cpp#L294. The cost of passing it would be negligible, but error message at least wouldn't be lost.

**Comment by kripken** [comment]
Looks like `pthread_create` returns `EAGAIN` in the stub version, so it is returning an error. But I guess that is possible to miss in user code. I agree a warning in ASSERTIONS mode would be nice.

**Comment by RReverser** [comment]
> Looks like `pthread_create` returns `EAGAIN` in the stub version, so it is returning an error.

Right, but the problem is twofold then:

1. In C it's too common to assume that `pthread_create` succeeds, so user won't see an error.
2. C++, like in my example above, actually tries to report a somewhat meaningful error but, as mentioned in the last paragraph, we currently ignore the error message passed to `__throw_system_error`, so all user gets is anonymous `abort` even in debug mode.

Having both a custom message in `pthread_create` in `ASSERTIONS` mode, and actually showing C++ error messages from `__throw_system_error` would be ideal.
