### ISSUE TITLE
emscripten_set_main_loop and embind

### ISSUE THREAD

**Issue by Jonathhhan** [emscripten-core/emscripten#18316]
If I set the third argument of `emscripten_set_main_loop` to 0 and use embind I get a null function or function signature mismatch error. I set it to 0, because that avoids the unwind warning that I get otherwise with `ASYNCIFY`.

```
Uncaught RuntimeError: null function or function signature mismatch
    at ofxAppEmscriptenWindow::draw() (emscriptenImport.wasm:0x2a78ae)
    at ofxAppEmscriptenWindow::display_cb() (emscriptenImport.wasm:0x2a8ed6)
    at emscripten::internal::Invoker<void>::invoke(void (*)()) (emscriptenImport.wasm:0xf93bd)
    at ret.<computed> (emscriptenImport.js:1:81968)
    at browserIterationFunc (emscriptenImport.js:1:140413)
    at callUserCallback (emscriptenImport.js:1:80812)
    at Object.runIter (emscriptenImport.js:1:122751)
    at Browser_mainLoop_runner (emscriptenImport.js:1:120967)
```

**Comment by sbc100** [comment]
This doesn't looks related to the third argument to `emscripten_set_main_loop`.  Setting that to 0/false should be fine.

It looks like somehow a bad function pointer ended up in `ofxAppEmscriptenWindow::draw`.. can you debug/print to see what the value of that function pointer is?

**Comment by Jonathhhan** [comment]
@sbc100 thank you for the hint. everything works well after updating the window settings. (strangely the error appeared only if the third arg was set to 0, but anyhow)
