### ISSUE TITLE
BUG: `Uncaught TypeError: Module._malloc is not a function`

### ISSUE THREAD

**Issue by raysan5** [emscripten-core/emscripten#18815]
This issue was introduced in `emscripten 3.1.31`, not present on previous versions.

### Emscripten Version

```
C:\emsdk>emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.32 (eab98adf462c39f3c31d348331c4830bcaa36949)
clang version 17.0.0 (https://github.com/llvm/llvm-project df82394e7a2d06506718cafa347bf7827c79fc4f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: C:\emsdk\upstream\bin
```
### Issue Description

This issue was detected when compiling a raylib audio example that worked with previous emscripten versions.

Related issue: https://github.com/raysan5/raylib/issues/2931. 

It happens at runtime, browser console output error:

```
Uncaught TypeError: Module._malloc is not a function
    at 55586 (audio_music_stream.js:1:18508)
    at runEmAsmFunction (audio_music_stream.js:1:72898)
    at _emscripten_asm_const_int (audio_music_stream.js:1:72977)
    at audio_music_stream.wasm:0x23238
    at audio_music_stream.wasm:0x311f9
    at audio_music_stream.wasm:0x19b3f
    at audio_music_stream.wasm:0x3a6b6
    at ret.<computed> (audio_music_stream.js:1:175833)
    at Module._main (audio_music_stream.js:1:189644)
    at callMain (audio_music_stream.js:1:193084)
```

### Full compilation command (`-v`)

```
emcc -o audio/audio_music_stream.html audio/audio_music_stream.c -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -Wunused-result -O3 -v -I. -I../src -I../src/external -L. -L../src -L../src -s USE_GLFW=3 -s TOTAL_MEMORY=134217728 -s FORCE_FILESYSTEM=1 -s ASYNCIFY --preload-file audio/resources@resources --shell-file ../src/minshell.html ../src/libraylib.a -DPLATFORM_WEB
 "C:/emsdk/upstream/bin\clang.exe" --version
 "C:/emsdk/upstream/bin\clang.exe" -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN -Werror=implicit-function-declaration --sysroot=C:\emsdk\upstream\emscripten\cache\sysroot -Xclang -iwithsysroot/include\fakesdl -Xclang -iwithsysroot/include\compat -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -Wunused-result -O3 -v -I. -I../src -I../src/external -DPLATFORM_WEB audio/audio_music_stream.c -c -o C:\Users\raysa\AppData\Local\Temp\emscripten_temp_04eqq9yb\audio_music_stream_0.o
clang version 17.0.0 (https://github.com/llvm/llvm-project df82394e7a2d06506718cafa347bf7827c79fc4f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: C:\emsdk\upstream\bin
 (in-process)
 "C:\\emsdk\\upstream\\bin\\clang.exe" -cc1 -triple wasm32-unknown-emscripten -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name audio_music_stream.c -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v "-fcoverage-compilation-dir=C:\\GitHub\\raylib\\examples" -resource-dir "C:\\emsdk\\upstream\\lib\\clang\\17" -D EMSCRIPTEN -D _DEFAULT_SOURCE -I . -I ../src -I ../src/external -D PLATFORM_WEB -isysroot "C:\\emsdk\\upstream\\emscripten\\cache\\sysroot" -internal-isystem "C:\\emsdk\\upstream\\lib\\clang\\17\\include" -internal-isystem "C:\\emsdk\\upstream\\emscripten\\cache\\sysroot/include/wasm32-emscripten" -internal-isystem "C:\\emsdk\\upstream\\emscripten\\cache\\sysroot/include" -O3 -Werror=implicit-function-declaration -Wall -Wno-missing-braces -Wunused-result -std=c99 "-fdebug-compilation-dir=C:\\GitHub\\raylib\\examples" -ferror-limit 19 -fvisibility=default -fgnuc-version=4.2.1 -fignore-exceptions -vectorize-loops -vectorize-slp "-iwithsysroot/include\\fakesdl" "-iwithsysroot/include\\compat" -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o "C:\\Users\\raysa\\AppData\\Local\\Temp\\emscripten_temp_04eqq9yb\\audio_music_stream_0.o" -x c audio/audio_music_stream.c
clang -cc1 version 17.0.0 based upon LLVM 17.0.0git default target x86_64-pc-windows-msvc
ignoring nonexistent directory "C:\emsdk\upstream\emscripten\cache\sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 .
 ../src
 ../src/external
 C:\emsdk\upstream\emscripten\cache\sysroot/include\fakesdl
 C:\emsdk\upstream\emscripten\cache\sysroot/include\compat
 C:\emsdk\upstream\lib\clang\17\include
 C:\emsdk\upstream\emscripten\cache\sysroot/include
End of search list.
 "C:\emsdk\upstream\emscripten\tools\file_packager.bat" audio/audio_music_stream.data --from-emcc --preload audio/resources@resources
 "C:/emsdk/upstream/bin\wasm-ld.exe" -o audio/audio_music_stream.wasm C:\Users\raysa\AppData\Local\Temp\emscripten_temp_04eqq9yb\audio_music_stream_0.o -L. -L../src -L../src ../src/libraylib.a -LC:\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten -lGL -lal -lhtml5 -lstubs -lnoexit -lc -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined-file=C:\Users\raysa\AppData\Local\Temp\tmpne_utylo.undefined --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export=emscripten_stack_get_base --export=emscripten_stack_get_end --export=emscripten_stack_set_limits --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=malloc --export=free --export=__wasm_call_ctors --export=__dl_seterr --export-table -z stack-size=65536 --initial-memory=134217728 --no-entry --max-memory=134217728 --global-base=1024
 "C:/emsdk/upstream\bin\wasm-emscripten-finalize" --pass-arg=legalize-js-interface-exported-helpers audio/audio_music_stream.wasm -o audio/audio_music_stream.wasm --detect-features
 "C:/emsdk/node/14.18.2_64bit/bin/node.exe" C:\emsdk\upstream\emscripten\src\compiler.js C:\Users\raysa\AppData\Local\Temp\tmpkbppg8ew.json
 "C:/emsdk/upstream\bin\wasm-opt" --strip-dwarf --post-emscripten -O3 --low-memory-unused --asyncify --pass-arg=asyncify-imports@env.invoke_*,env.emscripten_sleep,env.emscripten_wget,env.emscripten_wget_data,env.emscripten_idb_load,env.emscripten_idb_store,env.emscripten_idb_delete,env.emscripten_idb_exists,env.emscripten_idb_load_blob,env.emscripten_idb_store_blob,env.SDL_Delay,env.emscripten_scan_registers,env.emscripten_lazy_load_code,env.emscripten_fiber_swap,env.__load_secondary_module,wasi_snapshot_preview1.fd_sync,env.__wasi_fd_sync,env._emval_await,env._dlopen_js,env.__asyncjs__* --zero-filled-memory --pass-arg=directize-initial-contents-immutable --strip-debug --strip-producers audio/audio_music_stream.wasm -o audio/audio_music_stream.wasm --mvp-features --enable-mutable-globals --enable-sign-ext
 "C:/emsdk/node/14.18.2_64bit/bin/node.exe" C:\emsdk\upstream\emscripten\tools\acorn-optimizer.js C:\Users\raysa\AppData\Local\Temp\emscripten_temp_04eqq9yb\audio_music_stream.js AJSDCE minifyWhitespace -o C:\Users\raysa\AppData\Local\Temp\emscripten_temp_04eqq9yb\audio_music_stream.jso1.js
 "C:/emsdk/node/14.18.2_64bit/bin/node.exe" C:\emsdk\upstream\emscripten\tools\acorn-optimizer.js C:\Users\raysa\AppData\Local\Temp\emcc_acorn_info_83pt_yf0.js emitDCEGraph noPrint
 "C:/emsdk/upstream\bin\wasm-metadce" --graph-file=C:\Users\raysa\AppData\Local\Temp\emcc_dce_graph__m2tsvmr.json audio/audio_music_stream.wasm -o audio/audio_music_stream.wasm --mvp-features --enable-mutable-globals --enable-sign-ext
 "C:/emsdk/node/14.18.2_64bit/bin/node.exe" C:\emsdk\upstream\emscripten\tools\acorn-optimizer.js C:\Users\raysa\AppData\Local\Temp\emcc_acorn_info_ldlauwk9.js applyDCEGraphRemovals minifyWhitespace -o C:\Users\raysa\AppData\Local\Temp\emscripten_temp_04eqq9yb\audio_music_stream.jso2.js
 "C:/emsdk/node/14.18.2_64bit/bin/node.exe" C:\emsdk\upstream\emscripten\tools\acorn-optimizer.js C:\Users\raysa\AppData\Local\Temp\emscripten_temp_04eqq9yb\audio_music_stream.jso2.js AJSDCE minifyWhitespace -o C:\Users\raysa\AppData\Local\Temp\emscripten_temp_04eqq9yb\audio_music_stream.jso3.js
 "C:/emsdk/upstream\bin\wasm-opt" --strip-dwarf --minify-imports-and-exports-and-modules audio/audio_music_stream.wasm -o audio/audio_music_stream.wasm --mvp-features --enable-mutable-globals --enable-sign-ext
 "C:/emsdk/node/14.18.2_64bit/bin/node.exe" C:\emsdk\upstream\emscripten\tools\acorn-optimizer.js C:\Users\raysa\AppData\Local\Temp\emcc_acorn_info_c57jzzs8.js applyImportAndExportNameChanges minifyWhitespace -o C:\Users\raysa\AppData\Local\Temp\emscripten_temp_04eqq9yb\audio_music_stream.jso4.js
 "C:/emsdk/node/14.18.2_64bit/bin/node.exe" C:\emsdk\upstream\emscripten\tools\preprocessor.js C:\Users\raysa\AppData\Local\Temp\emscripten_temp_04eqq9yb\settings.js minshell.html
 "C:\emsdk\upstream\emscripten\node_modules\.bin\html-minifier-terser.cmd" audio/audio_music_stream.html -o audio/audio_music_stream.html --collapse-whitespace --collapse-inline-tag-whitespace --remove-comments --remove-tag-whitespace --sort-attributes --sort-class-name --decode-entities --collapse-boolean-attributes --remove-attribute-quotes --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --use-short-doctype --minify-css true --minify-js true
```

**Comment by curiousdannii** [comment]
The changelog explains the change: https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3131---012623

**Comment by raysan5** [comment]
@curiousdannii Oh, I see. Thank you very much for the info!
