### ISSUE TITLE
test_pthread_dlopen_many is very flaky

### ISSUE THREAD

**Issue by dschuff** [emscripten-core/emscripten#18887]
test_pthread_dlopen_many is a stress test for dlopen, but is currently failing too often to be useful. Until recently it was mostly failing in wasm64l mode and sanitizer mode, but with the recent changes to proxying (e.g. https://github.com/emscripten-core/emscripten/pull/18852) it's happening more often.

**Comment by kleisauke** [comment]
`test_pthread_dlopen_many` in the `core0` suite appears to have started triggering the `pthread mutex deadlock detected` assertion.
https://circleci.com/gh/emscripten-core/emscripten/1228242

<details>
  <summary>Details</summary>

```console
-- begin program output --
in main: 0x12b40
hello from js
thread_main 3 0x55578
thread_main 1 0x34388
thread_main 2 0x44c80
thread_main 0 0x23a90
thread_main 6 0x87060
thread_main 5 0x76768
thread_main 8 0xa8250
thread_main 9 0xb8b48
thread_main 4 0x65e70
thread_main 7 0x97958
jslib_func via dlsym: 0x46
loading libside3.so
jslib_func via dlsym: 0x46
loading libside1.so
jslib_func via dlsym: 0x46
loading libside2.so
jslib_func via dlsym: 0x46
jslib_func via dlsym: 0x46
loading libside6.so
loading libside0.so
jslib_func via dlsym: 0x46
loading libside5.so
side module ctor
done loading libside6.so (total=1)
side module ctor
done loading libside1.so (total=2)
side module ctor
done loading libside0.so (total=3)
side module ctor
done loading libside3.so (total=4)
p_side_data_address=0x51
p_side_data_address=0x49
side module ctor
done loading libside5.so (total=5)
jslib_func via dlsym: 0x46
loading libside8.so
p_side_func_address=0x4a
done thread_main 6
p_side_data_address=0x54
jslib_func via dlsym: 0x46
loading libside7.so
p_side_data_address=0x55
side module ctor
done loading libside7.so (total=6)
p_side_func_address=0x58
done thread_main 0
Aborted(Assertion failed: at || own != __pthread_self()->tid && "pthread mutex deadlock detected", at: /emsdk/emscripten/system/lib/libc/musl/src/thread/pthread_mutex_timedlock.c,95,__pthread_mutex_timedlock)
worker: onmessage() captured an uncaught exception: RuntimeError: Aborted(Assertion failed: at || own != __pthread_self()->tid && "pthread mutex deadlock detected", at: /emsdk/emscripten/system/lib/libc/musl/src/thread/pthread_mutex_timedlock.c,95,__pthread_mutex_timedlock)
RuntimeError: Aborted(Assertion failed: at || own != __pthread_self()->tid && "pthread mutex deadlock detected", at: /emsdk/emscripten/system/lib/libc/musl/src/thread/pthread_mutex_timedlock.c,95,__pthread_mutex_timedlock)
    at abort (/tmp/emtest_l2fn81mu/emscripten_test_core0_17fraieb/test_pthread_dlopen_many.js:876:11)
    at ___assert_fail (/tmp/emtest_l2fn81mu/emscripten_test_core0_17fraieb/test_pthread_dlopen_many.js:5393:7)
    at wasm://wasm/0003cb46:wasm-function[241]:0x5c8d
    at wasm://wasm/0003cb46:wasm-function[240]:0x5b37
    at wasm://wasm/0003cb46:wasm-function[127]:0x2e43
    at wasm://wasm/0003cb46:wasm-function[139]:0x32ba
    at wasm://wasm/0003cb46:wasm-function[68]:0x1835
    at wasm://wasm/0003cb46:wasm-function[104]:0x23b5
    at wasm://wasm/0003cb46:wasm-function[106]:0x2500
    at wasm://wasm/0003cb46:wasm-function[105]:0x23f0
    at wasm://wasm/0003cb46:wasm-function[186]:0x4538
    at wasm://wasm/0003cb46:wasm-function[187]:0x45b9
    at wasm://wasm/0003cb46:wasm-function[241]:0x5c38
    at wasm://wasm/0003cb46:wasm-function[240]:0x5b37
    at wasm://wasm/0003cb46:wasm-function[142]:0x340e
    at wasm://wasm/0003cb46:wasm-function[151]:0x3a79
    at wasm://wasm/0003cb46:wasm-function[130]:0x2f4e
    at wasm://wasm/0003cb46:wasm-function[135]:0x31c0
    at wasm://wasm/0003cb46:wasm-function[130]:0x2f4e
    at wasm://wasm/0003cb46:wasm-function[302]:0x6e78
    at wasm://wasm/0003cb46:wasm-function[229]:0x55cf
    at /tmp/emtest_l2fn81mu/emscripten_test_core0_17fraieb/test_pthread_dlopen_many.js:892:12
    at finish (/tmp/emtest_l2fn81mu/emscripten_test_core0_17fraieb/test_pthread_dlopen_many.js:1826:9)
    at invokeEntryPoint (/tmp/emtest_l2fn81mu/emscripten_test_core0_17fraieb/test_pthread_dlopen_many.js:1828:7)
    at handleMessage (/tmp/emtest_l2fn81mu/emscripten_test_core0_17fraieb/test_pthread_dlopen_many.js:679:11)
    at MessagePort.<anonymous> (/tmp/emtest_l2fn81mu/emscripten_test_core0_17fraieb/test_pthread_dlopen_many.js:568:61)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:827:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
Pthread 0x00023a90 sent an error! undefined:undefined: Aborted(Assertion failed: at || own != __pthread_self()->tid && "pthread mutex deadlock detected", at: /emsdk/emscripten/system/lib/libc/musl/src/thread/pthread_mutex_timedlock.c,95,__pthread_mutex_timedlock)
node:internal/event_target:1101
  process.nextTick(() => { throw err; });
                           ^

RuntimeError: Aborted(Assertion failed: at || own != __pthread_self()->tid && "pthread mutex deadlock detected", at: /emsdk/emscripten/system/lib/libc/musl/src/thread/pthread_mutex_timedlock.c,95,__pthread_mutex_timedlock)
    at abort (/tmp/emtest_l2fn81mu/emscripten_test_core0_17fraieb/test_pthread_dlopen_many.js:876:11)
    at ___assert_fail (/tmp/emtest_l2fn81mu/emscripten_test_core0_17fraieb/test_pthread_dlopen_many.js:5393:7)
    at wasm://wasm/0003cb46:wasm-function[241]:0x5c8d
    at wasm://wasm/0003cb46:wasm-function[240]:0x5b37
    at wasm://wasm/0003cb46:wasm-function[127]:0x2e43
    at wasm://wasm/0003cb46:wasm-function[139]:0x32ba
    at wasm://wasm/0003cb46:wasm-function[68]:0x1835
    at wasm://wasm/0003cb46:wasm-function[104]:0x23b5
    at wasm://wasm/0003cb46:wasm-function[106]:0x2500
    at wasm://wasm/0003cb46:wasm-function[105]:0x23f0
    at wasm://wasm/0003cb46:wasm-function[186]:0x4538
    at wasm://wasm/0003cb46:wasm-function[187]:0x45b9
    at wasm://wasm/0003cb46:wasm-function[241]:0x5c38
    at wasm://wasm/0003cb46:wasm-function[240]:0x5b37
    at wasm://wasm/0003cb46:wasm-function[142]:0x340e
    at wasm://wasm/0003cb46:wasm-function[151]:0x3a79
    at wasm://wasm/0003cb46:wasm-function[130]:0x2f4e
    at wasm://wasm/0003cb46:wasm-function[135]:0x31c0
    at wasm://wasm/0003cb46:wasm-function[130]:0x2f4e
    at wasm://wasm/0003cb46:wasm-function[302]:0x6e78
    at wasm://wasm/0003cb46:wasm-function[229]:0x55cf
    at /tmp/emtest_l2fn81mu/emscripten_test_core0_17fraieb/test_pthread_dlopen_many.js:892:12
    at finish (/tmp/emtest_l2fn81mu/emscripten_test_core0_17fraieb/test_pthread_dlopen_many.js:1826:9)
    at invokeEntryPoint (/tmp/emtest_l2fn81mu/emscripten_test_core0_17fraieb/test_pthread_dlopen_many.js:1828:7)
    at handleMessage (/tmp/emtest_l2fn81mu/emscripten_test_core0_17fraieb/test_pthread_dlopen_many.js:679:11)
    at MessagePort.<anonymous> (/tmp/emtest_l2fn81mu/emscripten_test_core0_17fraieb/test_pthread_dlopen_many.js:568:61)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:827:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
Thrown at:
    at node:internal/event_target:1101:28
    at processTicksAndRejections (node:internal/process/task_queues:85:11)


Node.js v22.16.0
-- end program output --
common:INFO: [32mRetrying flaky test "test_core.core0.test_pthread_dlopen_many" (attempt 0/2 failed):
```
</details>

But somehow I couldn't reproduce that locally. I think introducing a pthread barrier, just like was done in `test_pthread_dlopen.c‎` via commit 0d68ae8442d3636302a8cc6cec296c1f2026c42b could possibly fix this flakiness. I just opened PR #27154 for that.
