### ISSUE TITLE
memory access out of bounds in Chrome

### ISSUE THREAD

**Issue by Surabhi16112000** [emscripten-core/emscripten#18929]
I am using a web app for testing imaging data and for small size of input (say 10MB) my web app works fine but when I upload any input file of size beyond that, it crashes with the log:
   _```
Uncaught RuntimeError: memory access out of bounds
    at dlfree (dlmalloc.c:4807)
    at operator operator delete(void*) (new.cpp:142)
    at void void std::__2::__libcpp_operator_delete<void*>(void*) (new:255)
    at void std::__2::__do_deallocate_handle_size<>(void*, unsigned void std::__2::__do_deallocate_handle_size<>(void*, unsigned long) (new:279)
    at std::__2::__libcpp_deallocate(void*, unsigned long, unsigned std::__2::__libcpp_deallocate(void*, unsigned long, unsigned long) (new:289)
    at invoke_viii (AIDE_TestApp.js:6810:29)
    at std::__2::allocator<char>::deallocate(char*, unsigned std::__2::allocator<char>::deallocate(char*, unsigned long) (allocator.h:114)
    at std::__2::allocator_traits<std::__2::allocator<char>>::deallocate(std::__2::allocator<char>&, char*, unsigned std::__2::allocator_traits<std::__2::allocator<char>>::deallocate(std::__2::allocator<char>&, char*, unsigned long) (allocator_traits.h:282)
    at std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>::~basic_string() (string:2232)
    at PerformanceTracker::~PerformanceTracker() (PerfomanceTracker.cpp:43)
```
 I am using version 3.1.21 of emsdk

**Comment by kripken** [comment]
It's possible this is undefined behavior in your application code. I would try the sanitizers:

https://emscripten.org/docs/debugging/Sanitizers.html

**Comment by Surabhi16112000** [comment]
I tried the sanitisers and it gives the following log:
```
_ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x15d30101 in thread T0
put_char @ AIDE_TestApp.js:1818
write @ AIDE_TestApp.js:1753
write @ AIDE_TestApp.js:3502
doWritev @ AIDE_TestApp.js:5820
_fd_write @ AIDE_TestApp.js:5830
$__sanitizer::internal_write(int, void const*, unsigned long) @ AIDE_TestApp.wasm:0xd17f15
$__sanitizer::ReportFile::Write(char const*, unsigned long) @ AIDE_TestApp.wasm:0xd1868b
$__sanitizer::RawWrite(char const*) @ AIDE_TestApp.wasm:0xd15107
$__sanitizer::SharedPrintfCodeNoBuffer(bool, char*, int, char const*, void*) @ AIDE_TestApp.wasm:0xd19a13
$__sanitizer::SharedPrintfCode(bool, char const*, void*) @ AIDE_TestApp.wasm:0xd19884
$__sanitizer::Report(char const*, ...) @ AIDE_TestApp.wasm:0xd19a91
$__asan::ErrorFreeNotMalloced::Print() @ AIDE_TestApp.wasm:0xd00801
$__asan::ErrorDescription::Print() @ AIDE_TestApp.wasm:0xd095db
$__asan::ScopedInErrorReport::~ScopedInErrorReport() @ AIDE_TestApp.wasm:0xd08f8f
$__asan::ReportFreeNotMalloced(unsigned long, __sanitizer::BufferedStackTrace*) @ AIDE_TestApp.wasm:0xd09d37
$__asan::Allocator::Deallocate(void*, unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) @ AIDE_TestApp.wasm:0xcfbbc9
$__asan::asan_free(void*, __sanitizer::BufferedStackTrace*, __asan::AllocType) @ AIDE_TestApp.wasm:0xcfbb6e
$free @ AIDE_TestApp.wasm:0xd0760f
$operator delete(void*) @ AIDE_TestApp.wasm:0xcf68a4
$void std::__2::__libcpp_operator_delete<void*>(void*) @ AIDE_TestApp.wasm:0x23b67
$void std::__2::__do_deallocate_handle_size<>(void*, unsigned long) @ AIDE_TestApp.wasm:0x23b22
$std::__2::__libcpp_deallocate(void*, unsigned long, unsigned long) @ AIDE_TestApp.wasm:0x23ad6
invoke_viii @ AIDE_TestApp.js:6762
$std::__2::allocator<char>::deallocate(char*, unsigned long) @ AIDE_TestApp.wasm:0x23961
$std::__2::allocator_traits<std::__2::allocator<char>>::deallocate(std::__2::allocator<char>&, char*, unsigned long) @ AIDE_TestApp.wasm:0x2376b
$std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>::~basic_string() @ AIDE_TestApp.wasm:0xcf71a1
$PerformanceTracker::~PerformanceTracker() @ AIDE_TestApp.wasm:0x5ed3ff
$PerformanceTracker::~PerformanceTracker().1 @ AIDE_TestApp.wasm:0x5ed7c4
$TestContextImpl::resetPerfMeters() @ AIDE_TestApp.wasm:0x56feb8
$TestProgressTracker::endTestCase(ITestContext*) @ AIDE_TestApp.wasm:0x57f762
$TestCase::endTest() @ AIDE_TestApp.wasm:0x5873c8
$Test::run() @ AIDE_TestApp.wasm:0x56aadb
$TestSuite::runTest() @ AIDE_TestApp.wasm:0x58bb61
$Test::run() @ AIDE_TestApp.wasm:0x56aa5d
$TestSuite::runTest() @ AIDE_TestApp.wasm:0x58bb61
$Test::run() @ AIDE_TestApp.wasm:0x56aa5d
$TestSuite::runTest() @ AIDE_TestApp.wasm:0x58bb61
$Test::run() @ AIDE_TestApp.wasm:0x56aa5d
$PotluckMain::Run(ITest*) @ AIDE_TestApp.wasm:0x565a04
$PotluckMain::Run(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>) @ AIDE_TestApp.wasm:0x5666cc
$PotluckMain::Run(char const*) @ AIDE_TestApp.wasm:0x56658f
$main_web @ AIDE_TestApp.wasm:0x4d526
(anonymous) @ AIDE_TestApp.js:799
ccall @ AIDE_TestApp.js:6209
increment_test_file_upload_no @ UploadTestFiles.js:53
reader.onload @ UploadTestFiles.js:75
load (async)
(anonymous) @ UploadTestFiles.js:68
AIDE_TestApp.js:1818     #0 0xd075ab in free+0xd075ab (http://localhost:9113/AIDE_TestApp.wasm+0xd075ab)
put_char @ AIDE_TestApp.js:1818
write @ AIDE_TestApp.js:1753
write @ AIDE_TestApp.js:3502
doWritev @ AIDE_TestApp.js:5820
_fd_write @ AIDE_TestApp.js:5830
$__sanitizer::internal_write(int, void const*, unsigned long) @ AIDE_TestApp.wasm:0xd17f15
$__sanitizer::ReportFile::Write(char const*, unsigned long) @ AIDE_TestApp.wasm:0xd1868b
$__sanitizer::RawWrite(char const*) @ AIDE_TestApp.wasm:0xd15107
$__sanitizer::SharedPrintfCodeNoBuffer(bool, char*, int, char const*, void*) @ AIDE_TestApp.wasm:0xd19a13
$__sanitizer::SharedPrintfCode(bool, char const*, void*) @ AIDE_TestApp.wasm:0xd19884
$__sanitizer::Printf(char const*, ...) @ AIDE_TestApp.wasm:0xd19862
$__sanitizer::StackTrace::Print() const @ AIDE_TestApp.wasm:0xd1c614
$__asan::ErrorFreeNotMalloced::Print() @ AIDE_TestApp.wasm:0xd008d4
$__asan::ErrorDescription::Print() @ AIDE_TestApp.wasm:0xd095db
$__asan::ScopedInErrorReport::~ScopedInErrorReport() @ AIDE_TestApp.wasm:0xd08f8f
$__asan::ReportFreeNotMalloced(unsigned long, __sanitizer::BufferedStackTrace*) @ AIDE_TestApp.wasm:0xd09d37
$__asan::Allocator::Deallocate(void*, unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) @ AIDE_TestApp.wasm:0xcfbbc9
$__asan::asan_free(void*, __sanitizer::BufferedStackTrace*, __asan::AllocType) @ AIDE_TestApp.wasm:0xcfbb6e
$free @ AIDE_TestApp.wasm:0xd0760f
$operator delete(void*) @ AIDE_TestApp.wasm:0xcf68a4
$void std::__2::__libcpp_operator_delete<void*>(void*) @ AIDE_TestApp.wasm:0x23b67
$void std::__2::__do_deallocate_handle_size<>(void*, unsigned long) @ AIDE_TestApp.wasm:0x23b22
$std::__2::__libcpp_deallocate(void*, unsigned long, unsigned long) @ AIDE_TestApp.wasm:0x23ad6
invoke_viii @ AIDE_TestApp.js:6762
$std::__2::allocator<char>::deallocate(char*, unsigned long) @ AIDE_TestApp.wasm:0x23961
$std::__2::allocator_traits<std::__2::allocator<char>>::deallocate(std::__2::allocator<char>&, char*, unsigned long) @ AIDE_TestApp.wasm:0x2376b
$std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>::~basic_string() @ AIDE_TestApp.wasm:0xcf71a1
$PerformanceTracker::~PerformanceTracker() @ AIDE_TestApp.wasm:0x5ed3ff
$PerformanceTracker::~PerformanceTracker().1 @ AIDE_TestApp.wasm:0x5ed7c4
$TestContextImpl::resetPerfMeters() @ AIDE_TestApp.wasm:0x56feb8
$TestProgressTracker::endTestCase(ITestContext*) @ AIDE_TestApp.wasm:0x57f762
$TestCase::endTest() @ AIDE_TestApp.wasm:0x5873c8
$Test::run() @ AIDE_TestApp.wasm:0x56aadb
$TestSuite::runTest() @ AIDE_TestApp.wasm:0x58bb61
$Test::run() @ AIDE_TestApp.wasm:0x56aa5d
$TestSuite::runTest() @ AIDE_TestApp.wasm:0x58bb61
$Test::run() @ AIDE_TestApp.wasm:0x56aa5d
$TestSuite::runTest() @ AIDE_TestApp.wasm:0x58bb61
$Test::run() @ AIDE_TestApp.wasm:0x56aa5d
$PotluckMain::Run(ITest*) @ AIDE_TestApp.wasm:0x565a04
$PotluckMain::Run(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>) @ AIDE_TestApp.wasm:0x5666cc
$PotluckMain::Run(char const*) @ AIDE_TestApp.wasm:0x56658f
$main_web @ AIDE_TestApp.wasm:0x4d526
(anonymous) @ AIDE_TestApp.js:799
ccall @ AIDE_TestApp.js:6209
increment_test_file_upload_no @ UploadTestFiles.js:53
reader.onload @ UploadTestFiles.js:75
load (async)
(anonymous) @ UploadTestFiles.js:68
AIDE_TestApp.js:1818     #1 0xcf68a4 in operator delete(void*)+0xcf68a4 (http://localhost:9113/AIDE_TestApp.wasm+0xcf68a4)_
```
The error is being directed to .wasm file which is not being opened on the browser.
