### ISSUE TITLE
emcc -O2 generates invalid javascript for an EM_JS function

### ISSUE THREAD

**Issue by antocuni** [emscripten-core/emscripten#18967]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.34 (57b21b8fdcbe3ebb523178b79465254668eab408)
clang version 17.0.0 (https://github.com/llvm/llvm-project a031f72187ce495b9faa4ccf99b1e901a3872f4b)
Target: wasm32-unknown-emscripten
```

**Failing command line in full:**
Consider the following file named `main.c`:

```c
#include <emscripten.h>

EM_JS(void, foo, (), {
  let length = 0;
  for (let x of [1, 2, 3]) {
    length++;
    // console.log(x); // if you uncomment it, the problem goes away
  }
  return length;
})

int main(void) {
    foo();
}
```

It generates invalid javascript if I compile it with `emcc -O2 main.c`:
```
$ emcc -O2 main.c
$ node a.out.js 
[...]
SyntaxError: Unexpected token ')'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

By inspecting `a.out.js`, the relevant problem seems to be here:
```js
function foo(){let length=0;for(;of[1,2,3]){length++}return length}

// manually prettified
function foo(){
    let length=0;
    for(; of [1,2,3]) {
        length++;
    }
    return length;
}
```
It *think* that what's happening is that some optimization passes sees that `x` is unused and completely removes the declaration, but it causes a SyntaxError in this case.

Notes:
  - if you uncomment `console.log(x)`, it works
  - `emcc -O1` works
  - `emcc -O2 -s MAIN_MODULE=1` works

**Full link command and output with `-v` appended:**
```
$ emcc -O2 main.c -v
 "/home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/bin/clang" --version
 "/home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/bin/clang" -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN -Werror=implicit-function-declaration --sysroot=/home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -O2 -v main.c -c -o /tmp/emscripten_temp_7d2xwo58/main_0.o
clang version 17.0.0 (https://github.com/llvm/llvm-project a031f72187ce495b9faa4ccf99b1e901a3872f4b)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/bin
 (in-process)
 "/home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/bin/clang-17" -cc1 -triple wasm32-unknown-emscripten -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name main.c -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/antocuni/anaconda/pyodide/demo-js-dce -resource-dir /home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/lib/clang/17 -D EMSCRIPTEN -isysroot /home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot -internal-isystem /home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/lib/clang/17/include -internal-isystem /home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten -internal-isystem /home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot/include -O2 -Werror=implicit-function-declaration -fdebug-compilation-dir=/home/antocuni/anaconda/pyodide/demo-js-dce -ferror-limit 19 -fvisibility=default -fgnuc-version=4.2.1 -fignore-exceptions -fcolor-diagnostics -vectorize-loops -vectorize-slp -iwithsysroot/include/fakesdl -iwithsysroot/include/compat -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /tmp/emscripten_temp_7d2xwo58/main_0.o -x c main.c
clang -cc1 version 17.0.0 based upon LLVM 17.0.0git default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 /home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot/include/fakesdl
 /home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot/include/compat
 /home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/lib/clang/17/include
 /home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot/include
End of search list.
 "/home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/bin/wasm-ld" -o a.out.wasm /tmp/emscripten_temp_7d2xwo58/main_0.o -L/home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten -lGL -lal -lhtml5 -lstubs -lnoexit -lc -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined-file=/tmp/tmp8io4920w.undefined --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024
 "/home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/bin/wasm-emscripten-finalize" --dyncalls-i64 --pass-arg=legalize-js-interface-exported-helpers a.out.wasm -o a.out.wasm --detect-features
 "/home/antocuni/anaconda/pyodide/emsdk/emsdk/node/14.18.2_64bit/bin/node" /home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpwqhu_3kj.json
 "/home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/bin/wasm-opt" --strip-dwarf --post-emscripten -O2 --low-memory-unused --zero-filled-memory --pass-arg=directize-initial-contents-immutable --strip-debug --strip-producers a.out.wasm -o a.out.wasm --mvp-features --enable-mutable-globals --enable-sign-ext
 "/home/antocuni/anaconda/pyodide/emsdk/emsdk/node/14.18.2_64bit/bin/node" /home/antocuni/anaconda/pyodide/emsdk/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/emscripten_temp_7d2xwo58/a.out.js JSDCE minifyWhitespace -o /tmp/emscripten_temp_7d2xwo58/a.out.jso1.js
```

/cc @hoodmane

**Comment by sbc100** [comment]
I think this is probably our JS optimizer making a mistake.

If you want to help debug you can run with `EMCC_DEBUG=1` which will save the generated JS file at each stage of the compiler in `/tmp/emscripten_temp` and you can then look at each version and which stage was the one that f'd it up.

@kripken will probably know exactly there the problem lies.

**Comment by hoodmane** [comment]
Thanks @kripken!
