### ISSUE TITLE
UnboundTypeError for long double format

### ISSUE THREAD

**Issue by am2222** [emscripten-core/emscripten#18981]
Hi,

Is there any way to support `long double` format? I keep getting this error if my function has `long double` input. 

```
Error {name: 'UnboundTypeError', message: 'Cannot call testuint due to unbound types: e', stack: 'UnboundTypeError: Cannot call testuint due to unbo…0.0.1:8080/out.js:1:42316)\n    at <anonymous>:1:8'}
```

```c++
uint64_t testuint(long double pole_lon_deg)
{
 return 2^64;
}

std::string getExceptionMessage(intptr_t exceptionPtr)
{
  return std::string(reinterpret_cast<std::exception *>(exceptionPtr)->what());
}

EMSCRIPTEN_BINDINGS(my_module)
{
  register_vector<std::vector<int>>("IntegerVectorVector");
  register_vector<long double>("LongDoubleVector");
  register_vector<std::vector<long double>>("LongDoubleVectorVector");
  register_vector<uint64_t>("BigIntegerVector");
  emscripten::function("getExceptionMessage", &getExceptionMessage);
  emscripten::function("testuint", &testuint);
}

```

**Comment by M-SAI-SOORYA** [comment]
The error message you provided suggests that the testuint function is expecting a type that is not currently bound in your Emscripten bindings.

By default, Emscripten only supports a limited set of C++ types, and long double is not one of them. However, you can manually add support for long double by using the EMSCRIPTEN_BINDINGS macro to define a binding for the type.

**Comment by sbc100** [comment]
`long double` is not a supported builtin type in embind because `long double` is a 128bit float with the wasm llvm backend.   There is no way (easy) to represent a 128bit float in JS.  I would avoid long double if I were you, especially in the your JS bindings, but also in general since they are emulated in software and will be slow, and increase code size.

Is there some way you can remove the use of `long double` from your program?

**Comment by am2222** [comment]
@sbc100 Thanks for the reply! So my issue is that I am converting a library to `wasm` and it works a lot with `uint64_t` and `long double` numbers. I can avoid using `long double` and limit my inputs. However, I cannot avoid using `uint64_t` and `uint64_t vectors`. Apparently there are limitations for `val::array(std::vector<uint64_t>)` type too.  Are there any examples of handing such types?

```c++
val test2()
{
  std::vector<uint64_t> seqnum(500);
  for (unsigned int i = 0; i < 500; i++)
  {
    uint64_t in = 18446744073709551614ULL;
    seqnum.at(i) = in;
  }
  return val::array(seqnum);
}
```

The above code returns this error

```
node:internal/process/esm_loader:91
    internalBinding('errors').triggerUncaughtException(
                              ^
Waiting for the debugger to disconnect...
BindingError: _emval_take_value has unknown type N10emscripten11memory_viewIyEE
    at Error.<anonymous> (file:///H:/test/dist/test.js:1067:22)
    at new BindingError (file:///H:/test/dist/webdggrid.js:1058:23)
    at throwBindingError (file:///H:/test/dist/test.js:1087:13)
    at requireRegisteredType (file:///H:/test/dist/test.js:2825:11)
    at __emval_take_value (file:///H:/tt/dist/test.js:2968:14)
    at test2() (wasm://wasm/003cd09e:wasm-function[53]:0x2a0a)
    at emscripten::internal::Invoker<emscripten::val>::invoke(emscripten::val (*)()) (wasm://wasm/003cd09e:wasm-function[66]:0x3b15)
    at Object.test2 (eval at new_ (file:///H:/test/dist/test.js:2084:27), <anonymous>:7:10)
    at file:///H:/test/index.js:5:17

```


One method is that I can use `register_vector<uint64_t>("BigIntegerVector")`; however, extracting an array from `BigIntegerVector` adds more steps and would be nicer if `val::array` supported it out of box.

**Comment by am2222** [comment]
@M-SAI-SOORYA Do you mean like `register_vector` function? I already used `  register_vector<long double>("LongDoubleVector");`  and `register_vector<std::vector<long double>>("LongDoubleVectorVector");` but I was looking for a more straightforward way to manage these types.

**Comment by sbc100** [comment]
We should be able to make uint64_t and int64_t should work. 

But `long double` probably not.     Does the library you are working with expect long double to be 128bit?  I would imagine not.    Does the library have some way to disable or remove the long double support?

**Comment by am2222** [comment]
@sbc100 Thanks for your help! I think if we make `std::vector<uint64_t>` work the majority of my issues will be solved. About the `long double` the library is expecting the `lat` and `long` values to be in `long double` format but I think it will work with `double` numbers too. 
One of the functions I am working on is [here](https://github.com/r-barnes/dggridR/blob/29673d70fa5e9331417a1c3063dd9f932f60c640/src/dglib.h#L54)
