### ISSUE TITLE
Acorn optimizer regression: "Cannot read property 'type' of undefined"

### ISSUE THREAD

**Issue by mmarczell-graphisoft** [emscripten-core/emscripten#19052]
I want to call quite sophisticated JS code from C++, which has npm modules as dependencies. With some previous versions of Emscripten (we used 3.1.5 in production) transpiling my js code with webpack, and including the output with `--pre-js` worked well. However, with the latest emscripten version, including some of those modules, such as `assert`, breaks the acorn optimization step with the following error:
```
[1/1] Linking CXX executable main.js
FAILED: main.js 
: && /Volumes/SSD/git/emsdk/upstream/emscripten/em++ -O3 -DNDEBUG --pre-js=webpack/pre.bundle.js CMakeFiles/main.dir/main.cpp.o -o main.js   && :
/Volumes/SSD/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:603
      if (target.type == 'ParenthesizedExpression') {
                 ^

TypeError: Cannot read property 'type' of undefined
    at isExportWrapperFunction (/Volumes/SSD/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:603:18)
    at /Volumes/SSD/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:744:25
    at fullWalk (/Volumes/SSD/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:79:3)
    at /Volumes/SSD/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:77:5
    at maybeChild (/Volumes/SSD/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:47:7)
    at Array.forEach (<anonymous>)
    at visitChildren (/Volumes/SSD/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:57:15)
    at fullWalk (/Volumes/SSD/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:76:3)
    at /Volumes/SSD/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:77:5
    at maybeChild (/Volumes/SSD/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:47:7)
em++: error: '/Volumes/SSD/git/emsdk/node/14.18.2_64bit/bin/node /Volumes/SSD/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js /var/folders/4c/w1bj9h4d5_df436ckn8xxmqr0000gq/T/emcc_acorn_info_ke_t68v1.js emitDCEGraph noPrint' failed (returned 1)

```

Please see the code reproducing this error at https://github.com/mmarczell-graphisoft/embug. 

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.34 (57b21b8fdcbe3ebb523178b79465254668eab408)
clang version 17.0.0 (https://github.com/llvm/llvm-project a031f72187ce495b9faa4ccf99b1e901a3872f4b)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Volumes/SSD/git/emsdk/upstream/bin
```
**Failing command line in full:**
```
npm install
emcmake cmake -B Build
cmake --build Build --target main
```

**Comment by kripken** [comment]
Any chance you can get a reproducer without using `npx` etc.? Basically just a single `emcc` command that fails would be best.

(I tried to run cmake/make in that repo, and I get a bunch of errors, the main one seems to be `Error: Cannot find module 'webpack-cli/package.json'`)

**Comment by mmarczell-graphisoft** [comment]
I have committed the intermediate js file that gets generated by webpack. Now you only need to

```
em++ -O3 --pre-js=Build/webpack/pre.bundle.js main.cpp -o main.js
