### ISSUE TITLE
Embind `typed_memory_view<int64_t>` does not convert to `BigInt64Array` in the browser

### ISSUE THREAD

**Issue by harichards** [emscripten-core/emscripten#19095]
Attempting to return a memory view with type `int64_t` or `uint64_t` causes a runtime error in the browser. Expected to get a `BigInt64Array` or `BigUint64Array`, respectively.

**Version of emscripten/emsdk**
```
➜ emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.34 (57b21b8fdcbe3ebb523178b79465254668eab408)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Full link command and output with `-v` appended**
```
➜ emcc -v -lembind -sWASM_BIGINT -o main.js main.cc
 "/home/ubuntu/emsdk/upstream/bin/clang" --version
 "/home/ubuntu/emsdk/upstream/bin/clang++" -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN --sysroot=/home/ubuntu/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -v main.cc -c -o /tmp/emscripten_temp_qe85hquo/main_0.o
clang version 17.0.0 (https://github.com/llvm/llvm-project a031f72187ce495b9faa4ccf99b1e901a3872f4b)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/ubuntu/emsdk/upstream/bin
 (in-process)
 "/home/ubuntu/emsdk/upstream/bin/clang-17" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name main.cc -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/ubuntu/example -resource-dir /home/ubuntu/emsdk/upstream/lib/clang/17 -D EMSCRIPTEN -isysroot /home/ubuntu/emsdk/upstream/emscripten/cache/sysroot -internal-isystem /home/ubuntu/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1 -internal-isystem /home/ubuntu/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1 -internal-isystem /home/ubuntu/emsdk/upstream/lib/clang/17/include -internal-isystem /home/ubuntu/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten -internal-isystem /home/ubuntu/emsdk/upstream/emscripten/cache/sysroot/include -fdeprecated-macro -fdebug-compilation-dir=/home/ubuntu/example -ferror-limit 19 -fvisibility=default -fgnuc-version=4.2.1 -fcxx-exceptions -fignore-exceptions -fexceptions -fcolor-diagnostics -iwithsysroot/include/fakesdl -iwithsysroot/include/compat -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /tmp/emscripten_temp_qe85hquo/main_0.o -x c++ main.cc
clang -cc1 version 17.0.0 based upon LLVM 17.0.0git default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/home/ubuntu/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1"
ignoring nonexistent directory "/home/ubuntu/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 /home/ubuntu/emsdk/upstream/emscripten/cache/sysroot/include/fakesdl
 /home/ubuntu/emsdk/upstream/emscripten/cache/sysroot/include/compat
 /home/ubuntu/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1
 /home/ubuntu/emsdk/upstream/lib/clang/17/include
 /home/ubuntu/emsdk/upstream/emscripten/cache/sysroot/include
End of search list.
 "/home/ubuntu/emsdk/upstream/bin/wasm-ld" -o main.wasm /tmp/emscripten_temp_qe85hquo/main_0.o -L/home/ubuntu/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten --whole-archive -lembind-rtti --no-whole-archive -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined-file=/tmp/tmpc08li4qd.undefined --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=malloc --export=free --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --no-entry --max-memory=16777216 --stack-first
 "/home/ubuntu/emsdk/node/14.18.2_64bit/bin/node" /home/ubuntu/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpxn1kikm6.json
 "/home/ubuntu/emsdk/upstream/bin/llvm-objcopy" main.wasm main.wasm --remove-section=.debug* --remove-section=producers
```

**Server log**
```
➜ python -m http.server 8080                    
Serving HTTP on 0.0.0.0 port 8080 (http://0.0.0.0:8080/) ...
127.0.0.1 - - [29/Mar/2023 16:24:49] "GET / HTTP/1.1" 304 -
127.0.0.1 - - [29/Mar/2023 16:24:49] "GET /main.js HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2023 16:24:49] "GET /main.wasm HTTP/1.1" 200 -
```

**Client error**
```
BindingError: _emval_take_value has unknown type N10emscripten11memory_viewIxEE
    at Error.<anonymous> (http://0.0.0.0:8080/main.js:1343:22)
    at new BindingError (http://0.0.0.0:8080/main.js:1334:23)
    at throwBindingError (http://0.0.0.0:8080/main.js:1363:13)
    at requireRegisteredType (http://0.0.0.0:8080/main.js:2345:11)
    at __emval_take_value (http://0.0.0.0:8080/main.js:2350:14)
    at emscripten::val::val<emscripten::memory_view<long long>>(emscripten::memory_view<long long>&&) (http://0.0.0.0:8080/main.wasm:wasm-function[24]:0x658)
    at get_array() (http://0.0.0.0:8080/main.wasm:wasm-function[20]:0x52b)
    at emscripten::internal::Invoker<emscripten::val>::invoke(emscripten::val (*)()) (http://0.0.0.0:8080/main.wasm:wasm-function[34]:0xa1c)
    at Object.getArray (eval at new_ (http://0.0.0.0:8080/main.js:1676:27), <anonymous>:7:10)
    at Object.onRuntimeInitialized (http://0.0.0.0:8080/:6:34)
```

**Browser information**
```
Microsoft Edge
Version 111.0.1661.54 (Official build) (64-bit)
```

**main.cc**
```cpp
#include <emscripten/bind.h>
#include <emscripten/val.h>

#include <array>
#include <cstdint>

using namespace emscripten;

std::array<std::int64_t, 5> foo = {0, 1, 2, 3, 4};

val get_array() {
    return val(typed_memory_view(foo.size(), foo.data()));
}

EMSCRIPTEN_BINDINGS(my_module) {
    function("getArray", &get_array);
}
```

**index.html**
```html
<!doctype html>
<html>
    <script>
        var Module = {
            onRuntimeInitialized: function() {
                let foo = Module.getArray();
            }
        };
    </script>
    <script src="main.js"></script>
</html>
```

**Comment by am2222** [comment]
I am getting the same issue with `uint_64` type

**Comment by harichards** [comment]
Confirmed working using v3.1.35. Thanks for the fix!

**Comment by am2222** [comment]
@brendandahl Does this fix addresses `uint_64` too? I am trying this function but I am getting the same error

```
val test2()
{

  std::vector<uint64_t> seqnum(500);
  for (unsigned int i = 0; i < 500; i++)
  {

    uint64_t in = 18446744073709551614;
    seqnum.at(i) = in;
  }
  return val::array(seqnum);
}
```
