### ISSUE TITLE
Calling JS callback from C++ thread

### ISSUE THREAD

**Issue by moondayyy** [emscripten-core/emscripten#19292]
C++: Here, the callback function in the struct I created is equal to the pointer address of the function that I will add as a parameter on the JS side.
```
extern "C" EMSCRIPTEN KEEPALIVE void InitializeLoggingWeb(void (*cbLogging)(void*, void*)) {
    Debug::debugOpts->Logging = cbLogging;
}
```

JS: My Callback function
```
function Logging(t, b) {
                        if (b === 1) {
                            log.append(UTF8ToString(t) + "<br>");
                        }
                    }
let pointerLogging = Module.addFunction(Logging, "vii");
Module.ccall('InitializeLoggingWeb', 'number', ['number'], [pointerLogging]);
```

JS: Then I init my project and hope the callback function works where necessary. However, I am getting the following error.

`Module.Initialize(options);`

```
Uncaught RuntimeError: table index is out of bounds
    at XX-XXX_Library.wasm:0x4672
    at XX-XXX_Library.wasm:0x3ff9
    at XX-XXX_Library.wasm:0x2478
    at Object.invokeEntryPoint (XX-XXX_Library.js:3966:37)
    at handleMessage (XX-XXX_Library.worker.js:164:35)
```

#18390 I'm having almost the same problem as the one here. However, I couldn't figure out how to solve it.
NOTE: The project works fine without using std::thread. I will be glad if you help me.

**Comment by sbc100** [comment]
This is because the same table is not shared between threads, so it not really safe to call `addFunction` in threaded programs.  We should probably add warning about that, or simply make it impossible.

**Comment by DreamOfIce** [comment]
Maybe you can proxy js callback to the main thread for execution?
https://emscripten.org/docs/api_reference/proxying.h.html

**Comment by abdullahaygun** [comment]
> This is because the same table is not shared between threads, so it not really safe to call `addFunction` in threaded programs. We should probably add warning about that, or simply make it impossible.

Thanks your answer, but what should I use instead of addFunction? I did not fully understand it.

**Comment by abdullahaygun** [comment]
> Maybe you can proxy js callback to the main thread for execution? https://emscripten.org/docs/api_reference/proxying.h.html


Can you share example code? I'm new so I don't quite understand.

**Comment by sbc100** [comment]
I would do something like on the native side to avoid having to call `addFunction` at all:

```
static int jsFunctionID; 

static void jsLoggingHelper(void* arg1, void* arg2) {
  callJSFunction(jsFunctionID, areg1, arg2);
}

extern "C" EMSCRIPTEN KEEPALIVE void InitializeLoggingWeb(int loggingFunctionID) {
    jsFunctionID = loggingFunctionID;
    Debug::debugOpts->Logging = jsLoggingHelper;
}
```

Then on the JS side:

```
var jsFunctionMap = {};
var loggingFunctionID = 1
jsFunctionMap[loggingFunctionID] = function(arg1, arg2) { ... }
InitializeLoggingWeb(loggingFunctionID);
```

**Comment by DreamOfIce** [comment]
> I would do something like on the native side to avoid having to call `addFunction` at all:
> 
> ```
> static int jsFunctionID; 
> 
> static void jsLoggingHelper(void* arg1, void* arg2) {
>   callJSFunction(jsFunctionID, areg1, arg2);
> }
> 
> extern "C" EMSCRIPTEN KEEPALIVE void InitializeLoggingWeb(int loggingFunctionID) {
>     jsFunctionID = loggingFunctionID;
>     Debug::debugOpts->Logging = jsLoggingHelper;
> }
> ```
> 
> Then on the JS side:
> 
> ```
> var jsFunctionMap = {};
> var loggingFunctionID = 1
> jsFunctionMap[loggingFunctionID] = function(arg1, arg2) { ... }
> InitializeLoggingWeb(loggingFunctionID);
> void callJSFunction(ID, arg1, arg2) {
>   return jsFunctionMap[ID](arg1, arg2);
> }
> ```

I think there are some typo errors:
```diff
  static void jsLoggingHelper(void* arg1, void* arg2) {
-   callJSFunction(jsFunctionID, areg1, arg2);
+   callJSFunction(jsFunctionID, arg1, arg2);
  }
```

```diff
- void callJSFunction(ID, arg1, arg2) {
+ function callJSFunction(ID, arg1, arg2) {
    return jsFunctionMap[ID](arg1, arg2);
  }
```
