### ISSUE TITLE
When using --cpuprofiler, receive TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by andyb1979** [emscripten-core/emscripten#19521]
I added --cpuprofiler onto an existing build to try it out. Want to optimise wasmModule creation & startup time

Here's the error Im receiving at runtime 

```
scichart2d.js:6812 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at lh (scichart2d.js:6812:1)
    at new eval (scichart2d.js:6970:1)
    at eval (createSingle.ts:30:1)
    at new Promise (<anonymous>)
    at createSingleInternal (createSingle.ts:20:1)
    at eval (drawExample.ts:46:1)
    at step (drawExample.ts:33:1)
    at Object.eval [as next] (drawExample.ts:14:1)
    at eval (drawExample.ts:8:1)
```

Specific line of code that's failing in the non-minified JS output from emcc is 

```}
function lh(a, b, c) {
  for (; this.Ri.length <= a;) {
    this.Ri.push(null);
  }
```
this.Ri is undefined in this case

![image](https://github.com/emscripten-core/emscripten/assets/14041557/14eae265-1584-4f9a-921c-d4d66ca9c336)

**Question** 

This seems to be failing near document.getElementById("cpuProfiler"); 

Since Im running a wasm module in my own webpage I'm guessing I need to include something else to get --cpuprofiler to work?  

---------------- 
Further details
-----------------

**Version of emscripten/emsdk:**
Currently using EMCC 2.0.25 but in the process of upgrading to latest 

**Failing command line in full:**
```
emcc   -s WASM=1 --bind --closure 1 --no-heap-copy -s USE_SDL=2 -s FETCH=1 -s ALLOW_MEMORY_GROWTH=1 -s MAX_WEBGL_VERSION=2 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -Os   -s MODULARIZE=1 -s NODEJS_CATCH_REJECTION=0 -s ENVIRONMENT=web -s EXPORTED_FUNCTIONS="[
'_main','_SCRTFillActiveTextureCharArray','_SCRTFillActiveTextureFloat','_SCRTFillActiveDoubleVector','__get_timezone','__get_daylight','__get_tzname', '_setThrew']" -s EXPORTED_RUNTIME_METHODS="['ccall', 'cwrap','lengthBytesUTF8','stringToUTF8','U
TF8ToString','callMain']"  @allobjfiles2d.list obj/GL2/Release/Core.Cpp/src/SciChart.Charting.2D.Native/src/SCRT2DCallbacks.o    --preload-file assets/TSRAssets.web.pkg --preload-file assets/SCRTNAssets.web.pkg -o scichart2d.js --pre-js findTargetFix.js --minify 0 --cpuprofiler -v
 "C:/emsdk/upstream/bin\wasm-ld.exe" @C:\Users\aburn\AppData\Local\Temp\emscripten_0t0dpzeu.rsp
 "C:/emsdk/upstream\bin\wasm-emscripten-finalize" --minimize-wasm-changes --dyncalls-i64 scichart2d.wasm -o scichart2d.wasm --detect-features
 "C:/emsdk/node/14.18.2_64bit/bin/node.exe" C:\emsdk\upstream\emscripten\src\compiler.js C:\Users\aburn\AppData\Local\Temp\tmpz08dyqmf.txt
 "C:\emsdk\upstream\emscripten\tools\file_packager.bat" scichart2d.data --from-emcc --export-name=Module --preload assets/TSRAssets.web.pkg assets/SCRTNAssets.web.pkg --no-node
 "C:/emsdk/upstream\bin\wasm-opt" --strip-dwarf --post-emscripten --no-exit-runtime -Os --low-memory-unused --zero-filled-memory --strip-debug --strip-producers scichart2d.wasm -o scichart2d.wasm --mvp-features
 "C:/emsdk/node/14.18.2_64bit/bin/node.exe" C:\emsdk\upstream\emscripten\tools\acorn-optimizer.js C:\Users\aburn\AppData\Local\Temp\emscripten_temp__i0_vlib\scichart2d.js.pp.js AJSDCE --closureFriendly
 "C:/emsdk/node/14.18.2_64bit/bin/node.exe" C:\emsdk\upstream\emscripten\tools\acorn-optimizer.js C:\Users\aburn\AppData\Local\Temp\tmpq85a3c72.js emitDCEGraph noPrint --closureFriendly
 "C:/emsdk/upstream\bin\wasm-metadce" --graph-file=C:\Users\aburn\AppData\Local\Temp\tmpn14_0i1s.txt scichart2d.wasm -o scichart2d.wasm --mvp-features
 "C:/emsdk/node/14.18.2_64bit/bin/node.exe" C:\emsdk\upstream\emscripten\tools\acorn-optimizer.js C:\Users\aburn\AppData\Local\Temp\tmpwubozsbb.js applyDCEGraphRemovals --closureFriendly
 "C:/emsdk/node/14.18.2_64bit/bin/node.exe" C:\emsdk\upstream\emscripten\tools\acorn-optimizer.js C:\Users\aburn\AppData\Local\Temp\emscripten_temp__i0_vlib\scichart2d.js.pp.js.jso.js.jso.js AJSDCE --closureFriendly
 "C:/emsdk/upstream\bin\wasm-opt" --strip-dwarf --minify-imports-and-exports-and-modules scichart2d.wasm -o scichart2d.wasm --mvp-features
 "C:/emsdk/node/14.18.2_64bit/bin/node.exe" C:\emsdk\upstream\emscripten\tools\acorn-optimizer.js C:\Users\aburn\AppData\Local\Temp\tmpm0s0c956.js applyImportAndExportNameChanges --closureFriendly

```

**Comment by andyb1979** [comment]
**Update:**
--cpuprofiler option is working perfectly with EMSDK v3.1.40 after we updated to latest!

![image](https://github.com/emscripten-core/emscripten/assets/14041557/d08c9afa-3966-47c9-a5f6-622bd4297a81)
