### ISSUE TITLE
`embind` callback is not accesible in thread

### ISSUE THREAD

**Issue by DavidGOrtega** [emscripten-core/emscripten#19572]
👋 Apologies if Im overlooking something. Im trying my best to understand emscripten but im still a rookie 🙏 

Im trying to call a callback function within C code in a thread however Im not able to access to it. I find this feature useful for native code that tends to block the UI. 

```cpp
void add(const emscripten::val& vec, int id, emscripten::val cb) {
    std::vector<float> data = input_vec(vec);

    std::thread t([this, data, id, cb](){
      // Intensive operation that blocks the main thread
      cb(id);
    });
    t.detach();
  }
```

the error

```js
nn.js:8 Uncaught ErrorEvent {isTrusted: true, message: "Uncaught TypeError: Cannot read properties of undefined (reading 'value')", filename: 'http://localhost:8082/wann.worker.js', lineno: 1, colno: 3548, …}
worker.onerror @ wann.js:8
error (async)
(anonymous) @ wann.js:8
loadWasmModuleToWorker @ wann.js:8
getNewWorker @ wann.js:8
spawnThread @ wann.js:8
___pthread_create_js @ wann.js:8
imports.<computed> @ wann.js:8
$func218 @ wann.wasm:0x25858
$dynCall_iiiii @ wann.wasm:0x99a21
ret.<computed> @ wann.js:8
(anonymous) @ wann.js:8
invoke_iiiii @ wann.js:8
imports.<computed> @ wann.js:8
$func119 @ wann.wasm:0xcc59
$dynCall_iii @ wann.wasm:0x9985c
ret.<computed> @ wann.js:8
(anonymous) @ wann.js:8
invoke_iii @ wann.js:8
imports.<computed> @ wann.js:8
$func111 @ wann.wasm:0x8b8d
$dynCall_viiii @ wann.wasm:0x99799
ret.<computed> @ wann.js:8
(anonymous) @ wann.js:8
invoke_viiii @ wann.js:8
imports.<computed> @ wann.js:8
$func112 @ wann.wasm:0x8fc8
$dynCall_viiiii @ wann.wasm:0x99d91
ret.<computed> @ wann.js:8
(anonymous) @ wann.js:8
dynCallLegacy @ wann.js:8
dynCall @ wann.js:8
(anonymous) @ wann.js:8
AnnIndex$add @ VM432:11
main @ (index):44
await in main (async)
(anonymous) @ (index):61
wann.worker.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at Object.toValue (wann.js:8:140424)
    at __emval_call (wann.js:8:153028)
    at imports.<computed> (wann.js:8:129792)
    at wann.wasm:0x99a21
    at ret.<computed> (wann.js:8:130385)
    at wann.js:8:19235
    at invoke_iiiii (wann.js:8:184393)
    at imports.<computed> (wann.js:8:129792)
    at wann.wasm:0x2004c
    at wann.wasm:0x99603
t

```

**Comment by jnickg** [comment]
I've run into this too. I am guessing it's because separate workers run on separate JS engine instances (maybe using the wrong jargon there). Been wondering if maybe there's a way to copy them across so all workers have access?

**Comment by jnickg** [comment]
That's what I'm also hoping to find out. My background is in C++ where this would "just work" so I would have expected a built in mechanism too.

**Comment by brendandahl** [comment]
The embind val handles live in JS so they are per JS context which are not shared. There are a few alternative ways to callback to the main thread, see #8212 for some examples.

**Comment by DavidGOrtega** [comment]
I have make it work with PostMessage @jnickg, still thinking that this might have less boilerplate...

**Comment by DavidGOrtega** [comment]
@brendandahl thanks for the reply.

["An example for posterity"](https://github.com/emscripten-core/emscripten/issues/8212#issuecomment-927873066)

**Comment by DavidGOrtega** [comment]
After some thoughts I have come with this solution that might be unnecessary as emscripten probably has this already implemented properly. However I have to move forward and I marked it as a technical debt to investigate later on (or anyone here can drop some light 🙏 )

```cpp
std::string uid() {
  auto now = std::chrono::system_clock::now();
  auto now_ms = std::chrono::time_point_cast<std::chrono::milliseconds>(now);
  auto epoch = now_ms.time_since_epoch();
  auto timestamp = std::chrono::duration_cast<std::chrono::milliseconds>(epoch).count();

  std::random_device rd;
  std::mt19937 gen(rd());
  std::uniform_int_distribution<> distr(0, 99999);
  int random_number = distr(gen);

  std::string unique_id = std::to_string(timestamp) + "." + std::to_string(random_number);

  return unique_id;
}

EM_ASYNC_JS(bool, await_tid, (const char* tid, int timeout), {
  const id = UTF8ToString(tid);
  this[id] = true; 
  return new Promise(function(resolve, reject) {
    const watcher = setInterval(() => {
      if (!this[id]) {
        clearInterval(watcher);
        resolve(true);
      }
    }, 30);

    setTimeout(() => {
      clearInterval(watcher);
      reject(false)
    }, timeout * 1000);
  });
});
```

then my code is using `await_tid` as:

```cpp
void add(const emscripten::val& vec, int id) {
    std::string tid = uid();

    MAIN_THREAD_EM_ASM({ 
      const wid = UTF8ToString($0);
      this[wid] = true; 
    }, tid.c_str());

    std::vector<float> data = input_vec(vec);
    std::thread t([this, data, id, tid](){
      index_->addPoint((void*) data.data(), (size_t) id);

      MAIN_THREAD_EM_ASM({ 
        const wid = UTF8ToString($0);
        delete this[wid]; 
      }, tid.c_str());
    });

    t.detach();

    await_tid(tid.c_str(), 2);
  }
```
