### ISSUE TITLE
runtime_debug/checkInt overly aggressive when ASSERTIONS=2

### ISSUE THREAD

**Issue by RosHartigan** [emscripten-core/emscripten#19655]
When I run my emscripten app for debugging after compiling it with ASSERTIONS=2, the app aborts after calling stat, and after calling fillMouseEventData.

- In stat, the stat.rdev instance member is 'undefined', which causes an abort. (library_workerfs.js:85)
- In fillMouseEventData, 'e.clientX - rect.left' resolves to a float, not an int, which also causes an abort. (library_html5.js:439)
 
I believe this pull request is the breaking change for me: https://github.com/emscripten-core/emscripten/pull/19251

I've reverted to ASSERTIONS=1, but I'd love to debug with a higher assertion level.

**Console output**
t RuntimeError: Aborted(Assertion failed: attempt to write non-integer (undefined) into integer heap)
    at abort (cskyclasses-debug.js:836:10)
    at assert (cskyclasses-debug.js:615:3)
    at checkInt (cskyclasses-debug.js:1074:2)
    at checkInt32 (cskyclasses-debug.js:1085:27)
    at setValue_safe (cskyclasses-debug.js:5460:3)
    at SAFE_HEAP_STORE (cskyclasses-debug.js:564:2)
    at Object.doStat (cskyclasses-debug.js:4697:3)
    at ___syscall_stat64 (cskyclasses-debug.js:5807:19)
    at fstatat (fstatat.c:148:9)
    at stat (stat.c:6:9)

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.41 (71634e036d20209a5d81c2b2171e145b44de1e12)
clang version 17.0.0 (https://github.com/llvm/llvm-project 88421ea973916e60c34beb26597a5fc33f83dd8f)
Target: wasm32-unknown-emscripten
Thread model: posix

**Full link command and output with `-v` appended:**
Output of link is attached.
[ssww_emcc_link_log_2023-06-19.txt](https://github.com/emscripten-core/emscripten/files/11807360/ssww_emcc_link_log_2023-06-19.txt)

**Comment by sbc100** [comment]
For the rdev issues I have uploaded #19657.. for the fillMouseEventData issue, do you know why `e.clientX - rect.left` results in a floating point value?   I would have through those would be measures in pixels and be integers... but I'm not an export on these things.  Can you share the values that `e.clientX` and `rect.left` have?

**Comment by RosHartigan** [comment]
Thanks for responding!

rect is a DOMRect with members that _can_ be floating point, e is the event structure with int members.

> rect: DOMRect {x: 175.1953125, y: 0, width: 1701, height: 410, top: 0, …}
> e: MouseEvent {isTrusted: true, screenX: 689, screenY: 475, clientX: 414, clientY: 368, …}

**Comment by RosHartigan** [comment]
That seems like the best solution, given that all the other coordinates are integer.
