### ISSUE TITLE
`test_pthread_print_override_modularize` is failing on macOS after node upgrade to v16

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#19683]
Ever since we updated the version of node running on the emscripten-releases builder or (https://chromium-review.googlesource.com/c/emscripten-releases/+/4634060) this test has been failing consistenly, but only on macOS and only on the emscripten-releases waterfall (not on the github CI mac bots).

See https://logs.chromium.org/logs/emscripten-releases/buildbucket/cr-buildbucket/8777589317403048353/+/u/Emscripten_testsuite__other_/stdout

```
FAIL: test_pthread_print_override_modularize (test_other.other)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/s/w/ir/cache/vpython/store/cpython-ste21jq03jlov0apfh16dstb30/contents/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/opt/s/w/ir/cache/vpython/store/cpython-ste21jq03jlov0apfh16dstb30/contents/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/opt/s/w/ir/cache/vpython/store/cpython-ste21jq03jlov0apfh16dstb30/contents/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/opt/s/w/ir/x/w/install/emscripten/test/common.py", line 227, in decorated
    f(self, *args, **kwargs)
  File "/opt/s/w/ir/x/w/install/emscripten/test/test_other.py", line 5960, in test_pthread_print_override_modularize
    self.assertContained('hello, earth!', output)
  File "/opt/s/w/ir/x/w/install/emscripten/test/common.py", line 1112, in assertContained
    self.fail("Expected to find '%s' in '%s', diff:\n\n%s\n%s" % (
  File "/opt/s/w/ir/cache/vpython/store/cpython-ste21jq03jlov0apfh16dstb30/contents/lib/python3.8/unittest/case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: Expected to find 'hello, earth!
' in 'received "loaded" command from terminated worker: 1
received "callHandler" command from terminated worker: 1
', diff:

--- expected
+++ actual
@@ -1 +1,3 @@
-hello, earth!
+received "loaded" command from terminated worker: 1
+received "callHandler" command from terminated worker: 1
+
```

It seems like some kind of race between the thread/program exiting and postMessages being received from the workers.. but I can't seem to reproduce it.

**Comment by dschuff** [comment]
I had some luck awhile back getting some of the other flaky failures to reproduce on Linux by pinning a bunch of processes to a few CPUs to slow everything down.

**Comment by sbc100** [comment]
This flake looks like the same issue with races on pthread shutdown that we see in other flaky tests.

**Comment by jkukkula** [comment]
We hit this in our tests.
Very hasty debug session makes it appear that the promise returned by `worker.terminate();` is not awaited to resolve before the worker's onmessage handler is made to throw an error, so it's possible to get messages from worker still hit the message handler.

The behaviour of `worklet.terminate() `has changed in node v12.5.0, so the implementation probably was ok until that: https://nodejs.org/api/worker_threads.html#workerterminate
> This function now returns a Promise. Passing a callback is deprecated, and was useless up to this version, as the Worker was actually terminated synchronously. Terminating is now a fully asynchronous operation.

**Comment by sbc100** [comment]
Thanks for the pointer about `worker.terminate()`.  Sadly it looks like WebWorker's `terminate` does not do this: https://developer.mozilla.org/en-US/docs/Web/API/Worker/terminate#return_value.

The other problem I've run into while trying to solve this issue is that or shutdown process is currently not setup to be async.. and making async proved harder than I expected.

**Comment by juj** [comment]
Had a look at this today.

The root problem here is a logical design flaw that was introduced by this PR: https://github.com/emscripten-core/emscripten/pull/17925

The problem is that if we have the following program:

```c
void pthread_main()
{
  printf("hello, world!\n");
  exit(0); // Terminates the whole process from pthread (and not just the pthread)
}

int main()
{
  pthread_create(..., pthread_main, ...);
}
```
or the following program:
```c
void pthread_main()
{
  printf("hello, world!\n");
}

int main()
{
  pthread_create(..., pthread_main, ...);
  pthread_join(pthread_main);
  exit(0);
}
```

Then after PR #17925, neither of the above programs are guaranteed to print out hello world anymore.

The reason is that PR #17925 changed all printing from pthreads to be proxied to the main thread by using `postMessage()`. Before that PR, all prints would be handled by the Worker scope locally (i.e. call `console.log()` in the Worker itself, and don't proxy the print to main thread)

The problem that this postMessage() causes is that it breaks sequential consistency in a pthread synchronization with the main thread, due to Emscripten applications also having another message pipe: the WebAssembly heap -based proxying queue.

So printing now always takes a `postMessage()` path from worker to main thread, but `exit(0)` in a pthread always takes the Wasm proxying queue path.

There is no guaranteed synchronization between these two pipes, and the main thread can e.g. flush the Wasm queue before the postMessage queue. If that happens, then the program will exit without seeing the print message come through.

**Comment by juj** [comment]
In PR https://github.com/emscripten-core/emscripten/pull/25048 I thought that a simple fix to this issue would be to convert `exit(0)` to also use postMessage()-based proxying. This way printing and exiting will be sequentially consistent with each other. And that certainly fixed the test `other.test_pthread_print_override_modularize

But this would mean that pthreads could no longer synchronously exit the whole process, but the main thread would have to yield in order for that to happen. This broke posixtest suite, which uses structures that remind the following:

```c
void pthread_main()
{
  exit(0);
}

int main()
{
  pthread_create(..., pthread_main, ...);
  pthread_join(pthread_main);
}
```
i.e. create a pthread that wants to quit the program, and try to join with it on the main thread. This should shut down the application and halt blocking in pthread_join().

Even if the above scenario was ignored (e.g. on the basis of "blocking on the main thread blah blah"), there would still be a problem with approach #25048 that sequential consistency with respect to printing and exiting and other wasm heap proxied operations (e.g. fopen/fread/fwrite) would still not be preserved.

So then e.g. a program

```
void pthread_main()
{
  fopen("filename");
  fwrite("foo");
  fclose();
  exit(0);
}

int main()
{
  pthread_create(..., pthread_main, ...);
}
```
would again not have sequential consistency with respect to file writing and exiting.

So it seems that the only fixes are to

a) revert PR https://github.com/emscripten-core/emscripten/pull/17925 and let `printf()` and `Module.print()` call to `console.log()` in the Workers again, instead of proxying. Running a stress test on the background of this scenario, the Workers will process the print before the program exits, even though the synchronization here is not obvious or explicit. This however would break the feature that setting `Module.print()` function on main thread will then not apply to printing made in pthreads (one might argue, why should it? To me the feature proposed in #17925 is ill-defined)

b) change the proxying of callHandlers to use the wasm heap, instead of bare postMessage()s. This will have quite drastic implications to application performance, and it will require an alive pthread runtime on the main thread, so it is quite a tricky proposition. For correctness, one might start thinking at this point to use a second SAB for proxying purposes, that would work even if main thread runtime has already aborted (and hence wouldn't have a working C malloc alive anymore)

**Comment by juj** [comment]
> Running a stress test

The test I conducted was to disable the `callHandlers` mechanism, just via:

```diff
diff --git a/src/runtime_pthread.js b/src/runtime_pthread.js
index a77b2d9bb..d855121f9 100644
--- a/src/runtime_pthread.js
+++ b/src/runtime_pthread.js
@@ -81,6 +81,7 @@ if (ENVIRONMENT_IS_PTHREAD) {

         // Use `const` here to ensure that the variable is scoped only to
         // that iteration, allowing safe reference from a closure.
+        /*
         for (const handler of msgData.handlers) {
           // The the main module has a handler for a certain even, but no
           // handler exists on the pthread worker, then proxy that handler
@@ -103,6 +104,7 @@ if (ENVIRONMENT_IS_PTHREAD) {
           else dbg(`worker: using thread-local handler: ${handler}`);
 #endif
         }
+        */

 #if !WASM_ESM_INTEGRATION
         wasmMemory = msgData.wasmMemory;
```
i.e. pthreads will call `emscripten_out()` -> `Module.print()` -> `console.log()` in the Worker, rather than `postMessage()`ing the string to print to the main thread. This removed the instability of the test in my stress scenario.

I am not sure that it is a good idea to have a design where the main thread would define the print and printErr functions dynamically at runtime, requiring all prints to be serialized over to the main thread. I would recommend the `callHandlers` abstraction to be removed.

**Comment by juj** [comment]
To coax out the breakage of sequential consistency, the following test program can be used:

`prerun.js`
```js
if (!ENVIRONMENT_IS_PTHREAD) {
  Module.print = (text) => { console.log(text); }
}
```

`test.c`
```c
#include <pthread.h>
#include <emscripten/console.h>

void *pthread_main(void *arg) {
	emscripten_out("thread has started.");
	return 0;
}

int main() {
	pthread_t t;
	pthread_create(&t, 0, pthread_main, 0);
	pthread_join(t, 0);
	emscripten_out("thread has quit.");
}
```
Command line: `emcc test.c -pthread --pre-js prerun.js -o a.js`

This program will deterministically always print
```
thread has quit.
thread has started.
```
------------
Whereas when run with command line: `emcc test.c -pthread -o a.js`, the program will print
```
thread has started.
thread has quit.
```
as expected, since the `callHandlers` mechanism is not getting enabled.

**Comment by kleisauke** [comment]
I just opened PR #25208 for this. I could not (easily) revert that whole `callHandlers` abstraction due to the new `.proxy` logic:
https://github.com/emscripten-core/emscripten/blob/80ca182d92aa33f874acd2f25718143ce8848f37/test/browser_reporting.js#L107-L111
