### ISSUE TITLE
test_abort_on_exceptions_pthreads is flaky

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#20067]
```
======================================================================
FAIL: test_abort_on_exceptions_pthreads (test_core.core0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\b\s\w\ir\cache\vpython\store\cpython-e6tenrlsesftvg6k08ajgkk7b4\contents\bin\Lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "C:\b\s\w\ir\cache\vpython\store\cpython-e6tenrlsesftvg6k08ajgkk7b4\contents\bin\Lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "C:\b\s\w\ir\cache\vpython\store\cpython-e6tenrlsesftvg6k08ajgkk7b4\contents\bin\Lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "C:\b\s\w\ir\x\w\install\emscripten\test\common.py", line 237, in decorated
    f(self, *args, **kwargs)
  File "C:\b\s\w\ir\x\w\install\emscripten\test\test_core.py", line 9607, in test_abort_on_exceptions_pthreads
    self.do_core_test('test_hello_world.c')
  File "C:\b\s\w\ir\x\w\install\emscripten\test\test_core.py", line 360, in do_core_test
    self.do_run_in_out_file_test(Path('core', testname), **kwargs)
  File "C:\b\s\w\ir\x\w\install\emscripten\test\common.py", line 1474, in do_run_in_out_file_test
    output = self._build_and_run(srcfile, expected, **kwargs)
  File "C:\b\s\w\ir\x\w\install\emscripten\test\common.py", line 1512, in _build_and_run
    js_output = self.run_js(js_file, engine, args,
  File "C:\b\s\w\ir\x\w\install\emscripten\test\common.py", line 1105, in run_js
    self.fail('JS subprocess failed (%s): %s.  Output:\n%s' % (error.cmd, error.returncode, ret))
  File "C:\b\s\w\ir\cache\vpython\store\cpython-e6tenrlsesftvg6k08ajgkk7b4\contents\bin\Lib\unittest\case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: JS subprocess failed (C:/b/s/w/ir/cache/builder/emscripten-releases/node-v16.20.0-win-x64/bin/node.exe --stack-trace-limit=50 --trace-uncaught C:\b\s\w\ir\x\t\emtest_x2r2d6xg\emscripten_test_core0_nppgbyhw\test_hello_world.js): 7.  Output:
hello, world!
C:\b\s\w\ir\x\t\emtest_x2r2d6xg\emscripten_test_core0_nppgbyhw\test_hello_world.js:148
      throw ex;
      ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "program has already aborted!".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
Thrown at:
    at getErrorWithoutStack (node:internal/process/promises:311:15)
    at generateUnhandledRejectionError (node:internal/process/promises:331:15)
    at processPromiseRejections (node:internal/process/promises:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
 ```

**Comment by juj** [comment]
It looks like there is still a hang in this test.

The test deadlocks occassionally: http://clbri.com:8010/#/builders/11/builds/488

**Comment by brendandahl** [comment]
Also seen on emscripten-releases testers https://logs.chromium.org/logs/emscripten-releases/buildbucket/cr-buildbucket/8702978981420678449/+/u/Emscripten_testsuite__wasm64l_/stdout

**Comment by sbc100** [comment]
Seems like maybe and unrelated issue.    I sometimes see node timeout on wasm64 tests for no apparent reason.   Like it has something in the event loop queue, but I've never been able to debug it.
