### ISSUE TITLE
test_pthread_print_override_modularize is flaky

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#20142]
Looks like another example of the racey shutdown behaviour in pthreaded programs:

```
======================================================================
FAIL: test_pthread_print_override_modularize (test_other.other)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/b/s/w/ir/cache/vpython/store/cpython-n8umfpv0s1ufm2q1s4irhb59jc/contents/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield======================================================================
FAIL: test_pthread_print_override_modularize (test_other.other)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/b/s/w/ir/cache/vpython/store/cpython-n8umfpv0s1ufm2q1s4irhb59jc/contents/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/b/s/w/ir/cache/vpython/store/cpython-n8umfpv0s1ufm2q1s4irhb59jc/contents/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/b/s/w/ir/cache/vpython/store/cpython-n8umfpv0s1ufm2q1s4irhb59jc/contents/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/b/s/w/ir/x/w/install/emscripten/test/common.py", line 245, in decorated
    f(self, *args, **kwargs)
  File "/b/s/w/ir/x/w/install/emscripten/test/test_other.py", line 6064, in test_pthread_print_override_modularize
    self.assertContained('hello, earth!', output)
  File "/b/s/w/ir/x/w/install/emscripten/test/common.py", line 1216, in assertContained
    self.fail("Expected to find '%s' in '%s', diff:\n\n%s\n%s" % (
  File "/b/s/w/ir/cache/vpython/store/cpython-n8umfpv0s1ufm2q1s4irhb59jc/contents/lib/python3.8/unittest/case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: Expected to find 'hello, earth!
' in 'received "callHandler" command from terminated worker: 1
', diff:

--- expected
+++ actual
@@ -1 +1,2 @@
-hello, earth!
+received "callHandler" command from terminated worker: 1
+
  File "/b/s/w/ir/cache/vpython/store/cpython-n8umfpv0s1ufm2q1s4irhb59jc/contents/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/b/s/w/ir/cache/vpython/store/cpython-n8umfpv0s1ufm2q1s4irhb59jc/contents/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/b/s/w/ir/x/w/install/emscripten/test/common.py", line 245, in decorated
    f(self, *args, **kwargs)
  File "/b/s/w/ir/x/w/install/emscripten/test/test_other.py", line 6064, in test_pthread_print_override_modularize
    self.assertContained('hello, earth!', output)
  File "/b/s/w/ir/x/w/install/emscripten/test/common.py", line 1216, in assertContained
    self.fail("Expected to find '%s' in '%s', diff:\n\n%s\n%s" % (
  File "/b/s/w/ir/cache/vpython/store/cpython-n8umfpv0s1ufm2q1s4irhb59jc/contents/lib/python3.8/unittest/case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: Expected to find 'hello, earth!
' in 'received "callHandler" command from terminated worker: 1
', diff:

--- expected
+++ actual
@@ -1 +1,2 @@
-hello, earth!
+received "callHandler" command from terminated worker: 1
+

```

**Comment by sbc100** [comment]
Dupe of #19683
