### ISSUE TITLE
`emscripten_force_exit` waits for scheduled work

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#20315]
Example:

```c
#include <stdio.h>
#include <emscripten.h>

static void delayedWork(void *unused) {
  puts("2");
}

int main() {
  puts("1");
  emscripten_async_call(delayedWork, NULL, 5000);
  emscripten_force_exit(0);
}
```

When executed in either Node.js or browser, you can see that it attempts to execute the scheduled work and fails on assertions because runtime counters are already zeroed:

```
> node a.out.js
1
Aborted(Assertion failed)
/home/rreverser/emscripten/a.out.js:127
      throw ex;
      ^

RuntimeError: Aborted(Assertion failed)
    at abort (/home/rreverser/emscripten/a.out.js:648:11)
    at assert (/home/rreverser/emscripten/a.out.js:361:5)
    at runtimeKeepalivePop (/home/rreverser/emscripten/a.out.js:1200:7)
    at Timeout._onTimeout (/home/rreverser/emscripten/a.out.js:1207:9)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

Node.js v19.9.0
```

Additionally, in Node.js it's particularly obvious that it waits those 5 seconds for the scheduled work to finish.

I believe, based on the description, `emscripten_force_exit` should exit without waiting for any work or attempting to execute it.

**Comment by RReverser** [comment]
> I think the problem is that emscripten_force_exit is only really supposed to exit the current emscripten module.. not the entire node process. Imagine you had several emscripten modules in the same node process

Hm yeah that's fair, I can see how it can be hard to do this cleanup correctly. I think [`async_hooks`](https://nodejs.org/api/async_hooks.html) might be helpful here - I've seen folks using it to intercept any local async events together - but it still wouldn't be trivial.

Either way, the more immediate issue here is the assertion failure. In Asyncify code callbacks have something like `if (ABORT) return;` - I suspect the runtime keepalive code is missing something similar.

**Comment by sbc100** [comment]
I guess you could argue that the assert is correct.. a callback fired after runtime exit, which probably points a bug.   I guess we could instead just ignore any callbacks that happen after exit.... at least for now since we don't have any useful way to cancel that work on exit.

**Comment by RReverser** [comment]
> I guess we could instead just ignore any callbacks that happen after exit....

Yeah as I said that's what some other parts of runtime are already doing. If we could properly cancel the work like you described above, that would be even better, but 1) that would be possible only in Node.js, except for simple things like `setTimeout` that have cancellation counterparts and 2) for now it should be at least ignored IMO.

**Comment by sbc100** [comment]
Ah yes, I think its fine for `runtimeKeepalivePop` to have check for ABORT at the top, just like `callUserCallback`

**Comment by sbc100** [comment]
That check could also just be there in `ASSERTIONS` builds I think.

**Comment by RReverser** [comment]
Hm I don't really understand why some functions - like `calUserCallback` - check for both `runtimeExited` and `ABORT`, while others - like `Asyncify`'s callback - check only for `ABORT`.

Is this inconsistency intentional? If so, which one should be used in this scenario?

**Comment by sbc100** [comment]
I think its most just historical accident.

**Comment by RReverser** [comment]
But they're not always set to `true` together either... You think they can be unified somehow? If not, still unsure which one to use here.

**Comment by sbc100** [comment]
I'm sure there is room for unification/improvement here.  Until then, I would recommend checking both.
