### ISSUE TITLE
"-sSTRICT=1" does not work with "--preload-file"

### ISSUE THREAD

**Issue by fs-eire** [emscripten-core/emscripten#20361]
**Version of emscripten/emsdk:**
3.1.46

"-sSTRICT=1" does not work with "--preload-file". 

"-s INCOMING_MODULE_JS_API=[preRun]" can fix this (the preload file feature depends on it), but no document is referring to this. It takes a while to debug and find the root cause.

Possible fix:
1. warn user that they need to manually put "preRun" into INCOMING_MODULE_JS_API and pass that to commandline args
2. implicitly include "preRun" into INCOMING_MODULE_JS_API when "--preload-file" is specified.
3. Change the implementation to a different way so that it does not depend on "preRun".

**Comment by sbc100** [comment]
1 sounds like a good fix.  Honestly I'm surprised you don't see a warning since we do have one in place for such things: https://github.com/emscripten-core/emscripten/blob/efc13c67456271592b52e3d538d42d46584b31ee/src/runtime_debug.js#L22-L26

I guess there must be some reason its not firing in this case.  Did you run a debug build (i.e. a build without optimizations or with `-sASSERTIONS` enabled)?

**Comment by fs-eire** [comment]
I used debug build but with -sASSERTIONS=0 because it takes too long to run with ASSERTIONS=2

since I don't enable the ASSERTIONS, It is OK to have no warning messages.

However, even without -sASSERTIONS, I don't expect it keeps running until fopen() complains file not exist

**Comment by sbc100** [comment]
You don't see `Module.preRun was supplied but preRun not included in INCOMING_MODULE_JS_API`?  You should be seeing that error.  I'll take a look and see if I can figure it out.

**Comment by sbc100** [comment]
When I build with `-sSTRICT` and `--preload-file` I see that error as expected:

```
$ ./emcc -sSTRICT --preload-file=emcc.py
$ node a.out.js 
Aborted(`Module.preRun` was supplied but `preRun` not included in INCOMING_MODULE_JS_API)
/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:314
      throw ex;
      ^

RuntimeError: Aborted(`Module.preRun` was supplied but `preRun` not included in INCOMING_MODULE_JS_API)
    at abort (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:815:11)
    at ignoredModuleProp (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:1022:5)
    at checkIncomingModuleAPI (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:4237:3)
    at Object.<anonymous> (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:470:1)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

Can you check that you generated JS file contains the line `ignoredModuleProp('preRun');`?  Does it include `ignoredModuleProp` at all?

**Comment by fs-eire** [comment]
Sure, building the code...

**Comment by sbc100** [comment]
> I'm also getting this error on the recent versions. Shouldn't Emscripten automatically assume `preRun` in `INCOMING_MODULE_JS_API` if its internal implementation of `--preload-file` requires this - i.e., essentially the suggestion 2 from the original post?

Yes, I agree emscripten should certainly do this.

**Comment by emaxx-google** [comment]
thanks!
