### ISSUE TITLE
Sphinx-build no longer working?

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#20390]
Trying to make new docs, I get

```
C:\emsdk\emscripten\main\site>make html
Running Sphinx v7.2.6
WARNING: The pre-Sphinx 1.0 'intersphinx_mapping' format is deprecated and will be removed in Sphinx 8. Update to the current format as described in the documentation. Hint: "intersphinx_mapping = {'<name>': ('http://docs.python.org/', None)}".https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping
loading intersphinx inventory from http://docs.python.org/objects.inv...
intersphinx inventory has moved: http://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
writing output...
building [html]: targets for 85 source files that are out of date
updating environment: [new config] 85 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
copying assets... copying static files... done
copying extra files... done
done
writing output... [  1%] docs/api_reference/Filesystem-API
Theme error:
An error happened in rendering the page docs/api_reference/Filesystem-API.
Reason: UndefinedError("'style' is undefined")
```

and `C:\emsdk\emscripten\main\site\build\html` is not generated. It is not obviously clear what is causing this. Searching `'style'` or `"style"` in the `C:\emsdk\emscripten\main\site\` subtree does not find any hits.

I wonder if docs are building ok recently?

**Comment by sbc100** [comment]
I think we depend on specific version of sphinx to be used.  I'm not sure why you don't see this error:

https://github.com/emscripten-core/emscripten/blob/10e5db9fbd992e2449e32116fc3a9e8d2d072041/site/Makefile#L11-L14

**Comment by sbc100** [comment]
Actually this is the one that is supposed to check for the exact version match:  https://github.com/emscripten-core/emscripten/blob/10e5db9fbd992e2449e32116fc3a9e8d2d072041/site/Makefile#L16-L18

**Comment by juj** [comment]
Oh I see.

Hmm, tried to downgrade, but that didn't go too well:

```
C:\emsdk\emscripten\main\site>pip install -U --user sphinx==2.4.4
Collecting sphinx==2.4.4
  Downloading Sphinx-2.4.4-py3-none-any.whl (2.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 28.9 MB/s eta 0:00:00
Requirement already satisfied: sphinxcontrib-applehelp in c:\users\jukkaj\appdata\roaming\python\python311\site-packages (from sphinx==2.4.4) (1.0.7)
Requirement already satisfied: sphinxcontrib-devhelp in c:\users\jukkaj\appdata\roaming\python\python311\site-packages (from sphinx==2.4.4) (1.0.5)
Requirement already satisfied: sphinxcontrib-jsmath in c:\python311\lib\site-packages (from sphinx==2.4.4) (1.0.1)
Requirement already satisfied: sphinxcontrib-htmlhelp in c:\users\jukkaj\appdata\roaming\python\python311\site-packages (from sphinx==2.4.4) (2.0.4)
Requirement already satisfied: sphinxcontrib-serializinghtml in c:\users\jukkaj\appdata\roaming\python\python311\site-packages (from sphinx==2.4.4) (1.1.9)
Requirement already satisfied: sphinxcontrib-qthelp in c:\users\jukkaj\appdata\roaming\python\python311\site-packages (from sphinx==2.4.4) (1.0.6)
Requirement already satisfied: Jinja2>=2.3 in c:\users\jukkaj\appdata\roaming\python\python311\site-packages (from sphinx==2.4.4) (3.1.2)
Requirement already satisfied: Pygments>=2.0 in c:\python311\lib\site-packages (from sphinx==2.4.4) (2.16.1)
Requirement already satisfied: docutils>=0.12 in c:\python311\lib\site-packages (from sphinx==2.4.4) (0.20.1)
Requirement already satisfied: snowballstemmer>=1.1 in c:\python311\lib\site-packages (from sphinx==2.4.4) (2.2.0)
Requirement already satisfied: babel!=2.0,>=1.3 in c:\users\jukkaj\appdata\roaming\python\python311\site-packages (from sphinx==2.4.4) (2.13.0)
Requirement already satisfied: alabaster<0.8,>=0.7 in c:\users\jukkaj\appdata\roaming\python\python311\site-packages (from sphinx==2.4.4) (0.7.13)
Requirement already satisfied: imagesize in c:\python311\lib\site-packages (from sphinx==2.4.4) (1.4.1)
Requirement already satisfied: requests>=2.5.0 in c:\users\jukkaj\appdata\roaming\python\python311\site-packages (from sphinx==2.4.4) (2.31.0)
Requirement already satisfied: setuptools in c:\python311\lib\site-packages (from sphinx==2.4.4) (65.5.0)
Requirement already satisfied: packaging in c:\python311\lib\site-packages (from sphinx==2.4.4) (23.2)
Requirement already satisfied: colorama>=0.3.5 in c:\users\jukkaj\appdata\roaming\python\python311\site-packages (from sphinx==2.4.4) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\python311\lib\site-packages (from Jinja2>=2.3->sphinx==2.4.4) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\jukkaj\appdata\roaming\python\python311\site-packages (from requests>=2.5.0->sphinx==2.4.4) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in c:\python311\lib\site-packages (from requests>=2.5.0->sphinx==2.4.4) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\python311\lib\site-packages (from requests>=2.5.0->sphinx==2.4.4) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jukkaj\appdata\roaming\python\python311\site-packages (from requests>=2.5.0->sphinx==2.4.4) (2023.7.22)
INFO: pip is looking at multiple versions of sphinxcontrib-applehelp to determine which version is compatible with other requirements. This could take a while.
Collecting sphinxcontrib-applehelp (from sphinx==2.4.4)
  Downloading sphinxcontrib_applehelp-1.0.6-py3-none-any.whl (120 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.0/120.0 kB 6.9 MB/s eta 0:00:00
  Downloading sphinxcontrib_applehelp-1.0.5-py3-none-any.whl (120 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.0/120.0 kB 7.3 MB/s eta 0:00:00
  Downloading sphinxcontrib_applehelp-1.0.4-py3-none-any.whl (120 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.6/120.6 kB ? eta 0:00:00
INFO: pip is looking at multiple versions of sphinxcontrib-devhelp to determine which version is compatible with other requirements. This could take a while.
Collecting sphinxcontrib-devhelp (from sphinx==2.4.4)
  Downloading sphinxcontrib_devhelp-1.0.4-py3-none-any.whl (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.5/83.5 kB 4.6 MB/s eta 0:00:00
  Downloading sphinxcontrib_devhelp-1.0.3-py3-none-any.whl (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.5/83.5 kB 4.9 MB/s eta 0:00:00
  Downloading sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.7/84.7 kB ? eta 0:00:00
INFO: pip is looking at multiple versions of sphinxcontrib-htmlhelp to determine which version is compatible with other requirements. This could take a while.
Collecting sphinxcontrib-htmlhelp (from sphinx==2.4.4)
  Downloading sphinxcontrib_htmlhelp-2.0.3-py3-none-any.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 kB 5.9 MB/s eta 0:00:00
  Downloading sphinxcontrib_htmlhelp-2.0.2-py3-none-any.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 kB 5.6 MB/s eta 0:00:00
  Downloading sphinxcontrib_htmlhelp-2.0.1-py3-none-any.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.8/99.8 kB ? eta 0:00:00
INFO: pip is looking at multiple versions of sphinxcontrib-qthelp to determine which version is compatible with other requirements. This could take a while.
Collecting sphinxcontrib-qthelp (from sphinx==2.4.4)
  Downloading sphinxcontrib_qthelp-1.0.5-py3-none-any.whl (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.4/89.4 kB ? eta 0:00:00
  Downloading sphinxcontrib_qthelp-1.0.4-py3-none-any.whl (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.4/89.4 kB ? eta 0:00:00
  Downloading sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.6/90.6 kB ? eta 0:00:00
INFO: pip is looking at multiple versions of sphinxcontrib-serializinghtml to determine which version is compatible with other requirements. This could take a while.
Collecting sphinxcontrib-serializinghtml (from sphinx==2.4.4)
  Downloading sphinxcontrib_serializinghtml-1.1.8-py3-none-any.whl (92 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.6/92.6 kB 5.1 MB/s eta 0:00:00
  Downloading sphinxcontrib_serializinghtml-1.1.7-py3-none-any.whl (92 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.6/92.6 kB 1.3 MB/s eta 0:00:00
  Downloading sphinxcontrib_serializinghtml-1.1.6-py3-none-any.whl (92 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.6/92.6 kB ? eta 0:00:00
  Downloading sphinxcontrib_serializinghtml-1.1.5-py2.py3-none-any.whl (94 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.0/94.0 kB ? eta 0:00:00
Installing collected packages: sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, sphinx
  Attempting uninstall: sphinxcontrib-serializinghtml
    Found existing installation: sphinxcontrib-serializinghtml 1.1.9
    Uninstalling sphinxcontrib-serializinghtml-1.1.9:
      Successfully uninstalled sphinxcontrib-serializinghtml-1.1.9
  Attempting uninstall: sphinxcontrib-qthelp
    Found existing installation: sphinxcontrib-qthelp 1.0.6
    Uninstalling sphinxcontrib-qthelp-1.0.6:
      Successfully uninstalled sphinxcontrib-qthelp-1.0.6
  Attempting uninstall: sphinxcontrib-htmlhelp
    Found existing installation: sphinxcontrib-htmlhelp 2.0.4
    Uninstalling sphinxcontrib-htmlhelp-2.0.4:
      Successfully uninstalled sphinxcontrib-htmlhelp-2.0.4
  Attempting uninstall: sphinxcontrib-devhelp
    Found existing installation: sphinxcontrib-devhelp 1.0.5
    Uninstalling sphinxcontrib-devhelp-1.0.5:
      Successfully uninstalled sphinxcontrib-devhelp-1.0.5
  Attempting uninstall: sphinxcontrib-applehelp
    Found existing installation: sphinxcontrib-applehelp 1.0.7
    Uninstalling sphinxcontrib-applehelp-1.0.7:
      Successfully uninstalled sphinxcontrib-applehelp-1.0.7
  Attempting uninstall: sphinx
    Found existing installation: Sphinx 7.2.6
    Uninstalling Sphinx-7.2.6:
      Successfully uninstalled Sphinx-7.2.6
Successfully installed sphinx-2.4.4 sphinxcontrib-applehelp-1.0.4 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-2.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.5

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

C:\emsdk\emscripten\main\site>make html
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jukkaj\AppData\Roaming\Python\Python311\Scripts\sphinx-build.exe\__main__.py", line 4, in <module>
  File "C:\Users\jukkaj\AppData\Roaming\Python\Python311\site-packages\sphinx\cmd\build.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "C:\Users\jukkaj\AppData\Roaming\Python\Python311\site-packages\sphinx\application.py", line 42, in <module>
    from sphinx.highlighting import lexer_classes, lexers
  File "C:\Users\jukkaj\AppData\Roaming\Python\Python311\site-packages\sphinx\highlighting.py", line 30, in <module>
    from sphinx.ext import doctest
  File "C:\Users\jukkaj\AppData\Roaming\Python\Python311\site-packages\sphinx\ext\doctest.py", line 28, in <module>
    from sphinx.builders import Builder
  File "C:\Users\jukkaj\AppData\Roaming\Python\Python311\site-packages\sphinx\builders\__init__.py", line 24, in <module>
    from sphinx.io import read_doc
  File "C:\Users\jukkaj\AppData\Roaming\Python\Python311\site-packages\sphinx\io.py", line 42, in <module>
    from sphinx.util.rst import append_epilog, docinfo_re, prepend_prolog
  File "C:\Users\jukkaj\AppData\Roaming\Python\Python311\site-packages\sphinx\util\rst.py", line 22, in <module>
    from jinja2 import environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (C:\Users\jukkaj\AppData\Roaming\Python\Python311\site-packages\jinja2\__init__.py)

C:\emsdk\emscripten\main\site>
```

**Comment by juj** [comment]
That issue seems to be https://github.com/sphinx-doc/sphinx/issues/10291

Manually downgrading Jinja2 from 3.1.0 to `pip install -U --user jinja2==3.0.1` worked.

**Comment by juj** [comment]
Updated the instructions at https://github.com/emscripten-core/emscripten/pull/20391/files#diff-d7dbab731dfb4515315969a2b5e0dca76abab14f40e2c59da416e3bb22b5aa58R58-R67 to hint towards this being necessary.

**Comment by sbc100** [comment]
Do you know why you didn't see that error when running `make`?

**Comment by juj** [comment]
> Do you know why you didn't see that error when running `make`?

That seems to be because on Windows running `make html` invokes the make.bat, and not the make tool. That bat script unconditionally runs `sphinx-build` without doing any kind of testing.

Tried for a bit to do a check in the .bat script, but I think it's not worth spending time on it, because .bat is such a tool.

**Comment by sbc100** [comment]
> > Do you know why you didn't see that error when running `make`?
> 
> That seems to be because on Windows running `make html` invokes the make.bat, and not the make tool. That bat script unconditionally runs `sphinx-build` without doing any kind of testing.
> 
> Tried for a bit to do a check in the .bat script, but I think it's not worth spending time on it, because .bat is such a tool.

Oh.. I assumed make.bat eventually ran the Makefile itself.
