### ISSUE TITLE
library_webgpu.js shim doesn't seem to support closure pass

### ISSUE THREAD

**Issue by floooh** [emscripten-core/emscripten#20415]
emsdk version 3.1.46

Building and running webgpu samples with webgpu.h works fine without the closure pass, but when trying to enable closure with the linker option `--closure 1`, linking appears to work, but when running I get the following errors on the browser js console:

```
Uncaught (in promise) TypeError: Failed to execute 'configure' on 'GPUCanvasContext': Failed to read the 'format' property from 'GPUCanvasConfiguration': Required member is undefined.
    at Da (triangle-sapp.js:54:9)
    at triangle-sapp.wasm:0x1165
    at triangle-sapp.wasm:0x1b7b
    at triangle-sapp.js:42:369
    at mc (triangle-sapp.js:27:301)
    at triangle-sapp.js:42:252
onerror: Uncaught TypeError: Failed to execute 'configure' on 'GPUCanvasContext': Failed to read the 'format' property from 'GPUCanvasConfiguration': Required member is undefined.

triangle-sapp.js:54 Uncaught TypeError: Failed to execute 'configure' on 'GPUCanvasContext': Failed to read the 'format' property from 'GPUCanvasConfiguration': Required member is undefined.
    at Da (triangle-sapp.js:54:9)
    at triangle-sapp.wasm:0x1165
    at triangle-sapp.wasm:0x3269
    at Object.lb (triangle-sapp.js:18:70)
    at b (triangle-sapp.js:11:46)
```

The JS file location `triangle-sapp.js:54:9` looks like this:

<img width="390" alt="Screenshot 2023-10-08 at 18 36 28" src="https://github.com/emscripten-core/emscripten/assets/1699414/2c2116a0-5b1d-42f2-b235-07715ea470f0">

The only place in `library_webgpu.js` which has a configure call seems to be:

https://github.com/emscripten-core/emscripten/blob/1311f2220ef70554d0862de4ebf637b1dab10025/src/library_webgpu.js#L2607-L2614

I don't know what's needed to make such a JS shim closure-compatible, e.g. whether there are generally some sort of annotations missing, or only in this specific location. I could probably help with investigation and fixing if I would know where to start :)

Cheers!

(cc: @kainino0x)

**Comment by kripken** [comment]
Maybe add a little logging - is the value sent into `format` undefined somehow? If the read on the typed array is out of bounds, it would be, but it does seem odd for closure to cause that... if it is undefined, comparing to a non-closure build could help.

Otherwise, that code (both in the output and the source) seems ok.

The only other idea I'd have is if the error is actually on the internals of that object send into `device:`, `a` (if it's expected to have a format field but doesn't - logging out that object might help).

**Comment by floooh** [comment]
I'll try to investigate, thanks for the hints!

**Comment by kainino0x** [comment]
Most likely `{{{ gpu.makeGetU32('descriptor', C_STRUCTS.WGPUSwapChainDescriptor.format) }}}` -> `z[c + 12 >> 2]` is somehow producing a value that's either 0 or out of bounds of [`WebGPU.TextureFormat`](https://github.com/emscripten-core/emscripten/blob/b4786b63e11477419fd4386e62c923da3f4f2f5a/src/library_webgpu.js#L502-L598). This could be flaky if the C value was uninitialized, though I have no idea why this would be affected by Closure.

**Comment by floooh** [comment]
I think I found the culprit... not sure yet why it happens. But:

Closure-ized `wgpuSurfaceGetPreferredFormat` looks like this:

```js
    qa: ()=>{
        var a = navigator.gpu.getPreferredCanvasFormat();
        return ob[a]
    }
```
'var a' is `bgra8unorm` which is then used as key on the `ob` object (which should be a mapping from string names to numbers), but the `ob` property names have been minified:

<img width="214" alt="image" src="https://github.com/emscripten-core/emscripten/assets/1699414/3fcdf7ee-6de0-41e2-a0da-c05d926fdbe9">

...looking at that next...

**Comment by floooh** [comment]
Hmm, those string-to-number mapping objects all look the same, I assume those are all affected by the minification, but the `PreferredFormat` is just the first one that's encountered:

https://github.com/emscripten-core/emscripten/blob/1311f2220ef70554d0862de4ebf637b1dab10025/src/library_webgpu.js#L317-L330

I guess those need to be annotated somehow so that closure leaves the keys alone. I'll see if I can find any similar mapping objects elsewhere...

**Comment by kripken** [comment]
Interesting... I tested various combinations here:
```js

addToLibrary({
  $libA: {
    PreferredFormat: {
      'rgba8unorm': 0x12,
      'bgra8unorm': 0x17,
    },
  },
  $libB: {
    'rgba8unorm': 0x12,
    'bgra8unorm': 0x17,
  },
  $libC: function() {
    return {
      'rgba8unorm': 0x12,
      'bgra8unorm': 0x17,
    };
  }
});
```
Those show up in the output JS like this:
```js
var libA = {
 PreferredFormat: {
  rgba8unorm: 18,
  bgra8unorm: 23
 }
};

var libB = {
 rgba8unorm: 18,
 bgra8unorm: 23
};

function libC() {
 return {
  "rgba8unorm": 18,
  "bgra8unorm": 23
 };
}
```
So the first two are broken (missing `"`) while the last is ok. The last is by far the most common way we use quoted objects, that is, inside code and not on an object that is directly included itself, so I'd guess something in that direct inclusion path is going wrong. I'm investigating that now.

**Comment by floooh** [comment]
Hmm, one solution is to turn the mapping into a function:

```js
    mapPreferredFormat: (fmt) => {
      switch (fmt) {
        case 'rgba8unorm': return 0x12;
        case 'bgra8unorm': return 0x17;
      }
    },
```
...this allows it to get past the swapchain creation.

But then the next problem (and sometimes entirely different) is in the `wgpuDeviceGetLimits` shim:

https://github.com/emscripten-core/emscripten/blob/4b33521f103c2fb4fb218b1e1c8637a4a96b8e74/src/library_webgpu.js#L712-L727

...this gets minified to:

```js
ga: (a,b)=>{
        function c(g, h) {
            B[b + (8 + h) >> 2] = f.nb[g]
        }
        function d(g, h) {
            g = f.nb[g];
            Ga = [g >>> 0, (H = g,
            1 <= +Math.abs(H) ? 0 < H ? +Math.floor(H / 4294967296) >>> 0 : ~~+Math.ceil((H - +(~~H >>> 0)) / 4294967296) >>> 0 : 0)];
            B[b + (8 + h) >> 2] = Ga[0];
            B[b + (8 + h + 4) >> 2] = Ga[1]
        }
        var f = S.Wa[a].object;
        c("maxTextureDimension1D", 0);
        c("maxTextureDimension2D", 4);
        c("maxTextureDimension3D", 8);
```

Note how the original code:

```js
    function setLimitValueU32(name, limitOffset) {
      var limitValue = device.limits[name];
      {{{ makeSetValue('limitsOutPtr', 'limitsPtr + limitOffset', 'limitValue', 'i32') }}};
    }
```
...minified to:

```js
        function c(g, h) {
            B[b + (8 + h) >> 2] = f.nb[g]
        }
```

...meaning `.limits` is now `.nb`!

This might turn out to become a real rabbit hole...

**Comment by kripken** [comment]
Unfortunately the issue is due to how JS parsing and toString works:
```js
> x = (function a() { return { 'b': 5 } })
[Function: a]
> x.toString()
"function a() { return { 'b': 5 } }"
> y = { 'b': 5 }
{ b: 5 }
> y.toString()
'[object Object]'
```
That is, JS engines keep a copy of the source JS for function, and `toString()` retrieves that including any quotation marks. But JS engines do not do that for objects, where the quotes are simply lost.

A hard way to fix this would be to not use the JS engine native parsing and instead use Acorn, whose AST does note quoted properties. But that would mean integration Acorn in an entirely new part of Emscripten, and could make compilation slower.

Another option might be to always quote object properties. But that would be excessive and increase code size.

Other than that, we could work around this in `library_webgpu` using a function as @floooh said. That would also increase code size a little, but just here. That might be the best option if no one else has a better idea.

**Comment by floooh** [comment]
That last format seems to work if the shim is changed like this:

```js
    PreferredFormat: () => {
      return {
        'rgba8unorm': 0x12,
        'bgra8unorm': 0x17,
      };
    },
    // ...
    wgpuSurfaceGetPreferredFormat: (surfaceId, adapterId) => {
      var format = navigator["gpu"]["getPreferredCanvasFormat"]();
      return WebGPU.PreferredFormat()[format];
    },
```

...interestingly Closure seems to turn that function into:

```js
    qa: ()=>({
        rgba8unorm: 18,
        bgra8unorm: 23
    })[navigator.gpu.getPreferredCanvasFormat()],
```
...pretty crazy...

**Comment by kripken** [comment]
> ...meaning `.limits` is now `.nb`!

If `.limits` arrives from the WebAPI API, then `device.limits` should be `device['limits']` in `library_webgpu.js`.

**Comment by floooh** [comment]
Right. I guess somebody "just" needs to go through library_webgpu.js and fix all the little things.

On my side, one problem is that I don't have an exhaustive test code base which calls all functions (and thus would catch all problems), e.g. I could only fix the stuff that's called in my code base, and I'm only using a subset of the WebGPU feature set.

But I can try to get my code working and provide a list of required changes (even if incomplete), or some sort of proposal PR.

**Comment by floooh** [comment]
Regarding inefficiency when using a function for the string-to-number mapping, I think closure takes care of this, e.g. by turning this:

```js
  wgpuSurfaceGetPreferredFormat: (surfaceId, adapterId) => {
    var format = navigator["gpu"]["getPreferredCanvasFormat"]();
    return WebGPU.PreferredFormat()[format];
  }
```
...into this:

```js
    qa: ()=>({
        rgba8unorm: 18,
        bgra8unorm: 23
    })[navigator.gpu.getPreferredCanvasFormat()],
```

...that extra mapping function call is removed!

**Comment by floooh** [comment]
Looks like at least for my code, the changes are just in two categories (e.g. I currently have a state that works for me with closure minification):

All the string-to-number mappings need to be changed like this:

```js
    PreferredFormat: () => ({
      'rgba8unorm': 0x12,
      'bgra8unorm': 0x17,
    }),
```

...and called like this (note that this is a function call now):

```js
    WebGPU.PreferredFormat()[format];
```

And then there's a handful of places where WebGPU object properties are directly accessed, like:

```js
    device.limits[name];
```

...needs to be changed into:

```js
    device['limits'][name];
```

Cases I found:

- device.features
- device.limits
- device.label

...but it's not just device, but also:

- querySet.type
- querySet.label
- queue.label

...and probably more.

**Comment by sbc100** [comment]
> And then there's a handful of places where WebGPU object properties are directly accessed, like:
> 
> ```js
>     device.limits[name];
> ```
> 
> ...needs to be changed into:
> 
> ```js
>     device['limits'][name];
> ```

In these cases (where possible) it would be better to rely on closure extern files.  The Web APIs and the objects they return as supposed to be known to closure so it should not minify them.  In this case maybe the extern type definitions are just not up-to-date with the WebGPU Web API.

**Comment by sbc100** [comment]
In some cases we work around the "object evaluation + serialization removes quotes" issue by using `__postset`.  See `ERRNO_CODES` : https://github.com/emscripten-core/emscripten/blob/4b33521f103c2fb4fb218b1e1c8637a4a96b8e74/src/library.js#L1255

**Comment by kainino0x** [comment]
> All the string-to-number mappings need to be changed like this:

The Closure builds definitely used to work with the current pattern for string-to-number mappings. Is this a new problem with Closure?

**Comment by floooh** [comment]
I just remember that there was an Emscripten SDK version which suddenly spammed a lot of Closure warnings, that's why I had to add awkward hints like this into my EM_JS() embeddings:

https://github.com/floooh/sokol/blob/d98c8b92c25070f13d0491f5fade1d9d2ca885ad/sokol_app.h#L4847

From looking at git blame, this must have been around October 2022.

**Comment by sbc100** [comment]
Yes, I think the increase in closure warnings was just due to a change to not hide them by default.

The issue with object literals as library elements is not new.. its always been an issue AFAIK.

**Comment by kainino0x** [comment]
> PS: Also the problem is actually quite esoteric I think, it only affects WebGPU functions which return enum values, and I think apart from getting the preferred framebuffer pixel format (which I also just added quite recently to my code), those calls are quite rare. And linking works perfectly fine, the problem only manifests at runtime when such a function is actually called.

Good point, you're right. I think that would explain it. It's pretty likely no one has really noticed those were broken all along in Closure builds.

**Comment by kainino0x** [comment]
@floooh reports we still have issues here:

```
Failed to execute 'configure' on 'GPUCanvasContext': Failed to read the 'format' property from 'GPUCanvasConfiguration': Required member is undefined.
```

Not sure why I haven't seen this; I certainly have tried calling configure().

**Comment by kainino0x** [comment]
cc @shrekshao @lokokung

**Comment by floooh** [comment]
This is with emsdk 3.1.63 btw, I'll try to find out more later today.

**Comment by floooh** [comment]
The minified JS code of the function where that error happens looks like this:

```js
    na: (a,b,c)=>{
        a = Q.get(a);
        b = ic.get(b);
        var d = [A[c + 16 >> 2], A[c + 20 >> 2]];
        0 !== d[0] && (b.canvas.width = d[0]);
        0 !== d[1] && (b.canvas.height = d[1]);
        b.configure({
            device: a,
            format: fc[A[c + 12 >> 2]],
            usage: A[c + 8 >> 2],
            alphaMode: "opaque"
        });
        return jc.create(b)
    }
```

...and this seems to be the code without minification (which works fine). So it seems to be the `context` object where the `configure` method has been minified (Closure re-assigning variables is really a bit confusing):

```js
var _wgpuDeviceCreateSwapChain = (deviceId,surfaceId,descriptor)=>{
    var device = WebGPU.mgrDevice.get(deviceId);
    var context = WebGPU.mgrSurface.get(surfaceId);
    var canvasSize = [HEAPU32[descriptor + 16 >> 2], HEAPU32[descriptor + 20 >> 2]];
    if (canvasSize[0] !== 0) {
        context["canvas"]["width"] = canvasSize[0]
    }
    if (canvasSize[1] !== 0) {
        context["canvas"]["height"] = canvasSize[1]
    }
    var configuration = {
        device: device,
        format: WebGPU.TextureFormat[HEAPU32[descriptor + 12 >> 2]],
        usage: HEAPU32[descriptor + 8 >> 2],
        alphaMode: "opaque"
    };
    context.configure(configuration);
    return WebGPU.mgrSwapChain.create(context)
}
```

**Comment by floooh** [comment]
...ok when looking at the error message again:

```
TypeError: Failed to execute 'configure' on 'GPUCanvasContext': Failed to read the 'format' property from 'GPUCanvasConfiguration': Required member is undefined.
```

...it's the same error I wrote the ticket original for...

...when looking at the minified and original code, the only way this can happen is if this minified array index expression: `fc[A[c + 12 >> 2]],` results in `undefined`... and this must an effect of the original expression `WebGPU.TextureFormat[HEAPU32[descriptor + 12 >> 2]],` being minified...

**Comment by floooh** [comment]
...looking through the minified js shim I find that `fc` array, so that one seems to look correct...

```js
fc = [, "r8unorm", "r8snorm", "r8uint",  ..... // lot's more pixel format following here
```

**Comment by floooh** [comment]
Ok we're getting somewhere :)

<img width="541" alt="Screenshot 2024-07-31 at 17 32 04" src="https://github.com/user-attachments/assets/5109895a-94f0-4a73-8d31-b8693eb2e5dc">

When hovering the whole minified expression `fc[A[c + 12 >> 2]]`, the result is indeed undefined.

The inner HEAPU32 lookup `A[c + 12 >> 2]` results in `0`. But looking at the array `fc[]` there is no element at index 0 which explains the undefined result of the whole expression:

<img width="422" alt="image" src="https://github.com/user-attachments/assets/77e7e977-09fa-4a67-85ef-65b75009d294">

**Comment by floooh** [comment]
...looking at the same code in the non-minified code now...

**Comment by floooh** [comment]
In the unminified code, the result of the HEAPU32 lookup `HEAPU32[descriptor + 12 >> 2]` is 23, and not 0 like in the minified version.

But I just realized why I had such a strong deja-vu all the time. I had that all figured out already 😂

https://github.com/emscripten-core/emscripten/issues/20415#issuecomment-1757132707

**Comment by floooh** [comment]
...e.g. the problem are these mapping arrays:

https://github.com/emscripten-core/emscripten/blob/87ef02c43974ef645e9fe0232fab6a6baf086071/src/library_webgpu.js#L398-L417

...if you follow the discussion starting at https://github.com/emscripten-core/emscripten/issues/20415#issuecomment-1757132707 there are various potential solutions (for instance wrapping those mappings into functions).

**Comment by kainino0x** [comment]
If there are any remaining issues in Emscripten's current WebGPU implementation, they won't be fixed, but `emdawnwebgpu` (see #23432) has been more thoroughly tested with Closure and should be working.

**Comment by floooh** [comment]
Oki doki, is it still planned to eventually upstream emdawnwebgpu into Emscripten?

**Comment by sbc100** [comment]
No, I believe the plan is to remove webgpu from emscripten and have the port live externally.

**Comment by floooh** [comment]
Hmm, that will make integration harder, especially if this is still true (from https://source.chromium.org/chromium/chromium/src/+/main:third_party/dawn/src/emdawnwebgpu/README.md):

<img width="404" alt="Image" src="https://github.com/user-attachments/assets/33c62e2f-6f97-4cc2-8288-71db4cba51a8" />

There's this ticket though about unbundling from the Dawn repo (which is a 500 MBytes clone even without dependencies).

Personally I would very much prefer that WebGPU is handled the same as WebGL in the Emscripten SDK (e.g. webgpu.h plus libwebgpu.js shim).

**Comment by sbc100** [comment]
We are hoping to keep it very simple.  I believe @kainino0x is making releases that you can point to and you certainly won't need to be clone the whole repo.

In general I'm hoping to we can take some of the pressure off the emscripten repo by hosting more stuff like this externally.

**Comment by floooh** [comment]
Sounds like Emscripten needs a package manager ;)

**Comment by sbc100** [comment]
An yes, under the hood I believe its basically the same webgpu.h + libwebgpu.js but maintained upstream and packaged as an emscripten port.

**Comment by kainino0x** [comment]
The plan is to maintain it fully outside Emscripten. We may add a builtin port to Emscripten once it's a bit more stable. But for now it'll be super easy as soon as I get the packaging/publishing up and running. I already have preview packages you can use, see here:

https://github.com/emscripten-core/emscripten/issues/23432#issuecomment-2798404903

**Comment by floooh** [comment]
Confirmed working with emdawnwebgpu, thanks @kainino0x!

**Comment by floooh** [comment]
Ooooh.... correction, the problem is now back. I'm investigating and will write a ticket over at emdawnwebgpu.

**Comment by floooh** [comment]
For reference, followup ticket: https://issues.chromium.org/issues/424836759

(the problem is missing items in the `webgpu-externs.js` file)
