### ISSUE TITLE
C++20 coroutines + Native webassembly promise integration

### ISSUE THREAD

**Issue by unit-404** [emscripten-core/emscripten#20413]
From side of C++20 we have coroutines, from side of WebAssembly (at least in Chrome) we have native promise integration. Why be not to unify such features, and not to make an new and better async await API? Probably, make some sort of wrap or emulation? Or coroutine header with low-level code implementation?

**Comment by tlively** [comment]
Yes, this is something I'd like to do. See [emscripten/promise.h](https://github.com/emscripten-core/emscripten/blob/main/system/include/emscripten/promise.h) for the C API we have for interfacing with JS promises, including via JSPI. The next steps would be to create a C++11 wrapper API to take care of the resource management, then a C++20 coroutine API on top of that.

Is this something you would be interested in working on? I'd be happy to review patches if so.

**Comment by RReverser** [comment]
Ha, I actually literally implemented this last week for Embind and was going to send a PR next week.

**Comment by RReverser** [comment]
> See [emscripten/promise.h](https://github.com/emscripten-core/emscripten/blob/main/system/include/emscripten/promise.h?rgh-link-date=2023-10-08T06%3A03%3A28Z) for the C API we have for interfacing with JS promises, including via JSPI.

Btw I saw that experimental API too, but it's pretty low-level and it's kinda a shame that it uses its own list of promises and handles as that makes it harder to integrate with Embind's `emscripten::val`.

I decided to go with the latter as it's more useful for complex JS interactions.

**Comment by unit-404** [comment]
It seems, I have some idea about coroutines with C emscripten JSPI. 

```cpp
#include <coroutine>
#include <iostream>
#include <optional>
#include <future>
#include <emscripten/promise.h>
#include <emscripten.h>

//
std::string what(const std::exception_ptr &eptr = std::current_exception())
{
    if (!eptr) { throw std::bad_exception(); }

    try { std::rethrow_exception(eptr); }
    catch (const std::exception &e) { return e.what()   ; }
    catch (const std::string    &e) { return e          ; }
    catch (const char           *e) { return e          ; }
    catch (...)                     { return "who knows"; }
}

//
template <typename T>
struct async {
	struct promise_type;
	using coro_t = std::coroutine_handle<promise_type>;

	//
	struct awaiter {
		struct promise_type* p;
		bool await_ready() const noexcept { return false; }
		T await_resume() const noexcept { return p->data.value(); }

		//
		static void unhandled_exception() noexcept { 
			std::cerr << what() << std::endl;
		}

		// 
		std::coroutine_handle<> await_suspend(std::coroutine_handle<promise_type> h) {
			auto precursor = h.promise().precursor;
			if (precursor) { return precursor; }
			return std::noop_coroutine();
		}
	};

	// The return type of a coroutine must contain a nested struct or type alias called `promise_type`
	struct promise_type {
		std::coroutine_handle<> precursor;
		em_promise_t em_promise = nullptr;
		std::optional<T> data = {};

		// Invoked when we first enter a coroutine. We initialize the precursor handle
		// with a resume point from where the async is ultimately suspended
		async get_return_object() noexcept {
			return async(coro_t::from_promise(*this), em_promise);
		}

		// When the caller enters the coroutine, we have the option to suspend immediately.
		// Let's choose not to do that here
		static auto initial_suspend() noexcept { return std::suspend_never{}; }
		static void unhandled_exception() noexcept { 
			std::cerr << what() << std::endl;
		}
		auto final_suspend() noexcept { return awaiter{this}; }

		// When the coroutine co_returns a value, this method is used to publish the result
		awaiter return_value(T const& value) noexcept {
			if (em_promise) {
				emscripten_promise_resolve(em_promise, EM_PROMISE_FULFILL, &((data = value).value()));
			} else {
				//std::cerr << "JS promise is not exist..." << std::endl;
				data = value;
			}
			return awaiter{this};
		};
	};

	//
	auto& make_promise(em_promise_t $em_promise) {
		auto& p = handle->promise();
		if (!$em_promise) return p;
		p.em_promise = $em_promise;
		return p;
	}

	//
	async(async && t) : handle(t.handle) {}

	//
	async(em_promise_t promise = nullptr) {
		handle = std::make_shared<coro_t>(coro_t{});
		this->make_promise(promise);
	}
	async(coro_t&& h, em_promise_t promise = nullptr) : handle(std::make_shared<coro_t>(std::move(h))) { this->make_promise(promise); }

	//
	//~async() { handle.destroy(); };
	async(const async &) = delete;
	async& operator =(async &&t) { handle = t.handle; return *this; }
	async& operator =(coro_t&& h) = delete;

	//
	bool done() const noexcept { return this->handle->done(); };
	auto resume() noexcept { return this->handle->resume(); };

	//
	void await_suspend(std::coroutine_handle<> coroutine) const noexcept {
		auto& $p = this->handle->promise();
		$p.em_promise = emscripten_promise_then($p.em_promise, 
			[](void**result, void*data, void*value) {
				auto $p = reinterpret_cast<promise_type*>(data);
				*result = value;
				$p->data = *reinterpret_cast<T*>(value);
				$p->precursor.resume();
				return EM_PROMISE_FULFILL;
			}, 
			[](void**result, void*data, void*value){
				return EM_PROMISE_REJECT;
			},
			&$p
		);
		if (!$p.em_promise) { $p.precursor.resume(); };
		$p.precursor = coroutine;
	}

	//
	bool await_ready() const noexcept { return handle->done(); }
	T await_resume() const noexcept { return handle->promise().data.value(); }

	//
	std::shared_ptr<coro_t> handle = {};
	//std::shared_ptr<em_promise_x> em_promise = {};
};

std::shared_ptr<async<long>> $prom;

//
extern "C" {
    // 
	EMSCRIPTEN_KEEPALIVE
    void testPromise(em_promise_t promise) {
        $prom = std::make_shared<async<long>>([](em_promise_t promise) -> async<long> {
			std::cout << co_await async<long>(promise) << std::endl;
			std::cout << "Async Execution" << std::endl;
			co_return 5;
		}(promise));
    }

	// 
	em_promise_t tryPromise() {
		em_promise_t promise = emscripten_promise_create();
		return promise;
	}

	// 
	bool resolvePromise(em_promise_t promise, long T) {
		emscripten_promise_resolve(promise, EM_PROMISE_FULFILL, new long{T});
		//$prom->resume();
		//$prom->destroy();

		return true;
	}
}
```

```js
import Module from "./jspi.js"

//
const $mod = await Module();
const $promise = $mod._tryPromise();

//
$mod._testPromise($promise);
$mod._resolvePromise($promise, 256n);
```

**Comment by RReverser** [comment]
Note that JSPI is orthogonal / unnecessary for coroutines.

JSPI, like Asyncify, is useful for pausing the entire program, whereas in case of coroutines all the transformation magic happens at compile time and it only pauses the local coroutine itself, so Wasm engine doesn't [need to] know about promises and pausing.

**Comment by unit-404** [comment]
Sometime I would possibility to pass promise itself from JS (called function, or argument) into wasm program (for example, inside of coroutines). And return promise from wasm too. I even added `get_promise` and JS promise creation when not exists.

**Comment by RReverser** [comment]
> Ha, I actually literally implemented this last week for Embind and was going to send a PR next week. Just randomly saw this issue.

Yeah that's why I implemented mine via Embind instead - it supports passing promises from and to JS. I'll try to submit a PR soon.

**Comment by unit-404** [comment]
> The next steps would be to create a C++11 wrapper API to take care of the resource management, then a C++20 coroutine API on top of that.

I made test wrapper for promise.

**Comment by RReverser** [comment]
See https://github.com/emscripten-core/emscripten/pull/20420.

**Comment by unit-404** [comment]
I've already noticed, and I've updated my examples for C++11 (or something like that) in parallel, or rather the wrappers on `em_promise_t`.

**Comment by RReverser** [comment]
Ah right, I guess those are two slightly different issues - adding coroutine support for `em_promise_t` and for JavaScript values in Embind.

**Comment by unit-404** [comment]
Prototype by JSPI implementation... working in current version of Emscripten. 

Limitations: 

- Support only pointers, not numbers or other
- Needs function passing into wasm (TODO)

```cpp
#pragma once

//
#include <iostream>
#include <optional>
#include <functional>

#include <emscripten.h>
#include <emscripten/promise.h>
#include <emscripten/val.h>

//
extern "C" {
    // 
    em_promise_t promise_create() { return emscripten_promise_create();; }

    //
    struct void_t{};
    using vr_t = void_t const*;
    using fx_t = vr_t(vr_t);

    //
    bool promise_resolve(em_promise_t em, vr_t v) {
        emscripten_promise_resolve(em, EM_PROMISE_FULFILL, (void*)v);
        return true;
    }

    // NOT WORKING CURRENTLY!
    em_promise_t promise_then(em_promise_t em, fx_t* fulfill = nullptr, fx_t* rejected = nullptr) {
        using pr_t = std::pair<fx_t*, fx_t*>;
        pr_t ffx = {fulfill, rejected};
        return emscripten_promise_then(em, 
            [](void**result, void*data, void*value) {
                const auto ffx = reinterpret_cast<pr_t*>(data);
                if (ffx && ffx->first) {
                    *result = (void*)ffx->first(reinterpret_cast<vr_t>(value));
                }
                return EM_PROMISE_FULFILL;
            }, 
            [](void**result, void*data, void*value) {
                const auto ffx = reinterpret_cast<pr_t*>(data);
                if (ffx && ffx->second) {
                    *result = (void*)ffx->second(reinterpret_cast<vr_t>(value));
                }
                return EM_PROMISE_REJECT;
            }, 
            &ffx
        );
    }
}
```

```js
// NOT WORKING CURRENTLY!
const _ToPromise = (_mod, _ptr)=>{
    return new Promise((resolve, reject)=>{
        _mod._promise_then(_ptr, 
            BigInt(_mod.addFunction(resolve, "p")), 
            BigInt(_mod.addFunction(reject, "p"))
        );
    });
}

//
const _ToPtr = (_mod, _prom)=>{
    const _ptr = _mod._promise_create();
    const _res = (a) => (_mod._promise_resolve(_ptr, a));
    const _rej = (e) =>{ /*_mod._promise_reject(_ptr, e);*/ throw e; };
    _prom.then(_res).catch(_rej);
    return _ptr;
}

//
const EMX = {
    ToPromise: _ToPromise,
    ToPtr: _ToPtr
};

//
export default EMX;
```

**Comment by unit-404** [comment]
Sometime I thinking about extension or plugin API. For Embind, for JSPI API, etc.

**Comment by RReverser** [comment]
> for JSPI API

FWIW I know I mentioned it before, but if you're referring to `em_promise_*`, it's not JSPI API. It's just a JavaScript / C library, just like Embind. https://github.com/emscripten-core/emscripten/blob/main/src/library_promise.js

Both of those libraries _can_ use JSPI to await promises when compiled with `-s ASYNCIFY=2`, but otherwise the only difference between them is the provided API and value representation.

That is, I don't want to discourage you, just wanted to clarify because it sounds like you might think it's a low-level API for JSPI. They are both high-level libraries implemented in JavaScript and exposing C/C++ bindings - one works on JS promises created from C/C++ and another works on JS values (including promises) received from JS.

**Comment by unit-404** [comment]
On the subject of levelness, you can speculate a bit. Namely, to give the simdpp library as an example. It supports SSE, AVX, NEON. WebAssembly has its own SIMD API, which in turn emulates SSE, AVX, NEON, but this representation itself is compiled at runtime into the same SSE, AVX, NEON. So if we use some conditional simdpp we have sometimes unnecessary conversions back and forth if we include almost all stages. 
I apologize for my arrogance, it just reminded me of this particular individual case.

**Comment by unit-404** [comment]
Meanwhile... I getting such error when trying use promise C API with `-sASYNCIFY=2`, with any other is working. 

```
C:\BlazerNEO\EMX\test\js>call node --wasm-stack-switching-stack-size=1000 --experimental-wasm-modules --experimental-wasm-memory64 --experimental-modules --experimental-wasi-unstable-preview1 test.mjs --input-type=module
Aborted(Assertion failed: Missing __sig for invoke_djjj)
file:///C:/BlazerNEO/EMX/test/cxx/test.js:154
      throw ex;
      ^

RuntimeError: Aborted(Assertion failed: Missing __sig for invoke_djjj)
    at abort (file:///C:/BlazerNEO/EMX/test/cxx/test.js:684:11)
    at assert (file:///C:/BlazerNEO/EMX/test/cxx/test.js:396:5)
    at file:///C:/BlazerNEO/EMX/test/cxx/test.js:5078:17
    at Object.instrumentWasmImports (file:///C:/BlazerNEO/EMX/test/cxx/test.js:5090:13)
    at file:///C:/BlazerNEO/EMX/test/cxx/test.js:5621:10
    at async file:///C:/BlazerNEO/EMX/test/js/test.mjs:5:15

Node.js v20.7.0
```
