### ISSUE TITLE
-### doesn't work like it does in Clang

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#20468]
`-###` is useful command for debugging Clang invocations:

```shell
> echo 'int main(){}' | clang -### -xc -
Ubuntu clang version 17.0.0 (++20230911073117+0176e8729ea4-1~exp1~20230911073215.40)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-17/bin
 "/usr/lib/llvm-17/bin/clang" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-emit-obj" "-mrelax-all" "-dumpdir" "a-" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "-" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=all" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-debugger-tuning=gdb" "-fcoverage-compilation-dir=/home/rreverser/web-gphoto2" "-resource-dir" "/usr/lib/llvm-17/lib/clang/17" "-internal-isystem" "/usr/lib/llvm-17/lib/clang/17/include" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/usr/lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include" "-internal-externc-isystem" "/usr/include/x86_64-linux-gnu" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-fdebug-compilation-dir=/home/rreverser/web-gphoto2" "-ferror-limit" "19" "-fgnuc-version=4.2.1" "-fcolor-diagnostics" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-o" "/tmp/--d8a854.o" "-x" "c" "-"
 "/usr/bin/ld" "-pie" "-z" "relro" "--hash-style=gnu" "--build-id" "--eh-frame-hdr" "-m" "elf_x86_64" "-dynamic-linker" "/lib64/ld-linux-x86-64.so.2" "-o" "a.out" "/lib/x86_64-linux-gnu/Scrt1.o" "/lib/x86_64-linux-gnu/crti.o" "/usr/lib/gcc/x86_64-linux-gnu/12/crtbeginS.o" "-L/usr/lib/gcc/x86_64-linux-gnu/12" "-L/usr/lib/gcc/x86_64-linux-gnu/12/../../../../lib64" "-L/lib/x86_64-linux-gnu" "-L/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu" "-L/usr/lib/../lib64" "-L/lib" "-L/usr/lib" "/tmp/--d8a854.o" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "-lc" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "/usr/lib/gcc/x86_64-linux-gnu/12/crtendS.o" "/lib/x86_64-linux-gnu/crtn.o"
```

However, Emscripten can't quite handle it as it probably treats it as another filename, so it throws an error after printing the information:

```shell
> echo 'int main(){}' | emcc -### -xc -
clang version 18.0.0 (https://github.com/llvm/llvm-project f6f944e77f741861e641e1dd46c30dcbaf8c83b7)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/rreverser/emsdk/upstream/bin
 (in-process)
 "/home/rreverser/emsdk/upstream/bin/clang-18" "-cc1" "-triple" "wasm32-unknown-emscripten" "-emit-obj" "-mrelax-all" "-disable-free" "-clear-ast-before-backend" "-main-file-name" "-" "-mrelocation-model" "static" "-mframe-pointer=none" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-target-cpu" "generic" "-debugger-tuning=gdb" "-fdebug-compilation-dir=/home/rreverser/web-gphoto2" "-fcoverage-compilation-dir=/home/rreverser/web-gphoto2" "-resource-dir" "/home/rreverser/emsdk/upstream/lib/clang/18" "-D" "EMSCRIPTEN" "-isysroot" "/home/rreverser/emsdk/upstream/emscripten/cache/sysroot" "-internal-isystem" "/home/rreverser/emsdk/upstream/lib/clang/18/include" "-internal-isystem" "/home/rreverser/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten" "-internal-isystem" "/home/rreverser/emsdk/upstream/emscripten/cache/sysroot/include" "-ferror-limit" "19" "-fvisibility=default" "-fgnuc-version=4.2.1" "-fignore-exceptions" "-fcolor-diagnostics" "-iwithsysroot/include/fakesdl" "-iwithsysroot/include/compat" "-mllvm" "-combiner-global-alias-analysis=false" "-mllvm" "-enable-emscripten-sjlj" "-mllvm" "-disable-lsr" "-o" "/tmp/emscripten_temp__x4kzc63/-_0.o" "-x" "c" "-"
Traceback (most recent call last):
  File "/home/rreverser/emsdk/upstream/emscripten/emcc.py", line 4506, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/rreverser/emsdk/upstream/emscripten/emcc.py", line 4499, in main
    ret = run(args)
          ^^^^^^^^^
  File "/home/rreverser/emsdk/upstream/emscripten/emcc.py", line 1298, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/rreverser/emsdk/upstream/emscripten/emcc.py", line 3146, in phase_compile_inputs
    compile_source_file(i, input_file)
  File "/home/rreverser/emsdk/upstream/emscripten/emcc.py", line 3132, in compile_source_file
    assert os.path.exists(output_file)
AssertionError
```

**Comment by sbc100** [comment]
I've only ever seen `-###` used in the clang test suite.  Is it used elsewhere?  I've always used `-v` to see that sub-commands run by the compiler and I know that one works.

**Comment by RReverser** [comment]
I found it in couple of SO answers, so assumed it was somewhat popular. I'm not actually sure what the difference is with `-v`.
