### ISSUE TITLE
wgpuCommandEncoderBeginRenderPass failing because WebGPU.mgrTextureView.objects is empty

### ISSUE THREAD

**Issue by Ravbug** [emscripten-core/emscripten#20476]
When I call `wgpuCommandEncoderBeginRenderPass`, emscripten's `makeColorAttachment` function fails when accessing `WebGPU.mgrTextureView.objects` because it is empty and so cannot provide a value for ID `1`. 
![image](https://github.com/emscripten-core/emscripten/assets/22283943/627f40bf-b1d9-4c70-b221-356a46169df7)

![image](https://github.com/emscripten-core/emscripten/assets/22283943/c7719004-b2da-4775-942c-01352872da5c)

![image](https://github.com/emscripten-core/emscripten/assets/22283943/f4efd992-ecba-4e9f-880e-cbd4228485dd)

Call stack:
![image](https://github.com/emscripten-core/emscripten/assets/22283943/50031d23-1e1a-4f4d-bf80-74bcc11632bd)

I have one color attachment, whose `WGPUTextureView` has value `1`, created by calling `wgpuSwapChainGetCurrentTextureView(swapchain)`

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.48-git (5b63268c904dd0e542f9c45e2b136c3d4a0bd638)
clang version 18.0.0 (https://github.com/llvm/llvm-project 25da11541c0740950e812a85d332a6d5cf4a5f87)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: C:\Users\Admin\Documents\emsdk\upstream\bin
```

**Comment by kainino0x** [comment]
Please show your C or C++ code if possible; it sounds like the WGPUTextureView object is getting freed before the call to wgpuCommandEncoderBeginRenderPass.

**Comment by Ravbug** [comment]
I put a logging statement before my only call to `wgpuTextureViewRelease` and it's not appearing in the browser log (my debugger is not working atm, not sure why), so as far as I can tell I'm not intentionally freeing the texture view. 

My code is a little difficult to post because I'm making a WebGPU backend for an existing graphics library, but it looks something like this:
```cpp
// setup
 // we are expecting a CSS selector string, like "#canvas", for the value of pointer
        WGPUSurfaceDescriptorFromCanvasHTMLSelector canvasDesc{
            .chain = {
                .next = nullptr,
                .sType = WGPUSType_SurfaceDescriptorFromCanvasHTMLSelector 
            },
            .selector = static_cast<const char* const>(pointer)
        };
        WGPUSurfaceDescriptor desc{
            .nextInChain = &canvasDesc.chain,
            .label = "Surface"
        };
 auto surface = wgpuInstanceCreateSurface(instance, &desc);

 WGPUSwapChainDescriptor swapChainDesc{
            .nextInChain = nullptr,
            .width = width,
            .height = height,
            .format = wgpuSurfaceGetPreferredFormat(surface, adapter),
            .usage = WGPUTextureUsage_RenderAttachment,
            .presentMode = vsync ? WGPUPresentMode_Fifo : WGPUPresentMode_Immediate,
        };
auto swapchain = wgpuDeviceCreateSwapChain(owningDevice->device, surface->surface, &swapChainDesc);

// each frame...

auto next = wgpuSwapChainGetCurrentTextureView(swapchain);

// store `next` inside a WGPURenderPassDescriptor as a color attachment

// crashing here
currentRenderPassEncoder = wgpuCommandEncoderBeginRenderPass(currentCommandEncoder,&casted->renderPass)
```
Would it be possible for me to get a breakpoint / callstack when a textureview is freed? That would help me pinpoint where the issue is coming from

**Comment by Ravbug** [comment]
I tried adding a breakpoint + `console.trace()` inside of the emscripten-generated `_wgpuTextureViewRelease` but it didn't trigger
```js
  function _wgpuTextureViewRelease(id) {
    console.trace();
  if (ENVIRONMENT_IS_PTHREAD)
    return proxyToMainThread(96, 1, id);
  return WebGPU.mgrTextureView.release(id)
  }
  
```

**Comment by Ravbug** [comment]
I updated to latest ToT (as of a few hours ago) and the issue still occurs.

**Comment by fridenmf** [comment]
Has there been any progress here?

I'm getting the same problem when trying out the emdawnwebgpu_pkg release from @kainino0x:
https://github.com/kainino0x/dawn/releases/tag/v2025.04.12-03.06.48

I've added logging and breakpoints to the only place in the code where texture views or textures are released and it's never getting there. I've also tried removing all release calls and the behavior is still the same.

The runtime error occurs in both:
* Google Chrome Canary (Version 136.0.7103.0 (Official Build) canary (64-bit))
* Mozilla Firefox Nightly (138.0a1 (2025-03-27) (64-bit))

But the same code runs well in Windows using Dawn (revision d0fd02cd4070808533d3e0a13f664bddfcfdb1fa).

The behavior is the same in emsdk:
* 4.0.3
* 4.0.6

I'm porting a larger application so it's not easy to send a smaller reproducable, but the runtime errors happens when calling wgpuCommandEncoderBeginRenderPass with:
* WGPURenderPassDescriptor.colorAttachments[0].view = BGRA8Unorm texture view for a BGRA8Unorm texture with sampleCount 4
* WGPURenderPassDescriptor.colorAttachments[0].resolveTarget = BGRA8Unorm texture view for a BGRA8Unorm texture with sample count 1
* WGPURenderPassDescriptor.depthStencilAttachment.view = Depth24PlusStencil8 texture view for a Depth24PlusStencil8 texture with sample count 4

<details>

<summary>Runtime log output and call stack</summary>

```
[my_app] Created WGPUTexture 342736 with format BGRA8Unorm, sampleCount 4
[my_app] Created WGPUTextureView 342760 for texture 342736
[my_app] Created WGPUTexture 342816 with format BGRA8Unorm, sampleCount 1
[my_app] Created WGPUTextureView 342840 for texture 342816
[my_app] Created WGPUTexture 342896 with format Depth24PlusStencil8, sampleCount 4
[my_app] Created WGPUTextureView 342920 for texture 342896
[my_app] WGPUSurfaceGetCurrentTextureStatus: SuccessOptimal
[my_app] Got WGPUTexture 343304 from wgpuSurfaceGetCurrentTexture with format BGRA8Unorm
[my_app] Created WGPUTextureView 343328 for texture 343304 with format BGRA8Unorm
[my_app] Created WGPUTexture 344376 with format RGBA8Unorm, sampleCount 1
[my_app] Created WGPUTextureView 344400 for texture 344376
[my_app] Created WGPUTexture 344456 with format RGBA8Unorm, sampleCount 1
[my_app] Created WGPUTextureView 344480 for texture 344456
[my_app] Created WGPUTexture 345664 with format RGBA8Unorm, sampleCount 1
[my_app] Created WGPUTextureView 345688 for texture 345664
[my_app] Referring to WGPUTextureView 342760 in WGPURenderPassDescriptor.colorAttachments[0].view
[my_app] Referring to WGPUTextureView 342840 in WGPURenderPassDescriptor.colorAttachments[0].resolveTarget
[my_app] Referring to WGPUTextureView 342920 in WGPURenderPassDescriptor.depthStencilAttachment.view
[my_app] Calling wgpuCommandEncoderBeginRenderPass...
my_app.js:693 Uncaught (in promise) RuntimeError: Aborted(Assertion failed)
    at abort (http://localhost:6931/my_app.js:693:11)
    at assert (http://localhost:6931/my_app.js:276:5)
    at Object.getJsObject (http://localhost:6931/my_app.js:4390:9)
    at makeDepthStencilAttachment (http://localhost:6931/my_app.js:5714:26)
    at makeRenderPassDescriptor (http://localhost:6931/my_app.js:5751:37)
    at _wgpuCommandEncoderBeginRenderPass (http://localhost:6931/my_app.js:5762:18)
    at imports.<computed> (http://localhost:6931/my_app.js:6426:24)
```
</details>

<details>

<summary>Verbose build output</summary>

```sh
my_user@my_computer:~/repos/my_solution$ cmake --build out --verbose
Change Dir: '/home/my_user/repos/my_solution/out'

Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile
/usr/bin/cmake -S/home/my_user/repos/my_solution -B/home/my_user/repos/my_solution/out --check-build-system CMakeFiles/Makefile.cmake 0
Re-run cmake file: Makefile older than: CMakeFiles/3.28.3/CMakeSystem.cmake
-- Configuring done (0.1s)
-- Generating done (0.0s)
-- Build files have been written to: /home/my_user/repos/my_solution/out
/usr/bin/cmake -E cmake_progress_start /home/my_user/repos/my_solution/out/CMakeFiles /home/my_user/repos/my_solution/out//CMakeFiles/progress.marks
/usr/bin/gmake  -f CMakeFiles/Makefile2 all
gmake[1]: Entering directory '/home/my_user/repos/my_solution/out'
/usr/bin/gmake  -f my_lib/CMakeFiles/my_lib.dir/build.make my_lib/CMakeFiles/my_lib.dir/depend
gmake[2]: Entering directory '/home/my_user/repos/my_solution/out'
cd /home/my_user/repos/my_solution/out && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/my_user/repos/my_solution /home/my_user/repos/my_solution/my_lib /home/my_user/repos/my_solution/out /home/my_user/repos/my_solution/out/my_lib /home/my_user/repos/my_solution/out/my_lib/CMakeFiles/my_lib.dir/DependInfo.cmake "--color="
gmake[2]: Leaving directory '/home/my_user/repos/my_solution/out'
/usr/bin/gmake  -f my_lib/CMakeFiles/my_lib.dir/build.make my_lib/CMakeFiles/my_lib.dir/build
gmake[2]: Entering directory '/home/my_user/repos/my_solution/out'
[  7%] Building CXX object my_lib/CMakeFiles/my_lib.dir/src/my_lib_file_0.cpp.o
cd /home/my_user/repos/my_solution/out/my_lib && /home/my_user/repos/emsdk/upstream/emscripten/em++ @CMakeFiles/my_lib.dir/includes_CXX.rsp -g -std=c++20 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wno-unused-parameter -Wno-deprecated-declarations -Wfatal-errors -pedantic --use-port=/home/my_user/repos/my_solution/my_lib/external/emscripten_ports/emdawnwebgpu.py -O0 -g -MD -MT my_lib/CMakeFiles/my_lib.dir/src/my_lib_file_0.cpp.o -MF CMakeFiles/my_lib.dir/src/my_lib_file_0.cpp.o.d -o CMakeFiles/my_lib.dir/src/my_lib_file_0.cpp.o -c /home/my_user/repos/my_solution/my_lib/src/my_lib_file_0.cpp
[ 15%] Building CXX object my_lib/CMakeFiles/my_lib.dir/src/my_lib_file_1.cpp.o
cd /home/my_user/repos/my_solution/out/my_lib && /home/my_user/repos/emsdk/upstream/emscripten/em++ @CMakeFiles/my_lib.dir/includes_CXX.rsp -g -std=c++20 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wno-unused-parameter -Wno-deprecated-declarations -Wfatal-errors -pedantic --use-port=/home/my_user/repos/my_solution/my_lib/external/emscripten_ports/emdawnwebgpu.py -O0 -g -MD -MT my_lib/CMakeFiles/my_lib.dir/src/my_lib_file_1.cpp.o -MF CMakeFiles/my_lib.dir/src/my_lib_file_1.cpp.o.d -o CMakeFiles/my_lib.dir/src/my_lib_file_1.cpp.o -c /home/my_user/repos/my_solution/my_lib/src/my_lib_file_1.cpp
[ 23%] Building CXX object my_lib/CMakeFiles/my_lib.dir/src/my_lib_file_2.cpp.o
cd /home/my_user/repos/my_solution/out/my_lib && /home/my_user/repos/emsdk/upstream/emscripten/em++ @CMakeFiles/my_lib.dir/includes_CXX.rsp -g -std=c++20 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wno-unused-parameter -Wno-deprecated-declarations -Wfatal-errors -pedantic --use-port=/home/my_user/repos/my_solution/my_lib/external/emscripten_ports/emdawnwebgpu.py -O0 -g -MD -MT my_lib/CMakeFiles/my_lib.dir/src/my_lib_file_2.cpp.o -MF CMakeFiles/my_lib.dir/src/my_lib_file_2.cpp.o.d -o CMakeFiles/my_lib.dir/src/my_lib_file_2.cpp.o -c /home/my_user/repos/my_solution/my_lib/src/my_lib_file_2.cpp
[ 30%] Building CXX object my_lib/CMakeFiles/my_lib.dir/src/my_lib_file_3.cpp.o
cd /home/my_user/repos/my_solution/out/my_lib && /home/my_user/repos/emsdk/upstream/emscripten/em++ @CMakeFiles/my_lib.dir/includes_CXX.rsp -g -std=c++20 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wno-unused-parameter -Wno-deprecated-declarations -Wfatal-errors -pedantic --use-port=/home/my_user/repos/my_solution/my_lib/external/emscripten_ports/emdawnwebgpu.py -O0 -g -MD -MT my_lib/CMakeFiles/my_lib.dir/src/my_lib_file_3.cpp.o -MF CMakeFiles/my_lib.dir/src/my_lib_file_3.cpp.o.d -o CMakeFiles/my_lib.dir/src/my_lib_file_3.cpp.o -c /home/my_user/repos/my_solution/my_lib/src/my_lib_file_3.cpp
[ 38%] Linking CXX static library libmy_lib.a
cd /home/my_user/repos/my_solution/out/my_lib && /usr/bin/cmake -P CMakeFiles/my_lib.dir/cmake_clean_target.cmake
cd /home/my_user/repos/my_solution/out/my_lib && /usr/bin/cmake -E cmake_link_script CMakeFiles/my_lib.dir/link.txt --verbose=1
/home/my_user/repos/emsdk/upstream/emscripten/emar qc libmy_lib.a CMakeFiles/my_lib.dir/src/my_lib_file_0.cpp.o CMakeFiles/my_lib.dir/src/my_lib_file_1.cpp.o CMakeFiles/my_lib.dir/src/my_lib_file_2.cpp.o CMakeFiles/my_lib.dir/src/my_lib_file_3.cpp.o
/home/my_user/repos/emsdk/upstream/emscripten/emranlib libmy_lib.a
gmake[2]: Leaving directory '/home/my_user/repos/my_solution/out'
[ 38%] Built target my_lib
/usr/bin/gmake  -f my_app/CMakeFiles/my_app.dir/build.make my_app/CMakeFiles/my_app.dir/depend
gmake[2]: Entering directory '/home/my_user/repos/my_solution/out'
cd /home/my_user/repos/my_solution/out && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/my_user/repos/my_solution /home/my_user/repos/my_solution/my_app /home/my_user/repos/my_solution/out /home/my_user/repos/my_solution/out/my_app /home/my_user/repos/my_solution/out/my_app/CMakeFiles/my_app.dir/DependInfo.cmake "--color="
gmake[2]: Leaving directory '/home/my_user/repos/my_solution/out'
/usr/bin/gmake  -f my_app/CMakeFiles/my_app.dir/build.make my_app/CMakeFiles/my_app.dir/build
gmake[2]: Entering directory '/home/my_user/repos/my_solution/out'
[ 46%] Building CXX object my_app/CMakeFiles/my_app.dir/src/my_app.cpp.o
cd /home/my_user/repos/my_solution/out/my_app && /home/my_user/repos/emsdk/upstream/emscripten/em++ @CMakeFiles/my_app.dir/includes_CXX.rsp -g -std=c++20 -fPIE -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wno-unused-parameter -Wno-deprecated-declarations -Wfatal-errors -pedantic --use-port=/home/my_user/repos/my_solution/my_lib/external/emscripten_ports/emdawnwebgpu.py -O0 -g -MD -MT my_app/CMakeFiles/my_app.dir/src/my_app.cpp.o -MF CMakeFiles/my_app.dir/src/my_app.cpp.o.d -o CMakeFiles/my_app.dir/src/my_app.cpp.o -c /home/my_user/repos/my_solution/my_app/src/my_app.cpp
[ 53%] Building CXX object my_app/CMakeFiles/my_app.dir/src/my_app_file_0.cpp.o
cd /home/my_user/repos/my_solution/out/my_app && /home/my_user/repos/emsdk/upstream/emscripten/em++ @CMakeFiles/my_app.dir/includes_CXX.rsp -g -std=c++20 -fPIE -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wno-unused-parameter -Wno-deprecated-declarations -Wfatal-errors -pedantic --use-port=/home/my_user/repos/my_solution/my_lib/external/emscripten_ports/emdawnwebgpu.py -O0 -g -MD -MT my_app/CMakeFiles/my_app.dir/src/my_app_file_0.cpp.o -MF CMakeFiles/my_app.dir/src/my_app_file_0.cpp.o.d -o CMakeFiles/my_app.dir/src/my_app_file_0.cpp.o -c /home/my_user/repos/my_solution/my_app/src/my_app_file_0.cpp
[ 61%] Building CXX object my_app/CMakeFiles/my_app.dir/src/my_app_file_1.cpp.o
cd /home/my_user/repos/my_solution/out/my_app && /home/my_user/repos/emsdk/upstream/emscripten/em++ @CMakeFiles/my_app.dir/includes_CXX.rsp -g -std=c++20 -fPIE -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wno-unused-parameter -Wno-deprecated-declarations -Wfatal-errors -pedantic --use-port=/home/my_user/repos/my_solution/my_lib/external/emscripten_ports/emdawnwebgpu.py -O0 -g -MD -MT my_app/CMakeFiles/my_app.dir/src/my_app_file_1.cpp.o -MF CMakeFiles/my_app.dir/src/my_app_file_1.cpp.o.d -o CMakeFiles/my_app.dir/src/my_app_file_1.cpp.o -c /home/my_user/repos/my_solution/my_app/src/my_app_file_1.cpp
[ 69%] Building CXX object my_app/CMakeFiles/my_app.dir/src/my_app_file_2.cpp.o
cd /home/my_user/repos/my_solution/out/my_app && /home/my_user/repos/emsdk/upstream/emscripten/em++ @CMakeFiles/my_app.dir/includes_CXX.rsp -g -std=c++20 -fPIE -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wno-unused-parameter -Wno-deprecated-declarations -Wfatal-errors -pedantic --use-port=/home/my_user/repos/my_solution/my_lib/external/emscripten_ports/emdawnwebgpu.py -O0 -g -MD -MT my_app/CMakeFiles/my_app.dir/src/my_app_file_2.cpp.o -MF CMakeFiles/my_app.dir/src/my_app_file_2.cpp.o.d -o CMakeFiles/my_app.dir/src/my_app_file_2.cpp.o -c /home/my_user/repos/my_solution/my_app/src/my_app_file_2.cpp
[ 76%] Building CXX object my_app/CMakeFiles/my_app.dir/src/my_app_file_3.cpp.o
cd /home/my_user/repos/my_solution/out/my_app && /home/my_user/repos/emsdk/upstream/emscripten/em++ @CMakeFiles/my_app.dir/includes_CXX.rsp -g -std=c++20 -fPIE -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wno-unused-parameter -Wno-deprecated-declarations -Wfatal-errors -pedantic --use-port=/home/my_user/repos/my_solution/my_lib/external/emscripten_ports/emdawnwebgpu.py -O0 -g -MD -MT my_app/CMakeFiles/my_app.dir/src/my_app_file_3.cpp.o -MF CMakeFiles/my_app.dir/src/my_app_file_3.cpp.o.d -o CMakeFiles/my_app.dir/src/my_app_file_3.cpp.o -c /home/my_user/repos/my_solution/my_app/src/my_app_file_3.cpp
[ 84%] Building CXX object my_app/CMakeFiles/my_app.dir/src/my_app_file_4.cpp.o
cd /home/my_user/repos/my_solution/out/my_app && /home/my_user/repos/emsdk/upstream/emscripten/em++ @CMakeFiles/my_app.dir/includes_CXX.rsp -g -std=c++20 -fPIE -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wno-unused-parameter -Wno-deprecated-declarations -Wfatal-errors -pedantic --use-port=/home/my_user/repos/my_solution/my_lib/external/emscripten_ports/emdawnwebgpu.py -O0 -g -MD -MT my_app/CMakeFiles/my_app.dir/src/my_app_file_4.cpp.o -MF CMakeFiles/my_app.dir/src/my_app_file_4.cpp.o.d -o CMakeFiles/my_app.dir/src/my_app_file_4.cpp.o -c /home/my_user/repos/my_solution/my_app/src/my_app_file_4.cpp
[ 92%] Building CXX object my_app/CMakeFiles/my_app.dir/src/my_app_file_5.cpp.o
cd /home/my_user/repos/my_solution/out/my_app && /home/my_user/repos/emsdk/upstream/emscripten/em++ @CMakeFiles/my_app.dir/includes_CXX.rsp -g -std=c++20 -fPIE -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wno-unused-parameter -Wno-deprecated-declarations -Wfatal-errors -pedantic --use-port=/home/my_user/repos/my_solution/my_lib/external/emscripten_ports/emdawnwebgpu.py -O0 -g -MD -MT my_app/CMakeFiles/my_app.dir/src/my_app_file_5.cpp.o -MF CMakeFiles/my_app.dir/src/my_app_file_5.cpp.o.d -o CMakeFiles/my_app.dir/src/my_app_file_5.cpp.o -c /home/my_user/repos/my_solution/my_app/src/my_app_file_5.cpp
[100%] Linking CXX executable my_app.js
cd /home/my_user/repos/my_solution/out/my_app && /usr/bin/cmake -E cmake_link_script CMakeFiles/my_app.dir/link.txt --verbose=1
/home/my_user/repos/emsdk/upstream/emscripten/em++ -g -sWASM=1 -sUSE_WEBGPU=0 -sASYNCIFY=1 --use-port=/home/my_user/repos/my_solution/my_lib/external/emscripten_ports/emdawnwebgpu.py --closure-args=--externs=/home/my_user/repos/emsdk/upstream/emscripten/cache/ports/emdawnwebgpu/emdawnwebgpu_pkg/webgpu/src/webgpu-externs.js -sASSERTIONS=2 -sNO_DISABLE_EXCEPTION_CATCHING=1 @CMakeFiles/my_app.dir/objects1.rsp -o my_app.js @CMakeFiles/my_app.dir/linkLibs.rsp
em++: warning: running limited binaryen optimizations because DWARF info requested (or indirectly required) [-Wlimited-postlink-optimizations]
gmake[2]: Leaving directory '/home/my_user/repos/my_solution/out'
[100%] Built target my_app
gmake[1]: Leaving directory '/home/my_user/repos/my_solution/out'
/usr/bin/cmake -E cmake_progress_start /home/my_user/repos/my_solution/out/CMakeFiles 0
```
</details>

**Comment by kainino0x** [comment]
We're moving the WebGPU bindings to be maintained in Dawn instead of Emscripten, so I'm migrating this bug to Dawn here: https://crbug.com/413070246
You can follow along there by logging in and clicking the "+1" button.

**Comment by kainino0x** [comment]
Hey @fridenmf, are you still having this issue? I am not sure if it's exactly the same as the original issue since that used `wgpuSwapChainGetCurrentTextureView` and you're using `wgpuSurfaceGetCurrentTexture` - also I think yours isn't even related to GetCurrentTexture, because in the logs it looks like your render pass is using just regular textures and no canvas textures.

My best guess right now is that we have some accounting error and something else is deleting the ID? But that doesn't seem likely.

**Comment by kainino0x** [comment]
@fridenmf bump
