### ISSUE TITLE
Constructing stackTrace with multiple side modules

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#20493]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.35 (a90c5abb489c516f59c0d16864d953d4bedd37da)
clang version 17.0.0 (https://github.com/llvm/llvm-project 6865cff8ea8b07d9f2385fd92cecb422404f0f35)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: ~/3.1.35/emsdk/upstream/bin
```

Currently, if exception is raised in a side-module stacktrace looks like following:
```
 'Error: char const*,
    at http://localhost:8000/build/test.wasm:wasm-function[150]:0xba67
    at wasm://wasm/4feaf742:wasm-function[4]:0x135 <-- side-module function
    at _fun4 (http://localhost:8000/build/test.js:4108:30)
    at http://localhost:8000/build/test.wasm:wasm-function[17]:0x5384
    at http://localhost:8000/build/test.wasm:wasm-function[13]:0x5335
    at Module.callFunc (http://localhost:8000/build/test.js:4234:69)
    at onmessage (http://localhost:8000/test.js:30:28)'
```

For main-module functions, we have the url to it so we can map its function indices to names using symbol map. For side-modules, there is no such information which side-module the function belongs to. This inhibits constructing stack traces and thus debugging crashes happening in them. Can we have something like https://github.com/WebAssembly/binaryen/pull/3901 that we have for module splitting in which we get wasm name at each function call ?

**Comment by sbc100** [comment]
I guess that `wasm://wasm/4feaf742` is the name of the unique name of the side module but its not very useful.

How are you loading the side module in this case?  Are you using dlopen at runtime, or relying on it being loaded at startup automatically?    If possible, could you share the full link command you are using? 

I'm not sure we have any direct control over what appears in the backtrace but we might be able to somehow load the module in a way that gives more information here.

**Comment by ravisumit33** [comment]
I am adding side-module as link argument while linking the main-module at command line.

**Comment by kripken** [comment]
https://github.com/WebAssembly/binaryen/pull/3901 (links above) [links to](https://github.com/WebAssembly/binaryen/pull/3901/files#diff-e1f361a2d97280e82d323166f8f3528a4ba66bc5d68853759a12764b5b87dd5dR1273-R1277) https://bugs.chromium.org/p/v8/issues/detail?id=11808 as a blocker on the chrome side, which has since been fixed (and it already worked in Firefox before) Based on that, using an object URL could fix this.

**Comment by ravisumit33** [comment]
Sorry but I didn't get how can I use object URL for a side module that is automatically downloaded at startup (or at runtime if used with dlopen) to get its name in the stack trace.

**Comment by kripken** [comment]
I think the idea there was that we'd adjust the dynamic linking code to use an Object URL to load it, rather than a normal URL. I'm not sure how much work that would take.
