### ISSUE TITLE
embind-emit-tsd does not work with -fwasm-exceptions

### ISSUE THREAD

**Issue by skelly-energid** [emscripten-core/emscripten#20514]
**Version of emscripten/emsdk:**
3.1.47

**Failing command line in full:**

```emscripten$ em++ -fwasm-exceptions  -lembind    ./test/other/embind_tsgen.cpp --embind-emit-tsd=foo

failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): unexpected section <Tag> (enable with --experimental-wasm-eh) @+3361
Aborted(CompileError: WebAssembly.instantiate(): unexpected section <Tag> (enable with --experimental-wasm-eh) @+3361)
tsgen_a.out.js:136
      throw ex;
      ^

RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): unexpected section <Tag> (enable with --experimental-wasm-eh) @+3361)
    at abort (tsgen_a.out.js:641:11)
    at tsgen_a.out.js:766:5
em++: error: 'node tsgen_a.out.js' failed (returned 7)

```

**Comment by brendandahl** [comment]
This can currently be worked around by adding --experimental-wasm-eh to your .emscripten configuration file to the NODE_JS option:
e.g.

NODE_JS = ['/whever/your/node/is/node', '--experimental-wasm-eh']
