### ISSUE TITLE
embind-emit-tsd does not work with -sMEMORY64

### ISSUE THREAD

**Issue by skelly-energid** [emscripten-core/emscripten#20542]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
3.1.47

**Failing command line in full:**

After adding `--experimental-wasm-memory64` to `.emscripten`.

```
em++ -fwasm-exceptions  -lembind  -sMEMORY64  ./test/other/embind_tsgen.cpp --embind-emit-tsd=foo
em++: warning: -sMEMORY64 is still experimental. Many features may not work. [-Wexperimental]
/tmp/emscripten_temp_kgu18wx6/tsgen_a.out.js:136
      throw ex;
      ^

Error: Missing primitive type to TS type for 'unsigned long'
    at TsPrinter.typeToJsName (/tmp/emscripten_temp_kgu18wx6/tsgen_a.out.js:2503:19)
    at FunctionDefinition.printSignature (/tmp/emscripten_temp_kgu18wx6/tsgen_a.out.js:1511:39)
    at FunctionDefinition.printFunction (/tmp/emscripten_temp_kgu18wx6/tsgen_a.out.js:1519:14)
    at ClassDefinition.print (/tmp/emscripten_temp_kgu18wx6/tsgen_a.out.js:1430:18)
    at TsPrinter.print (/tmp/emscripten_temp_kgu18wx6/tsgen_a.out.js:2516:15)
    at embindEmitTypes (/tmp/emscripten_temp_kgu18wx6/tsgen_a.out.js:2535:15)
    at callRuntimeCallbacks (/tmp/emscripten_temp_kgu18wx6/tsgen_a.out.js:1002:26)
    at initRuntime (/tmp/emscripten_temp_kgu18wx6/tsgen_a.out.js:465:3)
    at doRun (/tmp/emscripten_temp_kgu18wx6/tsgen_a.out.js:3096:5)
    at run (/tmp/emscripten_temp_kgu18wx6/tsgen_a.out.js:3117:5)
em++: error: 'node --experimental-wasm-eh --experimental-wasm-memory64 /tmp/emscripten_temp_kgu18wx6/tsgen_a.out.js' failed (returned 7)

```

**Comment by brendandahl** [comment]
This will be fixed by #20451

**Comment by Dabolus** [comment]
I tried running the steps above with the latest int64 fixes on `main` but I'm actually receiving a different error:

```
CompileError: WebAssembly.instantiate(): invalid memory limits flags 0x5 (enable via --experimental-wasm-memory64) @+3756
```

This happens because, to generate the typings, emcc actually runs the code w/ Node.js, so the memory64 flag needs to be enabled for Node.js to run properly. I tried adding the flag as suggested and the error changed to:

```
RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): unexpected section <Tag> (enable with --experimental-wasm-eh) @+3763
```

This is a different issue due to the `-fwasm-exceptions` flag that is being tracked [here](https://github.com/emscripten-core/emscripten/issues/20514).
Anyway, I added that flag too and the error finally changed to the original one reported by OP:

```
Error: Missing primitive type to TS type for 'unsigned long'
```

So I mapped both `unsigned long` and `long` to `number` in embind ts and the typings were finally generated correctly.

Do you want me to open a PR with the necessary fixes?

Also, should we always use those flags or add them based on the options provided to the compiler?

Last but not least, on embind ts there is this code that should map all the numeric values to JS numbers:
```js
if (type instanceof IntegerType) {
  return 'number';
}
```
Any idea why longs are considered a `PrimitiveType` instead of an `IntegerType` when running `emcc` with memory64 enabled?
