### ISSUE TITLE
embind-emit-tsd definitions don't work with Angular

### ISSUE THREAD

**Issue by skelly-energid** [emscripten-core/emscripten#20609]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
3.1.47

**Failing command line in full:**

After running the below script:

```
#!/bin/sh

set -e
set -v

ng new myApp --routing --style=scss

cd myApp

sed -i "/'@angular\/core';/a\
import type { MainModule } from './myWrapperDefs.d.ts';\n\
declare function MyWrapperModule() : Promise<MainModule>;\n\
import MyWrapperModule from './myWrapperModule.js';" src/app/app.component.ts

sed -i '/title = /a\
  constructor()\
  {\
    console.log("INVOKED CTOR");\
    MyWrapperModule().then(module => {\
      console.log("GOT MODULE");\
    });\
  }' src/app/app.component.ts

sed -i '/noImplicitReturns/a "noImplicitAny": false,' tsconfig.json

git diff

cd ..

cat << EOF > mywrapper.cpp

#include <atomic>
#include <memory>
#include <thread>

class MyWrapper
{
public:
    explicit MyWrapper();
    ~MyWrapper();

    int getNum();
};

#include <emscripten/bind.h>

#include <iostream>

int main(int argc, char** argv)
{
    return 0;
}

MyWrapper::MyWrapper()
{
}

MyWrapper::~MyWrapper()
{
}

int MyWrapper::getNum()
{
    return 42;
}

// clang-format off
EMSCRIPTEN_BINDINGS(my_wrapper)
{
    emscripten::class_<MyWrapper>("MyWrapper")
        .constructor()
        .function("getNum", &MyWrapper::getNum)
        ;
}
// clang-format on
EOF

em++ --embind-emit-tsd=myWrapperDefs.d.ts -O2 -g -o mywrapper.cpp.o -c mywrapper.cpp
em++ --embind-emit-tsd=myWrapperDefs.d.ts -O2 -g -sWASM=1 \
        -sMODULARIZE=1 -sEXPORT_NAME=MyWrapperModule \
        --minify=0 --bind \
        -sENVIRONMENT=web mywrapper.cpp.o -o myWrapperModule.js

mv myWrapperDefs.d.ts myWrapperModule.js myWrapperModule.wasm myApp/src/app

cd myApp
ng build
ng serve

```

then open http://localhost:4200/ and open devtools to the the output. The output is 

```
app.component.ts:15 INVOKED CTOR
ERROR ReferenceError: MyWrapperModule is not defined
    at new AppComponent (app.component.ts:16:5)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (app.component.ts:19:4)
    at getNodeInjectable (core.mjs:4862:44)
    at createRootComponent (core.mjs:14273:35)
    at ComponentFactory.create (core.mjs:14137:25)
    at ApplicationRef.bootstrap (core.mjs:28701:42)
    at core.mjs:28411:64
    at Array.forEach (<anonymous>)
    at PlatformRef._moduleDoBootstrap (core.mjs:28411:44)
    at core.mjs:28381:26
```

I realize this might be an angular bug, but I'm continuing to try to use the output of embind-emit-tsd and I can not get it to work.

**Comment by brendandahl** [comment]
I'm not sure what's going on with angular, but it doesn't seem to like mixing TS declarations with JS. Also, webpack doesn't seem to like our modularized export.

I got something working by doing (noticed the -sEXPORT_ES6=1):
```
em++ --embind-emit-tsd=myWrapperDefs.d.ts -O2 -g -sWASM=1         -sMODULARIZE=1 -sEXPORT_NAME=MyWrapperModule         --minify=0 --bind  -sEXPORT_ES6=1       -sENVIRONMENT=web mywrapper.cpp -o myWrapperModule.js
```

app.component.ts
```ts
import { Component } from '@angular/core';
import MyWrapperModule from './myWrapperModule.js';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'myApp';
  constructor()
  {
    console.log("INVOKED CTOR");
    MyWrapperModule().then(module => {
      let obj = new module.MyWrapper();
 
      // TODO: Typescript should tell me a number is not a string
      // let result : string = obj.getNum();
      console.log("GOT MODULE");
    });
  }
}
```

added file myWrapperModule.d.ts
```ts
import type { MainModule } from './myWrapperDefs.d.ts';
export default function MyWrapperModule() : Promise<MainModule>;
```

You'll then get 
`ERROR Error: Uncaught (in promise): TypeError: Failed to fetch` which is about it not being able to find the wasm file. I don't  know much about angular, but hopefully you can figure that part out.
