### ISSUE TITLE
Double-lock in emcc.py 

### ISSUE THREAD

**Issue by jfolker** [emscripten-core/emscripten#20686]
I encountered the following error while attempting to fetch dependencies and build a library via emcc. The error occurs when attempting to fetch SDL2_image and all its deps when the following args are passed into emcc:

```-sUSE_SDL_IMAGE=2 -sSDL2_IMAGE_FORMATS='["bmp","png","jpeg","tiff","webp"]'```

**Version of emscripten/emsdk:**
```
jfolker@jumpluff RasterView % emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.48 (e967e20b4727956a30592165a3c1cde5c67fa0a8)
clang version 18.0.0 (https://github.com/llvm/llvm-project a54545ba6514802178cf7cf1c1dd9f7efbf3cde7)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/jfolker/git/emsdk/upstream/bin
jfolker@jumpluff RasterView % 
```

**Failing command line in full:**
```
jfolker@jumpluff RasterView % emcc -std=c++17 -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_gfx \
    -sUSE_SDL=2 -sUSE_SDL_TTF=2 -sUSE_SDL_IMAGE=2 -sUSE_SDL_GFX=2 \
    -sSDL2_IMAGE_FORMATS='["bmp","png","jpeg","tiff","webp"]' \
    -lwebsocket.js -sPROXY_POSIX_SOCKETS -pthread -sPROXY_TO_PTHREAD \
    -I/Users/jfolker/git/emsdk/upstream/emscripten/cache/sysroot/include \
    -o RasterView.html main.cpp window_session.cpp
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libSDL2_image_bmp-jpeg-png-tiff-webp.a... (this will be cached in "/Users/jfolker/git/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libSDL2_image_bmp-jpeg-png-tiff-webp.a" for subsequent builds)
Traceback (most recent call last):
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 4549, in <module>
Traceback (most recent call last):
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 4549, in <module>
    sys.exit(main(sys.argv))
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    sys.exit(main(sys.argv))
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 4542, in main
    return func(*args, **kwds)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 4542, in main
    ret = run(args)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 1320, in run
    ret = run(args)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 1320, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3170, in phase_compile_inputs
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3170, in phase_compile_inputs
    compile_source_file(i, input_file)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3148, in compile_source_file
    compile_source_file(i, input_file)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3148, in compile_source_file
    cmd = get_clang_command(input_file)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3082, in get_clang_command
    cmd = get_clang_command(input_file)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3082, in get_clang_command
    return get_compiler(src_file) + get_cflags(state.orig_args, use_cxx(src_file)) + compile_args + [src_file]
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 1037, in get_cflags
    ports.add_cflags(cflags, settings)
    return get_compiler(src_file) + get_cflags(state.orig_args, use_cxx(src_file)) + compile_args + [src_file]
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/ports/__init__.py", line 416, in add_cflags
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 1037, in get_cflags
    ports.add_cflags(cflags, settings)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/ports/__init__.py", line 416, in add_cflags
    port.get(Ports, settings, shared)
    port.get(Ports, settings, shared)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/ports/libpng.py", line 49, in get
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/ports/libpng.py", line 49, in get
    return [shared.cache.get_lib(get_lib_name(settings), create, what='port')]
    return [shared.cache.get_lib(get_lib_name(settings), create, what='port')]
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 139, in get_lib
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 139, in get_lib
Traceback (most recent call last):
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 4549, in <module>
    return get(name, *args, **kwargs)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 157, in get
    return get(name, *args, **kwargs)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 157, in get
    with lock(shortname):
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 117, in __enter__
    with lock(shortname):
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 61, in lock
    return next(self.gen)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 61, in lock
    acquire_cache_lock(reason)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 35, in acquire_cache_lock
    assert 'EM_CACHE_IS_LOCKED' not in os.environ, f'attempt to lock the cache while a parent process is holding the lock ({reason})'
    acquire_cache_lock(reason)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 35, in acquire_cache_lock
AssertionError: attempt to lock the cache while a parent process is holding the lock (sysroot/lib/wasm32-emscripten/libpng.a)
    assert 'EM_CACHE_IS_LOCKED' not in os.environ, f'attempt to lock the cache while a parent process is holding the lock ({reason})'
AssertionError: attempt to lock the cache while a parent process is holding the lock (sysroot/lib/wasm32-emscripten/libpng.a)
    sys.exit(main(sys.argv))
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
Traceback (most recent call last):
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 4549, in <module>
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 4542, in main
    sys.exit(main(sys.argv))
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 4542, in main
    ret = run(args)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 1320, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3170, in phase_compile_inputs
    ret = run(args)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 1320, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
    compile_source_file(i, input_file)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3148, in compile_source_file
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3170, in phase_compile_inputs
    cmd = get_clang_command(input_file)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3082, in get_clang_command
    compile_source_file(i, input_file)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3148, in compile_source_file
Traceback (most recent call last):
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 4549, in <module>
    return get_compiler(src_file) + get_cflags(state.orig_args, use_cxx(src_file)) + compile_args + [src_file]
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 1037, in get_cflags
    ports.add_cflags(cflags, settings)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/ports/__init__.py", line 416, in add_cflags
    cmd = get_clang_command(input_file)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3082, in get_clang_command
    port.get(Ports, settings, shared)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/ports/libpng.py", line 49, in get
    return [shared.cache.get_lib(get_lib_name(settings), create, what='port')]
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 139, in get_lib
    return get(name, *args, **kwargs)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 157, in get
    with lock(shortname):
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 117, in __enter__
    sys.exit(main(sys.argv))
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return next(self.gen)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 61, in lock
Traceback (most recent call last):
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 4549, in <module>
    acquire_cache_lock(reason)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 35, in acquire_cache_lock
    return func(*args, **kwds)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 4542, in main
    assert 'EM_CACHE_IS_LOCKED' not in os.environ, f'attempt to lock the cache while a parent process is holding the lock ({reason})'
AssertionError: attempt to lock the cache while a parent process is holding the lock (sysroot/lib/wasm32-emscripten/libpng.a)
    return get_compiler(src_file) + get_cflags(state.orig_args, use_cxx(src_file)) + compile_args + [src_file]
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 1037, in get_cflags
    ports.add_cflags(cflags, settings)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/ports/__init__.py", line 416, in add_cflags
    port.get(Ports, settings, shared)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/ports/libpng.py", line 49, in get
    return [shared.cache.get_lib(get_lib_name(settings), create, what='port')]
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 139, in get_lib
    return get(name, *args, **kwargs)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 157, in get
    with lock(shortname):
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 61, in lock
    acquire_cache_lock(reason)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 35, in acquire_cache_lock
    assert 'EM_CACHE_IS_LOCKED' not in os.environ, f'attempt to lock the cache while a parent process is holding the lock ({reason})'
AssertionError: attempt to lock the cache while a parent process is holding the lock (sysroot/lib/wasm32-emscripten/libpng.a)
    sys.exit(main(sys.argv))
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    ret = run(args)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 1320, in run
    return func(*args, **kwds)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 4542, in main
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3170, in phase_compile_inputs
    ret = run(args)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 1320, in run
    compile_source_file(i, input_file)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3148, in compile_source_file
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3170, in phase_compile_inputs
    cmd = get_clang_command(input_file)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3082, in get_clang_command
    compile_source_file(i, input_file)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3148, in compile_source_file
    return get_compiler(src_file) + get_cflags(state.orig_args, use_cxx(src_file)) + compile_args + [src_file]
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 1037, in get_cflags
    ports.add_cflags(cflags, settings)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/ports/__init__.py", line 416, in add_cflags
    cmd = get_clang_command(input_file)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3082, in get_clang_command
    port.get(Ports, settings, shared)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/ports/libpng.py", line 49, in get
    return [shared.cache.get_lib(get_lib_name(settings), create, what='port')]
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 139, in get_lib
    return get(name, *args, **kwargs)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 157, in get
    with lock(shortname):
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 61, in lock
    acquire_cache_lock(reason)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 35, in acquire_cache_lock
    return get_compiler(src_file) + get_cflags(state.orig_args, use_cxx(src_file)) + compile_args + [src_file]
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 1037, in get_cflags
    assert 'EM_CACHE_IS_LOCKED' not in os.environ, f'attempt to lock the cache while a parent process is holding the lock ({reason})'
AssertionError: attempt to lock the cache while a parent process is holding the lock (sysroot/lib/wasm32-emscripten/libpng.a)
    ports.add_cflags(cflags, settings)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/ports/__init__.py", line 416, in add_cflags
    port.get(Ports, settings, shared)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/ports/libpng.py", line 49, in get
    return [shared.cache.get_lib(get_lib_name(settings), create, what='port')]
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 139, in get_lib
    return get(name, *args, **kwargs)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 157, in get
    with lock(shortname):
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 61, in lock
    acquire_cache_lock(reason)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 35, in acquire_cache_lock
    assert 'EM_CACHE_IS_LOCKED' not in os.environ, f'attempt to lock the cache while a parent process is holding the lock ({reason})'
Traceback (most recent call last):
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 4549, in <module>
AssertionError: attempt to lock the cache while a parent process is holding the lock (sysroot/lib/wasm32-emscripten/libpng.a)
    sys.exit(main(sys.argv))
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 4542, in main
    ret = run(args)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 1320, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3170, in phase_compile_inputs
    compile_source_file(i, input_file)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3148, in compile_source_file
Traceback (most recent call last):
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 4549, in <module>
    cmd = get_clang_command(input_file)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3082, in get_clang_command
    sys.exit(main(sys.argv))
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 4542, in main
    return get_compiler(src_file) + get_cflags(state.orig_args, use_cxx(src_file)) + compile_args + [src_file]
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 1037, in get_cflags
    ports.add_cflags(cflags, settings)
    ret = run(args)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 1320, in run
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/ports/__init__.py", line 416, in add_cflags
    port.get(Ports, settings, shared)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/ports/libpng.py", line 49, in get
    return [shared.cache.get_lib(get_lib_name(settings), create, what='port')]
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 139, in get_lib
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return get(name, *args, **kwargs)
    return func(*args, **kwds)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3170, in phase_compile_inputs
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 157, in get
    with lock(shortname):
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 61, in lock
    acquire_cache_lock(reason)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 35, in acquire_cache_lock
    assert 'EM_CACHE_IS_LOCKED' not in os.environ, f'attempt to lock the cache while a parent process is holding the lock ({reason})'
AssertionError: attempt to lock the cache while a parent process is holding the lock (sysroot/lib/wasm32-emscripten/libpng.a)
    compile_source_file(i, input_file)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3148, in compile_source_file
    cmd = get_clang_command(input_file)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 3082, in get_clang_command
    return get_compiler(src_file) + get_cflags(state.orig_args, use_cxx(src_file)) + compile_args + [src_file]
  File "/Users/jfolker/git/emsdk/upstream/emscripten/emcc.py", line 1037, in get_cflags
    ports.add_cflags(cflags, settings)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/ports/__init__.py", line 416, in add_cflags
    port.get(Ports, settings, shared)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/ports/libpng.py", line 49, in get
    return [shared.cache.get_lib(get_lib_name(settings), create, what='port')]
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 139, in get_lib
    return get(name, *args, **kwargs)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 157, in get
    with lock(shortname):
  File "/Users/jfolker/git/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 61, in lock
    acquire_cache_lock(reason)
  File "/Users/jfolker/git/emsdk/upstream/emscripten/tools/cache.py", line 35, in acquire_cache_lock
    assert 'EM_CACHE_IS_LOCKED' not in os.environ, f'attempt to lock the cache while a parent process is holding the lock ({reason})'
AssertionError: attempt to lock the cache while a parent process is holding the lock (sysroot/lib/wasm32-emscripten/libpng.a)
emcc: error: Subprocess 1/19 failed (returned 1)! (cmdline: /Users/jfolker/git/emsdk/upstream/emscripten/emcc -c /Users/jfolker/git/emsdk/upstream/emscripten/cache/ports/sdl2_image/SDL_image-release-2.6.0/IMG.c -o /Users/jfolker/git/emsdk/upstream/emscripten/cache/ports-builds/sdl2_image/IMG.c.o -g -sSTRICT -Werror -O2 -I/Users/jfolker/git/emsdk/upstream/emscripten/cache/ports/sdl2_image/SDL_image-release-2.6.0 -O2 -sUSE_SDL=2 -Wno-format-security -DLOAD_BMP -DLOAD_JPEG -DLOAD_PNG -DLOAD_TIFF -DLOAD_WEBP -sUSE_LIBPNG)
jfolker@jumpluff RasterView % 

```

**Comment by sbc100** [comment]
I think this is a duplicate of #20214
