### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by Flyingbeanss** [emscripten-core/emscripten#20731]
Hi! I want to deal with  `memory access out of bound` in my program. After I add `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=address")` and `set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fsanitize=address")` , the console print as follow:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at lengthBytesUTF8 (occt-webgl-sample.js?t=1700141293680:1746:26)
    at stringToNewUTF8 (occt-webgl-sample.js?t=1700141293680:5971:13)
    at occt-webgl-sample.js?t=1700141293680:10523:32
    at withBuiltinMalloc (occt-webgl-sample.js?t=1700141293680:5962:10)
    at _emscripten_pc_get_file (occt-webgl-sample.js?t=1700141293680:10519:37)
    at occt-webgl-sample.wasm.__sanitizer::EmscriptenSymbolizerTool::SymbolizePC(unsigned long, __sanitizer::SymbolizedStack*) (occt-webgl-sample.wasm:0x16a5673)
    at occt-webgl-sample.wasm.__sanitizer::Symbolizer::SymbolizePC(unsigned long) (occt-webgl-sample.wasm:0x16a5960)
    at occt-webgl-sample.wasm.__lsan::LeakSuppressionContext::GetSuppressionForAddr(unsigned long) (occt-webgl-sample.wasm:0x1696920)
    at occt-webgl-sample.wasm.__lsan::LeakSuppressionContext::Suppress(unsigned int, unsigned long, unsigned long) (occt-webgl-sample.wasm:0x1696a6b)
    at occt-webgl-sample.wasm.__lsan::LeakReport::ApplySuppressions() (occt-webgl-sample.wasm:0x1697c0f)
```
I just don't understand why.
Here is the original output.
```
occt-webgl-sample.js?t=1700142325331:14608 Uncaught RuntimeError: memory access out of bounds
    at occt-webgl-sample.wasm.math_FunctionSetRoot::math_FunctionSetRoot(math_FunctionSetWithDerivatives&, math_Vector const&, int) (occt-webgl-sample.wasm:0xa28b01)
    at invoke_iiiii (occt-webgl-sample.js?t=1700142325331:14605:36)
    at occt-webgl-sample.wasm.math_FunctionRoot::math_FunctionRoot(math_FunctionWithDerivative&, double, double, double, double, int) (occt-webgl-sample.wasm:0xa261a0)
    at occt-webgl-sample.wasm.Extrema_LocEPCOfLocateExtPC::Perform(gp_Pnt const&, double) (occt-webgl-sample.wasm:0x8a659a)
    at invoke_viid (occt-webgl-sample.js?t=1700142325331:14990:29)
    at occt-webgl-sample.wasm.Extrema_LocateExtPC::Perform(gp_Pnt const&, double) (occt-webgl-sample.wasm:0x8a56ff)
    at invoke_viid (occt-webgl-sample.js?t=1700142325331:14990:29)
    at occt-webgl-sample.wasm.Extrema_LocateExtPC::Extrema_LocateExtPC(gp_Pnt const&, Adaptor3d_Curve const&, double, double, double, double) (occt-webgl-sample.wasm:0x8a62af)
    at invoke_iiiidddd (occt-webgl-sample.js?t=1700142325331:16343:36)
    at occt-webgl-sample.wasm.ShapeAnalysis_Curve::ProjectAct(Adaptor3d_Curve const&, gp_Pnt const&, double, gp_Pnt&, double&) const (occt-webgl-sample.wasm:0x4957fd)
```
Thanks for help , sincerely!

**Comment by sbc100** [comment]
Hmm.. it looks like `convertPCtoSourceLocation` must be returning a result that doesn't have a `.file` attribute so `undefined` is being passed to `stringToNewUTF8` here: https://github.com/emscripten-core/emscripten/blob/9429b4893c5e376e23e67d7007d2b948987445a0/src/library.js#L2819

Strange that we have never seen this before.

Can you try adding `-g` and/or `--profiling-funcs` to your compile and link flags?

**Comment by Flyingbeanss** [comment]
@sbc100  Thanks for reply. Actually, I have added `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g")` and `set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -g")`. After I add `set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} --profiling-funcs")` and `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --profiling-funcs")`, it seems to be no change in the console.

**Comment by sbc100** [comment]
Can you take look devtools a few levels up the stack in `emscripten_pc_get_file`?  Can you see what `result` contains?  (The thing that `convertPCtoSourceLocation` returns?)

**Comment by Flyingbeanss** [comment]
@sbc100  Thanks for your advice. I'm not very familiar with js and browser.
```
 var result = convertPCtoSourceLocation(pc);
 if (!result) return 0;
```
`convertPCtoSourceLocation(pc);` returns `null`

**Comment by sbc100** [comment]
When the crash happens though I'm pretty such it doesn't return null, since it does not return there but goes on to call `stringToNewUTF8` below.     You need to somehow pause/break when the exceptions happens.  Try "Pause on exceptions" in devtools.

Then select the `emscripten_pc_get_file` and type `result` in the console to see its contents (or inspect it using the Locals pane).

**Comment by Flyingbeanss** [comment]
Thank you for being so patient.I make a mistake, it's not null. The `convertPCtoSourceLocation(pc);` will be called many times.After a certain call, it returns `undefined`.The content is here:
<img width="154" alt="image" src="https://github.com/emscripten-core/emscripten/assets/53996591/7c7c9b51-6a96-4002-bc12-365354beb5ba">

**Comment by tovabar** [comment]
Hi,
I have the same problem in the following case:
I compiled with:
	   `set(CMAKE_CXX_FLAGS "-gsource-map -fsanitize=address -fsanitize-recover=address ${CMAKE_CXX_FLAGS}")`
	   `set(CMAKE_C_FLAGS "-gsource-map -fsanitize=address -fsanitize-recover=address ${CMAKE_C_FLAGS}")`
and link flags:
	  ` -O2 -gsource-map -fsanitize=address -fsanitize-recover=address -sMODULARIZE -sEXPORT_NAME=McStartMyProj -sERROR_ON_UNDEFINED_SYMBOLS=0 -sWARN_ON_UNDEFINED_SYMBOLS=0 --pre-js WrapperUtils.js -lnodefs.js -lembind --embed-file FS -sGL_ENABLE_GET_PROC_ADDRESS=1 -sMIN_WEBGL_VERSION=1 -sMAX_WEBGL_VERSION=2 -sSTACK_SIZE=5MB -sALLOW_MEMORY_GROWTH=1 -sINITIAL_HEAP=1GB -sMAXIMUM_MEMORY=4GB -sMEMORY_GROWTH_GEOMETRIC_STEP=0.5 -sMEMORY_GROWTH_GEOMETRIC_CAP=0` (optimization with -O2 is a must in my case, due to another limitation)

all ASan checks work properly, but once __lsan::DoRecoverableLeakCheckVoid() is invoked manually for runtime memory leak detection, the following error is emitted:
```
MyProj_D.js:3251 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at lengthBytesUTF8 (MyProj_D.js:3251:27)
    at stringToNewUTF8 (MyProj_D.js:8283:14)
    at MyProj_D.js:13853:33
    at withBuiltinMalloc (MyProj_D.js:8274:12)
    at _emscripten_pc_get_file (MyProj_D.js:13848:37)
    at MyProj_D.wasm.__sanitizer::EmscriptenSymbolizerTool::SymbolizePC(:3000/unsigned long, __sanitizer::SymbolizedStack*) (http://localhost:3000/MyProj_D.wasm)
    at MyProj_D.wasm.__sanitizer::Symbolizer::SymbolizePC(:3000/unsigned long) (http://localhost:3000/MyProj_D.wasm)
    at MyProj_D.wasm.__lsan::LeakSuppressionContext::GetSuppressionForAddr(:3000/unsigned long) (http://localhost:3000/MyProj_D.wasm)
    at MyProj_D.wasm.__lsan::LeakSuppressionContext::Suppress(:3000/unsigned int, unsigned long, unsigned long) (http://localhost:3000/MyProj_D.wasm)
    at MyProj_D.wasm.__lsan::CheckForLeaks(:3000/) (http://localhost:3000/MyProj_D.wasm)
```
as u mentioned before, result.file is undefined calling to convertPCtoSourceLocation from _emscripten_pc_get_file 
do u have an idea what can be done to resolve this?

**Comment by stevenwdv** [comment]
Hi, I also have this problem (with address sanitizer + source map), with all result fields being `undefined`.

It seems that `WasmSourceMap` allows all info fields to be optional:

https://github.com/emscripten-core/emscripten/blob/d1f88fa22e4145807622a06ea7dcf1494234e542/src/source_map_support.js#L49-L56

Contrary, functions like `emscripten_pc_get_file` assume they are always set if the result is not null (except for `emscripten_pc_get_column`, apparently, which has `result.column || 0`).
