### ISSUE TITLE
Build fails due to Unknown archive format on Mac M2

### ISSUE THREAD

**Issue by ChinYikMing** [emscripten-core/emscripten#20986]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.46 (19607820c447a13fd8d0b7680c56148427d6e1b8)
clang version 18.0.0 (https://github.com/llvm/llvm-project 75501f53624de92aafce2f1da698b249a7293dc7)

I was building the C program with ported SDL2, SDL2_image,  and SDL2_ttf. 

The build command:
```
emcc main.cpp -s WASM=1 -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='["png"]' -s USE_SDL_TTF=2 --preload-file res -o index.js
```

But get error:
```
ports:INFO: retrieving port: harfbuzz from https://github.com/harfbuzz/harfbuzz/releases/download/3.2.0/harfbuzz-3.2.0.tar.xz
ports:INFO: unpacking port: harfbuzz
Traceback (most recent call last):
  File "/Users/chinyikming/emsdk/upstream/emscripten/emcc.py", line 4465, in <module>
    sys.exit(main(sys.argv))
  File "/Users/chinyikming/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/chinyikming/emsdk/upstream/emscripten/emcc.py", line 4458, in main
    ret = run(args)
  File "/Users/chinyikming/emsdk/upstream/emscripten/emcc.py", line 1284, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/Users/chinyikming/emsdk/python/3.9.2_64bit/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/chinyikming/emsdk/upstream/emscripten/emcc.py", line 3140, in phase_compile_inputs
    compile_source_file(i, input_file)
  File "/Users/chinyikming/emsdk/upstream/emscripten/emcc.py", line 3118, in compile_source_file
    cmd = get_clang_command(input_file)
  File "/Users/chinyikming/emsdk/upstream/emscripten/emcc.py", line 3052, in get_clang_command
    return get_compiler(src_file) + get_cflags(state.orig_args, use_cxx(src_file)) + compile_args + [src_file]
  File "/Users/chinyikming/emsdk/upstream/emscripten/emcc.py", line 1021, in get_cflags
    ports.add_cflags(cflags, settings)
  File "/Users/chinyikming/emsdk/upstream/emscripten/tools/ports/__init__.py", line 416, in add_cflags
    port.get(Ports, settings, shared)
  File "/Users/chinyikming/emsdk/upstream/emscripten/tools/ports/harfbuzz.py", line 82, in get
    ports.fetch_project('harfbuzz', f'https://github.com/harfbuzz/harfbuzz/releases/download/{VERSION}/harfbuzz-{VERSION}.tar.xz', sha512hash=HASH)
  File "/Users/chinyikming/emsdk/upstream/emscripten/tools/ports/__init__.py", line 303, in fetch_project
    unpack()
  File "/Users/chinyikming/emsdk/upstream/emscripten/tools/ports/__init__.py", line 276, in unpack
    shutil.unpack_archive(filename=fullpath, extract_dir=fullname)
  File "/Users/chinyikming/emsdk/python/3.9.2_64bit/lib/python3.9/shutil.py", line 1241, in unpack_archive
    raise ReadError("Unknown archive format '{0}'".format(filename))
shutil.ReadError: Unknown archive format '/Users/chinyikming/emsdk/upstream/emscripten/cache/ports/harfbuzz.2.0.tar.xz'
```

It was solved by setting the `EMSDK_PYTHON` to system-wide python3:
```
export EMSDK_PYTHON=/usr/bin/python3
```
My system-wide python3 version is 3.9.6 and the default `EMSDK_PYTHON` is `3.9.2`.

Solution is from: #982

**Comment by nornagon** [comment]
Switching to system python3 solved the .xz error for me, but now I also see an error with a .zip file for SDL_ttf:

```
ports:INFO: unpacking port: sdl2_ttf
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 1229, in _unpack_tarfile
    tarobj = tarfile.open(filename)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tarfile.py", line 1639, in open
    raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
tarfile.ReadError: file could not be opened successfully:
- method gz: ReadError('not a gzip file')
- method bz2: ReadError('not a bzip2 file')
- method xz: ReadError('not an lzma file')
- method tar: ReadError('invalid header')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/emcc.py", line 1605, in <module>
    sys.exit(main(sys.argv))
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/emcc.py", line 1598, in main
    ret = run(args)
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/emcc.py", line 633, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/emcc.py", line 1015, in phase_compile_inputs
    cmd = get_clang_command() + inputs
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/emcc.py", line 978, in get_clang_command
    return compiler + get_cflags(state.orig_args, use_cxx) + compile_args
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/emcc.py", line 428, in get_cflags
    ports.add_cflags(cflags, settings)
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/tools/ports/__init__.py", line 416, in add_cflags
    port.get(Ports, settings, shared)
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/tools/ports/sdl2_ttf.py", line 19, in get
    ports.fetch_project('sdl2_ttf', f'https://github.com/libsdl-org/SDL_ttf/archive/{TAG}.zip', sha512hash=HASH)
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/tools/ports/__init__.py", line 303, in fetch_project
    unpack()
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/tools/ports/__init__.py", line 276, in unpack
    shutil.unpack_archive(filename=fullpath, extract_dir=fullname, format="xztar")
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 1297, in unpack_archive
    func(filename, extract_dir, **dict(format_info[2]))
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 1231, in _unpack_tarfile
    raise ReadError(
shutil.ReadError: /Users/jeremy.rose/play/emsdk/upstream/emscripten/cache/ports/sdl2_ttf.20.2.zip is not a compressed or uncompressed tar file
```

**Comment by sbc100** [comment]
That last issue looks like your homebrew version of python3 does not know how to unzip zip files.   I imagine that means that you need to install some additional homebrew package?   (I'm afraid I don't know which one since I don't use macOS myself).

I assume that your system version of python (/usr/bin/python3) is actually the homebrew version since all error message seem to refer to `/opt/homebrew/Cellar/python@3.10/3.10.6_2/`?

The original issue looks like the version of python we ship in emsdk for M1 macs does not support xz and that is something we should fix.   I think I've seen that issue reported elsewhere so this may be a duplicate.

**Comment by nornagon** [comment]
The system python3 (/usr/bin/python3) also fails to unzip zip files:

```
ports:INFO: unpacking port: sdl2_ttf
Traceback (most recent call last):
  File "/Users/jeremy.rose/work/build-tools/third_party/Xcode/Xcode-15.0.0.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/shutil.py", line 1180, in _unpack_tarfile
    tarobj = tarfile.open(filename)
  File "/Users/jeremy.rose/work/build-tools/third_party/Xcode/Xcode-15.0.0.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tarfile.py", line 1616, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/emcc.py", line 1605, in <module>
    sys.exit(main(sys.argv))
  File "/Users/jeremy.rose/work/build-tools/third_party/Xcode/Xcode-15.0.0.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/emcc.py", line 1598, in main
    ret = run(args)
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/emcc.py", line 633, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/Users/jeremy.rose/work/build-tools/third_party/Xcode/Xcode-15.0.0.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/emcc.py", line 1015, in phase_compile_inputs
    cmd = get_clang_command() + inputs
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/emcc.py", line 978, in get_clang_command
    return compiler + get_cflags(state.orig_args, use_cxx) + compile_args
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/emcc.py", line 428, in get_cflags
    ports.add_cflags(cflags, settings)
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/tools/ports/__init__.py", line 416, in add_cflags
    port.get(Ports, settings, shared)
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/tools/ports/sdl2_ttf.py", line 19, in get
    ports.fetch_project('sdl2_ttf', f'https://github.com/libsdl-org/SDL_ttf/archive/{TAG}.zip', sha512hash=HASH)
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/tools/ports/__init__.py", line 303, in fetch_project
    unpack()
  File "/Users/jeremy.rose/play/emsdk/upstream/emscripten/tools/ports/__init__.py", line 276, in unpack
    shutil.unpack_archive(filename=fullpath, extract_dir=fullname, format="xztar")
  File "/Users/jeremy.rose/work/build-tools/third_party/Xcode/Xcode-15.0.0.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/shutil.py", line 1243, in unpack_archive
    func(filename, extract_dir, **dict(format_info[2]))
  File "/Users/jeremy.rose/work/build-tools/third_party/Xcode/Xcode-15.0.0.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/shutil.py", line 1182, in _unpack_tarfile
    raise ReadError(
shutil.ReadError: /Users/jeremy.rose/play/emsdk/upstream/emscripten/cache/ports/sdl2_ttf.20.2.zip is not a compressed or uncompressed tar file
```
