### ISSUE TITLE
Libpng wasm port broken?

### ISSUE THREAD

**Issue by justinlaughlin** [emscripten-core/emscripten#21323]
I am not sure, but I believe there may be something wrong with the libpng ports hosted at https://storage.googleapis.com/webassembly/emscripten-ports/libpng-1.6.39.tar.gz.

Adding the flag `USE_LIBPNG=1` leads to `emscripten` trying to download `libpng` from that url, and it looks like it fails in doing so. I am pasting the relevant outputs of `emcc` below, but I was able to isolate this behavior using only `requests` from `python`, which is what `emscripten` seems to be calling. I will post an example python script below demonstrating this.

# EMCC

**Version**
```bash
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.51 (c0c2ca1314672a25699846b4663701bcb6f69cca)
clang version 18.0.0git (https://github.com/llvm/llvm-project f2464ca317bfeeedddb7cbdea3c2c8ec487890bb)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Failing command line**
```bash
emcc -std=c++11 -s USE_SDL=2 -s USE_FREETYPE=1 -s USE_LIBPNG=1  -O3 -std=c++11 <...>
ports:INFO: retrieving port: zlib from https://github.com/madler/zlib/archive/refs/tags/v1.2.13.tar.gz
ports:INFO: unpacking port: zlib
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libz.a... (this will be cached in "/home/euler/deps/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libz.a" for subsequent builds)
system_libs:INFO: compiled 15 inputs in 0.45s
cache:INFO:  - ok
ports:INFO: retrieving port: libpng from https://storage.googleapis.com/webassembly/emscripten-ports/libpng-1.6.39.tar.gz
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 737, in _error_catcher
    yield
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 873, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(591870 bytes read, 915458 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 1033, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 953, in read
    data = self._raw_read(amt)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 851, in _raw_read
    with self._error_catcher():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
ports:INFO: retrieving port: freetype from https://github.com/emscripten-ports/FreeType/archive/version_1.zip
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 754, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(591870 bytes read, 915458 more expected)', IncompleteRead(591870 bytes read, 915458 more expected))

...
```

## Python (just using `requests`)

```python
import requests

# try various different URLs
urls = ('https://storage.googleapis.com/webassembly/emscripten-ports/libpng-1.6.39.tar.gz',
        'https://storage.googleapis.com/webassembly/emscripten-ports/libpng-1.6.37.tar.gz',
        'https://storage.googleapis.com/webassembly/emscripten-ports/freetype-2.11.1.tar.gz',
        'https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v16.20.0-darwin-x64.tar.gz',
        'https://files.pythonhosted.org/packages/2d/20/e89ba2dfc5a274545350b5ba3abd9e8bbafdbeb84bb974bfd00a26d9d4df/streamlit-1.31.1.tar.gz',
        'https://github.com/SciML/DifferentialEquations.jl/archive/refs/tags/v7.12.0.tar.gz',
       )

def download_tarball(url, local_filename):
    with open(local_filename, 'wb') as f:
        r = requests.get(url, stream=True)
        for chunk in r.raw.stream(1024, decode_content=False):
            if chunk:
                f.write(chunk)
                f.flush()

for url in urls:
    local_filename=url.split('/')[-1]
    print(f"\nTrying to download tarball from {url}")
    print(f"Local filename: {local_filename}")
    try:
        download_tarball(url, local_filename)
        print("Success!")
    except Exception as e:
        print(e)
```

### Python output
![image](https://github.com/emscripten-core/emscripten/assets/27717785/1846c52f-3766-4aad-9f02-b5e5e195d147)

Only fails with `libpng-1.6.39.tar.gz` and `libpng-1.6.37.tar.gz`

**Comment by sbc100** [comment]
Can you run fetch https://storage.googleapis.com/webassembly/emscripten-ports/libpng-1.6.39.tar.gz using curl and/or wget on the command line?  Does it result in a file with the correct sha512hash?

**Comment by justinlaughlin** [comment]
I am able to just click on the link in my browser and it will download (I swear I remember this failing last week), but it does fail using `curl`. I hadn't tried `wget` until now but that actually does work. It looks like the failure happens at the same point in the file (byte 591870), and `wget` seems to succeed by retrying the read?

```bash
$ wget https://storage.googleapis.com/webassembly/emscripten-ports/libpng-1.6.39.tar.gz
--2024-02-12 17:45:31--  https://storage.googleapis.com/webassembly/emscripten-ports/libpng-1.6.39.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.46.219, 142.250.189.251, 142.251.46.187, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.46.219|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1507328 (1.4M) [application/x-tar]
Saving to: ‘libpng-1.6.39.tar.gz’

libpng-1.6.39.tar.gz                                                           39%[=========================================================================>                                                                                                                     ] 578.00K  2.63MB/s    in 0.2s

2024-02-12 17:45:31 (2.63 MB/s) - Read error at byte 591870/1507328 (Connection reset by peer). Retrying.

--2024-02-12 17:45:32--  (try: 2)  https://storage.googleapis.com/webassembly/emscripten-ports/libpng-1.6.39.tar.gz
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.46.219|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 1507328 (1.4M), 915458 (894K) remaining [application/x-tar]
Saving to: ‘libpng-1.6.39.tar.gz’

libpng-1.6.39.tar.gz                                                          100%[++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++====================================================================================================================>]   1.44M  3.71MB/s    in 0.2s

2024-02-12 17:45:33 (3.71 MB/s) - ‘libpng-1.6.39.tar.gz’ saved [1507328/1507328]
```

```bash
$ curl -o test.tar.gz https://storage.googleapis.com/webassembly/emscripten-ports/libpng-1.6.39.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 39 1472k   39  576k    0     0  1317k      0  0:00:01 --:--:--  0:00:01 1318k
curl: (18) transfer closed with 917504 bytes remaining to read
```

**Comment by justinlaughlin** [comment]
sha512 is incorrect with both `curl` and `emcc` because the full file doesn't download. I'm not sure what changed, but when I used to run the build with `emcc` it was actually complaining about the hash being incorrect (although the error it shows now is definitely very related).

**Comment by sbc100** [comment]
Its seems like there much be something wrong your networks connectivity.   Is there anything unusual about your network connection.

Can you download other large files using curl?

**Comment by justinlaughlin** [comment]
I think you are right about it being a network issue. Is there a way you'd recommend patching `emscripten` so that it will use a different URL when trying to install `libpng`?

**Comment by sbc100** [comment]
If you host that file somewhere else you could simple modify the `ports.fetch_project` line in `tools/ports/libpng.py`.
However, that seems like a workaround for a problem that will continue to effect you unless you fix the actual issue with your network.

Do other files download find from google cloud storage. For example can you use curl to download https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/d30afcda66729824a0418c868472bea7e01b02d7/wasm-binaries.tar.xz?

**Comment by justinlaughlin** [comment]
Thank you. I agree it is just a workaround, but this issue is coming from a corporate network which may take a very long time to update. I can use curl to download other files, the problem does seem isolated to libpng. I appreciate your help!

**Comment by sbc100** [comment]
> the problem does seem isolated to libpng

Wow that makes zero sense to me!

**Comment by justinlaughlin** [comment]
You aren't alone in the sentiment (: Thanks again
