### ISSUE TITLE
Cannot convert 1698917542 to a BigInt 

### ISSUE THREAD

**Issue by Alexufo** [emscripten-core/emscripten#21689]
**Version of emscripten/emsdk:**.
3.1.43 to the latest

My application can be successfully run on 3.1.42
But on 3.1.43 ( 3.1.44. 3.1.45) and the latest version I get:

```
wasm.js:3010 Uncaught (in promise) TypeError: Cannot convert "TypeError: Cannot convert 1698917542 to a BigInt" to int
    at checkAssertions (wasm.js:3010:17)
    at Object.toWireType (wasm.js:3024:11)
    at Object.printExceptionMessage (eval at newFunc (wasm.js:2513:27), <anonymous>:7:35)
    at worker.js:320:106
```

I can add sWASM_BIGINT and I can run my app on any version, but I need support for older iPhones.

my config

```
add_link_options(--bind -sWASM -sNO_EXIT_RUNTIME)
add_link_options(--no-entry)
add_link_options(-sMODULARIZE)
add_link_options(-sENVIRONMENT=web,worker)
add_link_options(-sNO_FILESYSTEM)
add_link_options(-sNO_USE_SDL -sNO_USE_SDL_MIXER)
add_link_options(-sALLOW_MEMORY_GROWTH=1)

add_link_options(-sMINIMAL_RUNTIME_STREAMING_WASM_INSTANTIATION=1)
add_link_options(-sDYNAMIC_EXECUTION=1)

add_link_options(-sNO_HTML5_SUPPORT_DEFERRING_USER_SENSITIVE_REQUESTS)
add_link_options(-sNO_ABORT_ON_WASM_EXCEPTIONS)
add_link_options(-sEXPORTED_FUNCTIONS=_malloc,_free)

add_link_options(-sINCOMING_MODULE_JS_API=['locateFile','mainScriptUrlOrBlob'])

add_link_options(-sNO_ERROR_ON_UNDEFINED_SYMBOLS)

add_compile_options(-sSHARED_MEMORY=0)
add_link_options(-sSHARED_MEMORY=0)
add_link_options(-flto)
add_link_options(-sNO_LEGALIZE_JS_FFI)
add_compile_options(-sNO_LEGALIZE_JS_FFI)
```

**Comment by sbc100** [comment]
Can you share your printExceptionMessage function?  What is it trying to do?  It looks like you are trying to call a function that takes an i64.   Do you know which function that is?   

Actaully the i64 looks like the issue.   Do you know why you are passing `-sNO_LEGALIZE_JS_FFI`?  That looks pretty suspicious.   The JS type legalization removes all the i64 from the Wasm/JS boundary.    Can you try removing this flag?

**Comment by Alexufo** [comment]
Yes! Removing NO_LEGALIZE_JS_FFI helped 😁.
