### ISSUE TITLE
mmap throws with "TypeError: Cannot read properties of null (reading 'length')" when mapping empty file

### ISSUE THREAD

**Issue by hly2019** [emscripten-core/emscripten#22202]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
Please include the output `emcc -v` here
3.1.54

Hi, I just met a problem when mapping an empty file with `mmap`: the program throws with `TypeError: Cannot read properties of null (reading 'length')`. 

I do understand it's not a normal operation to map an empty file, but it looks like currently emscripten can't handle it as an abnormal case and throw in JS code, thus it seems a bug. It'd be so appreciated if you could check and fix it. Thank you very much!

### Code

```cpp
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <unistd.h>
#include <sys/stat.h>

int main() {
    const char *filename = "./empty_file"; // an empty file
    int fd = open(filename, O_RDWR);
    if (fd == -1) {
        perror("open");
        exit(1);
    }
    struct stat st;
    if (fstat(fd, &st) == -1) {
        perror("Error getting file size");
        close(fd);
        return 1;
    }
    int filesize = st.st_size;
    printf("file size: %d\n", filesize); // file size is 0

    char *mapped = (char*) mmap(NULL, filesize, PROT_READ, MAP_PRIVATE, fd, 0);
    if (mapped == MAP_FAILED) {
        perror("mmap failed");
        close(fd);
        exit(1);
    } else {
        printf("after mmap, no failure\n");
    }

    close(fd);
    return 0;
}
```

### Compilation

```shell
# compile with emcc
$ emcc mmap_empty.cpp -o main.js --preload-file ./empty_file; node main.js

# compile with gcc
$ g++ mmap_empty.cpp -o main; ./main
```

### Results

```shell
# compile with emcc
file size: 0
/data/main.js:315
      throw ex;
      ^

TypeError: Cannot read properties of null (reading 'length')
    at Object.mmap (/data/main.js:2056:62)
    at Object.mmap (/data/main.js:3445:34)
    at __mmap_js (/data/main.js:4162:20)
    at wasm://wasm/00019aaa:wasm-function[104]:0x5a1f
    at wasm://wasm/00019aaa:wasm-function[24]:0x860
    at wasm://wasm/00019aaa:wasm-function[26]:0x942
    at wasm://wasm/00019aaa:wasm-function[13]:0x50e
    at wasm://wasm/00019aaa:wasm-function[14]:0x5a5
    at /data/main.js:903:12
    at callMain (/data/main.js:4705:15)

Node.js v20.11.0


# compile with gcc
file size: 0
mmap failed: Invalid argument
```

**Comment by hly2019** [comment]
@sbc100  Hi, sorry for bothering you, but if you have time could you please take a look at this? It happens several times to us. Thank you very much!
