### ISSUE TITLE
test_memorygrowth_linear_step is flaky under wasm64

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#22360]
Example: https://app.circleci.com/pipelines/github/emscripten-core/emscripten/36100/workflows/b41023e8-5f9f-48c9-ab5d-364333a838c3/jobs/805855

```
-- begin program output --
0 67108864 64
1 67108864 64
2 67108864 64
3 67108864 64
4 67108864 64
5 67108864 64
6 67108864 64
7 67108864 64
8 67108864 64
9 67108864 64
10 67108864 64
11 67108864 64
12 67108864 64
13 67108864 64
14 67108864 64
15 67108864 64
16 67108864 64
17 67108864 64
18 67108864 64
19 67108864 64
20 67108864 64
21 67108864 64
22 67108864 64
23 67108864 64
24 67108864 64
25 67108864 64
26 67108864 64
27 67108864 64
28 67108864 64
29 67108864 64
30 67108864 64
31 67108864 64
32 67108864 64
33 67108864 64
34 67108864 64
35 67108864 64
36 67108864 64
37 67108864 64
38 67108864 64
39 67108864 64
40 67108864 64
41 67108864 64
42 67108864 64
43 67108864 64
44 67108864 64
45 67108864 64
46 67108864 64
47 67108864 64
48 67108864 64
49 67108864 64
50 67108864 64
51 67108864 64
52 67108864 64
53 67108864 64
54 67108864 64
55 67108864 64
56 67108864 64
57 67108864 64
58 67108864 64
59 67108864 64
60 67108864 64
61 67108864 64
62 67108864 64
memory growth started at 62 68157440 65
63 68157440 65
64 69206016 66
65 70254592 67
66 71303168 68
67 72351744 69
68 73400320 70
69 74448896 71
70 75497472 72
71 76546048 73
72 77594624 74
73 78643200 75
74 79691776 76
75 80740352 77
76 81788928 78
77 82837504 79
78 83886080 80
79 84934656 81
80 85983232 82
81 87031808 83
82 88080384 84
83 89128960 85
84 90177536 86
85 91226112 87
86 92274688 88
87 93323264 89
88 94371840 90
89 95420416 91
90 96468992 92
91 97517568 93
92 98566144 94
93 99614720 95
94 100663296 96
95 101711872 97
96 102760448 98
97 103809024 99
98 104857600 100
99 105906176 101
100 106954752 102
101 108003328 103
102 109051904 104
103 110100480 105
104 111149056 106
105 112197632 107
106 113246208 108
107 114294784 109
108 115343360 110
109 116391936 111
110 117440512 112
111 118489088 113
112 119537664 114
113 120586240 115
114 121634816 116
115 122683392 117
116 123731968 118
117 124780544 119
118 125829120 120
119 126877696 121
120 127926272 122
121 128974848 123
122 130023424 124
123 131072000 125
124 132120576 126
125 133169152 127
126 134217728 128
127 135266304 129
128 136314880 130
failed at 128 136314880 130
grew memory ok.
-- end program output --
test_memorygrowth_linear_step (test_core.wasm64) ... ERROR
```

**Comment by sbc100** [comment]
it looks like the process times out:
```
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.10.7/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/circleci/.pyenv/versions/3.10.7/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/home/circleci/.pyenv/versions/3.10.7/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/circleci/project/test/common.py", line 223, in decorated
    f(self, *args, **kwargs)
  File "/home/circleci/project/test/common.py", line 208, in decorated
    f(self, *args, **kwargs)
  File "/home/circleci/project/test/test_core.py", line 2097, in test_memorygrowth_linear_step
    self.do_core_test('test_memorygrowth_memory_growth_step.c')
  File "/home/circleci/project/test/test_core.py", line 348, in do_core_test
    self.do_run_in_out_file_test(Path('core', testname), **kwargs)
  File "/home/circleci/project/test/common.py", line 1745, in do_run_in_out_file_test
    output = self._build_and_run(srcfile, expected, **kwargs)
  File "/home/circleci/project/test/common.py", line 1783, in _build_and_run
    js_output = self.run_js(js_file, engine, args,
  File "/home/circleci/project/test/common.py", line 1372, in run_js
    raise timeout_error
  File "/home/circleci/project/test/common.py", line 1341, in run_js
    jsrun.run_js(filename, engine, args,
  File "/home/circleci/project/test/jsrun.py", line 102, in run_js
    proc = subprocess.run(
  File "/home/circleci/.pyenv/versions/3.10.7/lib/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/home/circleci/.pyenv/versions/3.10.7/lib/python3.10/subprocess.py", line 1152, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home/circleci/.pyenv/versions/3.10.7/lib/python3.10/subprocess.py", line 2029, in _communicate
    self.wait(timeout=self._remaining_time(endtime))
  File "/home/circleci/.pyenv/versions/3.10.7/lib/python3.10/subprocess.py", line 1207, in wait
    return self._wait(timeout=timeout)
  File "/home/circleci/.pyenv/versions/3.10.7/lib/python3.10/subprocess.py", line 1933, in _wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command '['/home/circleci/node-v22.0.0-v8-canary20240423a2eb2005bd-linux-x64/bin/node', '--stack-trace-limit=50', '--trace-uncaught', '--experimental-wasm-memory64', '/tmp/emtest_6yslc_1k/emscripten_test_wasm64_i63xikgs/test_memorygrowth_memory_growth_step.js']' timed out after 299.9999738319966 seconds
```

**Comment by sbc100** [comment]
When attaching the hung node process I see the following backtrace:

```
Thread 1 "node" received signal SIGINT, Interrupt.
0x00007fa6d4ca01ce in __futex_abstimed_wait_common64 (private=0, cancel=true, 
    abstime=0x0, op=393, expected=0, futex_word=0x38e6d964)
    at ./nptl/futex-internal.c:57
57	in ./nptl/futex-internal.c
(gdb) bt
#0  0x00007fa6d4ca01ce in __futex_abstimed_wait_common64 (private=0, cancel=true, 
    abstime=0x0, op=393, expected=0, futex_word=0x38e6d964)
    at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x38e6d964, 
    expected=expected@entry=0, clockid=clockid@entry=0, 
    abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true)
    at ./nptl/futex-internal.c:87
#2  0x00007fa6d4ca024b in __GI___futex_abstimed_wait_cancelable64 (
    futex_word=futex_word@entry=0x38e6d964, expected=expected@entry=0, 
    clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0)
    at ./nptl/futex-internal.c:139
#3  0x00007fa6d4ca2930 in __pthread_cond_wait_common (abstime=0x0, clockid=0, 
    mutex=0x38e6d8e0, cond=0x38e6d938) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x38e6d938, mutex=0x38e6d8e0)
    at ./nptl/pthread_cond_wait.c:618
#5  0x00000000020ed6b9 in uv_cond_wait (cond=<optimized out>, 
    mutex=<optimized out>) at ../deps/uv/src/unix/thread.c:814
#6  0x00000000011198ab in node::NodePlatform::DrainTasks(v8::Isolate*) ()
#7  0x0000000000f6e652 in node::SpinEventLoopInternal(node::Environment*) ()
#8  0x00000000010dae72 in node::NodeMainInstance::Run() ()
#9  0x0000000001030332 in node::Start(int, char**) ()
#10 0x00007fa6d4c40c8a in __libc_start_call_main (
    main=main@entry=0xf62cf0 <main>, argc=argc@entry=2, 
    argv=argv@entry=0x7ffc160efbf8) at ../sysdeps/nptl/libc_start_call_main.h:58
#11 0x00007fa6d4c40d45 in __libc_start_main_impl (main=0xf62cf0 <main>, argc=2, 
    argv=0x7ffc160efbf8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffc160efbe8)
    at ../csu/libc-start.c:360
```

Trying to `step` or `finish` the  `__futex_abstimed_wait_common64` call never returns so I assume `__futex_abstimed_wait_common64` is blockign forever somehow.

This doesn't seem to be an emscripten issue but some kind of internal node or v8 bug.

**Comment by sbc100** [comment]
I have a workaround for this issue in https://github.com/emscripten-core/emscripten/pull/23301 which solves out immediate problem here on the emscripten side but doesn't address the underlying node/v8 issue.
