### ISSUE TITLE
Support omitting optional arguments in js embind bindings (2)

### ISSUE THREAD

**Issue by i-saint** [emscripten-core/emscripten#22389]
**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.64 (a1fe3902bf73a3802eae0357d273d0e37ea79898)
clang version 19.0.0git (https:/github.com/llvm/llvm-project 4d8e42ea6a89c73f90941fd1b6e899912e31dd34)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /mnt/d/Sources/emsdk/upstream/bin
```

**Issue:**
I thought #21776 solved this issue, but it seems not. It will greatly improve usability in JS side. I would be very grateful if you could address it.

The following simple example doesn't work as expected:
C++ (test.cpp):
```cpp
#include <emscripten.h>
#include <emscripten/bind.h>
#include <optional>
#include <string>

void FuncWithOptional(std::string arg1, std::optional<std::string> arg2)
{
    printf("FuncWithOptional(): %s %s\n", arg1.c_str(), arg2 ? arg2.value().c_str() : "");
}

EMSCRIPTEN_BINDINGS(test)
{
    using namespace emscripten;
    register_optional<std::string>();
    function("FuncWithOptional", &FuncWithOptional);
}
```

compile with ``emcc -std=c++20 -lembind test.cpp -g -o test.js``

HTML & JavaScript:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>tests</title>
  <script src="test.js"></script>
  <script>
    function runTests() {
      Module.FuncWithOptional("abc", "def");
      Module.FuncWithOptional("abc", undefined);
      Module.FuncWithOptional("abc");
    }
  </script>
  <body>
    <div id="app">
      <input type="button" value="test" onclick="runTests()" />
    </div>
  </body>
</html>
```

``Module.FuncWithOptional("abc")`` is expected to work same as ``Module.FuncWithOptional("abc", undefined)``, but causes BindingError.
```
test.js:2329 FuncWithOptional(): abc def
test.js:2329 FuncWithOptional(): abc 
test.js:1166 Uncaught BindingError: function FuncWithOptional called with 1 arguments, expected 2
    at throwBindingError (test.js:1166:48)
    at Object.FuncWithOptional (eval at newFunc (test.js:1431:27), <anonymous>:7:11)
    at runTests (test.html:11:14)
    at HTMLInputElement.onclick (test.html:16:64)
throwBindingError @ test.js:1166
FuncWithOptional @ VM349:7
runTests @ test.html:11
onclick @ test.html:16
```

**Comment by i-saint** [comment]
Thank you so much!
