### ISSUE TITLE
AssertionError: Emscripten failed to generate .js

### ISSUE THREAD

**Issue by bkaradzic** [emscripten-core/emscripten#2259]
On origin/incoming branch I get:

`Traceback (most recent call last):
  File "emsdk_portable/emscripten/github/emscripten.py", line 1433, in <module>
    _main(environ=os.environ)
  File "emsdk_portable/emscripten/github/emscripten.py", line 1421, in _main
    temp_files.run_and_clean(lambda: main(
  File "emsdk_portable/emscripten/github/tools/tempfiles.py", line 39, in run_and_clean
    return func()
  File "emsdk_portable/emscripten/github/emscripten.py", line 1429, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "emsdk_portable/emscripten/github/emscripten.py", line 1316, in main
    jcache=jcache, temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "emsdk_portable/emscripten/github/emscripten.py", line 827, in emscript_fast
    if not metadata['canValidate'] and settings['ASM_JS'] != 2:
KeyError: 'canValidate'
Traceback (most recent call last):
  File "emsdk_portable/emscripten/github/emcc", line 1555, in <module>
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "emsdk_portable/emscripten/github/tools/shared.py", line 1333, in emscripten
    assert os.path.exists(filename + '.o.js') and len(open(filename + '.o.js', 'r').read()) > 0, 'Emscripten failed to generate .js: ' + str(compiler_output)
AssertionError: Emscripten failed to generate .js:`

Command line option:

`emcc -O2 -s TOTAL_MEMORY=268435456 "$(TARGET)" -o "$(TARGET)".html`

This wasn't happening with 1.13.0

**Comment by tatosaurus** [comment]
![cool ass image](http://i.4cdn.org/g/1437867788664.png)
