### ISSUE TITLE
use glue code in vue2.0

### ISSUE THREAD

**Issue by HuangMinming** [emscripten-core/emscripten#22899]
Hi everyone,
I generateed c_pre.js and c_pre.wasm through emcc. I wanted use them in Vue 2.0.
I put c_pre.wasm to public/ directory.
I import c_pre.js like this in my vue code.
```sh
const C_PRE_Module = require('@/api/sgx/c_pre.js')
let c_pre_instance = {
  ready: new Promise(resolve => {
    C_PRE_Module({
      onRuntimeInitialized() {
        c_pre_instance = Object.assign(this, {
          ready: Promise.resolve()
        })
        resolve()
      }
    })
  })
}
```
I call the functions like this
c_pre_instance.ready.then(_ => {
          const pk_Hex = c_pre_instance.allocateUTF8('123')
})
However, there are some mistakes.
```sh
wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
falling back to ArrayBuffer instantiation
failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
c_pre.js:6577  CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
Uncaught (in promise) abort({}) at Error
    at jsStackTrace (http://localhost:8013/2.js:1031:15)
    at stackTrace (http://localhost:8013/2.js:1047:14)
    at abort (http://localhost:8013/2.js:6595:46)
    at http://localhost:8013/2.js:1564:11
```
I check the c_pre.wasm, it started with 3c 21 44 4f. So, I think it was not the wrong file.
I searched in internet, it said the c_pre.wasm is in wrong directory. I tried many different directory, but all failed. what can I do? How to use glue code in Vue 2.0

Thanks.

**Comment by HuangMinming** [comment]
Hi, everyone
I found a solution here [https://stackoverflow.com/questions/66049662/webpack-dev-server-serves-wasm-with-wrong-mime-type](url). Just export js file without wasm file, and it worked.
