### ISSUE TITLE
Emscripten bindings do not work with -sWASM_BIGINT and -sASYNCIFY

### ISSUE THREAD

**Issue by sachit-wp** [emscripten-core/emscripten#22928]
I am unable to successfully run emscripten bindings with WASM_BIGINT and ASYNCIFY
When asyncify is not used, everything works as expected.
For convenience purposes, here's a repo I created for trying this out: https://github.com/sachit-wp/asyncify-repro but I have also provided details below:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.71 (4171ae200b77a6c266b0e1ebb507d61d1ade3501)
clang version 20.0.0git (https:/github.com/llvm/llvm-project d6344c1cd0d099f8d99ee320f33fc9254dbe8288)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /workspaces/asyncify-repro/emsdk/upstream/bin
```

I have a simple program like this:
```cpp
#include <cstdint>
#include <emscripten.h>
#include <emscripten/bind.h>

int64_t getBigInt() {
    return 1000000000000;
}

EMSCRIPTEN_BINDINGS(my_module) {
    emscripten::function("getBigInt", &getBigInt);
}
```

I built it with the following options:
```
-sMODULARIZE -sWASM_BIGINT=1 -lembind -sEXPORT_ES6=1 -sASYNCIFY=1
```

When I attempt to run the following code from nodejs:
```js
import module from "./build/asyncify_bigint.js"
const mymod = await module();
console.log(mymod.getBigInt());
```

I get the error:
```
RuntimeError: null function or function signature mismatch
    at wasm://wasm/0001c73a:wasm-function[98]:0x57be
    at ret.<computed> (file:///workspaces/asyncify-repro/build/asyncify_bigint.js:1679:24)
    at file:///workspaces/asyncify-repro/build/asyncify_bigint.js:649:12
    at dynCallLegacy (file:///workspaces/asyncify-repro/build/asyncify_bigint.js:2028:14)
    at dynCall (file:///workspaces/asyncify-repro/build/asyncify_bigint.js:2045:17)
    at file:///workspaces/asyncify-repro/build/asyncify_bigint.js:2049:27
    at Object.getBigInt (eval at newFunc (file:///workspaces/asyncify-repro/build/asyncify_bigint.js:1447:27), <anonymous>:6:10)
    at file:///workspaces/asyncify-repro/test.js:5:19

Node.js v23.2.0
```

**Comment by sachit-wp** [comment]
Thanks for the quick fix!
