### ISSUE TITLE
After updating to Chrome version, an error occurs: TypeError: Cannot convert 32768 to a BigInt

### ISSUE THREAD

**Issue by Innovgame** [emscripten-core/emscripten#22933]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.59 (0e4c5994eb5b8defd38367a416d0703fd506ad81)
clang version 19.0.0git (https:/github.com/llvm/llvm-project df762a1643bb5b0b3c907611d118c82d4b68a39d)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: D:\lichun\emsdk\upstream\bin

After updating to Chrome version, an error occurs: TypeError: Cannot convert 32768 to a BigInt, The same error also occurs after upgrading the Edge browser. 
chrome version: 131.0.6778.70

vox-web.js:636 Uncaught (in promise) TypeError: Cannot convert 32768 to a BigInt
    at vox-web.js:636:16
    at initVox (vox.ts:19:25)
    at async DesignApplication.initWasm (DesignApplication.ts:50:29)
    at async Promise.all (:3000/index 0)
    at async Design.vue:327:5

![image](https://github.com/user-attachments/assets/1458c6ed-e692-42e4-8a21-8dee37bfb577)

**Comment by brendandahl** [comment]
There have been some recent changes to the memory 64 proposal. You'll probably need the latest version of emscripten and a maybe canary version of chrome. @sbc100 probably knows which versions numbers are compatible with each other.

**Comment by sbc100** [comment]
If you build with the latest version of emscripten (3.1.71) you should see the initial and max memory specified as bigint values not numbers.

```
    /** @suppress {checkTypes} */                                                
    wasmMemory = new WebAssembly.Memory({                                        
      'initial': BigInt(INITIAL_MEMORY / 65536),                                 
      'maximum': BigInt(INITIAL_MEMORY / 65536),                                 
      'shared': true,                                                            
      'address': 'i64',                                                          
      // TODO(sbc): remove this alias for `address` once both firefox and           
      // chrome roll out the spec change.                                        
      // See https://github.com/WebAssembly/memory64/pull/92                     
      'index': 'i64',                                                            
    });                                                                          
  }        
```

**Comment by Innovgame** [comment]
Alright, I will recompile using emscripten (3.1.71). Thank you for your contributions to Wasm64 - I'm looking forward to seeing it available in a stable release soon. @sbc100 @brendandahl
