### ISSUE TITLE
fastcomp does not support dlopen modules

### ISSUE THREAD

**Issue by amatus** [emscripten-core/emscripten#2365]
Instead of an informative message saying this was not supported I got pages and pages of cryptic back-traces when trying to compile a side module. Also nothing popped out at me in the list of open issues. It wasn't until I noticed browser.test_module was disabled for fastcomp that I realized this is a known issue. Is this feature deprecated or is it one of the "very few such features...planned to be rewritten?"

**Comment by dreamlayers** [comment]
With Emscripten 1.29.0, the test [above](https://github.com/kripken/emscripten/issues/2365#issuecomment-44199482) generates a proper error message:

```
AssertionError: Linking modules is not supported in fastcomp
```

However, removing `-s SIDE_MODULE=1` from the command line results in this mess:
```
$ emcc -O2 -s DLOPEN_SUPPORT=1 -s EXPORTED_FUNCTIONS='["_foo"]' test.c                 
Traceback (most recent call last):
  File "/home/bgjenero/gitapps/emsdk_portable/emscripten/master/emscripten.py", line 1656, in <module>
    _main(environ=os.environ)
  File "/home/bgjenero/gitapps/emsdk_portable/emscripten/master/emscripten.py", line 1644, in _main
    temp_files.run_and_clean(lambda: main(
  File "/home/bgjenero/gitapps/emsdk_portable/emscripten/master/tools/tempfiles.py", line 39, in run_and_clean
    return func()
  File "/home/bgjenero/gitapps/emsdk_portable/emscripten/master/emscripten.py", line 1652, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "/home/bgjenero/gitapps/emsdk_portable/emscripten/master/emscripten.py", line 1539, in main
    jcache=jcache, temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "/home/bgjenero/gitapps/emsdk_portable/emscripten/master/emscripten.py", line 1475, in emscript_fast
    for k, v in forwarded_json['Variables']['indexedGlobals'].iteritems():
KeyError: 'Variables'
Traceback (most recent call last):
  File "/home/bgjenero/gitapps/emsdk_portable/emscripten/master/emcc", line 1294, in <module>
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/home/bgjenero/gitapps/emsdk_portable/emscripten/master/tools/shared.py", line 1509, in emscripten
    assert os.path.exists(filename + '.o.js'), 'Emscripten failed to generate .js'
AssertionError: Emscripten failed to generate .js
```

This puzzled me for a bit but I realize I should have looked at the [documentation](https://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#dynamic-linking), where it clearly says "Dynamic linking at runtime is not supported when using Fastcomp".

**Comment by kripken** [comment]
Thanks, I pushed a fix to give a proper error message.
