### ISSUE TITLE
clang not working correctly when installing?

### ISSUE THREAD

**Issue by sinxtanx** [emscripten-core/emscripten#2398]
Hello!
I installed Emscripten because I wanted to build ammo.js myself, but it does not work well. Some things work, like building hello_world.cpp which poses no problem. 
It seems like it's clang that is not working correctly, because running

```
clang tests/hello_world.cpp
```

does not work but

```
emcc tests/hello_world.cpp
```

does work. 

When running

```
python tests/runner.py benchmark
```

results in 14 failures out of 19, all with the same error:

```
Exception: error, no benchmarkers: name 'LLVM_3_2' is not defined
```

Running all tests, a majority pass, but there are still many errors.

Naturally, I can't build ammo.js

```
python make.py

--------------------------------------------------
Building ammo.js, build type: ['-O3', '--llvm-lto', '1', '-s', 'NO_EXIT_RUNTIME=
1', '-s', 'AGGRESSIVE_VARIABLE_ELIMINATION=1', '-s', 'NO_DYNAMIC_EXECUTION=1', '
-s', 'TOTAL_MEMORY=67108864']
--------------------------------------------------


==========================
Stage 1: Generate bindings
==========================

C:/Program Files/Emscripten/python/2.7.5.3_64bit/python.exe: can't open file 'C:
/Program Files/Emscripten/emscripten/1.16.0\tools\webidl_binder.py': [Errno 2] N
o such file or directory
Traceback (most recent call last):
  File "make.py", line 80, in <module>
    assert os.path.exists('glue.js')
AssertionError
```

```
python test.py
Using build: builds\temp.js

===================================

0 : regression tests
      basics.js
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    output = run(fullname)
  File "test.py", line 21, in run
    return Popen(JS_ENGINE + ['-e', 'gcparam("maxBytes", 1024*1024*1024); load("
' + build + '"); load("' + os.path.join('tests', 'testutils.js') + '")', filenam
e], stdout=PIPE).communicate()[0]
TypeError: cannot concatenate 'str' and 'list' objects
```

I have followed the instructions at
https://github.com/kripken/emscripten/wiki/Emscripten-SDK
and
https://github.com/kripken/emscripten/wiki/Tutorial

I am on Windows 7 and I used the emsdk-1.16.0-full-64bit.exe installer.

**Comment by t4r0** [comment]
same here on a Linux Machine
