### ISSUE TITLE
Crash (abort called) when destructing an object

### ISSUE THREAD

**Issue by 4ian** [emscripten-core/emscripten#2778]
Hi,

I'm using emscripten and embind to compile and expose C++ classes to JS. Since the update to the latest version of emscripten (_1.23.0 (commit 33c92f65f9641fac702fe219e35aeb9b62cb748f)_), my tests are failing due to an error. I've extracted a minimal test case: http://compilgames.net/code/emscripten_crash.tar.gz

The archive contains libGD.js, the output of emscripten. test_crash.js reproduce the crash: just launch it with `node test_crash.js`.
The full error stack displayed is:

```
/home/florian/Programmation/GD/WebIDE/test/crash/libGD.js:1
aughtException",(function(ex){if(!(ex instanceof ExitStatus)){throw ex}}))}els
                                                                    ^
abort() at Error
    at jsStackTrace (/home/florian/Programmation/GD/WebIDE/test/crash/libGD.js:1:22730)
    at stackTrace (/home/florian/Programmation/GD/WebIDE/test/crash/libGD.js:1:22913)
    at Object.abort (/home/florian/Programmation/GD/WebIDE/test/crash/libGD.js:62:53346)
    at _abort (/home/florian/Programmation/GD/WebIDE/test/crash/libGD.js:1:634442)
    at E2 (/home/florian/Programmation/GD/WebIDE/test/crash/libGD.js:53:122643)
    at Array.Ey (/home/florian/Programmation/GD/WebIDE/test/crash/libGD.js:37:39227)
    at Array.mJ [as 204] (/home/florian/Programmation/GD/WebIDE/test/crash/libGD.js:5:382880)
    at Array.nu [as 586] (/home/florian/Programmation/GD/WebIDE/test/crash/libGD.js:25:371866)
    at S3 (/home/florian/Programmation/GD/WebIDE/test/crash/libGD.js:53:190719)
    at runDestructor (/home/florian/Programmation/GD/WebIDE/test/crash/libGD.js:1:638347)
```

What is strange is that the code was working well with previous version of emscripten, and I've reproduced the test case directly in a C++ function called test (and called at the beginning in test_crash.js) and it works correctly when called.

The codebase generating the file libGD.js is quite huge so I wasn't able to isolate the problem much better for now, I hope the two files could be sufficient to start doing any debugging, otherwise let me know if you need any information!
(Crash didn't happened with Emscripten 1.16.0, I could do some binary search to find the commits that introduced the bug if needed. But I don't know if it would be useful: when using 1.16.0, I had to rely on the old compiler, by setting `EMCC_FAST_COMPILER` to 0, as the new compiler didn't support asm.js at this time.)

**Comment by 4ian** [comment]
No issues with the latest Emscripten version, closing this (after 5 years ^^)
