### ISSUE TITLE
emmake error: python win32 not valid application

### ISSUE THREAD

**Issue by MicheleFioretto** [emscripten-core/emscripten#3138]
Hi,
I'm trying to compile the sql.js (sqlite) using emscripten (v.27 latest one for windows) but I received this error:
<<
G:>emmake G:\Research\sql.js\Makefile
ERROR root: Exception thrown when invoking Popen in make with args: "G:\Resea
rch\sql.js\Makefile"!
Traceback (most recent call last):
File "G:\Research\emscripten\emscripten\1.25.0\emmake", line 26, in
shared.Building.make(sys.argv[1:])
File "G:\Research\emscripten\emscripten\1.25.0\tools\shared.py", line 1074, in
make process = Popen(args, stdout=stdout, stderr=stderr, env=env)
File "G:\Research\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 711, in __init__errread, errwrite)
File "G:\Research\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 948
, in _execute_child startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application

I'm using win8.1 x64.
Any help?

thanks
Michele

**Comment by kripken** [comment]
Do simpler thinks work with emscripten, compile a single file by itself for example?

**Comment by MicheleFioretto** [comment]
I found this post: https://github.com/kripken/ammo.js/issues/67 it's the same problem of mine . no happy ending. 
I'm trying to compile sqlite to js as you did with sql.js project.
I'll try with linux :-)
thanks
Michele
