### ISSUE TITLE
Sockets test code runs in testrunner but not in standalone browser test.

### ISSUE THREAD

**Issue by nanowizard** [emscripten-core/emscripten#3244]
I noticed that if I compile the socket_echo test code standalone, it works on the latest version of IE and Firefox, but fails on Chrome and Opera. However, when I run the test "python tests/runner.py sockets.test_sockets_echo" invoking Chrome, it works flawlessly. I'm trying to understand the root of this issue, as I would like to leverage this code in another project.

When running the standalone test (outside the test runner), I get an error on the client where the assertion is made to check that data is available on the socket. The error I see on the client is as follows:

Uncaught Assertion failed: available, at: test_sockets_echo_client.c,84,main_loop at Error
    at jsStackTrace (http://localhost:8787/index.js:987:13)
    at stackTrace (http://localhost:8787/index.js:1004:22)
    at ___assert_fail (http://localhost:8787/index.js:4161:210)
    at Array._main_loop (http://localhost:8787/index.js:7307:4)
    at dynCall_v (http://localhost:8787/index.js:10884:30)
    at Object.Runtime.dynCall (http://localhost:8787/index.js:264:39)
    at http://localhost:8787/index.js:4242:21
    at Object.Browser.mainLoop.runIter (http://localhost:8787/index.js:6155:13)
    at Browser_mainLoop_runner (http://localhost:8787/index.js:4238:26)

The server also presents an error:

........\a.out.js:84
      throw ex;
            ^
Assertion failed: errno == EAGAIN, at: ./test_sockets_msg.h,75,do_msg_write at Error
    at jsStackTrace (C:\Users\rsivek\Projects\BBC\bbc-wfd\temp_test_code\echo_test\a.out.js:987:13)
    at stackTrace (C:\Users\rsivek\Projects\BBC\bbc-wfd\temp_test_code\echo_test\a.out.js:1004:22)
    at ___assert_fail (C:\Users\rsivek\Projects\BBC\bbc-wfd\temp_test_code\echo_test\a.out.js:4112:210)
    at _do_msg_write (C:\Users\rsivek\Projects\BBC\bbc-wfd\temp_test_code\echo_test\a.out.js:7127:3)
    at Array._main_loop [as 2](C:UsersrsivekProjectsBBCbbc-wfdtemp_test_codeecho_testa.out.js:7340:10)
    at dynCall_v (C:\Users\rsivek\Projects\BBC\bbc-wfd\temp_test_code\echo_test\a.out.js:10792:30)
    at Object.Runtime.dynCall (C:\Users\rsivek\Projects\BBC\bbc-wfd\temp_test_code\echo_test\a.out.js:264:39)
    at C:\Users\rsivek\Projects\BBC\bbc-wfd\temp_test_code\echo_test\a.out.js:4193:21
    at Object.Browser.mainLoop.runIter (C:\Users\rsivek\Projects\BBC\bbc-wfd\temp_test_code\echo_test\a.out.js:6105:13)
    at Browser_mainLoop_runner [as _onTimeout](C:UsersrsivekProjectsBBCbbc-wfdtemp_test_codeecho_testa.out.js:4189:26)

It appears that the client is somehow closing the connection unexpectedly.

After putting in some print statements in test_sockets_msg.h, I saw "errno: 115" (EINPROGRESS) on the client, and "errno: 107" (ENOTCONN) on the server.

Tested with:
Chrome version 41.0.2272.76 and 43.0.2328.0 canary
Opera version 27.0.1689.76

**Comment by kripken** [comment]
Are you recreating the server setup identically to how the test suite does it? The difference seems like it has to be in there, if it isn't how the testcase is being built in the test suite.

**Comment by nanowizard** [comment]
I haven't been able to completely figure out how the python script is setting up and running the server side javascript (I don't have much python experience myself). I set up a simple http server in the same manner as runner.py, but saw the same results. 

I was able to discover through debug logging the build command being invoked by the test harness:

emcc /tmp/emscripten_test_sockets_nLBNvv/test_sockets_echo_client.c -o test.html -DSOCKK=49163 -DTEST_DGRAM=0 -I/[path to tests]/sockets  (in /tmp/emscripten_test_sockets_nLBNvv)

Building with those exact same parameters doesn't change anything. I still get the same results as above.

Could using a different javascript engine cause this? I've been running my server side code with Node.js. Does the test harness invoke a different engine?

**Comment by kripken** [comment]
There are a few test harnesses, node, native, and python. test_sockets.py
shows that that test uses websockify+native, and node. You can modify the
test harness code to use just one which might be easier for comparisons.

- Alon

**Comment by nanowizard** [comment]
Turns out the issues I was seeing was because I was using the latest version of the "ws" node library (0.7.1 to be exact). Once I changed to the same version being used by the emscripten test suite (v0.4.28), everything works beautifully. Occam's Razor. 

Still, seems odd that this would cause normal behavior in IE and FF, but strange behavior in Chrome and Safari...
