### ISSUE TITLE
Test other.test_stdin fails on Windows.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#3282]
Running the test `other.test_stdin` on Windows fails with

```
======================================================================
ERROR: test_stdin (test_other.other)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "G:\slaves\emcc\win-incoming\build\emscripten\tests\test_other.py", line 1257, in test_stdin
    self.assertContained('abcdef\nghijkl\neof', open('out.txt').read())
  File "G:\slaves\emcc\win-incoming\build\emscripten\tests\runner.py", line 353, in assertContained
    additional_info
Exception: Expected to find 'abcdef
ghijkl
eof' in 'abcdef
ghijkl
error 1

', diff:

--- expected
+++ actual
@@ -1,3 +1,5 @@
 abcdef
 ghijkl
-eof
+error 1
+
+
```

What happens is that instead of receiving `feof`, the C code gets `ferror` raised. Not sure if this is due to a node.js incompatibility, a bug, or some issue in how the Emscripten FS calls to node.js.

**Comment by juj** [comment]
The breakage was caused by https://github.com/kripken/emscripten/commit/6c12786eb019fad30be111daff8c0b858840f838 , more discussion about the issue in the comments of that commit.
