### ISSUE TITLE
RangeError: Source is too large

### ISSUE THREAD

**Issue by ZengruiWang** [emscripten-core/emscripten#3603]
Hi, 
When I ran the ported project on browser, I encountered an exception: RangeError: Source is too large
The complete error stack is:
<b>
exception thrown: RangeError: Source is too large,RangeError: Source is too large
    at Uint8Array.set (native)
    at _emscripten_memcpy_big (http://localhost/smartbodyTest/simplesmartbody.js:8684:9)
    at _memcpy (http://localhost/smartbodyTest/simplesmartbody.js:1229822:31)
    at __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE21__grow_by_and_replaceEjjjjjjPKc (http://localhost/smartbodyTest/simplesmartbody.js:1162791:10)
    at __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6assignEPKcj (http://localhost/smartbodyTest/simplesmartbody.js:1193798:3)
    at Array.__ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEaSERKS5_ (http://localhost/smartbodyTest/simplesmartbody.js:1265268:3)
    at Object.dynCall_iii (http://localhost/smartbodyTest/simplesmartbody.js:1327481:38)
    at invoke_iii (http://localhost/smartbodyTest/simplesmartbody.js:12431:31)
    at Array.__ZN9SmartBody14SBSteerManager5startEv (http://localhost/smartbodyTest/simplesmartbody.js:157085:13)
    at Array.__ZN9SmartBody14SBSteerManager9setEnableEb (http://localhost/smartbodyTest/simplesmartbody.js:1157561:56)Module.printErr @ simplesmartbody.html:1245callMain @ simplesmartbody.js:1340177doRun @ simplesmartbody.js:1340203(anonymous function) @ simplesmartbody.js:1340212

<b>

What is the cause of this exception? I searched online, someone says it may be cause by insufficient memory allocation, and he used TOTAL_MEMORY to solve the problem. But I have already enabled ALLOW_MEMROY_GROUWTH=1.

Thanks!

**Comment by kripken** [comment]
Can you see what the values it is called with are? Perhaps they are beyond the size of memory, in other words, it is trying to copy data that in a native build would segfault?
