### ISSUE TITLE
sourcemapper.js fails for "-O0 -g4" in 1.34.6 (linux)

### ISSUE THREAD

**Issue by dgrechka** [emscripten-core/emscripten#3734]
Hi,

I run compilation with "-O0 -g4 -Werror -s DISABLE_EXCEPTION_CATCHING=0 -s ALLOW_MEMORY_GROWTH=1 -s DEMANGLE_SUPPORT=1 -s ASSERTIONS=2"

on

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.34.6
clang version 3.7.0 
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.0.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Selected multilib: .;@m64

node is v0.12.7
```

[emscripten_temp dir content is here](http://home.dgrechka.net/filestore/for_external/emscripten_temp.tar.gz)

and get the following failure:

```
#
# Fatal error in ../deps/v8/src/handles.h, line 48
# CHECK(location_ != NULL) failed
#

==== C stack trace ===============================

 1: V8_Fatal
 2: v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::String::NewStringType, int)
 3: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding)
 4: node::Buffer::Utf8Slice(v8::FunctionCallbackInfo<v8::Value> const&)
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 6: ??
 7: ??
Traceback (most recent call last):
  File "/home/dmitry/bin/emsdk_portable/emscripten/tag-1.34.6/emcc", line 1802, in <module>
    if debug_level >= 4: generate_source_map(target)
  File "/home/dmitry/bin/emsdk_portable/emscripten/tag-1.34.6/emcc", line 1639, in generate_source_map
    '--offset', str(offset)])
  File "/home/dmitry/bin/emsdk_portable/emscripten/tag-1.34.6/tools/jsrun.py", line 75, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['node', '/home/dmitry/bin/emsdk_portable/emscripten/tag-1.34.6/tools/source-maps/sourcemapper.js', '/tmp/tmpJwbCOE/z3.bc.o.js.pp.js', '--sourceRoot', '/home/dmitry/Repos/z3/build', '--mapFileBaseName', 'z3.js', '--offset', '0'] to finish with return code 0, but it returned with code -4 instead! Output: 
Makefile:3212: recipe for target 'z3.js' failed
make: *** [z3.js] Error 1

```

**Comment by juj** [comment]
This looks like a V8 issue. Can you report it here? https://code.google.com/p/v8/issues/list

**Comment by kripken** [comment]
Worth trying with the latest version of node, might have already been fixed.

**Comment by kripken** [comment]
Oh wait, that is the latest release version. Maybe they have a beta/dev version with newer v8 though.
