### ISSUE TITLE
Can't compile. Got failure to execute js library "library_syscall.js": XXX missing C define AT_FDCWD!

### ISSUE THREAD

**Issue by sikancil** [emscripten-core/emscripten#3962]
OSX El Capitan 10.11.12

``` bash
$ ./emsdk list
The following precompiled tool packages are available for download:
           clang-e1.30.0-64bit      
           clang-e1.34.1-64bit      
     *     clang-e1.35.0-64bit          INSTALLED
     *     node-4.1.1-64bit             INSTALLED
           spidermonkey-37.0.1-64bit
           spidermonkey-nightly-2015-04-12-64bit
           emscripten-1.30.0        
           emscripten-1.34.1        
     *     emscripten-1.35.0            INSTALLED
     *     crunch-1.04                  INSTALLED

The following tools can be compiled from source:
           clang-tag-e1.35.11-32bit 
           clang-tag-e1.35.12-32bit 
           clang-tag-e1.35.11-64bit 
           clang-tag-e1.35.12-64bit 
           clang-incoming-32bit     
           clang-incoming-64bit     
           clang-master-32bit       
           clang-master-64bit       
           emscripten-tag-1.35.11-32bit
           emscripten-tag-1.35.12-32bit
           emscripten-tag-1.35.11-64bit
           emscripten-tag-1.35.12-64bit
           emscripten-incoming-32bit
           emscripten-master-32bit  
           emscripten-incoming-64bit
           emscripten-master-64bit  

The following precompiled SDKs are available for download:
         sdk-1.30.0-64bit         
         sdk-1.34.1-64bit         
    *    sdk-1.35.0-64bit           INSTALLED

The following SDKs can be compiled from source:
         sdk-incoming-64bit       
         sdk-master-64bit

$ clang --version
clang version 3.7.0 (https://github.com/kripken/emscripten-fastcomp-clang dbe68fecd03d6f646bd075963c3cc0e7130e5767) (https://github.com/kripken/emscripten-fastcomp 4e83be90903250ec5142edc57971ed4c633c5e25)
Target: x86_64-apple-darwin15.2.0
Thread model: posix

$ python --version
Python 2.7.10

$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

$ node -v
v4.1.1

$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix

$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix

$ git --version
git version 2.5.4 (Apple Git-61)

$ ./emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.35.0
clang version 3.7.0 (https://github.com/kripken/emscripten-fastcomp-clang dbe68fecd03d6f646bd075963c3cc0e7130e5767) (https://github.com/kripken/emscripten-fastcomp 4e83be90903250ec5142edc57971ed4c633c5e25)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
INFO:root:(Emscripten: Running sanity checks)
```

Now when I compile the basic example **`hello_world.c`** it's always retuning error to **`library_syscall.js`**. Here how I produce it:

``` bash
$ cd ./emsdk_portable/emscripten/1.35.0/
$ ./emcc tests/hello_world.c
error: failure to execute js library "library_syscall.js": XXX missing C define AT_FDCWD!,,
preprocessed source (you can run a js engine on this to get a clearer error message sometimes):
=============
mergeInto(LibraryManager.library, {
  // Performs printf-style formatting.
... and so on.. you know the rest..
=============

Internal compiler error in src/compiler.js! Please raise a bug report at https://github.com/kripken/emscripten/issues/ with a log of the build and the input files used to run. Exception message: "XXX missing C define AT_FDCWD!" | undefined
Traceback (most recent call last):
  File "./emcc", line 1344, in <module>
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/Users/dimasarif/bin/emsdk_portable/emscripten/1.35.0/tools/shared.py", line 1571, in emscripten
    call_emscripten(cmdline)
  File "/Users/dimasarif/bin/emsdk_portable/emscripten/1.35.0/emscripten.py", line 1304, in _main
    temp_files.run_and_clean(lambda: main(
  File "/Users/dimasarif/bin/emsdk_portable/emscripten/1.35.0/tools/tempfiles.py", line 64, in run_and_clean
    return func()
  File "/Users/dimasarif/bin/emsdk_portable/emscripten/1.35.0/emscripten.py", line 1310, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "/Users/dimasarif/bin/emsdk_portable/emscripten/1.35.0/emscripten.py", line 1208, in main
    temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "/Users/dimasarif/bin/emsdk_portable/emscripten/1.35.0/emscripten.py", line 201, in emscript
    cwd=path_from_root('src'), error_limit=300)
  File "/Users/dimasarif/bin/emsdk_portable/emscripten/1.35.0/tools/jsrun.py", line 75, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['/Users/dimasarif/bin/emsdk_portable/node/4.1.1_64bit/bin/node', '/Users/dimasarif/bin/emsdk_portable/emscripten/1.35.0/src/compiler.js', '/var/folders/z9/pbr2f8ts4hgdgwzwsylvbrbw0000gn/T/tmp88Uxhp.txt', '/Users/dimasarif/bin/emsdk_portable/emscripten/1.35.0/src/library_pthread_stub.js'] to finish with return code 0, but it returned with code 1 instead! Output: // The Module object: Our interface to the outside world. We import
// and export values on it, and do the work to get that through
// closure compiler if necessary. There are various ways Module can be used:
// 1. Not defined. We create it here
// 2. A function parameter, function(Module) { ..gener
```

Did I missed something.. How to fix it?
Thanks

**Comment by kripken** [comment]
Try `emcc --clear-cache`. If that doesn't help, then it might be failing to generate some system info, which it does automatically if it isn't in the cache already (so clearing the cache forces a rebuild next time emcc is run).

**Comment by sikancil** [comment]
After cache cleared by ```./emcc --clear-cache```,
I tried again to call ```./emcc tests/hello_world.c```, seems it's not solved the problem, the same error still appear.
Please describes more with some clue about your statement..
> it might be failing to generate some system info, which it does automatically if it isn't in the cache already

**Comment by kripken** [comment]
Does `emcc -v` show any warnings or errors?

Otherwise, please provide the output of `EMCC_DEBUG=1` in the env when running right after clearing the cache.
