### ISSUE TITLE
Python HTTP server exceptions when running the test suite

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#4084]
Running locally on Windows, I'm seeing the following kind of exceptions being spammed:

```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 50251)
Traceback (most recent call last):
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\SocketServer.py", line 651, in __init__
    self.finish()
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\SocketServer.py", line 710, in finish
    self.wfile.close()
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\socket.py", line 279, in close
    self.flush()
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
```

which don't seem to affect the test runs, so not a big issue, but I can't recall these coming up before. These look like Firefox is closing the localhost sockets on the server in a non-benign manner(?). Will have to investigate this at some point when I've got more time, just noting down to self about it. I wonder if this is Windows only?

**Comment by kripken** [comment]
Not windows-only, I see it too.

Maybe an issue with the python webserver? Maybe if we used node it would be better.

**Comment by omkarkhair** [comment]
I'm facing the same issue on windows. Is there a resolution yet?
