### ISSUE TITLE
Error in llvm::sys::RunSignalHandlers() on CentOS 7

### ISSUE THREAD

**Issue by derekmooney** [emscripten-core/emscripten#4377]
I'm trying to get my project compiling on CentOS 7 with 1.36.5, and the llvm optimizations are failing on our unit test build. It's interesting because the primary build runs just fine - is it limited to situations with re-including the primary bytecode into the unit test build?

Anyway, the error is:

``` bash
DEBUG:root:(not saving intermediate /tmp/emscripten_temp/emcc-0-basebc.bc because deferring linking)
DEBUG:root:emcc: LLVM opts: -strip-debug -disable-verify -internalize -internalize-public-api-list=main,malloc,free,__errno_location,fflush,__cxa_can_catch,__cxa_is_pointer_type,malloc,free,malloc,free -globaldce -disable-loop-vectorization -disable-slp-vectorization -vectorize-loops=false -vectorize-slp=false -vectorize-slp-aggressive=false  [num inputs: 1]
#0 0x0000000000ed5275 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/apollobuild1-1/emsdk_portable/clang/tag-e1.36.5/src/lib/Support/Unix/Signals.inc:323:0
#1 0x0000000000ed34c6 llvm::sys::RunSignalHandlers() /home/apollobuild1-1/emsdk_portable/clang/tag-e1.36.5/src/lib/Support/Signals.cpp:45:0
#2 0x0000000000ed361b SignalHandler(int) /home/apollobuild1-1/emsdk_portable/clang/tag-e1.36.5/src/lib/Support/Unix/Signals.inc:200:0
#3 0x00007f01756c1100 __restore_rt (/lib64/libpthread.so.0+0xf100)
#4 0x0000000000c206a7 dyn_cast<llvm::DISubprogram, llvm::DIScope> /home/apollobuild1-1/emsdk_portable/clang/tag-e1.36.5/src/include/llvm/Support/Casting.h:298:0
#5 0x0000000000c206a7 findNeededSubprograms /home/apollobuild1-1/emsdk_portable/clang/tag-e1.36.5/src/lib/Linker/IRMover.cpp:1233:0
#6 0x0000000000c206a7 linkNamedMDNodes /home/apollobuild1-1/emsdk_portable/clang/tag-e1.36.5/src/lib/Linker/IRMover.cpp:1290:0
#7 0x0000000000c206a7 run /home/apollobuild1-1/emsdk_portable/clang/tag-e1.36.5/src/lib/Linker/IRMover.cpp:1561:0
#8 0x0000000000c206a7 llvm::IRMover::move(llvm::Module&, llvm::ArrayRef<llvm::GlobalValue*>, std::function<void (llvm::GlobalValue&, std::function<void (llvm::GlobalValue&)>)>, llvm::DenseMap<unsigned int, llvm::MDNode*, llvm::DenseMapInfo<unsigned int>, llvm::detail::DenseMapPair<unsigned int, llvm::MDNode*> >*, bool) /home/apollobuild1-1/emsdk_portable/clang/tag-e1.36.5/src/lib/Linker/IRMover.cpp:1695:0
#9 0x0000000000c272ca ~_Function_base /usr/include/c++/4.8.2/functional:2029:0
#10 0x0000000000c272ca ~function /usr/include/c++/4.8.2/functional:2174:0
#11 0x0000000000c272ca (anonymous namespace)::ModuleLinker::run() /home/apollobuild1-1/emsdk_portable/clang/tag-e1.36.5/src/lib/Linker/LinkModules.cpp:813:0
#12 0x0000000000c27ee2 llvm::Linker::linkInModule(std::unique_ptr<llvm::Module, std::default_delete<llvm::Module> >, unsigned int, llvm::FunctionInfoIndex const*, llvm::DenseSet<llvm::GlobalValue const*, llvm::DenseMapInfo<llvm::GlobalValue const*> >*, llvm::DenseMap<unsigned int, llvm::MDNode*, llvm::DenseMapInfo<unsigned int>, llvm::detail::DenseMapPair<unsigned int, llvm::MDNode*> >*) /home/apollobuild1-1/emsdk_portable/clang/tag-e1.36.5/src/include/llvm/ADT/DenseMap.h:381:0
#13 0x0000000000565f23 ~unique_ptr /usr/include/c++/4.8.2/bits/unique_ptr.h:183:0
#14 0x0000000000565f23 main /home/apollobuild1-1/emsdk_portable/clang/tag-e1.36.5/src/tools/opt/opt.cpp:379:0
#15 0x00007f0174af1b15 __libc_start_main (/lib64/libc.so.6+0x21b15)
#16 0x000000000058db65 _start (/home/apollobuild1-1/emsdk_portable/clang/tag-e1.36.5/build_tag-e1.36.5_64/bin/opt+0x58db65)
Stack dump:
0.  Program arguments: /home/apollobuild1-1/emsdk_portable/clang/tag-e1.36.5/build_tag-e1.36.5_64/bin/opt @/tmp/emscripten_temp/tmpWOFPz9.response -strip-debug -disable-verify -internalize -internalize-public-api-list=main,malloc,free,__errno_location,fflush,__cxa_can_catch,__cxa_is_pointer_type,malloc,free,malloc,free -globaldce -disable-loop-vectorization -disable-slp-vectorization -vectorize-loops=false -vectorize-slp=false -vectorize-slp-aggressive=false -o /tmp/tmpqUm0qq/UnitTests.bc 
Traceback (most recent call last):
  File "/home/apollobuild1-1/emsdk_portable/emscripten/tag-1.36.5/em++", line 13, in <module>
    emcc.run()
  File "/home/apollobuild1-1/emsdk_portable/emscripten/tag-1.36.5/emcc.py", line 1447, in run
    final = shared.Building.llvm_opt(final, link_opts, DEFAULT_FINAL)
  File "/home/apollobuild1-1/emsdk_portable/emscripten/tag-1.36.5/tools/shared.py", line 1585, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations: 
make: *** [build/UnitTests.js] Error 1
```

I've tried setting the optimizations to -O0 with no luck. I'm a bit stumped at this point. Any suggestions?

**Comment by kripken** [comment]
Looks like it might be an LLVM linking bug of some sort. Worth trying to reproduce with upstream LLVM.

**Comment by derekmooney** [comment]
Weird, though, because it works with the same emscripten toolset on OS X for me (on the same code, same makefiles, etc). Like it's something about one of the other toolsets I used on CentOS? I had to compile/install CMake 2.8.12 manually (only 2.8.11 is available via yum) and I used OpenJDK 1.8, but otherwise everything stock CentOS.

Is there anything I can do to try this out on upstream LLVM? I did some poking but I'm probably not quite qualified to work that out.

**Comment by derekmooney** [comment]
I tried with clang-incoming-64bit / emscripten-incoming-64bit with the same results.

**Comment by kripken** [comment]
Yeah, to test with upstream LLVM you would basically build latest LLVM, then run that same command on those bitcode files,

````
LLVM opts: -strip-debug -disable-verify -internalize -internalize-public-api-list=main,malloc,free,__errno_location,fflush,__cxa_can_catch,__cxa_is_pointer_type,malloc,free,malloc,free -globaldce -disable-loop-vectorization -disable-slp-vectorization -vectorize-loops=false -vectorize-slp=false -vectorize-slp-aggressive=false
````

Something like `opt` with those parameters should work. You may get warnings on the triple being wrong, but can ignore those. If it errors on something irrelevant, then you might need to build the bitcode files using upstream LLVM as well.

Or, you can use emcc with upstream LLVM. It will automatically use the wasm target in that case.
