### ISSUE TITLE
Test sanity.test_emcc fails if run after clearing cache.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#4415]
Running

```
emcc --clear-cache
emcc tests/runner.py sanity.test_mcc
```

fails with the error 

```
Jukkas-MacBook-Pro:incoming jjylanki$ emcc --clear-cache
WARNING:root:generating system asset: is_vanilla.txt...
WARNING:root:                                          ok
INFO:root:(Emscripten: Running sanity checks)
WARNING:root:clearing cache
INFO:root:(Emscripten: Running sanity checks)
Jukkas-MacBook-Pro:incoming jjylanki$ python tests/runner.py sanity.test_emcc
WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage

Running sanity checks.
WARNING: This will modify /Users/jjylanki/.emscripten, and in theory can break it although it should be restored properly. A backup will be saved in /Users/jjylanki/.emscripten_backup

test_emcc (test_sanity.sanity) ... ERROR

======================================================================
ERROR: test_emcc (test_sanity.sanity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jjylanki/emsdk_git/emscripten/incoming/tests/test_sanity.py", line 353, in test_emcc
    self.assertNotContained(SANITY_MESSAGE, output)
  File "/Users/jjylanki/emsdk_git/emscripten/incoming/tests/runner.py", line 470, in assertNotContained
    limit_size(''.join([a.rstrip()+'\n' for a in difflib.unified_diff(value.split('\n'), string.split('\n'), fromfile='expected', tofile='actual')]))
Exception: Expected to NOT find 'Emscripten: Running sanity checks' in 'WARNING:root:(Emscripten: settings file has changed, clearing cache)
INFO:root:(Emscripten: Running sanity checks)
WARNING:root:no input files
', diff:

--- expected
+++ actual
@@ -1 +1,4 @@
-Emscripten: Running sanity checks
+WARNING:root:(Emscripten: settings file has changed, clearing cache)
+INFO:root:(Emscripten: Running sanity checks)
+WARNING:root:no input files
+


----------------------------------------------------------------------
Ran 1 test in 0.698s

FAILED (errors=1)
```

I wonder if this is intended that the test is not run alone? Rerunning the test a second time succeeds.

**Comment by kripken** [comment]
The test should run standalone, so that sounds like a bug. However, I can't reproduce it: clearing the cache and then running that test passes for me.

Perhaps a timing issue? That line checks that if the sanity file is newer, we don't run sanity checks. First thing I would check is that altering the `>=` on line 347 to be `>` still passes. If not it might point to the problem.

**Comment by kripken** [comment]
I pushed the `>` change together with a timing adjustment. Might help, but doubtful. Maybe it can point to the problem though if you still see the error.
