### ISSUE TITLE
test_webidl failure on OS X

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#4505]
Getting this when running on OS X - not sure if this has always been there on this OS X machine or if something has changed recently:

```
Jukkas-MacBook-Pro:incoming jjylanki$ python tests/runner.py browser.test_webidl
WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
Test suites:
['test_browser']
Running test_browser: (1 tests)
[Browser harness server on process 70813]

Running the browser tests. Make sure the browser allows popups from localhost.

test_webidl (test_browser.browser) ... Traceback (most recent call last):
  File "/Users/jjylanki/emsdk_git/emscripten/incoming/tools/webidl_binder.py", line 42, in <module>
    p = WebIDL.Parser()
  File "/Users/jjylanki/emsdk_git/emscripten/incoming/third_party/WebIDL.py", line 4919, in __init__
    picklefile='WebIDLGrammar.pkl')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ply-3.6-py2.7.egg/ply/yacc.py", line 3242, in yacc
    read_signature = lr.read_pickle(picklefile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ply-3.6-py2.7.egg/ply/yacc.py", line 1986, in read_pickle
    in_f = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: 'WebIDLGrammar.pkl'
FAIL
[Browser harness server terminated]

======================================================================
FAIL: test_webidl (test_browser.browser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jjylanki/emsdk_git/emscripten/incoming/tests/test_browser.py", line 2730, in test_webidl
    assert os.path.exists('glue.cpp')
AssertionError

----------------------------------------------------------------------
Ran 1 test in 0.247s

FAILED (failures=1)
```

**Comment by kripken** [comment]
Looks os x specific, I can't reproduce on linux.
