### ISSUE TITLE
Python fails to pickle WebsockifyServerHarness on Windows

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#4585]
After https://github.com/kripken/emscripten/commit/86ebeec8abbe436829005b93ffdf90ee50c3727b, Windows is able to run a few more sockets tests. However any tests that use `WebsockifyServerHarness` fail due to Python inconsistencies in its pickling behavior across operating systems (a discrepancy which causes most of our cross platform multiprocessing bugs).

Removing the `if not WINDOWS:` blocks e.g. on `sockets.test_nodejs_sockets_echo` will give the following error when python tries to spawn a new process to run websockify:

```
======================================================================
ERROR: test_nodejs_sockets_echo (test_sockets.sockets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\code\emsdk\emscripten\incoming\tests\test_sockets.py", line 590, in test_nodejs_sockets_echo
    with harness:
  File "C:\code\emsdk\emscripten\incoming\tests\test_sockets.py", line 59, in __enter__
    self.websockify.start()
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 419, in save_reduce
    save(state)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\multiprocessing\forking.py", line 67, in dispatcher
    self.save_reduce(obj=obj, *rv)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 401, in save_reduce
    save(args)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 548, in save_tuple
    save(element)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 419, in save_reduce
    save(state)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 419, in save_reduce
    save(state)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 419, in save_reduce
    save(state)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 600, in save_list
    self._batch_appends(iter(obj))
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 636, in _batch_appends
    save(tmp[0])
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 419, in save_reduce
    save(state)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 419, in save_reduce
    save(state)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 396, in save_reduce
    save(cls)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 748, in save_global
    (obj, module, name))
PicklingError: Can't pickle <type 'thread.lock'>: it's not found as thread.lock

FAILED (errors=1)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\multiprocessing\forking.py", line 381, in main
    self = load(from_parent)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 858, in load

    C:\code\emsdk\emscripten\incoming>dispatch[key](self)
  File "C:\code\emsdk\python\2.7.5.3_64bit\lib\pickle.py", line 880, in load_eof
    raise EOFError
EOFError
```

but I'm not quite sure how to proceed to fix this. Perhaps an appropriately placed `import thread` might fix the issue, but couldn't make that fly after some tinkering around on the third-party WebSockify codebase that we use.

**Comment by kripken** [comment]
Interesting. Too bad that this stuff doesn't just work.

I'd say let's just disable websockify-using tests on windows? It's not very important.

**Comment by juj** [comment]
All the websockify portions of the sockets tests are skipped on Windows as part of the above commit. I expect that Windows should pass on the `sockets` suite now in incoming.
