### ISSUE TITLE
abort() at error for node a.out.js

### ISSUE THREAD

**Issue by sampsh** [emscripten-core/emscripten#4757]
Hello,
I ran `emcc -O2 -s ASSERTIONS=1 -s TOTAL_MEMORY=50331648 code/src/process/program/progam1.cpp code/src/process/program/program2.cpp code/src/process/program/program3.c --embed-file code/src/process/program/datafiles`
Then, `node a.out.js inputfile1 inputfile2` and I'm receiving the following:

`Reading files:`
`file 1 finished reading`
`file 2 finished reading`
`size of file1: 72`
`size of file2: 144`
`C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(typeof Module==="undefined")Module={};if(!Module.expectedDataFileDownloads){Module.expectedDataFileDownloads=0;Module.finishedDataFileDownloads=0}Module.expectedDataFileDownloads++;((function(){var loadPackage=(function(metadata){function runWithFS(){function assert(check,msg){if(!check)throw msg+(new Error).stack}Module["FS_createPath"]("/","code",true,true);Module["FS_createPath"]("/code","src",true,true);Module["FS_createPath"]("/code/src","process",true,true);Module["FS_createPath"]("/code/src/process","program",true,true);Module["FS_createPath"]("/code/src/process/program","datafiles",true,true);var fileData0=[];fileData0.push.apply(fileData0,[52,48,99,51,55,50,52,100,51,97,57,98,53,51,98,55,32,52,49,48,101,102,99,99,98,53,53,102,49,100,51,49,56,32,52,48,100,51,100,57,102,101,51,50,49,`
`abort() at Error`
`    at jsStackTrace (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:1:30004)`
`    at stackTrace (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:1:30187)`
`    at Object.abort (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:15:34443)`
`    at _abort (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:1:120626)`
`    at If (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:7:60623)`
`    at pe (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:5:111683)`
`    at qd (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:5:58010)`
`    at Kc (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:5:11451)`
`    at Object.asm._main (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:15:1004)`
`    at Object.callMain (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:15:32183)`

What is the meaning of this error? I'm completely lost.

**Comment by kripken** [comment]
The stack trace in a non-optimized build (without `-O2`) should be a lot clearer.

**Comment by sampsh** [comment]
Still getting the following error without `-O2`

C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:133
      throw ex;
      ^
abort() at Error
    at jsStackTrace (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:1209:13)
    at stackTrace (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:1226:22)
    at Object.abort (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:126280:44)
    at _abort (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:6414:22)
    at _free (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:77579:3)
    at __ZdlPv [operator delete(void*)] (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:36264:2)
    at Array.__Z17overlayPlaneSweepPK11halfsegmentiS1_iRNSt3__16vectorIS_NS2_9allocatorIS_EEEE [overlayPlaneSweep(halfsegment const*, int, halfsegment const*, int, std::__1::vector<halfsegment, std::__1::allocator<halfsegment> >&)] (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:24530:11)
    at Object.dynCall_viiiii (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:123420:35)
    at invoke_viiiii (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:7452:29)
    at _main (C:\Program Files\Emscripten\emscripten\1.34.1\a.out.js:11793:38)

**Comment by kripken** [comment]
An abort inside free is typically due to memory corruption or some other bug like a double-free. You can add a print in each malloc and free to track those. The `SAFE_HEAP` option might also help with some possible causes.

**Comment by sampsh** [comment]
Thank you!! I got the memory corruption fixed. I'm getting a different error now. I'm running 
`./emcc -O2 -s TOTAL_MEMORY=80000000 program1.cpp program2.cpp program3.c --embed-file data/`

This is the error: 
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Traceback (most recent call last):
  File "./emcc", line 13, in <module>
    emcc.run()
  File "/home/user/emscripten/emsdk_portable/emscripten/master/emcc.py", line 1668, in run
    JSOptimizer.flush()
  File "/home/user/emscripten/emsdk_portable/emscripten/master/emcc.py", line 1570, in flush
    run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "/home/user/emscripten/emsdk_portable/emscripten/master/emcc.py", line 1543, in run_passes
    final = shared.Building.js_optimizer(final, passes, debug_level >= 4, JSOptimizer.extra_info, just_split=just_split, just_concat=just_concat)
  File "/home/user/emscripten/emsdk_portable/emscripten/master/tools/shared.py", line 1651, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "/home/user/emscripten/emsdk_portable/emscripten/master/tools/js_optimizer.py", line 538, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/home/user/emscripten/emsdk_portable/emscripten/master/tools/tempfiles.py", line 64, in run_and_clean
    return func()
  File "/home/user/emscripten/emsdk_portable/emscripten/master/tools/js_optimizer.py", line 538, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/home/user/emscripten/emsdk_portable/emscripten/master/tools/js_optimizer.py", line 483, in run_on_js
    assert proc.returncode == 0
AssertionError

How can this be fixed?

**Comment by kripken** [comment]
The error says it's running out of memory. One way to reduce the memory used is to not use multiple cores, which is slower, use `EMCC_CORES=1` in the env.
