### ISSUE TITLE
tests/runner.py benchmark fails on incoming branch

### ISSUE THREAD

**Issue by rahulchaphalkar** [emscripten-core/emscripten#4781]
I updated emscripten with `emsdk update`, then installed and activated `sdk-incoming-64bit` on windows. No errors while installing/activating. When i run `python tests\runner.py benchmark`, it fails with errors: (I've turned on EMCC_DEBUG)
```
C:\Program Files\Emscripten\emscripten\incoming>python tests\runner.py benchmark
DEBUG:root:Cache: acquiring multiprocess file lock to Emscripten cache
DEBUG:root:Cache: done
INFO:root:generating system asset: is_vanilla.txt... (this will be cached in "C:\Users\rschapha\.emscripten_cache\is_vanilla.txt" for subsequent builds)
DEBUG:root:Cache: acquiring multiprocess file lock to Emscripten cache
DEBUG:root:Cache: done
DEBUG:root:Cache: released multiprocess file lock to Emscripten cache
DEBUG:root:testing for asm.js target, because if not present (i.e. this is plain vanilla llvm, not emscripten fastcomp), we will use the wasm target instead (set EMCC_WASM_BACKEND to skip this check)
INFO:root: - ok
DEBUG:root:Cache: released multiprocess file lock to Emscripten cache
DEBUG:root:check tells us to use asm.js backend
WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
DEBUG:root:Checking JS engine ['C:/Program Files/Emscripten/node/4.1.1_64bit/bin/node']
Test suites:
['test_benchmark']
Running test_benchmark: (20 tests)
Running Emscripten benchmarks... [ including compilation | Wed Dec 07 12:06:44 2016 | em: commit 0efac40f87a8028dda26e467e2f19ed12822c84f | llvm: C:/Program Files/Emscripten/clang/fastcomp/build_incoming_vs2015_64/RelWithDebInfo/bin ]
test_conditionals (test_benchmark.benchmark) ...
Building native executable with command failed C:/Program Files/Emscripten/clang/fastcomp/build_incoming_vs2015_64/RelWithDebInfo/bin\clang++ -fno-math-errno c:/users/rschapha/appdata/local/temp\emscripten_temp\conditionals.cpp -o c:/users/rschapha/appdata/local/temp\emscripten_temp\conditionals.cpp.native -O2
Output: c:/users/rschapha/appdata/local/temp\emscripten_temp\conditionals.cpp:2:16: fatal error: 'stdio.h' file not found
      #include <stdio.h>
               ^
1 error generated.

None
ERROR
test_copy (test_benchmark.benchmark) ...
Building native executable with command failed C:/Program Files/Emscripten/clang/fastcomp/build_incoming_vs2015_64/RelWithDebInfo/bin\clang++ -fno-math-errno c:/users/rschapha/appdata/local/temp\emscripten_temp\copy.cpp -o c:/users/rschapha/appdata/local/temp\emscripten_temp\copy.cpp.native -O2
Output: c:/users/rschapha/appdata/local/temp\emscripten_temp\copy.cpp:2:16: fatal error: 'stdio.h' file not found
      #include <stdio.h>
               ^
1 error generated.

None
ERROR
test_corrections (test_benchmark.benchmark) ...
Building native executable with command failed C:/Program Files/Emscripten/clang/fastcomp/build_incoming_vs2015_64/RelWithDebInfo/bin\clang++ -fno-math-errno c:/users/rschapha/appdata/local/temp\emscripten_temp\corrections.cpp -o c:/users/rschapha/appdata/local/temp\emscripten_temp\corrections.cpp.native -O2
Output: c:/users/rschapha/appdata/local/temp\emscripten_temp\corrections.cpp:2:16: fatal error: 'stdio.h' file not found
      #include <stdio.h>
               ^
1 error generated.
.
.
.
```
similarly for other benchmarks. In the end it displays:
```
======================================================================
ERROR: test_conditionals (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\incoming\tests\test_benchmark.py", line 443, in test_conditionals
    self.do_benchmark('conditionals', src, 'ok', reps=TEST_REPS*5)
  File "C:\Program Files\Emscripten\emscripten\incoming\tests\test_benchmark.py", line 194, in do_benchmark
    b.build(self, filename, args, shared_args, emcc_args, native_args, native_exec, lib_builder, has_output_parser=output_parser is not None)
  File "C:\Program Files\Emscripten\emscripten\incoming\tests\test_benchmark.py", line 82, in build
    shutil.move(filename + '.native', final)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\shutil.py", line 301, in move
    copy2(src, real_dst)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'c:/users/rschapha/appdata/local/temp\\emscripten_temp\\conditionals.cpp.native'

======================================================================
ERROR: test_copy (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\incoming\tests\test_benchmark.py", line 362, in test_copy
    self.do_benchmark('copy', src, 'sum:')
  File "C:\Program Files\Emscripten\emscripten\incoming\tests\test_benchmark.py", line 194, in do_benchmark
    b.build(self, filename, args, shared_args, emcc_args, native_args, native_exec, lib_builder, has_output_parser=output_parser is not None)
  File "C:\Program Files\Emscripten\emscripten\incoming\tests\test_benchmark.py", line 82, in build
    shutil.move(filename + '.native', final)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\shutil.py", line 301, in move
    copy2(src, real_dst)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'c:/users/rschapha/appdata/local/temp\\emscripten_temp\\copy.cpp.native'
.
.
.
```
etc for others too, with
```
Ran 20 tests in 4.912s

FAILED (errors=15)
```
Any insights?

**Comment by juj** [comment]
Running the `benchmark` suite on Windows has historically required running it inside the Visual Studio Command Prompt, but since some months ago, we have the machinery available to not need it. Posted PR #4782 to fix this, after which the `benchmark` suite has more success on my Windows system as well.

**Comment by juj** [comment]
After the PR, Visual Studio installation is still required (or Windows SDK at least I think), because Clang uses native Visual Studio headers when building on Windows.

**Comment by rahulchaphalkar** [comment]
Thanks for the prompt response. I'll try out both the approaches which you suggested including the PR.

**Comment by dschuff** [comment]
Also note that the benchmark build tries to build a native (windows)
version of the benchmarks as well as emscripten builds. This is what causes
the dependence on system/winSDK headers. If you just want to run the
emscripten version I think you can disable the native version by commenting
out any `NativeBenchmarker`s in `tests/test_benchmark.py`.
