### ISSUE TITLE
Fails to optimize with Closure Compiler v20160208 and newer

### ISSUE THREAD

**Issue by jirutka** [emscripten-core/emscripten#5109]
When I run `emcc --closure 1` with Closure Compiler v20170218 (or any older up to v20160208), it prints many warning and two errors (at the bottom of the output). The problematic code is from `src/postamble.js`.

It works fine when I declare `EMCC_CLOSURE_ARGS="--language_in=ECMASCRIPT6"` – no warnings or errors reported.

```
$ ./emcc -Os --closure 1 -o hello_world.js tests/hello_world.c
Traceback (most recent call last):
  File "./emcc", line 13, in <module>
    emcc.run()
  File "/home/jirutjak/aports/testing/emscripten/src/emscripten-1.37.9/emcc.py", line 1981, in run
    JSOptimizer.flush()
  File "/home/jirutjak/aports/testing/emscripten/src/emscripten-1.37.9/emcc.py", line 1876, in flush
    run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "/home/jirutjak/aports/testing/emscripten/src/emscripten-1.37.9/emcc.py", line 1849, in run_passes
    final = shared.Building.js_optimizer(final, passes, debug_level >= 4, JSOptimizer.extra_info, just_split=just_split, just_concat=just_concat)
  File "/home/jirutjak/aports/testing/emscripten/src/emscripten-1.37.9/tools/shared.py", line 2052, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "/home/jirutjak/aports/testing/emscripten/src/emscripten-1.37.9/tools/js_optimizer.py", line 563, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/home/jirutjak/aports/testing/emscripten/src/emscripten-1.37.9/tools/tempfiles.py", line 78, in run_and_clean
    return func()
  File "/home/jirutjak/aports/testing/emscripten/src/emscripten-1.37.9/tools/js_optimizer.py", line 563, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/home/jirutjak/aports/testing/emscripten/src/emscripten-1.37.9/tools/js_optimizer.py", line 494, in run_on_js
    cld = shared.Building.closure_compiler(cld, pretty='minifyWhitespace' not in passes)
  File "/home/jirutjak/aports/testing/emscripten/src/emscripten-1.37.9/tools/shared.py", line 2164, in closure_compiler
    raise Exception('closure compiler error: ' + cc_output + ' (rc: %d)' % process.returncode)
Exception: closure compiler error: /home/jirutjak/aports/testing/emscripten/src/emscripten-1.37.9/src/closure-externs.js:120: WARNING - variable window.Gamepad redefined with type None, original definition at externs.zip//w3c_gamepad.js:37 with type function (this:Gamepad): ?
var Gamepad;
    ^^^^^^^

/home/jirutjak/aports/testing/emscripten/src/emscripten-1.37.9/src/closure-externs.js:150: WARNING - assignment to property getGamepads of Navigator
found   : function (): (Array<{
  axes: (Array<number>|null),
  buttons: (Array<number>|null),
  id: string,
  index: number,
  timestamp: number
}>|null)
required: function (): Array<Gamepad>
navigator.getGamepads = function() {};
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/jirutjak/aports/testing/emscripten/src/emscripten-1.37.9/src/closure-externs.js:150: WARNING - variable navigator.getGamepads redefined with type function (): (Array<{
  axes: (Array<number>|null),
  buttons: (Array<number>|null),
  id: string,
  index: number,
  timestamp: number
}>|null), original definition at externs.zip//w3c_gamepad.js:26 with type function (): Array<Gamepad>
navigator.getGamepads = function() {};
^^^^^^^^^^^^^^^^^^^^^

/home/jirutjak/aports/testing/emscripten/src/emscripten-1.37.9/src/closure-externs.js:155: WARNING - assignment to property webkitGetGamepads of Navigator
found   : function (): (Array<{
  axes: (Array<number>|null),
  buttons: (Array<number>|null),
  id: string,
  index: number,
  timestamp: number
}>|null)
required: function (): Array<Gamepad>
navigator.webkitGetGamepads = function() {};
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/jirutjak/aports/testing/emscripten/src/emscripten-1.37.9/src/closure-externs.js:155: WARNING - variable navigator.webkitGetGamepads redefined with type function (): (Array<{
  axes: (Array<number>|null),
  buttons: (Array<number>|null),
  id: string,
  index: number,
  timestamp: number
}>|null), original definition at externs.zip//w3c_gamepad.js:31 with type function (): Array<Gamepad>
navigator.webkitGetGamepads = function() {};
^^^^^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:72: WARNING - function read masks variable (IE bug)
  Module['read'] = function read(filename, binary) {
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:85: WARNING - Function assert: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
    assert(ret.buffer);
    ^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:123: WARNING - function read masks variable (IE bug)
    Module['read'] = function read() { throw 'no read() available' };
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:131: WARNING - Function assert: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
    assert(typeof data === 'object');
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:150: WARNING - function read masks variable (IE bug)
  Module['read'] = function read(url) {
                   ^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:158: WARNING - function read masks variable (IE bug)
    Module['readBinary'] = function read(url) {
                           ^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:187: WARNING - function print masks variable (IE bug)
    if (!Module['print']) Module['print'] = function print(x) {
                                            ^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:190: WARNING - function printErr masks variable (IE bug)
    if (!Module['printErr']) Module['printErr'] = function printErr(x) {
                                                  ^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:306: WARNING - Function parseInt: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
          var bits = parseInt(type.substr(1));
                     ^^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:307: WARNING - Function assert: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
          assert(bits % 8 === 0);
          ^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:323: WARNING - Function assert: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
        assert((ptr & 7) === 4);
        ^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:327: WARNING - Function assert: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
      assert((ptr & 3) === 0);
      ^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:366: WARNING - Function assert: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
    assert(sig);
    ^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:418: WARNING - variable assert redefined with type function (?, ?): undefined, original definition at /usr/lib/node_modules/closurecompiler-externs/assert.js:36 with type function (*, string): ?
function assert(condition, text) {
         ^^^^^^

/tmp/tmp8Sdjjk.cl.js:485: WARNING - Function Pointer_stringify: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
    if (returnType === 'string') ret = Pointer_stringify(ret);
                                       ^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:649: WARNING - Function assert: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
    assert((ret & 3) == 0);
    ^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:675: WARNING - Property getFunctionIndex never defined on Runtime
      curr = Runtime.getFunctionIndex(curr);
                     ^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:686: WARNING - Function setValue: called with 3 argument(s). Function requires at least 4 argument(s) and no more than 4 argument(s).
    setValue(ret+i, curr, type);
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1076: WARNING - Function getValue: called with 2 argument(s). Function requires at least 3 argument(s) and no more than 3 argument(s).
      if (getValue(status, 'i32') === 0 && ret) {
          ^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1077: WARNING - Function Pointer_stringify: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
        return Pointer_stringify(ret);
               ^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1151: WARNING - actual parameter 1 of Int8Array does not match formal parameter
found   : (Object<string,*>|null)
required: (Array<number>|ArrayBuffer|ArrayBufferView|null|number)
  Module['HEAP8'] = HEAP8 = new Int8Array(buffer);
                                          ^^^^^^

/tmp/tmp8Sdjjk.cl.js:1152: WARNING - actual parameter 1 of Int16Array does not match formal parameter
found   : (Object<string,*>|null)
required: (Array<number>|ArrayBuffer|ArrayBufferView|null|number)
  Module['HEAP16'] = HEAP16 = new Int16Array(buffer);
                                             ^^^^^^

/tmp/tmp8Sdjjk.cl.js:1153: WARNING - actual parameter 1 of Int32Array does not match formal parameter
found   : (Object<string,*>|null)
required: (Array<number>|ArrayBuffer|ArrayBufferView|null|number)
  Module['HEAP32'] = HEAP32 = new Int32Array(buffer);
                                             ^^^^^^

/tmp/tmp8Sdjjk.cl.js:1154: WARNING - actual parameter 1 of Uint8Array does not match formal parameter
found   : (Object<string,*>|null)
required: (Array<number>|ArrayBuffer|ArrayBufferView|null|number)
  Module['HEAPU8'] = HEAPU8 = new Uint8Array(buffer);
                                             ^^^^^^

/tmp/tmp8Sdjjk.cl.js:1155: WARNING - actual parameter 1 of Uint16Array does not match formal parameter
found   : (Object<string,*>|null)
required: (Array<number>|ArrayBuffer|ArrayBufferView|null|number)
  Module['HEAPU16'] = HEAPU16 = new Uint16Array(buffer);
                                                ^^^^^^

/tmp/tmp8Sdjjk.cl.js:1156: WARNING - actual parameter 1 of Uint32Array does not match formal parameter
found   : (Object<string,*>|null)
required: (Array<number>|ArrayBuffer|ArrayBufferView|null|number)
  Module['HEAPU32'] = HEAPU32 = new Uint32Array(buffer);
                                                ^^^^^^

/tmp/tmp8Sdjjk.cl.js:1157: WARNING - actual parameter 1 of Float32Array does not match formal parameter
found   : (Object<string,*>|null)
required: (Array<number>|ArrayBuffer|ArrayBufferView|null|number)
  Module['HEAPF32'] = HEAPF32 = new Float32Array(buffer);
                                                 ^^^^^^

/tmp/tmp8Sdjjk.cl.js:1158: WARNING - actual parameter 1 of Float64Array does not match formal parameter
found   : (Object<string,*>|null)
required: (Array<number>|ArrayBuffer|ArrayBufferView|null|number)
  Module['HEAPF64'] = HEAPF64 = new Float64Array(buffer);
                                                 ^^^^^^

/tmp/tmp8Sdjjk.cl.js:1205: WARNING - only arrays or objects can be accessed
found   : undefined
required: Object
  HEAP32[0] = 0x63736d65; /* 'emsc' */
  ^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1206: WARNING - only arrays or objects can be accessed
found   : undefined
required: Object
HEAP16[1] = 0x6373;
^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1207: WARNING - only arrays or objects can be accessed
found   : undefined
required: Object
if (HEAPU8[2] !== 0x73 || HEAPU8[3] !== 0x63) throw 'Runtime error: expected the system to be little-endian!';
    ^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1433: WARNING - Property fround never defined on Math
var Math_fround = Math.fround;
                       ^^^^^^

/tmp/tmp8Sdjjk.cl.js:1579: WARNING - Function Pointer_stringify: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
        var ret = Pointer_stringify(SYSCALLS.get());
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1583: WARNING - Function assert: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
        if (low >= 0) assert(high === 0);
                      ^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1584: WARNING - Function assert: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
        else assert(high === -1);
             ^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1587: WARNING - Function assert: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
        assert(SYSCALLS.get() === 0);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1591: WARNING - Property getStreamFromFD never defined on SYSCALLS
      var stream = SYSCALLS.getStreamFromFD(), offset_high = SYSCALLS.get(), offset_low = SYSCALLS.get(), result = SYSCALLS.get(), whence = SYSCALLS.get();
                            ^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1593: WARNING - Function assert: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
      assert(offset_high === 0);
      ^^^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1610: WARNING - Property buffer never defined on ___syscall146
      if (!___syscall146.buffer) {
                         ^^^^^^

/tmp/tmp8Sdjjk.cl.js:1614: WARNING - Function assert: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
          assert(buffer);
          ^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1642: WARNING - unreachable code
    } catch (e) {
      ^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1653: WARNING - Property getStreamFromFD never defined on SYSCALLS
      var stream = SYSCALLS.getStreamFromFD();
                            ^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1662: WARNING - Function allocate: called with 3 argument(s). Function requires at least 4 argument(s) and no more than 4 argument(s).
DYNAMICTOP_PTR = allocate(1, "i32", ALLOC_STATIC);
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1664: WARNING - Function Runtime.alignMemory: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
STACK_BASE = STACKTOP = Runtime.alignMemory(STATICTOP);
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1668: WARNING - Function Runtime.alignMemory: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
DYNAMIC_BASE = Runtime.alignMemory(STACK_MAX);
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1790: WARNING - dangerous use of the global this object
  this.name = "ExitStatus";
  ^^^^

/tmp/tmp8Sdjjk.cl.js:1791: WARNING - dangerous use of the global this object
  this.message = "Program terminated with exit(" + status + ")";
  ^^^^

/tmp/tmp8Sdjjk.cl.js:1792: WARNING - dangerous use of the global this object
  this.status = status;
  ^^^^

/tmp/tmp8Sdjjk.cl.js:1803: WARNING - Function run: called with 0 argument(s). Function requires at least 1 argument(s) and no more than 1 argument(s).
  if (!Module['calledRun']) run();
                            ^^^^^

/tmp/tmp8Sdjjk.cl.js:1819: WARNING - Function allocate: called with 3 argument(s). Function requires at least 4 argument(s) and no more than 4 argument(s).
  var argv = [allocate(intArrayFromString(Module['thisProgram']), 'i8', ALLOC_NORMAL) ];
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1819: WARNING - Function intArrayFromString: called with 1 argument(s). Function requires at least 3 argument(s) and no more than 3 argument(s).
  var argv = [allocate(intArrayFromString(Module['thisProgram']), 'i8', ALLOC_NORMAL) ];
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1822: WARNING - Function allocate: called with 3 argument(s). Function requires at least 4 argument(s) and no more than 4 argument(s).
    argv.push(allocate(intArrayFromString(args[i]), 'i8', ALLOC_NORMAL));
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1822: WARNING - Function intArrayFromString: called with 1 argument(s). Function requires at least 3 argument(s) and no more than 3 argument(s).
    argv.push(allocate(intArrayFromString(args[i]), 'i8', ALLOC_NORMAL));
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1826: WARNING - Function allocate: called with 3 argument(s). Function requires at least 4 argument(s) and no more than 4 argument(s).
  argv = allocate(argv, 'i32', ALLOC_NORMAL);
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1929: WARNING - cannot instantiate non-constructor
  Module['quit'](status, new ExitStatus(status));
                         ^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1975: WARNING - Function run: called with 0 argument(s). Function requires at least 1 argument(s) and no more than 1 argument(s).
run();
^^^^^

/usr/lib/node_modules/closurecompiler-externs/crypto.js:34: WARNING - variable crypto redefined, original definition at /home/jirutjak/aports/testing/emscripten/src/emscripten-1.37.9/src/closure-externs.js:25
var crypto = {};
    ^^^^^^^^^^^

/usr/lib/node_modules/closurecompiler-externs/crypto.js:478: WARNING - variable crypto.randomBytes redefined with type function (number, function ((Error|null), (buffer.Buffer|null)): ?=): ?, original definition at /home/jirutjak/aports/testing/emscripten/src/emscripten-1.37.9/src/closure-externs.js:31 with type function (number, function ((Error|null), (buffer.Buffer|null)): ?): ?
crypto.randomBytes = function(size, callback) {};
^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1757: ERROR - functions can only be declared at top level or immediately within another function in ES5 strict mode
    function doBrowserLoad() {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^

/tmp/tmp8Sdjjk.cl.js:1764: ERROR - functions can only be declared at top level or immediately within another function in ES5 strict mode
      function useRequest() {
      ^^^^^^^^^^^^^^^^^^^^^^^

2 error(s), 63 warning(s), 73.5% typed
```

Relevant issues: #653

**Comment by kripken** [comment]
Is there a benefit to using newer closure? Faster, new features perhaps?

**Comment by jirutka** [comment]
I dunno, I just wanted to get rid of bundled third-party dependency and don’t wanna create a special package for outdated version of closure-compiler.

I’m creating emscripten package for Alpine Linux ([source](https://github.com/alpinelinux/aports/tree/master/testing/emscripten)). It’s basically done, but with a lot of custom patches.

**Comment by nazar-pc** [comment]
There is a good benefit: Emscripten's sources can start using some of the newer ES2015+ features that are easier to write/read and simply shorter, while still optionally targeting ES5-only browsers when needed (yes, new closure compiler supports ES5->ES2015 conversion).
