### ISSUE TITLE
Optimizer throws std::bad_alloc

### ISSUE THREAD

**Issue by cpitclaudel** [emscripten-core/emscripten#5317]
Hi there,

I'm seeing this when compiling with `-Os`:

```
$ emcc -s DISABLE_EXCEPTION_CATCHING=0 -s ALLOW_MEMORY_GROWTH=1 -s STRICT=1 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s NO_EXIT_RUNTIME=1 -s INVOKE_RUN=0 -s EXPORTED_FUNCTIONS='["_main"]' -Os <input> -o <output>.js 

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Traceback (most recent call last):
  File "/vagrant/cvc4-js/emsdk-portable/emscripten/tag-1.37.13/emcc", line 13, in <module>
    emcc.run()
  File "/vagrant/cvc4-js/emsdk-portable/emscripten/tag-1.37.13/emcc.py", line 1755, in run
    optimizer.flush()
  File "/vagrant/cvc4-js/emsdk-portable/emscripten/tag-1.37.13/emcc.py", line 221, in flush
    self.run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "/vagrant/cvc4-js/emsdk-portable/emscripten/tag-1.37.13/emcc.py", line 254, in run_passes
    just_concat=just_concat)
  File "/vagrant/cvc4-js/emsdk-portable/emscripten/tag-1.37.13/tools/shared.py", line 2046, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "/vagrant/cvc4-js/emsdk-portable/emscripten/tag-1.37.13/tools/js_optimizer.py", line 563, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/vagrant/cvc4-js/emsdk-portable/emscripten/tag-1.37.13/tools/tempfiles.py", line 78, in run_and_clean
    return func()
  File "/vagrant/cvc4-js/emsdk-portable/emscripten/tag-1.37.13/tools/js_optimizer.py", line 563, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/vagrant/cvc4-js/emsdk-portable/emscripten/tag-1.37.13/tools/js_optimizer.py", line 460, in run_on_js
    filenames = pool.map(run_on_chunk, commands, chunksize=1)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AssertionError: Error in optimizer (return code -6): 
```

I'm on a 32-bits machine.  How can I help debug this?

**Comment by juj** [comment]
A `std::bad_alloc` is generally caused due to running out of memory/address space. If building the code in question needs more address space than is available for 32-bit, there is not much that can be done except to migrate to 64-bit. Try doing the build on a 64-bit system and test if that passes. If so, then the issue is likely due to an exhaustion of available address space. Use a tool like `htop` to interactively observe the maximum amount of memory that the 64-bit run needs, that might give a clue to how much memory will be needed.

Also you can try doing `export EMCC_CORES=1` before the build to force single core execution, which might help reduce needed memory footprint.
