### ISSUE TITLE
Compilation gives LLVM ERROR and crashes

### ISSUE THREAD

**Issue by winadam** [emscripten-core/emscripten#5389]
I have been trying to compile clang into js for a couple days and keep getting stumped by this error.
````
DEBUG:root:LLVM => JS
DEBUG:root:emscript: llvm backend: /opt/emsdk-portable/clang/fastcomp/build_incoming_64/bin/llc /tmp/tmpnKwaLt/clang.bc -march=js -filetype=asm -o /tmp/emscripten_temp/tmpoBPKX2.4.js -emscripten-stack-size=5242880 -O2 -emscripten-global-base=8
Unsupported:   %163 = icmp slt i72 %162, 0
LLVM ERROR: Signed comparisons not yet supported for integer types larger than 64 bits
DEBUG:root:  emscript: llvm backend took 18.8891010284 seconds
Traceback (most recent call last):
  File "/opt/emsdk-portable/emscripten/incoming/emcc", line 13, in <module>
    emcc.run()
  File "/opt/emsdk-portable/emscripten/incoming/emcc.py", line 1517, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/opt/emsdk-portable/emscripten/incoming/tools/shared.py", line 2020, in emscripten
    call_emscripten(cmdline)
  File "/opt/emsdk-portable/emscripten/incoming/emscripten.py", line 2209, in _main
    temp_files.run_and_clean(lambda: main(
  File "/opt/emsdk-portable/emscripten/incoming/tools/tempfiles.py", line 78, in run_and_clean
    return func()
  File "/opt/emsdk-portable/emscripten/incoming/emscripten.py", line 2214, in <lambda>
    DEBUG=DEBUG,
  File "/opt/emsdk-portable/emscripten/incoming/emscripten.py", line 2114, in main
    temp_files=temp_files, DEBUG=DEBUG)
  File "/opt/emsdk-portable/emscripten/incoming/emscripten.py", line 93, in emscript
    backend_output = compile_js(infile, settings, temp_files, DEBUG)
  File "/opt/emsdk-portable/emscripten/incoming/emscripten.py", line 127, in compile_js
    backend_output = open(temp_js).read()
IOError: [Errno 2] No such file or directory: '/tmp/emscripten_temp/tmpoBPKX2.4.js'

````
It appears the llc gives this error and doesn't make an output. Any suggestions?
EDIT: This is on `sdk-incoming-64bit` emsdk

**Comment by kripken** [comment]
That's a limitation in the legalization code we use. For more details you can find the error text under `lib/Target/JSBackend/`. It would probably be possible to implement that, but it's probably less easy than the unsigned case which is supported.
