### ISSUE TITLE
ffsll symbol multiply defined

### ISSUE THREAD

**Issue by promethe42** [emscripten-core/emscripten#5390]
Hello,

I'm trying to build a binary built with the [Minko](https://github.com/aerys/minko) engine.
Our code is fine with older (pre 1.37) versions of Emscripten, but we have a bytecode => js conversion error now (tested with Emscripten 1.37.9, Ubuntu 16.04 64bit):

```
emcc.sh bin/html5/release/smartshape-player.bc -o bin/html5/release/smartshape-player.html -O3 --llvm-lto 1 -O3 --closure 1 --js-library "/home/promethe/Projects/smartshape.io/minko/module/emscripten/library.js" -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s DISABLE_EXCEPTION_CATCHING=1 -s ALLOW_MEMORY_GROWTH=0 -s NO_EXIT_RUNTIME=1 -s EXPORTED_FUNCTIONS="['_main', '_minkoRunPlayer']" -s OUTLINING_LIMIT=20000 --memory-init-file 1 --shell-file "/home/promethe/Projects/smartshape.io/minko-player/app/template.html" || sh script/fail.sh "bin/html5/release/smartshape-player.bc"
/home/promethe/emsdk/emscripten/tag-1.37.9/emcc bin/html5/release/smartshape-player.bc -o bin/html5/release/smartshape-player.html -O3 --llvm-lto 1 -O3 --closure 1 --js-library module/emscripten/library.js -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s DISABLE_EXCEPTION_CATCHING=1 -s ALLOW_MEMORY_GROWTH=0 -s NO_EXIT_RUNTIME=1 -s EXPORTED_FUNCTIONS=['_main', '_minkoRunPlayer'] -s OUTLINING_LIMIT=20000 --memory-init-file 1 --shell-file template.html
error: Linking globals named 'ffsll': symbol multiply defined!
Traceback (most recent call last):
  File "/home/promethe/emsdk/emscripten/tag-1.37.9/emcc", line 13, in <module>
    emcc.run()
  File "/home/promethe/emsdk/emscripten/tag-1.37.9/emcc.py", line 1624, in run
    final = shared.Building.llvm_opt(final, link_opts, DEFAULT_FINAL)
  File "/home/promethe/emsdk/emscripten/tag-1.37.9/tools/shared.py", line 1838, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations: 
Post-build command failed for project bin/html5/release/smartshape-player.bc
```

Yet it looks like `llvm-nm` says the `ffsll` symbol is defined only once;
```
$ llvm-nm smartshape-player.bc | grep ffsll
-------- T ffsll
```

What's wrong?

**Comment by promethe42** [comment]
I cannot reproduce the problem with:

> emscripten-nightly-1.36.14-2016_12_19_18_10
> clang-nightly-e1.36.14-2016_12_19_18_10-64bit

**Comment by promethe42** [comment]
It looks like the problem comes from GLSL optimizer:

https://github.com/aras-p/glsl-optimizer

There is a `HAVE___BUILTIN_FFSLL` macro. I'll try setting it and report back.
It's still strange to see it break just now...

**Comment by juj** [comment]
If your emsdk only shows 1.37.9, you might have been affected with an unfortunate emsdk update bug, see https://groups.google.com/forum/#!topic/emscripten-discuss/bKCQxN6Q76Y

**Comment by promethe42** [comment]
I can confirm the problem is related to glsl-optimizer and not the Emscripten version.
To be exact, it seams the Emscripten embedded libc now includes ffsll and it was not the case in earlier versions.
Is that possible?

**Comment by juj** [comment]
The commit

```
SHA-1: 31cf2bb1bc3a501a14ea9647f2bc7ad25fb2fce4

* Update musl to 1.1.15 (#4813)

* Revert all emscripten musl changes

* Update musl to 1.1.5

* Reapply emscripten patches

* Fix up libs to partially compile

* Revert emscripten musl include folder

* Update musl include folder to 1.1.5

* Reapply emscripten libc include changes

* Get compiling again!

* Restore alltypes.h to have emscripten-specific changes

alltypes.h is autogenerated, and we've since overridden the types

Longer-term, we should figure out a way to either autogenerate the types
to match what emscripten expects, or change emscripten's expectation to
support musl's assumptions. Probably worth including with merging the
asm&wasm ABIs.

* Update expected langinfo test output for fixes in upstream musl

* Canonicalize nans in hyperbolic test

Nans are now printed out with their sign if negative. Asm and wasm treat
these differently, so canonicalize how they print.

* Tweak how musl forwards syscalls to emscripten

Before: pass all syscall args as varargs, args are int32
After: cast all syscall args to int32, pass as varargs
This fixes and prevents aliasing issues, and is more consistent with
other architectures

* Change __syscall to syscall in isatty to set errno

POSIX specifies that isatty sets errno in the case that it fails.
__syscall doesn't set errno, and syscall does.

* Update struct_info again

* Always allocate pthread_self, even in the stub

* sys_open should call __syscall_ret

* Fix up pthread js for optimized code (remove __asm: true)

* Canonicalize more nans in testsuite

* Re-set expected langinfo output

* Update align_moar expected addresses

* Disable assert in wasm_backend llseek syscall

* Update now-passing wasm_backend tests

* Update other.test_locale to non-stub setlocale

* Fix compiling with -s USE_PTHREADS=1

* Initialize __pthread_self() when using pthread_stub

* Canonicalize nans for test_zerodiv

* Update count of globals in test_dlfcn_self

* Rework how we initialize pthread_self for non-threaded applications

* Prefer 'EMSCRIPTEN_START_FUNCS' in test_memorygrowth, because 'var TOTAL_MEMORY' can move around

* Now that CURRENT_LOCALE isn't reading off NULL, test_langinfo should expect ASCII

* Re-disable test_demangle_stacks - was spuriously passing earlier

* Explicitly pass 0 as the high bits for SYS__llseek

* Enable v8 for test_readdir now that it supports printErr

* Only use __syscall_emscripten if __EMSCRIPTEN__ is defined

* Move O_LARGEFILE as default back to libc

* libc #if to #ifdef

* Rename pthread import funcs to not rely on alias

* Consistently reference pthread_setcancelstate by alias in libc

* Stub out fcntl64 for NO_FILESYSTEM case

* Update emscripten-specific pthread struct fields

* Consistently reference pthread_testcancel by alias in libc

* Stub out SYS_rt_sigqueueinfo syscall

* Stub out SYS_sendmmsg syscall

* Stub out SYS_recvmmsg syscall

* Revert "Consistently reference pthread_testcancel by alias in libc"

This reverts commit 43563a5b141a47d4a7aa7e48c059ed0e98597fbb.

* Revert "Consistently reference pthread_setcancelstate by alias in libc"

This reverts commit 2ca2eded8a0d50bb3847cda0a99c900532f6937b.

* Correctly fix unresolved symbol: __pthread_setcancelstate

* Update library_pthread.c pthread_testcancel to match musl's expectations

* test_strftime.c -> test_strftime.cpp

* library_pthread_stub pthread_exit should call exit, not nothing

* TEMP: init pthread_self->locale with pthreads enabled

* Initialize pthread global data from libc in JS

* Move _b_lock and _b_waiters back to not emscripten-only

* Remove untrue __asm annotation from threaded pthread_self, make stub pthread_self non-asm

* Remove old unneeded pthread init exported functions

* Move pthread_self in stub case to libc C code

* Move emscripten_pthread initialization to its own file, out from locale_map.c

* Statically allocate the pthread struct and not just a pointer in the stub case

* Remove commented-out test args

* Remove misleading __asm annotation for _register_pthread_ptr

* Do module-side pthread initialization in-module

* Don't cast away volatile when calling emscripten_futex_wake in __wake

* Expose libc struct to emscripten, use that for non-main pthread initialization

* Re-add pthread_impl.h import to library_pthread.c

* Update align_moar alignment post-rebase

* Update emscripten header include in libc.c

* Remove obsolete locale preallocating code in newlocale

We previously statically allocated a single locale in the event that
we needed to dynamically allocate one during startup. musl changed their
implementation to statically allocate C_LOCALE and UTF8_LOCALE, so we
already get that behavior.
In addition this was causing invalid locales to get allocated instead of
returning NULL, because the preceding logic changed. That was caught by
other.test_locale_wrong

* Update test_llvm_lto

* Bump version to 1.37.5
```

introduced the file `system/lib/libc/musl/src/misc/ffsll.c` to Emscripten, it looks like it was not present in the earlier build of musl we were using.
