### ISSUE TITLE
Test browser.test_cubegeom_pre_vao_es fails on OS X.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#5408]
Running on Firefox Nightly on OS X, I see that the test fails to produce any rendering on the screen, it stays black, and hence fails on

```
======================================================================
ERROR: test_cubegeom_pre_vao_es (test_browser.browser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/clb/emslave/buildslave/osx-incoming/emsdk/emscripten/incoming/tests/test_browser.py", line 1826, in test_cubegeom_pre_vao_es
    self.btest('cubegeom_pre_vao_es.c', reference='cubegeom_pre_vao.png', args=['-s', 'FULL_ES2=1', '-lGL', '-lSDL'])
  File "/Users/clb/emslave/buildslave/osx-incoming/emsdk/emscripten/incoming/tests/runner.py", line 945, in btest
    self.run_browser(outfile + url_suffix, message, ['/report_result?' + e for e in expected], timeout=timeout)
  File "/Users/clb/emslave/buildslave/osx-incoming/emsdk/emscripten/incoming/tests/runner.py", line 803, in run_browser
    self.assertIdentical(expectedResult, output)
  File "/Users/clb/emslave/buildslave/osx-incoming/emsdk/emscripten/incoming/tests/runner.py", line 484, in assertIdentical
    limit_size(''.join([a.rstrip()+'\n' for a in difflib.unified_diff(x.split('\n'), y.split('\n'), fromfile='expected', tofile='actual')]))
Exception: Expected to have '/report_result?0' == '/report_result?34', diff:

--- expected
+++ actual
@@ -1 +1 @@
-/report_result?0
+/report_result?34
```

The failure is not restricted to the OS X buildbot (Mac Pro server), but the failure also deterministically occurs on my 2016 MacBook Pro. This is a new test that was introduced in #5231, and with immediate glance, I can't see what would be wrong with that test. The test passes on Linux and Windows bots though. The test also passes on Chrome Canary on the same 2016 MacBook Pro, so this may be a OS X specific Firefox bug.

**Comment by juj** [comment]
Skipped this test on OS X for now.
