### ISSUE TITLE
SSE tests including test_sse1_full fail

### ISSUE THREAD

**Issue by saschanaz** [emscripten-core/emscripten#5618]
emscripten is installed by `emsdk install latest`.

With the flag `-v` for clang manually turned on:

```
$ python2 tests/runner.py test_sse1_full
WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
Test suites:
['test_core']
Running test_core: (1 tests)
test_sse1_full (test_core.default) ... (checking sanity from test runner)
INFO:root:(Emscripten: Running sanity checks)
clang version 4.0.0  (emscripten 1.37.21 : 1.37.21)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/saschanaz/emsdk-portable/clang/e1.37.21_64bit
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/home/saschanaz/emsdk-portable/clang/e1.37.21_64bit/clang++" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test_sse1_full.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -v -dwarf-column-info -debugger-tuning=gdb -resource-dir /home/saschanaz/emsdk-portable/clang/e1.37.21_64bit/../lib/clang/4.0.0 -D _CRT_SECURE_NO_WARNINGS=1 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/backward -internal-isystem /usr/local/include -internal-isystem /home/saschanaz/emsdk-portable/clang/e1.37.21_64bit/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /tmp/emscripten_test_default_9k9ovk -ferror-limit 19 -fmessage-length 120 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -o /tmp/test_sse1_full-60c169.o -x c++ /home/saschanaz/emsdk-portable/emscripten/1.37.21/tests/test_sse1_full.cpp
clang -cc1 version 4.0.0 based upon LLVM 4.0.0 default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/home/saschanaz/emsdk-portable/clang/e1.37.21_64bit/../lib/clang/4.0.0/include"
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0
 /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0
 /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/backward
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
/home/saschanaz/emsdk-portable/emscripten/1.37.21/tests/test_sse1_full.cpp:4:10: fatal error: 'xmmintrin.h' file not
      found
#include <xmmintrin.h>
         ^~~~~~~~~~~~~
1 error generated.
ERROR

======================================================================
ERROR: test_sse1_full (test_core.default)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/saschanaz/emsdk-portable/emscripten/1.37.21/tests/test_core.py", line 17, in decorated
    f(self)
  File "/home/saschanaz/emsdk-portable/emscripten/1.37.21/tests/test_core.py", line 5051, in test_sse1_full
    native_result, err = Popen('./test_sse1_full', stdout=PIPE).communicate()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

----------------------------------------------------------------------
Ran 1 test in 0.449s

FAILED (errors=1)
```

**Comment by juj** [comment]
The way that test works is that it builds the same code twice - once for native, and second time for Emscripten, and then compares the two that they get the same result.

This error message seems to come from the native compilation side. Tried this out on my Linux Mint 18 box, which passes the test, so this seems to be something configuration specific.

Check out this line https://github.com/kripken/emscripten/blob/incoming/tests/test_core.py#L5067, which is running the build. Two things come to mind here:

1. that line is missing `-msse` compiler directive passed to Clang. I wonder what happens if that is added?

2. If the above does not resolve it: can you search your system to find where the header file `xmmintrin.h` is located? Perhaps there's an include directive that we are missing that should be added. Note that here the `xmmintrin.h` from inside Emscripten repository should not be getting used, but the one that is available in the native system compiler.

**Comment by SaschaNaz** [comment]
1. No difference.
2. It's in `/usr/lib/gcc/x86_64-linux-gnu/5/include`, but this seems not clang-compatible as `-I /usr/lib/gcc/x86_64-linux-gnu/5/include` causes several compile time errors.
