### ISSUE TITLE
How to use build and source directories

### ISSUE THREAD

**Issue by johnnyhoffmann32** [emscripten-core/emscripten#5643]
I'm trying to have one folder called `src/` and the other `build/` , and another one called `assets/` for holding SDL fonts and images, here is my build.sh script
```
#/bin/bash
source /home/johnnyhoffmann/emsdk/emsdk/emsdk_env.sh > /dev/null

#Global Compiler Options
cpp_in_file="src/main.cpp"

#em++ Compiler Options
em_cpp_out_file="build/hello.js"
em_cpp_libs="-s USE_SDL=2 -s USE_SDL_IMAGE=2 -s USE_SDL_TTF=2"
em_cpp_opt="-s WASM=1 -s NO_EXIT_RUNTIME=1 --use-preload-plugins --preload-file assets -O3"
em++ $cpp_in_file -o $em_cpp_out_file $em_cpp_libs $em_cpp_opt

#g++ Compiler Options
gpp_cpp_out_file="build/hello.run"
gpp_cpp_libs="-lSDL2 -lSDL_image -lSDL_ttf"
g++  $cpp_in_file -o $gpp_cpp_out_file $gpp_cpp_libs
	
```
In firefox I get errors:
```
Error: Not Found : http://localhost/JohnnyHoffmannWebsite_PHP/Experimental/WebAssembly/hello.data
uncaught exception: abort("failed to load wasm binary file at 'hello.wasm'") at jsStackTrace@http://localhost/JohnnyHoffmannWebsite_PHP/Experimental/WebAssembly/index_files/build/hello.js:1:23793
stackTrace@http://localhost/JohnnyHoffmannWebsite_PHP/Experimental/WebAssembly/index_files/build/hello.js:1:23964
abort@http://localhost/JohnnyHoffmannWebsite_PHP/Experimental/WebAssembly/index_files/build/hello.js:1:276028
doNativeWasm/<@http://localhost/JohnnyHoffmannWebsite_PHP/Experimental/WebAssembly/index_files/build/hello.js:1:34918

If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

```
The file `hello.data` is located in the build folder as I wanted, but firefox keeps on trying to load the `hello.data` file where my build script is located which is not what is i want.

Please Help, Thanks :)

**Comment by kripken** [comment]
By default it looks in the same dir for the wasm file, yeah. You can use [locateFile](https://kripken.github.io/emscripten-site/docs/api_reference/module.html#Module.locateFile) to adjust that at runtime. I see the docs don't mention it applies to the wasm file too, I'll update that.

**Comment by kripken** [comment]
No, locateFile should be a function. See the docs - it receives the file name as input, and returns the path to find it at. So if the input is 'hello.wasm' you can return the full new path to that file.

**Comment by johnnyhoffmann32** [comment]
I changed Module.locateFile to a function, and says `Module.locateFile` is not a function.
I'm new to emscripten and WebAssembly, Sorry :( 
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        
    </head>
    
    <body>
        <canvas id="canvas" tabindex="1">           
            <noscript>Sorry, your web browser is not compatible with HTML5, JavaScript or WebAssembly technologies<br></noscript>
        </canvas>
        <br>
        <p id="testingtag"></p>
         
        <script type="text/javascript" src="index_files/build/hello.js"></script>
        <script> 
            Module.locateFile("index_files/build/hello.wasm");   
            Module.canvas = document.getElementById("canvas"); 
        
        </script>
    </body>
</html>
```

```
TypeError: Module.LocateFile is not a function[Learn More]  default.php:17:13
	<anonymous> http://localhost/JohnnyHoffmannWebsite_PHP/Experimental/WebAssembly/default.php:17:13
Error: Not Found : http://localhost/JohnnyHoffmannWebsite_PHP/Experimental/WebAssembly/hello.data  hello.js:1:2462
	fetchRemotePackage/xhr.onload http://localhost/JohnnyHoffmannWebsite_PHP/Experimental/WebAssembly/index_files/build/hello.js:1:2462
uncaught exception: abort("failed to load wasm binary file at 'hello.wasm'") at jsStackTrace@http://localhost/JohnnyHoffmannWebsite_PHP/Experimental/WebAssembly/index_files/build/hello.js:1:23793
stackTrace@http://localhost/JohnnyHoffmannWebsite_PHP/Experimental/WebAssembly/index_files/build/hello.js:1:23964
abort@http://localhost/JohnnyHoffmannWebsite_PHP/Experimental/WebAssembly/index_files/build/hello.js:1:276028
doNativeWasm/<@http://localhost/JohnnyHoffmannWebsite_PHP/Experimental/WebAssembly/index_files/build/hello.js:1:34918

If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.  (unknown)
```

**Comment by curiousdannii** [comment]
Try setting Module.locateFile before you load hello.js.

**Comment by johnnyhoffmann32** [comment]
I've tried that and I get errors:
```
ReferenceError: Module is not defined[Learn More]  default.php:15:13
	<anonymous> http://localhost/JohnnyHoffmannWebsite_PHP/Experimental/WebAssembly/default.php:15:13
SyntaxError: missing ; before statement[Learn More]  hello.js:1:10
ReferenceError: Module is not defined[Learn More]  default.php:26:13
	<anonymous> http://localhost/JohnnyHoffmannWebsite_PHP/Experimental/WebAssembly/default.php:26:13
```

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        
    </head>
    
    <body>
        <canvas id="canvas" tabindex="1">           
            <noscript>Sorry, your web browser is not compatible with HTML5, JavaScript or WebAssembly technologies<br></noscript>
        </canvas>
        <br>
        <p id="testingtag"></p>
        <script> 
            Module.locateFile = function(url)
            {
                return "index_files/build/hello.wasm";
            };
            Module.getPreloadedPackage = function(remotePackageName, remotePackageSize)
            {
                return "index_files/build/hello.data";
            };
        </script> 
        <script type="text/javascript" src="index_files/build/hello.js"></script>
        <script>
            Module.canvas = document.getElementById("canvas"); 
        </script>
    </body>
</html>
```

**Comment by curiousdannii** [comment]
Yes, you have to define a Module variable first. That's just a normal undefined variable error.

https://kripken.github.io/emscripten-site/docs/api_reference/module.html#creating-the-module-object

**Comment by johnnyhoffmann32** [comment]
But, my SDL code is still not running, I don't know if i'm doing this right
