### ISSUE TITLE
js_optimizer fails badly when with EMCC_CORES=32

### ISSUE THREAD

**Issue by saschanaz** [emscripten-core/emscripten#5667]
I'm getting errors on js_optimizer on Circle CI which seems to be reporting 32 as CPU numbers. I can reproduce same errors on Travis CI with manual EMCC_CORES=32.

This is some of the tracebacks I get:

```
Traceback (most recent call last):
  File "/root/emscripten/tools/emterpretify.py", line 786, in <module>
    shared.Building.js_optimizer(infile, ['emterpretify'], extra_info={ 'emterpretedFuncs': list(emterpreted_funcs), 'externalEmterpretedFuncs': list(external_emterpreted_funcs), 'opcodes': OPCODES, 'ropcodes': ROPCODES, 'ASYNC': ASYNC, 'PROFILING': PROFILING, 'ASSERTIONS': ASSERTIONS }, output_filename=temp, just_concat=True)
  File "/root/emscripten/tools/shared.py", line 2105, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "/root/emscripten/tools/js_optimizer.py", line 563, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/root/emscripten/tools/tempfiles.py", line 78, in run_and_clean
    return func()
  File "/root/emscripten/tools/js_optimizer.py", line 563, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/root/emscripten/tools/js_optimizer.py", line 464, in run_on_js
    filenames = [run_on_chunk(command) for command in commands]
  File "/root/emscripten/tools/js_optimizer.py", line 287, in run_on_chunk
    assert proc.returncode == 0, 'Error in optimizer (return code ' + str(proc.returncode) + '): ' + output
AssertionError: Error in optimizer (return code 127): 
```

```
Traceback (most recent call last):
  File "/root/emscripten/emcc", line 13, in <module>
    emcc.run()
  File "/root/emscripten/emcc.py", line 1788, in run
    emterpretify(js_target, optimizer, options)
  File "/root/emscripten/emcc.py", line 2159, in emterpretify
    optimizer.flush()
  File "/root/emscripten/emcc.py", line 220, in flush
    self.run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "/root/emscripten/emcc.py", line 253, in run_passes
    just_concat=just_concat)
  File "/root/emscripten/tools/shared.py", line 2105, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "/root/emscripten/tools/js_optimizer.py", line 563, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/root/emscripten/tools/tempfiles.py", line 78, in run_and_clean
    return func()
  File "/root/emscripten/tools/js_optimizer.py", line 563, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/root/emscripten/tools/js_optimizer.py", line 306, in run_on_js
    js = open(filename).read()
IOError: [Errno 2] No such file or directory: '/tmp/tmpOFV3dYtmp_Iyamm.jsfunc_0.js.jo.js.jo.js.em.js'
```

```
Traceback (most recent call last):
  File "/root/emscripten/tools/emterpretify.py", line 771, in <module>
    shared.Building.js_optimizer(infile, ['findReachable'], extra_info={ 'blacklist': list(emterpreted_funcs) }, output_filename=temp, just_concat=True)
  File "/root/emscripten/tools/shared.py", line 2105, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "/root/emscripten/tools/js_optimizer.py", line 563, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/root/emscripten/tools/tempfiles.py", line 78, in run_and_clean
    return func()
  File "/root/emscripten/tools/js_optimizer.py", line 563, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/root/emscripten/tools/js_optimizer.py", line 460, in run_on_js
    filenames = pool.map(run_on_chunk, commands, chunksize=1)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AssertionError: Error in optimizer (return code -9): // REACHABLE ["runPostSets7","runPostSets6","runPostSets4","runPostSets2","runPostSets5","runPostSets3","runPostSets1","_emscripten_memcpy_big","setTempRet0","_realloc","_saveSetjmp"]
```

**Comment by kripken** [comment]
It might be hitting a memory limit or some other VM limit, killing a process before it can write the output file.

We may be missing a check for a failed process somewhere, which could have given a better error, but I'm not sure.

**Comment by saschanaz** [comment]
Linking discussions on #5779, #5843 and #5876. Most of the current subprocess calls should check return code.
