### ISSUE TITLE
llvm.round.f32/f64, libc round() and rint() rounding mode errors

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#5716]
It looks like our implementation of rounding modes for each of `llvm.round.f32`, `llvm.round.f64`, libc `round()` family of functions and libc `rint()` family of functions are incorrect. Found out about this during LLVM 4.0.1 merge, which adds the `llvm.rint.f32/f64` intrinsic, and compilation began to route to using that one instead of musl `rint.c`. As a sidenote, musl `rint.c` implementation operates on non-canonical NaNs and it never worked properly either.

Searching through the specs, here's the official wordings:
 - `llvm.round.f32` & `llvm.round.f64`: https://llvm.org/docs/LangRef.html#id508: `"This function returns the same values as the libm round functions would, and handles error conditions in the same way."

I was not able to find documentation of libm round functions, but I did find the following: [The GNU C Library (libc)](http://www.gnu.org/software/libc/manual/html_node/Rounding-Functions.html): `"These functions are similar to rint, but they round halfway cases away from zero instead of to the nearest integer (or other current rounding mode). "`

 - `round`, `roundf`, `roundl`: [cplusplus.com](http://en.cppreference.com/w/c/numeric/math/round): `"1-3) Computes the nearest integer value to arg (in floating-point format), rounding halfway cases away from zero, regardless of the current rounding mode."`

so these implementations align with `llvm.round.f32/f64`.

 - Then, looking at `rint` at [cplusplus.com](http://www.cplusplus.com/reference/cmath/rint/): `"Rounds x to an integral value, using the rounding direction specified by fegetround."`, i.e. `rint` family is identical to `round` family, but this takes rounding mode into account. We don't have rounding modes implemented, so I want to make `rint()` behave according to what is the default musl rounding mode, which is `FE_TONEAREST`, or round-to-even (or banker's rounding).

The above is fixed in the LLVM 4.0.1 merge branch (#5400), which changes the LLVM intrinsic and `round` to operate away from zero, and fixes `rint` to round-to-even; however after that the one mode that remains is the emterpreter case, which is failing in test `asm2i.test_rounding`. @kripken: does emterpreter implement its math `round` intrinsic somehow differently?

**Comment by kripken** [comment]
The emterpreter doesn't have any special code for rounding. It should just do a normal call into a js library method for `_round` or such. Or do we now implement those in asm.js? If so then in theory this could have uncovered an emterpreter bug where it mistranslates the implementation code of rounding.

**Comment by juj** [comment]
The failure message is

```
======================================================================
ERROR: test_rounding (test_core.asm2i)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\code\emsdk\emscripten\incoming\tests\test_core.py", line 537, in test_rounding
    self.do_run_in_out_file_test('tests', 'core', 'test_rounding')
  File "C:\code\emsdk\emscripten\incoming\tests\test_core.py", line 80, in do_run_in_out_file_test
    self.do_run_from_file(src, output, **kwargs)
  File "C:\code\emsdk\emscripten\incoming\tests\runner.py", line 634, in do_run_from_file
    assert_returncode, assert_identical)
  File "C:\code\emsdk\emscripten\incoming\tests\runner.py", line 674, in do_run
    raise e
Exception: Expected to find 'Initial rounding mode is FE_TONEAREST
fesetround(FE_TONEAREST) returned 0, fegetround() afterwards returns FE_TONEAREST. Test results:
FE_TONEAREST: round(-4.5)=-5.0
FE_TONEAREST: round(-3.6)=-4.0
FE_TONEAREST: round(-3.5)=-4.0
FE_TONEAREST: round(-3.4)=-3.0
FE_TONEAREST: round(-2.6)=-3.0
FE_TONEAREST: round(-2.5)=-3.0
FE_TONEAREST: round(-2.4)=-2.0
FE_TONEAREST: round(-1.5)=-2.0
FE_TONEAREST: round(-0.5)=-1.0
FE_TONEAREST: round(0.0)=0.0
FE_TONEAREST: round(0.5)=1.0
FE_TONEAREST: round(1.4)=1.0
FE_TONEAREST: round(1.5)=2.0
FE_TONEAREST: round(1.6)=2.0
FE_TONEAREST: round(2.5)=3.0
FE_TONEAREST: round(3.5)=4.0
FE_TONEAREST: round(4.5)=5.0
FE_TONEAREST: roundf(-4.5)=-5.0
FE_TONEAREST: roundf(-3.6)=-4.0
FE_TONEAREST: roundf(-3.5)=-4.0
FE_TONEAREST: roundf(-3.4)=-3.0
FE_TONEAREST: roundf(-2.6)=-3.0
FE_TONEAREST: roundf(-2.5)=-3.0
FE_TONEAREST: roundf(-2.4)=-2.0
FE_TONEAREST: roundf(-1.5)=-2.0
FE_TONEAREST: roundf(-0.5)=-1.0
FE_TONEAREST: roundf(0.0)=0.0
FE_TONEAREST: roundf(0.5)=1.0
FE_TONEAREST: roundf(1.4)=1.0
FE_TONEAREST: roundf(1.5)=2.0
FE_TONEAREST: roundf(1.6)=2.0
FE_TONEAREST: roundf(2.5)=3.0
FE_TONEAREST: roundf(3.5)=4.0
FE_TONEAREST: roundf(4.5)=5.0
FE_TONEAREST: rint(-4.5)=-4.0
FE_TONEAREST: rint(-3.6)=-4.0
FE_TONEAREST: rint(-3.5)=-4.0
FE_TONEAREST: rint(-3.4)=-3.0
FE_TONEAREST: rint(-2.6)=-3.0
FE_TONEAREST: rint(-2.5)=-2.0
FE_TONEAREST: rint(-2.4)=-2.0
FE_TONEAREST: rint(-1.5)=-2.0
FE_TONEAREST: rint(-0.5)=-0.0
FE_TONEAREST: rint(0.0)=0.0
FE_TONEAREST: rint(0.5)=0.0
FE_TONEAREST: rint(1.4)=1.0
FE_TONEAREST: rint(1.5)=2.0
FE_TONEAREST: rint(1.6)=2.0
FE_TONEAREST: rint(2.5)=2.0
FE_TONEAREST: rint(3.5)=4.0
FE_TONEAREST: rint(4.5)=4.0
FE_TONEAREST: rintf(-4.5)=-4.0
FE_TONEAREST: rintf(-3.6)=-4.0
FE_TONEAREST: rintf(-3.5)=-4.0
FE_TONEAREST: rintf(-3.4)=-3.0
FE_TONEAREST: rintf(-2.6)=-3.0
FE_TONEAREST: rintf(-2.5)=-2.0
FE_TONEAREST: rintf(-2.4)=-2.0
FE_TONEAREST: rintf(-1.5)=-2.0
FE_TONEAREST: rintf(-0.5)=-0.0
FE_TONEAREST: rintf(0.0)=0.0
FE_TONEAREST: rintf(0.5)=0.0
FE_TONEAREST: rintf(1.4)=1.0
FE_TONEAREST: rintf(1.5)=2.0
FE_TONEAREST: rintf(1.6)=2.0
FE_TONEAREST: rintf(2.5)=2.0
FE_TONEAREST: rintf(3.5)=4.0
FE_TONEAREST: rintf(4.5)=4.0
FE_TONEAREST: lrint(-4.5)=-4
FE_TONEAREST: lrint(-3.6)=-4
FE_TONEAREST: lrint(-3.5)=-4
FE_TONEAREST: lrint(-3.4)=-3
FE_TONEAREST: lrint(-2.6)=-3
FE_TONEAREST: lrint(-2.5)=-2
FE_TONEAREST: lrint(-2.4)=-2
FE_TONEAREST: lrint(-1.5)=-2
FE_TONEAREST: lrint(-0.5)=0
FE_TONEAREST: lrint(0.0)=0
FE_TONEAREST: lrint(0.5)=0
FE_TONEAREST: lrint(1.4)=1
FE_TONEAREST: lrint(1.5)=2
FE_TONEAREST: lrint(1.6)=2
FE_TONEAREST: lrint(2.5)=2
FE_TONEAREST: lrint(3.5)=4
FE_TONEAREST: lrint(4.5)=4
FE_TONEAREST: lrintf(-4.5)=-4
FE_TONEAREST: lrintf(-3.6)=-4
FE_TONEAREST: lrintf(-3.5)=-4
FE_TONEAREST: lrintf(-3.4)=-3
FE_TONEAREST: lrintf(-2.6)=-3
FE_TONEAREST: lrintf(-2.5)=-2
FE_TONEAREST: lrintf(-2.4)=-2
FE_TONEAREST: lrintf(-1.5)=-2
FE_TONEAREST: lrintf(-0.5)=0
FE_TONEAREST: lrintf(0.0)=0
FE_TONEAREST: lrintf(0.5)=0
FE_TONEAREST: lrintf(1.4)=1
FE_TONEAREST: lrintf(1.5)=2
FE_TONEAREST: lrintf(1.6)=2
FE_TONEAREST: lrintf(2.5)=2
FE_TONEAREST: lrintf(3.5)=4
FE_TONEAREST: lrintf(4.5)=4
FE_TONEAREST: llrint(-4.5)=-4
FE_TONEAREST: llrint(-3.6)=-4
FE_TONEAREST: llrint(-3.5)=-4
FE_TONEAREST: llrint(-3.4)=-3
FE_TONEAREST: llrint(-2.6)=-3
FE_TONEAREST: llrint(-2.5)=-2
FE_TONEAREST: llrint(-2.4)=-2
FE_TONEAREST: llrint(-1.5)=-2
FE_TONEAREST: llrint(-0.5)=0
FE_TONEAREST: llrint(0.0)=0
FE_TONEAREST: llrint(0.5)=0
FE_TONEAREST: llrint(1.4)=1
FE_TONEAREST: llrint(1.5)=2
FE_TONEAREST: llrint(1.6)=2
FE_TONEAREST: llrint(2.5)=2
FE_TONEAREST: llrint(3.5)=4
FE_TONEAREST: llrint(4.5)=4
FE_TONEAREST: llrintf(-4.5)=-4
FE_TONEAREST: llrintf(-3.6)=-4
FE_TONEAREST: llrintf(-3.5)=-4
FE_TONEAREST: llrintf(-3.4)=-3
FE_TONEAREST: llrintf(-2.6)=-3
FE_TONEAREST: llrintf(-2.5)=-2
FE_TONEAREST: llrintf(-2.4)=-2
FE_TONEAREST: llrintf(-1.5)=-2
FE_TONEAREST: llrintf(-0.5)=0
FE_TONEAREST: llrintf(0.0)=0
FE_TONEAREST: llrintf(0.5)=0
FE_TONEAREST: llrintf(1.4)=1
FE_TONEAREST: llrintf(1.5)=2
FE_TONEAREST: llrintf(1.6)=2
FE_TONEAREST: llrintf(2.5)=2
FE_TONEAREST: llrintf(3.5)=4
FE_TONEAREST: llrintf(4.5)=4
3.141593 = 3.000000 + 0.141593
-3.141593 = -3.000000 + -0.141593
' in 'Initial rounding mode is FE_TONEAREST
fesetround(FE_TONEAREST) returned 0, fegetround() afterwards returns FE_TONEAREST. Test results:
FE_TONEAREST: round(-4.5)=-5.0
FE_TONEAREST: round(-3.6)=-4.0
FE_TONEAREST: round(-3.5)=-4.0
FE_TONEAREST: round(-3.4)=-3.0
FE_TONEAREST: round(-2.6)=-3.0
FE_TONEAREST: round(-2.5)=-3.0
FE_TONEAREST: round(-2.4)=-2.0
FE_TONEAREST: round(-1.5)=-2.0
FE_TONEAREST: round(-0.5)=-1.0
FE_TONEAREST: round(0.0)=0.0
FE_TONEAREST: round(0.5)=1.0
FE_TONEAREST: round(1.4)=1.0
FE_TONEAREST: round(1.5)=2.0
FE_TONEAREST: round(1.6)=2.0
FE_TONEAREST: round(2.5)=3.0
FE_TONEAREST: round(3.5)=4.0
FE_TONEAREST: round(4.5)=5.0
FE_TONEAREST: roundf(-4.5)=-5.0
FE_TONEAREST: roundf(-3.6)=-4.0
FE_TONEAREST: roundf(-3.5)=-4.0
FE_TONEAREST: roundf(-3.4)=-3.0
FE_TONEAREST: roundf(-2.6)=-3.0
FE_TONEAREST: roundf(-2.5)=-3.0
FE_TONEAREST: roundf(-2.4)=-2.0
FE_TONEAREST: roundf(-1.5)=-2.0
FE_TONEAREST: roundf(-0.5)=-1.0
FE_TONEAREST: roundf(0.0)=0.0
FE_TONEAREST: roundf(0.5)=1.0
FE_TONEAREST: roundf(1.4)=1.0
FE_TONEAREST: roundf(1.5)=2.0
FE_TONEAREST: roundf(1.6)=2.0
FE_TONEAREST: roundf(2.5)=3.0
FE_TONEAREST: roundf(3.5)=4.0
FE_TONEAREST: roundf(4.5)=5.0
FE_TONEAREST: rint(-4.5)=-4.0
FE_TONEAREST: rint(-3.6)=-4.0
FE_TONEAREST: rint(-3.5)=-4.0
FE_TONEAREST: rint(-3.4)=-3.0
FE_TONEAREST: rint(-2.6)=-3.0
FE_TONEAREST: rint(-2.5)=-2.0
FE_TONEAREST: rint(-2.4)=-2.0
FE_TONEAREST: rint(-1.5)=-2.0
FE_TONEAREST: rint(-0.5)=-0.0
FE_TONEAREST: rint(0.0)=0.0
FE_TONEAREST: rint(0.5)=0.0
FE_TONEAREST: rint(1.4)=1.0
FE_TONEAREST: rint(1.5)=2.0
FE_TONEAREST: rint(1.6)=2.0
FE_TONEAREST: rint(2.5)=2.0
FE_TONEAREST: rint(3.5)=4.0
FE_TONEAREST: rint(4.5)=4.0
FE_TONEAREST: rintf(-4.5)=-5.0
FE_TONEAREST: rintf(-3.6)=-4.0
FE_TONEAREST: rintf(-3.5)=-4.0
FE_TONEAREST: rintf(-3.4)=-3.0
FE_TONEAREST: rintf(-2.6)=-3.0
FE_TONEAREST: rintf(-2.5)=-3.0
FE_TONEAREST: rintf(-2.4)=-2.0
FE_TONEAREST: rintf(-1.5)=-2.0
FE_TONEAREST: rintf(-0.5)=-1.0
FE_TONEAREST: rintf(0.0)=0.0
FE_TONEAREST: rintf(0.5)=1.0
FE_TONEAREST: rintf(1.4)=1.0
FE_TONEAREST: rintf(1.5)=2.0
FE_TONEAREST: rintf(1.6)=2.0
FE_TONEAREST: rintf(2.5)=3.0
FE_TONEAREST: rintf(3.5)=4.0
FE_TONEAREST: rintf(4.5)=5.0
FE_TONEAREST: lrint(-4.5)=-5
FE_TONEAREST: lrint(-3.6)=-4
FE_TONEAREST: lrint(-3.5)=-4
FE_TONEAREST: lrint(-3.4)=-3
FE_TONEAREST: lrint(-2.6)=-3
FE_TONEAREST: lrint(-2.5)=-3
FE_TONEAREST: lrint(-2.4)=-2
FE_TONEAREST: lrint(-1.5)=-2
FE_TONEAREST: lrint(-0.5)=-1
FE_TONEAREST: lrint(0.0)=0
FE_TONEAREST: lrint(0.5)=1
FE_TONEAREST: lrint(1.4)=1
FE_TONEAREST: lrint(1.5)=2
FE_TONEAREST: lrint(1.6)=2
FE_TONEAREST: lrint(2.5)=3
FE_TONEAREST: lrint(3.5)=4
FE_TONEAREST: lrint(4.5)=5
FE_TONEAREST: lrintf(-4.5)=-5
FE_TONEAREST: lrintf(-3.6)=-4
FE_TONEAREST: lrintf(-3.5)=-4
FE_TONEAREST: lrintf(-3.4)=-3
FE_TONEAREST: lrintf(-2.6)=-3
FE_TONEAREST: lrintf(-2.5)=-3
FE_TONEAREST: lrintf(-2.4)=-2
FE_TONEAREST: lrintf(-1.5)=-2
FE_TONEAREST: lrintf(-0.5)=-1
FE_TONEAREST: lrintf(0.0)=0
FE_TONEAREST: lrintf(0.5)=1
FE_TONEAREST: lrintf(1.4)=1
FE_TONEAREST: lrintf(1.5)=2
FE_TONEAREST: lrintf(1.6)=2
FE_TONEAREST: lrintf(2.5)=3
FE_TONEAREST: lrintf(3.5)=4
FE_TONEAREST: lrintf(4.5)=5
FE_TONEAREST: llrint(-4.5)=-5
FE_TONEAREST: llrint(-3.6)=-4
FE_TONEAREST: llrint(-3.5)=-4
FE_TONEAREST: llrint(-3.4)=-3
FE_TONEAREST: llrint(-2.6)=-3
FE_TONEAREST: llrint(-2.5)=-3
FE_TONEAREST: llrint(-2.4)=-2
FE_TONEAREST: llrint(-1.5)=-2
FE_TONEAREST: llrint(-0.5)=-1
FE_TONEAREST: llrint(0.0)=0
FE_TONEAREST: llrint(0.5)=1
FE_TONEAREST: llrint(1.4)=1
FE_TONEAREST: llrint(1.5)=2
FE_TONEAREST: llrint(1.6)=2
FE_TONEAREST: llrint(2.5)=3
FE_TONEAREST: llrint(3.5)=4
FE_TONEAREST: llrint(4.5)=5
FE_TONEAREST: llrintf(-4.5)=-5
FE_TONEAREST: llrintf(-3.6)=-4
FE_TONEAREST: llrintf(-3.5)=-4
FE_TONEAREST: llrintf(-3.4)=-3
FE_TONEAREST: llrintf(-2.6)=-3
FE_TONEAREST: llrintf(-2.5)=-3
FE_TONEAREST: llrintf(-2.4)=-2
FE_TONEAREST: llrintf(-1.5)=-2
FE_TONEAREST: llrintf(-0.5)=-1
FE_TONEAREST: llrintf(0.0)=0
FE_TONEAREST: llrintf(0.5)=1
FE_TONEAREST: llrintf(1.4)=1
FE_TONEAREST: llrintf(1.5)=2
FE_TONEAREST: llrintf(1.6)=2
FE_TONEAREST: llrintf(2.5)=3
FE_TONEAREST: llrintf(3.5)=4
FE_TONEAREST: llrintf(4.5)=5
3.141593 = 3.000000 + 0.141593
-3.141593 = -3.000000 + -0.141593
', diff:

--- expected
+++ actual
@@ -51,91 +51,91 @@
 FE_TONEAREST: rint(2.5)=2.0
 FE_TONEAREST: rint(3.5)=4.0
 FE_TONEAREST: rint(4.5)=4.0
-FE_TONEAREST: rintf(-4.5)=-4.0
+FE_TONEAREST: rintf(-4.5)=-5.0
 FE_TONEAREST: rintf(-3.6)=-4.0
 FE_TONEAREST: rintf(-3.5)=-4.0
 FE_TONEAREST: rintf(-3.4)=-3.0
 FE_TONEAREST: rintf(-2.6)=-3.0
-FE_TONEAREST: rintf(-2.5)=-2.0
+FE_TONEAREST: rintf(-2.5)=-3.0
 FE_TONEAREST: rintf(-2.4)=-2.0
 FE_TONEAREST: rintf(-1.5)=-2.0
-FE_TONEAREST: rintf(-0.5)=-0.0
+FE_TONEAREST: rintf(-0.5)=-1.0
 FE_TONEAREST: rintf(0.0)=0.0
-FE_TONEAREST: rintf(0.5)=0.0
+FE_TONEAREST: rintf(0.5)=1.0
 FE_TONEAREST: rintf(1.4)=1.0
 FE_TONEAREST: rintf(1.5)=2.0
 FE_TONEAREST: rintf(1.6)=2.0
-FE_TONEAREST: rintf(2.5)=2.0
+FE_TONEAREST: rintf(2.5)=3.0
 FE_TONEAREST: rintf(3.5)=4.0
-FE_TONEAREST: rintf(4.5)=4.0
-FE_TONEAREST: lrint(-4.5)=-4
+FE_TONEAREST: rintf(4.5)=5.0
+FE_TONEAREST: lrint(-4.5)=-5
 FE_TONEAREST: lrint(-3.6)=-4
 FE_TONEAREST: lrint(-3.5)=-4
 FE_TONEAREST: lrint(-3.4)=-3
 FE_TONEAREST: lrint(-2.6)=-3
-FE_TONEAREST: lrint(-2.5)=-2
+FE_TONEAREST: lrint(-2.5)=-3
 FE_TONEAREST: lrint(-2.4)=-2
 FE_TONEAREST: lrint(-1.5)=-2
-FE_TONEAREST: lrint(-0.5)=0
+FE_TONEAREST: lrint(-0.5)=-1
 FE_TONEAREST: lrint(0.0)=0
-FE_TONEAREST: lrint(0.5)=0
+FE_TONEAREST: lrint(0.5)=1
 FE_TONEAREST: lrint(1.4)=1
 FE_TONEAREST: lrint(1.5)=2
 FE_TONEAREST: lrint(1.6)=2
-FE_TONEAREST: lrint(2.5)=2
+FE_TONEAREST: lrint(2.5)=3
 FE_TONEAREST: lrint(3.5)=4
-FE_TONEAREST: lrint(4.5)=4
-FE_TONEAREST: lrintf(-4.5)=-4
+FE_TONEAREST: lrint(4.5)=5
+FE_TONEAREST: lrintf(-4.5)=-5
 FE_TONEAREST: lrintf(-3.6)=-4
 FE_TONEAREST: lrintf(-3.5)=-4
 FE_TONEAREST: lrintf(-3.4)=-3
 FE_TONEAREST: lrintf(-2.6)=-3
-FE_TONEAREST: lrintf(-2.5)=-2
+FE_TONEAREST: lrintf(-2.5)=-3
 FE_TONEAREST: lrintf(-2.4)=-2
 FE_TONEAREST: lrintf(-1.5)=-2
-FE_TONEAREST: lrintf(-0.5)=0
+FE_TONEAREST: lrintf(-0.5)=-1
 FE_TONEAREST: lrintf(0.0)=0
-FE_TONEAREST: lrintf(0.5)=0
+FE_TONEAREST: lrintf(0.5)=1
 FE_TONEAREST: lrintf(1.4)=1
 FE_TONEAREST: lrintf(1.5)=2
 FE_TONEAREST: lrintf(1.6)=2
-FE_TONEAREST: lrintf(2.5)=2
+FE_TONEAREST: lrintf(2.5)=3
 FE_TONEAREST: lrintf(3.5)=4
-FE_TONEAREST: lrintf(4.5)=4
-FE_TONEAREST: llrint(-4.5)=-4
+FE_TONEAREST: lrintf(4.5)=5
+FE_TONEAREST: llrint(-4.5)=-5
 FE_TONEAREST: llrint(-3.6)=-4
 FE_TONEAREST: llrint(-3.5)=-4
 FE_TONEAREST: llrint(-3.4)=-3
 FE_TONEAREST: llrint(-2.6)=-3
-FE_TONEAREST: llrint(-2.5)=-2
+FE_TONEAREST: llrint(-2.5)=-3
 FE_TONEAREST: llrint(-2.4)=-2
 FE_TONEAREST: llrint(-1.5)=-2
-FE_TONEAREST: llrint(-0.5)=0
+FE_TONEAREST: llrint(-0.5)=-1
 FE_TONEAREST: llrint(0.0)=0
-FE_TONEAREST: llrint(0.5)=0
+FE_TONEAREST: llrint(0.5)=1
 FE_TONEAREST: llrint(1.4)=1
 FE_TONEAREST: llrint(1.5)=2
 FE_TONEAREST: llrint(1.6)=2
-FE_TONEAREST: llrint(2.5)=2
+FE_TONEAREST: llrint(2.5)=3
 FE_TONEAREST: llrint(3.5)=4
-FE_TONEAREST: llrint(4.5)=4
-FE_TONEAREST: llrintf(-4.5)=-4
+FE_TONEAREST: llrint(4.5)=5
+FE_TONEAREST: llrintf(-4.5)=-5
 FE_TONEAREST: llrintf(-3.6)=-4
 FE_TONEAREST: llrintf(-3.5)=-4
 FE_TONEAREST: llrintf(-3.4)=-3
 FE_TONEAREST: llrintf(-2.6)=-3
-FE_TONEAREST: llrintf(-2.5)=-2
+FE_TONEAREST: llrintf(-2.5)=-3
 FE_TONEAREST: llrintf(-2.4)=-2
 FE_TONEAREST: llrintf(-1.5)=-2
-FE_TONEAREST: llrintf(-0.5)=0
+FE_TONEAREST: llrintf(-0.5)=-1
 FE_TONEAREST: llrintf(0.0)=0
-FE_TONEAREST: llrintf(0.5)=0
+FE_TONEAREST: llrintf(0.5)=1
 FE_TONEAREST: llrintf(1.4)=1
 FE_TONEAREST: llrintf(1.5)=2
 FE_TONEAREST: llrintf(1.6)=2
-FE_TONEAREST: llrintf(2.5)=2
+FE_TONEAREST: llrintf(2.5)=3
 FE_TONEAREST: llrintf(3.5)=4
-FE_TONEAREST: llrintf(4.5)=4
+FE_TONEAREST: llrintf(4.5)=5
 3.141593 = 3.000000 + 0.141593
 -3.141593 = -3.000000 + -0.141593




----------------------------------------------------------------------
Ran 1 test in 16.034s

FAILED (errors=1)
```

i.e. it looks like emterpreter is performing `rint` rounding away from zero instead of rounding to even.

**Comment by juj** [comment]
For a small test case:

```c
#include <stdio.h>
#include <math.h>

int main()
{
	printf("%f\n", rintf(-4.5f));
}
```

Building and running in node with `em++ a.cpp -o a.js` prints `-4` as expected (round to even), whereas building and running with `em++ a.cpp -o a.js -s EMTERPRETIFY=1` prints out `-5`, i.e. it's rounding away from zero.

**Comment by kripken** [comment]
Still running tests to confirm, but I think a fix for that issue is in https://github.com/kripken/emscripten/commit/895acd42538b230c257f934d4b954d6e7f8f8074 (compiler-emitted constants are always `+.5`, while in the handwritten `_rintf` it had just `.5`).

**Comment by kripken** [comment]
Tests look good, opened #5725.
