### ISSUE TITLE
Websockets not working

### ISSUE THREAD

**Issue by felipellrocha** [emscripten-core/emscripten#5776]
I've been trying to port a piece of code that connects to a server using WebSockets. But, even though my server works just fine with every other connection method I use (javascript, and the native build of my project), I cannot get it to work when building using WebAssembly. Am I missing something here?

It doesn't even try to connect to the correct path:
```
main.js:13235 easywsclient: connecting: host=localhost port=9001 path=/game/3c51327e-00ab-41e2-b16b-92c9c3cee849
emrun_printErr @ main.js:13235
put_char @ main.js:4978
write @ main.js:4898
write @ main.js:6921
doWritev @ main.js:7726
___syscall146 @ main.js:8243
<WASM UNNAMED> @ wasm-00604b7a-2335:106
<WASM UNNAMED> @ wasm-00604b7a-2366:147
<WASM UNNAMED> @ wasm-00604b7a-2436:24
<WASM UNNAMED> @ wasm-00604b7a-593:343
<WASM UNNAMED> @ wasm-00604b7a-592:5
<WASM UNNAMED> @ wasm-00604b7a-3039:9
Module.Module.dynCall_iii @ main.js:12895
invoke_iii @ main.js:12434
<WASM UNNAMED> @ wasm-00604b7a-624:475
<WASM UNNAMED> @ wasm-00604b7a-3032:13
Module.Module.dynCall_viiiiii @ main.js:12888
invoke_viiiiii @ main.js:12371
<WASM UNNAMED> @ wasm-00604b7a-588:97
Module.Module.__GLOBAL__sub_I_main_cpp @ main.js:12830
func @ main.js:2175
callRuntimeCallbacks @ main.js:1459
ensureInitRuntime @ main.js:1489
doRun @ main.js:13082
run @ main.js:13106
runCaller @ main.js:13002
removeRunDependency @ main.js:1750
processPackageData @ main.js:167
(anonymous) @ main.js:95
xhr.onload @ main.js:80
XMLHttpRequest.send (async)
(anonymous) @ VM319:1
fetchRemotePackage @ main.js:85
loadPackage @ main.js:93
(anonymous) @ main.js:191
Module @ main.js:193
script.onload @ index.js:60
localhost/:1 WebSocket connection to 'ws://localhost:9001/' failed: WebSocket is closed before the connection is established.
main.js:9797 Uncaught TypeError: Cannot read property 'emit' of undefined
    at WebSocket.peer.socket.onerror (http://localhost:9000/engine/main.js:9797:35)
    at Object.close (http://localhost:9000/engine/main.js:9856:27)
    at Object.close (http://localhost:9000/engine/main.js:9600:25)
    at Object.close (http://localhost:9000/engine/main.js:6860:31)
    at ___syscall6 (http://localhost:9000/engine/main.js:8085:10)
    at wasm-function[2386]:44
    at wasm-function[3021]:13
    at Object.Module.Module.dynCall_ii (http://localhost:9000/engine/main.js:12877:89)
    at invoke_ii (http://localhost:9000/engine/main.js:12272:32)
    at wasm-function[593]:1048
peer.socket.onerror @ main.js:9797
close @ main.js:9856
close @ main.js:9600
close @ main.js:6860
___syscall6 @ main.js:8085
<WASM UNNAMED> @ wasm-00604b7a-2386:24
<WASM UNNAMED> @ wasm-00604b7a-3021:8
Module.Module.dynCall_ii @ main.js:12877
invoke_ii @ main.js:12272
<WASM UNNAMED> @ wasm-00604b7a-593:500
<WASM UNNAMED> @ wasm-00604b7a-592:5
<WASM UNNAMED> @ wasm-00604b7a-3039:9
Module.Module.dynCall_iii @ main.js:12895
invoke_iii @ main.js:12434
<WASM UNNAMED> @ wasm-00604b7a-624:475
<WASM UNNAMED> @ wasm-00604b7a-3032:13
Module.Module.dynCall_viiiiii @ main.js:12888
invoke_viiiiii @ main.js:12371
<WASM UNNAMED> @ wasm-00604b7a-588:97
Module.Module.__GLOBAL__sub_I_main_cpp @ main.js:12830
func @ main.js:2175
callRuntimeCallbacks @ main.js:1459
ensureInitRuntime @ main.js:1489
doRun @ main.js:13082
run @ main.js:13106
runCaller @ main.js:13002
removeRunDependency @ main.js:1750
processPackageData @ main.js:167
(anonymous) @ main.js:95
xhr.onload @ main.js:80
XMLHttpRequest.send (async)
(anonymous) @ VM319:1
fetchRemotePackage @ main.js:85
loadPackage @ main.js:93
(anonymous) @ main.js:191
Module @ main.js:193
script.onload @ index.js:60
main.js:9788 Uncaught TypeError: Cannot read property 'emit' of undefined
    at WebSocket.peer.socket.onclose (http://localhost:9000/engine/main.js:9788:35)
    at Object.close (http://localhost:9000/engine/main.js:9856:27)
    at Object.close (http://localhost:9000/engine/main.js:9600:25)
    at Object.close (http://localhost:9000/engine/main.js:6860:31)
    at ___syscall6 (http://localhost:9000/engine/main.js:8085:10)
    at wasm-function[2386]:44
    at wasm-function[3021]:13
    at Object.Module.Module.dynCall_ii (http://localhost:9000/engine/main.js:12877:89)
    at invoke_ii (http://localhost:9000/engine/main.js:12272:32)
    at wasm-function[593]:1048
peer.socket.onclose @ main.js:9788
close @ main.js:9856
close @ main.js:9600
close @ main.js:6860
___syscall6 @ main.js:8085
<WASM UNNAMED> @ wasm-00604b7a-2386:24
<WASM UNNAMED> @ wasm-00604b7a-3021:8
Module.Module.dynCall_ii @ main.js:12877
invoke_ii @ main.js:12272
<WASM UNNAMED> @ wasm-00604b7a-593:500
<WASM UNNAMED> @ wasm-00604b7a-592:5
<WASM UNNAMED> @ wasm-00604b7a-3039:9
Module.Module.dynCall_iii @ main.js:12895
invoke_iii @ main.js:12434
<WASM UNNAMED> @ wasm-00604b7a-624:475
<WASM UNNAMED> @ wasm-00604b7a-3032:13
Module.Module.dynCall_viiiiii @ main.js:12888
invoke_viiiiii @ main.js:12371
<WASM UNNAMED> @ wasm-00604b7a-588:97
Module.Module.__GLOBAL__sub_I_main_cpp @ main.js:12830
func @ main.js:2175
callRuntimeCallbacks @ main.js:1459
ensureInitRuntime @ main.js:1489
doRun @ main.js:13082
run @ main.js:13106
runCaller @ main.js:13002
removeRunDependency @ main.js:1750
processPackageData @ main.js:167
(anonymous) @ main.js:95
xhr.onload @ main.js:80
XMLHttpRequest.send (async)
(anonymous) @ VM319:1
fetchRemotePackage @ main.js:85
loadPackage @ main.js:93
(anonymous) @ main.js:191
Module @ main.js:193
script.onload @ index.js:60
main.js:13235 Unable to connect to localhost:9001
```

Even though it does so natively just fine...

**Comment by kripken** [comment]
Might be worth looking at the socket tests (`python tests/runner.py sockets`, in `tests/test_sockets.py`). Those should pass, and the examples should all be working code.

**Comment by felipellrocha** [comment]
It looks like after I set my `Module`'s config to: `{ websocket: { url: '...some valid url...' } }` it tried to connect to the right place. But now my websocket server is rejecting connections:

```
registering
[]
websocket: close 1006 (abnormal closure): unexpected EOF
unregistering
```

Where `[]` is an empty message

**Comment by felipellrocha** [comment]
```
  struct sockaddr_in addr;
  addr.sin_family = AF_INET;

  socket_t sockfd = socket(PF_INET, SOCK_STREAM, IPPROTO_TCP);
  if (sockfd == INVALID_SOCKET) {
    closesocket(sockfd);
  }
  int res = connect(sockfd, (struct sockaddr *)&addr, sizeof(addr));
  int flag = 1;
  setsockopt(sockfd, IPPROTO_TCP, TCP_NODELAY, (char*) &flag, sizeof(flag));
```

This is how I'm trying to open my socket

**Comment by felipellrocha** [comment]
This turned out to be an issue with my server not accepting the `binary` subprotocol. It took me a while to figure out that that was the subprotocol used by Emscripten, though. It would be nice if this was more appropriately detailed in documentation

**Comment by kripken** [comment]
The place where you looked for those docs and didn't find them is probably the right place to add docs for this. Do you want to submit a PR with that?
