### ISSUE TITLE
Building Binaryen fails #2 (regression)

### ISSUE THREAD

**Issue by Moeplhausen** [emscripten-core/emscripten#5923]
I have switched to emscripten  1.37.24-1 (archlinux package).

After that the command `embuilder.py build binaryen` stopped working. Error:

```
[ 76%] Built target wasm-dis
Scanning dependencies of target wasm-ctor-eval
[ 77%] Building CXX object CMakeFiles/wasm-ctor-eval.dir/src/tools/wasm-ctor-eval.cpp.o
In file included from /home/mattis/.emscripten_ports/binaryen/binaryen-version_39/src/tools/wasm-opt.cpp:36:0:
/home/emscripten/.emscripten_ports/binaryen/binaryen-version_39/src/tools/translate-to-fuzz.h: In member function ‘wasm::Expression* wasm::TranslateToFuzzReader::makeConst(wasm::WasmType)’:
/home/emscripten/.emscripten_ports/binaryen/binaryen-version_39/src/tools/translate-to-fuzz.h:1270:5: error: ‘first’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   T pickGivenNum(size_t num, T first, Args... args) {
     ^~~~~~~~~~~~
[ 78%] Linking CXX executable bin/wasm-merge
```
and the end result:
```
[ 84%] Built target asm2wasm
make: *** [Makefile:130: all] Error 2
ERROR:root:a problem occurred when using an emscripten-ports library. try to run    emcc --clear-ports    and then run this command again
Traceback (most recent call last):
  File "/usr/lib/emscripten/emcc", line 13, in <module>
    emcc.run()
  File "/usr/lib/emscripten/emcc.py", line 1440, in run
    extra_files_to_link = system_libs.get_ports(shared.Settings)
  File "/usr/lib/emscripten/tools/system_libs.py", line 725, in get_ports
    ret += [f for f in port.get(Ports, settings, shared) if not f.endswith('.txt')]
  File "/usr/lib/emscripten/tools/ports/binaryen.py", line 29, in get
    return [shared.Cache.get('binaryen_tag_' + TAG, create, what='port', extension='.txt')]
  File "/usr/lib/emscripten/tools/cache.py", line 101, in get
    temp = creator()
  File "/usr/lib/emscripten/tools/ports/binaryen.py", line 24, in create
    ports.build_native(os.path.join(ports.get_dir(), 'binaryen', 'binaryen-' + TAG))
  File "/usr/lib/emscripten/tools/system_libs.py", line 712, in build_native
    subprocess.check_call(['cmake', '--build', '.'] + make_args)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--', '-j', '4']' returned non-zero exit status 2
Traceback (most recent call last):
  File "/usr/lib/emscripten/embuilder.py", line 247, in <module>
    build_port('binaryen', None, ['-s', 'WASM=1'])
  File "/usr/lib/emscripten/embuilder.py", line 136, in build_port
    build(C_BARE, [os.path.join('ports-builds', port_name, lib_name)] if lib_name else None, params)
  File "/usr/lib/emscripten/embuilder.py", line 126, in build
    shared.Building.emcc(temp, args, output_filename=temp_js)
  File "/usr/lib/emscripten/tools/shared.py", line 1988, in emcc
    assert os.path.exists(output_filename), 'emcc could not create output file: ' + output_filename
AssertionError: emcc could not create output file: /tmp/tmpPOtKlP.js
embuilder.py build binaryen  202.34s user 8.41s system 304% cpu 1:09.27 total
```

**Comment by Moeplhausen** [comment]
Emscripten 1.37.22-1 works for me. I don't know if there are later version which still work.

**Comment by kripken** [comment]
That's using a fairly recent gcc? Emscripten incoming (after 1.37.24) contains a workaround for a gcc compiler bug, that should fix that. You can also get binaryen master manually and build it (and set `BINARYEN` in `~/.emscripten` to point to it, and it will it instead of getting the default version).

**Comment by Moeplhausen** [comment]
Yes, that is using a very recent gcc:
```
%gcc --version                                                                                                                                                                                  
gcc (GCC) 7.2.1 20171128
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I'll wait for the next emscripten version then.

**Comment by dschuff** [comment]
I just pushed 1.37.25 in order to pick up https://github.com/kripken/emscripten/commit/b1acff26c2c9ee802b20af01e53a6fe276a99335, so you can try again. However if @kripken is referring to https://github.com/WebAssembly/binaryen/commit/e91d1bf256d70d0e1635dcf35a3d253d11555f58, then that should have been on 1.37.24 already. So it's possible that there is a different issue? But in any case you'll want to check that you are building with that revision.

**Comment by Moeplhausen** [comment]
There hasn't been a package upgrade on archlinux yet. I was able to successfully compile  https://github.com/WebAssembly/binaryen/archive/version_40.zip (I suppose that would be downloaded with 1.37.25) though.
I guess I can be fairly sure that it would be fixed with 1.37.25 then. Thank you :)

**Comment by Moeplhausen** [comment]
So, emscripten 1.37.25 actually still loads binaryen version 39, which still has that issue about the first variable not being initialized resulting in an error.

**Comment by kripken** [comment]
Oh, yes, then this needs an update to 40. That happened on incoming after 1.37.25 (no 1.37.26 yet).
