### ISSUE TITLE
Please is there a work around for passing args to emconfigure ./configure

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [emscripten-core/emscripten#6453]
Please when I run this script, i get this error:

```
#!/bin/bash

set -e

CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Delete all -Werror strings from configure.ac
# Don't treat warnings as errors!
sed -i "s/ -Werror//" $CWD/configure.ac

# Generate automake files
autoreconf -i

# Configure: Disable all codes except QR code, disable all unneccesary features
# This may produce red error messages, but it is safe to ignore them (it assumes that
# emscripten is GCC and uses invalid parameters on it)
emconfigure ./configure --enable-codes=ean --without-x --without-jpeg --without-imagemagick --without-npapi --without-gtk --without-python --without-qt --without-xshm --disable-video --disable-pthread

# Compile!
emmake make

# Glue javascript and compiled code together
emcc -O1 -I`pwd`/include ./templates/zbar-main.c ./zbar/.libs/libzbar.a --js-library ./templates/zbar-callbacks.js -o ./decoder-content.js
sed '/\/\* EMSCRIPTEN_CODE \*\//r ./decoder-content.js' ./templates/zbar-processor-wrapper.js > ./decoder.js
```

**Error**

```
$ ./generate-decoder.sh
ERROR:root:Exception thrown when invoking Popen in configure with args: "./configure --enable-codes=ean --without-x --without-jpeg --without-imagemagick --without-npapi --without-gtk --without-python --without-qt --without-xshm --disable-video --disable-pthread"!
Traceback (most recent call last):
  File "C:/Github/emsdk/emscripten/1.37.36/emconfigure", line 10, in <module>
    python_selector.run(__file__)
  File "C:\Github\emsdk\emscripten\1.37.36\tools\python_selector.py", line 43, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "C:\Github\emsdk\emscripten\1.37.36\tools\python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "C:\Github\emsdk\emscripten\1.37.36\emconfigure.py", line 47, in run
    shared.Building.configure(sys.argv[1:])
  File "C:\Github\emsdk\emscripten\1.37.36\tools\shared.py", line 1520, in configure
    process = Popen(args, stdout=None if EM_BUILD_VERBOSE_LEVEL >= 2 else stdout, stderr=None if EM_BUILD_VERBOSE_LEVEL >= 1 else stderr, env=env)
  File "C:\Github\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Github\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application

```

Please is there a work around for passing args to emconfigure ./configure on windows?

**Comment by brion** [comment]
I haven't tested this, but you might try inserting `bash` or `sh` manually in that command line, something like:

```
emconfigure sh ./configure --options --go --here
```

**Comment by cancerberoSgx** [comment]
You are trying to execute a shell script in windows. 

I recommend using emscripten docker container instead the native system, particularly on windows. Is easier and safer.

unix:
docker run --rm --workdir /code -v "$PWD":/code "trzeci/emscripten:latest" emconfigure ./configure --options --go --here

windows:
docker run --rm --workdir /code -v "$(get-location):/code" "trzeci/emscripten:latest" emconfigure ./configure --options --go --here
