### ISSUE TITLE
Need help compiling ezquake with emmake

### ISSUE THREAD

**Issue by WormChickenWizard** [emscripten-core/emscripten#6560]
So before I begin to explain my issue. I'd like to point out that I am new to coding in c and using emscripten.

Anyways, i have been trying to compile ezquake with emscipten and im able to follow the instructions on compiling ezquake normally using this command:`EZ_CONFIG_FILE=.config_windows make` but when I try to use `emmake EZ_CONFIG_FILE=.config_windows make` it gives me this: 
```


  emmake is a helper for make, setting various environment
  variables so that emcc etc. are used. Typical usage:

    emmake make [FLAGS]

  (but you can run any command instead of make)


ERROR:root:Exception thrown when invoking Popen in make with args: "EZ_CONFIG_FILE=.config_windows make"!
Traceback (most recent call last):
  File "/home/justin/emsdk/emscripten/1.38.1/emmake", line 9, in <module>
    python_selector.run(__file__)
  File "/home/justin/emsdk/emscripten/1.38.1/tools/python_selector.py", line 38, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "/home/justin/emsdk/emscripten/1.38.1/tools/python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "/home/justin/emsdk/emscripten/1.38.1/emmake.py", line 42, in run
    shared.Building.make(sys.argv[1:])
  File "/home/justin/emsdk/emscripten/1.38.1/tools/shared.py", line 1572, in make
    process = Popen(args, stdout=None if EM_BUILD_VERBOSE_LEVEL >= 2 else stdout, stderr=None if EM_BUILD_VERBOSE_LEVEL >= 1 else stderr, env=env, shell=WINDOWS)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I don't know whether I am using the command wrong or if its something else.
Any help whatsoever is appreciated.

Link to ezquake github for reference:
[https://github.com/ezQuake/ezquake-source](url)

**Comment by WormChickenWizard** [comment]
OK I decided to start over again and try following the Linux compiling instructions instead but now when I try running the command `~/emsdk/emscripten/1.38.1/emmake make -j5` when I am in the ezquake-source directory, it gives me this: 

```
emscripten sdl2-config called with /home/justin/emsdk/emscripten/1.38.1/system/bin/sdl2-config --cflags
Package libpcre was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpcre.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpcre' found
Package expat was not found in the pkg-config search path.
Perhaps you should add the directory containing `expat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'expat' found
Package libpng was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpng.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpng' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
make: Nothing to be done for 'all'.
```

**Comment by kripken** [comment]
Emscripten is a cross-compiler, so it's not enough to have libpng, libcurl etc. installed locally on your system - you need something compatible with the web target. For libpng, there is an existing port to emscripten in ports (basically just add `-s USE_LIBPNG=1` to the emcc command) but for the others, I think you'd need to port them. See http://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#using-libraries
