### ISSUE TITLE
At least on Windows, %PYTHONHOME% needs to be updated by emsdk_env

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [emscripten-core/emscripten#6919]
Considering nobody else has reported this yet, I suppose it may just be my system (I may or may not have added this variable manually at some point - can't remember), even though it seems like it should be universal:
```bash
D:\development\emsdk>emsdk activate latest
Traceback (most recent call last):
  File "D:\development\emsdk\\emsdk", line 7, in <module>
    import sys, optparse, subprocess, os, os.path, errno, zipfile, string, json,
 platform, shutil, tarfile, tempfile, multiprocessing, re, stat, copy
  File "D:\Python\Python27\lib\tarfile.py", line 52, in <module>
    import copy
  File "D:\Python\Python27\lib\copy.py", line 52, in <module>
    import weakref
  File "D:\Python\Python27\lib\weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

I got beyond that with a dirty patch but when I then tried to execute `emcc -v`, I got the same error:
```bash
D:\development\emsdk>emcc -v
Traceback (most recent call last):
  File "D:\development\emsdk\emscripten\1.38.10\emcc.py", line 34, in <module>
    import logging
  File "D:\Python\Python27\lib\logging\__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "D:\Python\Python27\lib\weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

After this, I tried setting `%PYTHONHOME%` to the path where emscripten's Python resides and... ta-da:
```bash
D:\development\emsdk>emcc -v
INFO:root:generating system asset: is_vanilla.txt... (this will be cached in "C:
\Users\Brix\.emscripten_cache\is_vanilla.txt" for subsequent builds)
INFO:root: - ok
INFO:root:(Emscripten: Running sanity checks)
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.10
clang version 6.0.1  (emscripten 1.38.10 : 1.38.10)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: D:\development\emsdk\clang\e1.38.10_64bit
INFO:root:(Emscripten: Running sanity checks)
```

**Comment by timwells** [comment]
Same issue for me and fixed in same way. Thanks for documenting it.  Is there an official documented fix?

**Comment by kripken** [comment]
PR with a fix here would be good - I don't know enough about windows to know how to write it myself.

**Comment by sbc100** [comment]
I believe this should be fixed in https://github.com/emscripten-core/emsdk/pull/600
