### ISSUE TITLE
Error loading tmp file

### ISSUE THREAD

**Issue by treytencarey** [emscripten-core/emscripten#6976]
Emscripten cannot finish building due to the tmp file not being created/found. Here is the log:

> /cygdrive/c/emsdk/emscripten/1.38.11/emcc -fPIC -pthread -Wall -I"C:/emsdk/emscripten/1.38.11/system/include/libc" -I"C:/emsdk/emscripten/1.38.11/system/lib/libc/musl/arch/emscripten" -D__STDC_NO_ATOMICS__ -L. -shared -Wl,-Bsymbolic   -Wl,-soname=libcrypto.so.1.1 \
>         -o libcrypto.so.1.1 -Wl,--version-script=libcrypto.map crypto/aes/aes_cbc.o crypto/aes/aes_cfb.o crypto/aes/aes_core.o ... \
>                  -ldl -pthread
> C:\emsdk\clang\e1.38.11_64bit\llvm-link.exe: @/tmp/tmpgJovJu.response: error: Could not open input file: no such file or directory
> C:\emsdk\clang\e1.38.11_64bit\llvm-link.exe: error loading file '@/tmp/tmpgJovJu.response'
> Traceback (most recent call last):
>   File "/cygdrive/c/emsdk/emscripten/1.38.11/emcc.py", line 3042, in <module>
>     sys.exit(run())
>   File "/cygdrive/c/emsdk/emscripten/1.38.11/emcc.py", line 1586, in run
>     shared.Building.link(linker_inputs, specified_target)
>   File "/cygdrive/c/emsdk/emscripten/1.38.11/tools/shared.py", line 2114, in link
>     output = run_process([LLVM_LINK] + link_args + ['-o', target], stdout=PIPE).stdout
>   File "/cygdrive/c/emsdk/emscripten/1.38.11/tools/shared.py", line 167, in run_process
>     return run_base(cmd, universal_newlines=universal_newlines, check=check, *args, **kw)
>   File "/cygdrive/c/emsdk/emscripten/1.38.11/tools/shared.py", line 162, in run_base
>     result.check_returncode()
>   File "/cygdrive/c/emsdk/emscripten/1.38.11/tools/shared.py", line 148, in check_returncode
>     raise Py2CalledProcessError(returncode=self.returncode, cmd=self.args, output=self.stdout, stderr=self.stderr)
> tools.shared.Py2CalledProcessError: Command '['c:/emsdk/clang/e1.38.11_64bit/llvm-link', '@/tmp/tmpgJovJu.response', '-o', 'libcrypto.so.1.1']' returned non-zero exit status 1
> make[1]: *** [Makefile:759: libcrypto.so] Error 1

(Note that ... in the output above is just a bunch of crypto .o files)

I believe the issue is that the temp file starts with @, but I'm not finding where this is coming from

**Comment by treytencarey** [comment]
Actually that's not the issue. I see the @ is coming from tools/shared.py. I can't figure out why the file isn't being created.

**Comment by treytencarey** [comment]
I found that if I manually change the name (like so):
```
if cmd[1][0] == '@':
  cmd[1] = "C:/cygwin64" + cmd[1][1:]
```
in tools/shared.py before proc = Popen(cmd, *args, **kw), then I get this error:

> C:\emsdk\clang\e1.38.11_64bit\llvm-link.exe: C:/cygwin64/tmp/tmpT1HXlE.response:1:1: error: expected top-level entity
> "crypto/aes/aes_cbc.o"
> ^
> C:\emsdk\clang\e1.38.11_64bit\llvm-link.exe: error loading file 'C:/cygwin64/tmp/tmpT1HXlE.response'
