### ISSUE TITLE
java crashing in CircleCI running closure compiler

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#7232]
I'm seeing this type of failure on a several CircleCI runs.  Not sure if its flaky or consistent yet:

```
test_files (test_core.asm2g) ... ok
base ['-O1', '-s', 'WASM=0', '-s', 'FORCE_FILESYSTEM=1']
[]
['-s', 'MEMFS_APPEND_TO_TYPED_ARRAYS=1']
Traceback (most recent call last):
  File "/root/emscripten/emcc.py", line 3092, in <module>
    sys.exit(run())
  File "/root/emscripten/emcc.py", line 2056, in run
    emterpretify(js_target, optimizer, options)
  File "/root/emscripten/emcc.py", line 2438, in emterpretify
    optimizer.flush('finalizing-emterpreted-code')
  File "/root/emscripten/emcc.py", line 270, in flush
    self.run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "/root/emscripten/emcc.py", line 305, in run_passes
    output_filename=self.in_temp(os.path.basename(final) + '.jsopted.js'))
  File "/root/emscripten/tools/shared.py", line 2341, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "/root/emscripten/tools/js_optimizer.py", line 579, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/root/emscripten/tools/tempfiles.py", line 98, in run_and_clean
    return func()
  File "/root/emscripten/tools/js_optimizer.py", line 579, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/root/emscripten/tools/js_optimizer.py", line 506, in run_on_js
    cld = shared.Building.closure_compiler(cld, pretty='minifyWhitespace' not in passes)
  File "/root/emscripten/tools/shared.py", line 2477, in closure_compiler
    raise Exception('closure compiler error: ' + process.stdout + ' (rc: %d)' % process.returncode)
Exception: closure compiler error: #
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (macroAssembler_x86.hpp:116), pid=3454, tid=3524
#  guarantee(this->is8bit(imm8)) failed: Short forward jump exceeds 8-bit offset
#
# JRE version: OpenJDK Runtime Environment (9.0) (build 9-internal+0-2016-04-14-195246.buildd.src)
# Java VM: OpenJDK 64-Bit Server VM (9-internal+0-2016-04-14-195246.buildd.src, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /tmp/tmpvteii1b6/emscripten_test_asm2i_qe837e1a/hs_err_pid3454.log
#
# Compiler replay data is saved as:
# /tmp/tmpvteii1b6/emscripten_test_asm2i_qe837e1a/replay_pid3454.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

**Comment by kripken** [comment]
I've seen it a few times too - seems flaky I think, not related to changes we made. Java bug tracker mentions an error with that text was fixed a few years ago, and we are installing jdk-9, which seems like it should be new enough...
