### ISSUE TITLE
ctor_evaller.py fails to generate valid js if SPLIT_MEMORY=1

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#7463]
```
/tmp/emscripten_temp/tmpixPguX.ctorEval.js:34032
});
  ^

SyntaxError: Unexpected end of input
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Looks like its assumptions about the structure of the asm.js are invalid in this case

**Comment by kripken** [comment]
Thanks!

Yeah, something's not right there. But really we should remove the SPLIT_MEMORY option, which I asked about on the mailing list a while ago, and seems like no one objects. I'll get a PR up.

**Comment by kripken** [comment]
PR to remove SPLIT_MEMORY: https://github.com/kripken/emscripten/pull/7465
