### ISSUE TITLE
emscripten doesn't support  -fsyntax-only option

### ISSUE THREAD

**Issue by maxim-banaev** [emscripten-core/emscripten#7857]
`-fsyntax-only` is checking the code for syntax errors, but don't do anything beyond that.

STR:
1. Execute `em++ -fsyntax-only hello_world.cpp`
2. Catch AssertionError in emcc.py. 

`
Traceback (most recent call last):
  File "<path_to_emsdk>/emsdk/emscripten/1.38.22/emcc.py", line 3088, in <module>
    sys.exit(run())
  File "<path_to_emsdk>/emsdk/emscripten/1.38.22/emcc.py", line 1532, in run
    compile_source_file(i, input_file)
  File "<path_to_emsdk>/emsdk/emscripten/1.38.22/emcc.py", line 1526, in compile_source_file
    assert(os.path.exists(output_file))
AssertionError
`

**Comment by Rishabh0712** [comment]
Hii. I am new to github and would like to give it a try. Some more info would help

**Comment by kripken** [comment]
@Rishabh0712 sure, what kind of info do you need?

The bug report gives concrete steps to reproduce the problem, and aside from that I'd say the relevant code would be in emcc.py, where it crashes.
