### ISSUE TITLE
emscripten_webgl_commit_frame returns EMSCRIPTEN_RESULT_NOT_SUPPORTED

### ISSUE THREAD

**Issue by mfleisz** [emscripten-core/emscripten#8307]
I have a small application that just clears a canvas using different colors on paints the result on screen. The code runs just fine with Firefox (65.0.2) but it causes problems with Chrome (73.0.3683.75):

```
#include <cstdio>
#include <GLES2/gl2.h>
#include <emscripten.h>
#include <emscripten/html5.h>
#include <emscripten/threading.h>

bool g_Running = true;
void* threadFunc(void* arg)
{
    EmscriptenWebGLContextAttributes attr;
    emscripten_webgl_init_context_attributes(&attr);
    attr.explicitSwapControl = EM_TRUE;
    EMSCRIPTEN_WEBGL_CONTEXT_HANDLE context = emscripten_webgl_create_context("#canvas", &attr);
    if (context == 0)
    {
        std::printf ("error can't create context\n");
        return NULL;
    }
    
    if (emscripten_webgl_make_context_current(context) != EMSCRIPTEN_RESULT_SUCCESS)
    {
        emscripten_webgl_destroy_context(context);
        std::printf("error can't make context current\n");
        return NULL;
    }

    int x = 0;
    do
    {
        switch (x)
        {
            case 0:
                glClearColor(0, 1, 0, 1);
                break;
            case 1:
                glClearColor(1, 1, 0, 1);
                break;
            case 2:
                glClearColor(0, 1, 1, 1);
                break;        
            default:
                glClearColor(1, 0, 0, 1);
                x = 0;
                break;
        }
        x++;

        glClear(GL_COLOR_BUFFER_BIT);
        int res = emscripten_webgl_commit_frame();
        if (res != EMSCRIPTEN_RESULT_SUCCESS)
            std::printf("Commit %d\n", res);
        emscripten_thread_sleep(500);
    } while (g_Running);

    emscripten_webgl_make_context_current(0);
    emscripten_webgl_destroy_context(context);
    pthread_exit(0);
    return NULL;
}


int main()
{
    std::printf("emscripten_supports_offscreencanvas returned %d\n", emscripten_supports_offscreencanvas());

    pthread_t pth;
    pthread_attr_t attr;

    pthread_attr_init(&attr);
    emscripten_pthread_attr_settransferredcanvases(&attr, "#canvas");
    int rc = pthread_create(&pth, &attr, threadFunc, NULL);
    std::printf("pthread_create returned %d\n", rc);
    pthread_attr_destroy(&attr);

    return 0;
}
```

Running the code on Chrome causes emscripten_webgl_commit_frame to fail with -1 (EMSCRIPTEN_RESULT_NOT_SUPPORTED). Also when the while loop exits following error messages are shown in the debugging console:

```
worker.js onmessage() captured an uncaught exception: DataCloneError: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': An OffscreenCanvas could not be cloned because it had a rendering context.

test_wasm.worker.js:191 Error: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': An OffscreenCanvas could not be cloned because it had a rendering context.
    at Object.threadExit (http://localhost:8080/test_wasm.js:1884:15)
    at _pthread_exit (http://localhost:8080/test_wasm.js:7835:20)
    at __Z10threadFuncPv (wasm-function[98]:641)
    at dynCall_ii (wasm-function[4229]:13)
    at Object.Module.dynCall_ii (http://localhost:8080/test_wasm.js:8834:38)
    at onmessage (http://localhost:8080/test_wasm.worker.js:155:42)

Pthread 5583072 uncaught exception in http://localhost:8080/test_wasm.worker.js:192:5: Uncaught DataCloneError: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': An OffscreenCanvas could not be cloned because it had a rendering context.. Error object:
(anonymous) @ test_wasm.worker.js:50

DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': An OffscreenCanvas could not be cloned because it had a rendering context.
    at Object.threadExit (http://localhost:8080/test_wasm.js:1884:15)
    at _pthread_exit (http://localhost:8080/test_wasm.js:7835:20)
    at __Z10threadFuncPv (wasm-function[98]:641)
    at dynCall_ii (wasm-function[4229]:13)
    at Object.Module.dynCall_ii (http://localhost:8080/test_wasm.js:8834:38)
    at onmessage (http://localhost:8080/test_wasm.worker.js:155:42)
(anonymous) @ test_wasm.worker.js:51
```

I'm using following compiler flags: ` -s WASM=1 -s USE_PTHREADS=1 -s NO_EXIT_RUNTIME=1 -s TOTAL_MEMORY=256MB -s OFFSCREENCANVAS_SUPPORT=1 -s USE_WEBGL2=1 -s GL_DEBUG=1`.

WebAssembly threads and SharedArrayBuffer support are both enabled in Chrome. Any idea what could be wrong with my code in Chrome?
I'm using the latest EMSDK 1.38.29

**Comment by mfleisz** [comment]
I also see this error message at the beginning of the console log (but it looks more like a debug info message than an real error):

```
pthread_create: canvas.transferControlToOffscreen(), transferring canvas by name "canvas" (DOM id="canvas") from main thread to pthread
```

**Comment by mfleisz** [comment]
One more note: just gave `gl_in_pthread.cpp` in `tests` a try with exactly the same result: working on Firefox and the exact same errors on Chrome.
