### ISSUE TITLE
zlib build fails under 1.38.30

### ISSUE THREAD

**Issue by bhelyer** [emscripten-core/emscripten#8341]
Hi there,
Our project uses zlib through -s USE_ZLIB=1. Today I tried to upgrade to 1.38.30 from 1.38.19, a clean build (emcc.bat --clear-ports) failed with the following:

```
emcc.bat -s NO_EXIT_RUNTIME=1 -s USE_LIBPNG=1 -s USE_ZLIB=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'cwrap', 'addFunction', 'UTF16ToString', 'Pointer_stringify', 'removeFunction', 'getValue']" -s EXPORTED_FUNCTIONS="['_malloc', '_free']" --preload-file "Common/Unmanaged/Dependencies/Components@Components" --preload-file "Common/Unmanaged/Dependencies/SceneGraph/fonts@fonts" --preload-file "Common/Unmanaged/Dependencies/SceneGraph/textures@textures" --preload-file "Common/Unmanaged/Dependencies/SceneGraph/symbols@symbols" --no-heap-copy -s RESERVED_FUNCTION_POINTERS=35 -O3 -D"NDEBUG" -s DISABLE_EXCEPTION_CATCHING=1 -s WASM=1 -s BINARYEN_METHOD='native-wasm' -MMD -s ALLOW_MEMORY_GROWTH=1 @emobjsrsp.txt -o bin/x86/Release/sym3operatorruntime.html
cache:INFO: generating port: libz.a... (this will be cached in "C:\Users\bernard.helyer\.emscripten_cache\asmjs\libz.a" for subsequent builds)
system_libs:ERROR: a problem occurred when using an emscripten-ports library.  try to run `emcc --clear-ports` and then run this command again
Traceback (most recent call last):
  File "C:\emsdk\emscripten\1.38.30\emcc.py", line 3276, in <module>
    sys.exit(run(sys.argv))
  File "C:\emsdk\emscripten\1.38.30\emcc.py", line 1756, in run
    extra_files_to_link = system_libs.get_ports(shared.Settings)
  File "C:\emsdk\emscripten\1.38.30\tools\system_libs.py", line 1011, in get_ports
    ret += [f for f in port.get(Ports, settings, shared) if not f.endswith('.txt')]
  File "C:\emsdk\emscripten\1.38.30\tools\ports\zlib.py", line 46, in get
    return [shared.Cache.get('libz.a', create, what='port')]
  File "C:\emsdk\emscripten\1.38.30\tools\cache.py", line 127, in get
    temp = creator()
  File "C:\emsdk\emscripten\1.38.30\tools\ports\zlib.py", line 42, in create
    ports.run_commands([[shared.EMAR, 'rc', final] + o_s])
  File "C:\emsdk\emscripten\1.38.30\tools\system_libs.py", line 817, in run_commands
    run_commands(commands)
  File "C:\emsdk\emscripten\1.38.30\tools\system_libs.py", line 35, in run_commands
    call_process(command)
  File "C:\emsdk\emscripten\1.38.30\tools\system_libs.py", line 28, in call_process
    shared.run_process(cmd, stdout=stdout, stderr=stderr)
  File "C:\emsdk\emscripten\1.38.30\tools\shared.py", line 170, in run_process
    proc = Popen(cmd, *args, **kw)
  File "C:\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application
```

This is under Windows 10, 64 bit.

**Comment by JimmySnails** [comment]
I get the same error for zlib and for SDL_Mixer=2 as well.

Since it's the same line number, i guess this'll be fixed in the next release too? Unfortunately i can't get the master to work, so i'll have to wait for the next release

```
  File "D:\iso\emscripten\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "D:\iso\emscripten\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 ist keine zulõssige Win32-Anwendung
```
