### ISSUE TITLE
Browser CI: os.getcwd() fails with "No such file or directory"

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#8367]
e.g. https://circleci.com/gh/emscripten-core/emscripten/110267?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52994)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/root/emscripten/tests/runner.py", line 1101, in do_GET
    SimpleHTTPRequestHandler.do_GET(self)
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 45, in do_GET
    f = self.send_head()
  File "/root/emscripten/tests/runner.py", line 1025, in send_head
    path = self.translate_path(self.path)
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 168, in translate_path
    path = os.getcwd()
OSError: [Errno 2] No such file or directory
----------------------------------------
```
This is adjacent to failures on `test_webgl_context_*` fail (which seems fairly frequent recently) - but it shows up in the log several lines later, so it may be unrelated. Those tests don't hit a clientside exception though, as we would now be reporting that, so a server problem would make sense.

cc @sbc100 - maybe that python error makes sense to you?

**Comment by kripken** [comment]
cc @VirtualTim who was also interested in those test failures I think.

**Comment by sbc100** [comment]
Looks like the CWD is set to a non-existent directory.. either because the directory was removed .. or perhaps some test did a "chdir" to a directory that was then removed?
