### ISSUE TITLE
Compiler crashes in LLVMSymbolizer with optimizations on

### ISSUE THREAD

**Issue by Matheus28** [emscripten-core/emscripten#8373]
The following code crashes emscripten, I tested this using `sdk-1.38.28-64bit`. I've also tested `sdk-1.38.30-64bit` not with this reduced code, but the entire project code and it crashes too (likely also crashes with this repro code). Note that it also crashes with `-O1` and `-O2` but not `-O0`. I've reduced the repro code as much as possible:

```
#include <emscripten.h>

double Now(){
	static bool hasPerformanceClock = (bool) EM_ASM_INT({ return window.performance && window.performance.now }, 0);
	
	if(hasPerformanceClock){
		return EM_ASM_DOUBLE({ return window.performance.now(); }, 0);
	}else{
		return EM_ASM_DOUBLE({ return Date.now(); }, 0);
	}
}

int main(){
	Now();
	
}

```

Compile using:

`emcc.bat -std=c++14 -O3 -o client.js main.cpp`

Outputs:

```
LLVMSymbolizer: error reading file: DIA Error: An unknown error has occurred.  HRESULT: 0x8007007E: Calling NoRegCoCreate

LLVMSymbolizer: error reading file: DIA Error: An unknown error has occurred.  HRESULT: 0x8007007E: Calling NoRegCoCreate

LLVMSymbolizer: error reading file: DIA Error: An unknown error has occurred.  HRESULT: 0x8007007E: Calling NoRegCoCreate

#0 0x00007ff8a7c1162c (C:\Windows\SYSTEM32\VCRUNTIME140.dll+0x162c)
#1 0x00007ff717ff154d (C:\Projects\planets\deps\emsdk\clang\e1.38.28_64bit\llc.exe+0x3154d)
#2 0x00007ff71820c2ba (C:\Projects\planets\deps\emsdk\clang\e1.38.28_64bit\llc.exe+0x24c2ba)
#3 0x00007ff718218b72 (C:\Projects\planets\deps\emsdk\clang\e1.38.28_64bit\llc.exe+0x258b72)
#4 0x00007ff7181c141c (C:\Projects\planets\deps\emsdk\clang\e1.38.28_64bit\llc.exe+0x20141c)
#5 0x00007ff7182194cc (C:\Projects\planets\deps\emsdk\clang\e1.38.28_64bit\llc.exe+0x2594cc)
#6 0x00007ff7182033e2 (C:\Projects\planets\deps\emsdk\clang\e1.38.28_64bit\llc.exe+0x2433e2)
#7 0x00007ff7181f963f (C:\Projects\planets\deps\emsdk\clang\e1.38.28_64bit\llc.exe+0x23963f)
#8 0x00007ff71821be72 (C:\Projects\planets\deps\emsdk\clang\e1.38.28_64bit\llc.exe+0x25be72)
#9 0x00007ff71821bc49 (C:\Projects\planets\deps\emsdk\clang\e1.38.28_64bit\llc.exe+0x25bc49)
#10 0x00007ff71821d892 (C:\Projects\planets\deps\emsdk\clang\e1.38.28_64bit\llc.exe+0x25d892)
#11 0x00007ff718222c90 (C:\Projects\planets\deps\emsdk\clang\e1.38.28_64bit\llc.exe+0x262c90)
#12 0x00007ff71854bcf7 (C:\Projects\planets\deps\emsdk\clang\e1.38.28_64bit\llc.exe+0x58bcf7)
#13 0x00007ff71854b410 (C:\Projects\planets\deps\emsdk\clang\e1.38.28_64bit\llc.exe+0x58b410)
#14 0x00007ff717ff2b63 (C:\Projects\planets\deps\emsdk\clang\e1.38.28_64bit\llc.exe+0x32b63)
#15 0x00007ff717ff3fcd (C:\Projects\planets\deps\emsdk\clang\e1.38.28_64bit\llc.exe+0x33fcd)
#16 0x00007ff718b2a885 (C:\Projects\planets\deps\emsdk\clang\e1.38.28_64bit\llc.exe+0xb6a885)
#17 0x00007ff8b39781f4 (C:\Windows\System32\KERNEL32.DLL+0x181f4)
#18 0x00007ff8b4a3a251 (C:\Windows\SYSTEM32\ntdll.dll+0x6a251)
Traceback (most recent call last):
  File "C:\Projects\planets\deps\emsdk\emscripten\1.38.28\emcc.py", line 3220, in <module>
    sys.exit(run(sys.argv))
  File "C:\Projects\planets\deps\emsdk\emscripten\1.38.28\emcc.py", line 1882, in run
    final = shared.Building.emscripten(final, target + '.mem', js_libraries)
  File "C:\Projects\planets\deps\emsdk\emscripten\1.38.28\tools\shared.py", line 2315, in emscripten
    emscripten.run(infile, outfile, memfile, js_libraries)
  File "C:\Projects\planets\deps\emsdk\emscripten\1.38.28\emscripten.py", line 2499, in run
    return temp_files.run_and_clean(lambda: emscripter(
  File "C:\Projects\planets\deps\emsdk\emscripten\1.38.28\tools\tempfiles.py", line 105, in run_and_clean
    return func()
  File "C:\Projects\planets\deps\emsdk\emscripten\1.38.28\emscripten.py", line 2500, in <lambda>
    infile, outfile_obj, memfile, libraries, shared.COMPILER_ENGINE, temp_files, shared.DEBUG)
  File "C:\Projects\planets\deps\emsdk\emscripten\1.38.28\emscripten.py", line 89, in emscript
    backend_output = compile_js(infile, temp_files, DEBUG)
  File "C:\Projects\planets\deps\emsdk\emscripten\1.38.28\emscripten.py", line 118, in compile_js
    jsrun.timeout_run(subprocess.Popen(backend_args, stdout=subprocess.PIPE, universal_newlines=True), note_args=backend_args)
  File "C:\Projects\planets\deps\emsdk\emscripten\1.38.28\tools\jsrun.py", line 27, in timeout_run
    raise Exception('Subprocess "' + ' '.join(note_args) + '" failed with exit code ' + str(proc.returncode) + '!')
Exception: Subprocess "C:/Projects/planets/deps/emsdk/clang/e1.38.28_64bit\llc.exe C:\Users\M28\AppData\Local\Temp\emscripten_temp_kswwix\client.bc -march=js -filetype=asm -o C:\Users\M28\AppData\Local\Temp\tmpe7ladw.4.js -emscripten-stack-size=5242880 -O3 -emscripten-precise-f32 -emscripten-global-base=1024 -emscripten-no-exit-runtime -emscripten-wasm -emscripten-only-wasm" failed with exit code -1073741819!
```

**Comment by Matheus28** [comment]
Here's one of the dump files, if needed:
[llc.exe-0f0e38.dmp.zip](https://github.com/emscripten-core/emscripten/files/3026008/llc.exe-0f0e38.dmp.zip)

**Comment by Matheus28** [comment]
Note that this variant does **not** crash:

```#include <emscripten.h>

double Now(){
	static bool hasPerformanceClock = (bool) EM_ASM_INT({ return window.performance && window.performance.now }, 0);
	
	return EM_ASM_DOUBLE({ return $0 ? window.performance.now() : Date.now(); }, hasPerformanceClock);
}

int main(){
	Now();
}
```

**Comment by kripken** [comment]
Thanks for the testcase! Looks like what happens is that the LLVM optimizer turns that if into a select, so two EM_ASM calls turn into one,
```
  %.sink = select i1 %13, i8* getelementptr inbounds ([14 x i8], [14 x i8]* @.str.2, i32 0, i32 0), i8* getelementptr inbounds ([14 x i8], [14 x i8]* @.str.1, i32 0, i32 0)
  %14 = tail call double (i8*, ...) @emscripten_asm_const_double(i8* %.sink, i32 0)
```
But fastcomp assumes it can find the string by following the pointer - here the pointer is a select which might be one of two different strings.

There isn't a trivial way to fix this. On the other hand, the good news is the LLVM wasm backend is close to being used instead of fastcomp by default, and I confirmed it does not crash on this testcase.
