### ISSUE TITLE
Emscripten won't compile libc.a, then throw error because it's not in emscripten_cache/wasm_o

### ISSUE THREAD

**Issue by DragonOsman** [emscripten-core/emscripten#8491]
After building LLVM 9.0 recently, I tried to compile some code I had to JavaScript to try to use it as a small Node.js module (I used the `-s ENVIRONMENT=Node.js` too), but I had this message returned:
```
cache:INFO: generating system library: libc++_noexcept.a... (this will be cached in "C:\Users\Osman\.emscripten_cache\wasm_o\libc++_noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc++abi.a... (this will be cached in "C:\Users\Osman\.emscripten_cache\wasm_o\libc++abi.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc.a... (this will be cached in "C:\Users\Osman\.emscripten_cache\wasm_o\libc.a" for subsequent builds)
shared:WARNING: (Emscripten: system change: 1.38.31|C:\Program Files (x86)\LLVM\bin|9.0_wasm vs 1.38.30|C:\Program Files (x86)\LLVM\bin|9.0_wasm, clearing cache)
shared:WARNING: (Emscripten: system change: 1.38.31|C:\Program Files (x86)\LLVM\bin|9.0_wasm vs 1.38.30|C:\Program Files (x86)\LLVM\bin|9.0_wasm, clearing cache)
shared:WARNING: (Emscripten: system change: 1.38.31|C:\Program Files (x86)\LLVM\bin|9.0_wasm vs 1.38.30|C:\Program Files (x86)\LLVM\bin|9.0_wasm, clearing cache)
shared:WARNING: (Emscripten: system change: 1.38.31|C:\Program Files (x86)\LLVM\bin|9.0_wasm vs 1.38.30|C:\Program Files (x86)\LLVM\bin|9.0_wasm, clearing cache)
shared:INFO: (Emscripten: Running sanity checks)
shared:WARNING: java does not seem to exist, required for closure compiler, which is optional (define JAVA in C:\Users\Osman/.emscripten if you want it)
shared:WARNING: closure compiler will not be available
shared:INFO: (Emscripten: Running sanity checks)
shared:WARNING: java does not seem to exist, required for closure compiler, which is optional (define JAVA in C:\Users\Osman/.emscripten if you want it)
shared:WARNING: closure compiler will not be available
shared:INFO: (Emscripten: Running sanity checks)
shared:WARNING: java does not seem to exist, required for closure compiler, which is optional (define JAVA in C:\Users\Osman/.emscripten if you want it)
shared:WARNING: closure compiler will not be available
shared:INFO: (Emscripten: Running sanity checks)
shared:WARNING: java does not seem to exist, required for closure compiler, which is optional (define JAVA in C:\Users\Osman/.emscripten if you want it)
shared:WARNING: closure compiler will not be available
Traceback (most recent call last):
  File "C:\emscripten\emcc.py", line 3286, in <module>
    try:
  File "C:\emscripten\emcc.py", line 1759, in run

  File "C:\emscripten\tools\system_libs.py", line 752, in calculate
    logger.debug('considering %s: we need %s and have %s' % (lib.shortname, str(need_syms), str(has_syms)))
  File "C:\emscripten\tools\system_libs.py", line 719, in add_library
    need_whole_archive = lib.shortname in force_include and lib.suffix != 'bc'
  File "C:\emscripten\tools\system_libs.py", line 719, in add_library
    need_whole_archive = lib.shortname in force_include and lib.suffix != 'bc'
  File "C:\emscripten\tools\system_libs.py", line 713, in add_library
    logger.debug('including %s' % name)
  File "C:\emscripten\tools\cache.py", line 129, in get
    what = 'system asset'
  File "C:\Python27\lib\shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\Osman\\.emscripten_cache\\wasm_o\\libc.a'
```
As you can see, it didn't build and cache libc.a and then threw an error saying it's not there.  How do I fix this?  Thanks in advance for any help.

Note: this was the command I ran to invoke Emscripten: 
```
em++ -s WASM=1 -s ENVIRONMENT=Node.js -std=c++17 -Wall -pedantic makechange.cpp -o makechange.js
```

**Comment by sbc100** [comment]
Seems strange that it would choose the clear the cache between after starting to build libc.a.    The cache clearing should happen right at the start before anything is built.

**Comment by sbc100** [comment]
It looks like you somehow updated to version 1.38.31 from 1.38.30 while the system libraries were being built.

Try running `emcc --clear-cache` and trying again.

**Comment by DragonOsman** [comment]
Yes, that's also strange.  Any way to troubleshoot this?

**Comment by DragonOsman** [comment]
@sbc100 That solved the cache problem, but now I have this:
```
wasm-ld: warning: function signature mismatch: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEE7seekposENS_4fposI11__mbstate_tEEj
>>> defined as () -> void in C:\Users\Osman\.emscripten_cache\wasm-obj\libc++_noexcept.a(iostream.cpp.o)
>>> defined as (i32, i32, i32, i32) -> void in C:\Users\Osman\.emscripten_cache\wasm-obj\libc++_noexcept.a(ios.cpp.o)

wasm-ld: warning: function signature mismatch: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEE7seekoffExNS_8ios_base7seekdirEj
>>> defined as () -> void in C:\Users\Osman\.emscripten_cache\wasm-obj\libc++_noexcept.a(iostream.cpp.o)
>>> defined as (i32, i32, i64, i32, i32) -> void in C:\Users\Osman\.emscripten_cache\wasm-obj\libc++_noexcept.a(ios.cpp.o)

wasm-ld: warning: function signature mismatch: _ZNSt3__215basic_streambufIwNS_11char_traitsIwEEE7seekposENS_4fposI11__mbstate_tEEj
>>> defined as () -> void in C:\Users\Osman\.emscripten_cache\wasm-obj\libc++_noexcept.a(iostream.cpp.o)
>>> defined as (i32, i32, i32, i32) -> void in C:\Users\Osman\.emscripten_cache\wasm-obj\libc++_noexcept.a(ios.cpp.o)

wasm-ld: warning: function signature mismatch: _ZNSt3__215basic_streambufIwNS_11char_traitsIwEEE7seekoffExNS_8ios_base7seekdirEj
>>> defined as () -> void in C:\Users\Osman\.emscripten_cache\wasm-obj\libc++_noexcept.a(iostream.cpp.o)
>>> defined as (i32, i32, i64, i32, i32) -> void in C:\Users\Osman\.emscripten_cache\wasm-obj\libc++_noexcept.a(ios.cpp.o)
cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "C:\Users\Osman\.emscripten_cache\wasm-obj\generated_struct_info.json" for subsequent builds)
shared:WARNING: emcc: WASM_BACKEND is not compatible with asmjs (WASM=0), forcing WASM=1
Traceback (most recent call last):
  File "C:\emscripten\emcc.py", line 3307, in <module>
    sys.exit(run(sys.argv))
  File "C:\emscripten\emcc.py", line 1938, in run
    final = shared.Building.emscripten(final, target + '.mem', js_libraries)
  File "C:\emscripten\tools\shared.py", line 2209, in emscripten
    emscripten.run(infile, outfile, memfile, js_libraries)
  File "C:\emscripten\emscripten.py", line 2556, in run
    shared.Settings.STRUCT_INFO = shared.Cache.get(generated_struct_info_name, ensure_struct_info)
  File "C:\emscripten\tools\cache.py", line 133, in get
    temp = creator()
  File "C:\emscripten\emscripten.py", line 2553, in ensure_struct_info
    gen_struct_info.main(['-qo', out, path_from_root('src', 'struct_info.json')])
  File "C:\emscripten\tools\gen_struct_info.py", line 527, in main
    struct_info = inspect_code(header_files, cpp_opts, structs, defines)
  File "C:\emscripten\tools\gen_struct_info.py", line 405, in inspect_code
    info = shared.run_js(js_file[1]).splitlines()
  File "C:\emscripten\tools\shared.py", line 1090, in run_js
    return jsrun.run_js(filename, engine, *args, **kw)
  File "C:\emscripten\tools\jsrun.py", line 155, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['C:\\Program Files\\nodejs\\node.exe', 'c:\\users\\osman\\appdata\\local\\temp\\tmplcrzgw.js'] to finish with return code 0, but it returned with code -1073741819 instead! Output:
```
Also, when running `em++`, this:
```
cache:INFO: generating system library: libc++_noexcept.a... (this will be cached in "C:\Users\Osman\.emscripten_cache\wasm-obj\libc++_noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc++abi.a... (this will be cached in "C:\Users\Osman\.emscripten_cache\wasm-obj\libc++abi.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc.a... (this will be cached in "C:\Users\Osman\.emscripten_cache\wasm-obj\libc.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libcompiler_rt.a... (this will be cached in "C:\Users\Osman\.emscripten_cache\wasm-obj\libcompiler_rt.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc-wasm.a... (this will be cached in "C:\Users\Osman\.emscripten_cache\wasm-obj\libc-wasm.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libdlmalloc.a... (this will be cached in "C:\Users\Osman\.emscripten_cache\wasm-obj\libdlmalloc.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libpthreads_stub.a... (this will be cached in "C:\Users\Osman\.emscripten_cache\wasm-obj\libpthreads_stub.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libcompiler_rt_wasm.a... (this will be cached in "C:\Users\Osman\.emscripten_cache\wasm-obj\libcompiler_rt_wasm.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc_rt_wasm.a... (this will be cached in "C:\Users\Osman\.emscripten_cache\wasm-obj\libc_rt_wasm.a" for subsequent builds)
cache:INFO:  - ok
```
And it said it's forcing WASM=1 because WASM_BACKEND (which I have set to 1 in system env variables) isn't compatible with asmjs, but I already did provide that setting when invoking `em++`.  Did I put at the wrong place in the command?  As I said, I ran the command like this:
```
em++ -s WASM=1 -s ENVIRONMENT=Node.js -std=c++17 -Wall -pedantic makechange.cpp -o makechange.js
```
Notice the placement of the `-s` stuff and let me know where they should be in the command if I do have the wrong placement for those.

**Comment by sbc100** [comment]
You don't need to specify WASM_BACKEND anywhere.. emscripten will detect that you using the WASM_BACKEND automatically.

You also don't need to specify WASM=1 since that is the default.

Your actual error is that the generated_struct_info step failed to run under node... do you see any other output about why it failed?     What version of node are you using?

**Comment by DragonOsman** [comment]
My Node version is 11.14.0.  

How do I fix those linker warnings?  And how do I figure out why the generated_struct_info step (what's supposed to happen in that step and what exactly is generated_struct_info?) failed?

**Comment by sbc100** [comment]
The linker warning is generated internally when generating the struct_info.  You can ignore it, it will only show up when the struct info is regenerated (i.e when you change emscripten version).  I've submitted a PR to fix that to avoid confusion.

The figure out why generated_struct_info is failing you will probably need to take a look at tools/gen_struct_info.py.   The call to node at line 405 is failing.. but node is not giving any output at all.   You might want to try saving the JS file in question and running it from the command line.   

You can trigger generation of struct_info more directly via `./embuilder.py build struct_info` so you can be sure this is unrelated to the program you are trying to compile or your command line flags (which it absolutely should be).

**Comment by DragonOsman** [comment]
How do I save the JavaScript file myself?  

This is what's on line 405:
```py
info = shared.run_js(js_file[1]).splitlines()
```
It's part of this code block:
```py
    # Run the compiled program.
    show('Calling generated program...')
    try:
      info = shared.run_js(js_file[1]).splitlines()
    except subprocess.CalledProcessError:
      sys.stderr.write('FAIL: Running the generated program failed!\n')
      sys.exit(1)
```
Is this `try-except` code where the error is coming from?

**Comment by DragonOsman** [comment]
@kripken or anyone else.  Please help me out with this.  I want to successfully generate the JS file.

**Comment by DragonOsman** [comment]
If I already have a JS file I compiled before using the same code, but without specifying Node as the environment, how do I write a JS file to use it?  I'm trying to write one now but I'm lost.  Here's what I have now (I just copied the Module object from the HTML code that was generated by Emscripten):
```js
let wasm_module = require("./index.js");

let Module = {
  preRun: [],
  postRun: [],
  print: (function() {
    console.log(text);
  })(),
  printErr: function(text) {
    if (arguments.length > 1)
      text = Array.prototype.slice.call(arguments).join(" ");
    console.error(text);
  },
  onRuntimeInitialized: function() {
    wasm_module._main();
  },
  setStatus: function(text) {
    if (!Module.setStatus.last)
      Module.setStatus.last = { time: Date.now(), text: "" };
    if (text === Module.setStatus.last.text) return;
    var m = text.match(/([^(]+)\((\d+(\.\d+)?)\/(\d+)\)/);
    var now = Date.now();
    if (m && now - Module.setStatus.last.time < 30) return; // if this is a progress update, skip it if too soon
    Module.setStatus.last.time = now;
    Module.setStatus.last.text = text;
    if (m) {
      text = m[1];
      progressElement.value = parseInt(m[2]) * 100;
      progressElement.max = parseInt(m[4]) * 100;
      progressElement.hidden = false;
      spinnerElement.hidden = false;
    } else {
      progressElement.value = null;
      progressElement.max = null;
      progressElement.hidden = true;
      if (!text) spinnerElement.style.display = "none";
    }
    statusElement.innerHTML = text;
  },
  totalDependencies: 0,
  monitorRunDependencies: function(left) {
    this.totalDependencies = Math.max(this.totalDependencies, left);
    Module.setStatus(
      left
        ? "Preparing... (" +
            (this.totalDependencies - left) +
            "/" +
            this.totalDependencies +
            ")"
        : "All downloads complete."
    );
  }
};
```
Any help is appreciated.  Thanks.

**Comment by DragonOsman** [comment]
I opened another thread asking for help in compiling code to WASM since I noticed that I couldn't compile anything with Emscripten.  This thread was mainly for asking about why libc.a wasn't being generated which is fixed now.  So I'm thinking of closing it now if that's okay.

**Comment by owenammann** [comment]
How did you fix it?

**Comment by sbc100** [comment]
@owenammann this bug is from 2019.  Are you experiencing something similar today with a recent version?  If so, please open a new bug

**Comment by owenammann** [comment]
Thanks, all good here. Updated the library and used latest emsdk to successfully build. We were using some code that relied on fastcomp but now we've got the new updated llvm version
