### ISSUE TITLE
test_zzz_emrun if still failing frequently under test-browser-chrome

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#8495]
e.g. https://circleci.com/gh/emscripten-core/emscripten/118539?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
test_zzz_emrun (test_browser.browser) ... Web server root directory: /tmp/emscripten_test_browser_kL1SvB
Starting web server: http://localhost:6939/
Starting browser: /usr/bin/xvfb-run -a -e /dev/stdout /usr/bin/google-chrome-stable --no-first-run -start-maximized --no-sandbox --use-gl=swiftshader --enable-features=WebAssembly --enable-features=SharedArrayBuffer --disable-features=WebAssemblyTrapHandler --js-flags=--experimental-wasm-threads --harmony-sharedarraybuffer --no-wasm-disable-structured-cloning http://localhost:6939/hello_world.html?1&2&--3
[8483:8499:0425/171711.326180:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[5928:5934:0425/171711.446003:ERROR:command_buffer_proxy_impl.cc(106)] ContextResult::kTransientFailure: Shared memory region is not valid
[8483:8495:0425/171711.456259:ERROR:browser_process_sub_thread.cc(217)] Waited 5 ms for network service
Opening in existing browser session.
[0425/171711.467543:ERROR:nacl_helper_linux.cc(310)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
POST: "/stdio.html" (path: "/stdio.html", query: "")
Browser process has quit. Shutting down web server.. Pass --serve_after_close to keep serving the page even after the browser closes.
Closed web server.
emrun quitting with process exit code 0
FAIL
test_zzz_html_source_map (test_browser.browser) ... sh: 0: getcwd() failed: No such file or directory
[client logging: /?exception=Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:6939/stdio.html'. / undefined ]

If manually bisecting:
  Check that you see src.cpp among the page sources.
  Even better, add a breakpoint, e.g. on the printf, then reload, then step
  through and see the print (best to run with EMTEST_SAVE_DIR=1 for the reload).

ok
[Browser harness server terminated]

======================================================================
FAIL: test_sdl_image_must_prepare (test_browser.browser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/emscripten/tests/test_browser.py", line 710, in test_sdl_image_must_prepare
    self.btest('sdl_image_must_prepare.c', reference='screenshot.jpg', args=['--preload-file', 'screenshot.jpg', '-lSDL', '-lGL'])
  File "/root/emscripten/tests/runner.py", line 1438, in btest
    self.run_browser(outfile + url_suffix, message, ['/report_result?' + e for e in expected], timeout=timeout)
  File "/root/emscripten/tests/runner.py", line 1273, in run_browser
    self.assertIdentical(expectedResult, output)
  File "/root/emscripten/tests/runner.py", line 701, in assertIdentical
    limit_size(''.join([a.rstrip() + '\n' for a in difflib.unified_diff(x.split('\n'), y.split('\n'), fromfile='expected', tofile='actual')]))
AssertionError: Expected to have '/report_result?0' == '/report_result?37', diff:

--- expected
+++ actual
@@ -1 +1 @@
-/report_result?0
+/report_result?37


======================================================================
FAIL: test_zzz_emrun (test_browser.browser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/emscripten/tests/test_browser.py", line 2473, in test_zzz_emrun
    assert proc.returncode == 100
AssertionError
```

**Comment by kripken** [comment]
I can find more time to look into this. On the other hand, someone else taking a fresh look at the problem might see something I missed.

**Comment by awaismbajwa** [comment]
I am getting the same error in my debian container. I install google-chrome-stable through package provided by google and I am not able to get it running. I get the same error message

**Comment by sbc100** [comment]
Do you get it consistently?   When run in isolation (i.e just running this one test)?

**Comment by awaismbajwa** [comment]
My issue was caused by the incompatible version of teaspoon with selenium. I found out that teaspoon source was not updated according to selenium version and chrome was not getting required arguments like --headless --disable-gpu etc. to run it in headless mode. I was able to make it work by making sure that arguments are passed correctly to chrome. may be you have some similar issue

**Comment by blockspacer** [comment]
Got similar issue on Ubuntu 18 (issue happens not in every browser run)

```bash
[1452:1470:1107/093033.128871:ERROR:browser_process_sub_thread.cc(221)] Waited 3 ms for network service
```

after 

```bash
emrun --port 9090 --serve_root / .
```

**Temporary fix:** Start browser as root with `--no-sandbox` and NetworkService enabled, see https://stackoverflow.com/a/56485360

```bash
sudo -E /usr/bin/google-chrome-stable --enable-features=NetworkService --enable-features=NetworkServiceWindowsSandbox --no-sandbox
```

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.21
clang version 6.0.1 (955fea46a999fc222ca7699b5e58ff193fbe6c4c) (612d2bb450448675a76191966aef1ab138c99e7f) (emscripten 1.38.21 : 1.38.21)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: ../lib/gcc/x86_64-pc-linux-gnu/6.3.0
Found candidate GCC installation: ../lib/gcc/x86_64-pc-linux-gnu/7.3.0
Found candidate GCC installation: ../lib64/gcc/x86_64-pc-linux-gnu/6.3.0
Found candidate GCC installation: ../lib64/gcc/x86_64-pc-linux-gnu/7.3.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
shared:INFO: (Emscripten: Running sanity checks)
```
