### ISSUE TITLE
libcompiler_rt.a: function not supported.

### ISSUE THREAD

**Issue by diegocr** [emscripten-core/emscripten#8548]
Hello,

I've just upgraded `1.37.21` to `1.38.30` and got this issue compiling a hello-world example:

```
$ emcc -Wall -v test.c
shared:INFO: (Emscripten: Running sanity checks)
clang version 6.0.1  (emscripten 1.38.30 : 1.38.30)
Target: asmjs-unknown-emscripten
Thread model: posix
InstalledDir: C:\emsdk\clang\e1.38.30_64bit
 "C:\\emsdk\\clang\\e1.38.30_64bit\\clang.exe" -cc1 -triple asmjs-unknown-emscripten -emit-llvm-bc -emit-llvm-uselists -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -no-integrated-as -mconstructor-aliases -dwarf-column-info -debugger-tuning=gdb -v -coverage-notes-file "R:\\Temp\\emscripten_temp_oazeip\\test_0.gcno" -nostdsysteminc -nobuiltininc -resource-dir "C:\\emsdk\\clang\\lib\\clang\\6.0.1" -D __EMSCRIPTEN_major__=1 -D __EMSCRIPTEN_minor__=38 -D __EMSCRIPTEN_tiny__=30 -D _LIBCPP_ABI_VERSION=2 -O3 -Werror=implicit-function-declaration -Wall -fno-dwarf-directory-asm -fdebug-compilation-dir "R:\\" -ferror-limit 19 -fmessage-length 158 -fobjc-runtime=gnustep -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -nobuiltininc -nostdsysteminc "-isystemC:\\emsdk\\emscripten\\1.38.30\\system\\include\\libcxx" "-isystemC:\\emsdk\\emscripten\\1.38.30\\system\\lib\\libcxxabi\\include" "-isystemC:\\emsdk\\emscripten\\1.38.30\\system\\include\\compat" "-isystemC:\\emsdk\\emscripten\\1.38.30\\system\\include" "-isystemC:\\emsdk\\emscripten\\1.38.30\\system\\include\\SSE" "-isystemC:\\emsdk\\emscripten\\1.38.30\\system\\include\\libc" "-isystemC:\\emsdk\\emscripten\\1.38.30\\system\\lib\\libc\\musl\\arch\\emscripten" "-isystemC:\\emsdk\\emscripten\\1.38.30\\system\\local\\include" -disable-O0-optnone "-isystemC:\\emsdk\\emscripten\\1.38.30\\system\\include\\SDL" -disable-llvm-optzns -o "R:\\Temp\\emscripten_temp_oazeip\\test_0.o" -x c test.c clang -cc1 version 6.0.1 based upon LLVM 6.0.1 default target x86_64-pc-windows-msvc
ignoring nonexistent directory "C:\emsdk\emscripten\1.38.30\system\include\SSE"
#include "..." search starts here:
#include <...> search starts here:
 C:\emsdk\emscripten\1.38.30\system\include\libcxx
 C:\emsdk\emscripten\1.38.30\system\lib\libcxxabi\include
 C:\emsdk\emscripten\1.38.30\system\include\compat
 C:\emsdk\emscripten\1.38.30\system\include
 C:\emsdk\emscripten\1.38.30\system\include\libc
 C:\emsdk\emscripten\1.38.30\system\lib\libc\musl\arch\emscripten
 C:\emsdk\emscripten\1.38.30\system\local\include
 C:\emsdk\emscripten\1.38.30\system\include\SDL
End of search list.
 "C:/emsdk/clang/e1.38.30_64bit\opt.exe" R:\Temp\emscripten_temp_oazeip\test_0.o -O3 -lower-non-em-intrinsics -disable-loop-vectorization -disable-slp-vectorization -vectorize-loops=false -vectorize-slp=false -o R:\Temp\emscripten_temp_oazeip\test_0_1.o
cache:INFO: generating system library: libcompiler_rt.a... (this will be cached in "C:\home\dc\.emscripten_cache\asmjs\libcompiler_rt.a" for subsequent builds)
C:/emsdk/clang/e1.38.30_64bit\llvm-ar.exe: R:\Temp\emscripten_temp_oazeip\libcompiler_rt.a: function not supported.
OVERVIEW: LLVM Archiver (llvm-ar)

  This program archives bitcode files into single libraries

USAGE: llvm-ar.exe [options] [relpos] [count] <archive-file> [members]...

OPTIONS:
  -M                  -
  -format             - Archive format to create
    =default          -   default
    =gnu              -   gnu
    =darwin           -   darwin
    =bsd              -   bsd
  -help               - Display available options (-help-hidden for more)
  -plugin=<string>    - plugin (ignored for compatibility
  -print-module-scope - When printing IR for print-[before|after]{-all} always print a module IR
  -version            - Display the version of this program
Traceback (most recent call last):
  File "C:\emsdk\emscripten\1.38.30\emcc.py", line 3276, in <module>
    sys.exit(run(sys.argv))
  File "C:\emsdk\emscripten\1.38.30\emcc.py", line 1757, in run
    extra_files_to_link += system_libs.calculate([f for _, f in sorted(temp_files)] + extra_files_to_link, in_temp, stdout_=None, stderr_=None, forced=forced_stdlibs)
  File "C:\emsdk\emscripten\1.38.30\tools\system_libs.py", line 754, in calculate
    add_library(lib)
  File "C:\emsdk\emscripten\1.38.30\tools\system_libs.py", line 721, in add_library
    add_library(system_libs_map[d])
  File "C:\emsdk\emscripten\1.38.30\tools\system_libs.py", line 721, in add_library
    add_library(system_libs_map[d])
  File "C:\emsdk\emscripten\1.38.30\tools\system_libs.py", line 715, in add_library
    libfile = shared.Cache.get(name, do_create)
  File "C:\emsdk\emscripten\1.38.30\tools\cache.py", line 127, in get
    temp = creator()
  File "C:\emsdk\emscripten\1.38.30\tools\system_libs.py", line 713, in do_create
    return lib.create(name)
  File "C:\emsdk\emscripten\1.38.30\tools\system_libs.py", line 422, in create_compiler_rt
    shared.Building.emar('cr', in_temp(libname), o_s)
  File "C:\emsdk\emscripten\1.38.30\tools\shared.py", line 2268, in emar
    run_process(cmd, stdout=stdout, stderr=stderr, env=env)
  File "C:\emsdk\emscripten\1.38.30\tools\shared.py", line 174, in run_process
    result.check_returncode()
  File "C:\emsdk\emscripten\1.38.30\tools\shared.py", line 154, in check_returncode
    raise Py2CalledProcessError(returncode=self.returncode, cmd=self.args, output=self.stdout, stderr=self.stderr)
tools.shared.Py2CalledProcessError: Command '['C:/emsdk/python/2.7.13.1_64bit/python-2.7.13.amd64/python.exe', 'C:\\emsdk\\emscripten\\1.38.30\\emar.py', 'cr', 'R:\\Temp\\emscripten_temp_oazeip\\libcompiler_rt.a', '@R:\\Temp\\emscripten_17qkfo.rsp']' returned non-zero exit status 1
```

Could someone give me some hint on what's going on and/or how to resolve it please? thanks in advance.

**Comment by diegocr** [comment]
Trying to track this down, it seems a blatant bug - or breaking change - within clang's llvm-ar

```bash
$ llvm-ar cr lib.a test_0.o
C:\emsdk\clang\e1.38.30_64bit\llvm-ar.exe: lib.a: function not supported.
OVERVIEW: LLVM Archiver (llvm-ar)

  This program archives bitcode files into single libraries

USAGE: ....
``` 
```bash
$ which llvm-ar
/c/emsdk/clang/e1.38.30_64bit/llvm-ar

$ /c/emsdk/clang/e1.37.21_64bit/llvm-ar cr lib.a test_0.o

$ file lib.a
lib.a: current ar archive
```

So, this makes me wonder if nobody is using clang/emscripten under Windows, otherwise this would have been noticed before i think, and whether i could just downgrade to an older clang or this will cause some weirdness from latest emscripten :-/

**Comment by diegocr** [comment]
...no longer happening with 1.39.7
