### ISSUE TITLE
emcc -v: Exec format error

### ISSUE THREAD

**Issue by LucienXian** [emscripten-core/emscripten#8622]
With the docker image ubuntu:16.04, after install the emsdk, I type the `emcc -v`, it outputs an  errro. How can I fix it?

**type:** 
`emcc -v`
**Ouput:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.31
Traceback (most recent call last):
  File "/home/emscripten/emscripten/1.38.31/emcc.py", line 3308, in <module>
    sys.exit(run(sys.argv))
  File "/home/emscripten/emscripten/1.38.31/emcc.py", line 477, in run
    code = run_process([shared.CLANG_CC, '-v'], check=False).returncode
  File "/home/emscripten/emscripten/1.38.31/tools/shared.py", line 163, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error

**type:**
`file /home/emscripten/clang/e1.38.31_64bit/clang++`
**Output:**
`home/emscripten/clang/e1.38.31_64bit/clang++: Mach-O 64-bit x86_64 executable`

**Comment by sbc100** [comment]
Oh.. you somehow installed the Mac version of clang "Mach-O" is the mac binary format.

**Comment by sbc100** [comment]
Did you perhaps run the emsdk install command in your mac and them share the contents with docker somehow?

**Comment by LucienXian** [comment]
@sbc100 Yeah, you're right! Thx for your answer!
