### ISSUE TITLE
How to create map binding with std::variant values?

### ISSUE THREAD

**Issue by adam-cyclones** [emscripten-core/emscripten#8682]
consider the following example:

```c++
// A map with a key that is an integer and a value that is either a integer or a string. 
std::map<int, std::variant<int, std::string>> returnMapData () {
  std::map<int, std::variant<int, std::string>> m;
  m[1] = "a string";
  m[2] = 42;
  return m;
}

EMSCRIPTEN_BINDINGS (my_module) {
	register_map<int,  std::variant<int, std::string>>("HolyGrailMapOfAnyValue");
};
```

std::variant is available since c++ 17, it is a useful type allowing multiple potential values, I can use it within my c++ program (thank goodness!), but I get this error with the above example:

```
{ BindingError: _emval_take_value has unknown type NSt3__27variantIJiNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEEEE
    at BindingError.<anonymous> (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:5528:24)
    at new BindingError (eval at createNamedFunction (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:5516:14), <anonymous>:4:34)
    at throwBindingError (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:5546:13)
    at requireRegisteredType (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:7052:11)
    at __emval_take_value (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:7056:14)
    at __ZN10emscripten3valC2IRKNSt3__27variantIJiNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEEEEEOT_ (wasm-function[368]:251)
    at __ZN10emscripten8internal9MapAccessINSt3__23mapIiNS2_7variantIJiNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEEENS2_4lessIiEENS8_INS2_4pairIKiSB_EEEEEEE3getERKSI_RSF_ (wasm-function[359]:89)
    at __ZN10emscripten8internal15FunctionInvokerIPFNS_3valERKNSt3__23mapIiNS3_7variantIJiNS3_12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEENS3_4lessIiEENS9_INS3_4pairIKiSC_EEEEEERSG_ES2_SL_JSM_EE6invokeEPSO_PSJ_i (wasm-function[367]:60)
    at dynCall_iiii (wasm-function[1714]:16)
    at Module.dynCall_iiii (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:8605:40)
  name: 'BindingError',
  message: '_emval_take_value has unknown type NSt3__27variantIJiNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEEEE',
  stack: 'BindingError: _emval_take_value has unknown type NSt3__27variantIJiNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEEEE\n    at BindingError.<anonymous> (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:5528:24)\n    at new BindingError (eval at createNamedFunction (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:5516:14), <anonymous>:4:34)\n    at throwBindingError (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:5546:13)\n    at requireRegisteredType (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:7052:11)\n    at __emval_take_value (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:7056:14)\n    at __ZN10emscripten3valC2IRKNSt3__27variantIJiNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEEEEEOT_ (wasm-function[368]:251)\n    at __ZN10emscripten8internal9MapAccessINSt3__23mapIiNS2_7variantIJiNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEEENS2_4lessIiEENS8_INS2_4pairIKiSB_EEEEEEE3getERKSI_RSF_ (wasm-function[359]:89)\n    at __ZN10emscripten8internal15FunctionInvokerIPFNS_3valERKNSt3__23mapIiNS3_7variantIJiNS3_12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEENS3_4lessIiEENS9_INS3_4pairIKiSC_EEEEEERSG_ES2_SL_JSM_EE6invokeEPSO_PSJ_i (wasm-function[367]:60)\n    at dynCall_iiii (wasm-function[1714]:16)\n    at Module.dynCall_iiii (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:8605:40)' }
{ BindingError: _emval_take_value has unknown type NSt3__27variantIJiNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEEEE
    at BindingError.<anonymous> (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:5528:24)
    at new BindingError (eval at createNamedFunction (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:5516:14), <anonymous>:4:34)
    at throwBindingError (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:5546:13)
    at requireRegisteredType (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:7052:11)
    at __emval_take_value (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:7056:14)
    at __ZN10emscripten3valC2IRKNSt3__27variantIJiNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEEEEEOT_ (wasm-function[368]:251)
    at __ZN10emscripten8internal9MapAccessINSt3__23mapIiNS2_7variantIJiNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEEENS2_4lessIiEENS8_INS2_4pairIKiSB_EEEEEEE3getERKSI_RSF_ (wasm-function[359]:89)
    at __ZN10emscripten8internal15FunctionInvokerIPFNS_3valERKNSt3__23mapIiNS3_7variantIJiNS3_12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEENS3_4lessIiEENS9_INS3_4pairIKiSC_EEEEEERSG_ES2_SL_JSM_EE6invokeEPSO_PSJ_i (wasm-function[367]:60)
    at dynCall_iiii (wasm-function[1714]:16)
    at Module.dynCall_iiii (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:8605:40)
  name: 'BindingError',
  message: '_emval_take_value has unknown type NSt3__27variantIJiNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEEEE',
  stack: 'BindingError: _emval_take_value has unknown type NSt3__27variantIJiNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEEEE\n    at BindingError.<anonymous> (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:5528:24)\n    at new BindingError (eval at createNamedFunction (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:5516:14), <anonymous>:4:34)\n    at throwBindingError (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:5546:13)\n    at requireRegisteredType (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:7052:11)\n    at __emval_take_value (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:7056:14)\n    at __ZN10emscripten3valC2IRKNSt3__27variantIJiNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEEEEEOT_ (wasm-function[368]:251)\n    at __ZN10emscripten8internal9MapAccessINSt3__23mapIiNS2_7variantIJiNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEEENS2_4lessIiEENS8_INS2_4pairIKiSB_EEEEEEE3getERKSI_RSF_ (wasm-function[359]:89)\n    at __ZN10emscripten8internal15FunctionInvokerIPFNS_3valERKNSt3__23mapIiNS3_7variantIJiNS3_12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEENS3_4lessIiEENS9_INS3_4pairIKiSC_EEEEEERSG_ES2_SL_JSM_EE6invokeEPSO_PSJ_i (wasm-function[367]:60)\n    at dynCall_iiii (wasm-function[1714]:16)\n    at Module.dynCall_iiii (/Users/acrockett/Code/Lua/lua-wasm/wasm/main.js:8605:40)' }
```

Thanks for any help in advance.

**Comment by acronamy** [comment]
Some notes about implementing this feature

from main.js gluecode
```
function requireRegisteredType(rawType, humanName) {
      var impl = registeredTypes[rawType];
      if (undefined === impl) {
          throwBindingError(humanName + " has unknown type " + getTypeName(rawType));
      }
      return impl;
}
function __emval_take_value(type, argv) {
      type = requireRegisteredType(type, '_emval_take_value');
      var v = type['readValueFromPointer'](argv);
      return __emval_register(v);
}
```

looks like the typename is looked up in registered types. But what is a variant type going to look like?

Given that the return type is `<int, double>` NSt3__27**variantI**J**id**EEE
Given that the return type is `<double, int>` NSt3__27**variantI**J**di**EEE

Should I look to detect variants and somehow dynamically get the correct value, I think it's possible that only basic types could be supported?
