### ISSUE TITLE
runner.py fails with benchmark command on windows

### ISSUE THREAD

**Issue by darkmoon233** [emscripten-core/emscripten#8961]
I try to run the command `python tests/runner.py benchmark` on windows command line, and i got some errors just like
```
tests/runner.py:WARNING: use EMTEST_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
WARNING: no 'numpy' module, HyBi protocol will be slower
WARNING: no 'resource' module, daemonizing is disabled
Test suites:
['test_benchmark']
Running test_benchmark: (39 tests)
(checking sanity from test runner)
shared:INFO: (Emscripten: Running sanity checks)
Running Emscripten benchmarks... [ including compilation | Thu Jul 11 17:12:11 2019 | em: commit 5e5e79df2614c2c043ff15791ce6cf7386e134a9 | llvm: D:/emsdk/emsdk/fastcomp/fastcomp/bin ]
ERROR

======================================================================
ERROR: setUpClass (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 354, in setUpClass
    self.emcc_args += [OPTIMIZATIONS]
AttributeError: type object 'benchmark' has no attribute 'emcc_args'

----------------------------------------------------------------------
Ran 0 tests in 0.279s

FAILED (errors=1) 
```

so i change the file `test_benchmark.py` at 354 line:
` self.emcc_args += [OPTIMIZATIONS]`
to 
` self.emcc_args = [OPTIMIZATIONS]`
because i know someone do it at # 8834. And then,i run the command `python tests/runner.py benchmark`  again.I got some errors like that:
```
tests/runner.py:WARNING: use EMTEST_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
WARNING: no 'numpy' module, HyBi protocol will be slower
WARNING: no 'resource' module, daemonizing is disabled
Test suites:
['test_benchmark']
Running test_benchmark: (39 tests)
(checking sanity from test runner)
shared:INFO: (Emscripten: Running sanity checks)
Running Emscripten benchmarks... [ including compilation | Thu Jul 11 17:17:48 2019 | em: commit 5e5e79df2614c2c043ff15791ce6cf7386e134a9 | llvm: D:/emsdk/emsdk/fastcomp/fastcomp/bin ]
test_base64 (test_benchmark.benchmark) ... ERROR
test_conditionals (test_benchmark.benchmark) ... ERROR
test_copy (test_benchmark.benchmark) ... ERROR
test_corrections (test_benchmark.benchmark) ... ERROR
test_fannkuch (test_benchmark.benchmark) ... ERROR
test_fasta_double (test_benchmark.benchmark) ... skipped 'only running core benchmarks'
test_fasta_double_full (test_benchmark.benchmark) ... skipped 'only running core benchmarks'
test_fasta_float (test_benchmark.benchmark) ... ERROR
test_foreign_functions (test_benchmark.benchmark) ... skipped 'only running core benchmarks'
test_havlak (test_benchmark.benchmark) ... ERROR
test_ifs (test_benchmark.benchmark) ... ERROR
test_life (test_benchmark.benchmark) ... skipped 'only running core benchmarks'
test_linpack (test_benchmark.benchmark) ... ERROR
test_matrix_multiply (test_benchmark.benchmark) ... ERROR
test_memcpy_128b (test_benchmark.benchmark) ... skipped 'only running core benchmarks'
test_memcpy_16k (test_benchmark.benchmark) ... skipped 'only running core benchmarks'
test_memcpy_16mb (test_benchmark.benchmark) ... skipped 'only running core benchmarks'
test_memcpy_1mb (test_benchmark.benchmark) ... skipped 'only running core benchmarks'
test_memcpy_4k (test_benchmark.benchmark) ... skipped 'only running core benchmarks'
test_memops (test_benchmark.benchmark) ... ERROR
test_memset_128b (test_benchmark.benchmark) ... skipped 'only running core benchmarks'
test_memset_16k (test_benchmark.benchmark) ... skipped 'only running core benchmarks'
test_memset_16mb (test_benchmark.benchmark) ... skipped 'only running core benchmarks'
test_memset_1mb (test_benchmark.benchmark) ... skipped 'only running core benchmarks'
test_memset_4k (test_benchmark.benchmark) ... skipped 'only running core benchmarks'
test_native_function_pointers (test_benchmark.benchmark) ... skipped 'only running core benchmarks'
test_native_functions (test_benchmark.benchmark) ... skipped 'only running core benchmarks'
test_primes (test_benchmark.benchmark) ... ERROR
test_primes_nocheck (test_benchmark.benchmark) ... ERROR
test_skinning (test_benchmark.benchmark) ... ERROR
test_zzz_box2d (test_benchmark.benchmark) ... ERROR
test_zzz_bullet (test_benchmark.benchmark) ... ERROR
test_zzz_java_nbody (test_benchmark.benchmark) ... skipped 'only running core benchmarks'
test_zzz_lua_binarytrees (test_benchmark.benchmark) ... ERROR
test_zzz_lua_scimark (test_benchmark.benchmark) ... ERROR
test_zzz_lzma (test_benchmark.benchmark) ... ERROR
test_zzz_poppler (test_benchmark.benchmark) ... ERROR
test_zzz_sqlite (test_benchmark.benchmark) ... ERROR
test_zzz_zlib (test_benchmark.benchmark) ... ERROR

======================================================================
ERROR: test_base64 (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 787, in test_base64
    self.do_benchmark('base64', src, 'decode')
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_conditionals (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 659, in test_conditionals
    self.do_benchmark('conditionals', src, 'ok', reps=TEST_REPS, emcc_args=['-s', 'MINIMAL_RUNTIME=0'])
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_copy (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 578, in test_copy
    self.do_benchmark('copy', src, 'sum:')
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_corrections (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 712, in test_corrections
    self.do_benchmark('corrections', src, 'final:')
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_fannkuch (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 679, in test_fannkuch
    self.do_benchmark('fannkuch', src, 'Pfannkuchen(')
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_fasta_float (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 767, in test_fasta_float
    self.fasta('fasta_float', 'float')
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 764, in fasta
    self.do_benchmark('fasta', src, '')
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_havlak (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 783, in test_havlak
    self.do_benchmark('havlak', src, 'Found', shared_args=['-std=c++11'])
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_ifs (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 623, in test_ifs
    self.do_benchmark('ifs', src, 'ok')
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_linpack (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 798, in test_linpack
    self.do_benchmark('linpack_double', open(path_from_root('tests', 'linpack2.c')).read(), '''Unrolled Double  Precision''', force_c=True, output_parser=output_parser)
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_matrix_multiply (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 884, in test_matrix_multiply
    self.do_benchmark('matrix_multiply', open(path_from_root('tests', 'matrix_multiply.cpp')).read(), 'Total time:', output_parser=output_parser, shared_args=['-I' + path_from_root('tests')])
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_memops (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 481, in test_memops
    self.do_benchmark('memops', src, 'final:', emcc_args=['-s', 'MINIMAL_RUNTIME=0'])
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_primes (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 443, in test_primes
    self.do_benchmark('primes' if check else 'primes-nocheck', src, 'lastprime:' if check else '', shared_args=['-DCHECK'] if check else [], emcc_args=['-s', 'MINIMAL_RUNTIME=0'])
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_primes_nocheck (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 448, in test_primes_nocheck
    self.test_primes(check=False)
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 443, in test_primes
    self.do_benchmark('primes' if check else 'primes-nocheck', src, 'lastprime:' if check else '', shared_args=['-DCHECK'] if check else [], emcc_args=['-s', 'MINIMAL_RUNTIME=0'])
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_skinning (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 779, in test_skinning
    self.do_benchmark('skinning', src, 'blah=0.000000')
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_zzz_box2d (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 935, in test_zzz_box2d
    self.do_benchmark('box2d', src, 'frame averages', shared_args=['-I' + path_from_root('tests', 'box2d')], lib_builder=lib_builder)
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_zzz_bullet (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 954, in test_zzz_bullet
    lib_builder=lib_builder)
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_zzz_lua_binarytrees (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 918, in test_zzz_lua_binarytrees
    self.lua('binarytrees', 'long lived tree of depth')
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 908, in lua
    output_parser=output_parser, args_processor=args_processor)
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_zzz_lua_scimark (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 914, in test_zzz_lua_scimark
    self.lua('scimark', '[small problem sizes]', output_parser=output_parser)
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 908, in lua
    output_parser=output_parser, args_processor=args_processor)
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_zzz_lzma (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 962, in test_zzz_lzma
    self.do_benchmark('lzma', src, 'ok.', shared_args=['-I' + path_from_root('tests', 'lzma')], lib_builder=lib_builder)
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_zzz_poppler (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 1016, in test_zzz_poppler
    lib_builder=lib_builder, skip_native=True)
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_zzz_sqlite (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 967, in test_zzz_sqlite
    self.do_benchmark('sqlite', src, 'ok.', shared_args=['-I' + path_from_root('tests', 'sqlite')], emcc_args=['-s', 'FILESYSTEM=1'], force_c=True)
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

======================================================================
ERROR: test_zzz_zlib (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 927, in test_zzz_zlib
    force_c=True, shared_args=['-I' + path_from_root('tests', 'zlib')], lib_builder=lib_builder)
  File "D:\emsdk\emscripten\tests\test_benchmark.py", line 379, in do_benchmark
    raise Exception('error, no benchmarkers')
Exception: error, no benchmarkers

----------------------------------------------------------------------
Ran 39 tests in 0.403s

FAILED (errors=22, skipped=17)
```
and i got the same errors by vs 2017 command line.
I'm very confused and what can i do to fix it .

**Comment by kripken** [comment]
Sorry about this @darkmoon233 , I have #8834 to fix this but didn't have time to finish it. It should be done now, though, you can apply the one-line change in there (remove the line with `self.emcc_args`) to fix that.

**Comment by darkmoon233** [comment]
I got this project again, and i removed the line `self.emcc_args = [OPTIMIZATIONS]`.but it did’n work.I still got the same errors. Is there anything i ignored?

**Comment by kripken** [comment]
Ah, `Exception: error, no benchmarkers` also means you need to set up a benchmarker. If you have `V8_ENGINE` defined in your `.emscripten` file it will use that. You can also edit the python file to define benchmarkers (search for `V8_ENGINE` in there).

**Comment by darkmoon233** [comment]
i know emsdk\fastcomp\bin has d8.exe and i got a d8.exe by compiling the v8 source code.
I added the path of v8.exe to the windows environmental variable，it didn't make sense.And i changed the .emscripten file like that 
`V8_ENGINE = 'D:/V8/source/v8/out.gn/x64.release/obj/d8.exe',
 it still can't work.
Could you tell me how to add a benchmark to benchmarkers  because i could't find it at the document.
Or anything can help is ok.

**Comment by kripken** [comment]
Some of the relevant code is here:
```python
if V8_ENGINE and V8_ENGINE in shared.JS_ENGINES:
  benchmarkers += [
    EmscriptenBenchmarker(os.environ.get('EMBENCH_NAME') or 'v8', V8_ENGINE),
  ]
```
You basically want that if's condition to be true. So you need to also add the engine to JS_ENGINES. But, you can just replace those lines with this:
```python
benchmarkers += [
  EmscriptenBenchmarker('my_benchmarker', V8_ENGINE),
]
```
That creates and adds a benchmarker called "my_benchmarker" and it uses V8_ENGINE.

**Comment by darkmoon233** [comment]
I replaced 
```python
if V8_ENGINE and V8_ENGINE in shared.JS_ENGINES:
  benchmarkers += [
    EmscriptenBenchmarker(os.environ.get('EMBENCH_NAME') or 'v8', V8_ENGINE),
  ]
```
with
```
benchmarkers += [
  EmscriptenBenchmarker('my_benchmarker', V8_ENGINE),
]
```.
And i change these code in .emscripten file
```
V8_ENGINE = 'D:/emsdk/emsdk/fastcomp/bin/d8.exe'
```
But i still had the same errors.
I know nodejs's core is v8,so i replaced the line while
```
V8_ENGINE = 'C:/Program Files/nodejs/node.exe'
```
**It worked !**And i replaced it by clang,it still worked.
By the way, can emscripten project provides a test or benchmark document?

**Comment by darkmoon233** [comment]
And i have a problem:  what i had test is webassembly or javascript?

**Comment by kripken** [comment]
Yeah, it would be good to document the benchmark suite more - we've just used it internally so far. It would also be good to clean up that python a little. Not sure I'll have time for that myself, but help would be very welcome if you or someone else is interested!

To see if it runs wasm or JS, check the emcc flags passed in the benchmark runner. The default in emcc is wasm, so unless it says `WASM=0` it will be wasm. You can also keep the files around to see them by setting `EMTEST_SAVE_DIR=1` in the env (that's a [general test suite flag](https://emscripten.org/docs/getting_started/test-suite.html#debugging-test-failures)).
