### ISSUE TITLE
error: redefinition of 'SDL_Rect' / clang headers in upstream builds

### ISSUE THREAD

**Issue by yurivict** [emscripten-core/emscripten#9673]
emscripten-1.38.48 fails on FreeBSD:

```
$ em++ base64.cpp  -std=c++11 -O1 -s WASM=1 -o base64.js --bind
...skipped...
cache:INFO: generating system library: libc_rt_wasm.a... (this will be cached in "/home/yuri/.emscripten_cache/wasm-obj/libc_rt_wasm.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "/home/yuri/.emscripten_cache/wasm-obj/generated_struct_info.json" for subsequent builds)
In file included from /tmp/tmplunp5_9x.c:35:
In file included from /usr/local/include/SDL/SDL_events.h:35:
In file included from /usr/local/include/SDL/SDL_mouse.h:32:
/usr/local/include/SDL/SDL_video.h:50:16: error: redefinition of 'SDL_Rect'
typedef struct SDL_Rect {
               ^
/usr/local/lib/emscripten/system/include/SDL/SDL_rect.h:65:16: note: previous definition is here
typedef struct SDL_Rect
               ^
In file included from /tmp/tmplunp5_9x.c:35:
In file included from /usr/local/include/SDL/SDL_events.h:35:
In file included from /usr/local/include/SDL/SDL_mouse.h:32:
/usr/local/include/SDL/SDL_video.h:53:3: error: typedef redefinition with different types ('struct (anonymous struct at /usr/local/include/SDL/SDL_video.h:50:16)' vs
      'struct SDL_Rect')
} SDL_Rect;
  ^
```

**Comment by kripken** [comment]
It's not good that `/usr/local/` appears there - as a cross-compiler, the local system libraries and headers should not be used. What's in that `base64.cpp` file?

**Comment by yurivict** [comment]
> What's in that base64.cpp file?

It's taken from https://github.com/ReneNyffenegger/cpp-base64
One user tried to use it when he's submitted some issue for the port.


----------

```/usr/local/``` is where all packages are installed on BSDs. ```/usr/local/include``` has the ```unwind.h``` supplied by the ```libunwind``` package that ```emscripten``` needs. I likely added that directory so that ```unwind.h``` is satisfied.

**Comment by yurivict** [comment]
You should either use the external libraries (like SDL), which is strongly recommended, or always place your include statements ahead of standard ones if for some reason you have to use bundled versions. But system-supplied versions should always be strongly preferred.

**Comment by kripken** [comment]
Maybe I'm not understanding you, but an emscripten-compiled program should never use local system headers (see notes [here](https://emscripten.org/docs/compiling/Building-Projects.html#configure-may-run-checks-that-appear-to-fail) and [here](https://emscripten.org/docs/getting_started/FAQ.html#why-does-compiling-code-that-works-on-another-machine-gives-me-errors)). The local headers would be different on each system, but the output must be the same so that it can run on the Web. So any use of local system headers can cause problems, as a general rule for cross-compilers like emscripten that don't emit a native local executable.

In that repo it looks like `base64.h` and `base.cpp` only include `<string>` and `<iostream>`. Both of those are fully provided by the emscripten system headers, so it should just work with `emcc`. I tested your command `em++ base64.cpp  -std=c++11 -O1 -s WASM=1 -o base64.js --bind` on that linked repo, and did not get an error, and I verified that it did not use any system headers while doing so (using `EMCC_DEBUG=1` in the env and by passing `-v`). So again, the question is why those `/usr/local` paths appear, that should be fixed.

**Comment by yurivict** [comment]
> I tested your command em++ base64.cpp -std=c++11 -O1 -s WASM=1 -o base64.js --bind on that linked repo, and did not get an error,

On which OS?

You use ```unwind.h``` but you don't provide it, so I added the system directory include to allow for it to be included. Please advise what would be a better solution to get the ```#include <unwind.h>``` satisfied.

**Comment by kripken** [comment]
I'm on linux, but again, I verified using `EMCC_DEBUG=1` and `-v` that my system headers aren't being used. Perhaps build with those flags and see if they are on your system? Maybe on FreeBSD clang has a bug and it ignores the `-nostdsysteminc` flag which we pass? (you can verify we pass it with `EMCC_DEBUG=1`)

We also do provide `unwind.h`, it's in `./system/lib/libunwind/include/unwind.h` in emscripten. If that header is needed, that one should be used.

If nothing else works, please paste here your full output with `EMCC_DEBUG=1` in the env and `-v` as an argument, maybe the logging can help us figure it out.

**Comment by kripken** [comment]
Also, it would be good to see that logging output when you do not add `unwind.h` and it errors. That is, the full error when it fails to find `unwind.h` may be the quickest way to debug this.

**Comment by yurivict** [comment]
I removed the system include, and  now it fails:
```
$ em++ base64.cpp  -std=c++11 -O1 -s WASM=1 -o base64.js --bind
cache:INFO: generating system asset: is_vanilla.txt... (this will be cached in "/home/yuri/.emscripten_cache/is_vanilla.txt" for subsequent builds)
cache:INFO:  - ok
shared:INFO: (Emscripten: Running sanity checks)
cache:INFO: generating system library: libc.a... (this will be cached in "/home/yuri/.emscripten_cache/wasm-obj/libc.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libcompiler_rt.a... (this will be cached in "/home/yuri/.emscripten_cache/wasm-obj/libcompiler_rt.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc-wasm.a... (this will be cached in "/home/yuri/.emscripten_cache/wasm-obj/libc-wasm.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc++-noexcept.a... (this will be cached in "/home/yuri/.emscripten_cache/wasm-obj/libc++-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc++abi-noexcept.a... (this will be cached in "/home/yuri/.emscripten_cache/wasm-obj/libc++abi-noexcept.a" for subsequent builds)
In file included from /usr/local/lib/emscripten/system/lib/libcxxabi/src/cxa_exception_storage.cpp:14:
/usr/local/lib/emscripten/system/lib/libcxxabi/src/cxa_exception.hpp:19:10: fatal error: 'unwind.h' file not found
#include "unwind.h"
         ^~~~~~~~~~
In file included from /usr/local/lib/emscripten/system/lib/libcxxabi/src/cxa_default_handlers.cpp:19:
/usr/local/lib/emscripten/system/lib/libcxxabi/src/cxa_exception.hpp:19:10: fatal error: 'unwind.h' file not found
#include "unwind.h"
         ^~~~~~~~~~
In file included from /usr/local/lib/emscripten/system/lib/libcxxabi/src/cxa_handlers.cpp:19:
/usr/local/lib/emscripten/system/lib/libcxxabi/src/cxa_exception.hpp:19:10: fatal error: 'unwind.h' file not found
#include "unwind.h"
         ^~~~~~~~~~
1 error generated.
shared:ERROR: '/usr/local/bin/clang++-devel -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=0 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/usr/local/lib/emscripten/system/include/libcxx -Xclang -isystem/usr/local/lib/emscripten/system/lib/libcxxabi/include -Xclang -isystem/usr/local/lib/emscripten/system/include/compat -Xclang -isystem/usr/local/lib/emscripten/system/include -Xclang -isystem/usr/local/lib/emscripten/system/include/libc -Xclang -isystem/usr/local/lib/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/usr/local/lib/emscripten/system/local/include -c -Werror -std=c++11 -Oz -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -fno-exceptions -DNDEBUG -D_LIBCXXABI_HAS_NO_THREADS -D_LIBCXXABI_NO_EXCEPTIONS -DEMSCRIPTEN /usr/local/lib/emscripten/system/lib/libcxxabi/src/cxa_exception_storage.cpp -fno-inline-functions -Xclang -isystem/usr/local/lib/emscripten/system/include/SDL -c -o /tmp/emscripten_temp_6cv_faak/cxa_exception_storage.cpp.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
1 error generated.
shared:ERROR: '/usr/local/bin/clang++-devel -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=0 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/usr/local/lib/emscripten/system/include/libcxx -Xclang -isystem/usr/local/lib/emscripten/system/lib/libcxxabi/include -Xclang -isystem/usr/local/lib/emscripten/system/include/compat -Xclang -isystem/usr/local/lib/emscripten/system/include -Xclang -isystem/usr/local/lib/emscripten/system/include/libc -Xclang -isystem/usr/local/lib/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/usr/local/lib/emscripten/system/local/include -c -Werror -std=c++11 -Oz -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -fno-exceptions -DNDEBUG -D_LIBCXXABI_HAS_NO_THREADS -D_LIBCXXABI_NO_EXCEPTIONS -DEMSCRIPTEN /usr/local/lib/emscripten/system/lib/libcxxabi/src/cxa_default_handlers.cpp -fno-inline-functions -Xclang -isystem/usr/local/lib/emscripten/system/include/SDL -c -o /tmp/emscripten_temp_6cv_faak/cxa_default_handlers.cpp.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
1 error generated.
shared:ERROR: '/usr/local/bin/clang++-devel -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=0 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/usr/local/lib/emscripten/system/include/libcxx -Xclang -isystem/usr/local/lib/emscripten/system/lib/libcxxabi/include -Xclang -isystem/usr/local/lib/emscripten/system/include/compat -Xclang -isystem/usr/local/lib/emscripten/system/include -Xclang -isystem/usr/local/lib/emscripten/system/include/libc -Xclang -isystem/usr/local/lib/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/usr/local/lib/emscripten/system/local/include -c -Werror -std=c++11 -Oz -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -fno-exceptions -DNDEBUG -D_LIBCXXABI_HAS_NO_THREADS -D_LIBCXXABI_NO_EXCEPTIONS -DEMSCRIPTEN /usr/local/lib/emscripten/system/lib/libcxxabi/src/cxa_handlers.cpp -fno-inline-functions -Xclang -isystem/usr/local/lib/emscripten/system/include/SDL -c -o /tmp/emscripten_temp_6cv_faak/cxa_handlers.cpp.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
In file included from /usr/local/lib/emscripten/system/lib/libcxxabi/src/cxa_noexception.cpp:19:
/usr/local/lib/emscripten/system/lib/libcxxabi/src/cxa_exception.hpp:19:10: fatal error: 'unwind.h' file not found
#include "unwind.h"
         ^~~~~~~~~~
1 error generated.
shared:ERROR: '/usr/local/bin/clang++-devel -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=0 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/usr/local/lib/emscripten/system/include/libcxx -Xclang -isystem/usr/local/lib/emscripten/system/lib/libcxxabi/include -Xclang -isystem/usr/local/lib/emscripten/system/include/compat -Xclang -isystem/usr/local/lib/emscripten/system/include -Xclang -isystem/usr/local/lib/emscripten/system/include/libc -Xclang -isystem/usr/local/lib/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/usr/local/lib/emscripten/system/local/include -c -Werror -std=c++11 -Oz -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -fno-exceptions -DNDEBUG -D_LIBCXXABI_HAS_NO_THREADS -D_LIBCXXABI_NO_EXCEPTIONS -DEMSCRIPTEN /usr/local/lib/emscripten/system/lib/libcxxabi/src/cxa_noexception.cpp -fno-inline-functions -Xclang -isystem/usr/local/lib/emscripten/system/include/SDL -c -o /tmp/emscripten_temp_6cv_faak/cxa_noexception.cpp.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/emscripten/tools/system_libs.py", line 55, in run_build_command
    shared.run_process(cmd, stdout=stdout, stderr=stderr)
  File "/usr/local/lib/emscripten/tools/shared.py", line 177, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/local/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/python3.6', '/usr/local/lib/emscripten/em++.py', '-c', '/usr/local/lib/emscripten/system/lib/libcxxabi/src/cxa_exception_storage.cpp', '-o', '/tmp/emscripten_temp_6cv_faak/cxa_exception_storage.cpp.o', '-Werror', '-std=c++11', '-Oz', '-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS', '-fno-exceptions', '-DNDEBUG', '-D_LIBCXXABI_HAS_NO_THREADS', '-D_LIBCXXABI_NO_EXCEPTIONS']' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/emscripten/emcc.py", line 3663, in <module>
    sys.exit(run(sys.argv))
  File "/usr/local/lib/emscripten/emcc.py", line 2058, in run
    extra_files_to_link += system_libs.calculate([f for _, f in sorted(temp_files)] + extra_files_to_link, in_temp, stdout_=None, stderr_=None, forced=forced_stdlibs)
  File "/usr/local/lib/emscripten/tools/system_libs.py", line 1417, in calculate
    add_library(lib)
  File "/usr/local/lib/emscripten/tools/system_libs.py", line 1377, in add_library
    add_library(system_libs_map[d])
  File "/usr/local/lib/emscripten/tools/system_libs.py", line 1373, in add_library
    libs_to_link.append((lib.get_path(), need_whole_archive))
  File "/usr/local/lib/emscripten/tools/system_libs.py", line 310, in get_path
    return shared.Cache.get(self.get_filename(), self.build)
  File "/usr/local/lib/emscripten/tools/cache.py", line 133, in get
    temp = creator()
  File "/usr/local/lib/emscripten/tools/system_libs.py", line 350, in build
    create_lib(out_filename, self.build_objects())
  File "/usr/local/lib/emscripten/tools/system_libs.py", line 344, in build_objects
    run_commands(commands)
  File "/usr/local/lib/emscripten/tools/system_libs.py", line 69, in run_commands
    pool.map_async(run_build_command, commands, chunksize=1).get(999999)
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
subprocess.CalledProcessError: Command '['/usr/local/bin/python3.6', '/usr/local/lib/emscripten/em++.py', '-c', '/usr/local/lib/emscripten/system/lib/libcxxabi/src/cxa_exception_storage.cpp', '-o', '/tmp/emscripten_temp_6cv_faak/cxa_exception_storage.cpp.o', '-Werror', '-std=c++11', '-Oz', '-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS', '-fno-exceptions', '-DNDEBUG', '-D_LIBCXXABI_HAS_NO_THREADS', '-D_LIBCXXABI_NO_EXCEPTIONS']' returned non-zero exit status 1.
```

It does install ```unwind.h```:
```
$ pkg info -l emscripten | grep unwind.h
	/usr/local/lib/emscripten/system/lib/libunwind/include/libunwind.h
	/usr/local/lib/emscripten/system/lib/libunwind/include/unwind.h
```
But it isn't found for some reason.

**Comment by sbc100** [comment]
It looks like `unwind.h` is normally found as part in clang's builtin include directories.

If you run your underlying compiler `/usr/local/bin/clang++-devel` with `-v` it should print its builtin include path and you should see something like: `/usr/local/llvm-10.0.0/lib/clang/10.0.0/include` in the include path.  This is where the compiler should find unwind.h.

**Comment by sbc100** [comment]
I'm curious how `/usr/local/include/` ended up in your include path in the first place.   Did you modify emscripten to add this?  emscripten runs clang with `-Xclang -nostdsysteminc` which means that the system includes should be visible, but the compiler builtin includes should still be.

**Comment by yurivict** [comment]
> I'm curious how /usr/local/include/ ended up in your include path in the first place.

I added it manually, now it is removed, back to the problem of ```unwind.h``` not being found.

**Comment by sbc100** [comment]
> > I'm curious how /usr/local/include/ ended up in your include path in the first place.
> 
> I added it manually, now it is removed, back to the problem of `unwind.h` not being found.

Our of curiosity how did you add it manually.   Did you modify emscripten itself?  Or set some environment variable?  (I only ask because the files being compiled should not be effected by what you pass on the command line).

**Comment by yurivict** [comment]
> Our of curiosity how did you add it manually. Did you modify emscripten itself?

I patched tools/shared.py, added ```-I${LOCALBASE}/include``` after ```'-target', get_llvm_target()```.

**Comment by sbc100** [comment]
OK, thanks for the explanation.  

Can you see why your compilers's builtin unwind.h is not being found?  (what does running the compiler -v produce?)

**Comment by yurivict** [comment]
```
$ em++ -v 
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.0
clang version 10.0.0 
Target: x86_64-portbld-freebsd12.0
Thread model: posix
InstalledDir: /usr/local/llvm-devel/bin
shared:INFO: (Emscripten: Running sanity checks)
```

No, I don't know why the builtin isn't found.

There's one available in the system:
```
$ find /usr/include/ -name unwind.h
/usr/include/c++/v1/unwind.h
```

**Comment by sbc100** [comment]
Sorry, you need to give it some C source to compile to that it prints the include path>

Something like: `/usr/local/bin/clang++-devel -v -c tmp.c`

You could also add `-Xclang -nostdsysteminc` and `--target wasm32`.   In all cases you should see a clang/X.X.X path in there.

**Comment by yurivict** [comment]
```
$ /usr/local/bin/clang++-devel -v -c base64.cpp 
clang version 10.0.0 
Target: x86_64-portbld-freebsd12.0
Thread model: posix
InstalledDir: /usr/local/llvm-devel/bin
 "/usr/local/llvm-devel/bin/clang-cpp" -cc1 -triple x86_64-portbld-freebsd12.0 -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name base64.cpp -mrelocation-model static -mthread-model posix -mframe-pointer=all -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -v -coverage-notes-file /home/yuri/emscripten/base64.gcno -resource-dir /usr/local/llvm-devel/lib/clang/10.0.0 -internal-isystem /usr/include/c++/v1 -fdeprecated-macro -fdebug-compilation-dir /home/yuri/emscripten -ferror-limit 19 -fmessage-length 173 -fobjc-runtime=gnustep -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -faddrsig -o base64.o -x c++ base64.cpp
clang -cc1 version 10.0.0 based upon LLVM 10.0.0svn default target x86_64-portbld-freebsd12.0
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/v1
 /usr/local/llvm-devel/lib/clang/10.0.0/include
 /usr/include
End of search list.
```

**Comment by sbc100** [comment]
Does `unwind.h` exist in ` /usr/local/llvm-devel/lib/clang/10.0.0/include`.   That is where emscripten normally expects to find it.

**Comment by yurivict** [comment]
No ```unwind.h``` in ```/usr/local/llvm-devel/lib/clang/10.0.0/include```.

**Comment by kripken** [comment]
@sbc100 do we really depend on finding `unwind.h` in the local system clang install? Shouldn't it be found in the emscripten tree?

**Comment by sbc100** [comment]
I don't see why we shouldn't depend on it, given that its part of clang and we depend on clang.  This is the first time we've heard reports of somebody using a copy of clang doesn't does't include this.  We need to figure out its possible to install clang without this file.

@yairlev what files do you have in `/usr/local/llvm-devel/lib/clang/10.0.0/include`?  Do you build the copy of llvm-devel yourself? Or is it part of freebsd?

**Comment by yurivict** [comment]
> what files do you have in /usr/local/llvm-devel/lib/clang/10.0.0/include? Do you build the copy of llvm-devel yourself? Or is it part of freebsd?

It is built from the port, which is built from the llvm sources.

**Comment by sbc100** [comment]
Can you link to the port?  How it is built?  I'm curious how you end up without that include.  What other includes are in that directory?

**Comment by kripken** [comment]
@sbc100 It seems safer to only depend on the clang executable, and to provide headers ourselves. But I see your point too. Perhaps we could add a sanity check for the presence of the clang headers, and issue a clear warning for the case where they are not there?

**Comment by yurivict** [comment]
```unwind.h``` is in the llvm source tree, but it is removed by a port patch and doesn't get installed.

I asked the llbm-devel port maintainer via e-mail why isn't this file installed.

**Comment by sbc100** [comment]
I think we should open a new issue for the unwind.h issue.

**Comment by sbc100** [comment]
Created #9778
