### ISSUE TITLE
Memory access out of bounds 

### ISSUE THREAD

**Issue by 5ut** [emscripten-core/emscripten#9677]
```
index.js:9042 Uncaught RuntimeError: memory access out of bounds
    at _malloc (wasm-function[1201]:0x1b91a4)
    at Module._malloc (http://local.srv/wow/barrens-three/output/index.js:9042:34)
    at arrayToHeap (http://local.srv/wow/barrens-three/output/js/General.js:7:18)
    at WebSocket.ws.onmessage (http://local.srv/wow/barrens-three/output/index.js:960:13)
_malloc
Module._malloc @ index.js:9042
arrayToHeap @ General.js:7
ws.onmessage @ index.js:960
```

I am getting this error after about 30sec - 1min of run time. I have tried every option out there, I have read over the settings.js and tried everything. Nothing is working. 

I've compiled with every optimization, debug information, set the memory size, allowed memory growth, etc. Oddly enough, if I do not compile with atleast -O1 my program becomes so slow that it is unusable and drops this error, over and over again

```
wasm-00ac8262-1827:1 Uncaught RuntimeError: memory access out of bounds
    at _free (wasm-function[1827]:0x245fcc)
    at __ZdlPv (wasm-function[2360]:0x274c23)
    at __ZNSt3__213__vector_baseIhNS_9allocatorIhEEED2Ev (wasm-function[1151]:0x9782f)
    at __ZNSt3__26vectorIhNS_9allocatorIhEEED2Ev (wasm-function[1150]:0x97679)
    at __ZN6BufferD2Ev (wasm-function[1355]:0x193730)
    at __ZN6PacketD2Ev (wasm-function[1266]:0x11636f)
    at __ZN9WoWPacketD2Ev (wasm-function[1374]:0x1ce761)
    at __ZN6Socket15serverToHandlerEii (wasm-function[1404]:0x1ec4ec)
    at __ZN10emscripten8internal13MethodInvokerIM6SocketFviiEvPS2_JiiEE6invokeERKS4_S5_ii (wasm-function[1405]:0x1ec5ef)
    at dynCall_viiii (wasm-function[2486]:0x279083)
```

If I compile using -O1 or higher, it will run excellent without errors until a bit later into the program. 

The Buffer class in above stacktrace is from https://github.com/m-byte918/Binary-Reader-Writer

**Comment by dschuff** [comment]
have you tried Address Sanitizer (
https://emscripten.org/docs/debugging/Sanitizers.html)?

**Comment by 5ut** [comment]
Thanks for the response, I didn't know this was a feature. I'll certainly use this in the future. 

However, I have fixed the error. This cryptic stacktrace was actually the result of just my poor coding. 

I would call a reference of a "const std::vector" and my destructor was attempting to run it's destructor when a) it's constant (not 100% sure if I can run it's destructor then), or b) it was private, not allowing access to destroying it's data.

This took me over a month to figure out. I need to sleep.

**Comment by 5ut** [comment]
I managed to certainly reduce this.. it didn't fix this. I'm not sure, I'm entirely out of ideas. Its been months.
