### ISSUE TITLE
SDL2_mixer fails on windows because it uses configure

### ISSUE THREAD

**Issue by mrj0721** [emscripten-core/emscripten#9933]
Anyway, a compilation error occurs.

<pre>
Traceback (most recent call last):
  File "C:\Program Files\emsdk\upstream\emscripten\emconfigure.py", line 61, in <module>
    sys.exit(run())
  File "C:\Program Files\emsdk\upstream\emscripten\emconfigure.py", line 54, in run
    shared.Building.configure(sys.argv[1:])
  File "C:\Program Files\emsdk\upstream\emscripten\tools\shared.py", line 1713, in configure
    run_process(args, stdout=stdout, stderr=stderr, env=env)
  File "C:\Program Files\emsdk\upstream\emscripten\tools\shared.py", line 184, in run_process
    proc = Popen(cmd, *args, **kw)
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 は有効な Win32 アプリケーションではありません。
Traceback (most recent call last):
  File "C:\Program Files\emsdk\upstream\emscripten\emcc.py", line 3681, in <module>
    sys.exit(run(sys.argv))
  File "C:\Program Files\emsdk\upstream\emscripten\emcc.py", line 1960, in run
    compile_source_file(i, input_file)
  File "C:\Program Files\emsdk\upstream\emscripten\emcc.py", line 1942, in compile_source_file
    cmd = get_clang_command([input_file]) + ['-c', '-o', output_file]
  File "C:\Program Files\emsdk\upstream\emscripten\emcc.py", line 1913, in get_clang_command
    args = system_libs.process_args(args, shared.Settings)
  File "C:\Program Files\emsdk\upstream\emscripten\tools\system_libs.py", line 1757, in process_args
    args = port.process_args(Ports, args, settings, shared)
  File "C:\Program Files\emsdk\upstream\emscripten\tools\ports\sdl2_mixer.py", line 53, in process_args
    get(ports, settings, shared)
  File "C:\Program Files\emsdk\upstream\emscripten\tools\ports\sdl2_mixer.py", line 38, in get
    return [shared.Cache.get('libSDL2_mixer.a', create, what='port')]
  File "C:\Program Files\emsdk\upstream\emscripten\tools\cache.py", line 133, in get
    temp = creator()
  File "C:\Program Files\emsdk\upstream\emscripten\tools\ports\sdl2_mixer.py", line 31, in create
    shared.run_process([shared.PYTHON, shared.EMCONFIGURE, configure, '--prefix=' + dist_dir] + formatflags + commonflags + ['CFLAGS=-s USE_VORBIS=1'])
  File "C:\Program Files\emsdk\upstream\emscripten\tools\shared.py", line 188, in run_process
    result.check_returncode()
  File "C:\Program Files\emsdk\upstream\emscripten\tools\shared.py", line 168, in check_returncode
    raise Py2CalledProcessError(returncode=self.returncode, cmd=self.args, output=self.stdout, stderr=self.stderr)
</pre>

emscripten ver,1.39.3

Audio cannot be used in Windows development.
Please correct.

**Comment by kripken** [comment]
Yes, I think this is due to https://github.com/emscripten-core/emscripten/issues/7879#issuecomment-557262416 - we need to rewrite `tools/ports/sdl2_mixer.py` in a generic way (like `sdl2.py` for example), and not to use configure etc. which fails on windows.

If someone tries and has any questions about the ports python code, let me know!

**Comment by sbc100** [comment]
I thunk this already got fixed in #9849.  So it should be part of the next release.

**Comment by sbc100** [comment]
I'm going to mark this as closes, assuming that #9849 fixed it.  If it didn't feel free to re-open.
